### ISSUE TITLE
inline + defaultDate causing an error

### ISSUE THREAD

**Issue by pgunya** [Eonasdan/bootstrap-datetimepicker#1000]
I'm using date picker as calendar (inline: true). But when I also set defaultDate to have it selected in inline calendar then javascript throws an error. Example fiddle: http://jsfiddle.net/vu5vem98/

**Comment by mdular** [comment]
having the same issue

**Comment by ip512** [comment]
It seems that function checking for date validity uses .val() method of associated input field, which doesn't exists in inline mode.
I can make a PR to avoid checking input value in inline mode.

**Comment by ip512** [comment]
In the meantime I found this workaround :
    $(".timepicker-inline").datetimepicker({
            inline: true,
            "format": "H mm",
    }).data("DateTimePicker").date(moment().hour(12).minute(0));

**Comment by dukedelaet** [comment]
Yeah, ^ that's a good time. 

***also, you can just hide the input***
`<input id="dt" class="hidden"/>`

***... and it still shows the same when inline is turned on***
```javascript
  $(function () { 
                    var md = moment().add(1, 'days');
                    var dd = moment().add(3, 'days');
                   
                    $('#dt').datetimepicker({
                        minDate: md,
                        defaultDate: dd,
                        showTodayButton:false,
                        stepping: 30,
                        inline: true,
                        sideBySide: true,
                        showTodayButton: false,
                        keepOpen: true
                    });

```

**Comment by ip512** [comment]
@dukedelaet I prefer your solution :+1:  
Do you think it makes sense to update the documentation and replace div by hidden input ?

**Comment by dukedelaet** [comment]
Maybe. I'm new to this project. 
I think it makes more sense in a forms world, b/c the input is going to carry the value whether it's hidden or not.
