### ISSUE TITLE
Does not work with <input type="date">

### ISSUE THREAD

**Issue by secrettriangle** [Eonasdan/bootstrap-datetimepicker#1001]
http://jsfiddle.net/oa88xcdc/

**Comment by jakezatecky** [comment]
The above fiddle only makes sense for Chrome (and a few [other browsers](http://caniuse.com/#feat=input-datetime)), as it is the only browser that supports `<input type="date">` for now. Unfortunately, this means that the input needs to be reverted to `type="text"`, for this plugin to work in Chrome.

It certainly would be nice to be able to support the semantic `type="date"` input, but Chrome's date picker would probably just confuse the user anyway, as there would be two ways to select a date from a calendar view (clicking the down arrow Chrome displays).

**Comment by Eonasdan** [comment]
see this SO post http://stackoverflow.com/questions/11320615/disable-native-datepicker-in-google-chrome

**Comment by BradRyan** [comment]
I was interested in this for mobile use.  If I'm not mistaken, defining input type date, time, or datetime on an input field will allow users to use native pickers on their phone if available, which is admittedly a better experience on a phone than the bootstrap datetime picker.

Perhaps through some combination of what @Eonasdan recommended I could get this to work?  I'm worried that if I hide the prompt will this also hide the picker that appears on a mobile device?

Also, I'm having trouble with testing this implementation in a time only picker (format: 'LT').  When I try to use input type = 'time', I get the error:
The specified value '08:01 AM' does not conform to the required format.  The format is 'HH:mm', 'HH:mm:ss' or 'HH:mm:ss.SSS' where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.

I can get this picker to work if I set the format option to  'HH:mm', but then I loose the AM/PM picker which I preferred.  Any ideas/thoughts on what I'm trying to do?
