### ISSUE TITLE
Layout issue with calendarWeeks: true

### ISSUE THREAD

**Issue by pgunya** [Eonasdan/bootstrap-datetimepicker#1002]
When picker is used as calendar (inline: true) and calendarWeeks is set to true then controls spacing differs from calendar without weeks.
Please take notice to right and left edges in example: http://jsfiddle.net/0avxc1bo/
Without weeks - finely aligned columns, right and left spacing are equals.
With weeks - columns shifted to the right, bigger left edge, smaller right edge.

**Comment by Eonasdan** [comment]
not sure what to do about this, since the `calendarWeeks` adds another column so it would be expected that the size is different

**Comment by pgunya** [comment]
Yes, size is different, but maybe it's possible to make equal left and right spacing on edges when ```calendarWeeks``` is enabled. Not equal spacing is especially visible when picker is wide and centered on page.
