### ISSUE TITLE
highlight list of dates

### ISSUE THREAD

**Issue by aacanakin** [Eonasdan/bootstrap-datetimepicker#1006]
I have 2 questions;
- Is it possible to highlight a custom list of dates using datetimepicker functions ?
- Is it possible to add custom class to the list of dates using datetimepicker functions ?

if not, how can I handle date highligting (i.e putting a red dot given date) ?

**Comment by Eonasdan** [comment]
this has been requested in #841 (v5 planning). Currently, there isn't an out of the box function for this.

If you use the dev branch, it includes a `data-day-` on the `td` of in the datepicker. Unfortunately, you'll have to do this any time the month view changes.

**Comment by aacanakin** [comment]
Ok then, I'm closing this
