### ISSUE TITLE
HH format shows up in time popup when the format is set to hh

### ISSUE THREAD

**Issue by thilinag** [Eonasdan/bootstrap-datetimepicker#1007]
```javascript
$('#time').datetimepicker({
	format: 'hh:mm'
});
```

http://jsfiddle.net/4xk2o4rp/

![screen shot 2015-04-17 at 3 33 58 pm](https://cloud.githubusercontent.com/assets/218862/7200129/8c2ea0d0-e517-11e4-9f1c-d6de9cc8523f.png)

**Comment by Eonasdan** [comment]
the picker will use HH if you don't include the a/pm selector `a`
