### ISSUE TITLE
Time pop-up always shows time  - 12 AM (i cannot change it) when i set minDate and maxDate

### ISSUE THREAD

**Issue by PaulSh84** [Eonasdan/bootstrap-datetimepicker#1008]
Please see my forked issue:

http://jsfiddle.net/f2j28jh9/

This is my initial code. 
But when i am adding a line more as you can see on this screenshot:

![source](https://cloud.githubusercontent.com/assets/11867456/7207153/04465d4c-e540-11e4-8db7-a9f5af8f2c25.PNG)

Time pop-up opens, no errors displayed, but you cannot change the time(neither hours nor minutes), it's always showing 12 AM. Check the following screenshot:

![stucked](https://cloud.githubusercontent.com/assets/11867456/7207213/6a22d938-e540-11e4-93c3-10785287a4b8.PNG)

When clicking on arrows, time is not changed. 

Can you please advise on this? maybe i need to change code somewhat?

**Comment by PaulSh84** [comment]
I can replicate the same issue on that js fiddle url provided above. 

![on_jsfiddle](https://cloud.githubusercontent.com/assets/11867456/7207587/296d73dc-e543-11e4-953c-96a26f111a44.PNG)

**Comment by Eonasdan** [comment]
why are you setting min/max date on a timer picker anyway?

**Comment by PaulSh84** [comment]
I'd like to disable past time only, so that user could enter dates starting from now on only.

**Comment by Eonasdan** [comment]
can you check the dev branch and see if that makes any difference? It seems like I did some adjusting around this already.

**Comment by PaulSh84** [comment]
It works just fine. 
Thank you

**Comment by PaulSh84** [comment]
still can't disable arrows on start-time and end-time pickers, so that user can't choose time that has already past.

p.s. should i create another issue?
