### ISSUE TITLE
Not working in IE8..please fix it

### ISSUE THREAD

**Issue by nikhil-toobler** [Eonasdan/bootstrap-datetimepicker#1009]
Hi,
The Datetimepicker doesn't working  in IE8..could you please fix it or tell me a solution?

**Comment by Eonasdan** [comment]
you can search through the issues of shivs, polyfills and other hacks to get it work in IE. See also: http://eonasdan.github.io/bootstrap-datetimepicker/Extras/#ie-7 

IE != latest is not supported

**Comment by nikhil-toobler** [comment]
thanks for your reply,,
I'm focusing IE8 so the datetimepicker doesn't show up there, finally I fixed the issue with "<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.1/es5-shim.min.js"></script>" and change "debug: true"..now it's working..but click function is not working when click on the out side of the widget..i tried to fix that from the above link...but nothing happend...please clarify me how use it. 
thanks in advance :)

**Comment by claudchan** [comment]
Any fix on this at the moment?

**Comment by nikhil-toobler** [comment]
yes, I did in my own way :)

**Comment by dalexisv83** [comment]
@nikhil-toobler How?

**Comment by nikhil-toobler** [comment]
@dalexisv83 , Please check my above comment.
