### ISSUE TITLE
viewMode = 'months'

### ISSUE THREAD

**Issue by renathy** [Eonasdan/bootstrap-datetimepicker#1011]
When viewMode = 'months' is choden in datetimepicker, I expect that it allows use to choose only month. However, the real functionality is the following:
- month selection calendar is displayed
- when use chooses any date on calender, then I expect that month is choosen and calendar closes, however, the calendar doesn't close, instead it asks user to choose date (calendar with default viewMode is loaded)

**Comment by Eonasdan** [comment]
the `format` string is what determines what parts of the picker can be used. use `format: 'MM'` if you only want the month to be selectable.
