### ISSUE TITLE
default day start with monday

### ISSUE THREAD

**Issue by rubi** [Eonasdan/bootstrap-datetimepicker#1013]
how to display the first day is moday, but not is sunday.

**Comment by Eonasdan** [comment]
first day of the week is based on the [`local`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#locale). Please include a moment locale file and set the option accordingly

**Comment by saji89** [comment]
I have figured it out, it based on the `locale`, the default locale is `en`, so add the following code, before initialising your date picker:

```js
moment.lang('en', {
    week : {
        dow : 1 // Monday is the first day of the week
    }
});
```

If you;re using some other `locale`, just use the locale sting for the respective locale.

**Comment by ermanisharma** [comment]
Thanks saji89
