### ISSUE TITLE
Can I disable key bindings when the calendar is not shown?

### ISSUE THREAD

**Issue by lbjones** [Eonasdan/bootstrap-datetimepicker#1014]
I'd like the user to be able to change the selected date and time when the calendar is not shown like a normal text field.  The problem is, the key bindings are still in effect even when the calendar is not shown.  Most notably, the left and right arrows will not work, therefore making manual edits very frustrating for the user.

Is this an option that I am missing?

I think good UX would suggest that if manual edits were not expected from the user, then the input field should be made readonly.  All of the examples have this condition.

**Comment by tomws** [comment]
+1

I've burned a few hours trying to figure out what I was doing wrong to make the text field uneditable (for manual input). I'm glad I found your issue!  

We would like to allow adept keyboard users the ability to enter date-times manually - even though most users will prefer the graphical selection.

**Comment by Eonasdan** [comment]
the easiest work around until I can do something about it is to comment out the keybinding options or set it to null

**Comment by nkovacs** [comment]
I came up with this workaround:

```js
$(document).on('dp.show', function(e) {
    var $el = $(e.target);
    var keys = $el.data("__DPKeys");
    if (keys) {
        $el.data("DateTimePicker").keyBinds(keys);
        $el.data("__DPKeys", null);
    }
});

$(document).on('dp.hide', function(e) {
    var $el = $(e.target);
    $el.data("__DPKeys", $el.data("DateTimePicker").options().keyBinds);
    $el.data("DateTimePicker").keyBinds({
        down: function(widget) {
            if (!widget) {
                this.show();
            }
        }
    });
});
```

**Comment by mblandfo** [comment]
That may not be the best workaround since some of the keybinds do have a widget closed behavior: 

```
up: function (widget) {
    if (!widget) {
        return;
    }
    var d = this.date() || this.getMoment();
    if (widget.find('.datepicker').is(':visible')) {
        this.date(d.clone().subtract(7, 'd'));
    } else {
        this.date(d.clone().add(this.stepping(), 'm'));
    }
}
```

**Comment by Delagen** [comment]
Disable at least preventDefault action, it break all other actions that user need to react

**Comment by ToreOlavKristiansen** [comment]
I did this, similar to @nkovacs:
```
.on('dp.show', function () {
                        $(this).data("DateTimePicker").keyBinds($.fn.datetimepicker.defaults.keyBinds);
                    }).on('dp.hide', function () {
                        $(this).data("DateTimePicker").keyBinds({
                            down: function (widget) {
                                if (!widget) {
                                    this.show();
                                }
                            }
                        });
                    });
```
