### ISSUE TITLE
Bootstrap 3 Datetimepicker in pqGrid

### ISSUE THREAD

**Issue by ssathishkumar540** [Eonasdan/bootstrap-datetimepicker#1015]
Please send me a jsfiddle for latest version of bootstrap 3 Datetimepicker inside the pqGrid. It has resolving so many issues in my module. But I can't able give bootstrap 3 inside of the pqGrid. Please send me fiddle for this.

**Comment by Eonasdan** [comment]
I don't have to time to track down issues relating to random third party plugins. Please don't open new issues that are duplicates of your currently open issues.
