### ISSUE TITLE
Datetimepicker IE8 Issue 

### ISSUE THREAD

**Issue by nikhil-toobler** [Eonasdan/bootstrap-datetimepicker#1016]
I'm focusing IE8 version so the datetimepicker doesn't show up there, finally I fixed the issue with "[ES5 shim] (https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.1/es5-shim.min.js)" and change "debug: true"..now it's working..but click function is not working when click on the out side of the widget in all Browsers..I tried to fix that from the "[link] (http://eonasdan.github.io/bootstrap-datetimepicker/Extras/#ie-7)"...but nothing happend... could you please fiddle it .
thanks in advance.

**Comment by Eonasdan** [comment]
As I mentioned in your other, duplicate, issue, IE != latest is not supported. I just don't have time to troubleshoot.
