### ISSUE TITLE
Escaped format sequences should be ignored when setting up picker views

### ISSUE THREAD

**Issue by rexblack** [Eonasdan/bootstrap-datetimepicker#1019]
Thanks for excellent work! 

I encountered the following issue:
With momentjs, a format pattern can contain escaped character sequences that are ignored when formatting the date, such as: 'dddd, DD. MMMM YYYY, HH:mm [Uhr]' (German standard format)

```js
$('#datetimepicker1').datetimepicker({
  locale: 'de',
  format: 'dddd, DD. MMMM YYYY, HH:mm [Uhr]'
});
```
The picker should respect escaped sequences when determining which control views are displayed.
With given example, the picker currently shows 12-hour-selection while textfield displays 24-hour-format (which is correct)

JSFiddle:
https://jsfiddle.net/9vejj26m/2/

**Comment by Eonasdan** [comment]
check the dev branch. I've got a fix in there for this issue.

Pro Tip: you might want to look at Moment's shorthand format strings

**Comment by rexblack** [comment]
Thanks for your quick response. Looking forward to the release fixing the issue.
Shorthand strings are not an option in my case, because i'm generating the format dynamically from a strftime-pattern. But many thanks for the hint.
Best regards, Rafael
