### ISSUE TITLE
Clock view for time

### ISSUE THREAD

**Issue by cimtico** [Eonasdan/bootstrap-datetimepicker#1021]
Would it be possible to integrate a "clock picker" (similar to android's clock) to select the time?
Something similar to:
https://github.com/weareoutman/clockpicker

It would be great if that was possible, since I believe this design is a bit more mobile friendly.
It would be interesting to have the ability to swap between the current design and the clock, but that might be a bit too complicated to handle though.

**Comment by glepretre** [comment]
It would indeed improve the datetimepicker's UX by reducing the number of click/touch required to set a full date :+1: 

@cimtico Have you already used this clockpicker? If so, is it reliable?
I can't find any good competitor to this one on github, do you know one?

**Comment by cimtico** [comment]
Sorry I didn't answer earlier. I haven't used it in a project, so I'm not sure as to how "good" it is. I did some searches looking for clock options, and that was the closest I could find to what I was aiming for in UX terms.

**Comment by Eonasdan** [comment]
closing this since it's already in the works and in the v5 planning issue

**Comment by itfourp** [comment]
Is this still planned for development?
