### ISSUE TITLE
multiple date fields using datetimepicker in one form

### ISSUE THREAD

**Issue by mrdinghy** [Eonasdan/bootstrap-datetimepicker#1026]
I got the datetimepicker that came with the Angle theme from wrapbootstrap (one of the few that has a builtin datetimepicker). I updated the datatimepicker.js, css,  and the moment js to the current version.  

I have a form with the following. The first date text box works wonderfully but the second one is broken. If i change the second field to datetimepicker2 it works fine as well...but is only the time picker . I want the full datetimepicker1 to pop on both fields. 

Thanks..

<code>
<div class="form-group mb">
     <label class="col-sm-2 control-label mb" style="background-color: #ffff00 ">DateTimePicker</label>
     <div class="col-sm-4">
          <div id="datetimepicker1" class="input-group date">
               <input type="text" class="form-control" name="date1">
               <span class="input-group-addon">
                     <span class="fa fa-calendar"></span>
               </span>
          </div>
     </div>
</div>
<div class="form-group mb">
     <label class="col-sm-2 control-label mb" style="background-color: #ffff00 ">Event Start</label>
     <div class="col-sm-4">
           <div id="datetimepicker1" class="input-group date">
                  <input type="text" class="form-control" name="date2">
                  <span class="input-group-addon">
                        <span class="fa fa-calendar"></span>
                 </span>
          </div>
    </div>
</div>
</code>

**Comment by mrdinghy** [comment]
sorry here is the code 
 
    <div class="form-group mb"> 
    <label class="col-sm-2 control-label mb" style="background-color: #ffff00 ">Event Start</label>
    <div class="col-sm-4"> 
    <div id="datetimepicker1" class="input-group date"> 
    <input type="text" class="form-control" name="date1"> 
    <span class="input-group-addon"> 
    <span class="fa fa-calendar"></span> 
    </span>   
    </div> 
    </div> 
    </div> 

    <div class="form-group mb"> 
    <label class="col-sm-2 control-label mb" style="background-color: #ffff00 ">Event End</label> 
    <div class="col-sm-4">
    <div id="datetimepicker1" class="input-group date"> 
    <input type="text" class="form-control" name="date2"> 
    <span class="input-group-addon"> 
    <span class="fa fa-calendar"></span> 
    </span> 
    </div> 
    </div> 
    </div>

**Comment by Eonasdan** [comment]
please post a jsfiddle of your issue. You can use this one http://jsfiddle.net/Eonasdan/0Ltv25o8/ to start out

**Comment by mrdinghy** [comment]
thanks
I see that the current jsfiddle seems to work fine. I have the same three external resources loaded on my page and this same code works but only with the javascript section removed. datetimepicker1 is the full calendar/ and time picker combined but datetimepicker2 is just the time picker, not the calendar view popup. If i include the javascript:
     $('#datetimepicker1').datetimepicker();
    $('#datetimepicker2').datetimepicker();

on the same page ...then nothing works. Its like somewhere datetimpicker2 is defined as the popup with only the time showing. 

This is by far the most frustrating thing ive had to deal with in the last year on javascript issues


thanks if you can help. 
I can get id="datetimepicker1" to work on the first input but not on the second one. How can i reset it to show up on two input boxes??????

**Comment by mrdinghy** [comment]
Still have this problem ....can anyone solve it?
Do i have to go into datepicker.js and create functions for each date field?
i assume 'datetimepicker1' and 'datetimepicker2' are explicitly defined in the js. Can I override them on my html page. I have 4 dates to edit on my form. I don't need the timepicker function (which i think is 'datetimepicker2'

I can't be the only one with this issue, although i may be the dumbest one with it.
Thanks

**Comment by RomeroMsk** [comment]
@mrdinghy, the problem of your HTML from the second post is duplicating ids of divs. You need to set different id for each div, for example: datetimepicker1, datetimepicker2, datetimepicker3, datetimepicker4. And then you can call `$('#datetimepicker1').datetimepicker({/* some options */});`, `$('#datetimepicker2').datetimepicker({/* another options */});` etc. Or use common selector for all, something like this: `$('.input-group.date').datetimepicker({/* some options */});`.

**Comment by iyunusov** [comment]
Improved version of Eonasdan: http://jsfiddle.net/0Ltv25o8/4212/
