### ISSUE TITLE
Readonly input

### ISSUE THREAD

**Issue by balticSD** [Eonasdan/bootstrap-datetimepicker#1028]
Hi,

the  picker does not work on a readonly input field. I want the user Input is forced to the picker and not allow text Input.

     <div class="input-group date input-group-sm">
         <input type="text" class="form-control" readonly>
         <span class="input-group-btn">
            <button class="btn btn-default btn-sm" type="button">
                <i class="fa fa-calendar"></i>
                <span class="caret"></span>
            </button>
          </span>
     </div>

**Comment by j-hudecek** [comment]
According to https://github.com/Eonasdan/bootstrap-datetimepicker/issues/969 for readonly to work you need to create the datepicker with 

    .datetimepicker({
        ignoreReadonly: true
    });
