### ISSUE TITLE
Conext menu opens on input changed

### ISSUE THREAD

**Issue by balticSD** [Eonasdan/bootstrap-datetimepicker#1029]
Hi,
the context menu opens automaticly if the conntent of the related Input field is change external.
I don't think this is right behavior.

For example, I have a button on side of the Input to set the date to next-date.
![unbenannt](https://cloud.githubusercontent.com/assets/8436300/7361292/2429e82c-ed56-11e4-9e81-0cab95b8c0d0.JPG)

**Comment by Eonasdan** [comment]
please post a jsfiddle
