### ISSUE TITLE
nuget package references

### ISSUE THREAD

**Issue by TrabacchinLuigi** [Eonasdan/bootstrap-datetimepicker#1031]
the nuget package should not include bootstrap but require bootstrap official package as required reference

**Comment by Eonasdan** [comment]
Not sure what you mean.

Both packages have references to the bootstrap nuget packages. Neither of them include bootstrap sources files

**Comment by TrabacchinLuigi** [comment]
Sorry my fault i've installed the less package and just noticed it was not depending on bootstrap, and blindly filled a bug ... i need holidays
