### ISSUE TITLE
min/maxDate attribute is not working

### ISSUE THREAD

**Issue by ReAdPT** [Eonasdan/bootstrap-datetimepicker#1032]
First of all, many thanks for your excelent work.

I'm facing a problem with min/maxDate attribute. If I set using the js, is ok, but using attributes, doesn't work :(

**Working code**:
```
<input type='text' class="form-control" id='@(datetimePickerId)' name="datetimepicker" 
data-date-format="YYYY-MM-DD HH:mm"/>
```
```javascript
$("input[name='datetimepicker']").datetimepicker({maxDate: "4/28/2015"});
```
**NOT working code**:
```
<input type='text' class="form-control" id='@(datetimePickerId)' name="datetimepicker" 
data-date-format="YYYY-MM-DD HH:mm" data-date-maxDate="4/28/2015"/>
```
```javascript
$("input[name='datetimepicker']").datetimepicker();
```
Many thanks for the support.

**Comment by Eonasdan** [comment]
that might have to be `data-date-max-date` or `data-date-maxdate`

**Comment by ReAdPT** [comment]
Many thanks for the fast answer.

I use ```data-date-max-date```, the ```data-date-maxdate``` doesn't work.
