### ISSUE TITLE
Limit datepicker functionality

### ISSUE THREAD

**Issue by diosney** [Eonasdan/bootstrap-datetimepicker#1033]
Hi,

I searched through the docs and didn't found any related option to limit the below functionality on the datepicker:

- only to display the 'days' viewMode and restrict access to the other views (months and years),
- set the datepicker to a readonly mode, where clicking in any date don't do anything.

I'm using the inline mode.

There is a way to accomplish this? Thanks

**Comment by Eonasdan** [comment]
1) the dp uses `format` to determine what options are available.

2) not sure why you would want to set readonly on the inline picker
