### ISSUE TITLE
How to remove current date and time

### ISSUE THREAD

**Issue by ssathishkumar540** [Eonasdan/bootstrap-datetimepicker#1034]
I am using Bootstrap datetimepicker version 2.1.0.   Here I am facing one problem, If I click picker icon calendar is open but without selecting any date if I click outside, it is taking current date and time. How can I resolve this? I want the following things,

    1) Don't want to display current date and time.

    2) After selecting date or time from the calendar only, the selected date or time shuold display in textbox.

    3)  If I select date first time from the calendar means I want to display date and time as, selected date and time as "00:00",   

                       "29/04/2015 00:00"   like this I want display.

    4) Won't affect existing records. Means the previous date and time is "28/04/2015 11:20", if I update this date as 26 instead of 28, the date only will change. Here time should be "11:20" only. Here I won't display time "00:00".

**Comment by Eonasdan** [comment]
version 2?! The docs for v2 are still [here](http://eonasdan.github.io/bootstrap-datetimepicker/version2/). v2 is very limited since it didn't include moment. Please refer the docs or upgrade to the latest
