### ISSUE TITLE
Incorrect positionof popup when the datetimepicker place on the bottom of the screen.

### ISSUE THREAD

**Issue by thearabbit** [Eonasdan/bootstrap-datetimepicker#1036]
I have multiple text box on my form, and the datetimepicker is on the bottom of the form (bottom of screen).
So when i focus on this, it show the popup date on the top of form/screen that so far with datetimepicker of text box (I think that, it don't have free space for display because it is nearly of bottom of screen).
How to solve this???

**Comment by jmartinm** [comment]
I have seen the same issue. If the input is a the bottom of the screen and there is no space for the datepicker dropdown, the datepicker will appear far down in the page out of place.

![screenshot 2015-05-06 11 19 27](https://cloud.githubusercontent.com/assets/580727/7490563/edcf2ce6-f3e1-11e4-8d04-4f7345490a4f.png)

**Comment by Eonasdan** [comment]
the picker will be positioned at the closest element with a `position: relative;`.

Please post a jsfiddle or a demo page of your setup

**Comment by thearabbit** [comment]
Sorry I'm late, but I try remove the `poistion` It still don't work.
I use bs3 template.

**Comment by thearabbit** [comment]
I tried to install v 3, It work fine.
