### ISSUE TITLE
conflict between datepicker and general bootstrap dropdown button

### ISSUE THREAD

**Issue by havok2063** [Eonasdan/bootstrap-datetimepicker#1038]
Not sure if this is real issue.  I'm trying to build an input group that contains a dropdown button menu + input box + datetimepicker.  Maybe this is solely due to how I've coded things up, but I'm getting a conflict between my dropdown button and the datetimepicker. 

 When I click my dropdown button menu, it also toggles the datetimepicker.  My dropdown button menu is supposed to store a relevant id in a hidden input field, but instead it is storing the results of my datetimepicker.  I think there is confusion between the two because they are both referenced by class dropdown-toggle, and dropdown-menu.  

One thing I've tried is setting date-target='#datemode' on my dropdown button, but this just completely turns off the functionality, so it's stops working.  

Since the div for the datetimepicker isn't created/visible until I select it, how can I get around this problem?    Any ideas or help would be great.  

Here is my code and here is my jsfiddle:  http://jsfiddle.net/gxwLw1zr/1/

		<div class='form-group'>
			<label for='date'>Date</label>
			<div class='input-group date' id='datetimepicker'>
				<div class='input-group-btn'>
					<button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false" id='datebutton'>Before <span class="caret"></span></button>
					<ul class="dropdown-menu" role="menu" id='datemode' aria-labelledby="datebutton">
					  <li><a id='before'>Before</a></li>
					  <li><a id='after'>After</a></li>
					</ul>											
				</div>
				<input type='text' class="form-control input-sm" name='date' placeholder="{{'Date'|filterForm('date',form)}}" value="{{''|filterForm('date',form)}}" id='date'/>
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-calendar"></span>
				</span>
				<input class='hidden' name='datehide' id='datehide' value='before'/>
			</div>	
		</div>

**Comment by Eonasdan** [comment]
try adding [`.datepickerbutton`](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L1854) to the cal icon

http://jsfiddle.net/gxwLw1zr/2/

**Comment by havok2063** [comment]
@Eonasdan 
That fixed it.  Perfect.  Thanks a lot.
