### ISSUE TITLE
datetimepicker in iFrame on Android Internet 1.5.28.

### ISSUE THREAD

**Issue by 41GitHub** [Eonasdan/bootstrap-datetimepicker#1039]
Any suggestions on how to get the picker to fit in this iFrame? It appears to work fine on other Android and iOS browsers. 

Android Internet 1.5.28.
![image](https://cloud.githubusercontent.com/assets/8295590/7426609/a804869a-ef8e-11e4-8f30-54e7aaef4084.png)

**Comment by Eonasdan** [comment]
you could try inline, but I'm not sure what else you could do.
