### ISSUE TITLE
Datetimepicker is not showing correctly on Bootstrap table-responsive

### ISSUE THREAD

**Issue by h-morales** [Eonasdan/bootstrap-datetimepicker#1040]
I have a table wrapped with .table-responsive class. Inside the table is an entry form with a datetimepicker. When you click the datetimepicker, the widget does not float outside the responsive table.

**Comment by Eonasdan** [comment]
please provide a jsfiddle of your issue

**Comment by Petercopter** [comment]
@h-morales I'd recommend looking into tables and positioning. They do not work together, and I believe that's at least part of the problem.

I would recommend using `widgetParent` to have the body as the parent.
