### ISSUE TITLE
Update UI if date is changed programmatically

### ISSUE THREAD

**Issue by mouse0270** [Eonasdan/bootstrap-datetimepicker#1044]
I am using the date picker on three fields. One for the date of a class, one for the date when users can start signing up for the class and one for the date which users can no longer sign up. So for example if the class was on `05/29/2015` users could sign up between `05/01/2015` and `05/28/2015`

I have the date picker working and the min and max dates working all just fine. The problem is when the user selects the start date I programmatically set the default date of the close registration to the day before the day of the class using the code below:

``` javascript
$classDate.on("dp.change", function (e) {
	$closeDate.data("DateTimePicker").date(moment(e.date).subtract(1, 'day'));
	$closeDate.find('input').val(moment(e.date).subtract(1, 'day').format('MM/DD/YYYY'));

	$closeDate.data("DateTimePicker").maxDate(moment(e.date).subtract(1, 'day'));
});
```

This makes it so it appears right on the screen but if someone clicks on the `$closeDate` calendar icon they are presented with the date was selected before I programmatically changed it.

Is there a way to update the calendar so that if I change the date in code it would show the correct selected date when someone goes to change that date?

**Comment by Eonasdan** [comment]
the [dev branch](https://github.com/Eonasdan/bootstrap-datetimepicker/tree/development) allow you to set the `viewDate`, which is probably what you're looking for

**Comment by mouse0270** [comment]
Okay, I'll have to look into it because I just noticed this is causing an issue with my min/max dates because it is still using the old ones and not the newest ones.

**Comment by mouse0270** [comment]
I modified the code so now it looks like this http://jsfiddle.net/arLofn9m/

The problem now seems to be that it isn't updating the min/max dates anymore. I do understand this is a development build though and may not work correctly.

**Comment by mouse0270** [comment]
I solved all my problems. Thank you!
