### ISSUE TITLE
No Icon (input field only) doesn't close the calender after a date is chosen

### ISSUE THREAD

**Issue by tianxu0836** [Eonasdan/bootstrap-datetimepicker#1047]
it doesn't close the calender after I pick on a date.

**Comment by Eonasdan** [comment]
if you are also using the time picker it won't auto close. It will close on a `blur` event though

**Comment by tianxu0836** [comment]
I see, I using this way
$('#datetimepicker2').datetimepicker({format:"MM/DD/YYYY"})
so that the time picker is not visible now.
however, after I pick a date and click on the input again, it doesn't show the calender I still have to click outside

**Comment by Eonasdan** [comment]
this is similar to #1069 I'm planning on adding a `blur` to the input on hide
