### ISSUE TITLE
There is no way to hide the header?

### ISSUE THREAD

**Issue by tianxu0836** [Eonasdan/bootstrap-datetimepicker#1048]
For month only case I want to hide the header so that user can only choose month from Jan to Dec.

**Comment by Eonasdan** [comment]
if you just want to allow the user to select a month, use the `format` option like this: `format: 'MM'`

**Comment by tianxu0836** [comment]
Yes, I'm doing that, but I want to hide the top bar so that user can't go to next year. because it is a month picker

**Comment by Eonasdan** [comment]
then set `min/max` to the last day of last year and the first day of next

**Comment by tianxu0836** [comment]
that will work but needs to take care of the calculation, if there is a
setting to hide it will be nice tho.

**Comment by Eonasdan** [comment]
`maxDate: moment().endOf('year').add(1,'d')`
