### ISSUE TITLE
Problem with the inline mode - it's not possible select Saturday days

### ISSUE THREAD

**Issue by oaki** [Eonasdan/bootstrap-datetimepicker#1049]
There is a padding over all Saturday days and also over the arrow (next month). Then is not clickable. I tested it on chrome here http://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by compcentral** [comment]
I'm also seeing this issue.

**Comment by compcentral** [comment]
Adding the following to bootstrap-datetimepicker.css should resolve the problem.  The issue was with the size of the col divs....

.timepicker{
	min-width: 228px;
}
.datepicker{
	min-width: 240px;
}

**Comment by compcentral** [comment]
Or... possibly another solution...

I changed .timepicker to col-sm-5 and that seems to be fine.  makes the control a bit smaller which I liked.  Here is the code to change:

    return d.inline&&b.removeClass("dropdown-menu"),f&&b.addClass("usetwentyfour"),d.sideBySide&&z()&&y()?(b.addClass("timepicker-sbs"),b.append(a("<div>").addClass("row").append(c.addClass("col-sm-6")).append(e.addClass("col-sm-5"))),b.append(h),b):("top"===d.toolbarPlacement&&g.append(h),z()&&g.append(a("<li>").addClass(d.collapse&&y()?"collapse in":"").append(c)),"default"===d.toolbarPlacement&&g.append(h),y()&&g.append(a("<li>").addClass(d.collapse&&z()?"collapse":"").append(e)),"bottom"===d.toolbarPlacement&&g.append(h),b.append(g))},F=function(){var b,e={};

**Comment by Eonasdan** [comment]
the real issue is how the docs are laid out, which I've fixed
