### ISSUE TITLE
How about add support for persian(Jalali) calendar?

### ISSUE THREAD

**Issue by elenorgt500** [Eonasdan/bootstrap-datetimepicker#1052]
Hello

Can Any One Help Me To add support for persian(Jalali) calendar ? 
Like This : 
https://github.com/smalot/bootstrap-datetimepicker/issues/116

**Comment by arminjgh** [comment]
I have the same issue please help

**Comment by Eonasdan** [comment]
locale support is handled by [momentjs](https://github.com/moment/moment/tree/develop/locale). I'd suggest looking at an existing local file and change it to your needs. If you make a file, you should submit it to moment so that others can benefit from it

**Comment by elenorgt500** [comment]
no, local support only change it,s language to persian, i need to change date to jalali (shamsi).
in top link available it,s convertor to jalali date, but only work in bootstrap-datetimepicker.js, it no work in moment.js

can you help me to how change date to jalalidate ?

thanks.

**Comment by maghari** [comment]
Hi,
I Have the same issue, 
the Persian calendar system (jalali) is deferent from Georgian system. 
I found moment.js convertor to jalali here: https://github.com/jalaali/moment-jalaali
this works fine!
please let me know how can i use "moment-jalali" to this component?

I have a suggestion to add new option as "Calendar" to "bootstrap-datetimepicker" new version 5 to change by calendar systems and develope famous calendar systems like jalali (https://github.com/jalaali/moment-jalaali ), hijri (https://github.com/xsoh/moment-hijri) etc.

thanks,
Alireza

**Comment by ghominejad** [comment]
+1
