### ISSUE TITLE
dp.show event does not work when datetimepicker shows as inline element

### ISSUE THREAD

**Issue by elioncho** [Eonasdan/bootstrap-datetimepicker#1053]
Hello,

I'm implementing the datetimekeeper as an inline element, so I'm trying to store the initial date value on a hidden input, but the dp.show event does not work. It's never been called. I guess its because the datetimepicker element is shown inline (the dp.change works great). Any ideas on how to solve this issue?

**Comment by Eonasdan** [comment]
The show event shouldn't fire for an inline picker since it is already open.
