### ISSUE TITLE
widget width not working correctly

### ISSUE THREAD

**Issue by locito54** [Eonasdan/bootstrap-datetimepicker#1055]
for me the widget with is not working ccorrectly.

here is the JS-Code

<code>
$('#request-edit-dt-pos1-id').datetimepicker({
  locale: "de",
  format: "DD.MM.YYYY HH:mm",
  minDate: new Date()
});
</code>

any idea?

![screenshot](https://cloud.githubusercontent.com/assets/876995/7615021/f788be50-f99a-11e4-9b47-f68c64b3dcd9.png)

**Comment by SharpNoiZy** [comment]
I have the same problem! ;(

**Comment by locito54** [comment]
no ideas?

**Comment by Eonasdan** [comment]
you must have some css overwriting the picker styles.

please post a jsfiddle of your issue

**Comment by tsmith3000** [comment]
I have something similar happening with the width. I don't see anywhere where the css is overwritten in my MVC application...

![2015-07-15 16_13_21-haccp master](https://cloud.githubusercontent.com/assets/2466980/8712076/b28222d0-2b0c-11e5-8253-305e8f3113a2.png)

**Comment by SirRawlins** [comment]
Had similar issues myself this morning. Turns out I was applying a `min-width` to the top-level `.dropdown` class which was breaking the widget.
