### ISSUE TITLE
Class selector is not working

### ISSUE THREAD

**Issue by andresclua** [Eonasdan/bootstrap-datetimepicker#1056]
Guys, could any help me on this?

$('#datetimepicker1').datetimepicker(); -> this is working
$('.datetimepicker1').datetimepicker(); -> not working.

also change
`<div class='input-group date' id='datetimepicker1'>`
to
`<div class='input-group date' class='datetimepicker1'>`

Could anyone help me?

**Comment by Eonasdan** [comment]
basic setup instructions are in the docs: http://eonasdan.github.io/bootstrap-datetimepicker/

if that doesn't help please post a jsfiddle of your issue
