### ISSUE TITLE
Close button in DatetimePicker.

### ISSUE THREAD

**Issue by VigneshPalanisamy** [Eonasdan/bootstrap-datetimepicker#1057]
If there is a close button in DatetimePicker it will be good. because there is no auto close for the picker if it using timepicker.

**Comment by Eonasdan** [comment]
you mean like this: http://eonasdan.github.io/bootstrap-datetimepicker/Options/#showclose?

**Comment by VigneshPalanisamy** [comment]
yes thanks Eonasdan
