### ISSUE TITLE
Making the week numbers selectable 

### ISSUE THREAD

**Issue by santoshgiridhar** [Eonasdan/bootstrap-datetimepicker#1058]
An option to select the week numbers from the datetimepicker.
Currently only calendarWeeks: boolean value can be set to display it but no option to select those numbers or display it.
Or toggle between week and day.

**Comment by andrius-senulis** [comment]
I am also looking for a solution to select a week number in the calendar. It would be a great enhancement for datetimepicker.

**Comment by Kestanous** [comment]
:+1:

**Comment by lipis** [comment]
Yes please..! Can we have that?

**Comment by acucchieri** [comment]
+1

**Comment by schmidtwastl** [comment]
This would be awesome!
