### ISSUE TITLE
add option for format 'view'

### ISSUE THREAD

**Issue by christopheg** [Eonasdan/bootstrap-datetimepicker#1060]
Hi,

The 'format' option defines the way the date/time is shown in the input field and how it will be posted in the form.
I think it could be useful to make a separate option for both.
Ex:
An input field to request a date could post its date in a MySQL datetime format while showing it to the user in his localized preference.

I think this would mean that a new (hidden) input field needs to be created. This field can hold the format that needs to be posted.

Kind regards,
Christophe

**Comment by Eonasdan** [comment]
you can listen for the change event and store the value in a hidden field with whatever format you'd like

**Comment by christopheg** [comment]
Can't you reconsider this? 
I know you can work with the change event, but this has to be implemented for every datetimepicker as the visible format of a date is almost never the Mysql format.
A general option would save us a lot of work.

**Comment by christopheg** [comment]
In JqueryUI, there is a different approach to this problem:
http://api.jqueryui.com/datepicker/#option-altField

Have a look at 'altField' and 'altFormat'.

**Comment by Eonasdan** [comment]
no. see issue #1168. if you want it, fork the rep and make a pr to dev.
