### ISSUE TITLE
Manually setting Date is not working

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [Eonasdan/bootstrap-datetimepicker#1061]
Hi Can you please let me know how to set the date manually. I am getting date() is not a defined function. I am new to javascript to find a way around.

Thanks

**Comment by Eonasdan** [comment]
[`$('#datetimepicker6').data("DateTimePicker").date()`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#date)
