### ISSUE TITLE
calendarWeeks:true - add ability to set first day of the week

### ISSUE THREAD

**Issue by JelmerD** [Eonasdan/bootstrap-datetimepicker#1062]
When I set the `calendarWeeks:true`, I would like to be able to set which day is the first day of the week. Where I live (The Netherlands) that would be monday, whereas other parst of the world use sunday.

So an option like `firstWeekDay` would be nice where the default is `0` (sunday).

**Comment by Eonasdan** [comment]
the start of the week is based on the `locale`, include the proper locale file and set the option, other create a custom local file with the setting you need

**Comment by derwok** [comment]
This works for me:
import moment from 'moment/moment'; 
             moment.locale('en', { 
                week: { dow: 1 } // Monday is the first day of the week 
            }); 

Then configure & launch the datetimepicker afterwards.
