### ISSUE TITLE
set minDate and maxDate on 'dp.change' => $(...).data(...).minDate is not a function

### ISSUE THREAD

**Issue by DigitalCoder** [Eonasdan/bootstrap-datetimepicker#1063]
hello with this code 

{code}

        jQuery('#start_date').datetimepicker({
            language: 'fr',
            //viewMode: 2,
            minDate: new Date(),
            format: "YYYY-MM-DD",
            pickTime: false
        });
        jQuery('#end_date').datetimepicker({
            language: 'fr',
            //viewMode: 2,
            minDate: new Date(),
            format: "YYYY-MM-DD",
            pickTime: false
        });

        jQuery("#start_date").on("dp.change", function (e) {
            console.log("#start_date");
            console.log(e);
            jQuery('#end_date').data("DateTimePicker").minDate(e.date);
        });
        jQuery("#end_date").on("dp.change", function (e) {
            console.log("#end_date");
            console.log(e);
            jQuery('#start_date').data("DateTimePicker").maxDate(e.date);
        });

{code}

I does not work and send error message : 
Uncaught TypeError: jQuery(...).data(...).minDate is not a function
Uncaught TypeError: jQuery(...).data(...).maxDate is not a function

thanks for advance

**Comment by DigitalCoder** [comment]
So, I've found the solution.

In fact when I've called console.log(jQuery('#end_date').data("DateTimePicker")); 
I've seen that the name of the functions to change the value of minDate and maxDate is setMinDate and setMaxDate

Now, my new code is : 
{code}

    jQuery('#start_date').datetimepicker({
        language: 'fr',
        minDate: new Date(),
        format: "YYYY-MM-DD",
        pickTime: false
    });
    jQuery('#end_date').datetimepicker({
        language: 'fr',
        minDate: new Date(),
        format: "YYYY-MM-DD",
        pickTime: false
    });

    jQuery("#start_date").on("dp.change", function (e) {
        jQuery('#end_date').data("DateTimePicker").setMinDate(e.date);
    });
    jQuery("#end_date").on("dp.change", function (e) {
        jQuery('#start_date').data("DateTimePicker").setMaxDate(e.date);
    });

{code}

**Comment by Eonasdan** [comment]
you must be using an older version

**Comment by DigitalCoder** [comment]
true ^^
