### ISSUE TITLE
Use of allowInputToggle function on 4.7.14

### ISSUE THREAD

**Issue by irsm** [Eonasdan/bootstrap-datetimepicker#1064]
Although documentation on site said that "allowInputToggle" function can be used on version 4.7.14, it can't be found on data("DateTimePicker") nether on tests to verify this function.
I'm using minified build of that version and didn't check if there's another function missing.

**Comment by irsm** [comment]
I ended to see now that a "allowInputToggle" option is only available at version 4.13.28 but its respective function "allowInputToggle()" is in 4.7.14. What must be the correct information?

**Comment by Eonasdan** [comment]
it's in the dev branch. the docs are fixed
