### ISSUE TITLE
Can't use minDate with stepping

### ISSUE THREAD

**Issue by ghost** [Eonasdan/bootstrap-datetimepicker#1065]
I can't use minDate: moment() with stepping:15. The problem is the way the stepping is handled. When  for example the time is 19:47, time will be set at 19:45, which is before minDate. This is causing the date to be visually available but not clickable. This problem even persists with defaultDate set at moment().add(1, 'h').

JSFIDDLE: http://jsfiddle.net/xyzd4cs7/

Hacky workaround

JSFIDDLE: http://jsfiddle.net/yojr693g/

minDate: moment().subtract( Math.ceil( stepping / 2 ) )
stepping: stepping

**Comment by devinus** [comment]
I'm currently experiencing this bug as well, however @less-anonymous's workaround does not work for me.

**Comment by BoffinbraiN** [comment]
Same here.

**Comment by WHarris22** [comment]
+1 is this problem still open? @less-anonymous's workaround doesn't seem to work consistently and i'm struggling to find another solution.
