### ISSUE TITLE
disable picking

### ISSUE THREAD

**Issue by raiffeisennet** [Eonasdan/bootstrap-datetimepicker#1068]
is there a way to disable the picking of an inline datepicker during e.g. an ajax call?

**Comment by Eonasdan** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#disable

**Comment by raiffeisennet** [comment]
usign the disable-function:
jQuery('#picker').disable();

gives the error:
Uncaught TypeError: picker.disable is not a function

When i disable the inline datepicker, i won't hide it, i just want to disable all inputs...

**Comment by Eonasdan** [comment]
should be `$('#datetimepicker6').data("DateTimePicker").disable()`
