### ISSUE TITLE
Widget doesn't show on second click with format YYYY-MM-DD

### ISSUE THREAD

**Issue by chanjarster** [Eonasdan/bootstrap-datetimepicker#1069]
Hi, I created a fiddle ( http://jsfiddle.net/chanjarster/r450s3Lg/2/ ) to demonstrate the bug.

Steps of reproducing:

1. create a datetimepicker with format YYYY-MM-DD
2. click the input, widget shows
3. select a day, input updates, widget closes
4. click the input, widget doesn't show

I think there are two ways to solve this:

1. when widge closes, blur the input
2. or, keep the same behavior of format HH:mm. The time picker in the fiddle doesn't close unless you click other place

Thank you very much

**Comment by Eonasdan** [comment]
we can blur the input in a future version. in the meantime, you can set the option `keepOpen` which will keep the picker open until the person clicks off

**Comment by benmarte** [comment]
This also occurs if you use the showClose option and close the datepicker with the close button, the input field retains focus and will not open the date picker when clicked on a second time unless you click outside the input field.

Example can be seen here: http://jsfiddle.net/0Ltv25o8/1193/

**Comment by Eonasdan** [comment]
please check the dev branch
