### ISSUE TITLE
Add way to automatically close picker after selecting

### ISSUE THREAD

**Issue by cool-RR** [Eonasdan/bootstrap-datetimepicker#1071]
I find it annoying that after you pick a datetime in the picker, you need to click somewhere outside of the picker to make it go away. I wish it was possible to do without that. I'd like there to be a setting where, after you pick a date, you're automatically prompted to pick a time, and after you pick a time, the picker automatically disappears.

**Comment by Eonasdan** [comment]
the picker will close automatically if you're not using the time picker. There is no way to know that a user is done with selecting a time. You are welcome to use the `hide` function and `dp.change` event to do this yourself
