### ISSUE TITLE
Set default time in datetimepicker

### ISSUE THREAD

**Issue by Fitzerbirth** [Eonasdan/bootstrap-datetimepicker#1073]
Hi,

I'm using the datetimepicker function for pick date and time,

$('#end').datetimepicker({
  format: 'DD-MM-YYYY HH:mm',
                collapse:false,
               sideBySide:true,
               useCurrent:false,
               showClose:true
  });

It is picking the date with the time 00:00 by default, Is there any way to set the default time value (e.g 23:00)?

![u0-weu-d3-b947b2d6fc14439f06f9982afb4ea6e8 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/7982088/7786901/cbbbe344-0208-11e5-8404-75431bc940bd.jpg)

Thanks

**Comment by Eonasdan** [comment]
in the dev branch you might be able to set the `viewDate`, otherwise you can set the `date`. In either case you will have to set both date and time

**Comment by Fitzerbirth** [comment]
$('#end').datetimepicker({
format: 'DD-MM-YYYY HH:mm',
collapse:false,
sideBySide:true,
useCurrent:false,
showClose:true,
viewDate:'23-04-2015 23:00'
});
it tried like this.but it is not working

**Comment by php-engineer** [comment]
@Fitzerbirth You already found a solution for it? `viewDate` also not working for me.

**Comment by Eonasdan** [comment]
`viewDate` is in the dev branch

**Comment by php-engineer** [comment]
Yes :)

```
"eonasdan-bootstrap-datetimepicker": "https://github.com/Eonasdan/bootstrap-datetimepicker.git#development"
```

Otherwise I would get the error mesage that the option isn't recognized.

**Comment by Eonasdan** [comment]
please post a fiddle of your issue

**Comment by php-engineer** [comment]
http://jsfiddle.net/f4nhwjaw/1/

I would expect that `2015-01-01 23:59:59` is preselected in the picker.

**Comment by steefaan** [comment]
@Fitzerbirth A workaround could be:

```
	$('.datetime-picker').on('dp.change', function(e) {
		if (e.oldDate === null) {
			$(this).data('DateTimePicker').date(new Date(new Date().setHours(23, 59, 59)));
		}
	});
```

**Comment by kriswebdev** [comment]
Proposed workaround above erases the first selected date.

Corrected workaround:

    $('.datetime-picker').on('dp.change', function(e) {
        if (e.oldDate === null) {
            $(this).data('DateTimePicker').date(new Date(e.date._d.setHours(20, 00, 00)));
        }
    });

**Comment by kerubiyan** [comment]
use this 

$('#end').datetimepicker({
 dateFormat: 'yy-mm-dd',
collapse:false,
sideBySide:true,
useCurrent:false,
showClose:true,
hour : '23',
minute :'00'
});

**Comment by ramppt** [comment]
How to set the date for inline bootstrap datetimepicker.  
I used jQuery ('#datetimepicker1').data('DateTimePicker).date('1/10/2017 12:34:24').
Is there any other way to set date and time since it throws error

**Comment by ramppt** [comment]
It's urgent

**Comment by William-H-M** [comment]
@ramppt Please next time debug your code you have horrible error on your code:
`
jQuery ('#datetimepicker1').data('DateTimePicker).date('1/10/2017 12:34:24')`

If you look very closely you have skipped a ' on this `data('DateTimePicker)`

As this a solution given that currently works this will be close and locked
