### ISSUE TITLE
4.13.28 Linked Pickers

### ISSUE THREAD

**Issue by nightkon** [Eonasdan/bootstrap-datetimepicker#1075]
Examples at Plunker:
[v4.1.74 (master branch - stable version)](http://embed.plnkr.co/eynoE9/)
[v4.13.28 (development branch)](http://embed.plnkr.co/jkwLX7U7mbdpLNjlIp2N/)

The Issue happens after opening the calendar "Date from".
After opening, calendar "Date to" automaticly set the minimum date and choose a date that should not happen. In the calendar "Date to" should set only minimum date.

In version 4.1.74 it not happens.

**Comment by Eonasdan** [comment]
both links to the same thing for me. I'm not sure what your issue is

**Comment by nightkon** [comment]
How don't you see this?
When you click at "Date to" [here](http://embed.plnkr.co/eynoE9/) and [here](http://embed.plnkr.co/jkwLX7U7mbdpLNjlIp2N/) you see two different behaviors.
Just click only by the calendar icon on "Date to" and nothing more.
If you don't see it, then I write ver-very detailed for you to understand.

**Comment by nightkon** [comment]
??

**Comment by Eonasdan** [comment]
this isn't really a bug. Set `useCurrent:false` on the "Date From" picker. The reason you are having this issue is because `useCurrent` will automatically move to the closest valid date, which is new in 4.13.

**Comment by nightkon** [comment]
You're right!
With option `useCurrent: false` it works normally!
[See working example](http://run.plnkr.co/plunks/8CQ51xiNuM4p8UEtMdV7/)


**Code, that I use:**
```javascript
$(function () {
  $('#datetimepicker-from').datetimepicker({
    useCurrent: false
  });
  $('#datetimepicker-to').datetimepicker({
    useCurrent: false
  });
  
  $("#datetimepicker-from").on("dp.change", function (e) {
    $('#datetimepicker-to').data("DateTimePicker").minDate(e.date);
  });
  $("#datetimepicker-to").on("dp.change", function (e) {
    $('#datetimepicker-from').data("DateTimePicker").maxDate(e.date);
  });
});
```

**Comment by Eonasdan** [comment]
I'll make sure to make a note of this in the docs thanks for catching this

**Comment by gagarski** [comment]
@Eonasdan 
Currently there is a code on the doc page:
```javascript
    $(function () {
        $('#datetimepicker6').datetimepicker();
        $('#datetimepicker7').datetimepicker({
            useCurrent: false //Important! See issue #1075
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
        });
    });
```

Are you sure that `useCurrent: false` for only one picker is enough? We've experienced same kind of problem and only passing `useCurrent: false` to both pickers solved it.
