### ISSUE TITLE
UI doesn't reflect value of input if value is changed programmatically

### ISSUE THREAD

**Issue by garethdn** [Eonasdan/bootstrap-datetimepicker#1076]
If I was to change the value of an input (with a valid value) using JavaScript I would have expected that the next time I was to open the datepicker that the selected value in the widget would reflect the value in the input. This does not seem to be the case.

In this fiddle i initialize the plugin on two inputs and 1000ms later I programmatically update the value of each. 

http://jsfiddle.net/wekedwjv/7/

1. If you click the date input, you'll see that the wrong month is displayed (June instead of May) and when you navigate to June the selected day is not highlighted.

2. If you click the time input, the selected date is 12:00 AM, not the input value of 04:45 PM.

I'm assuming that this would be the expected behaviour but please correct me if I'm wrong.

**Comment by Eonasdan** [comment]
you should use the `date(newDate)` function instead.

**Comment by garethdn** [comment]
@Eonasdan Sorry but could you elaborate a little on your response? I'm sure I'm missing something fundamental here

**Comment by Eonasdan** [comment]
Use the [`date(newDate)`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#date) function to set the date instead of `val`


    $('#datetimepicker6').data("DateTimePicker").date('06/13/2016')

**Comment by garethdn** [comment]
Great, thanks
