### ISSUE TITLE
showClear breaks the widget

### ISSUE THREAD

**Issue by xDaizu** [Eonasdan/bootstrap-datetimepicker#1077]
I don't know if I'm the clumsiest programmer alive, but as soon as I write something as simple as 

$('#datetimepicker1').datetimepicker({
    showClear: true
});

https://jsfiddle.net/g6b4ftc4/2/

everything stops working. :(

**Comment by Eonasdan** [comment]
your fiddle has console errors. The fiddle on the front page works fine

**Comment by xDaizu** [comment]
Yeah, ok, but I literally just added a documented option to de initialization. What did I do wrong? How are you supposed to initialize a widget instance with clear button?

**Comment by Eonasdan** [comment]
you fiddle has errors because of the scripts you referenced. http://jsfiddle.net/0Ltv25o8/1071/
