### ISSUE TITLE
When will 4.13.28 be released?

### ISSUE THREAD

**Issue by MojoDK** [Eonasdan/bootstrap-datetimepicker#1082]
Hi

I see there's a 4.13.28 (http://eonasdan.github.io/bootstrap-datetimepicker/Version%204%20Changelog/#version-4) ... when will it be released? Thx

**Comment by Eonasdan** [comment]
![image](https://cloud.githubusercontent.com/assets/1006516/8042897/6424afc4-0df0-11e5-84f8-bd08272ebade.png)
