### ISSUE TITLE
Retain empty value if clicked outside of datepicker

### ISSUE THREAD

**Issue by dmytropopov** [Eonasdan/bootstrap-datetimepicker#1083]
Steps to reproduce:
1. Go to http://jsfiddle.net/Eonasdan/0Ltv25o8/
2. Click inside second datepicker. Current datetime is being set for text field.
3. Click outside of datepicker. Current datetime remains in text field. Most other datepickers understand this as 'cancel' action and will keep input empty.

Check the behavior of http://dev.sencha.com/extjs/5.1.0/examples/simple-widgets/editor.html and http://demos.telerik.com/kendo-ui/datepicker/index for example.

Possibly you can introduce some option for enabling/disabling such behavior.

**Comment by Eonasdan** [comment]
you can set `useCurrent: false`

**Comment by dmytropopov** [comment]
Oh thanks, apparently it works. My bad, it wasn't obvious for me.
