### ISSUE TITLE
Implement something like `defaultDate` except doesn't populate field

### ISSUE THREAD

**Issue by cool-RR** [Eonasdan/bootstrap-datetimepicker#1085]
I want to have a datetime picker that, when opened, shows the month January, 1980. I tried using `defaultDate` of `01/01/1980` for this but then it also populates the field with the text `01/01/1980`, which I want to avoid. Is there a way to achieve what I want?

**Comment by Eonasdan** [comment]
The `viewDate` can be set using the dev branch. This won't set the input value

**Comment by cool-RR** [comment]
Stable enough to use currently?

**Comment by Eonasdan** [comment]
yup, a [couple of bugs](https://github.com/Eonasdan/bootstrap-datetimepicker/issues?q=is%3Aopen+is%3Aissue+label%3Abug) nothing to bad though

**Comment by cool-RR** [comment]
Works great! Thanks!
