### ISSUE TITLE
Navigation icons not rendered

### ISSUE THREAD

**Issue by TalalYousif** [Eonasdan/bootstrap-datetimepicker#1086]
hour increment and decrement icons are also not visible

![untitled](https://cloud.githubusercontent.com/assets/10151271/7881968/df668240-0619-11e5-9ace-da4cc674e150.png)

**Comment by Eonasdan** [comment]
Please check for console errors. Do you have bootstraps icons included? If not you will need to change the icon option

**Comment by TalalYousif** [comment]
I added GLYPHICONS Halflings and everything worked just awesomely. Thanks.

Had no idea they are included as fonts!
