### ISSUE TITLE
viewDate

### ISSUE THREAD

**Issue by bjsafdie** [Eonasdan/bootstrap-datetimepicker#1089]
When I click the link to the docs, the Functions topic lists a viewDate() function.  
http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#viewdate

I see no implementation in the source code I pulled from NuGet or in the GitHub repo.
https://raw.githubusercontent.com/Eonasdan/bootstrap-datetimepicker/master/src/js/bootstrap-datetimepicker.js

I tried searching for viewDate and found the internal variable, but did not see the function definition, "picker.viewDate = function(viewDate)...".  Which also explains why I got an error when I tried to use the function.  Did I pull the wrong code?

**Comment by Eonasdan** [comment]
The public viewDate function is in the Dev branch. Check the version numbers next to the functions in the docs
