### ISSUE TITLE
How can I disable time?

### ISSUE THREAD

**Issue by pensiero** [Eonasdan/bootstrap-datetimepicker#1092]
It seems that the options `enabledHours` and `disabledHours` are not found

**Comment by Eonasdan** [comment]
starting with v4 those options where removed. v4 now uses the `format` option to determine which components to display. `format: 'L'` or `format: 'MM/dd/yyyy`. See the moment docs for valid formats

**Comment by pensiero** [comment]
Thanks, I was confused by the old docs
