### ISSUE TITLE
option pickDate is not recognized!  Rails install instructions lead to bug in docs

### ISSUE THREAD

**Issue by TheNotary** [Eonasdan/bootstrap-datetimepicker#1094]
Hey, thanks for this repo, it looks and works great!  I've been jumping back and forth against a million 'not quite right' date time pickers, and I'm settling on this one because it's great, but there's an error in the documentation.  

The inline code (http://eonasdan.github.io/bootstrap-datetimepicker/#inline) isn't compatible with the install procedure for rails (http://eonasdan.github.io/bootstrap-datetimepicker/Installing/#rails).  

The workaround was to use a version other than 4.0.0, I guess the bug was there and now is fixed?  

    gem 'bootstrap3-datetimepicker-rails', '~> 4.7.14'

I actually left mine without a version specification.  Perhaps that rails install just needs to be bumped to that version.  

Thanks again =)

**Comment by Eonasdan** [comment]
this will be fixed when I push the docs out next. Thanks
