### ISSUE TITLE
Setting format to 'DD' doesn't disable month view

### ISSUE THREAD

**Issue by adamgruber** [Eonasdan/bootstrap-datetimepicker#1096]
If I set format option to 'DD', I would expect that the month view would be disabled. However, I am still able to click on the month title and switch views.

**Comment by Eonasdan** [comment]
This is the correct behavior, as it is still possible to select a day in a different month.

If you want to prevent people from leaving the month, use the `min/maxDate` to the `startOf` and `endOf` the current month (+/- 1 day)

**Comment by adamgruber** [comment]
I don't want to prevent people from leaving the month, I just want to disable clicking of the title to show the month view. Users would still be able to get to other months using the left and right arrows.

Basically I'm seeing a formatting issue when I switch to month view so I wanted to disable that view. These images show the issue:

Normal date view
![screen shot 2015-06-04 at 11 48 52 am](https://cloud.githubusercontent.com/assets/2378900/7988138/d854fa0a-0aaf-11e5-80f8-110948dda187.png)

After clicking month title
![screen shot 2015-06-04 at 11 48 59 am](https://cloud.githubusercontent.com/assets/2378900/7988124/d292426c-0aaf-11e5-9831-01f17a4415cf.png)

I know a better solution would be to fix the display bug but in the interim I wondered if there was a way to just disable clicking the title.

**Comment by Eonasdan** [comment]
There must be some css overwriting the monthview styles. This is not how the picker looks normally. You could disable the code or the link, but the better thing to do would be to fix the styles

**Comment by adamgruber** [comment]
I agree, I'll spend some time debugging the styles. Thanks.

**Comment by adamgruber** [comment]
FYI, I had set the `widgetParent` option to the button that I was using to invoke the picker. Removing this option returned all display issues back to normal.

**Comment by Bogatinov** [comment]
Might I ask how have you set to open the datetimepicker on the button click without `widgetParent`?

I have a similar structure using Knockout binding handlers and the same thing happens as above
```
<span class="btn btn-default  btn-center fo fo-calendar" id="calendar-btn"></span>
<input type="hidden" data-bind="dateTimePicker: navigation.currentDate, daysOfWeekDisabled: navigation.daysOfWeekDisabled, widgetParent: 'calendar-btn'" />
```

Another thing, how do you handle when mouse is clicked outside of the calendar? 
I tried some workarounds and it works, but it tries

- Is mouse up outside of widget parent element to hide it
- Is mouse up clicked on the widget parent itself to toggle it
- Is mouse up done for specific widget parent, or `widgetParent = null/$(body)`

The default behavior is correct, but as soon as you set `widgetParent` to a specific element (like above), it stays open when mouse is clicked outside.

**Comment by adamgruber** [comment]
@Bogatinov Honestly at this point I don't recall how I solved the issue and I no longer have access to that codebase to check.
