### ISSUE TITLE
ViewMode Time

### ISSUE THREAD

**Issue by TrabacchinLuigi** [Eonasdan/bootstrap-datetimepicker#1097]
i really miss the possibility to set the calendar format as  'L LT' and make it start in the time view ...

**Comment by Eonasdan** [comment]
I don't understand your question. You **can** set the format to `L LT`.

**Comment by TrabacchinLuigi** [comment]
yes but i want the calendar to start in the time picker mode not the day, in my case the user is probably going to change the time not the day, but he might (rarely) want to.
If i want it to start in time mode the only way i've found is changing the format in let's say 'LT', but then the user can't change the date...

What i miss i a 'time' or 'clock' viewmode

**Comment by Aesthetickz** [comment]
I have the same issue, I want the picker to initially show the time, and then the user can click on the date if he wants to. Please make this possible or give a guide on how to archieve this.

**Comment by Eonasdan** [comment]
Not sure how this can be "misses" since it wasn't in the picker to begin with, but this is planned.

**Comment by Aesthetickz** [comment]
Well in our case users will adjust the time most of the time and the date in more rare occasions. Any tips on how I could 'hack' this feature in for now? Thanks for the fast response.

**Comment by ironman1964** [comment]
@Eonasdan : In version 3.1.3 there were the following options: pickDate: true, pickTime: true,
With those you could show only time or only date picker ... so please incorporate them again.
I'm missing them as well

**Comment by Eonasdan** [comment]
@ironman1964 `pickDate/pickTime` was wrapped into one option: `format`. Please see [the FAQs](http://eonasdan.github.io/bootstrap-datetimepicker/FAQ/#how-do-i-disable-the-date-or-time-element)

**Comment by Aesthetickz** [comment]
@TrabacchinLuigi
I have a temporary solution. 
From line 290:
```javascript
if (!options.sideBySide && hasDate() && hasTime()) {
    row.push($('<td>').append($('<a>').attr({ 'data-action': 'togglePicker', 'title': 'Select Time' }).append($('<span>').addClass(options.icons.time))));
}
```
Change options.icons.time into options.icons.date

From line 339:
```javascript
if (hasDate()) {
    content.append($('<li>').addClass((options.collapse && hasTime() ? 'collapse in' :               '')).append(dateView));
}
if (options.toolbarPlacement === 'default') {
    content.append(toolbar);
}
if (hasTime()) {
    content.append($('<li>').addClass((options.collapse && hasDate() ? 'collapse' : '')).append(timeView));
}
```
Replace 'collapse in' with 'collapse' and vice versa (you need to use the bootstrap collapse plugin for this to work).

**Comment by Jecoms** [comment]
Is this on the table for the next major version? I want to use both starting view modes within the same project, so a built-in option would be great over another ninja patch to the source.

**Comment by ConstantinoSchillebeeckx** [comment]
This is a workaround for the time being:

```
<script type="text/javascript">
    $(function () {
        $('#datetimepicker').datetimepicker({
            // some options
        }).on("dp.show", function() {
            $('[data-action=togglePicker]').click();
        });
    });
</script>
```

Note you may want to adjust the selector `$('[data-action=togglePicker]')` to be specific to that particular picker.
