### ISSUE TITLE
Extending the UI

### ISSUE THREAD

**Issue by DominoDev** [Eonasdan/bootstrap-datetimepicker#1098]
I would like to extend your plugin to include the selection of "Present" as a selectable date.  I am new to JQuery but was able to get this to work by duplicating the todaybutton functionality in the source.  I would prefer to actually extend the plugin instead of modifying it.  I have read several posts about extending and overriding jQuery plugins but I can't seem to get a handle on the getToolbar method to override.  Can you offer any pointers on how I should do this?

**Comment by Eonasdan** [comment]
what do you mean by "selection of "Present" as a selectable date"?

**Comment by DominoDev** [comment]
take a job application form for instance.  When asking for previous employment start and end dates they may still be working for the last employer.  So I would like to add a button that works like the today button but puts a sting in the field that indicates they date range has not ended.

**Comment by Eonasdan** [comment]
ah, ok. Actually, someone just submitted PR #1095 that is in the dev branch that might do what you need it to do.

**Comment by DominoDev** [comment]
I'm not sure if that would address this.  The relative dates are actual dates where as "Present" could not be calculated to a real date.  
![calpicker](https://cloud.githubusercontent.com/assets/1407088/8009347/45cdddec-0b76-11e5-96f4-af5d284060bd.png)

**Comment by Eonasdan** [comment]
I was thinking about this last night, you might be able to set [`keepInvalid: true`](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#keepinvalid). However, in my test both "present" and "current" get translated to the actual date

**Comment by DominoDev** [comment]
look at the datetimepicker.js included in this fiddle http://fiddle.jshell.net/spridemore/ewr5ocz1/  I have updated to include a "Present" button that set the input item to the String "Present" and calls a setValue(false)
