### ISSUE TITLE
Focus out after choosing date

### ISSUE THREAD

**Issue by pensiero** [Eonasdan/bootstrap-datetimepicker#1100]
Now, if I call datetimepicker() directly on an input ([no icon, input field only](https://eonasdan.github.io/bootstrap-datetimepicker/#no-icon-input-field-only)) when I click on a day, the datetimepicker will automatically close (and that's ok), but the input remain in a focused state.

So, if the user click again inside the input, the datetimepicker wont appear (because probably the datetimepicker is triggered onFocus). How can I do?

Thanks

**Comment by olance** [comment]
:+1:

**Comment by olance** [comment]
@pensiero here's a workaround:

```javascript
$('.pub_date').datetimepicker();
$('.pub_date').on('dp.change', function() {
  $(this).blur();
});
```

**Comment by pensiero** [comment]
Thanks a lot @olance!

**Comment by Eonasdan** [comment]
adding a blur event on hide is planned

**Comment by pensiero** [comment]
Thanks @Eonasdan :+1:
