### ISSUE TITLE
Wrong boostrap variables.less path

### ISSUE THREAD

**Issue by atuzovic** [Eonasdan/bootstrap-datetimepicker#1101]
In bootstrap-datetimepicker-build.less this line:
@import "/Content/bootstrap/less/variables.less";

Should be replaced with:
@import "/Content/bootstrap/variables.less";

This issues occurs when latest version of datetimepicker is used with Bootstrap Less 3.3.4:
https://www.nuget.org/packages/Twitter.Bootstrap.Less/

**Comment by Eonasdan** [comment]
thanks I'm hoping to put the dev branch to main. I'll make sure it's fixed there

**Comment by Eonasdan** [comment]
should be fixed 4.14.20 is out now!
