### ISSUE TITLE
Repeated popup of keyboard bar on android

### ISSUE THREAD

**Issue by authentik8** [Eonasdan/bootstrap-datetimepicker#1104]
When trying to interact with the datetimepicker on Android, the keyboard pops up both when the picker is initialised and, if hidden, on every subsequent button press within the picker.

Reproducible on the default JSFiddle (as mentioned in contribution guidelines) when viewed on Android (discovered on HTC One M9)

**Comment by Eonasdan** [comment]
You read the contrib doc!? WOW :+1: 

[`focusOnShow: false`](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#focusonshow) was added to the dev branch. See if that works for you

**Comment by authentik8** [comment]
I try my best! I'm currently using tsega's meteor wrapper for your datetimepicker, so I guess I shall have to check whether that implementation is up to date / has a dev branch.

Thanks!

**Comment by Eonasdan** [comment]
I just pushed the dev branch to the master this week so they can update to the latest. I'm going to close the issue for now. If `focusOnShow` doesn't solve your issue, please create a new comment and I'll reopen this.
