### ISSUE TITLE
z-order issue

### ISSUE THREAD

**Issue by feralanPaladin** [Eonasdan/bootstrap-datetimepicker#1107]
Hi,

I use the date time picker without any icons in a DIV element inside the angular ui grid.
Here is the representation:
 ({div style="position: relative; z-index: 9999;"}{input id="date-time-picker-is-defined-here" /}{/div}) 

But unfortunately, picker is placed under the grid.
Are you planning to support an option like "appendToBody"?

**Comment by Eonasdan** [comment]
You'll have to set the z-index on the widget. What do you mean by append to body

**Comment by feralanPaladin** [comment]
Appending the widget on the body parti of the HTML page solves the
visibility problem, but this time i need to concern with the position of
the widget.
10 Haz 2015 ÖS 5:07 tarihinde "Eonasdan" <notifications@github.com> yazdı:

**Comment by Eonasdan** [comment]
the widget already gets appended to the body but then positions itself to the nearest item with a `position: relative`

**Comment by feralanPaladin** [comment]
So I'll try your z index suggestion and inform you about the issue.
10 Haz 2015 ÖS 9:24 tarihinde "Eonasdan" <notifications@github.com> yazdı:

**Comment by feralanPaladin** [comment]
Setting the widget z-index on the widget's div (with class "bootstrap-datetimepicker-widget") does not solve the problem.

**Comment by Eonasdan** [comment]
well you'll have to set a fiddle or plunker or a demo page or something so I can look at it. I don't know anything about angular.
