### ISSUE TITLE
Bower can't download last stable version (4.14.30)

### ISSUE THREAD

**Issue by nightkon** [Eonasdan/bootstrap-datetimepicker#1108]
[Last specified tag is 4.7.14](https://github.com/Eonasdan/bootstrap-datetimepicker/releases), but stable version is 4.14.30.
- - -
```
bower info eonasdan-bootstrap-datetimepicker
```

shows this:
```
Available versions:
  - 4.7.14
  - 4.0.0
  - 3.1.3
  - 3.1.2
...
```

**Comment by Eonasdan** [comment]
Just created a release, which I forgot to do last night. See if that works

**Comment by nightkon** [comment]
Thank you for you work (new stable version)!
It works!
I've been using this!
- - - -
By the way, I created [the pull-request](https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1112) for the marker in ``td.today``.
Can you look at this?
