### ISSUE TITLE
Change tooltip text

### ISSUE THREAD

**Issue by nkovacs** [Eonasdan/bootstrap-datetimepicker#1110]
Please provide a way to change the tooltips. Moment.js already translated everything in previous versions, but since #916 the tooltips are hardcoded and in English.

**Comment by Eonasdan** [comment]
No moment did not translate the tooltips. I plan to move the text into the icon array, but that will likely have to wait until the need major release

**Comment by nkovacs** [comment]
Moment translated the month and day names, and there was no other text.
Why put it into the icons array? You could add a new option that doesn't require a major release.
