### ISSUE TITLE
keybinds documentation

### ISSUE THREAD

**Issue by nkovacs** [Eonasdan/bootstrap-datetimepicker#1113]
This is wrong:
http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#keybinds

The function is called keyBinds and calling it without a parameter returns nothing and set the keybindings to null. (To get the current keybindings as an object: `$el.data('DateTimePicker').options().keyBinds`)

Also, the documentation of `options.keyBinds` (after the default) is copy-pasted from `keepOpen`
http://eonasdan.github.io/bootstrap-datetimepicker/Options/#keybinds

**Comment by mansouralex** [comment]
I noticed the DOCS says that in the defaults keyBinds

`if (widget.find('.datepicker').is(':visible')) {
                this.date(this.date().clone().subtract(7, 'd'));
            } else {
                this.date(this.date().clone().add(1, 'm'));
            }`

But at the moment when the widget is not visible it's adding 1 week ('w') not 1 month ('m')  as the docs mention.
