### ISSUE TITLE
Possible to fire dp.change event when using picker only as time picker? 

### ISSUE THREAD

**Issue by tulbox** [Eonasdan/bootstrap-datetimepicker#1114]
Is it possible to fire dp.change event when using picker only as time picker? I've got two pickers set to format: 'LT' and want to enforce minTime and maxTime for them like you can set the minDate and maxDate (which could do by setting to today's date and setting maxDate/minDate, but the dp.change event doesn't fire when just change the time).

**Comment by Eonasdan** [comment]
works for me:

```
$('#datetimepicker1').datetimepicker({format: 'LT'});

$('#datetimepicker1').on('dp.change', function (e) {
    alert(e.date.format());
});
```

**Comment by tulbox** [comment]
I had:

    $('.time-picker').datetimepicker(
    {
        ...
        format: 'LT'
    });

    var start = $('#StartTime');
    var end = $('#EndTime');

    if (start.length) {
        start.datetimepicker({
            ...
            format: 'LT'
        });
        start.on('dp.change', function (e) {
            alert(e.date);
            end.data('DateTimePicker').minDate(e.date);
        });
        end.on('dp.change', function (e) {
            alert(e.date);
            start.data('DateTimePicker').maxDate(e.date);
        });
    }
    
Changed to instantiate with #StartTime and #EndTime instead of .date-picker selector and the events now fire. Both elements in question need to be instantiated while via element ID.

**Comment by tulbox** [comment]
Here's what is working for me now. Thanks for confirming that it was me off my rocker.
    
    $('.time-picker').datetimepicker(
    {
        ...
        format: 'LT'
    });

    var start = $('#StartTime');

    if (start.length) {
        var startParent = start.parent('div.input-group');
        var endParent = $('#EndTime').parent('div.input-group');
        startParent.on('dp.change', function (e) {
            endParent.data('DateTimePicker').minDate(e.date);
        });
        endParent.on('dp.change', function (e) {
            startParent.data('DateTimePicker').maxDate(e.date);
        });
    }
