### ISSUE TITLE
How to use callback/function in options like "minDate"???

### ISSUE THREAD

**Issue by thearabbit** [Eonasdan/bootstrap-datetimepicker#1116]
I want to use callback to return value in options like example:
```js
...
issueDate.datetimepicker({
        format: 'YYYY-MM-DD'
        minDate: function(){
            return '2016-06-0-11';
        }
    })
```
But not work, pl help me.

**Comment by Eonasdan** [comment]
[`minDate`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#mindate) does not accept a function. 

It can be set like this though:
`issueDate.data("DateTimePicker").minDate('2016-06-0-11')`

**Comment by thearabbit** [comment]
Oh, thanks for your reply.
Don't have any solution?

**Comment by Eonasdan** [comment]
what do you need a callback function? You can call the `minDate` function to set it at any time

**Comment by thearabbit** [comment]
I use this package in `Meteor JS`.
I need to calculate the mindate, and pass to `datetimepicker`.

**Comment by Eonasdan** [comment]
So do the calculation and call the function...
