### ISSUE TITLE
dp.change is triggered when the widget is initialized and the input has a value

### ISSUE THREAD

**Issue by nkovacs** [Eonasdan/bootstrap-datetimepicker#1118]
When the widget is initialized and the input has a value, it triggers a dp.change event:
http://jsfiddle.net/nkovacs/j3mek9ej/6/

**Comment by Leftyx** [comment]
I am facing the same problem. 
Just upgraded from ver. 3.x to 4.x and I've found out about it.
I cannot even find a workaround as the input box is generated by asp.net mvc.

**Comment by Leftyx** [comment]
This might be a work-around:

```
$(".datetimepicker").on("dp.change", function (e) {
	if (e.oldDate !== null)
	{
	// Do Something!
	}
});
```

```e.oldDate``` is null only the first time.

**Comment by nkovacs** [comment]
I [forked it](https://github.com/nkovacs/bootstrap-datetimepicker) and made the normal change event trigger on the input, because I needed that for third-party code. If the picker is open, it only triggers after it closes, unlike dp.change, which triggers while the user is navigating in the open picker using the keyboard. This worked better for my use case.
