### ISSUE TITLE
detachDatePickerElementEvents detaches wrong focus fuction

### ISSUE THREAD

**Issue by nkovacs** [Eonasdan/bootstrap-datetimepicker#1119]
`attachDatePickerElementEvents` attaches `show` to `'focus'`: https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L1271
but `detachDatePickerElementEvents` tries to detach `hide`: https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L1290

**Comment by Eonasdan** [comment]
please check the dev branch
