### ISSUE TITLE
Add localization support 

### ISSUE THREAD

**Issue by cvsguimaraes** [Eonasdan/bootstrap-datetimepicker#1121]
AFAIK The current locale option is just to select momentjs' locale.
Please add locale support for other strings, like [those in the toolbar](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/development/src/js/bootstrap-datetimepicker.js#L285).

Thanks for this amazing component! :smile:

**Comment by Eonasdan** [comment]
The plan is to move the tooltip text to the icon array or something like that so that it can be customized.

Not sure I'll be able to get this into a v4 release since it might be a breaking change but I've added the comment to the #841 v5 planning issue
