### ISSUE TITLE
Issue with DD-MMM-YYYY type formating

### ISSUE THREAD

**Issue by dudds6699** [Eonasdan/bootstrap-datetimepicker#1122]
Here is the [jsfiddle](https://jsfiddle.net/dudds6699/fhfnb55j/)

Basically what happens is that when you use the mouse it works fine, but when you manually type in a different format IE 25-05-2015 instead of 25-May-2015 which i would expect
i get 25-Jan-2015.

**Comment by Eonasdan** [comment]
you linked to the base fiddle, did you forget to click "update" or "fork"? Also the picker expects the enter date to be in the same format. You can use the `extraFormat` option so that other dates are valid

**Comment by dudds6699** [comment]
Sorry yes i did this one should be the [updated](https://jsfiddle.net/dudds6699/fhfnb55j/)

**Comment by Eonasdan** [comment]
this will work for you:

```
$('#datetimepicker1').datetimepicker({
    format: "DD-MMM-YYYY",
    extraFormats: ['DD-MM-YYYY']
});
```

**Comment by dudds6699** [comment]
This works thank you Sir
