### ISSUE TITLE
Knockout binding handler snippet doesn't work

### ISSUE THREAD

**Issue by Eagle3386** [Eonasdan/bootstrap-datetimepicker#1123]
Hey everyone,

after reading #838, implementing the docs' snippet and trying several suggestions from the referenced issue, I've added my two cents over at https://github.com/Eonasdan/bootstrap-datetimepicker/issues/838#issuecomment-111452978 - but it seems nobody gets notified since the issue was closed a couple of weeks ago.

Therefore I'm opening this issue to seek out for your help. My issue is as follows:

Using the docs from http://eonasdan.github.io/bootstrap-datetimepicker/Installing/#knockout I get:
```PowerShell
Property 'dateTimePicker' does not exist on type 'KnockoutBindingHandlers'
```

Adding a Knockout interface for that (current TypeScript definition for Bootstrap V3 DateTimePicker was written for 3.0.0 and not 4.14.30; BTW: @Eonasdan the changelog at http://eonasdan.github.io/bootstrap-datetimepicker/Changelog/ has a typo: 4.14.**4**0):
```TypeScript
/// <reference path="knockout.d.ts" />

interface KnockoutBindingHandlers {
  dateTimePicker: KnockoutBindingHandler;
}
```
and another fix for:
```PowerShell
Property 'date' does not exist on type 'Datetimepicker'.
```
by modifying **bootstrap.v3.datetimepicker.d.ts** with this:
```TypeScript
line 32 (**interface DatetimepickerOptions**): format?: any;
lines 58-62 (**interface Datetimepicker**):
date(): any;
date(date: any): void;
format(): any;
format(format: any): void;
```
I got the compiler's OK. However, it seems that I've missed something, because having
``` TypeScript
ko.utils.registerEventHandler(element, "dp.change", function(event) {
  var value = valueAccessor();
  console.log(value);
```
doesn't log anything.

Am I missing something? What did I wrong?
Any help would be greatly appreciated!

**Comment by Eonasdan** [comment]
sorry I don't know enough about knockout to help you with this.
