### ISSUE TITLE
calender div is displayed under another div

### ISSUE THREAD

**Issue by ilyasse05** [Eonasdan/bootstrap-datetimepicker#1124]
Hello,
the calender div is displayed under another div can you fix that ?
thanks.

![datetimepicker](https://cloud.githubusercontent.com/assets/10314286/8162283/2676c44e-1374-11e5-830f-b895c6de3604.jpg)

**Comment by Eonasdan** [comment]
check the z-index of the widget and the div that's overlapping.

**Comment by ilyasse05** [comment]
thank you very much.
