### ISSUE TITLE
Unable to render datetime picker controls from within a panel div

### ISSUE THREAD

**Issue by M730-536** [Eonasdan/bootstrap-datetimepicker#1127]
I am unable to render the datetime picker calender control or a time control within a panel div. 

I have created a fork to demonstrate my problem

https://jsfiddle.net/M70_536/j64uLrjd/1/ 

If I move the datetime pickers out of the panel div ~ everything works perfectly.

Here is an example of what I am seeing in my browsers (IE11, Chrome and Firefox). 

![datetimepicker 16 06 2015](https://cloud.githubusercontent.com/assets/12914450/8187653/4d17f37e-1451-11e5-807b-d1e9fce0a477.PNG)

If I change the div class from 

div class="panel panel-primary"

to 

div class="panel"

then I am able to see the following 

![datetimepicker 16 06 2015 panel](https://cloud.githubusercontent.com/assets/12914450/8187724/bffb002a-1451-11e5-8ed0-dcca95757c4e.PNG)

 but then I lose the color and formatting of the panel and the calender control has lost its color formatting too.  

Can you help me / point me in the right direction as to what I should do to fix this issue? 

I think the work you have done with this control is fantastic and I'd really like to use it in a current solution I am working on. 

Thanks very much in anticipation.

**Comment by Eonasdan** [comment]
You've got everything stuff into `panel-heading`, it should go into `panel-body`. I'd suggest reading the bootstrap docs on panels http://getbootstrap.com/components/#panels-heading

Also, you don't need separate doc ready functions in your javascript.

Also, you should probably read up on how `input-groups` are supposed to work: http://getbootstrap.com/components/#input-groups

**Comment by M730-536** [comment]
Okay, thanks very much for getting back to me.

I will move in to the panel-body. (and will read the docs as you suggest).

**Comment by Eonasdan** [comment]
I'm going to close this issue. If you get it changed and it still doesn't work, just comment and I'll reopen it

**Comment by M730-536** [comment]
Closing the header div and then creating a  panel-body, then moving the date time picker control within the  panel-body works perfectly.

Thanks for your help and an excellent control.
