### ISSUE TITLE
side by side mode, tab over removes calendar and time

### ISSUE THREAD

**Issue by milkandteamedia** [Eonasdan/bootstrap-datetimepicker#1129]
Like the title says,  with my date and time picker in side by side mode within a form.
Tabbing over the form field for the date and time picker causes the calendar and time to be removed.
Even if you don't change the date, just simply tabbing over the form input....
I've tried, keepOpen: true, and collapse: false
I can't seem to get the calendar and time picker while in side by side mode to stay on the page!

Please help

**Comment by Eonasdan** [comment]
Please post a jsfiddle of your issue.
