### ISSUE TITLE
can't press left button in keyboard in the input where bootstrap datetimepicker implemented ?

### ISSUE THREAD

**Issue by ghost** [Eonasdan/bootstrap-datetimepicker#1130]
I have implemented bootstrap datetimepicker in one page 1 year ago. till than now I have a issue that I can't press left button in my input where this plugin implement.

This problem work in Chrome and webkit based browser. in Firefox it's work fine  as expected.

suppose date is  (this is the exact format I used (only date in certain format)
2015/07/07

now I want to change 2015 to 2016.

I need to select 2015 or press left,

in chrome.
1. if press left it's move to the right.
2. if select it will unselect and move cursor to right.

Any fix for this bug ?

**Comment by edy** [comment]
same here. one cannot use the left and right arrow keys. i fount a workaround though. press and hold left, then press right to move right. press and hold right, then press left to move left.

**Comment by mblandfo** [comment]
It would also be nice if Enter would update the date

**Comment by andriysavin** [comment]
I'm wondering if this picker is still supported? This bug basically prevents manual editing of the date/time, and is still open for more than a year!
