### ISSUE TITLE
Button title's localization

### ISSUE THREAD

**Issue by winters-song** [Eonasdan/bootstrap-datetimepicker#1131]
Button's title attribute needs to have localization.
![image](https://cloud.githubusercontent.com/assets/3926769/8202489/1ab368b6-150d-11e5-993e-d2391e0dfe90.png)

**Comment by Eonasdan** [comment]
this has already been brought up and is planned.

**Comment by miguelcobain** [comment]
:+1: Couldn't find a reference to the original issue.
