### ISSUE TITLE
Must be used useCurrent: false if maxDate is lower than current date

### ISSUE THREAD

**Issue by radekdostal** [Eonasdan/bootstrap-datetimepicker#1132]
If I have defined maxDate:

``` javascript
maxDate: (new Date().getFullYear() - 10) + '-12-31'
```

and not defined useCurrent option, the value from maxDate is filled as default value to the input box. Version 4.7.14 is OK but 4.14.30 not.

If I set option

``` javascript
useCurrent: false
```

than everything is OK in 4.14.30.

**Comment by Eonasdan** [comment]
please post a jsfiddle of your issue.

Aside: you're doing way to much work to set the maxDate, since momentjs is required for the library you don't have to use javascript Date :)

**Comment by radekdostal** [comment]
https://jsfiddle.net/2t8jqy0k/17/

**Comment by radekdostal** [comment]
I think that the problem is on [this line](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/v4.14.30/src/js/bootstrap-datetimepicker.js#L1629) in condition date.isAfter(maxDate), because the value of the date object is set to current date and the condition is true. See the picture, where first object is date and second object is maxDate.

![picker](https://cloud.githubusercontent.com/assets/375717/10279161/7c29f946-6b63-11e5-8bdc-c334fc88da44.png)
