### ISSUE TITLE
how to Highlight today?

### ISSUE THREAD

**Issue by sferoze** [Eonasdan/bootstrap-datetimepicker#1133]
Hello,

I was wondering how to set an option to highlight today? Even as the user selects other day on the calendar, I want today to still be highlighted in yellow. 

Like the bootstrap datepicker:

http://bootstrap-datepicker.readthedocs.org/en/latest/options.html

Can this be done already. Is it an option not specified?

**Comment by Eonasdan** [comment]
Each day has `data-day` and a class of `day`. You can highlight whatever days you want this way.

Also "today" has a class of `today`

**Comment by mauricioac** [comment]
Could this info get included in the docs? I was searching on the docs for some time and decided to search in here...
