### ISSUE TITLE
[package.json] moment

### ISSUE THREAD

**Issue by maarekj** [Eonasdan/bootstrap-datetimepicker#1134]
There is an issue in package.json:

    "dependencies": {
        "moment": "~2.8.2",
        ...
    }

Whereas in bower.json there is:

    "dependencies": {
        "moment": ">=2.9.0"
     }

In the first case (package.json), the version 2.9.0 is not valid for pattern ~2.8.2, so with *npm install* we can't get the last version of moment.

We can just fix the issue with

    "moment": "~2.8"

**Comment by Eonasdan** [comment]
every time I update npm I have to change the package name to  `"name": "eonasdan-bootstrap-datetimepicker",` from `"name": "bootstrap-datetimepicker",` since there is already a `bootstrap-datetimepicker` package. Is there any reason not to leave it that way?

**Comment by maarekj** [comment]
I wasn't speaking about the name of package, but about of pattern version of moment

**Comment by Eonasdan** [comment]
I know. I was just asking for your opinion on bower/npm which I know very little about

**Comment by maarekj** [comment]
Like you, I don't know good neither npm nor bower.
Just I use npm for download dependencies of my apps, but I don't know it good.

**Comment by Eonasdan** [comment]
ok. thanks
