### ISSUE TITLE
Split date & time into two fields? Time only

### ISSUE THREAD

**Issue by vinceroni** [Eonasdan/bootstrap-datetimepicker#1138]
I have a requirement that the date be in one field and the time be in another field.
It seems to me that the beauty of your plugin is that these values are combined into one field.
The 'date only' input is working.

Is there an option or options set that would allow us to create a 'time only' input?

**Comment by Eonasdan** [comment]
You can use the [`format`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#format) option and set it to `LT` or any of valid momentjs format string
