### ISSUE TITLE
Set Timezone

### ISSUE THREAD

**Issue by faizanqadri** [Eonasdan/bootstrap-datetimepicker#1140]
I tried alot to set the by default timezone of the datetimepicker but I was unable to do so. Is there any simple way to set the default timezone. I tried following workaround but all were in vain. Kindly help I am really suffering because of this lack of functionality:

moment().utcOffset("8");
moment(1369266934311).zone('+0100').format('YYYY-MM-DD HH:mm');

**Comment by praneethgelli** [comment]
Try this:
https://github.com/praneethgelli/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js

**Comment by Eonasdan** [comment]
TZ support is coming. Unfortunately, it will take a well planned changed and I haven't had time to do it.
