### ISSUE TITLE
component should be placed within a relative positioned container

### ISSUE THREAD

**Issue by Treolorn** [Eonasdan/bootstrap-datetimepicker#1142]
When activated by input focus i have error 'component should be placed within a relative positioned container'

using bootstrap 3, inline form
```
        <form class="form-inline" novalidate name="formGetByFilter">
            <div class="form-group">
                <label for="from" class="control-label">from:</label>
                <input type="text" datetime class="form-control input-sm">
            </div>
        </form>
```

**Comment by mscdex** [comment]
Did you find a solution to this? I'm running into the same problem.

**Comment by Treolorn** [comment]
can't remember.. :(

**Comment by Eonasdan** [comment]
put the picker inside of div that has a relative position, like `row`

**Comment by ddelella** [comment]
That is not a solution.  The row class comes with additional styles which affect margin, padding, etc.  A basic <div style="position: relative"></div> around the input field would be better but is still not the best answer.  This should be re-opened for a valid solution and not a work around.

**Comment by digitalfrost** [comment]
@ddelella 's suggestion works for me. But I agree with him that it is a work around...

**Comment by richard-ejem** [comment]
+1 for re-opening
