### ISSUE TITLE
Today not getting highlighted from 4.7.14 on

### ISSUE THREAD

**Issue by kerry-money** [Eonasdan/bootstrap-datetimepicker#1143]
The border property of the today::before rule is incorrectly written, so it is not applied.  Currently from the less file:

             &.today {
                position: relative;

                &:before {
                    content: '';
                    display: inline-block;
                    border: 0 0 7px 7px solid transparent;
                    border-bottom-color: @bs-datetimepicker-active-bg;
                    border-top-color: @bs-datetimepicker-secondary-border-color-rgba;
                    position: absolute;
                    bottom: 4px;
                    right: 4px;
                }
            }

When writing a shorthand border property like this, I don't think you can specify all four border widths.  Instead, you could do this:

border-width: 0 0 7px 7px;
border-style: solid;
border-color: transparent

**Comment by Eonasdan** [comment]
this is fixed in the dev branch
