### ISSUE TITLE
Can't type in meridian (AM/PM) manually

### ISSUE THREAD

**Issue by emergingdzns** [Eonasdan/bootstrap-datetimepicker#1145]
I've been struggling with an issue that I just can't get figured out. I have two datetimepicker inputs setup and have a defaultDate set using a moment object in each one. It shows like this in my input field:

05/12/2015 12:00 PM

If I click on the field and change PM to AM using my keyboard, when I click out of the field, the AM changes back to PM. I've tried changing the dates forwards and backwards but to no success. 

I think this is a bug in the code, but can't be sure. Looking for some guidance on this.

Here is a jsfiddle of the issue: http://jsfiddle.net/emergingdzns/fpqqzw02/

Thank you,
Andrew

**Comment by Eonasdan** [comment]
your fiddle doesn't work. Please fork the fiddle listed in the readme on the front page
