### ISSUE TITLE
e.date is undefined on "dp.show" (v4.14.30)

### ISSUE THREAD

**Issue by inflop** [Eonasdan/bootstrap-datetimepicker#1146]
I try to read e.date value on "dp.show" and I get "undefined".
Here is a jsfiddle of the issue: https://jsfiddle.net/adollphus/c79ddtok/

**Comment by Eonasdan** [comment]
`dp.show` does not emit any parameters. However, if you're using `useCurrent` you can listen for `dp.change`.
