### ISSUE TITLE
Keyboard appears on mobile Android devices

### ISSUE THREAD

**Issue by websafe** [Eonasdan/bootstrap-datetimepicker#1149]
Hello, 

when I'm on an Android based device running Firefox/Chrome/Dolphin and try to **pick a date**, the keyboard appears... Is it possible to disable/prevent somehow this default system behavior?

**Comment by Eonasdan** [comment]
yes. you can disable the input box, you can set some of the picker options to prevent that from happening.

**Comment by alexvanstalkeR** [comment]
But how to properly disable it? Adding disabled or readonly attributes prevents timepicker from showing up!

**Comment by Eonasdan** [comment]
"properly" is for you to decide. You can disable the input box and use the icon or you can call `show()` from some other method.
