### ISSUE TITLE
Change format with jQuery

### ISSUE THREAD

**Issue by chon27** [Eonasdan/bootstrap-datetimepicker#1150]
Hello,
I'm trying change the format with jQuery but I get undefined variable when I get actual format and it is not working when I apply a new format by function:

var format = $(this).val(); //I get new format by a select
$('#eurRelease').format(format); //This is not work

I have initializated the datetimepicker with format option 'YYYY' and if I get it:

$('#eurRelease').format; //Return undefined

Thanks.

**Comment by Eonasdan** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/

Note All functions are accessed via the data attribute e.g. $('#datetimepicker6').data("DateTimePicker").FUNCTION()
