### ISSUE TITLE
Compatibility with IE8

### ISSUE THREAD

**Issue by evorios** [Eonasdan/bootstrap-datetimepicker#1151]
I use this code for compatibility with IE8:
http://jsfiddle.net/hLn1dtgq/
```javascript
$('#datetimepicker2').datetimepicker({
                format: "DD.MM.YYYY",
                showClose: true,
                keepOpen: true,
                locale: "ru",
                viewMode: "months"
            });
```
and got this well result:
![2015-06-29_121956](https://cloud.githubusercontent.com/assets/1260935/8403859/56bd1104-1e59-11e5-9482-dc6224e558f9.png)

**But when i clicked at calendar, then focus from textbox is hiding and calendar is hiding.**
May be option 'focusOnShow'(4.14.40) help me. I dont know.
Maybe you know what I do to make it work.

I use next libraries:
- [Polyfill v1](https://polyfill.io/) (important)
- [Modernizr 2.8.3](http://modernizr.com/)
- [Respond 1.4.2](https://github.com/scottjehl/Respond) (important)
- [Bootstrap 3.3.2](http://getbootstrap.com/)
- [Bootstrap-DateTimePicker 4.14.30](https://github.com/Eonasdan/bootstrap-datetimepicker)
- [Moment 2.9.0](http://momentjs.com/)
- [jQuery 1.11.3](https://jquery.com/) (important)

For testing i used Internet Explorer 11 in simulate mode IE8.

**Comment by Eonasdan** [comment]
IE 8 isn't supported. There some other issues out there about making it work with hacks and such. Sorry I just don't have time

**Comment by Rattone** [comment]
Try with this... http://jsfiddle.net/hLn1dtgq/1/
I've added polyfills for reduce() indexOf() and trim() issue

**Comment by pzi** [comment]
Using a polyfill for [`trim`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/trim), [`indexOf`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf), [`reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) gets at least the basic datepicker working. However, like @evorios said, every click inside the datepicker window closes it.
