### ISSUE TITLE
Stepping up not working

### ISSUE THREAD

**Issue by 0lide** [Eonasdan/bootstrap-datetimepicker#1157]
Hi!

I don't know if I made something wrong but if I use 15min stepping, and time is example 12:43, it works right and result is 12:45. But if time is 12:53 (closer 13 than 12:45) it works wrong, result is 12:00.

Do I something wrong or is it bug?

Fiddle: http://jsfiddle.net/0lide/xxcdex88/2/

![screenshot 2015-07-02 12 43 18](https://cloud.githubusercontent.com/assets/7567839/8474725/d7966e34-20ba-11e5-9694-20b2ee553c36.png)
![screenshot 2015-07-02 12 53 19](https://cloud.githubusercontent.com/assets/7567839/8474726/d7a549fe-20ba-11e5-9e79-dbfc070597a2.png)

**Comment by Eonasdan** [comment]
this looks like it's working in the latest
