### ISSUE TITLE
Formatting problem

### ISSUE THREAD

**Issue by cychong** [Eonasdan/bootstrap-datetimepicker#1161]
format somehow go wrong when i use like this: "DD MMM, YYYY", it become 20 Jan, 0015, and also the datepicker header become 0015 as well.

![screen shot 2015-07-04 at 12 35 07 pm](https://cloud.githubusercontent.com/assets/3241515/8506488/24ecb050-2249-11e5-94fb-222a99d09f1c.png)

**Comment by Eonasdan** [comment]
works for me. please provide a jsfiddle of your issue
