### ISSUE TITLE
How to set unlimited maximum value for hours and minutes?

### ISSUE THREAD

**Issue by maxdonetsk** [Eonasdan/bootstrap-datetimepicker#1162]
Hi all!
I use Eonasdan datetimepicker. It works, but I would like to set custom value for time (e.g., 65:78). Is it possible using format or embedded settings (moment.js, datetimepicker plugin)? If not, how is possible to implement it using jQuery or pure JavaScript?

See markup and script:
<pre>
&lt;input type="text" id="time" name="time" class="form-control"/&gt;
&lt;script type="text/javascript"&gt;
$(function () {
    $('#time').datetimepicker({
        format: 'HH:mm',
        useCurrent: false
    });
});
</pre>

**Comment by Eonasdan** [comment]
This plugin won't work as a timer. It is not possible to use this picker to set the time value to that since it's not a valid time. Momentjs  would likely bubble that up to 2 day, 17 hours and 18 minutes. Even at the point it would still not be a valid date.
