### ISSUE TITLE
Allow the user to type in the input (and update the view)

### ISSUE THREAD

**Issue by alvarotrigo** [Eonasdan/bootstrap-datetimepicker#1164]
Right now, if I'm in the input and I press the left or right arrow, it will move the day of the month right or left in the calendar.

This is far from ideal. The visual interface shouldn't be in conflict with the input from the user in a text input.

Whenever the user press the right or left arrow, they expect the cursor in the text input to move right or left, as in any other text input. 
This way, they can freely move in the text input and update the date (and time) by just typing. (which experts users always demand).

In relation with this, the `delete` key shouldn't delete the whole text in the input. That's totally unexpected for any user. Users expect it to work as it normally does, by just removing the previous character to the cursor in the input box.

**Comment by alvarotrigo** [comment]
I modified a couple of lines in the plugin to make it works as I expected.

[Demo online](http://jsfiddle.net/a4u71thz/5/)

You can see it [on this online demo](http://jsfiddle.net/a4u71thz/).
You'll be able to:

- Position the cursor and change the date string
- Press `delete` to remove a character
- Press `left` or `right` arrows to move the cursor


Then, adding a few lines of Javascript to detect any change on the input, I managed to create something even better that updates the view in real time:

[Demo online](http://jsfiddle.net/a4u71thz/4/)

**Comment by exhtml** [comment]
Awesome! just looking for solution for this same issue. Thank you very much for sharing!
I think it would be perfect if we had an option to disable keyboard working this way, if desired. Formidable plugin, anyway, keep the good work. Thanks!

**Comment by Eonasdan** [comment]
there already is an option to disable this. See [`keybinds`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#keybinds). You can provide your own keybinds or set this to null.

This was a FR to put this *in* to the repo. This plugin is used by thousands of people in 10 of thousands of projects, I can't possible make everyone's idea of "ideal", "expected", "obvious" work at the same time.
