### ISSUE TITLE
Open calendar on focus

### ISSUE THREAD

**Issue by alvarotrigo** [Eonasdan/bootstrap-datetimepicker#1165]
Not sure how the plugin decides to show or hide the date & time picker at the moment, but it is very difficult to debug or change the styles because whenever the DOM inspector is opened and any element is clicked, the datepicker gets removed. (and funny enough, changing tabs and coming back opens it again in Chrome...) 

It seems is is not being fired on focus, as when setting the input to `focus` on the developers tools nothing happens.

Ideally it should be fired on focus as far as I see it. Is there any reason why this approach was avoided? 

The only way I found to debug the CSS styles and the DOM structure of the plugin was to use breakpoints. Far from ideal.

**Comment by kevin-brown** [comment]
> whenever the DOM inspector is opened and any element is clicked, the datepicker gets removed.

I might as well point out that there's a `debug` setting that can be enabled. It disables this, and makes it considerably easier to debug.

**Comment by alvarotrigo** [comment]
Right, I see it:

**Comment by alvarotrigo** [comment]
Right. I see it:

> **debug**
For the moment this function will only prevent the picker from calling hide() on blur so that the picker can be inspected.

I guess this would be the way to use it ?

```
$('#datetimepicker6').data("DateTimePicker").debug()
```

**Comment by kevin-brown** [comment]
> I guess this would be the way to use it ?

I typically use it as the option form, where it's passed into the constructor.

```js
$('#datetimepicker1').datetimepicker({
  debug: true
});
```

But it does appear that there is a `debug()` method, so the following would work as well

```js
$('#datetimepicker1').data("DateTimePicker").debug(true)
```

**Comment by Eonasdan** [comment]
yup. use the `debug` feature. It will keep the picker open.

**Comment by alvarotrigo** [comment]
Ok thanks.
