### ISSUE TITLE
Formatting on an existing date time value not working

### ISSUE THREAD

**Issue by connexionsw** [Eonasdan/bootstrap-datetimepicker#1169]
Formatting date time control using a date time object. (e.g. 08/07/2015 13:05)
using moment with a locale of en_gb and a format setting of 'L LT'
js to initialise component..
      $('#id_start_datetimepicker').datetimepicker({
        defaultDate: 'now',
        showTodayButton: true,
        format: 'L LT'
      });
When creating a new form record, the date time formatting is correct (DD/MM/YYYY HH:mm) and the picker working as expected. However when editing a record, the stored value (2015-07-08 13:05) flashes briefly in the picker controls input edit, its unformatted and then the edit controls input clears showing no value.

Any ideas very much appriciated

**Comment by Eonasdan** [comment]
check the `extraFormats` option. It will allow the input to be valid in several formats

**Comment by connexionsw** [comment]
By adding the additional extraFormats setting appears to work.
      $('#id_start_datetimepicker').datetimepicker({
        defaultDate: 'now',
        showTodayButton: true,
        format: 'L LT',
        extraFormats: [ 'YYYY-MM-DD HH:mm' ]
      });

Many thanks
