### ISSUE TITLE
disabledTimeIntervals : accepted when moved from one day to another

### ISSUE THREAD

**Issue by dbertha** [Eonasdan/bootstrap-datetimepicker#1173]
Hi there !
Thanks for this nice plugin.
There is an issue with the disabledTimeIntervals option : a time in a disabled time interval can be accepted by the datetimepicker if we get to it through another day where this hour is allowed.
Example : I disable today from 10h to 18h. My previous selection was tomorrow 11h. If I change the day to today, the datetime will be accepted (today at 11h), even if the arrows for hours or minutes selection won't react anymore.
jsfiddle : https://jsfiddle.net/dbertha/6jL0eo0d/

Bonus : instead of no reaction from the arrows when next selection is disabled, why not jump to next allowed time selection ? as with the stepping option

**Comment by cibien** [comment]
Hey guys,

I am experiencing the same problem from this issue with the version 4.17.42
:(

**Comment by stephen-lim** [comment]
We're seeing a similar issue with a pop open datepicker. Say you set the allowable times between say 9:00 to 10:00. If you visit the page outside of those valid times (suppose at 11:00), you are presented with today's date and the time selector is restricted to 12. If you choose a future date without clicking away, the time selector remains restricted eventhough we know you should have been able to select from 9:00 to 10:00. The only way is to select the date, click away so the datepicker closes. Open again and the time selector is updated.
