### ISSUE TITLE
Question: how do I get the selected date programatically?

### ISSUE THREAD

**Issue by germanger** [Eonasdan/bootstrap-datetimepicker#1178]
This is my html:

          <input type="datetime" class="form-control" id="input-date" placeholder="">

This is my `$(document).ready..`:

           $(document).ready(function () {
                      $("#input-date").datetimepicker({format: "YYYY-MM-DD hh:mm A"});
          });

The input field is working fine. The calendar is displayed, etc.

Now... how do I programatically get the selected date?

This is not working:

             console.log($("#input-date").datetimepicker().date());

Throws:

             Uncaught TypeError: $(...).datetimepicker(...).date is not a function

I think the `functions` section is not clear enough on how to use the function `date()`
http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#date

Of course the following is an alternative that works:

            console.log(moment($("#input-date").val(), "YYYY-MM-DD hh:mm A"))

(Parsing from the `val()` string to a `moment` date)

**Comment by dbertha** [comment]
You can try 
    console.log($("#input-date").data("DateTimePicker").date());

**Comment by germanger** [comment]
Ah, so the way all the functions listed in the docs ( http://eonasdan.github.io/bootstrap-datetimepicker/Functions/ )
Is like that?

                    $("#input-date").data("DateTimePicker").someFunctionListedInDocs()

 Is not clear enough in the docs. Thanks.

**Comment by Eonasdan** [comment]
[![image](https://cloud.githubusercontent.com/assets/1006516/8677742/d054c4e6-2a1e-11e5-865c-85cc73c707ae.png)](http://eonasdan.github.io/bootstrap-datetimepicker/)

**Comment by germanger** [comment]
Shouldn't that note be in the "Functions" section?

**Comment by crashoverride002** [comment]
This doesnt work as documented:

console.log("data:" + $("input[id='datevalue_" + busid + "']").data("DateTimePicker").date());

returns: 
Uncaught TypeError: Cannot read property 'date' of undefined
    at HTMLAnchorElement.<anonymous> (Default.aspx?)
    at HTMLAnchorElement.dispatch (jquery-2.1.1.min.js:7)
    at HTMLAnchorElement.r.handle (jquery-2.1.1.min.js:7)
