### ISSUE TITLE
defaultDate doesn't work with input value

### ISSUE THREAD

**Issue by ttocskcaj** [Eonasdan/bootstrap-datetimepicker#1179]
If there is a value field on the input then the defaultDate won't show, neither will the value.
See the fiddle https://jsfiddle.net/ttocskcaj/vm4315uL/2/ 

I'm using laravel's form model bindng which is setting the value automatically, so something other than removing the value would be great.

**Comment by Eonasdan** [comment]
The issue is that the value being supplied to the input field doesn't match the dtp's format. The default format is `L LT` of the locale being used. If you add `keepInvalid` or set the `format` to match it works.

**Comment by ttocskcaj** [comment]
Ok. Thank you.
