### ISSUE TITLE
Additional HTML layer between date table cell and date text

### ISSUE THREAD

**Issue by lllopo** [Eonasdan/bootstrap-datetimepicker#1180]
Currently it is not possible to style the date numbers completely independently from the table cell that they belong. A common use case is : style current date to be highlighted with a round (circle) background instead of square. Since the cell size depends on the table size, the styling of type "border-radius : 50%" results ellipses instead of circles. A solution would be to wrap each date number in a span inside the cell like this :
`<td class="day" data-day="15-07-2015" data-action="selectDay"><span>15</span></td>`

**Comment by hamsterboy** [comment]
+1 I've had the same challenge quite a few times too.

**Comment by astroanu** [comment]
this is a good idea +10

**Comment by priyankmaniar** [comment]
@lllopo Your solution helped. It saved a lot of time.

Thanks for sharing the solution over here.
