### ISSUE TITLE
There is no option to change the first day of the week

### ISSUE THREAD

**Issue by andrius-senulis** [Eonasdan/bootstrap-datetimepicker#1182]
Hello,

I could not find in the documentation how to set the first day of the week to Monday. Is it possible somehow?

Best regards,
Andrius

**Comment by Eonasdan** [comment]
momentjs locale handles the first day of the week. You can either create a custom locale or use one of their files. Check their docs for more info.

**Comment by andrius-senulis** [comment]
I'll try, thanks.
