### ISSUE TITLE
dinamically changed minDate and maxDate

### ISSUE THREAD

**Issue by Jadone** [Eonasdan/bootstrap-datetimepicker#1183]
I need an advice, as i  can't understand if this possible to refresh datetimepicker in such situation.
the minDate and maxDate of datetimepicker  depends on the value of other field (dropdown) and according to the selected value in dropdown.. datetimepicker should dinamically change..But i can't find the right solution 
  <code> 
      if(field == 1) 
	 {
		minDate = moment().startOf('day').hour(5).minute(00);
               maxDate = moment().startOf('day').hour(8).minute(00);}
 else
     { minDate = moment();
       maxDate = moment();}

$('.datetimepicker').datetimepicker({
	        defaultDate: false,
	        minDate: minDate,
	        maxDate : maxDate,
	        showClear : true })
        .off('focus')
        .click(function () {
            $(this).datetimepicker('change');
        });</code>

 but this doesn't work as  expected.

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.
