### ISSUE TITLE
Bug: disabled year range that the selected year belongs to

### ISSUE THREAD

**Issue by andrius-senulis** [Eonasdan/bootstrap-datetimepicker#1185]
Hi,

I have encountered a wrong behavior in the calendar of years. 

I have set a minDate option to limit years before 2015 and when I select a specific year, then click on the year range at the top of the calendar, it shows the range that my selected year belongs to as disabled.

Here's how it looks:
![datetimepicker year range bug](https://cloud.githubusercontent.com/assets/1100012/8694870/24a20bb2-2ae2-11e5-963d-d6a3d82b3926.png)

Regards,
Andrius

**Comment by bertoost** [comment]
Same issue here. Hope this gets fixed soon :-1:

**Comment by DragonZero** [comment]
I was able to work around this particular bug by subscribing to the decades header click and cancelling the change (in my case I don't require decades when dealing with min/max date ranges)

$('th.picker-switch[data-action=pickerSwitch][title="Select Decade"]').click(function(){ return false; });

**Comment by andrius-senulis** [comment]
Thank you for fixing it!
