### ISSUE TITLE
BeforeShowDay/Month/Year/Decade callback

### ISSUE THREAD

**Issue by lllopo** [Eonasdan/bootstrap-datetimepicker#1186]
It would be very useful to introduce a callback of the type beforeShowDay/Month/Year/Decade, which allows to inject specific properties, css/styles and html to each entry/cell. This would allow to create more complete calendar/schedule experience, like adding specific colors or icons per date etc. etc.

**Comment by hamsterboy** [comment]
+1 Indeed!

**Comment by ismaelisuani** [comment]
+1

**Comment by vntopcoders** [comment]
+1

**Comment by johnsenpeder** [comment]
+1

**Comment by Messhias** [comment]
+1

**Comment by Messhias** [comment]
Hi, you will develop this function?

**Comment by William-H-M** [comment]
@Messhias I doubt it this repor i sin code freeze maybe to the request at the new active repo https://github.com/tempusdominus/bootstrap-3 or https://github.com/tempusdominus/bootstrap-4
