### ISSUE TITLE
Setting `minDate` on a time-only picker resets the initial value to the minimum date value

### ISSUE THREAD

**Issue by Ingannatore** [Eonasdan/bootstrap-datetimepicker#1187]
I'm using two time pickers to get a time range from the user; when I open the picker on the `toTime` input field, its original value is overwritten by its `minDate` value (taken from the `fromTime` input field).

On the other hand, the picker on the `fromTime` input field works correctly by setting a `maxDate` (taken from the `toTime` input field).

Fiddle: https://jsfiddle.net/oc3bshaL/1/

**Comment by ane** [comment]
Encountered this issue as well. Fiddle: https://jsfiddle.net/w92ucsy7/

It works fine with the maxDate setting, but for the minDate (on picker 2) it sets its default date to the minDate, ignoring the default date.

**Comment by trevorgehman** [comment]
I'm encountering the same issue. Basically makes minDate useless for editing an existing value.

**Comment by Ingannatore** [comment]
I've updated my original jsfiddle by adding the `useCurrent` option and it seems to work.
Thanks for the help.
