### ISSUE TITLE
Angularjs option

### ISSUE THREAD

**Issue by phanhongphucit** [Eonasdan/bootstrap-datetimepicker#1188]
Is there bootstrap-datetimepicker for AngularJS framework?

Thanks

**Comment by kevin-brown** [comment]
There are better options for AngularJS than a jQuery plugin. Just google "angular datetimepicker", there are plenty of AngularJS-native ones.

For example, https://github.com/dalelotts/angular-bootstrap-datetimepicker (untested)

**Comment by anyayunli** [comment]
anybody sees this ticket, just let you know the above repository https://github.com/dalelotts/angular-bootstrap-datetimepicker has a lot issues with angularjs, it does not even work well with ng-change.
