### ISSUE TITLE
DatePicker value not set programatically

### ISSUE THREAD

**Issue by Silwest** [Eonasdan/bootstrap-datetimepicker#1192]
Hello guys,

Let me describe you the problem. Each time when I'm changing datetime of one of my inputs I would like to trigger another function (calculate other dates etc.). The code which was working previously:

$('#input_id').change(function_to_trigger);

Is now not working. I read a lot on the internet and I believe that the root cause is that:
DatePicker after changing the date does not trigger event therefore Jquery doesn't see the change.

More info in the first answer below:
http://stackoverflow.com/a/25998184/2175772

As I don't want to execute function each 3 seconds could you please tell me how this should be properly handled ?

**Comment by Eonasdan** [comment]
please read the docs. [`dp.change`](http://eonasdan.github.io/bootstrap-datetimepicker/Events/#dpchange) is fired when the date is changed.

If that's not enough help, please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.
