### ISSUE TITLE
Wrong year change using with custom format

### ISSUE THREAD

**Issue by egreek** [Eonasdan/bootstrap-datetimepicker#1194]
Hello,
I use plugin with custom date format ('DD.MM.GG') and have a trouble. When I set date differs from current date more than a year and remove focus from input, after clicking again at the input or plugin button year have changed to current automatically. This appears only when I use custom formats and works properly with 'L' for example. Is it my mistake with options or plugin bug?

![picker2 gif](https://cloud.githubusercontent.com/assets/5384423/8805782/c37ccefe-2fdb-11e5-9598-4b68e415d5dd.gif)

Problem in this fiddle: https://jsfiddle.net/fhfnb55j/18/

Thank you.

**Comment by Eonasdan** [comment]
`GG` is "Week Year (ISO)" according to the moment docs. http://momentjs.com/docs/#/displaying/format/

are you sure you don't want `YY`?

**Comment by egreek** [comment]
thank's a lot. Setting 'YY' fixed a problem.
