### ISSUE TITLE
Compatibility with floating labels (remove empty tag upon closing)

### ISSUE THREAD

**Issue by gergalyb** [Eonasdan/bootstrap-datetimepicker#1195]
I use this [Material theme](https://fezvrasta.github.io/bootstrap-material-design/#input)

The problem is that the empty tag returns after closing the picker even if there is data in the input field  so it results in the data and the floating label overlapping. I'm not that much into js so I don't know if it should be fixed from here or the theme author's side.

**Comment by notentered** [comment]
@gergalyb Do you have any update on this? I just hit the same problem :)

**Comment by sammichael25** [comment]
I'm having same issue. Any update on how to fix this?

**Comment by William-H-M** [comment]
Hi, at least there's an example on something like http://jsfiddle.net/ I have no idea what you're talking about, and (_just in case that you ask_) no I don't want to create and example by myself :)
