### ISSUE TITLE
When I enable showTodayButton, I cannot see the word "Today"

### ISSUE THREAD

**Issue by rogelio-blanco** [Eonasdan/bootstrap-datetimepicker#1197]
Hi, thanks for the hard work.

I have an issue with the datetimepicker, when I try to enable the showTodayButton property to TRUE, I can see the button however I cannot see the work "Today" I saw just an icon.

Is this the correct behavior?  If yes, could you please tell me how to show text in that button, so the user knows what that button does?

Thanks

**Comment by Eonasdan** [comment]
the buttons are all icons. There are tooltips (in english) for each icon when hovered over:

![image](https://cloud.githubusercontent.com/assets/1006516/8851794/a1146008-311f-11e5-9f11-185dd5b0c98f.png)

You can change the icons to another icon if you want:

http://eonasdan.github.io/bootstrap-datetimepicker/Options/#icons

**Comment by Alex-Sokolov** [comment]
Is it possible to show some text instead icon here?

**Comment by rogelio-blanco** [comment]
I think it would be a good enhancement +1
