### ISSUE TITLE
setting 'minDate' to today's date puts it also into input

### ISSUE THREAD

**Issue by ZuBB** [Eonasdan/bootstrap-datetimepicker#1198]
today's date - [bug](http://jsfiddle.net/wq6swvzr/1/)
prev date - [no bug](http://jsfiddle.net/wq6swvzr/2/)

**Comment by Eonasdan** [comment]
the reason you're seeing this is because `now` is the default date, so by setting the `minDate` to `now` it makes the current date invalid. The picker automatically moves the current date to the closest valid date when setting `min/maxDate`

**Comment by ZuBB** [comment]
> now is the default date

Options page says that 

> defaultDate Default: false

And I am sure I do not set a `defaultDate`

**Comment by Eonasdan** [comment]
when you open the picker, the input field is set to the current date/time.

if you just don't want the input field set, set `useCurrent:false`

**Comment by ZuBB** [comment]
oh, thanks, thats works

**Comment by ZuBB** [comment]
HI @Eonasdan!

I would like to come back to this issue again :(

I cant deal with set of option that is supported by your lib for achieving requirements that I have to meet with:

* ability to select only today's and later dates
* do not fill by default today's date into input that is bound to date-picker (no value is passed to input/date-picker's initially)
* date-picker should be able to pick up date (actually string in correspondent format) from input or as param passed into `date` method of date-picker

it seems that combination of `minDate` param set to today's value and `useCurrent:[false||true]` option make picker behave really weird.

Do you have any ideas? // already going to start digging..

Thanks in advance
