### ISSUE TITLE
Standalone CSS file like the datepicker (for using it without Bootstrap)

### ISSUE THREAD

**Issue by vdhicts** [Eonasdan/bootstrap-datetimepicker#1199]
This datetimepicker is one of the best I've seen. So I want to use in a lot of projects. Unfortunately I'm working on a project without Bootstrap. The original datepicker has an extra CSS file so it can be used without the Bootstrap CSS. 

It would be great to also have one for the datetimepicker. I will probably give it a try myself (if I can find some time) but maybe someone already has some suggestions for a quick start or perhaps already have started this.

**Comment by Eonasdan** [comment]
I know someone else asked the same thing. There was an issue about. You could try [Critical Path CSS Generator](http://jonassebastianohlsson.com/criticalpathcssgenerator/) with a just the picker in a html file to see if that would work

**Comment by dvdheiden** [comment]
I've searched the issues but couldn't find anything. I will try the Critical Path CSS Generator with the inline version of the timepicker first.
