### ISSUE TITLE
Calendar cannot display well

### ISSUE THREAD

**Issue by JOHNSHAO** [Eonasdan/bootstrap-datetimepicker#1202]
I add datetimepicker to my website, but it don't display well. Anyone have any idea? any possible mistake on my installation?

![image](https://cloud.githubusercontent.com/assets/1856301/8867122/050af4e0-31f8-11e5-90c9-c3f580f636d8.png)

**Comment by Eonasdan** [comment]
you must be missing the pickers css file

**Comment by JOHNSHAO** [comment]
I add below css in my style, so the calendar cannot display well.
table {
    min-width: 800px;
}
