### ISSUE TITLE
Multiple Time picker not working on IE

### ISSUE THREAD

**Issue by SukanyaSampathkumar** [Eonasdan/bootstrap-datetimepicker#1209]
Hi,

I need to use multiple dynamic instances of the time picker in my mvc razor page. It works great on firefox and chrome but on IE 11, clicking on the first time picker shifts focus and opens pop up on the last time picker in the page.  Thank you for any help and Thanks for the helpful plugin!

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.

**Comment by SukanyaSampathkumar** [comment]
Hi, I've updated the jsfiddle. on IE, the issue is on single click, but on other browsers it can be re produced by double clicking on the text box

**Comment by Eonasdan** [comment]
Can you provide me with a link to your fork?

**Comment by SukanyaSampathkumar** [comment]
sorry about that, please find it here : http://jsfiddle.net/0Ltv25o8/1562/

**Comment by Eonasdan** [comment]
your fiddle does the same thing for me in both IE11 and Chrome. Your init function must be assigning something incorrectly

**Comment by SukanyaSampathkumar** [comment]
Hi,

the issue was that i was doing a common init for all elements whose id's end with jobtime, once i changed it to initialise each one separately it's working fine. Thank you for the help! I have the updated working version here : http://jsfiddle.net/0Ltv25o8/1564/.
