### ISSUE TITLE
No option to change visibility for inline pickers

### ISSUE THREAD

**Issue by Visgean** [Eonasdan/bootstrap-datetimepicker#1214]
I have these options and I have played with many more, but there seems to be no way how to prevent datepicker from being expanded/rendered/displayed from the beginning (and not only after user clicks on the input)...

```
        allowInputToggle: true,
        inline: true,
        useCurrent: false
```

**Comment by Eonasdan** [comment]
you can call `$('#datetimepicker1').data('DateTimePicker').hide()` and `$('#datetimepicker1').data('DateTimePicker').show()`.
