### ISSUE TITLE
DateTimePicker does not work with <input type="button"> in Safari browser

### ISSUE THREAD

**Issue by PratikDotCa** [Eonasdan/bootstrap-datetimepicker#1218]
DateTimePicker does not work with <input type="button"> in Safari browser.

I am using AngularJS and datetimepicker with button control:

      <input type="button" class="date-picker" ng-model="fromDate" datetimepicker-options="{{scopeUntil}}" datetimepicker />

it works fine in IE 11, Chrome, Mozilla & Opera, but it does not work in Safari.

Any fix available for it?

Thanks in advance.

**Comment by PratikDotCa** [comment]
Issue is resolved. Added new event parameter for 'click' in attachDatePickerElementEvents() function.

![datetimepicker](https://cloud.githubusercontent.com/assets/10426732/9064812/3b20a7bc-3a9c-11e5-8bf7-07da7de5eb24.PNG)

**Comment by Eonasdan** [comment]
wow. strange. glad you got it working though :+1:

**Comment by oitozero** [comment]
@PratikDotCa Exactly what I needed. Thanks 👍
