### ISSUE TITLE
Always keep open

### ISSUE THREAD

**Issue by milkandteamedia** [Eonasdan/bootstrap-datetimepicker#1220]
How to tell the calendar to always be open?

I like the SideBySide mode the best and I can't keep the calendar open/showing...

    $('#datetimepicker').datetimepicker({
        inline: true,
        sideBySide: true,
        format: 'YYYY-MM-DD hh:mm A'
    });

I thought, "collapse: false," would work, but it does not work.

help!?

**Comment by milkandteamedia** [comment]
Also,  "keepOpen: true,"  doesn't work?

**Comment by Eonasdan** [comment]
what does "can't keep the calendar open" mean to you?

Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.

**Comment by milkandteamedia** [comment]
http://jsfiddle.net/whdp87L6/2/

I've created a fiddle.. but I also took some screen shots.  http://imgur.com/a/AkEUw

I think my images explain what "Can't Keep The Calendar Open" is, but I'll try again as well.
When the input for the calendar has focus the calendar and time picker are present.
When that input box loses focus, the calendar and time picker fade out.... I would like the calendar and day picker in inline side by side mode to always bee on the screen.

I can't seen to find a option, or override function to make that happen...

**Comment by ironman1964** [comment]
Same here, 
I would like to show the calender all the time no matter if the input has focus.

**Comment by ironman1964** [comment]
Just found a little tick ... 
set the option debug:true and it will stay open !

Scan the js file for the blur and you'll find it :+1:

**Comment by milkandteamedia** [comment]
@ironman1964, Nice find.  I try to not edit js plugins. Rather, relying on overrides or built in options the author built.

**Comment by Eonasdan** [comment]
You're using `inline` incorrectly, please see the docs on how that works.

I'm planning on changing the option `keepOpen` to keep the picker open until you call `.hide()`.

**Comment by ironman1964** [comment]
@milkandteamedia I don't edit the js, just was looking for the blur function on the input field.
That's when the calendar disappears ...

@Eonasdan good to see you planning to modify keepOpen to a real keepOpen and not untilBlur :+1:

**Comment by milkandteamedia** [comment]
@ironman1964    ah, that's great!   I misunderstood....   Thank you.
