### ISSUE TITLE
Not working with other than id selector

### ISSUE THREAD

**Issue by skoushlendra** [Eonasdan/bootstrap-datetimepicker#1232]
I tried to implement for the multiple fields by using class as the selector, but it supports only the id as selector. One more thing that is this would also work with dynamic elements if yes then how to do.

Kindly suggest me on both(class as selector & support on dynamic elements).
http://jsfiddle.net/eqecdd0v/

**Comment by Eonasdan** [comment]
You defined the `class` attribute twice.

**Comment by skoushlendra** [comment]
Thanks dear, but what about the dynamic textfield http://jsfiddle.net/8dz66auc/ if i would have create a dynamic field then how to add datepicker onto the newly created element.

**Comment by Eonasdan** [comment]
You'll have to do the same thing you do anytime you want to attach jquery events to dynamically created elements.

I'd suggest Google "dynamic elements  jquery plugins" or something like that
