### ISSUE TITLE
How to disable all dates at once

### ISSUE THREAD

**Issue by jfrot** [Eonasdan/bootstrap-datetimepicker#1237]
I am building a news module.
When visiting a month page, where news of the month are listed, I enable only the dates on which there are news, via the enabledDates option.

But when I visit a month page where there is no news at all, how can set enabledDates to something like "none" or "null", ... ?

Thanks, Johann

**Comment by Eonasdan** [comment]
you could disable the picker `$('#datetimepicker1').data('DateTimePicker').disable()`

currently, I don't think there's a way to disable all the dates in a month

**Comment by jfrot** [comment]
Thanks for your suggestion.
However, if I disable the whole picker, I will not be able to navigate between months anymore, which is not what I want.

Simply, if there are months without news I want that no date is selectable, still I need to go to other months.

Johann
