### ISSUE TITLE
Enable hours for different days - custom callback?

### ISSUE THREAD

**Issue by tmcnicholls** [Eonasdan/bootstrap-datetimepicker#1238]
Is it possible to set different enabledHours depending on the day of the week? I'd like to restrict times to our opening hours, so for example:

Monday - Thursday: 9am - 7pm
Friday: 9am - 5pm
Saturday/Sunday: closed

I've had a look at disabledTimeIntervals but it doesn't seem to do what I want? Is it possible to set a custom callback function for isValid?

Thanks

**Comment by chapterjason** [comment]
+1 that would be awesome!

**Comment by echan00** [comment]
same here, also interested in this

**Comment by William-H-M** [comment]
This project is in code freeze so no new features will be added, maybe ask at the new repo https://github.com/tempusdominus/bootstrap-3
