### ISSUE TITLE
Multiple months to show

### ISSUE THREAD

**Issue by ironman1964** [Eonasdan/bootstrap-datetimepicker#1241]
Is there a possibility to have two months in the calendar ?
Like here : http://jsbin.com/ibile4/1/edit?html,js,output

**Comment by PerryD** [comment]
I would like to see that as well.

**Comment by LcbPereira** [comment]
Hello there,
This issue were closed because it's already implemented or wont be implemented?
I would like to have this functionality as well.

Thanks in advance.
