### ISSUE TITLE
Bug calendar Firefox

### ISSUE THREAD

**Issue by otaviofavero** [Eonasdan/bootstrap-datetimepicker#1243]
hello good afternoon I encotrei this bug

you know what I can do or give me a hint or location in the code where I can fix and help in developing the project

I found it very good ...

![erro calendar](https://cloud.githubusercontent.com/assets/7750317/9144489/b8282742-3d23-11e5-9886-1b58da43ab0c.jpg)

**Comment by Eonasdan** [comment]
yup this is a browser issue. I believe it's due to how certain locales deal with daylight savings time, see #1243 and #881 and more. I thought I fixed it with `4.13.28` but it's resurfaced it seems.  It doesn't happen to me so it's hard to troubleshoot.
