### ISSUE TITLE
Setting maxDate 7 days ahead of another field

### ISSUE THREAD

**Issue by edwade3** [Eonasdan/bootstrap-datetimepicker#1244]
So I am using the linked example you posted on your website, however I want the maxDate of field 2 to be 7days later than the date set in field 1. Is this possible, and if so, how do I go about doing it?

**Comment by Eonasdan** [comment]
the picker uses momentjs is that's a super easy task. Just do `e.date.add(7,'d')` if that doesn't work post a fiddle

**Comment by edwade3** [comment]
Thank you, thank you, thank you!! Worked a charm - sorry for asking a bit of a dense question!!

**Comment by ATouhou** [comment]
This should have been (more clear) in the documentations! :-)
