### ISSUE TITLE
dp.change event preventing ability to change between AM and PM

### ISSUE THREAD

**Issue by pconway11** [Eonasdan/bootstrap-datetimepicker#1245]
I added an event listener for dp.change 
$('.datetimepicker').on("dp.change",function(e){
	$('#sendDateInput').trigger('change');
	});

In the time portion of the picker clicking on AM and PM does not toggle the value...
ie. AM stays as AM when clicked

**Comment by pconway11** [comment]
actually its the .trigger('change') which is stopping AM and PM from being toggled

**Comment by Eonasdan** [comment]
please provide a jsfiddle of your issue

**Comment by pconway11** [comment]
I can work around it by making a function and calling it from the input .change and dp.change methods, instead of calling .trigger.  dont really have time to create a jsfiddle atm
