### ISSUE TITLE
Input value attribute overrides defaultDate

### ISSUE THREAD

**Issue by variousauthors** [Eonasdan/bootstrap-datetimepicker#1247]
I feel that these two clauses (starting from [this line](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L2282)),

``` javascript
if (input.is('input') && input.val().trim().length !== 0) {
    setValue(parseInputDate(input.val().trim()));
}
else if (options.defaultDate && input.attr('placeholder') === undefined) {
     setValue(options.defaultDate);
}
```

are a gotcha. This is probably a matter of taste, but this caught me completely off guard. My feeling is that if I have specifically included a `defaultDate` in the options passed to `datetimepicker()`, then it should override whatever value the associated input happens to have.

I realize this is kind of a "six of one, half a dozen of the other" issue. I can see a reasonable case for both behaviors. If you like things the way they are, could you at least update the documentation of `defaultDate` so that users will know that the `input`'s value attribute will override the `defaultDate`?

**EDIT**: upon further reflection, I think this is a bug. Either I've completely missunderstood your documentation or the datetimepicker's `defaultDate` just doesn't work. Take a look:
## JSFiddles

`using version : 4.15.35`

[Here is a fiddle](http://jsfiddle.net/0Ltv25o8/1614/) based on the documentation's description of the defaultData option. From the docs I'm lead to believe that I can pass a `moment` to the `datetimepicker` initializer and have it be the default value. It does not appear to set the default value, instead using the current date.

[Here is a fiddle](http://jsfiddle.net/0Ltv25o8/1615/) in which I have provided a `format` option in addition to the `defaultData` option. In this case, the new default is used correctly.

[Here is a fiddle](http://jsfiddle.net/0Ltv25o8/1618/) in which the format is different from the provided data. Note the output of `date1.format("hh:mm a")` and `date2.format("hh:mm a")`. In this example, the dates differ by a few hours, so the formatted outputs also differ. However the datetimepicker outputs "8:00 pm" in both cases (I think it is parsing the "8" in the date).

Finally, [here is a fiddle](http://jsfiddle.net/0Ltv25o8/1620/) in which I have replaced your library with my fork, in which I reversed the two clauses above. All three examples work fine: 
1. providing a `defaultDate` without a format uses the given `moment`
2. providing a `defaultDate` and a format different from the `input` value's format
3. providing just a format allows the datepicker to read the `input`'s value

**Comment by variousauthors** [comment]
I'll be using my fork for now, but please let me know if I've just misunderstood.

**Comment by fasomann** [comment]
This is definitely an issue. Especially the point concerning the output format "hh:mm a".
