### ISSUE TITLE
enabled/disabledHours not working

### ISSUE THREAD

**Issue by samfrjn11** [Eonasdan/bootstrap-datetimepicker#1250]
Somehow the system doesn't enable nor disable hours on my timepicker, any ideas?
Also if I don't typecast with the (array) it throws an exception: "Uncaught TypeError: enabledHours() expects an array parameter"

$('#overtime-withdraw-start, #overtime-withdraw-end').datetimepicker({
                daysOfWeekDisabled: [0, 6],
                enabledHours: (Array)[9, 10, 11, 12, 13, 14, 15, 16, 17],  
            });

**Comment by MarcReniu** [comment]
I have the same problem with en/disabledDates. Constructor can't handle collections, you have to do it one-by-one. With a each loop, for example. #1257

**Comment by samfrjn11** [comment]
I don't see any differences in your code with mine...

**Comment by MarcReniu** [comment]
My code is the "bad" example of use. Here, an example with a functional enabledDates (it has to work equal with enabledHours) http://jsfiddle.net/3wsedhbk/2/

**Comment by samfrjn11** [comment]
Yep, that did the trick for me! 

So basically you have to assign the datetimepicker function to each formfield separately :)

**Comment by gameboyzone** [comment]
Yep, this worked for me. Thanks @samfrjn11 and @MarcReniu

**Comment by JackWells** [comment]
Can someone post a working example of enabledHours ??  The reference to the jsfiddle is to enabled dates.  I have exactly what is in the example, and the hours are still available for picking in the widget.

**Comment by samfrjn11** [comment]
@JackWells Just add the option to your options...

http://jsfiddle.net/3wsedhbk/20/

**Comment by JackWells** [comment]
Thank you for the quick response  In my Rails app, using the gem here (https://github.com/TrevorS/bootstrap3-datetimepicker-rails)  the enabled and disabled hours does nothing, though minDate and defaultDate work ok in the same block of options.  That got me thinking ... I have now discovered that allowTimes[] from jquery-ui-datetimepicker syntax works - and that JS is running on my input - overriding the bootstrap-datetimepicker JS.  Apologies for the trouble - and thank you again for responding.  If returning to the Bootstrap version, I will reference the same files you use in your fiddle.
