### ISSUE TITLE
en/disabledDates parameter issue in jQuery inputs collection

### ISSUE THREAD

**Issue by MarcReniu** [Eonasdan/bootstrap-datetimepicker#1257]
First of all, en/disabledDates option works, but only when jQuery have to do it in a single element.

In the next jsFiddle link I create a double picker with enabledDates options configured, and jQuery collects them with the 'datetimepickers' class.  http://jsfiddle.net/fpf3n0ko/1/

Then the magic occurs: using the browser console, you will see an error message like "Uncaught TypeError: enabledDates() expects an array parameter". Expects an array and I configured it!!

So, what happens? After some debugging, the problem is with the option parameters overwrite. Lines from #2303 to #2312 of Datetimepicker constructor. 

Issue is in #2308, 'options' variable is fulfill with input and default parameters, BUT disabledDates and enabledDates functions overwrites his parameter options, transform it from a array to a hash ("indexGivenDates"). Here comes the problem with jQuery input collections.

_Posible solution_: move 'options' variable definition before the each loop.

**Comment by Eonasdan** [comment]
might be related to #943

**Comment by MarcReniu** [comment]
Not at all. In this issue, options validation throws an error message and pickers are not created. It is more related with #1250.

I create a fiddle with a workaround where you have to apply the constructor for each formfield individually http://jsfiddle.net/3wsedhbk/2/ to make it work.

**Comment by thorsten-krieger** [comment]
I also have this problem in a project, where more than one picker is on a page.

i wrote a bugfix for the method picker.disabledDates()
replace these lines
```
            if (!(dates instanceof Array)) {
                throw new TypeError('disabledDates() expects an array parameter');
            }
            options.disabledDates = indexGivenDates(dates);
```
by this
```
            if (!(dates instanceof Array)) {
                if ((dates instanceof Object))
                    options.disabledDates = dates; // Dates alreades indexed
                else
                    throw new TypeError('disabledDates() expects an array parameter');
            }
            else
                options.disabledDates = indexGivenDates(dates);
```
