### ISSUE TITLE
Set start day of the week

### ISSUE THREAD

**Issue by Tisiber** [Eonasdan/bootstrap-datetimepicker#1259]
Hi
Is it possible to edit the first day of the week?
Thanks¡¡

**Comment by Eonasdan** [comment]
Start of the week is based on the [`locale` provided](http://stackoverflow.com/a/24471814/237917). This is defined by moment's locales. If you want to change it, create your own locale file or override. [See moment's docs](http://momentjs.com/docs/#/i18n/).

Duplicate of #1013, #518, #345 and #670

**Comment by Tisiber** [comment]
Perfect, solved, thank you
