### ISSUE TITLE
How to hide the date time picker after the selection of date?

### ISSUE THREAD

**Issue by 2arunpmohan** [Eonasdan/bootstrap-datetimepicker#1264]
In my app, I just need the date to be inputted. So I have hidden the time picker. But the problem is that, after the selection of date, I need to hide the calender. Is this possible?

**Comment by Eonasdan** [comment]
the picker already hides if you're just using the datepicker. Beyond that you can listen for the change event and close it yourself

**Comment by bodrick** [comment]
My guess is that you have a format that specifies a time component, if you change the format to something that provides just a date you shouldn't have to worry about the time picker part.  An example you could try is "L", if you want other formats you can look here http://momentjs.com/docs/#/displaying/format/

**Comment by 2arunpmohan** [comment]
I solved the issue,by setting "pickTime" to false.
I did it like below:
$(function () { 
   $('.custom-datetimepicker').datetimepicker(
                { format: "DD/MM/YYYY", pickTime: false}); });
