### ISSUE TITLE
Question: What is the difference to eternicode/bootstrap-datepicker?

### ISSUE THREAD

**Issue by dialogik** [Eonasdan/bootstrap-datetimepicker#1266]
Hi, there is another very similar and popular repository on github, https://github.com/eternicode/bootstrap-datepicker. That very much seems to be a lot like this project.

Are there any major differences between both? When should I use one or the other?

**Comment by Eonasdan** [comment]
There are similarities and their differences. My package relies on momentjs for the date/time handling.

I can't tell you which to choose

**Comment by dialogik** [comment]
Ah yeah, that kind of info about the usage of `momentjs` was what I was looking for. Thanks!
