### ISSUE TITLE
ShowClose does not render a close icon when SideBySide is set true

### ISSUE THREAD

**Issue by bussemac** [Eonasdan/bootstrap-datetimepicker#1267]
See http://codeply.com/go/3LRYUygdiL

In the second example, there is no close button anywhere. If this is "working as intended" it should at least be documented, but I would prefer seeing a close button actually be rendered (perhaps at top-right, where users would normally look).

**Comment by madsbrydegaard** [comment]
This problem also extends to clear button not shown in sideBySide mode.
Any fix or workaround?

**Comment by Eonasdan** [comment]
have either of you tried the latest version?

**Comment by madsbrydegaard** [comment]
Downloaded master branch today

**Comment by bussemac** [comment]
Updated the codeply; problem persists. http://www.codeply.com/go/3LRYUygdiL

**Comment by Eonasdan** [comment]
works for me: http://jsfiddle.net/Eonasdan/0Ltv25o8/1825/

**Comment by bussemac** [comment]
Hm. Either there's a more recent change without a new version number, or the CDN at CloudFlare is lying about what version it has and the comments at the top of the files are bogus too.
https://jsfiddle.net/thwfgL6n/1/

**Comment by GerardBrouwer** [comment]
Also not working for me, also on latest version.

**Comment by waltsatan** [comment]
I discovered that setting `toolbarPlacement:'bottom'` in the initialize options fixes this.

**Comment by DePalmo** [comment]
Confirming that @waltsatan solution works, without that option, the close/clear/today buttons do not show.
