### ISSUE TITLE
Avoid use of moment.js

### ISSUE THREAD

**Issue by pensiero** [Eonasdan/bootstrap-datetimepicker#1268]
Hi, is it possible to avoid the use of moment.js? The entire moment.js file, compressed, is ~36kb (moment without all locales, but only with the single locale I need)...it's really a lot of space, considering that I only need to translate some strings.

Thanks

**Comment by Eonasdan** [comment]
nope. this package is totally based on momentjs. You can use a cdn if the file size is an issue. There are other pickers that don't use momentjs

**Comment by pensiero** [comment]
And what do they use instead?

**Comment by Eonasdan** [comment]
they either use a different date time library or they just use the built in javascript d/t stuff. moment is well worth the weight

**Comment by pensiero** [comment]
Ok
