### ISSUE TITLE
DateTimePicker does not work with ISO 8601 datetime format

### ISSUE THREAD

**Issue by Halofreak1990** [Eonasdan/bootstrap-datetimepicker#1271]
We are developing a web application that deals with multiple time zones. As the server is unaware of the client's time zone, the server sends UTC datetimes in ISO 8601 format to the client, which are then fed to the datetimepicker. Here lies the problem; the datetimepicker does not handle this format correctly, and the hours value defaults to 20, regardless of the value in the datetime string. As any and all datetime entries are done using the datetimepicker, this is a major issue for us.

A quick test, in which I read out the ISO datetime using moment.utc() revealed that while moment correctly interprets the value as an UTC datetime, the same does not apply to the datetimepicker.

**Comment by Eonasdan** [comment]
please post a fiddle or at least the format string you're using

**Comment by Halofreak1990** [comment]
@Eonasdan The format used is like so: 2015-08-17T15:22:54Z

You can find a JSFiddle here: http://jsfiddle.net/ogtybrq2/1/

**Comment by bodrick** [comment]
So I fixed this issue by adding to the extraformats of the date time picker, I just added : 'extraFormats': [moment.ISO_8601],

**Comment by Eonasdan** [comment]
Yup. I was just about to suggest that adding the `extraFormats` option was what you needed. Your input's value string doesn't match the `format` you provided.

@bodrick nice find on `moment.ISO_8601` didn't realize that was an option

**Comment by Eonasdan** [comment]
You might also be interested to know that the dev branch as TZ support thanks to a recent PR

**Comment by Halofreak1990** [comment]
@Eonasdan I see. So I should fetch the dev branch and use that one, or specify the 'extraFormats'?

**Comment by Eonasdan** [comment]
that depends on if you need it the tz support or not. try extraformats first

**Comment by Halofreak1990** [comment]
extraFormats did the trick. Thanks for the help.
