### ISSUE TITLE
Show only timepicker

### ISSUE THREAD

**Issue by BenevidesLecontes** [Eonasdan/bootstrap-datetimepicker#1272]
Hi all! I want to use this plugin and i want to use date and time separately, both as input, is this possible?

**Comment by Eonasdan** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/FAQ/

**Comment by BenevidesLecontes** [comment]
Thanks for quick reply, it works. I'm some Bootstrap modal problems, the dropdown widget doesn't appear. I'm using the latest bootstrap, i tried all z-index suggestions, but nothing happens. Bootstrap now use z-index = 1050 on modals.
