### ISSUE TITLE
extra days appearing

### ISSUE THREAD

**Issue by pine3ree** [Eonasdan/bootstrap-datetimepicker#1276]
Browsing dates between 1970 and 1979 1 extra day appear on every May.

mmm...seems js-engine browser related
browser affected chromium 37.0.2062.120

**Comment by Eonasdan** [comment]
yup this is a browser issue. I believe it's due to how certain locales deal with daylight savings time, see #1243 and #881 and more. I thought I fixed it with `4.13.28` but it's resurfaced it seems.  It doesn't happen to me so it's hard to troubleshoot.
