### ISSUE TITLE
Mobile screen usage

### ISSUE THREAD

**Issue by vkomphasouk** [Eonasdan/bootstrap-datetimepicker#1277]
I have the picker hooked up with the calendar icon and an input. It works wonders on the desktop. However, on a mobile device (iPhone 6), when I click on the calendar icon, both the picker and the built in Safari keyboard shows up, which is not ideal since half of the picker is cut off due to the keyboard. Any way to not have the keyboard show up and just show the picker? I couldn't really find any examples for mobile device use with the picker. 

Not sure if this is an issue or just how the picker is supposed to be used. Any recommendations for use on a mobile device would be helpful.

Thanks

**Comment by vkomphasouk** [comment]
Ok, after searching around I found out by section **focusOnShow: false** the keyboard does not popup on a mobile devices. However, now i'm able to open more than 1 picker at a time.

**Comment by digitalfrost** [comment]
+1 for a section on Mobile screen usage in the docs
@vkomphasouk did you manage to fix / work around this problem?
Are you experiencing the same issue on Android?

**Comment by SgtOddball** [comment]
I can attest to having the same issue on Android. Might be a case of adding another check if there's a calendar already open and closing it down if it already exists. 

As an extra question @vkomphasouk does it scroll down the page on iPhone when the input is selected, so that the input box is at the top of the page, causing the calendar to appear above the input and so off screen?

**Comment by FBosler** [comment]
can you guys actually pick dates on mobile? doesn't really work for me :( The picker would open, and then after clicking on a date or time it would close, but won't take the picked date into consideration.

**Comment by KryptikOne** [comment]
@vkomphasouk I used the combination of adding the `readonly="readonly"` attribute on the input and using the following on my config...
```js
$('#start_control').datetimepicker({
    minDate: startDate,
    maxDate: endDate,
    stepping: 60,
    toolbarPlacement: 'top',
    focusOnShow: false,
    ignoreReadonly: true
});
```

`focusOnShow` and `ignoreReadonly` being the important options there.

**Comment by Anachin** [comment]
doesn't work on Android Devices,

**Comment by glendlockhart** [comment]
Seems to work on htc one m7 - using lollipop (android 5.0) and on kitkat (4.4) and on iphone 6.

**Comment by michaelimstepf** [comment]
+1 for @KryptikOne's solution, tested on Chrome for iOS and Safari on an iPhone 5s with iOS 9.2.1

**Comment by kriswebdev** [comment]
KryptikOne solution has the adverse effect that we clicking on the rest of the page doesn't close the datetime picker anymore.
