### ISSUE TITLE
dp.change Firing when initializing..

### ISSUE THREAD

**Issue by KpjComp** [Eonasdan/bootstrap-datetimepicker#1278]
When initializing a DateTime input I've noticed it fires the dp.change event,..
This to me seems inconsistent with the way a normal inputs change event is fired.
IOW: I would be nicer if the event is only fired when the user changes the input.
I've implemented a simple fix that seems to work, basically change the notifyEvent to ->

``` javascript
notifyEvent = function (e) {
     if (e.type === 'dp.change' && ((e.date && e.date.isSame(e.oldDate)) || (!e.date && !e.oldDate))) {
          return;
     }

     //Prevent trigger if initializing, basically if the DateTimePicker
     //data is not yet set, where still initializing
     if (!element.data('DateTimePicker')) return;
     //End mod

     element.trigger(e);
},
```

**Comment by LarsBlaabjerg** [comment]
I second this

**Comment by ungue** [comment]
+1 to avoid change event when the control is initialized. The issue is given in those lines when plugin is invoked:
``` javascript
        if (input.is('input') && input.val().trim().length !== 0) {
            setValue(parseInputDate(input.val().trim()));
        }
        else if (options.defaultDate && input.attr('placeholder') === undefined) {
            setValue(options.defaultDate);
        }
```
When `setValue` is called, then the change event is triggered and this is really annoying.
An easy solution could be adding a second parameter to setValue in order to avoid event triggering and use it when control is instantiated.

``` javascript
...
 if (input.is('input') && input.val().trim().length !== 0) {
   setValue(parseInputDate(input.val().trim()), {silent: true});
 }
...
```

**Comment by HomerSimpson** [comment]
Hello,
A solution is to save an attribute when the calendar is shown at once. In this case, it's possible to know that it's not fired at startup.

```
$(document).on('dp.change', '.formAutoSubmit input', function(e) {
	var shown = $(this).attr('dp.shown');
	if (typeof shown != 'undefined' && shown && e.date != e.oldDate)
		console.log('this event is fired only when input has changed and not at startup!');
});

$(document).on('dp.show', '.formAutoSubmit input', function(e) {
	$(this).attr('dp.shown', 1);
});
```
