### ISSUE TITLE
maxDate blocks any manually set value for the date

### ISSUE THREAD

**Issue by kbaggott** [Eonasdan/bootstrap-datetimepicker#1279]
When setting the datetimepicker on a text input and setting the default date manually in the value, maxDate doesn't take this into account and overwrites it because the default date (today) may be after the maxDate.

JSFiddle: http://jsfiddle.net/0Ltv25o8/1712/

For example:

``` html
<!-- HTML -->
<input type="text" class="datetimepicker" value="2015-08-01"/>
```

``` Js
//JS
$('.datetimepicker').datetimepicker({
  format: 'YYYY-MM-DD',
  maxDate: moment().subtract(1, 'days')
});
```

Will result in the input showing yesterdays date, not the value of the input.
I believe all that's need to fix this is the addition of two checks found in the defaulDate function, as follows:

``` Js
//JS
//Line:1638

//From:
if (options.useCurrent && !options.keepInvalid && date.isAfter(maxDate)) {
  setValue(options.maxDate);
}

//To this:
if (options.useCurrent && !options.keepInvalid && date.isAfter(maxDate) && input.val().trim() === '' && input.attr('placeholder') === undefined) {
  setValue(options.maxDate);
}
```

This should stop maxDate overriding any values or placeholders explicitly set in the HTML.

**Comment by Cruiser13** [comment]
+1 with this issue
The solution does not check if the manual value is valid though. At the moment valid values are cleared too.

**Comment by samir-kamble** [comment]
+1 with this,

I have set **defaultDate** with a variable. Works well if i dont set **maxDate**. 

But if I set it. It overrides **defaultDate** with current date.

Please help.

**Comment by dstream** [comment]
If your maxdate is currently date you can use set maxDate: 'now' instead of new Date() or moment(), the issue will be gone ;)
