### ISSUE TITLE
Error with date time field pop up.

### ISSUE THREAD

**Issue by wpoosanguansit** [Eonasdan/bootstrap-datetimepicker#1280]
Hi,

I am using the latest js file and I keep getting the following error:

bootstrap-datetimepicker.js:430 Uncaught Error: datetimepicker component should be placed within a relative positioned container

Appreciate any guide in resolving the issue.  Thanks.

**Comment by Eonasdan** [comment]
Just like the error states, the picker needs to be in an element with `position:relative`.

**Comment by wpoosanguansit** [comment]
Thank you.
