### ISSUE TITLE
DateTimePicker appears behind Bootstrap 2.3.x Modals

### ISSUE THREAD

**Issue by holmes2136** [Eonasdan/bootstrap-datetimepicker#1282]
The following is my jsfiddle
http://jsfiddle.net/r61wbrhq/1/

According to previous issues , i would like to fix 

this issue by z-index , but it still  not working ,

any advise would be thanks !

**Comment by Eonasdan** [comment]
BS 2 is not supported. it's not about the z-index in the case, it's about the body height of the modal. trying setting the min-height
