### ISSUE TITLE
I set maxdate yesterday, how to make today still have blue background but still disabled?

### ISSUE THREAD

**Issue by donnygunawan93** [Eonasdan/bootstrap-datetimepicker#1286]
I set maxdate yesterday, how to make today still have blue background but still disabled?

**Comment by Eonasdan** [comment]
each date has a `data-date="DATE"` and a class of `day` and today has a class of `today` so you can add whatever styles you want to it

**Comment by donnygunawan93** [comment]
.day.today.active{
    background-color: red;
  }

yes, today is red,

but when i set options maxdate into yesterday,
today has disabled and not red anymore.

is possible for today to still disabled, but have red background?
