### ISSUE TITLE
How to include bootstrap-files correctly?

### ISSUE THREAD

**Issue by mb13** [Eonasdan/bootstrap-datetimepicker#1287]
I've spent many hours with bootstrap-datepicer, but I'm still not able to make it functional :(

I followed "Manual" instructions: jquery, moment, transition, collapse are OK
But where do I find "bootstrap.min.js" ?

**Comment by Eonasdan** [comment]
you'll either need to inlcude Bootstrap from a CDN or download it from http://getbootstrap.com/getting-started/#download

**Comment by mb13** [comment]
I would like to have the 3rd example functional from page (just hours and minutes):

http://eonasdan.github.io/bootstrap-datetimepicker/


I have the following .html file:


<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<script type="text/javascript" src="jquery.min.js"></script>
<script type="text/javascript" src="moment.js"></script>
<script type="text/javascript" src="transition.js"></script>
<script type="text/javascript" src="collapse.js"></script>
<script type="text/javascript" src="bootstrap.min.js"></script>
<script type="text/javascript" src="bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="bootstrap-datetimepicker.min.css" />


</head>

<body>


<div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker3'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker3').datetimepicker({
            format: 'LT'
        });
    });
</script>

</body>

</html>


and all the files are located in the same directory where is the .html file. Yet it is not working... :(

**Comment by Eonasdan** [comment]
You don't need:
```
<script type="text/javascript" src="transition.js"></script>
<script type="text/javascript" src="collapse.js"></script>
```
if you have: (assuming you didn't customize bootstrap to remove them)
```
<script type="text/javascript" src="bootstrap.min.js"></script>
```

What does "not working" mean?

Do you have any console errors?

**Comment by mb13** [comment]
okay, I removed transition.js and collapse.js, but nothing has changed...
I have an empty input-text field, no errors on console, but the "time-hours-AM/PM" windows is not popping up for me, like in the example on your page.

**Comment by Eonasdan** [comment]
please post a project somewhere with your setup.

**Comment by mb13** [comment]
could you like send me a zip file with an HTML in which is your datepicker located and also with .js files... thx

**Comment by Eonasdan** [comment]
No, sorry. I don't have time for that. **You** can zip **your** project. You can use the any of the installation methods to get your project working.
