### ISSUE TITLE
How can I match the dropdown width to the parent input?

### ISSUE THREAD

**Issue by wjxtc** [Eonasdan/bootstrap-datetimepicker#1288]

**Comment by wjxtc** [comment]
what requirements?

**Comment by Eonasdan** [comment]
When creating a new issue:

![image](https://cloud.githubusercontent.com/assets/1006516/9547772/a0ba2ba8-4d6a-11e5-84ec-fa2def323ab9.png)

https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/CONTRIBUTING.md
