### ISSUE TITLE
Disabled Day of Week setting changes initial date value

### ISSUE THREAD

**Issue by benr77** [Eonasdan/bootstrap-datetimepicker#1289]
When using daysOfWeekDisabled - if an existing value is defined in the form field then this is modified upon initialisation to show the next allowable date in the future as defined by the allowable days of the week

`<input type="text" class="form-control" id="datetimepicker2" data-date-format="DD MMMM YYYY" data-date-view-mode="months" data-date-days-of-week-disabled="[0,1,2,3,4,5]" value="08 August 2015" />`

i.e. if the date is Thursday 27th August and only Saturdays are permitted, the existing form field value is ignored and field value is modified to be the next Saturday in future after the 27th August - in this case the 29th August.

This is before you click on a date field to pop-up the date picker.

See JSFiddle for example behaviour
https://jsfiddle.net/benr77/jou6dwo3/1/

**Comment by benr77** [comment]
After further investigation I see that explicitly setting `data-date-use-current="false"` corrects this behaviour. (from a hunch from reading #885)

However, reading the docs at https://eonasdan.github.io/bootstrap-datetimepicker/Functions/#usecurrent it states that if the field already has a valid value then the use of useCurrent is ignored. In the case described by my previous post this is not the case so I still think this is a bug or the documentation needs amending.

**Comment by NoCoffeeBreaks** [comment]
I have experienced this problem as well

**Comment by SayyesTono** [comment]
benr77, you are a life saver!!! The data-date-use-current="false" works like a charm. EXCELLENT job there buddy!
