### ISSUE TITLE
Either an input value format issue or input value disables defaultDate

### ISSUE THREAD

**Issue by mnovotny** [Eonasdan/bootstrap-datetimepicker#1290]
If the `<input>` element contains its own datetime `value` the datetime picker makes the input textbox appear empty despite a correct `defaultDate` specified.

Here's a [jsfiddle](http://jsfiddle.net/es1xdwb0/7/)

A temporary workaround would be to delete the `value` attribute from the `<input>` element. The default date is correctly displayed then. But that's against graceful degradation principles.

**Comment by scuba6388** [comment]
I feel as if the datetimepicker should use existing values upon initialization.  I see in the js that default date is not used if there is an existing value.  Have you found any better ways to accomplish this?  Am I doing something wrong.

**Comment by mnovotny** [comment]
I found out that this was indeed an input format issue. Apparently, the `value `of the `<input>` element has to match the datetime string formatting of the specified datetimepicker  `locale`. 

Here's a working demonstration: [jsfiddle](http://jsfiddle.net/es1xdwb0/9/)
