### ISSUE TITLE
How to change the popup title

### ISSUE THREAD

**Issue by bradwoo8621** [Eonasdan/bootstrap-datetimepicker#1291]
I set the option `dayViewHeaderFormat : 'YY MM'`, works fine.
but if set the option `format: 'YYYY/MM'` or `format: YYYY`, the `dayViewHeaderFormat` doesn't work.

the question is how change the popup title in those scenarios?

thank you very much.

**Comment by Eonasdan** [comment]
please post a jsfiddle of your issue

**Comment by bradwoo8621** [comment]
Hi Eonasdan,

thank you for your quickly reply, I post the code at https://jsfiddle.net/g732wys4/

the first is default format, and set as `dayViewHeaderFormat: 'YY MM'`, 
and the second is set `format: 'YYYY/MM'` and `dayViewHeaderFormat: 'YY'`  

I guess the `dayViewHeaderFormat` is only effective when the format contains days, but is there any way to change the title if there is no days visible?

thank you very much.

**Comment by Eonasdan** [comment]
ah. `dayViewHeaderFormat` only affects the days view mode. There's no option to override the other headings

**Comment by bradwoo8621** [comment]
will you consider to add this option? 
as you know, there are many special formats in the world. in my project, my client is Taiwanese, and their format is three digits years. eg. 1912 will be displayed as 1, and 2015 will be displayed as 104.

your component is really powerful and friendly to use, but seems too hard to fit this special requirement. 

btw, the Japanese format is also very special...

**Comment by bradwoo8621** [comment]
Hi Eonasdan,

I've implemented the Taiwan format base on momentjs, see https://github.com/bradwoo8621/moment-taiwan

and here is the screenshot
![1](https://cloud.githubusercontent.com/assets/2330098/9852638/f654ea7e-5b31-11e5-8257-cfbae6d5a970.png)


and I try to learned your source code, find there are 3 points to resolve the problem:  
```javascript
updateMonths = function () {
    monthsViewHeader.eq(1).text(viewDate.year());
}
updateYears = function () {
    yearsViewHeader.eq(1).text(startYear.year() + '-' + endYear.year());
}
updateDecades = function () {
    decadesViewHeader.eq(1).text(startDecade.year() + '-' + endDecade.year());
}
```

I guess maybe you can add an option(maybe `xxxViewHeaderFormat ` to format the year, will you consider the suggestion?

thank you very much.
