### ISSUE TITLE
Error while selecting time

### ISSUE THREAD

**Issue by parismo** [Eonasdan/bootstrap-datetimepicker#1293]
I got error while selecting minutes or hours..

<code>bootstrap-datetimepicker.js:1061</code>

<code>
Uncaught TypeError: widget.find is not a functionactions.showPicker @ bootstrap-datetimepicker.js:1061actions.selectMinute @ bootstrap-datetimepicker.js:1100doAction @ bootstrap-datetimepicker.js:1123jQuery.event.dispatch @ jquery.js:4430jQuery.event.add.elemData.handle @ jquery.js:4116</code>

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.

**Comment by parismo** [comment]
I solved my problem. My own directive had action onblur which caused this error.

**Comment by FBosler** [comment]
Hi Parismo

My time part is still a bit buggy, any idea why? It says widget.find() is not a function. Please find attached a widget. You said you had a problem with onblur. I do not have that. Any ideas?
http://jsfiddle.net/fbosler/516zsh7b/7/

Thanks again!

**Comment by parismo** [comment]
Hi Fbosler

Try this http://jsfiddle.net/d71m6nau/
changes when blur (click out of widget)
