### ISSUE TITLE
multiple datetimepicker on modal not working well

### ISSUE THREAD

**Issue by finalight** [Eonasdan/bootstrap-datetimepicker#1295]
I attempt to create multiple datepicker on a modal dialog

and this happens

the first date picker is still okay
<img width="625" alt="19e1eb34-4d10-11e5-86bb-5b047f3bdfd9" src="https://cloud.githubusercontent.com/assets/4475526/9567667/83cb8872-4f66-11e5-9e81-739c4ec6d7bb.png">

however the second one has this problem...
<img width="597" alt="1c264e26-4d10-11e5-8d21-050b6287b3d4" src="https://cloud.githubusercontent.com/assets/4475526/9567668/849513ea-4f66-11e5-8b32-07d1adb2daf7.png">

same goes for the third one..

<img width="627" alt="1f0a0704-4d10-11e5-89af-f0806b161529" src="https://cloud.githubusercontent.com/assets/4475526/9567669/85afad94-4f66-11e5-9071-6a95cbbe1456.png">

any idea on how to fix this?

**Comment by ddelella** [comment]
They appear to be working just fine in the latest version for me (4.15.35).  Make sure you do not have any other CSS which could be interfering.

**Comment by finalight** [comment]
this is very serious problem:

if it's CSS interfering with it; it would have affect all datetimepicker already, and not only just the first one.

so that's why I don't think it's my CSS at all, but rather the way it works with angular

**Comment by ddelella** [comment]
I think the key was that you did not initially say it was using AngularJS.  That might be it since I am not using that and mine is working.
