### ISSUE TITLE
I need manage timestamp with time zone (1994-11-05T13:15:30Z) for postgresql any datetimepicker that works with this? 

### ISSUE THREAD

**Issue by josemadev** [Eonasdan/bootstrap-datetimepicker#1296]
If I configure -> format : 'YYYY-MM-DDThh:mm:ssZ' it works but i cant visualize in this format .

**Comment by Eonasdan** [comment]
What does "but i cant visualize in this format" mean?

Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.

**Comment by josemadev** [comment]
https://jsfiddle.net/Eonasdan/0Ltv25o8/
My english is not well sorry i try to explane :)

**Comment by Eonasdan** [comment]
your link points to the base fiddle, did you fork or update it?

**Comment by josemadev** [comment]
http://jsfiddle.net/jsanchez/nnjud8qd/

**Comment by Eonasdan** [comment]
sorry, but there's still no changes. I don't see what you're trying to do. When you make changes, be sure to click "Update" and provide the new link

**Comment by josemadev** [comment]
https://jsfiddle.net/jsanchez/nnjud8qd/2/

**Comment by josemadev** [comment]
sorry first time with jsfiddle

**Comment by Eonasdan** [comment]
Ah! Ok. If I understand you correctly, you need to set the option `extraFormats : ['YYYY-MM-DDThh:mm:ssZ']` like this. `extraFormats` allows other input formats to be accepted.

You will either need to hook into the form submit to parse the date back into a database format, or parse it on the server side.

**Comment by josemadev** [comment]
Thanks,  is it possible format the output  to ISO?

**Comment by Eonasdan** [comment]
You can use `moment.ISO_8601` as a format string. You can use the `.date()` function on the picker to get a momentjs object. Then call `.date().format(moment.ISO_8601)`

**Comment by josemadev** [comment]
Thanks you for the patience! ;)

2015-08-31 17:46 GMT+02:00 Eonasdan <notifications@github.com>:
