### ISSUE TITLE
JqGrid + datetimepicker + bootstrap 3

### ISSUE THREAD

**Issue by arleybequadro** [Eonasdan/bootstrap-datetimepicker#1297]
Hi, 

I've been in trouble when trying to open datetimepicker as a jqGrid column. It has been limited by the jqGrid space. You will find an example in JsFiddle link above. 
http://jsfiddle.net/cmpgtuwy/103/

Also, I tried to make some changes in the css as adding "z-index" in ".bootstrap-datetimepicker-widget" class with no success. 

Please, see my example and let me know if you have any clue.

Thanks in advance

**Comment by dylanmensaert** [comment]
This is not an issue related to bootstrap-datetimepicker.

Please use the provided forums for these type of questions: http://stackoverflow.com
