### ISSUE TITLE
Can't select tomorrow as date

### ISSUE THREAD

**Issue by albertoeps** [Eonasdan/bootstrap-datetimepicker#1300]
In this JsFiddle, the user can not select the date following the current one (that is, the user cannot select tomorrow as the date). Why is that?

http://jsfiddle.net/0Ltv25o8/1794/

This code is being used in a production site, and we didn't have any reports of this issue before today; however, when we test it setting our computer's date to a previous date (August), it happens too.

**Comment by jlsalvador** [comment]
The same problem like #1302

**Comment by Eonasdan** [comment]
please check the latest version (4.17.37) as it appears to be fixed

**Comment by Eonasdan** [comment]
also, you don't need to do `var m = moment(new Date());` you can just use `moment()` it already calls `new Date()`

**Comment by Eonasdan** [comment]
please check the dev branch
