### ISSUE TITLE
[BUG] Impossible to select today date when minDate is enabled

### ISSUE THREAD

**Issue by pensiero** [Eonasdan/bootstrap-datetimepicker#1302]
You can see an example [here](https://www.uala.it/), if you try to select today from the datepicker that appear in the search bar when you click on 'Quando?', nothing happen.

Thanks

**Comment by Eonasdan** [comment]
please provide the code you are using for the datepicker

**Comment by pensiero** [comment]
Sure
```js
$('.search-date input').datetimepicker({
    useCurrent: false,
    locale: 'it',
    dayViewHeaderFormat: 'MMMM',
    format: 'DD/MM/YYYY',
    minDate: new Date(),
    widgetPositioning: {
        horizontal: 'auto',
        vertical: 'bottom'
    },
    icons: {
        date: 'icon icon-calendar',
        up: 'glyphicon glyphicon-chevron-up',
        down: 'glyphicon glyphicon-chevron-down',
        previous: 'icon icon-arrow-small-left',
        next: 'icon icon-arrow-small-right',
        today: 'glyphicon glyphicon-screenshot',
        clear: 'glyphicon glyphicon-trash'
    }
}).on('dp.hide', function() {
    $(this).blur();
});
```

```html
<div class="search-date">
    <input name="date" type="text" placeholder="Quando?" />
</div>
```

Thanks

**Comment by Eonasdan** [comment]
You're setting the `minDate` to today, which means won't be able to select it.

Instead, set `minDate` to `minDate: moment().subtract(1,'d')` which will be yesterday.

**Comment by pensiero** [comment]
I tried to do that, and in that way I can select *today*, but it appears that *yesterday* could be clickable (while the previous days appear as grey instead of black and if you move the mouse over them, it appears a circle with a stroke instead of the classic mouse pointer).

**Comment by pensiero** [comment]
In fact, now if I set the `minDate` to today, the today date appear to be clickable, while yesterday not (the mouse pointer change when you hover it on yesterday, and it's ok, but it should be the same also for today).

I hope I explain myself well, I can't do a screenshot of the pointer unfortunately.

**Comment by pensiero** [comment]
@Eonasdan Do I explain not well? Can I provide some other element to help?

**Comment by jlsalvador** [comment]
@pensiero
I have the same problem.

@Eonasdan Your solution isn't correct because of that:
`minDate = moment().subtract(1,'d') // But 2015/09/09 has not the class disabled`
![snapshot19](https://cloud.githubusercontent.com/assets/1464850/9786801/305cd812-57bd-11e5-9c44-5ca51d120f7c.png)

So...
Changes:
-------------
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L516
```
                if (options.minDate && (targetMoment.isBefore(options.minDate, granularity) || targetMoment.isSame(options.minDate, granularity))) {
```
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L519
```
                if (options.maxDate && (targetMoment.isAfter(options.maxDate, granularity) || targetMoment.isSame(options.maxDate, granularity))) {
```

**Comment by pensiero** [comment]
Thanks @jlsalvador

**Comment by jlsalvador** [comment]
The real bug is about when you use `minDate="now"` or `"minDate="moment"`. Because `minDate` or `maxDate` has hours, minutes and seconds; but when you click in a day, you are setting to 00:00:00 (that is before from minDate).

![snapshot19](https://cloud.githubusercontent.com/assets/1464850/9788045/bfcd0652-57c7-11e5-8ff4-a3603026cd71.png)
![snapshot19](https://cloud.githubusercontent.com/assets/1464850/9788030/96794266-57c7-11e5-9b28-787ad4be1105.png)

**Comment by pensiero** [comment]
So how can we solve?

**Comment by jlsalvador** [comment]
Was fixed in the development branch :-(

**Comment by pensiero** [comment]
Good :+1: thanks a lot both! When you think it will be released?

**Comment by Eonasdan** [comment]
pushed 4.17.35 last night. If it's fixed, please let me know so I can close this

**Comment by pensiero** [comment]
Unfortunately it appear not to be fixed :(

**Comment by pensiero** [comment]
I tried also replacing `minDate: new Date(),` with `minDate: moment(),`, but the 'today' date is still clickable, and if I click on it, it doesn't do anything.

**Comment by pensiero** [comment]
@Eonasdan if I can help you in any ways please tell me :)

**Comment by Eonasdan** [comment]
@pensiero you can check the dev branch. I pushed another change that might fix it

**Comment by pensiero** [comment]
@Eonasdan there are some improvements, but still some problems:
- if there is no value in the input field, you open the datetimepicker and you select *today*, the input value is filled with the today date (so it's ok)
- after doing this, if you change the date and then change again to the today date, the input will not update with the today date (and this is not ok, same behaviour of the first bug reported in this conversation)

**Comment by alundstroem** [comment]
Hi, I stupidly created https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1333 (: this issue is the same as mine so I closed mine and subscribed to this one instead!

**Comment by alundstroem** [comment]
Workaround, set minDate to moment().millisecond(0).second(0).minute(0).hour(0)

Seems to work for me..

**Comment by pensiero** [comment]
IT WORKS! Thanks @alundstroem

**Comment by alundstroem** [comment]
Great (: its all thanks to @jlsalvador for pointing it out in his comment 11 days ago: "The real bug is about when you use minDate="now" or "minDate="moment". Because minDate or maxDate has hours, minutes and seconds; but when you click in a day, his time is 00:00:00 (that is before minDate)."

**Comment by alundstroem** [comment]
And also @iforlife that posted a line in his issue on the same matter, https://github.com/Eonasdan/bootstrap-datetimepicker/issues/953: minDate: new Date().setHours(0,0,0,0) -> WORKS

**Comment by pensiero** [comment]
:+1:

**Comment by vijender1256** [comment]
@pensiero you are awesome man thanks for asking the question, I am breaking my head from hours now, and the workaround just solved the issue :)

**Comment by pensiero** [comment]
ahahah i'm only a normal developer with lot of problems to solve! :D

**Comment by vijender1256** [comment]
@pensiero I am trying to edit an existing date that is read from database, and here is the code

  $('#startDate').datetimepicker({
            useCurrent: false,
            format: 'MM-DD-YYYY',
            ignoreReadonly: true,
            minDate: moment().millisecond(0).second(0).minute(0).hour(0)
        });

when i put minDate at the time of calendar initialization, It is clearing the existing value in the textbox. any help is appreciated :)

**Comment by jlsalvador** [comment]
@vijender1256 That's not this bug. Please keep clean the issue (open another issue). Thanks.

**Comment by Kerumen** [comment]
@alundstroem A shorter way to write it: `moment().startOf('d')`

**Comment by Renkas** [comment]
This workaround you guys provided is not a fix. And the problem exists still.

With this workaround the user could select todays date with a time that is in the past. But I need also the current time.

What I expect to happen when I click on todays time when `minDate = new Date()` is that the value would be set to `minDate`. It should not be a hard thing to implement I think. Something in the likes of: if date is selectable (is clickable in picker) but fails the minDate constraint then set value to minDate.

**Comment by Eonasdan** [comment]
setting min**Date** to now or `new Date()` or `moment()`, you are saying the lowest point a user can select is **today**.
