### ISSUE TITLE
how to do datetimepicker from & to validation on page load 

### ISSUE THREAD

**Issue by sushant357** [Eonasdan/bootstrap-datetimepicker#1303]
I want to validate fromDate & toDate onload.
I have dafult date on from & to. If i directly changed toDate to lesser than fromDate it's allowing me to select the date. how can I validate that ?

**Comment by Eonasdan** [comment]
all options have getter/setter functions `$('#datetimepicker').data("DateTimePicker").FUNCTION()` so you could do `var maxDate = $('#datetimepicker').data("DateTimePicker").maxDate()`

**Comment by William-H-M** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers
