### ISSUE TITLE
Incomplete rendering since chrome v45

### ISSUE THREAD

**Issue by dylanmensaert** [Eonasdan/bootstrap-datetimepicker#1305]
Since chrome changed from v44 to **v45**, the datepicker modal renders imcomplete **after** initial DOM injection.

This is caused when table or one of its ancesters traversing up in the DOM tree has `position: absolute;`

fiddle: http://jsfiddle.net/dylanmensaert/0Ltv25o8/1804/

**Comment by Eonasdan** [comment]
works for me Version 45.0.2454.85 m (64-bit)

**Comment by dylanmensaert** [comment]
I am on the same version as you.

Could you click datepicker #2 and click the click the time? The initial render is correct, but if you perform any onclick actions after that, you should see an incomplete rendering.

**Comment by Eonasdan** [comment]
what's really fun, is if you turn on `debug:true` and inspect element on the time picker... it renders

**Comment by dylanmensaert** [comment]
Yes, I noticed that to.

**Comment by Eonasdan** [comment]
wow... this is a really weird bug. If I break the hide function, inspect element and click **anywhere** else on the page it comes back!

This might be related to https://code.google.com/p/chromium/issues/detail?id=528229 and https://code.google.com/p/chromium/issues/detail?id=529879

Looks like they've updated that today. At this point I might wait for 46 to be released to before raking my brain about a Chromium problem

**Comment by Eonasdan** [comment]
Looks like this works properly in Version 47.0.2507.0 canary (64-bit)

**Comment by dylanmensaert** [comment]
Thanks for the feedback! I will have to wait till version 47.x then :/

**Comment by Eonasdan** [comment]
just updated to Version 45.0.2454.93 m (64-bit) and it looks like it's fixed there

**Comment by dylanmensaert** [comment]
I can confirm that this works for the newest version!
Thanks a lot, closing the issue.
