### ISSUE TITLE
Question - How dependent is this on bootstrap?

### ISSUE THREAD

**Issue by CharlotteAmyWilson** [Eonasdan/bootstrap-datetimepicker#1306]
We are thinking of teasing out bootstrap from our solution because there is quite a bit that we don't use and we want to reduce (where possible) the amount of 3rd party code we are dependent on.

I had a quick look in the js and it looks like there are a few dependencies on classes from bootstrap. This is manageable as we could just implement those classes if we were to not use bootstrap.

Are there any other dependencies (js or css) that you are aware of?

Thanks
Charlotte

**Comment by Eonasdan** [comment]
there's a stand alone css file in the development branch.

otherwise, momentjs is the only other dependency
