### ISSUE TITLE
Add support for displaying week days starting from monday

### ISSUE THREAD

**Issue by huksley** [Eonasdan/bootstrap-datetimepicker#1310]
Add support for displaying week days starting from monday

Currently Su Mo ... Sa
Must be possible to display Mo ... Sa Su
based on locale and/or configuration setting.

**Comment by Eonasdan** [comment]
the picker already does this. set the `locale` option appropriate and include the correct local file from momentjs

**Comment by digitalfrost** [comment]
See my comment to #1313. 
Having a good example in the docs of how to include the correct local file from momentjs would be great...

**Comment by huksley** [comment]
Yes. Adding moment-with-locales.js and using locale: "ru" in options results in days starting from Monday... Thanks for clarification.
