### ISSUE TITLE
Linked pickers first picker can go 1 hour past maxDate

### ISSUE THREAD

**Issue by Gloompirate** [Eonasdan/bootstrap-datetimepicker#1312]
I have a setup with 2 linked pickers. If I set a date in the first picker, and then one in the second one which becomes the maxDate of the first one, when I go back to the first picker I am able to select a time up to 1 hour after what should be the maxDate. The pickers are setup as shown in the docs:

Javascript:

    $('#start').datetimepicker({
        format: "HH:mm DD/MM/YYYY"
    });  
	$('#end').datetimepicker({
        useCurrent: false,
        format: "HH:mm DD/MM/YYYY"
    }); 
    $("#start").on("dp.change", function (e) {
        $('#end').data("DateTimePicker").minDate(e.date);
    });
    $("#end").on("dp.change", function (e) {
        $('#start').data("DateTimePicker").maxDate(e.date);
    });

HTML:

    <div class="form-group">
        <label class="col-md-3 control-label" for="start">Start</label>
    	  <div class="col-md-8">
		<div class="input-group date" id="start" name="start">
			<input type="text" class="form-control">
			<span class="input-group-addon">
				<span class="glyphicon glyphicon-calendar"></span>
			</span>
		</div>
	</div>
    </div>
    <div class="form-group" id="endgroup">
	<label class="col-md-3 control-label" for="end">End</label>
	<div class="col-md-8">
		<div class="input-group date" id="end" name="end">
			<input type="text" class="form-control">
			<span class="input-group-addon">
				<span class="glyphicon glyphicon-calendar"></span>
			</span>
		</div>
	</div>
    </div>

![image](https://cloud.githubusercontent.com/assets/12813867/9816663/5918494c-5896-11e5-9ae9-40e7c53b949c.png)

This can also happen the other way around, so that the second picker can be set upto an hour before the minDate.

**Comment by Eonasdan** [comment]
please post a jsfiddle of your issue
