### ISSUE TITLE
Documentation Cleanup

### ISSUE THREAD

**Issue by Eonasdan** [Eonasdan/bootstrap-datetimepicker#1313]
I feel as though the Functions and Options pages are too fat. Most, if not all, of the `option.---` have a related function that gets/sets that option. That said, the functions page could be greatly reduced by not re-explaining this.

Idea for change:
- Strip the Functions page down to a hand full of functions that aren't simple set actions (e.g. `viewDate`, you might actually call that)
- Re/Move get/set functions to the Options page with a brief explanation that most options are get/set-able.

Please leave a comment with a +/- 1 to vote

**Comment by digitalfrost** [comment]
Your proposal makes sense to me.

If you are working on the docs. I feel this is not clear:
http://eonasdan.github.io/bootstrap-datetimepicker/Options/#locale
(Mostly due to changes / lack of clear documention in moment.js?)
An example of loading another locale would be help full.
