### ISSUE TITLE
Margin on the input used for the datepicker throws off the positioning of the picker

### ISSUE THREAD

**Issue by cheeseweasel** [Eonasdan/bootstrap-datetimepicker#1314]
Fiddle demonstrating the issue here: http://jsfiddle.net/y99nfh90/

It's possible to work around this obviously by nesting the input within a div, and moving the margin on to that, but a better solution might be to pass true (includeMargin) to the outerHeight calls for setting the top and bottom values when positioning the picker.

**Comment by William-H-M** [comment]
Hi, or add a class like this that won't affect all input-addons, even does that are not DateTimePicker
```
input .input-group-addon{
  margin: 20px;
}
```
