### ISSUE TITLE
TypeError: locale() locale fr is not loaded from moment locales

### ISSUE THREAD

**Issue by digitalfrost** [Eonasdan/bootstrap-datetimepicker#1315]
I get this error and the datepicker does not "pop up" if I try to pass in a locale
```
TypeError: locale() locale fr is not loaded from moment locales!
    at Object.picker.locale (bootstrap3-datetimepicker.js:1720)
    at String.<anonymous> (bootstrap3-datetimepicker.js:1429)
    at Function.jQuery.extend.each (jquery.js:392)
    at Object.picker.options (bootstrap3-datetimepicker.js:1427)
    at dateTimePicker (bootstrap3-datetimepicker.js:2251)
    at HTMLInputElement.<anonymous> (bootstrap3-datetimepicker.js:2284)
    at Function.jQuery.extend.each (jquery.js:384)
    at jQuery.fn.jQuery.each (jquery.js:136)
    at $.fn.datetimepicker (bootstrap3-datetimepicker.js:2279)
    at null.<anonymous> (expiry_date_submit.js?225fe5e58d090f2ab70d3751ab16e2a9bcbb978e:2)
```
I am setting up the datepicker like this. Everything works fine if I remove the locale option.

```
Template.expiryDateSubmit.onRendered(function() {
    this.$('.datepicker').datetimepicker({format: "DD-MM-YYYY", locale: moment.locale('fr')});
});
```
I am loading the locales properly into moment.js. In the console I am able to do this

```
moment().format("dddd, MMMM Do YYYY, h:mm:ss a")
"dimanche, septembre 13 2015, 7:05:16 pm"
moment.locale()
"fr"
moment.locale("de")
"de"
moment().format("dddd, MMMM Do YYYY, h:mm:ss a")
"Sonntag, September 13. 2015, 7:05:43 pm"
```

**Comment by digitalfrost** [comment]
JSFiddle.

https://jsfiddle.net/bq0rwypb/

This tries to load the locale differently to what I am actually doing in my app but the result appears to be the same.

**Comment by RomeroMsk** [comment]
Why are you trying to load `fr` locale by yourself? It is already included into `moment-with-locales.js`. You just need to set it up in options like this (use the name of locale):
```javascript
$('#datetimepicker1').datetimepicker({
    locale: 'fr'
});
```
[Updated fiddle](http://jsfiddle.net/bq0rwypb/2/).

**Comment by digitalfrost** [comment]
It doesn't work either if I just do: __locale: 'fr'__

The documentation says locale "*Accepts: string, moment.local('locale')*" - so as I understand it I should be able to pass in __moment.locale('fr')__

**Comment by RomeroMsk** [comment]
I don't know about second variant, but it works with `'fr'` in my fiddle.

**Comment by jeremyVignelles** [comment]
Hi,
Just updated the jsfiddle to test with the latest version. I also added the tooltips option so that the picker is completely in french ;) (was needing this for my project and thought it would be nice to share) : 
http://jsfiddle.net/bq0rwypb/4/

**Comment by digitalfrost** [comment]
@jeremyVignelles - Thanks for sharing.
I still can't get this to work in my meteor project for some reason.
I will issue a pull request to tsega/meteor-bootstrap3-datetimepicker
to update to the latest version of bootstrap3-datetimepicker and see if this fixes the issue. I didn't realize the meteor  version had fallen out of sync with the original...

**Comment by digitalfrost** [comment]
Pull request issued.
I think the problem comes from the dependencies in the meteor package which cause it to load moment without locales rather than using the installed moment-with-locale package or file...

@Eonasdan would you accept a pull request to add official Meteor integration - which would auto sync the meteor package to the latest version of bootstrap-datetimepicker?

**Comment by Eonasdan** [comment]
@digitalfrost what would be involved with that?

**Comment by digitalfrost** [comment]
Adding the following Meteor integration files in a meteor folder
- package.js
- tests
- gruntfile (or makefile or equivalent) entries to run meteor publish

moment.js has an official meteor package. If you look at this folder you can see everything is pretty straight forward:

https://github.com/moment/moment/tree/develop/meteor
