### ISSUE TITLE
content not matched header in decade view

### ISSUE THREAD

**Issue by bradwoo8621** [Eonasdan/bootstrap-datetimepicker#1318]
![1](https://cloud.githubusercontent.com/assets/2330098/9857967/5cedc792-5b50-11e5-99d3-0d35dcdf2112.png)

header is 1999 - 2099, but the content is 2000 - 2107. only 9 blocks in content, and each content is 12 years, not 10 years.

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.
