### ISSUE TITLE
Problem with webpack

### ISSUE THREAD

**Issue by Dodelkin** [Eonasdan/bootstrap-datetimepicker#1319]
I try =>
import BootstrapDateTimePicker from "eonasdan-bootstrap-datetimepicker"; and console.log(BootstrapDateTimePicker);
And console.log return me empty object.

I try => 
import from "eonasdan-bootstrap-datetimepicker";
But i have Uncaught TypeError: $(".picker").datetimepicker is not a function

Please add module.exports = $.fn.datetimepicker; 
to 2551 line

**Comment by Eonasdan** [comment]
I have no idea what you're talking about.

**Comment by alexrm** [comment]
Hello, look, I met the same problem. That's what he tried to say.

He tried to import your plugin via require, but he gets empty object, when he did.

So he asks you to add module.exports

Regards!

**Comment by Eonasdan** [comment]
I don't know anything about require or webpacks. You're welcome to put in a pull request

**Comment by alexrm** [comment]
Well, I did pull-request which helps this situation. Hope you'll accept it ASAP. 
Thanks in advance!

**Comment by JanMalte** [comment]
@alxrm Could you link to the PR or state if it is already merged?

**Comment by alxrm** [comment]
@JanMalte https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1322

**Comment by JanMalte** [comment]
@alxrm Thanks. It looks like it wasn't merged but rejected.
Did you get this date picker to properly working with webpack?

**Comment by NeWbY100** [comment]
I ran into the same problem, and managed to solve/(hack around) it as follow:

- Create a new folder in the same folder as your node_modules, but call it custom_modules
- Inside the custom_modules folder, add a new folder eonasdan-bootstrap-datetimepicker
- Move the following files into custom_modules/eonasdan-bootstrap-datetimepicker
```
node_modules/eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js
node_modules/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css
```
- uninstall the eonasdan-bootstrap-datetimepicker project from node_modules
- In your webpack config, add the following:

> Under plugins, add:

```
  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    'windows.jQuery': 'jquery'
  })
```

> Under resolve, add:

```
    modulesDirectories: ['custom_modules', 'node_modules'],
    alias: {
      'datetimepicker': 'eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.js'
    }
```
- In the component you're using the datepicker, add the following at your imports:
```
import 'datetimepicker';
import 'style!css!eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.css';
```
- You should now be able to call the datetimepicker() on a jQuery object.

**Comment by aburkut** [comment]
I ran into the same problem too. Datetimepicker tries to load his own jQuery.
So the solution is very simple:

resolve: {
    alias: {
        'jquery': path.join(__dirname, 'node_modules/jquery/dist/jquery'),
    }
}

**Comment by kebian** [comment]
@aburkut Thank you.  I've been pulling my hair out for about 24 hours and that little alias fixes everything.  My webpack.config.js:

```js
var path = require('path');

module.exports = {
    resolve: {
        alias: {
            // Force all modules to use the same jquery version.
            'jquery': path.join(__dirname, 'node_modules/jquery/dist/jquery')
        }
    }
};
```

**Comment by sebastiaanluca** [comment]
Man, I've been looking for this solution for the past few hours. None of the plugins (datetimepicker, popover, tooltips) wanted to work and I always got a `Uncaught TypeError: $(…).datetimepicker is not a function`-like error. Had to be Webpack messing things up.

THANK YOU @aburkut

**Comment by SlyNet** [comment]
Is there an example on usage of this plugin with webpack?

**Comment by alshuwaikhat** [comment]
@kebian If I could like your post 1000+ time, I would've done so!  
Thank you
