### ISSUE TITLE
Setting the date to null does not reset values in the time picker window

### ISSUE THREAD

**Issue by Gloompirate** [Eonasdan/bootstrap-datetimepicker#1323]
If you select a time, and then set the date for the datetimepicker to null (either via function, or by clicking the clear button), when you re-open the time picker window, the previously selected time will still be there, and hasn't reset to any default value. This can lead to a time that can't be selected being shown when being used with linked pickers.

fiddle: http://jsfiddle.net/fpf3n0ko/2/

**Comment by geraldbiggs** [comment]
+1

This is a big usability problem when using ajax forms, impossible to clear the calendar or reset it after a successful entry. Have attempted many variations of the documented function to no success.
