### ISSUE TITLE
Format is not respecting browser language

### ISSUE THREAD

**Issue by Joev-** [Eonasdan/bootstrap-datetimepicker#1325]
Hi,

I have an ASP MVC application in which I am returning a date that is auto-formatted based on the Accept-Language in the request headers. This is handled by setting the culture to auto in my web.config.

The date value is delivered to the HTML fine, and my input field shows the value in the correct format. The value displayed in the field however is incorrect, and any subsequent selections from the picker are equally incorrect.

My environment is as follows:
* OS Language: English (United Kingdom) with matching date, time and number formats. US Keyboard input.
* Browser Language: English (United Kingdom)
* Accept-Headers are `Accept-Language:en-GB,en;q=0.8,en-US;q=0.6`

The value returned by the server is `17/09/2015 14:25:06`
The value displayed in the field is `09/17/2015 2:25 PM`

What is setting this format, and how can I change it? This issue has plagued me for months.

**Comment by Eonasdan** [comment]
See this: http://eonasdan.github.io/bootstrap-datetimepicker/FAQ/#how-do-i-change-the-languagelocale and this: http://eonasdan.github.io/bootstrap-datetimepicker/#using-locales

**Comment by Joev-** [comment]
Okay, using `moment-with-locales` and hard-coding the locale does work. I am surprised to see that it would not auto detect the locale to use from the browser's language list, however after some research I see that is a shortcoming of JavaScript itself.
