### ISSUE TITLE
UTC/timezone does not take into account the moment that was set

### ISSUE THREAD

**Issue by jeremyVignelles** [Eonasdan/bootstrap-datetimepicker#1326]
Hi,
Sorry for posting into multiple bugs. Here's the place I will try to explain my issue the best way I can.

fiddle : http://jsfiddle.net/ch85khv7/

local time zone : UTC+2 (CEST)
local time : 21:36
UTC time (correctly displayed at the bottom) : 19:36
displayed time in the picker : 17:36 (expected 19:36).

Opening the picker successively displays 15:36, 13:36 ...

**Comment by jeremyVignelles** [comment]
Updated jsfiddle with corrected library : http://jsfiddle.net/ch85khv7/1/

**Comment by jeremyVignelles** [comment]
Since commit jeremyVignelles/bootstrap-datetimepicker@26d5fd8110d2dc1cca8195fdb834704a202096ff , explicit time zone doesn't need to be explicitely set.
see http://jsfiddle.net/ch85khv7/3/

**Comment by tmotyl** [comment]
@jeremyVignelles thanks for the pull request, just stumbled over the same issue, and got to the same conclusion. I hope your pull request will be merged soon.
