### ISSUE TITLE
scss has no decade styles

### ISSUE THREAD

**Issue by CharlotteAmyWilson** [Eonasdan/bootstrap-datetimepicker#1328]
When viewing the decades in the date picker when using the sass version it does not display correctly.

The css version has the following:
.bootstrap-datetimepicker-widget .datepicker-decades .decade {
  line-height: 1.8em !important;
}
This fixes the styling issues. 

When hovering over the decades - only part of the decade is highlighted and appears clickable.
![bootstrap datetime picker decade issue hover](https://cloud.githubusercontent.com/assets/1980616/9956572/bca9a9c8-5df1-11e5-9b63-12f21db2f14b.PNG)
![bootstrap datetime picker decade issue](https://cloud.githubusercontent.com/assets/1980616/9956573/bcac51dc-5df1-11e5-8794-f5bf29eb21fa.PNG)

Thanks
Charlotte

**Comment by chrisdemetriad** [comment]
Thanks @CharlotteAmyWilson. This displays is better for me as the dash gets in the middle.

        line-height: .8em !important;
        width: 40px;
        padding-top: 10px;

**Comment by ferares** [comment]
I have the same issue, however I've noticed there are some classless spans inside the decade selector:

![datepicker-bug](https://user-images.githubusercontent.com/12473537/32689152-d1584578-c6bd-11e7-8cbd-0b205293a864.jpg)

```
<td colspan="7">
  <span data-action="selectDecade" class="decade" data-selection="1905">1900 - 1911</span>
  <span data-action="selectDecade" class="decade" data-selection="1917">1912 - 1923</span>
  <span data-action="selectDecade" class="decade" data-selection="1929">1924 - 1935</span>
  <span data-action="selectDecade" class="decade" data-selection="1941">1936 - 1947</span>
  <span data-action="selectDecade" class="decade" data-selection="1953">1948 - 1959</span>
  <span data-action="selectDecade" class="decade" data-selection="1965">1960 - 1971</span>
  <span data-action="selectDecade" class="decade" data-selection="1977">1972 - 1983</span>
  <span data-action="selectDecade" class="decade" data-selection="1989">1984 - 1995</span>
  <span data-action="selectDecade" class="decade active" data-selection="2001">1996 - 2007</span>
  <span></span>
  <span></span>
  <span></span>
</td>
```
and this is my scss fix:

```
.bootstrap-datetimepicker-widget {
  table {
    td {
      span {
        width: 108px;

        &:not(.decade) {
          display: none;
        }
      }
    }
  }
}
```

![datepicker-fix](https://user-images.githubusercontent.com/12473537/32689164-fefedf64-c6bd-11e7-8a46-10de77f20790.jpg)

**Comment by ferares** [comment]
I have the same issue, however I've noticed there are some classless spans inside the decade selector:

![datepicker-bug](https://user-images.githubusercontent.com/12473537/32689152-d1584578-c6bd-11e7-8cbd-0b205293a864.jpg)

```
<td colspan="7">
  <span data-action="selectDecade" class="decade" data-selection="1905">1900 - 1911</span>
  <span data-action="selectDecade" class="decade" data-selection="1917">1912 - 1923</span>
  <span data-action="selectDecade" class="decade" data-selection="1929">1924 - 1935</span>
  <span data-action="selectDecade" class="decade" data-selection="1941">1936 - 1947</span>
  <span data-action="selectDecade" class="decade" data-selection="1953">1948 - 1959</span>
  <span data-action="selectDecade" class="decade" data-selection="1965">1960 - 1971</span>
  <span data-action="selectDecade" class="decade" data-selection="1977">1972 - 1983</span>
  <span data-action="selectDecade" class="decade" data-selection="1989">1984 - 1995</span>
  <span data-action="selectDecade" class="decade active" data-selection="2001">1996 - 2007</span>
  <span></span>
  <span></span>
  <span></span>
</td>
```
and this is my scss fix:

```
.bootstrap-datetimepicker-widget {
  table {
    td {
      span {
        &.decade {
          width: 108px;
        }

        &:not([class]) {
          display: none;
        }
      }
    }
  }
}
```

![datepicker-fix](https://user-images.githubusercontent.com/12473537/32689164-fefedf64-c6bd-11e7-8a46-10de77f20790.jpg)
