### ISSUE TITLE
minDate further than this month makes navigating further impossible

### ISSUE THREAD

**Issue by bertoost** [Eonasdan/bootstrap-datetimepicker#1334]
For example; today it's September 21. My minDate is set to December 15th, I cannot navigate (on day level) to december. I can click on the month to go to December but using the arrow buttons should be possible too.

Didn't test this with maxDate option. Probably the same?

**Comment by bertoost** [comment]
My solution for now is to use viewDate().

```
var minDate = new Date();
$("...").data('DateTimePicker').viewDate(minDate);
```

This should be default behavior in my opinion

**Comment by Eonasdan** [comment]
please provide a jsfiddle of your issue

**Comment by bertoost** [comment]
Don't know (never used) jsfiddle. Please try setting minDate option to something far in the future. And then try to use the arrow navigation next to the top month to go to the first possible date, it will not work.

**Comment by bertoost** [comment]
This is also happening with the "max date". When set to something earlier than today, the datepicker is not able to navigate back. Using **$("...").data('DateTimePicker').viewDate(...);** to force the datepicker to start at selected month.

In my case; both min and max date could be set. And min date is leading.

**Comment by William-H-M** [comment]
Hi, I’ll be closing issues that have been answered by the community.

You can always left `useCurrent: true` and that way the picker will load default date and won't be any problem.
