### ISSUE TITLE
input value data-binding issue in angular

### ISSUE THREAD

**Issue by woohling** [Eonasdan/bootstrap-datetimepicker#1341]
I'm using this plugin in angular and met a really tricky problem and failed to find a solution.
I'm binding the input value using angular. When setting  $(selector).data("DateTimePicker").date(null), I need to set the input value to string 'no-date-selected'. However the input element is displayed empty in browser, and when I inspect the input element, it's shown that <input value="no-date-selected">.
Hopefully you may help out. Many thanks in advance.
And BTW, really love your work , : )

**Comment by jcamilorm902** [comment]
I have the problem, I am binding the input value with angular ng-model, but the model in Controller is not set when selecting date. When I write in the input field, model is updated, like other models do it in angular.

**Comment by UzairNouman** [comment]
After messing with my mind for like 4,5 hours,I decided to create an issue but suprised to see its already there.I am using Angular 2.0 BETA and facing the same issue that input tag of datetime picker when binded to the view its giving nothing.I also noticed, when you manually type something in that that input field,it is working(data is binded).

**Comment by jnm2** [comment]
I'd recommend using this particular AngularJS module: https://github.com/atais/angular-eonasdan-datetimepicker
