### ISSUE TITLE
How to get it in a form to be able to convert to SECONDS?

### ISSUE THREAD

**Issue by ollie007** [Eonasdan/bootstrap-datetimepicker#1342]
How to get it in a form to be able to convert to SECONDS?

I need to be able to convert the input to seconds for PHP.....

So how do i set it to 24hrs at least?

**Comment by ollie007** [comment]
hey, i am using DD-MM-YYYY with strtotime to get the unix timestamp for db storage

but when i pull it out of the db the value is different, why? timezone?

i am using php date('d-m-Y')

**Comment by dahuzix** [comment]
how can i sort the table by  client?

**Comment by Eonasdan** [comment]
These are questions for stackoverflow
