### ISSUE TITLE
Incorrect time format resolve in some locales

### ISSUE THREAD

**Issue by NerijusV** [Eonasdan/bootstrap-datetimepicker#1345]
In some locales where 24 hours format should be used DateTimePicker still uses 12 hour format. For example, in Lithuanian locale long date format `LLL` is `YYYY [m.] MMMM D [d.], HH:mm [val.]`. In this case the format itself contains symbol 'a' and code decides to use 12 hour format. I believe problem is with this line:

```
 use24Hours = (actualFormat.toLowerCase().indexOf('a') < 1 && actualFormat.replace(/\[.*?\]/g, '').indexOf('h') < 1);
```

https://jsfiddle.net/myq50a5g/4/

version : 4.17.37

**Comment by dfabreguette-ap** [comment]
+1 I just got the case in french mode.

My problem is I want to use following format to get this format "20h30" (for 8:30pm). 
I set format option to "HH\\hmm" but the

```
indexOf('h')
```

breaks the use24hours detection.

A cool thing would be to be allowed to override this detection with a "use24hours" option right ?
