### ISSUE TITLE
Lack of color CSS property for calendar numbers

### ISSUE THREAD

**Issue by alvarotrigo** [Eonasdan/bootstrap-datetimepicker#1347]
It seems to me that the plugin is missing a default `color` property for the numbers in the calendar.

Right now it looks quite weird when wrapping the calendar in any element (div, table, row...) and setting a color to its parent.
![calendar](https://cloud.githubusercontent.com/assets/1706326/10170055/643e7772-66cb-11e5-9044-c69195cd9d28.PNG)

[Reproduction online](http://jsfiddle.net/a4u71thz/11/)

I would like to use the default colors but I want to style my table row with another color and this behavior makes it difficult because I would be the one having to set the color inside the external datetimepicker plugin.

**Comment by Maelstorm1973** [comment]
I'm having a similar issue myself, but with the colors of white on black some of the numbers, and even the controls are invisible until you mouse over them.
