### ISSUE TITLE
datetimepicker events not firing

### ISSUE THREAD

**Issue by Fattouh92** [Eonasdan/bootstrap-datetimepicker#1352]
I cant get the events to work, I am using on meteor 1.2 and everything is working properly
the code:
    $('.datetimepickerStart').datetimepicker({
      showClear: true,
      format: "DD MMM YYYY"
    });
    $('.datetimepickerEnd').datetimepicker({
      showClear: true,
      format: "DD MMM YYYY"
    });
    $("#datetimepickerStart").on("dp.change", function (e) {
      console.log(e,"CHANGEEEEEEEE");
    });

**Comment by mmalyska** [comment]
You are attaching event to input not to datetimepicker.
You can do something like this:
```javascript
$('.datetimepickerEnd').datetimepicker({
  showClear: true,
  format: "DD MMM YYYY"
}).on("dp.change", function (e) {
  console.log(e,"CHANGEEEEEEEE")
});
```
or something like that:
```javascript
$('.datetimepickerEnd').datetimepicker({
  showClear: true,
  format: "DD MMM YYYY"
});
$("#datetimepickerStart").data("DateTimePicker").on("dp.change", function (e) {
  console.log(e,"CHANGEEEEEEEE");
});
```
