### ISSUE TITLE
Problem with stepping

### ISSUE THREAD

**Issue by otherprod** [Eonasdan/bootstrap-datetimepicker#1354]
Hi,
i found that the stepping option does not work as it should, or it could work better :). 

I want to use it with two dayparts , the first with full hours and the second with full hours but starting from half hours, i explain.

Some reservation can start at 10:00, 11:00 12:00 and so on for a period of 60 min each, so i m using the options stepping with a value of 60 minutes wich from what I understood it give the possibility to go from 10:00 to 11:00 etc ... so here its working perfect.

The problem i have is for the period wich must start from 10:30 to 11:30, 11:30 to 12:30 etc, on those dayparts i tried with the stepping option of 60 minutes with a start date of [date] 00:30 or [date] 09:30 and it does not work.

The script start to 10:00 every time i put a stepping of 60 minutes it  doesnt want to work with a stepping of 60 min starting from hal hours .

Did i missed something ?

**Comment by otherprod** [comment]
Hi, Any idea of getting this option work as it should ?

**Comment by RobertSandor** [comment]
I have the same issue with smaller values: step 15 mins starting at 10 mins will not work; start time must be multiple of step, in my case: 0, 15, 30, 45 will work.
