### ISSUE TITLE
Wrong format is used in getMoment when parsing dateWithTimeZoneInfo (when timezone is set)

### ISSUE THREAD

**Issue by tmotyl** [Eonasdan/bootstrap-datetimepicker#1355]
I'm using v.4.17.42, but the same applies to 4.17.37

datetimepicker is using configured format for parsing string "dateWithTimeZoneInfo".
This results in wrong date parsing.
E.g. if you have configured datetimepicker to use DD-MM-YYYY format.

The problem is in the line 
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L159
it should rather reuse format which was used to create "dateWithTimeZoneInfo" variable.
changing line 159 to:

```
returnMoment = moment(dateWithTimeZoneInfo, 'YYYY-MM-DD[T]HH:mm:ss', options.useStrict).tz(options.timeZone);
```

solves the issue.

**Comment by mblandfo** [comment]
I think the proposed solution have a 'Z' on the end of 'YYYY-MM-DD[T]HH:mm:ss'

'YYYY-MM-DD[T]HH:mm:ssZ'

I am using the datetimepicker with a custom format of 'ddd, MMM D, YYYY h:mm A', and trying to parse that here results in "Invalid Date", which means you cannot update the picker by typing in a date. If you type in a date, it parses an invalid date here, and reverts to the last set date.

**Comment by johvet** [comment]
We just hit this problem today. The parsing of `dateWithTimeZoneInfo` and custom format is definitely wrong. Are there any plans on fixing this?

**Comment by rkhmelichek** [comment]
+1 for proposed fix
