### ISSUE TITLE
How to set time from 8:30 to 24

### ISSUE THREAD

**Issue by pcleal** [Eonasdan/bootstrap-datetimepicker#1361]
I would like to set time to select between 8:30 and 24.
Anyone can help with this? 

in datetimepicker.min.js, i've change only the next line
for(var z=8;z<24;z++){if(k.indexOf(z)!==-1){continue}var v=g(s,G,m,z);

This only show hours between 8:00 and 24. 
But i want from 8:30 ..

I've this code:

JS
$('.form_time').datetimepicker({
        language:  'pt',
    autoclose: 1,
    startView: 1,
    maxView: 1,
    minuteStep: 30,
    });

**Comment by ursuleacv** [comment]
You can use moment for this

```
$('.form_time').datetimepicker({
        format: 'HH:mm', //'LT',
        stepping: 30,
        minDate: moment().hours(08).minutes(30),
        maxDate: moment().hours(0).minutes(0),
});
```
