### ISSUE TITLE
Setting maxDate makes it the defaultDate

### ISSUE THREAD

**Issue by sandyandi** [Eonasdan/bootstrap-datetimepicker#1364]
Setting the `maxDate` option makes the textbox display the specified date which I believe should be the behavior of `defaultDate`?
    $('#datepicker').datetimepicker({
        format: 'MMMM D, YYYY',
        maxDate: moment().subtract(18, 'y')
    });
But if I remove the `maxDate` option, it behaves as normal - no date in the textbox.

**Comment by meetajhu** [comment]
I'm having the same issue.

**Comment by meetajhu** [comment]
ok solved. Set **useCurrent:false**

$('#datepicker').datetimepicker({
format: 'MMMM D, YYYY',
maxDate: moment().subtract(18, 'y'),
useCurrent: false
});
