### ISSUE TITLE
Datepicker doesn't show after click

### ISSUE THREAD

**Issue by brunoDegaspare** [Eonasdan/bootstrap-datetimepicker#1365]
Why the plugin is not working here? I am using the exact same configuration as the examples on the websites.

http://jsfiddle.net/brunodd/a28Lxkbg/1/

**Comment by RomeroMsk** [comment]
Just click on addon (calendar icon), it works.
And you forgot to include datetimepicker css, by the way.

**Comment by brunoDegaspare** [comment]
Thank you, all working now :)
