### ISSUE TITLE
Getting 'Uncaught TypeError: Cannot read property 'top' of undefined'

### ISSUE THREAD

**Issue by brunoDegaspare** [Eonasdan/bootstrap-datetimepicker#1366]
The plugin is working however I am getting 'Uncaught TypeError: Cannot read property 'top' of undefined'
I am using the latest version.

```
<div class="form-group">
    <div class="input-group date js-datetimepicker">
    <input type="text" class="form-control">
    </div>
</div>
```

```
$('.js-datetimepicker').datetimepicker({
     allowInputToggle: true,
     format:"MM/YYYY"
});
```

After inspecting the error it seems to be an issue with this line

```
if (offset.top + widget.height() * 1.5 >= $(window).height() + $(window).scrollTop() &&
```

**Comment by mikepostma** [comment]
I've been running into the same issue. A quick fix seems to be to replace:

```javascript
var position = (component || element).position(),
                    offset = (component || element).offset(),
```

with:
```javascript
var position = element.position(),
                    offset = element.offset(),
```

on line 378 - 379. Not sure if it has any adverse effects, I haven't noticed any yet.

**Comment by marccollin** [comment]
get same isue with this basic code:

```
<div class="input-group" id="fromDateFundPicker">
    <input type="text" class="form-control" id="fromDateFund" placeholder="Date de début">
 </div>
```

**Comment by William-H-M** [comment]
Hi, If anyone still gets this

on the OP he has this:
```
<div class="form-group">
    <div class="input-group date js-datetimepicker">
    <input type="text" class="form-control">
    </div>
</div>
```
If changed to this no error appear, this should be the guidelines of http://eonasdan.github.io/bootstrap-datetimepicker/#no-icon-input-field-only
```
<div class="form-group">
  <div class="input-group date ">
    <input type="text" class="form-control js-datetimepicker">
  </div>
</div>
```

**Comment by adamcbuckley** [comment]
This is how I got it to work.  The `input` element has to be wrapped with a `div` with `position: relative`

	<div style="position: relative">
		<input class="form-control" type="text" data-datetimepicker>
	</div>
