### ISSUE TITLE
Readonly behavior

### ISSUE THREAD

**Issue by BenjaminHorn** [Eonasdan/bootstrap-datetimepicker#1367]
Why do we have to set "readonly" to times?

first in the markup
```HTML
<input type="text" class="form-control datepicker" id="datetimepicker2" readonly />
```
and then in javascript
```javascript
$('#datetimepicker2').datetimepicker({
    ignoreReadonly : true
});
```

Should not ignoreReadonly's default value be false?

I cant really think of a use case where someone makes a readonly input, init datetimepicker on it and does not want to have the picker to pop up on click. (That is the default behavior)

**Comment by Eonasdan** [comment]
out of the box, the picker will respect the `readonly` and `disabled` properties of an input. Setting `ignoreReadyOnly` allows the picker to continue to work if you want to force a user to use the picker and not manual entry.

**Comment by BenjaminHorn** [comment]
ok. but I still think it should be the default behavior.  I guess the whole purpose of this component is to disallow to the user to input invalid date or format. Basically no manual entry.

**Comment by Eonasdan** [comment]
not sure why you're complaining about this. **You** told the textbox to be readonly, so the picker respects that and doesn't open.

If you want the textbox to be readonly and force your users to use the picker, add `ignoreReadyOnly: true` to the setup.

If you don't want it the textbox to be readonly so a user can use either... don't set the property.

**Comment by BenjaminHorn** [comment]
Maybe readonly is not the correct term, but I do not know how to achieve it else. **The key point is no manually enter by default.**
