### ISSUE TITLE
Open time picker when date is selected

### ISSUE THREAD

**Issue by kursusHC** [Eonasdan/bootstrap-datetimepicker#1368]
Hello,

I can't find an easy way to do this. I would need the time picker to be automatically shown when a date is clicked. Is that possible ? 

edit: Managed to get this effect with 

```
$("#datetimepicker1").on("dp.show", function (e) {
  $(".day").on('click', function(){
    $("a[data-action='togglePicker']").trigger('click');
  });
});

$("#datetimepicker1").on("dp.change", function (e) {
  $(".day").on('click', function(){
    $("a[data-action='togglePicker']").trigger('click');
  });
});
```

but is there a better way ? 
Thank you

**Comment by sumanthkumarc** [comment]
This js code worked for me too. Thanks :+1:

**Comment by wtfkeklol** [comment]
If anyone still interested in this, I managed to do it by changing the plugin's code. It works well and you don't need anything extra when applying the picker.

Here's what I did:

I added this piece of code to the end of the "selectDay" function:
`if (hasTime()) actions.togglePicker();`

Then I had to modify the "togglePicker" function like so:
```
togglePicker: function (e) {
                    var target = !e ? widget.find('[data-action="togglePicker"]').find('span') : e.target;
                    var $this = $(target),
```

If anyone finds any mistakes in this, let me know.

Cheers

**Comment by michaeldevenney** [comment]
The suggestion above by @wtfkeklol worked well for me.  In our case we wanted to strongly suggest the user enter the time component of the date they were entering becuase when they didn't it defaulted to midnight and that threw off our reports.  This was a nice way to _suggest_ they enter the time without having to pop a dialog up to confirm that they didn't want to enter a time.
