### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by wolganens** [Eonasdan/bootstrap-datetimepicker#1370]
Hello, the datetimepicker popover is looking like that:
![datepicker error](https://cloud.githubusercontent.com/assets/7290281/10457587/7ae4ac58-719d-11e5-91cb-63d3d98872c2.png)
And when we select a date, the day is always one number less then we have selected, sorry about the english, hope u guys understand. Nice plugin, thank you.

**Comment by fsolans** [comment]
I have the same problem. I have made a JSF page and write directly the value without this component and date and hours are correct. But when I use this component, I view 1 day less and also one hour less.
