### ISSUE TITLE
All decades are dissabled when minDate, maxDate are set.

### ISSUE THREAD

**Issue by emil-alexandrescu** [Eonasdan/bootstrap-datetimepicker#1372]
Here is a demo.
http://jsfiddle.net/516zsh7b/8/

I am stuck at decades mode when minDate and maxDate are set.

**Comment by bjarnef** [comment]
Furthermore if you set minDate = new Date(2015,10,2) and maxDate new Date(2021,31,12) ... then I can't choose the "decade" 2012-2023 .. but I can choose 2024-2035 (but all dates in this decades are then disabled.

If I then just change minDate = new Date(2022,1,1) then all decades are disabled.

**Comment by nbhuy89** [comment]
+1

**Comment by zhangjiayin** [comment]
+1

**Comment by votiv** [comment]
+1

**Comment by Zero3** [comment]
Maybe duplicate of https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1170

**Comment by lesilent** [comment]
Give this css a try:

```
.bootstrap-datetimepicker-widget .datepicker-years thead .picker-switch {
     cursor: default;
     pointer-events: none;
}

```

**Comment by bdemolder** [comment]
Having the same issue here... quite a blocker since we cannot override the 'save which viewmode' it is on, otherwise we could just on open open the days viewmode, then you would avoid the user being stuck?

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.
