### ISSUE TITLE
Max date Current Date Problem

### ISSUE THREAD

**Issue by sushant357** [Eonasdan/bootstrap-datetimepicker#1374]
Hi,
if my minDate is 3 days ago from current date & Max date is current date then its not allowing to select me current date

Please reply asap... 
We are stuck into that

**Comment by jlsalvador** [comment]
My bet, #1302

**Comment by Eonasdan** [comment]
you can set the min/max date to **now** and expect to be able to pick **now**

**Comment by sushant357** [comment]
Actually its not working for me but i done it in different way but there is one issues I am facing in IE.
It's working in Firefox & Chrome but In IE it disabling todays date instead of tomorrow.
var crtDate = $('#crtDate').val();
	if(crtDate != ""){
		crtDate = crtDate.replace(/-/g,'/');
		var date  = new Date(crtDate);
	}else{
		var date  = new Date();
	}
	var dd = date.getDate(); 
	var mm = date.getMonth()+1;
	var yyyy = date.getFullYear();
	var compareDate = new Date(yyyy,mm,dd);
	compareDate.setHours(0,0,0,0);
	var minDate1 = mm + "/" + dd + "/" + yyyy; 
	
	var date1  = new Date();
	var dd = date1.getDate(); 
	var mm = date1.getMonth()+1;
	var yyyy = date1.getFullYear();
	var compareDate1 = new Date(yyyy,mm,dd);
	compareDate1.setHours(0,0,0,0);
	var todayDate = mm + "/" + dd + "/" + yyyy; 
	
	var myDate = new Date();
	var date = myDate.getDate()+1; 
	var month = myDate.getMonth()+1;
	var year = myDate.getFullYear();
	var tommorow = month + "/" + date  + "/" + year;
	
	if(crtDate != ""){
		if(compareDate.valueOf() === compareDate1.valueOf()){
			$('#actDate').datetimepicker({
		   		format : "DD-MMM-YYYY",
		   		minDate: todayDate,
		   		maxDate: tommorow,
		   		disabledDates: [tommorow]
		    });	
		}else{
			$('#actDate').datetimepicker({
		   		format : "DD-MMM-YYYY",
		   		minDate: minDate1,
		   		maxDate: tommorow,
		   		disabledDates: [tommorow]
		    });
		}
	}else{
		$('#actDate').datetimepicker({
	   		format : "DD-MMM-YYYY",
	   		/*minDate: moment(),*/
	   		minDate: todayDate,
	   		maxDate: tommorow,
	   		disabledDates: [tommorow]
	    });	
	}

**Comment by sushant357** [comment]
Actually the problem is i can't select date which is clickable

**Comment by sookoll** [comment]
Also run into this issue, since my maxDate was moment(), which give you at the most moment. If I specify my range as follows:
```
minDate: moment().startOf('d');
maxDate: moment().endOf('d');
```
everything works just fine.
