### ISSUE TITLE
How to change locale dynamically or on runtime

### ISSUE THREAD

**Issue by sandeepthomas** [Eonasdan/bootstrap-datetimepicker#1376]
Thanks

**Comment by Leeh91** [comment]
?

**Comment by Eonasdan** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/FAQ/#how-do-i-change-the-languagelocale

http://eonasdan.github.io/bootstrap-datetimepicker/#using-locales

http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#locale

**Comment by Leeh91** [comment]
Thank you for your answer @Eonasdan,
but I still can't change my datetimepicker language dynamically.
If I set any language script in my index.html, I can't change to any other one in runtime.

**Comment by Leeh91** [comment]
@Eonasdan, now is working.

The problem was my lack of attention.

Thank you very much for your  patience and attention.

**Comment by priyankmaniar** [comment]
This might help someone.

If you need to change it to say french then use following code.

$('#your-id-of-datepicker').data("DateTimePicker").locale('fr');

Above will change on the fly, it's beautiful to see it in action.
