### ISSUE TITLE
Linked pickers with only time do not work

### ISSUE THREAD

**Issue by nicolasroux** [Eonasdan/bootstrap-datetimepicker#1383]
Hi,

I have 2 datetime pickers to select time range. 

When I link them with min and max, it does not work.

See demo here: http://plnkr.co/edit/h10J55DICwjAeLaCas2c

thanks for your help.

**Comment by jakeholland** [comment]
I was able to get them to work by doing this: https://jsfiddle.net/jtholla2/pvrjn80p/7/
