### ISSUE TITLE
4.17.37 date picker position issue.

### ISSUE THREAD

**Issue by gaojianzhuang** [Eonasdan/bootstrap-datetimepicker#1384]
My date picker position is not correct. From the demo page, the plugin show under left or above left of the input field. However, in my page, the plugin show under the icon or above the icon. 
My js code as same as the demo.
Css:
<link href="/QHW.ZPH.Mvc/Content/bootstrap/3.3.5/bootstrap.min.css" rel="stylesheet"/>
<link href="/QHW.ZPH.Mvc/Content/font-awesome/4.4.0/font-awesome.min.css" rel="stylesheet"/>
<link href="/QHW.ZPH.Mvc/Content/datatables/1.10.9/media/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
<link href="/QHW.ZPH.Mvc/Content/bootstrapdatetimepicker/4.17.37/bootstrap-datetimepicker.min.css" rel="stylesheet"/>
Scripts:

<script src="/QHW.ZPH.Mvc/Scripts/sea-modules/bootstrap/momentjs/2.10.6/moment.js"></script>

<script src="/QHW.ZPH.Mvc/Scripts/sea-modules/bootstrap/momentjs/2.10.6/moment-with-locales.js"></script>

<script src="/QHW.ZPH.Mvc/Scripts/sea-modules/bootstrap/datetimepicker/4.17.37/bootstrap-datetimepicker.min.js"></script>

![1](https://cloud.githubusercontent.com/assets/1866009/10748773/689eeb60-7c9e-11e5-95e8-49fd4ec7b21e.png)

**Comment by CR4567** [comment]
same here... I can't get the position to the left, even when setting the widgetPosition to left.
