### ISSUE TITLE
Missing assets are breaking compilation with django-pipeline

### ISSUE THREAD

**Issue by karolyi** [Eonasdan/bootstrap-datetimepicker#1388]
Hi,

since you're missing `fonts/` under your build directory and [`bootstrap-datetimepicker-standalone.css`](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/build/css/bootstrap-datetimepicker-standalone.css#L8) is referencing it, `django-pipeline` breaks on asset compilation because of this issue:

https://github.com/cyberdelia/django-pipeline/issues/302

Please fix that file, or the put the asset there.

**Comment by Eonasdan** [comment]
that doesn't make it very "standalone" does it?

**Comment by karolyi** [comment]
and you expect everybody to put their font folders in place when using the css? I think that's a bad practice.

**Comment by Eonasdan** [comment]
guess you'll have to do some work and fix it

**Comment by natecox** [comment]
This is currently affecting me. I have a pull request open to fix the issue here: https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1733

**Comment by karolyi** [comment]
@natecox see https://github.com/jazzband/django-pipeline/issues/484#issuecomment-170656271
