### ISSUE TITLE
Wrong week numbers for 2016

### ISSUE THREAD

**Issue by andersHj** [Eonasdan/bootstrap-datetimepicker#1408]
![image](https://cloud.githubusercontent.com/assets/2843210/12115054/36929336-b3af-11e5-846d-fd4021dea8cb.png)

Week 1 should start on January 3rd (4th).

http://jsfiddle.net/z0bpry3h/1/

**Comment by smisch** [comment]
Week numbers come from moment.js and moment.js uses ISO 8601 to define the week number. 

From Wikipedia:
"The first week of a year is the week that contains the first Thursday of the year [...]". 
https://en.wikipedia.org/wiki/ISO_week_date

Moment.js Docs
http://momentjs.com/docs/#/displaying/

**Comment by lvostinar** [comment]
The current implementation is fine, depends on locale, we also needed to enforce ISO 8601, so created a new option for it; here is the pull request
https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1886
