### ISSUE TITLE
Where's the CSS?

### ISSUE THREAD

**Issue by sfdi** [Eonasdan/bootstrap-datetimepicker#1409]
I'm trying to install bootstrap-datetimepicker manually.The installation instructions here: https://eonasdan.github.io/bootstrap-datetimepicker/Installing/ list Bootstrap Datepicker CSS as item 6 of the prerequisites. However, there don't seem to be any such CSS files in the repo. Do you expect users to compile a CSS file from either src/sass/_bootstrap-datetimepicker.scss or src/less/_bootstrap-datetimepicker.less? If so, I'd ask that the installation docs be updated to reflect this. If not, please add the CSS file to repo.

**Comment by Eonasdan** [comment]
You're kidding right? https://github.com/Eonasdan/bootstrap-datetimepicker/tree/master/build/css

**Comment by sfdi** [comment]
Oh damn, I was using github's filename search (hit t) for .css. It didn't catch it.
