### ISSUE TITLE
Keyup event blocks propagation of ctrl key

### ISSUE THREAD

**Issue by hogan** [Eonasdan/bootstrap-datetimepicker#1413]
I have a page that handles ctrl + mouse wheel in JS. When i press and release ctrl key in datepicker input, my app thinks that ctrl key is still down.
This issue may also apply to other keys for other people.
I fixed it for me by changing keyup function to this:

```
        keyup = function (e) {
            keyState[e.which] = 'r';
            if (e.which === 17) {
                return;
            }
            e.stopPropagation();
            e.preventDefault();
        },
```

**Comment by Hugoer** [comment]
me too that happens to me, but not only with the 'Control' key, the 'Escape' key is also true. I understand it is not clear that the stack of keystrokes.
