### ISSUE TITLE
No way to dismiss dialog on mobile device

### ISSUE THREAD

**Issue by mikeerickson** [Eonasdan/bootstrap-datetimepicker#142]
Controls work fine on mobile, but no way to dismiss control (except when control is displayed to hide time option)

**Comment by e2** [comment]
:+1:

**Comment by Eonasdan** [comment]
the dev branch has some new features that will help with this. `showClose: true` will show an icon that will call the `hide()` function. `ignoreReadonly: true` will allow you to set an input to be `readonly` or `disabled` but still let the icon work.

**Comment by tweinreich** [comment]
As the showclose option didn't work for me (_bootstrap-datepicker v1.6.4 in symfony 2.7 form component_) I tried the following with success on iOS:

`$("body").on("tap touchstart touchend",function(){
                    $('.dropdown-menu').hide();
                });`

Maybe not the most elegant solution but it works for me and I tried a lot different approaches that didn't solve this issue.

**Comment by ashanvabs** [comment]
I'm getting below error in iphone 5s. And In the android and windows browsers 
`$(this).collapse is not a function. (In '$(this).collapse('hide')', '$(this).collapse' is undefined)` I hope this also related this issue.
