### ISSUE TITLE
Datetime picker not fully showing inside a .table-responsive class

### ISSUE THREAD

**Issue by daza110** [Eonasdan/bootstrap-datetimepicker#1420]
Please see https://jsfiddle.net/daza110/6abxn644/ this fiddle for an example. If I put overflow as visible on the .table-responsive class it works. But then when you shrink the view to mobile view, the table does not then become responsive.

**Comment by Eonasdan** [comment]
you have console errors http://jsfiddle.net/Eonasdan/4rfy3Lvc/

**Comment by daza110** [comment]
I see no errors in my console log (Firefox), as far as I can tell your fiddle is exactly the same as mine and still does not work? Still does not show the date picker unless in the css you add .table-responsive { overflow:visible !important } in the css?

**Comment by jacopozzo** [comment]
@daza110  doesn't have any console error.
He simply included bootstrap.min.css in the fiddle to replicate the environment and give to you an example.
In your fiddle there is not any bootstrap.min.css included, so the css class table-responsive doesn't exists.
Check it with firebug ;)

If you'll include the bootstrap stylesheet your fiddle won't works anymore....

**Comment by kashifullahwebdeveloper** [comment]
I have solved the issue by adding position:relative; rule to **.bootstrap-datetimepicker-widget** class in bootstrap-datetimepicker.min.js.
