### ISSUE TITLE
How can I set date?

### ISSUE THREAD

**Issue by konopiux** [Eonasdan/bootstrap-datetimepicker#1424]
How to set to control dynamically?

tried: `element.datetimepicker.setDate(new Date(2016-05-12));`, but no luck

**Comment by konopiux** [comment]
var picker = element.data("DateTimePicker");
                        picker.date(new Date(2016-05-12));

faund!!!

but maybe you can add it to documentation?

**Comment by mnelsonwhite** [comment]
See the alert styled container at the very top of the [function documentation](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/).

> Note All functions are accessed via the data attribute e.g. $('#datetimepicker').data("DateTimePicker").FUNCTION()
