### ISSUE TITLE
Datetime picker not fully showing inside a .table-responsive class NOT CLOSED

### ISSUE THREAD

**Issue by daza110** [Eonasdan/bootstrap-datetimepicker#1427]
You closed my initial response #1420, but it is not closed, you did not reply to my comment and there is still an issue when nested within a .table-responsive class. Are you aware of this? Have you tried to fix this?

The comment on my closed thread is:

@Eonasdan I see no errors in my console log (Firefox), as far as I can tell your fiddle is exactly the same as mine and still does not work? Still does not show the date picker outside the table unless in the css you add .table-responsive { overflow:visible !important } in the css?

EDIT: I see I added the external CSS file incorrectly, but other than that, the picker does not show the date picker outside the table
https://jsfiddle.net/daza110/6abxn644/3/ ---- see that I have added the overflow CSS element, delete that, run it and then you will see the difference.

Also see my stack thread which no one has yet answered too.
http://stackoverflow.com/questions/34811084/bootstrap-datetimepicker-issue-instide-a-table-responsive-class

**Comment by nikunj24u** [comment]
Any update on this. I am still facing the same issue.

**Comment by daza110** [comment]
Still not fixed still no response

**Comment by coke-cent** [comment]
Hola que tal... tengo el mismo problema...! alguien poddria ayudar porfavor!!!

**Comment by William-H-M** [comment]
Quick workaround
```
$('#picker').datetimepicker().on('dp.show', function() {
$(this).closest('.table-responsive').removeClass('table-responsive').addClass('temp');
}).on('dp.hide', function() {
$(this).closest('.temp').addClass('table-responsive').removeClass('temp')
});
```
