### ISSUE TITLE
Missing glyphicon in default configuration 

### ISSUE THREAD

**Issue by dmmihaylov** [Eonasdan/bootstrap-datetimepicker#1430]
Hello,

Just noticed that an icon in the current default configuration is missing from recent glyphicons package (or is renamed):

```
time: 'glyphicon glyphicon-time'
```

should be:

```
time: 'glyphicon glyphicon-clock'
```

Thanks!

**Comment by William-H-M** [comment]
Hi, though this a quite older release, this is because this is using bootstrap V3 which in the components they have the icon of `glyphicon glyphicon-time`
