### ISSUE TITLE
Issue with Bootstrap Datetime Picker and Moment Timezone

### ISSUE THREAD

**Issue by juancarlosfarah** [Eonasdan/bootstrap-datetimepicker#1432]
When you use version 4.17.37 with Moment Timezone 0.5.0, you cannot edit the input field manually. 
Example:
https://jsfiddle.net/juancarlosfarah/kqgoegpw/6/

The issue is in [line 159](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L159) with the inclusion of `parseFormats`. Given that you format the string in line 158. If that format is not in `parseFormats` and does not pass as a valid moment.

**Comment by DigitalSmile** [comment]
+1 would be nice to be fixed

**Comment by juancarlosfarah** [comment]
I have checked out the development branch and that code has been changed. As a workaround for now, I simply remove `parseFormats` from the function call in [line 159](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L159).

**Comment by jeremyjannotta** [comment]
+1 for moment-timezone compatibility (0.5.3 still causes issues with datetime picker)

**Comment by cutterbl** [comment]
+1 for compatibility. See that this is in the 'develop' branch. Any timeframe on when this might be part of an official release?

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.

**Comment by fracz** [comment]
Yes, it does :-(

    npm WARN eonasdan-bootstrap-datetimepicker@4.17.47 requires a peer of moment-timezone@^0.4.0 but none is installed. You must install peer dependencies yourself.

**Comment by William-H-M** [comment]
No, it doesn't
> requires a peer of moment-timezone@^0.4.0 but none is installed. You must install peer dependencies yourself.

There's clearly telling what you must do.

Issue locked
>Issues that have been closed for longer than 30 days will be locked.
