### ISSUE TITLE
Wrong 'today' date when using locale: 'nl'

### ISSUE THREAD

**Issue by WLepelaar** [Eonasdan/bootstrap-datetimepicker#1436]
It seems that something goes wrong with moment.js. The date jumps randomly.
See: https://jsfiddle.net/WilfredLepelaar/tj8duvoo/2/

Does anyone know how I can fix this?

**Comment by CreasolDev** [comment]
Remove the locale property and insert it using the moment.js package.
This works for mij project ;)

**Comment by WLepelaar** [comment]
@CreasolDev Thanks for your message. If have updated the code but this does not fix the problem for me. The new problem is 'daysOfWeekDisabled'

See: https://jsfiddle.net/WilfredLepelaar/tj8duvoo/2/
Can u give me an example of your working code?

**Comment by RonJeremyR6** [comment]
I have got the same problem with locale NL, is there a fix or workaround?

**Comment by Sef1995** [comment]
Same issue here.. Still no fix for this?

**Comment by Sef1995** [comment]
I have managed to fix it by commenting this out in the head of my html code:

`<!--    <script src="bower_components/moment-timezone/builds/moment-timezone-with-data-2010-2020.js"></script>-->`
