### ISSUE TITLE
npm package says it's 4.15.35 when it's really 4.15.37

### ISSUE THREAD

**Issue by pwolfert** [Eonasdan/bootstrap-datetimepicker#1438]
I would like to verify that this is true.  https://www.npmjs.com/package/eonasdan-bootstrap-datetimepicker

This says it's `4.15.35`, so when I had that version as a dependency in my project and ran `npm install` in December, it got one version, and then when I installed my project somewhere else today, it got what it says is `4.15.35`, but it breaks my app.  And when I copy the old `eonasdan-bootstrap-datetimepicker` directory from the other machine's `node_modules`, it works.  So it has to be a different version.  And the page on npm says "version 4.15.37 | build passing" instead of 4.15.35.

Can someone verify this?

**Comment by khakulov** [comment]
@Eonasdan please update npm package

**Comment by btecu** [comment]
I'm also having issue with `npm`. Can we get the latest version published?

**Comment by ceefour** [comment]
Most likely duplicated by #1522

**Comment by btecu** [comment]
This issue has been solved.
