### ISSUE TITLE
Escape key handling conflicts with bootstrap modal

### ISSUE THREAD

**Issue by kikonen** [Eonasdan/bootstrap-datetimepicker#1441]
I'm trying to use this control in bootstrap modal, and it appears that ESC key doesn't work as expected when bootstrap-datetimepicker field is focused. I.e. ESC in bootstrap modal dialog is supposed to close dialog.

I tried to workaround it by defining own ESC handler, but since logic is stopping keyevent propogation always, this workaround doesn't work.

``` javascript
  keyBinds: {
    escape: function () {
      var $widget = $('.bootstrap-datetimepicker-widget.dropdown-menu');
      if ($widget.length) {
        console.debug($widget);
        this.hide();
      } else {
        console.debug("no widget open: Ignore ESC");
      }
    }
  }
```

workaround fails due to this.

``` javascript
            keydown = function (e) {
...
                if (handler) {
                    handler.call(picker, widget);
                    e.stopPropagation();
                    e.preventDefault();
                }
```

**Comment by jochenjonc** [comment]
Having the same issue, would love it could be fixed.
Beside the escape character, I'm having the same issue with the enter key, in my modals this submits the form.

**Comment by robintheilade** [comment]
I also experience the same issue

**Comment by robintheilade** [comment]
I solved it by overriding `escape` event handler.

```
        $('#fromDatePicker')
            .datetimepicker({
                format: 'YYYY-MM-DD HH:mm',
                keyBinds: {
                    escape: function (widget) {
                        if (widget === false) {
                            $modal.modal('hide');
                        }
                        else {
                            this.hide();
                            this.show();
                        }
                    }
                }
            })
```

`$modal` is my jQuery reference to the modal.

The invocation of `this.show()` is to refocus the input field after hiding the calender widget. The focus allows for a second escape key press to hide the modal.
