### ISSUE TITLE
Linking two datepickers, using startdate

### ISSUE THREAD

**Issue by drkshady** [Eonasdan/bootstrap-datetimepicker#1442]
Hi, i cant get the datepickers linked to each other.

Also the startDate is not influenced by "startDate: "-3d" "

```

 $(function () {
        $('#datetimepicker1').datetimepicker({
			format: 'dd.MM.yyyy',
			startDate: '-3d',
			locale:'de'});
			
        $('#datetimepicker2').datetimepicker({
            useCurrent: false,
			format: 'dd.MM.yyyy',
			startDate: '-3d',
			locale:'de'
        });

        $("#datetimepicker1").on("dp.change", function (e) {
            $('#datetimepicker2').data("datetimepicker").minDate(e.date);
        });
        $("#datetimepicker2").on("dp.change", function (e) {
            $('#datetimepicker2').data("datetimepicker").maxDate(e.date);
        });
    });


```

**Comment by Eonasdan** [comment]
Please read the docs: http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers

`-3d` isn't supposed to do anything.

**Comment by drkshady** [comment]
What should i read? Theres only code and i used and modified it.

Could you tell me where it seems wrong to you?

Also there is nothing about a start date in the docs... or atleast i cant find them.

**Comment by Eonasdan** [comment]
you're looking for `defaultDate` http://eonasdan.github.io/bootstrap-datetimepicker/Options/#defaultdate

this is not a bug or an enhancement, please ask your question on Stackoverflow

**Comment by drkshady** [comment]
Hi, i asked in stackoverflow: 
http://stackoverflow.com/questions/35209546/bind-link-2-bootstrap-datepicker-eonasdan

and you answered someone a while ago with this problem with this:
http://stackoverflow.com/questions/26653246/bootstrap-datepicker-events

but your solution there is not working for me either...

Please help me, im trying for too long :(
