### ISSUE TITLE
time resets out of bounds when choosing the max date

### ISSUE THREAD

**Issue by CreasolDev** [Eonasdan/bootstrap-datetimepicker#1446]
I'm using the min - max variant, for a planner in calendar and disabled hours 0-9 and 21 - 23

```
 $('#datetimepicker6').datetimepicker({
        disabledHours: [0, 1, 2, 3, 4, 5, 6, 7, 8, 21, 22, 23]
    });
    $('#datetimepicker7').datetimepicker({
        disabledHours: [0, 1, 2, 3, 4, 5, 6, 7, 8, 21, 22, 23],
        useCurrent: false //Important! See issue #1075
    });
    $("#datetimepicker6").on("dp.change", function (e) {
        $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
    });
    $("#datetimepicker7").on("dp.change", function (e) {
        $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
    });
```

When I do nothing with the min date (because, for instance, it's already on the correct date), open the max date and choose today, both hours change to 00:00 on today, but those hours are disabled, so the form kinda 'crashes'...

Does anyone know how to fix this?

**Comment by nsamuels0510** [comment]
Did anyone ever resolve this issue or is there a workaround?
