### ISSUE TITLE
Attaching picker to dynamically created element returns "relative positioned container" error

### ISSUE THREAD

**Issue by JamsusMaximus** [Eonasdan/bootstrap-datetimepicker#1448]
I have the following input, which I'm attaching datetimepicker to on pageload:

![image](https://cloud.githubusercontent.com/assets/1645256/12810610/3cb3e97c-cb1f-11e5-988e-129c73a33ef3.png)

This works as expected.

When the user clicks a button, I duplicate this input to allow for multiple dates.

Clone code: 

![image](https://cloud.githubusercontent.com/assets/1645256/12810641/6383f592-cb1f-11e5-922c-c1d551f5ab12.png)

The cloning works as expected, but clicking the date input triggers this error: 

**Uncaught Error: datetimepicker component should be placed within a relative positioned container**

`.input-group` already has `"position: relative;"` set in a separate CSS file. I tried adding this as an inline style, but id didn't make a difference.

Any ideas? Thanks in advance!

**Comment by JamsusMaximus** [comment]
![image](http://g.recordit.co/Zss0VJxc6G.gif)

**Comment by JamsusMaximus** [comment]
+ StackOverflow question: http://stackoverflow.com/questions/35204626/attaching-eonasdan-datetimepicker-to-dynamically-created-element-returns-relati

**Comment by William-H-M** [comment]
> Solved! Swapped the order of my .datetimepicker and insertAfter functions. Was trying to add a datetimepicker to an input that didn't yet exist.
