### ISSUE TITLE
Problem with propagation keypress event. 

### ISSUE THREAD

**Issue by topguss** [Eonasdan/bootstrap-datetimepicker#1452]
Problem with propagation key-press event.

Some application have to have 'next gui-control on Enter press' functionality. We use code below to register global handler, but it doesn't work on Bootstrap 3 Datepicker. Can you provide some way that we can 'override' default behavior? 

```
jQuery.extend(jQuery.expr[':'], {
  focusable: function (el, index, selector) {
    return $(el).is('a, button, :input, [tabindex]');
  }
});
```

```
$(document).on('keypress', 'input,select,textarea', function (e) {
  if (e.which == 13) {
    e.preventDefault();
    // Get all focusable elements on the page
    var $canfocus = $(':focusable');
    var index = $canfocus.index(document.activeElement) + 1;
    if ($canfocus.eq(index).attr('tabindex') == -1) index++;
    if (index >= $canfocus.length) index = 0;
    $canfocus.eq(index).focus();
  }
});
```

**Comment by Eonasdan** [comment]
I don't support v3. I don't even have much time for v4. You're welcome to ask your question on SO

**Comment by topguss** [comment]
Hi, here is post on SO:
[http://stackoverflow.com/questions/35309412/bootstrap-3-datepicker-propagation-keypress-event?noredirect=1#comment58375693_35309412](http://stackoverflow.com/questions/35309412/bootstrap-3-datepicker-propagation-keypress-event?noredirect=1#comment58375693_35309412)

Solution is additional script witch create new event dpkeydown.
Full code, you can see on: [http://jsfiddle.net/gekvf59r/1/](http://jsfiddle.net/gekvf59r/1/)
