### ISSUE TITLE
locale English week starting on Monday

### ISSUE THREAD

**Issue by Eraldo** [Eonasdan/bootstrap-datetimepicker#1460]
How can I get the English locale version with weekdays starting on Monday?
How about adding a week starts on setting that overwrites the locale if given?

**Comment by Eonasdan** [comment]
see the docs: http://eonasdan.github.io/bootstrap-datetimepicker/Options/#locale

**Comment by Eraldo** [comment]
I did see that and read through it.
I _want_ 'en' locale.. however with weekdays starting on Monday.

Example google calendar: I have locale set to 'en' and `week starts on` set to Monday.

**Comment by Eonasdan** [comment]
`en` isn't a valid moment locale. If by English you mean UK/GB then you need [`en-gb`](https://github.com/moment/moment/blob/develop/locale/en-gb.js)

**Comment by Eraldo** [comment]
Sorry.. you are right.
However I cannot set the week-start day that way.

**Comment by Eonasdan** [comment]
start of the week is controlled by what locale you are using, thus if you include and set the locale to `en-gb` it will (should) set the start of the week to Monday

**Comment by Eraldo** [comment]
The default locale on my system is english.. however across my system all calendar weeks start on Monday. What locale would that be in this case?

**Comment by Eonasdan** [comment]
Once again, the `locale` option sets the start of the week. There isn't a option on the picker to change this without changing the locale. If you can't use the British locale, create your own locale file.

https://jsfiddle.net/Eonasdan/0Ltv25o8/2429/

**Comment by Eraldo** [comment]
Nice.. it works nicely in the fiddle.
I feel really incapable now.
I included 'moment.min.js' instead of 'moment-with-locales.min.js' ..I thought I used the other one.
Bug was on my side sorry. And thank you for helping me find where the error was. :D

*cheer*
