### ISSUE TITLE
Broken CSS reference

### ISSUE THREAD

**Issue by Eraldo** [Eonasdan/bootstrap-datetimepicker#1463]
The CSS file
`'components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker-standalone.css'`
references a file which could not be found:
`components/eonasdan-bootstrap-datetimepicker/build/fonts/glyphicons-halflings-regular.eot`

There is a link to a fonts directory that does not exist!
This happens via `'../fonts'`.

Please look into it and tell me whether you want the reference removed the the font added.
(then I can create a PR if you wish)

(At the moments this breaks my building process)

Your judgement is appreciated. ;)

**Comment by Eonasdan** [comment]
unfortunately the standalone css assumes you have a folder where your css lives `/css` and the folder where your font is is one level above `/fonts`.  I'm not sure there's a good way to make that work for everyone in ever case since we're not including the fonts.

BS4 has dropped the glyphicons anyway.

**Comment by Eraldo** [comment]
I agree.
I am already using BS4 on one project where I also use your datepicker.
Would it be okay to add a comment in the docs for the standalone users telling them to include the fonts?
In any case I think it is good practise not to include broken links.
Until then I will use my patched version.
Thanks for the reply Jonathan.

**Comment by natecox** [comment]
I have a pull request open to remove the references to these files, which fixed the problem for me.

**Comment by nicklecoder** [comment]
I hope this gets merged in soon; installing eonasdan-bootstrap-datetimepicker via bower in Django breaks things on `./manage.py collectstatic` because Django attempts to resolve file references and fails.

**Comment by thecortex** [comment]
I m having the same issue on Django Bower

```
whitenoise.storage.MissingFileError: The file 'eonasdan-bootstrap-datetimepicker/build/fonts/glyphicons-halflings-regular.eot' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x1061cb080>.

The CSS file 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker-standalone.css' references a file which could not be found:
  eonasdan-bootstrap-datetimepicker/build/fonts/glyphicons-halflings-regular.eot

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

**Comment by GitRon** [comment]
Sorry to dig this up but it seems the issue hasnt been tackled yet, right?

**Comment by GitRon** [comment]
@natecox Your PR #1733 got closed because its not targeting dev. Could you change that?
