### ISSUE TITLE
How to close DateTimePicker after date is picker

### ISSUE THREAD

**Issue by anikets43** [Eonasdan/bootstrap-datetimepicker#1464]
Hi,

Is there any event or configuration to close the datetimepicker automatically after date is picked.

**Comment by juancarlosfarah** [comment]
It should close automatically by default as explained [here](https://eonasdan.github.io/bootstrap-datetimepicker/Options/#keepopen). However, if there is a time component to your picker, it won't close automatically.

**Comment by anikets43** [comment]
I was using TimePicker but when i changed the format to 'MM/DD/YYYY', it worked like charm.
Thanks Juan!!

**Comment by juancarlosfarah** [comment]
You're welcome! Glad to help.

**Comment by Eonasdan** [comment]
@admackin you can also use the format string `L` which will provide the default date format for the locale you're using
