### ISSUE TITLE
Multiple Select Date.

### ISSUE THREAD

**Issue by aaesis** [Eonasdan/bootstrap-datetimepicker#1465]
Can this bootstrap-datetimepicker can have multitple select on the dates?

**Comment by elephantux** [comment]
+1

**Comment by danielefenix** [comment]
+1

**Comment by EdwinRoestenburg** [comment]
+1

**Comment by EdwinRoestenburg** [comment]
I suspect it's not easy to extend the tool to include the selection of multiple date/times, but it would be great to have. Yours is the best DateTime picker I found, but I need the multiple selection option (though I need it only for the dates and not the times). I would use it to allow the user to schedule items, with exceptions on certain days, or alternatively to select the dates on which action need to take place. In either case I'm going to need multiple selections. 

But even if you don;t build it in: big thumbs up for a datetime picker well built !!

**Comment by sabansen** [comment]
+1

**Comment by ravimallya** [comment]
+1 
Here is an example of old bootstrap datepicker http://bootstrap-datepicker.readthedocs.io/en/latest/options.html#multidate which is no longer maintained it seems. This is the playground: http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=2&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

**Comment by tomheathershub** [comment]
+1

**Comment by Lukas1990** [comment]
+1

**Comment by Lukas1990** [comment]
or multiple select Hours

**Comment by William-H-M** [comment]
This has been implemented on V5 https://github.com/tempusdominus/bootstrap-3
