### ISSUE TITLE
Firefox 44.0.2 rendering issue

### ISSUE THREAD

**Issue by elnibs** [Eonasdan/bootstrap-datetimepicker#1466]
Hello guys,
there is a rendering issue on firefox 44.0.2
![issue on firefox](https://cloud.githubusercontent.com/assets/7337098/13052860/da6504b0-d409-11e5-800c-70f510052881.png)

To reproduce it just click to the next month, day 26 appears twice

**Comment by charlesartbr** [comment]
This issue happens with me too, but with Firefox 46.0.1 and only on October.

![ff-october-2015](https://cloud.githubusercontent.com/assets/12157011/15114729/b36540e6-15d1-11e6-972a-5252980e2f09.png)

![ff-october-2016](https://cloud.githubusercontent.com/assets/12157011/15114730/b365a248-15d1-11e6-8d8b-5cc56676c697.png)
