### ISSUE TITLE
Act as a counter

### ISSUE THREAD

**Issue by DomagojHrzic** [Eonasdan/bootstrap-datetimepicker#1467]
Hello, 
i'm using datetimepicker in multiple inputs with different formats. I want to customize one of them to act as a counter. Is this possible or it has restrict to max of 24 hour. 

 $('.picktimeNoLimit').datetimepicker({
                      format: 'LT',
                      locale: 'hr',
                      stepping: '15',
                      useCurrent: false
                  });
Thanks

**Comment by Eonasdan** [comment]
I guess you could set the `maxDate`, other wise, you'll have to listen to the onchange event and work some magic with that.
