### ISSUE TITLE
Issue with "sk" locale and minDate

### ISSUE THREAD

**Issue by soft17** [Eonasdan/bootstrap-datetimepicker#1469]
if i set options with datetimepicker:

locale: 'sk'
format: 'L'
minDate: '20.02.2016'

he throw error with parsing mindate, but for locale "sk" format "L" = DD.MM.YYYY, but datepicker choose "en" format MM/DD/YYYY 

here is link to fiddle:
http://jsfiddle.net/70k22yay/

**Comment by William-H-M** [comment]
Really old issue but still, use:
this way is better as moment stated it

> Warning: Browser support for parsing strings is inconsistent. Because there is no specification on which formats should be supported, what works in some browsers will not work in other browsers.
> 
> For consistent results parsing anything other than ISO 8601 strings, you should use String + Format.




http://momentjs.com/docs/#/parsing/string/
`minDate: moment('20.02.2016', 'DD.MM.YYYY')`
