### ISSUE TITLE
keyboardNavigation: false

### ISSUE THREAD

**Issue by skironDotNet** [Eonasdan/bootstrap-datetimepicker#1470]
in https://github.com/tarruda/bootstrap-datetimepicker there is an option keyboardNavigation: false
I can't find it in your version. The reason I would like to have it is when a user click on the text box the picker show up, but then let say using arrows can navigate to a specific digit and change it via typeing that may be faster or preferred for someone.

Without keyboardNavigation: false, using arrows moves selection within picker, so there is no way to manually(using keyboard) delete any digits and reenter

Maybe you have some "focus" option, I'll try to find it but please respond if you have such option

Thanks!

**Comment by valeriob** [comment]
yep that would be very usefull

**Comment by gosieg** [comment]
I was able to fix this by adding these configuration options:

            up: null,
            down: function (widget) {
                if (!widget) {
                    this.show();
                    return;
                }
            },
            left: null,
            right: null,
            t : null,
            'delete' : null

**Comment by valeriob** [comment]
cheers @gosieg !

**Comment by valeriob** [comment]
Since you have closed this, do you plan to add an option to make explicit what @gosieg is doing ?

**Comment by Eonasdan** [comment]
No, because it's already there. `keyBinds` allows you to customize what it does.

http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#keybinds
http://eonasdan.github.io/bootstrap-datetimepicker/Options/#keybinds

**Comment by inad9300** [comment]
Please, consider including an example of this particular use case somewhere in the documentation. I was trying to achieve the same thing using a no-op function (`_.noop`) as opposed to `null` before reading this issue, but the default event is still _prevented_ in this case, so it wouldn't work.
