### ISSUE TITLE
Set startDate based on another datepicker date selection (without date-range picker)

### ISSUE THREAD

**Issue by isfak** [Eonasdan/bootstrap-datetimepicker#1472]
Hello all,

I am creating some kind of reservation system for a hotel. I have 2 separate datepickers, one for selecting the arrival date and one for selecting the departure date of the guest.
When the user sets the arrival date via the first datepicker, I would like to set the startDate property of the departure date datepicker to the arrival date, so that the guest cannot select departure date prior to arrival date. I don't want to use date-range picker for this.

Thanks in advance!

**Comment by Eonasdan** [comment]
you mean like this: http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers

**Comment by isfak** [comment]
exactly that! Thanks a million!
