### ISSUE TITLE
Is it possible to overwrite the render function?

### ISSUE THREAD

**Issue by ImanMh** [Eonasdan/bootstrap-datetimepicker#1473]
I wish I could get the current date for each day in calendar and convert it to Persian date and show both Persian and Gregorian date in each cell. Here is an example: 

![screen shot 1394-12-01 at 19 24 07](https://cloud.githubusercontent.com/assets/4482199/13197594/8d27bff6-d807-11e5-9735-52eda6c5690c.png)

If there was a render function that I could overwrite I could make much more changes to my view. What is the closest thing I can do right now? Is it possible?

**Comment by Eonasdan** [comment]
sorry, but you'll have to make it do that yourself or find a picker that supports that.
