### ISSUE TITLE
Disable decades view

### ISSUE THREAD

**Issue by MoAsmar** [Eonasdan/bootstrap-datetimepicker#1474]
Hi,
If anyone is able to disable last click on 'pickerSwitch' in years view to prevent moving to decades view, I want to make years view the last view, and stop going to decades. 

I've taken a look on options but I could not find any solution, please advice.

Thanks

**Comment by chrisdemetriad** [comment]
+1 !!!

**Comment by z827101859** [comment]
version : 4.17.37
bootstrap-datetimepicker.js，在源码的第500行，有一个showMode方法，改为如下，就可以禁用decades view了：

showMode = function (dir) {
                if (!widget) {
                    return;
                }
                /********begin********/
                /********disable decades View********/
                /********by sweetyx********/
                var preVM = Math.max(minViewModeNumber, Math.min(3, currentViewMode + dir));
                if(preVM == 3){
                    return;
                }
                /*******end******/
                if (dir) {
                    currentViewMode = Math.max(minViewModeNumber, Math.min(3, currentViewMode + dir));
                }
                widget.find('.datepicker > div').hide().filter('.datepicker-' + datePickerModes[currentViewMode].clsName).show();
            },

**Comment by Zero3** [comment]
Makes this bug worse: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1372

**Comment by lesilent** [comment]
Give this css a try:

```
.bootstrap-datetimepicker-widget .datepicker-years thead .picker-switch {
     cursor: default;
     pointer-events: none;
}

```

**Comment by applebya** [comment]
Yeh, that works for me! Thanks @lesilent

**Comment by Zero3** [comment]
@William-H-M was this issue fixed?

**Comment by William-H-M** [comment]
Hi, @Zero3 be itself this is not an issue as is not an option not working, but a solution has been given,

**Comment by Zero3** [comment]
@William-H-M Yes, this is indeed a feature request. It sounds like you don't want these here on GitHub issues. Is there another place to submit it? I think it would be a shame if this is forgotten about, now that you closed the issue.

**Comment by William-H-M** [comment]
Hi, @Zero3 indeed as you have said this is more a feature request than an issue, an issue would be more like a bug, you can always do a PR to add the feature but this project is currently under code freeze as been said on the read me of the project:

> We are in code freeze and this issue tracker is no longer actively monitored. I'll be closing PR that do not contribute emergency fixes and leaving some open as they are evaluated for migration into the new repo.

But of course you can always, as said before, do a PR or either do it on the current repo that's being rewrite it and can take feature request.

BS3 Version:
https://github.com/tempusdominus/bootstrap-3

BS4 Version:
https://github.com/tempusdominus/bootstrap-4

**Comment by natashawylie** [comment]
Slightly better work around for disabling decades available here: https://stackoverflow.com/a/49008471/664777

It actually disables on page load rather than other workarounds which only disable once a date has been clicked.
