### ISSUE TITLE
Datepicker doesn't grey out minDate - 1 day

### ISSUE THREAD

**Issue by SZankel** [Eonasdan/bootstrap-datetimepicker#1475]
When you give a moment-object with minDate to the datepicker it doesn't grey out the minDate - 1 day. The date is not chooseable, but still the user might click on it and datepicker closes.

Enviroment:
- Angular 1.5
- Moment.js
- JQuery

**Comment by marc-gist** [comment]
It works fine for me; perhaps you can show your code or link to a jsfiddle or something.

**Comment by Zheult** [comment]
:+1: doesn't grey out minDate - 1

**Comment by SZankel** [comment]
Hello guys I think it is a moment.js timezone issue. Have to check.

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
