### ISSUE TITLE
Documentation Options missing: pickDate PickTime

### ISSUE THREAD

**Issue by marc-gist** [Eonasdan/bootstrap-datetimepicker#1476]
need to update docs for and add subject.

**Comment by Eonasdan** [comment]
those options were replaced in v4

**Comment by marc-gist** [comment]
But it still works and I can't seem to find how to set it otherwise.

**Comment by marc-gist** [comment]
perhaps I should explain better: here is my code for only having date picker (no time) and it should close when I choose a date.  This works, but took me looking through google to find the solution!

`$(".date-picker").datetimepicker({
            format: 'YYYY-MM-DD',
            defaultDate: t,
            minDate: t,
            keepOpen: false,
            pickTime: false
        });
`

**Comment by antongorodezkiy** [comment]
Some more info for those who will find this thread via search like I did - https://github.com/Eonasdan/bootstrap-datetimepicker/issues/864#issuecomment-76004406
