### ISSUE TITLE
Cannot set Default Time

### ISSUE THREAD

**Issue by seivad** [Eonasdan/bootstrap-datetimepicker#1477]
I have the time and date components split between 2 separate input boxes. here is my code for the time picker component, but no matter what I pass it (moment, string) it defaults to the wrong time.

$('#time-picker').datetimepicker({format:'LT', defaultDate: timeNow, allowInputToggle: true, stepping: '15', disabledHours: ['0', '1', '2', '3', '4', '5', '22', '23'] });

timeNow is a moment object and formated as hh::mm A

I've tried formatting from LT to hh:mm A and it didn't do anything different. 

Pretty stuck on this, not being able to simple set the defaultTime is a pain.

**Comment by afanasy** [comment]
I'm experiencing the same problem
```js
datetimepicker({
  format: 'hh:mm A',
  showClear: true,
  defaultDate: moment(timePoint.value, 'HH:mm:ss')
})
```
this resets input time to 12:00 PM when the picker pops up

**Comment by afanasy** [comment]
It seems to be connected with resetting time here to start of the day here:
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L759

**Comment by afanasy** [comment]
Seems to be some issue with timezones (picker changes the input time according to local timezone), can be fixed by using `timeZone: null` in options
```js
datetimepicker({
  format:'LT',
  defaultDate: timeNow,
  allowInputToggle: true,
  stepping: '15',
  disabledHours: ['0', '1', '2', '3', '4', '5', '22', '23'],
  timeZone: null
})
```
