### ISSUE TITLE
How to Prevent Time adjustment from increasing Date

### ISSUE THREAD

**Issue by BLooRT** [Eonasdan/bootstrap-datetimepicker#1480]
I'm trying the sideBySide setup, and what i find is increasing the hours will increment the date.
increasing the minutes will increment the hours.  Currently my picker responds as if you were adjusting an actual clock. (pretty cool)  

i assume this is normal behavior, but is there an option to disable this? (so adjusting minutes does not effect the hours,  nor adjusting hours does not effect the days, etc...)

tia.

**Comment by dflickcb** [comment]
Having the same issue. Did not see an option to disable the default behavior. Is anything in the works to add this option? 
thanks
