### ISSUE TITLE
Custom fate time format

### ISSUE THREAD

**Issue by stojankukrika** [Eonasdan/bootstrap-datetimepicker#1482]
Hi.
Can you list me all aveable format for date and time,because I have in backend php application with user custom format date and time so I need that info how to convert php date to valid datetime piker value abd oposite.Can you halp me with that custom format list for date and time?

**Comment by Eonasdan** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#format

**Comment by stojankukrika** [comment]
:+1:
