### ISSUE TITLE
export dateTimePicker

### ISSUE THREAD

**Issue by khakulov** [Eonasdan/bootstrap-datetimepicker#1484]
for npm usage the library should export dateTimePicker function like:

``` javascript

import dateTimePicker from 'eonasdan-bootstrap-datetimepicker';
const options = {
    showTodayButton: true,
};
const dtp = dateTimePicker(element, options);

```

actually i have to import jQuery and use $(element).datetimepicker. jQuery library must be the same instance as dateTimePicker's jquery. See #1483 
Now i have to remove node_modules/eonasdan-bootstrap-datetimepicker/node_modules/jquery to work with this library.

**Comment by davidlanger** [comment]
I have the same issue but the development branch does export it correctly.

Although there it still has its own dependencies, so if those do not match you will have no way to load a locale beforehand.

My proposal would be to instead use peerDependencies, that will print a nice warning if you did not install the other modules.
