### ISSUE TITLE
[minorBug] minDate() bad disabling/graying

### ISSUE THREAD

**Issue by bakroistvan** [Eonasdan/bootstrap-datetimepicker#1489]
Set datepicker1 to today.
After that click on the detepicker2 calendar header to make it 100 year division.
( February 2016 >> 2016 >> 2011-2022 )

You can not click on 2012-2023.

Try here: [http://jsfiddle.net/4288hmj6/1/](http://jsfiddle.net/4288hmj6/1/)

**Comment by JaniceLian** [comment]
the same problem

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.
