### ISSUE TITLE
viewDate ignores time

### ISSUE THREAD

**Issue by lauramosher** [Eonasdan/bootstrap-datetimepicker#1491]
**Desire**
Current Date is used, Time is set to 4:00 PM

**Issue**
`viewDate` takes a moment object, but ignores the time.

**Simplified setup in jsfiddle**
This shows that `defaultDate` works just fine and `viewDate` works fine for the year and month, but any time input is ignored.
http://jsfiddle.net/0Ltv25o8/2488/

**System**

```
bootstrap3-datetimepicker-rails (4.17.37)
  momentjs-rails (>= 2.8.1)
jquery-rails (4.0.5)
jquery-ui-rails (5.0.5)
momentjs-rails (2.11.0)
```

Please let me know if you need further information... I am happy to do some more troubleshooting on my end.

**Comment by mlmadque** [comment]
I am seeing this behavior. I am using 4.17.45.  Any solution for this?
