### ISSUE TITLE
Not compatible with BS4

### ISSUE THREAD

**Issue by anikets43** [Eonasdan/bootstrap-datetimepicker#1492]
Hi Folks,

I upgraded the application from Bootstrap 3 to 4. Facing UI issues after upgradation. Is there any plan for new release with BS4?

**Comment by Eonasdan** [comment]
plans? sure, but bs4 is in **alpha** so I'm not in a hurry

**Comment by anikets43** [comment]
Bootstrap 3 'table-condensed' class has been replaced by 'table-sm'.
I added below styles to fix UI issue.
.table-condensed th, .table-condensed td {
  padding: .3rem;
}

**Comment by canfiax** [comment]
Hey @Eonasdan - I would love some Bootstrap 4 support as well. Currently I run the package under Bootstrap 4, but its just minor style issues (i.e. class renames etc) that is an issue. Using the css snippet from @anikets43 solves most of the styling issues.

**Comment by anikets43** [comment]
@canfiax Glad to know it helped you!!
Glyphicons are not included in BS4, you can customize the icons in the configuration. Something like below:
`icons: any = {
        time: 'fa fa-clock-o',
        date: 'fa fa-calendar',
        up: 'fa fa-angle-up',
        down: 'fa fa-angle-down',
        previous: 'fa fa-chevron-circle-left',
        next: 'fa fa-chevron-circle-right',
        today: 'fa fa-calendar-check-o',
        clear: 'fa fa-trash-o',
        close: 'fa fa-times-circle'
    };

    dateFormat: any = {
        'date': {
            format: 'MM/DD/YYYY',
            icons: this.icons
        },
        'datetime': {
            format: '',
            icons: this.icons
        },
        'time': {
            format: 'LT',
            icons: this.icons
        },

    };`

**Comment by canfiax** [comment]
Thanks @anikets43 - Can you show some more code examples of how to use the dateFormat variable? And why use LT instead of HHss in format?

**Comment by websiteduck** [comment]
The css and icons fixed the issues that I ran into, thanks @anikets43 

Here is a jsfiddle of those two changes https://jsfiddle.net/wrLncr06/
