### ISSUE TITLE
Set year ranges or max/last year for viewMode: years

### ISSUE THREAD

**Issue by mardanlin** [Eonasdan/bootstrap-datetimepicker#1501]
I cannot find anywhere in the documentation how to set the max year or a custom year range on the viewMode: 'years' option.

I am using a setup like this:

```
$('#date-input').datetimepicker({
    viewMode: 'years',
    maxDate: moment()
});
```
However, all the maxDate option does is prevent you from clicking a year in the future, it doesn't hide them.

This presents a dialogue like this:
http://i.stack.imgur.com/2hZbe.png

However, it should only show up to the current year (2016) so that more past years would fit on the page. In other words, the default range to go from 2005-2016 instead of from 2011-2022.

**Comment by Eonasdan** [comment]
Sorry, but no. Any disabled date (including year selection) have a class of `disabled`. If you want to completely hide or remove them, it's up to you to implement that.
