### ISSUE TITLE
Timepicker Widget Incorrect Auto-Formatting

### ISSUE THREAD

**Issue by LHinson** [Eonasdan/bootstrap-datetimepicker#1504]
In testing the widget [1], I found that is not correctly reformatting the time. For example...

- 200 gave me 8:00 PM
- 900am gave me 8:00 PM
- 750pm gave me 8:00 PM
- 340 gave me 11:11 AM
- 600 gave me 10:20 AM

[1] http://eonasdan.github.io/bootstrap-datetimepicker/#custom-formats

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.

**Comment by LHinson** [comment]
@Eonasdan Unfortunately I don't know JavaScript :/ Was curious if it would be possible to improve how the widget reformats the input? For example, if I input "200", I would expect "2:00 PM" or "2:00 AM" vs "8:00 PM".

**Comment by Eonasdan** [comment]
The parsing is handled by momentjs which expects the input string to be in an appropriate format. If you set the picker's format to `LT` or `hh:mm a` moment will attempt to apply that format to the input date. Entering 24 hour time as `0200` or `1400` worked as expected. I really don't know why 200 would convert to 8:00 PM but 200 is not a valid time.

You'll either have to validate the inputs or enforce the input yourself.

Perhaps asking on Stackoverflow would give you some direction. You could also try playing around with the format string.

I'm sorry, but I don't consider this a bug.

**Comment by LHinson** [comment]
Fair enough. Thanks @Eonasdan
