### ISSUE TITLE
Widget positioning when positioned to the top of date input

### ISSUE THREAD

**Issue by lydongray** [Eonasdan/bootstrap-datetimepicker#1505]
My websites layout is quite complicated so I've created a simple example showing this issue here:

http://embed.plnkr.co/VOVjoHewMWUmOBjU2gD5/

The issue is the positioning of the widget when it tries to position itself to the top of the datetime input box when it has no room at the bottom of the page. 

To reproduce this you need to have a parent div positioned relative. Inside the parent you have the datetime widget and another element tall enough that it pushes the datetime input box near the bottom of the page. This forces it to create the widget on top of the datetime input box.

I have written a fix for this and will be creating a PR soon. Before doing so, I just want to make sure I have not done anything wrong or that there isn't a simple fix to my issue.

**Comment by pedrocosta** [comment]
Hi, can you share your solution? I am having the same problem... Thanks

**Comment by lydongray** [comment]
Hi Pedro,
Look in the source code and replace it with the following:

```javascript
widget.css({
    top: vertical === 'top' ? position.top - widget.height() - element.outerHeight() / 2 : position.top + element.outerHeight(),
    bottom: 'auto',
    left: horizontal === 'left' ? (parent === element ? 0 : position.left) : 'auto',
    right: horizontal === 'left' ? 'auto' : parent.outerWidth() - element.outerWidth() - (parent === element ? 0 : position.left)
});
```

What this does is keep the bottom position 'auto' and positions the top relative to the input element.

**Comment by pedrocosta** [comment]
Thanks!

**Comment by Zero3** [comment]
I worked around this issue by wrapping the datepicker in a container and putting `position: relative;` on it.

**Comment by lydongray** [comment]
Hi Zero3,
That is a solution I have tried and would work in most situations. My solution fixes special problem where there is a larger parent div with the style `overflow: auto`. The parent div becomes scrollable when the contents are too big. Wrapping the datepicker in a container and giving it `position: relative` when there is another parent with `overflow: auto` causes the date popup to be hidden behind the parent div.

**Comment by Zero3** [comment]
@lydongray That is useful information to have. Thanks!

**Comment by ziaulrehmandevsinc** [comment]
Wondering when this issue will get resolved, i.e: fix goes to production.
