### ISSUE TITLE
How can I retain the value which is there in database?

### ISSUE THREAD

**Issue by clubbavi** [Eonasdan/bootstrap-datetimepicker#1506]
Hello,

I am using bootstrap-datetimepicker in my rails project.
Rails 4.2.3, Ruby 2.2.
We are using bootstrap-datetimepicker pluggin.
So my requirement is to use minDate and maxDate in a single textbox.
I am achieving that by:

```
var todayDate = new Date();
var maxDate = todayDate.setYear(todayDate.getFullYear() + 10);

$('#someID').datetimepicker({
    format: 'DD-MM-YYYY',
    minDate: todayDate,
    maxDate: maxDate,
    widgetPositioning: {
        horizontal: 'auto',
        vertical: 'auto'
    }
});

$("#someID").on("dp.change", function (e) {
    $('#someID').data("DateTimePicker").setMinDate(e.date);
});
$("#someID").on("dp.change", function (e) {
    $('#someID').data("DateTimePicker").setMaxDate(e.date);
});
```

In this always the minDate comes as selected. It doesn't take the value from the database which is already stored. And if I remove both minDate & maxDate, I can see the correct value from database.
How can I fix this?

Thanks.

**Comment by craig-winaust** [comment]
Use the defaultDate option and set it to the date from the database.
