### ISSUE TITLE
Wrong date displayed from value attribute

### ISSUE THREAD

**Issue by clavier-souris** [Eonasdan/bootstrap-datetimepicker#1508]
http://jsfiddle.net/bg0qn9ey/

The date shown in the text input on load ( if input has a value ) is not correct.

**Comment by donnyv** [comment]
The same thing happens with this format "ddd MMM DD YYYY".

**Comment by Eonasdan** [comment]
Your input value doesn't match your format. Try using `[extraFormats](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#extraformats)` or change `format` to match your input value
