### ISSUE TITLE
If there is a value datetimepicker don't work

### ISSUE THREAD

**Issue by josgiwta** [Eonasdan/bootstrap-datetimepicker#1512]
I have a php app and I Use datetimepicker and works perfect .
But in the edit.php that I give a value to datetimepicker with "php"  dont work any more.

This is the code in the edit.php that fill the 

`<table>
<tr><td> Meeting Time :</td><td><input type="text" name="meettime" id="datetimepicker3" value="<?php  

```
if(($info['meet_time'])=='00-00-00')
{
   $mysqldate28 ='Δεν έχει καθοριστεί';
   echo $mysqldate28;
}
else    
{
$mysqldate28 = date('H:i:s', strtotime($info['meet_time']));
echo $mysqldate28;
}
```

?>"/>
</td></tr></table>`

and this is the java

```
        jQuery(document).ready(function () {
            jQuery('#datetimepicker3').datetimepicker({
                    pickDate: false,
             format: 'HH:mm'

            });
        });
```

and this is the before close body.....ref..

<script src="http://code.jquery.com/jquery.js"></script>

```
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

        <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js"></script>        
        <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.4.0/lang/en-gb.js"></script>  
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/3.3.0/ekko-lightbox.min.js"></script>

        <script src="js/bootstrap-datepicker.js"></script>  
        <script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.0.0/js/bootstrap-datetimepicker.min.js"></script>`
```

Can you tell what i have to do??????
thank you in advance

**Comment by scuba6388** [comment]
The value of the input element has to match the specified formatting datetimepicker in order for the value to be populated.

**Comment by SarahITH** [comment]
I agree to the above solution Format is important parameter and one more is 

```
useCurrent: false,
```

Add this to your code , hope its helpful
