### ISSUE TITLE
Hover over text for button to switch from time selector to date selector is wrong

### ISSUE THREAD

**Issue by aprevost** [Eonasdan/bootstrap-datetimepicker#1513]
When selecting date and then hover over the button to switch to selecting time, the hover over text is correct, it says "Select Time":

<img width="1280" alt="screen shot 2016-03-15 at 12 48 45 pm 2" src="https://cloud.githubusercontent.com/assets/5704741/13786068/76c62b8c-eaac-11e5-905f-341dcd9e109f.png">

However, when selecting time and then hover over the button to switch to selecting date, I think the hover over text should say "Select Date". Instead, it also says "Select Time":

<img width="1280" alt="screen shot 2016-03-15 at 12 49 35 pm 2" src="https://cloud.githubusercontent.com/assets/5704741/13786107/968beb78-eaac-11e5-9de9-9c6bbbbd51e4.png">

**Comment by SarahITH** [comment]
Hi,
  The above issue can be resolved through the following code: 
  In the file "bootstrap-datetimepicker.js" on line no. 1051 
Replace-
togglePicker: function (e) {
                    var $this = $(e.target),
                        $parent = $this.closest('ul'),
                        expanded = $parent.find('.in'),
                        closed = $parent.find('.collapse:not(.in)'),
                        collapseData;

                    if (expanded && expanded.length) {
                        collapseData = expanded.data('collapse');
                        if (collapseData && collapseData.transitioning) {
                            return;
                        }
                        if (expanded.collapse) { // if collapse plugin is available through bootstrap.js then use it
                            expanded.collapse('hide');
                            closed.collapse('show');
                        } else { // otherwise just toggle in class on the two views
                            expanded.removeClass('in');
                            closed.addClass('in');
                        }
                        **if ($this.is('span')) {
                            $this.toggleClass(options.icons.time + ' ' + options.icons.date);
                        } **else {
                            $this.find('span').toggleClass(options.icons.time + ' ' + options.icons.date);
                        }

                        // NOTE: uncomment if toggled state will be restored in show()
                        //if (component) {
                        //    component.find('span').toggleClass(options.icons.time + ' ' + options.icons.date);
                        //}
                    }
                },
WITH -
togglePicker: function (e) {
                    var $this = $(e.target),
                        $parent = $this.closest('ul'),
                        expanded = $parent.find('.in'),
                        closed = $parent.find('.collapse:not(.in)'),
                        collapseData;

                    if (expanded && expanded.length) {
                        collapseData = expanded.data('collapse');
                        if (collapseData && collapseData.transitioning) {
                            return;
                        }
                        if (expanded.collapse) { // if collapse plugin is available through bootstrap.js then use it
                            expanded.collapse('hide');
                            closed.collapse('show');
                        } else { // otherwise just toggle in class on the two views
                            expanded.removeClass('in');
                            closed.addClass('in');
                        }
                        ** #if ($this.is('span')) {                           
                            $this.toggleClass(options.icons.time + ' ' + options.icons.date);
                            if ($this.hasClass(options.icons.date)){
                                $this.parent().attr({'data-action':'togglePicker', 'title':'Select Date'});
                            }
                            else{
                               $this.parent().attr({'data-action':'togglePicker', 'title':'Select Time'});
                            }
                        }** else {
                            $this.find('span').toggleClass(options.icons.time + ' ' + options.icons.date);
                        }

                        // NOTE: uncomment if toggled state will be restored in show()
                        //if (component) {
                        //    component.find('span').toggleClass(options.icons.time + ' ' + options.icons.date);
                        //}
                    }
                },
