### ISSUE TITLE
Get value in English when Locale is set to another language.

### ISSUE THREAD

**Issue by dedles** [Eonasdan/bootstrap-datetimepicker#1517]
In my app, the user can set the locale manually. But I want to store the value of the datetimepicker in the database as English. Currently when the locale is set to Chinese, for instance, the value changes from am/pm to Chinese characters. Is there away to record the value into English while the locale is set to another language?

**Comment by Eonasdan** [comment]
I'd look at the momenjs docs for that kind of thing or convert it server side.
