### ISSUE TITLE
Widget doesn't work after using .toggle() or .show() function

### ISSUE THREAD

**Issue by simivar** [Eonasdan/bootstrap-datetimepicker#1520]
I was trying to make widget work without input field (or with hidden one) and weird bug occured: after showing widget with .toggle() or .show() it won't work - non of the buttons are clickable.

Example:
http://jsfiddle.net/Eonasdan/516zsh7b/

**Comment by sheepcount** [comment]
For me, this issue occurs in IE11 and Firefox when `widgetParent` is a button. It works fine on Chrome or when using a surrounding `<div>` as the `widgetParent`.
