### ISSUE TITLE
do not clear data on initialization

### ISSUE THREAD

**Issue by zoinkydoink** [Eonasdan/bootstrap-datetimepicker#1521]
I auto generate fields for datepickers but as i generate them, i fill them with dates I want and as soon as i apply $('.datetimepicker').datetimepicker(); it deletes my dates.

I need a way to apply $('.datetimepicker').datetimepicker(); after creating them but do not clear the dates I have put in.

**Comment by scuba6388** [comment]
I would have thought doing this by default would be built in, but here's what I'm doing translated to your example scenario...

```
var date = $('.datetimepicker').val();

$('.datetimepicker').val("");

$('.datetimepicker').datetimepicker({
    defaultDate: date,
    useCurrent: false
});
```

I'd love to see or hear better ways of doing this, so let me know if you found one.
