### ISSUE TITLE
npm version out of date

### ISSUE THREAD

**Issue by jwanga** [Eonasdan/bootstrap-datetimepicker#1522]
Hi, 

The current npm version is 4.15.35. I'm attempting to avoid adding bower as a dependency exclusively for the datepicker.

Thanks for your hard work!

**Comment by melanke** [comment]
+1

**Comment by adam1658** [comment]
+1

**Comment by Kilowhisky** [comment]
+1

**Comment by JellyBellyDev** [comment]
👍

**Comment by JellyBellyDev** [comment]
👍 

Please publish new tag `4.17.37` on npm!
Thanks

**Comment by jonatanjohnsson** [comment]
👍

**Comment by sebestenyb** [comment]
+1

**Comment by franciscogouveia** [comment]
Temporary fix, just add to your `package.json`:

```json
"dependencies": {
    ....
    "eonasdan-bootstrap-datetimepicker": "git://github.com/Eonasdan/bootstrap-datetimepicker.git#4.17.37",
    ....
}
```

Then, `npm install`

**Comment by JellyBellyDev** [comment]
It's ok, but I do not like the workaround! 😄

**Comment by OvermindDL1** [comment]
Still not updated as of current.

**Comment by mattjanssen** [comment]
@Eonasdan Pretty Please bump the NPM version to 4.17.37! Thanks 😺

**Comment by btecu** [comment]
This can be closed.
