### ISSUE TITLE
Chasing time past midnight also changes date

### ISSUE THREAD

**Issue by craig-winaust** [Eonasdan/bootstrap-datetimepicker#1523]
_Changing, not chasing_

Wondering if this is the intended behaviour and if there is any setting to stop this from happening.

Use case: Select a date, click the select time icon, advance or decrease the hours past midnight and the date changes. 

From a usability point of view, I have already selected the date, changing the time should not change the date. Users of my app might not notice the date change while changing the time. 

I've also noticed that on the time picker the calendar icon hover tooltip says "select time" when it should probably say "select date", as it takes you back to the date picker.

**Comment by mdgiles** [comment]
I have exactly the same question and requirement to stop the time from changing the date when it goes past midnight.

**Comment by William-H-M** [comment]
Hi, this is a intended behaviour as it's basically how most of things like alarms, clocks and other works.

> if there is any setting to stop this from happening

No, there's not such option to stop doing it, and this should the expected behaviour for most of people after all a clock after past 00:00 goes to the next day not repeat again.

What you could do is check with `dp.change` if time is over midnight and set again original date

**Comment by craig-winaust** [comment]
> Hi, this is a intended behaviour as it's basically how most of things like alarms, clocks and other works.

Google, Apple, Microsoft all disagree with you. It's not how computers, tablets and phones work. Which are the devices that people will be using the datetimepicker on.

When setting the time on an Android device, it doesn't do it, iOS doesn't do it, macOS doesn't do it, Windows doesn't do it, every digital watch, digital alarm clock, vcr, pvr, lawn watering controller I've ever owned didn't do it.

In my experience every device (except analogue watches that use gears) allow you to set the time and date independently, with one change not affecting the other.

Thanks for the tip about `dp.change` I'll see if I can fix my UX with that.

**Comment by William-H-M** [comment]
Ok, so this is basically taking as close as a solution has been given, good luck :).
