### ISSUE TITLE
Cannot disable time for start-time and end-time pickers, that has already past

### ISSUE THREAD

**Issue by PaulSh84** [Eonasdan/bootstrap-datetimepicker#1524]
When you click on the time picker, current time is selected. With the arrows i am still able to choose time that is already over. Do i miss something?
Thank you.

**Comment by nikbas** [comment]
You should set `minDate` option to current time.
`minDate: moment()` will disable selecting times in the past.

[minDate](https://eonasdan.github.io/bootstrap-datetimepicker/Options/#mindate)

**Comment by PaulSh84** [comment]
Yeah, i tried it before, it did not work.Check my reported issue [here](https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1008). Moreover it is not correct to use Date properties for time-picker as per the words of the author of this awesome app.
