### ISSUE TITLE
End-time picker cannot be set to choose current time + 15 min

### ISSUE THREAD

**Issue by PaulSh84** [Eonasdan/bootstrap-datetimepicker#1525]
When you click on the end-time picker, you get the current time. Is there a possibility to set it up to show e.g. current time + 15min(my stepping) right away?

**Comment by marknl** [comment]
Set the date using moment.
```js
$('#dtp').datetimepicker().on('dp.show', function() {
  $('#dtp').data('DateTimePicker').date(moment().add(15, 'minutes'));
});```

**Comment by PaulSh84** [comment]
It works! 
Thank you, Mark!
