### ISSUE TITLE
Uncaught TypeError: locale pt-br is not loaded from moment locales!

### ISSUE THREAD

**Issue by ianzitow** [Eonasdan/bootstrap-datetimepicker#1530]
Hey guys, I'm using Browserify with the following code:

`var datetimepicker = require('eonasdan-bootstrap-datetimepicker');`
`window.$ = window.jQuery = require('jquery');`
`var moment = require('moment');`
`require('moment/locale/pt-br');`
`window.moment = moment;`

However, I'm facing this issue: 

> Uncaught TypeError: locale pt-br is not loaded from moment locales!

This occurs when I set locale:

`$('#datetimepicker').datetimepicker({
        locale: 'pt-br'
    });`

What should I do to fix that?

**Comment by melanke** [comment]
I am doing exactly like you.
- I could not make it work with browserify, because it doesn't include `module.exports` in front of the factory, there is an issue for this already.
- After I download the code and modify it then it works perfectly with moment locale (pt-br, I am brazillian too)

**Comment by unamix** [comment]
Same problem.. How to fix this?

**Comment by vargvinter** [comment]
Same problem and question. How to fix this S***? @melanke - where did you put `module.exports`? I need 'pl' locales.

**Comment by William-H-M** [comment]
You need to include moment-with-locale.js
http://momentjs.com/downloads/moment-with-locales.min.js
