### ISSUE TITLE
can't get current time(ver.4.17.37)

### ISSUE THREAD

**Issue by meteor9000** [Eonasdan/bootstrap-datetimepicker#1531]
when I use ver.4.17.37, I can't get the current time.
ver.4.15.35 is ok

**Comment by Xkeywee** [comment]
I found by changing the following

<code>
                if (d === undefined || d === null) {
                    if (tzEnabled) {
                        returnMoment = moment().tz(options.timeZone).startOf('d');
                    } else {
                        returnMoment = moment().startOf('d');
                    }
</code>

in getMoment function to
(line 146)
<code>
                if (d === undefined || d === null) {
                    if (tzEnabled) {
                        returnMoment = moment().tz(options.timeZone);
                    } else {
                        returnMoment = moment();
                    }
</code>

Fixed the time issue.

**Comment by timur-orudzhov** [comment]
I've encountered with the same bug.
