### ISSUE TITLE
In NPM, jQuery is a dependency, not a peer dependency

### ISSUE THREAD

**Issue by adam1658** [Eonasdan/bootstrap-datetimepicker#1533]
Can cause duplication (with different versions of jQuery) in browserify if bootstrap-datetimepicker is using it's own version of jQuery than the rest of a project.
Also, the plugin will be put on this package's own version of jQuery, rather than the main one used in the project - making it inaccessible.
https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by melanke** [comment]
+1

**Comment by dmr** [comment]
It's just a few lines to fix and would really help my development process if jquery and moment would be peerDependencies.

Is this project still alive?

**Comment by siyomai** [comment]
This fixes many bugs, such as using bootstrap-datepicker with brunch, webpack, and browserify.

**Comment by EstherAF** [comment]
That pull request is not going to be accepted (I gess...), cause it's to `master` branch instead of `development`, as the [contrib notes asks](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/CONTRIBUTING.md#very-important-notes)
