### ISSUE TITLE
Locale numerals in widget calendar

### ISSUE THREAD

**Issue by ehabzaky** [Eonasdan/bootstrap-datetimepicker#1534]
Hello,

Thank you very much for this tool.

I am using the tool with Arabic locale. The Arabic numerals appears in the text box perfectly when I choose a date. However the widget calendar when pop ups, it shows the Latin Numerals. Is there any option or a way to change the widget calendar to display numerals in locale digits like the Text Box?

Regards,
Ehab

**Comment by Eonasdan** [comment]
nope sorry
