### ISSUE TITLE
Why are change events caught so aggressively?

### ISSUE THREAD

**Issue by johannesspohr** [Eonasdan/bootstrap-datetimepicker#1537]
I'm using a generic approach to listen on all inputs for change events to warn the user if there are unsaved changes etc. but this component makes it impossible to trigger such events because it catches them all and immediately stops propagation. I don't see any reason for hiding those events from the parents.
(Yes i know the dp.change event, but my parent form would have to know all kinds of change events that could possibly mean that the use changed something).

**Comment by Eonasdan** [comment]
perhaps a different picker would suit your needs better

**Comment by johannesspohr** [comment]
I mean i love the component, I just wanted to know whether those two lines are really needed. 
```javascript
           change = function (e) {
                var val = $(e.target).val().trim(),
                    parsedDate = val ? parseInputDate(val) : null;
                setValue(parsedDate);
                //e.stopImmediatePropagation();
                //return false;
            },
```
If I remove them, the component works just like before and parent components are now able to capture change events in the common way to.
