### ISSUE TITLE
Format doesn't work

### ISSUE THREAD

**Issue by beruic** [Eonasdan/bootstrap-datetimepicker#1538]
I have tried with settine the format string to both `yyyy-mm-dd hh:ii` and `yyyy-MM-dd HH:mm`, but none of them makes `bootstrap-datetimepicker` understand an ISO date.

Version: 4.17.37

**Comment by SarahITH** [comment]
Hi, 
The problem you have have mentioned can be resolve through following Formats , which is used for bootstrap-datetimepicker v4

```
format: 'YYYY-MM-DD hh:mm ' - will give ** 2016-04-07 09:51**
format: 'MMM DD YYYY' - will give  **Apr 07 2016**
format: 'MMMM DD YYYY' - will give  **April 07 2016**

```

Hope this is helpful for you 
Thank You
