### ISSUE TITLE
Three issues with Arabic locale

### ISSUE THREAD

**Issue by eric79** [Eonasdan/bootstrap-datetimepicker#1541]
In the Arabic locale, the following three issues appear:
1. Though the numbers in the time picker are properly translated, those in the date picker are not.
2. Tooltips are not translated
3. If your browser is set to Arabic (easiest to do in Firefox), the left and right icons on the calendar for selecting the month point in the wrong directions.

See this fiddle:  http://jsfiddle.net/jurt8wn3/

The tooltips and icons can be worked around by setting the correct values for the `tooltips` and `icons` options, but I haven't found a way to correct the numerals in the date picker.

Oh, and I just wanted to say ... thanks for creating this library.  It's absolutely fantastic, this issue notwithstanding.  :smile:

**Comment by joaovarandas** [comment]
> Though the numbers in the time picker are properly translated, those in the date picker are not.
> Tooltips are not translated

This is also true in any language when using the "tooltips" option.
