### ISSUE TITLE
Incorrect tooltip for calendar icon in timepicker

### ISSUE THREAD

**Issue by eric79** [Eonasdan/bootstrap-datetimepicker#1542]
When inside the timepicker, hovering over the calendar icon displays the tooltip `Select Time` instead of `Select Date`.  This can be seen from your base jsfiddle: http://jsfiddle.net/Eonasdan/0Ltv25o8/

**Comment by HamsterCoder** [comment]
Overriding date tooltip in settings doesn't seem to help.

Here we are creating button intitally with selectTime.tooltip 
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L325

The on toggle icon is changed while tooltip is not.

https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L1084

Also in default there is no predefined tooltip for selectDate.

**Comment by kchauhaneworkplaceappscom** [comment]
Can we override date time picker tool-tip in side calendar "Select Time" to "Select Date" on calendar Icon.

**Comment by William-H-M** [comment]
Hi, if someone still looking for this, does the following:

Add the tooltip `selectDate` on the defaults value 'Select Date'
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/5a991bfff0b7a721c73d482d06bcbaf9f1e3fc98/src/js/bootstrap-datetimepicker.js#L2473

Then on the `togglePicker` function replace it with this code:
(The function has been take it from [tempus dominus repo](https://github.com/tempusdominus/bootstrap-3/blob/513fb95f955c8aea1ef2c974e2d3f712886c4d9f/src/js/tempusdominus-bootstrap-3.js#L763 ) that doesn't have this)


https://github.com/Eonasdan/bootstrap-datetimepicker/blob/5a991bfff0b7a721c73d482d06bcbaf9f1e3fc98/src/js/bootstrap-datetimepicker.js#L1100
```
togglePicker: function (e) {
    var $this = $(e.target),
        $link = $this.closest('a'),
        $parent = $this.closest('ul'),
        expanded = $parent.find('.in'),
        closed = $parent.find('.collapse:not(.in)'),
        $span = $this.is('span') ? $this : $this.find('span');
        collapseData;

    if (expanded && expanded.length) {
        collapseData = expanded.data('collapse');
        if (collapseData && collapseData.transitioning) {
            return;
        }
        if (expanded.collapse) { // if collapse plugin is available through bootstrap.js then use it
            expanded.collapse('hide');
            closed.collapse('show');
        } else { // otherwise just toggle in class on the two views
            expanded.removeClass('in');
            closed.addClass('in');
        }

        $span.toggleClass(options.icons.time + ' ' + options.icons.date);
        
        if ($span.hasClass(options.icons.date)) {
            $link.attr('title', options.tooltips.selectDate);
        } else {
            $link.attr('title', options.tooltips.selectTime);
        }
    }

        

        // NOTE: uncomment if toggled state will be restored in show()
        //if (component) {
        //    component.find('span').toggleClass(options.icons.time + ' ' + options.icons.date);
        //}
}
```

And that should be it.
