### ISSUE TITLE
Add one hour to minDate

### ISSUE THREAD

**Issue by nicolaszi** [Eonasdan/bootstrap-datetimepicker#1548]
Hi everyone, 

I use two blocks of time picker and separately a datepicker and  a timepicker. 
So i have 4 values, fromDate and fromHour then toDate and toHour. 

When i modify my fromHour field, right now i set the minDate of toHour to be the value of fromHour
`toHourtimepicker.data("DateTimePicker").minDate(fromHourtimepicker.val());` and format is `format:            'HH:mm',`

But actually i don't want it to be "fromDate" but fromDate + 1 hour. How can i do that ? is that possible directly with the library bootstrap-datetimepicker or i need to use some basic JS ? 

Thanks ! 

cheers

Nicolas Z

**Comment by jakeholland** [comment]
Just use moment.js which is a dependency of bootstrap-datetimepicker. The syntax is `.add(1, 'hours')`

**Comment by nicolaszi** [comment]
Ok, thank you ! i do something and it works but with moment.js it should be realy easier.
