### ISSUE TITLE
datetimepicker not showing using jquery layout ui

### ISSUE THREAD

**Issue by ezekel** [Eonasdan/bootstrap-datetimepicker#1549]
I am using jquery ui layout but unfortunately i cannot make it work properly the datepicker is not showing. here is the [fiddle](https://jsfiddle.net/jemz24/pv35uptc/4/)

Thank you in advance

**Comment by Eonasdan** [comment]
the picker is your fiddle is not my plugin

**Comment by ezekel** [comment]
@Eonasdan ,

why not I get the snippet here [datetimepicker](http://eonasdan.github.io/bootstrap-datetimepicker/)

**Comment by Eonasdan** [comment]
you are loading this js file: https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.3/jquery.datetimepicker.js in your fiddle, which is **not** my plugin.

**Comment by ezekel** [comment]
@Eonasdan ,

sorry my bad I thought that's yours, but In my local I use your correct because I use bower, only in fiddle I get mistake...here I updated my with the correct file [fiddle](https://jsfiddle.net/q9paLrad/1/)

**Comment by ezekel** [comment]
@Eonasdan ,

can you please open this back I updated my fiddle with your own plugin.

Thank you in advance.

**Comment by Eonasdan** [comment]
your issue is that your layout is covering the picker and there's no room for it. You can either play with the css to make it work or  change the [pickers orientation](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#widgetpositioning).

**Comment by ezekel** [comment]
@Eonasdan,

You mean this widgetPositioning ?

Thank you in advance.
