### ISSUE TITLE
The icon is not showing next to the textbox

### ISSUE THREAD

**Issue by MovTeam** [Eonasdan/bootstrap-datetimepicker#1550]
Hello,

I am trying to use the datetimepicker but i cannot achive to show the icon next to the textbox.

The icon appers at the final of the line. 

I am using asp.net MVC. This is my code:

`<div class="form-group">
@Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
 <div class="input-group date">
 <input type="text" class="form-control" />
<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
</div>
</div>
`
Any idea?

Thanks a lot in advance!

Update with this image to see better the problem: http://s27.postimg.org/nqte0qblf/dt1.png

**Comment by benbakle** [comment]
I had this same problem and was annoying.  I assume you are using Visual Studio.  When  VS sets up your page, it gives you some default styles located in your "Site.css".  

/* Set width on the form input elements since they're 100% wide by default */
input,
select,
textarea {
    max-width: 280px;
}

That "max-width" messes with your ability to put your icon next to it.  You'll notice if you shrink your screen to xs, it will probably look correct because the width is less than or equal to the max.

Either remove that styleor change it to a value that works better for you.

**Comment by MovTeam** [comment]
Yes. I am user VS and i have this style in "Site.css"

But if I remove that style the form control fill all the screen... so it is not good for me...

I spent a couple of hours and i did not achieve to put the icon next to the textbox at right side.

It is possible to put it at the left side, but i have another problem, it does not align with the rest of controls....

Image: http://s15.postimg.org/u98366yjf/dt1.png

this is very frustrating

**Comment by benbakle** [comment]
Correct. It will span the width of 100%. But if you put a wrapper around it containing the width of everything, it should only span 100% of your container.

<div class="your-container">
...your stuff as you typed it above
</div>

Site.css
.your-container{ max-width:280px} //Or whatever value looks best

As far as the not lining up. I would "inspect element" and see what the 'left' in that css element is set to.  If I had to guess, I would say it was a negative number. Try overwriting that.

**Comment by benbakle** [comment]
Check out this jsfiddle   

https://jsfiddle.net/benbakle/68oj72n3/2/

**Comment by benbakle** [comment]
I removed some of the extras to make it easier to read.  I hope this helps.
https://jsfiddle.net/benbakle/68oj72n3/4/

**Comment by MovTeam** [comment]
Thanks you benbakle.

I want to cry... I don't understand anything... Now the icon is next to the textbox but... the label is not aligned... :(

Image: http://s8.postimg.org/s671c2red/dt1.png

**Comment by benbakle** [comment]
LOL... I know the feeling. We have all spent hours on something just to get it to look right or even work.  Do you understand bootstrap and how to implement the 12-coll?  You are going to want to have the entire form in your container so all inputs respond the same way.  Can you show code the entire div with the form in it? There is something off for sure.

**Comment by benbakle** [comment]
Wait... I see what you did. Put your container around the entire form.  It will contain everything equally

&lt;div class="your-container">
   &lt; div class="form-group">
     ...labelfor description
     ...editorfor description
     ...validationMessageFor description
   &lt;/div>
    &lt; div class="form-group">
      ...labelfor dateTime
     ... etc...
   &lt;/div>
&lt;/div>  
     
You are running into css problems.  Less to do with the actual dateTimePicker.  But I'm fine helping you out. I know the frustration too well.

**Comment by Eonasdan** [comment]
Please move this to SO as this is not a bug with the picker

**Comment by Eonasdan** [comment]
and thank you @benbakle for helping him out
