### ISSUE TITLE
Trying to set default date

### ISSUE THREAD

**Issue by wfabian** [Eonasdan/bootstrap-datetimepicker#1551]
Hi,
I'm trying to set the my default value, with a value from my database.

I parse it into a momentjs-object. My console.log-output of my parsed date is:

`Moment {_isAMomentObject: true, _i: "2016-04-27T05:02:00+0200", _f: "YYYY-MM-DDTHH:mm:ssZ", _tzm: 120, _isUTC: false…}`

But my default value is not set.
I've a list with three entries. I open a bootstrap modal to edit the entry.
On opening the modal the date is loaded from database and set to the input-field.

```
                    $('#date-datetimepicker').datetimepicker({
                        locale: 'de',
                        defaultDate: moment(data.date)
                    });
```

But the given entry is always on 2016-04-03. It's the third entry in list.
My second entry always is 2016-04-02.
My first entry always is 2016-04-01.

Does anyone knows this issue?
Can anyone help? Would be awesome!

**Comment by highfield** [comment]
Fabian, this widget is very nice, but at bit awkward to work with.
This works for me (I choose to store the date/time as an ISO8601 string).
Set date:
`$("#crop-tsk-sched").data("DateTimePicker").defaultDate(moment(scheduled));`

Get date:
`var scheduled = $("#crop-tsk-sched").data("DateTimePicker").viewDate().toISOString();`

Hope it helps.

**Comment by r3m4k3** [comment]
+1

**Comment by wfabian** [comment]
I used it this way:
` $("#date-datetimepicker").data("DateTimePicker").date(moment(dateVar));`

Worked great for me - Thank's a lot!
