### ISSUE TITLE
pad version redeux

### ISSUE THREAD

**Issue by dougwo** [Eonasdan/bootstrap-datetimepicker#1554]
I have tried repeatedly to add readonly to the text field and then the new option ignoreReadonly:true and when I do, the clicks are not being caught so no dates may be set. Even clicks on the icon. Help!Has Chrome changed since issue #494

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.

Setting this option and all work as it should
```
  ignoreReadonly: true,
  allowInputToggle: true
```
