### ISSUE TITLE
minDate is broken when using also time values in input

### ISSUE THREAD

**Issue by Renkas** [Eonasdan/bootstrap-datetimepicker#1555]
## Usecase:

I want to set minimum datetime that the user can select in the picker. In my case it's equal to current timestamp so I set `minDate = new Date()`
## Problem/example:
- `minDate` is set to 2016-04-09 17:48
- User selects some future date in the picker and modifies the time to be something lower. For example: 2016-04-10 15:00
- Now users wants to click on the todays date in calendar but nothing happens when he does that. There's no feedback that the datetime is before minDate constraint.
- In my usecase I would expect that when user click on the date in calendar then picker would automatically set the datetime to minimum allowed value for that time (if there is such a constraint).
## ...

I'm not sure why did you close the last issue as the problem is/was the same: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1302#issuecomment-207766799
You could have started a new issue from it if you wanted to separate them not just ignore the problem ...

**Comment by quadrifoliumclover** [comment]
@Renkas try to add `else if` statement before line [880](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L880) similar to `isValid`, but date will be actual moment

`} else if (targetMoment.isSame(moment(), 'd')) {`
&nbsp;&nbsp;&nbsp;&nbsp;`date = moment();`
&nbsp;&nbsp;&nbsp;&nbsp; `...`
`}`

**Comment by quadrifoliumclover** [comment]
Excuse me for duplication. Couldn't get a proper codestyle.
So now i've finally got it and made a pull request #1610 to fix this issue.
