### ISSUE TITLE
Standalone manual install not working for me

### ISSUE THREAD

**Issue by comatory** [Eonasdan/bootstrap-datetimepicker#1559]
I'm trying to use this picker without bootstrap CSS framework but I can't get it to work. I followed the instructions here http://eonasdan.github.io/bootstrap-datetimepicker/Installing/#manual.

I'm in rails app so I think I'm including all the files
- bootstrap.js
- bootstrap-datetimepicker.js
- knockout-3.4.0.js
- bootstrap-datetimepicker.css

http://imgur.com/yzXB2Uv

You can see in the screenshot that something is not quite right (the picker window is not floating and is all messed up). When I include the whole bootstrap.css file it works right. So I'm probably missing some CSS part but I don't know which.

**Comment by benbakle** [comment]
Need to include jQuery file as well

**Comment by comatory** [comment]
Yes I'm including jQuery and moment. It looks like styling issue but i have no idea whats up with it. (I tried removing all my css files to see if i have collission but still the same result)

**Comment by benbakle** [comment]
Can you post some code?

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.

**Comment by comatory** [comment]
OK so I think I figured it out. There was one problem I overlooked and it was the glyph fonts, the path wasn't matching so it was causing problems that looked like layout issues.

As for css files I thought I only needed `bootstrap-datetimepicker-standalone.css` but it turns out I also had to include `bootstrap-datetimepicker.css` from the github repo.

The layout still wasn't right as `sideBySide` option didn't really work, after a bit of digging I found out it uses core bootstrap classes like `row` and `col`, so I went to [zirafa/bootstrap-grid-only](https://github.com/zirafa/bootstrap-grid-only) to get just the classes for the grid system.

It all works ok except I can't still display the close button etc.

I'm sorry but the manual installation guide isn't really clear on what you need. Just later I noticed that in the upper section "Minimum requirements" it says it needs bootstrap but in the manual section it doesn't mention it. I just found it a bit confusing. It'd be great to have source files that are completely independent on bootstrap (even though it's supposed to be used with it) with javascript and CSS.

Anyway I don't want to sound ungrateful, this datetimepicker is really one of the best I've used.

**Comment by rknetwork** [comment]
I'm having exactly same problem. bootstrap-datetimepicker can't really work independently of bootstrap css styles. Those bootstrap default styles messed all my styles. I suggest to include separate css files, so bootstrap styles won't conflict with my own styles.
