### ISSUE TITLE
current time always show 00:00

### ISSUE THREAD

**Issue by lee-Peter2** [Eonasdan/bootstrap-datetimepicker#1560]
When I use the newest version, 4.17.37, it always show time with 00:00 (e.g. 04/14/2016 12:00 AM or 00:00).  Then if I tried at http://jsfiddle.net/Eonasdan/0Ltv25o8/, it works normally. It's used 4.14.30.

**Comment by gomo** [comment]
+1

I think the problem is [here](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L150).

**Comment by lfarkas** [comment]
+1 it's a regression and at least would be nice to document!

**Comment by rgargente** [comment]
The current development branch commit doesn't seem to have that issue. I also created a little patch for the currently released version with the issue. You can get it here:
https://github.com/rgargente/bootstrap-datetimepicker

**Comment by lfarkas** [comment]
then it's high time for a new release:-)
