### ISSUE TITLE
Display calendar without weekend cols

### ISSUE THREAD

**Issue by ShakurOo** [Eonasdan/bootstrap-datetimepicker#1561]
Hello,
It is possible to don't build the datetimepicker without the weekend cols in inline mode ? (because I have to manage the width of the schedule).

Thanks

**Comment by Pragatheesh** [comment]
Nice to have feature, when it is required to have the calendar to display only working days. Right now we can disable the weekend but that still takes a lot of space and also have dates which is not required at all.
