### ISSUE TITLE
minDate behaviour via constructor differs from minDate function call

### ISSUE THREAD

**Issue by stuarta0** [Eonasdan/bootstrap-datetimepicker#1567]
Following on from #1302 there is still an inconsistency with the standard behaviour depending on order of operations.

```
<div class="form-group">
  <div class='input-group date' id='checkin-date'>
    <input type='text' class="form-control" placeholder="Check in date" />
    <span class="input-group-addon">
      <i class="fa fa-calendar"></i>
    </span>
  </div>
</div>
...
$('#checkin-date').datetimepicker({ minDate: moment(), useCurrent: false });
```

This shows the input with the placeholder text "Check in date" with the intent that dates prior to today cannot be selected.  Setting minDate via options means you cannot select todays date. **However, if you then call minDate() with the same value, todays date can now be selected.**

```
$('#checkin-date').datetimepicker({ minDate: moment(), useCurrent: false });
$('#checkin-date').data("DateTimePicker").minDate(moment());
```

I'm happy with the behaviour of setting `minDate: moment.startOf('d')` in the options because it makes sense, but the above inconsistency is a problem.

**Comment by iamarsey** [comment]
Using format option breaks the behavior as well - it is impossible to select current date after changing a date once.
`$('#datetimepicker').datetimepicker({
                format: "MM-DD-YYYY",
                minDate : moment()
            });`
[DEMO](https://jsfiddle.net/65vaoqkw/31/)

**Comment by stuarta0** [comment]
@iamarsey this is actually the moment().startOf('d') behaviour.  If you set minDate: moment().startOf('d') your problem will go away.  This is what I do in production, however what I've raised in this issue is that behaviour is varying between initialisation and function call.
