### ISSUE TITLE
Incompatibility between bootstrap-datetimepicker and moment 2.13.0

### ISSUE THREAD

**Issue by maggiepint** [Eonasdan/bootstrap-datetimepicker#1568]
Hi,

I'm from the Moment team. We wanted to let you know that there is an issue where Moments created with versions 2.12 and before cannot be used with 2.13 due to some internal property changes. As a result, errors will occur if moments are taken from this datepicker and passed into a diff function relative to a 2.13 moment.

We are tracking this issue in moment/moment#3124, but I wanted to document it here as well so that it was readily find-able for people who check this repository first. 

Feel free to close this if you don't want it hanging around.

**Comment by gregegan** [comment]
👍

**Comment by kriswebdev** [comment]
Not sure where to put this:

date() accepts javascript Date and pass it to setValue() since v4. However, setValue() only accepts moment(), not Javascript Date. Resulting in silent `dp.error` (it would have been better to console.log it).
