### ISSUE TITLE
how do i set up online time picker with no calendar?

### ISSUE THREAD

**Issue by Davidthecoolsmartguy** [Eonasdan/bootstrap-datetimepicker#1570]
how do i set up online time picker with no calendar? just like the inline style.

**Comment by Eonasdan** [comment]
Please see [the FAQs](http://eonasdan.github.io/bootstrap-datetimepicker/FAQ/#how-do-i-disable-the-date-or-time-element)

**Comment by Davidthecoolsmartguy** [comment]
ty
