### ISSUE TITLE
Using moment-timezone displays incorrect current date marker

### ISSUE THREAD

**Issue by dvlsg** [Eonasdan/bootstrap-datetimepicker#1572]
Using a `moment` date from moment with timezones which has had `#tz(timezone)` applied to it seems to shift the calendar's current date marker back a day, depending on the current time of day. 

The following fiddle reproduces the issue on my machine (at least in Chrome, can do other tests if it is required):
http://jsfiddle.net/g34vg6ok/2/

The screenshot was taken at approximately `2016-04-21T12:13:00-07:00` local time, `2016-04-21T12:13:00-06:00` in the altered timezone, but the datetimepicker calendar displays a current date marker of `2016-04-20` after modifying the date. If I chop out the `$data.date()` call, the calendar displays the correct current date as expected.

![2016-04-21 12_14_02-datetimepicker-fiddle](https://cloud.githubusercontent.com/assets/4721566/14721314/a6b3840e-07ba-11e6-89e9-f4293f0b740c.png)

Is there a different way I should be handling timezones with the calendar, or is this a bug? I also noted that when doing this at approximately 5 PM local time (so right when UTC flips over), the current date marker shifts to the actual current local day, instead of one day back.

**Comment by fasomann** [comment]
I encountered similar problems with moment timezone.

First of all i noticed, that my value attibute on the input field is ignored completely. Later when i want to change the date manually by typing an accepted format in the input field, it resets the input value.

[http://jsbin.com/xinuxuhadu/edit?html,output](url)
