### ISSUE TITLE
Decades view when using minDate, does not allow to go to years view

### ISSUE THREAD

**Issue by Wgil** [Eonasdan/bootstrap-datetimepicker#1573]
Hello,

When using minDate option, decades view does not allow to select the years view of that date, so the user must select the next decade and then go to previous one.

It is a little cumbersome to do that, would be better to clic the actual decade and then see the locked years.

http://jsfiddle.net/0Ltv25o8/2687/

**Comment by Zero3** [comment]
Maybe duplicate of this: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1372
