### ISSUE TITLE
Datetimepicker Bugs on format "ww/YYYY"

### ISSUE THREAD

**Issue by ElliDy** [Eonasdan/bootstrap-datetimepicker#1574]
Hi,

I found two bugs in the datetimepicker, when the format "ww/YYYY" is set.

The first one is, that the datetimepicker only shows years, when I want to select a date:
I fixed it with the following code in the function initFormatting:

`if (isEnabled('d') || isEnabled('w')) {
     minViewModeNumber = 0;
}`

The second one is, that it always jumps two weeks or one week before, when you click on the input field. Furthermore the wrong date is selected.

For now I fixed that with not setting the value, if the calendar shows up. Unfortunately the selected date is still wrong with this fix.

Would be nice, if you can find out, why there is something going wrong.

Best regards
Elli

**Comment by Eonasdan** [comment]
the picker doesn't support selecting weeks. To working around it you could set the the format to include picking the day and simply parse the week out of it.
