### ISSUE TITLE
minDate overrides DefaultDate

### ISSUE THREAD

**Issue by benbhale** [Eonasdan/bootstrap-datetimepicker#1579]
Using an example of  MinDate =  '2016-05-11'  and  DefaultDate = '2016-05-18' ....

I simply cannot make the date go to Default not matter what I try. It is always overridden by minDate

'YYYY-MM-DD' wasn't even my first choice of date format. I wanted 'dd MMM yyyy' but that had the same problem.

As you can see I even try and set the date to the default after creation. Still no luck.

```
$('#DesiredDate').datetimepicker({
            minDate: '@ViewBag.MinDate',
            defaultDate: '@ViewBag.DefaultDate',
            maxDate: '@ViewBag.MaxDate',
            format: 'YYYY-MM-DD',
            showClose: false,
            showClear: false,
            toolbarPlacement: 'top'
        });
$('#DesiredDate').datetimepicker('date','@ViewBag.DefaultDate');
```

**Comment by benbhale** [comment]
p.s. if I drop minDate from the definition, then the defaultDate gets picked up. So it's definitely a comparison issue.

**Comment by r3m4k3** [comment]
+1 the same here

**Comment by r3m4k3** [comment]
@benbhale  check setting: useCurrent: false
For me it's working pretty cool.
Let me know.

**Comment by PaRoxUs** [comment]
I noticed that the defaultDate got picked up the second time the DateTimePicker is shown, so I sloved the bug with calling 
`$el.datetimepicker('show');  $el.datetimepicker('hide'); `

**Comment by ahaurat** [comment]
As @r3m4k3 mentioned, I was able to workaround this issue by explicitly setting the useCurrent option to false e.g.

```javascript
$( '#DesiredDate' ).datetimepicker({
    useCurrent: false,
    defaultDate: moment({hour: 19}).add(1, 'day'),
    minDate: moment()
});
```
