### ISSUE TITLE
Customize no option

### ISSUE THREAD

**Issue by Mayur23491** [Eonasdan/bootstrap-datetimepicker#1589]
Please provide demo for customize the datepicker like
decide on which date datepicker should start start week of the datepicker and etc etc etc.

Thanks and regards,
Mahavirsinh Padhiyar

**Comment by Eonasdan** [comment]
I guess you could try reading the docs or looking through the many many [issues](https://github.com/Eonasdan/bootstrap-datetimepicker/issues?utf8=%E2%9C%93&q=is%3Aissue+start+day+of+week+), or even the [FAQ](http://eonasdan.gith aub.io/bootstrap-datetimepicker/FAQ/) about setting the start of the week
