### ISSUE TITLE
Not selecting current time when the today button is hit?

### ISSUE THREAD

**Issue by matthewmalone** [Eonasdan/bootstrap-datetimepicker#1598]
Not selecting current time when the today button is hit?

Using the latest version of moment...

http://jsfiddle.net/9osk7w2j/

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <div class="input-group date" id="datetimepicker1">
                <input type="text" placeholder="datetimepicker" class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon-calendar glyphicon"></span>
                </span>
            </div>
        </div>
    </div>
</div>

$('#datetimepicker1').datetimepicker({
    format: 'YYYY-MM-DD HH:mm',
    locale: 'en-au',
    showTodayButton: true,
});

**Comment by MB34** [comment]
I agree. Is there a way to set it to the Current Time?

**Comment by tslatt** [comment]
I also need to get the actual time rather than 12:00:00 AM when clicking today. Anyone?

**Comment by thebarless** [comment]
@tslatt, it looks like this was tagged as a bug in #1311 with possible fixes there. I ended up reverting to 4.15 until a solution is developed.

**Comment by MB34** [comment]
If you look at my comment above, it will set the current date and current time. 
This sets the format and then sets to current date and current time:
`$('#examtime').datetimepicker({
        showClear: true,
        format: 'LT',
        toolbarPlacement: 'bottom',
        showTodayButton: true,
        useCurrent: true
    });
    $('#examdate').datetimepicker({
        format: 'MM/DD/YYYY',
        viewMode: 'days',
        showTodayButton: true,
        showClear: true,
        minDate: new Date(new Date().getFullYear(), 0, 1)
    });
    $('#examdate').data("DateTimePicker").date(new Date());
    $('#examtime').data("DateTimePicker").date(new Date());`

**Comment by William-H-M** [comment]
@VedaRamaiah I couldn't reproduce what you're saying
Using the most recent version of the plugin and using moment tz
https://jsfiddle.net/William_/20oywuno/298/

**Comment by VedaRamaiah** [comment]
My code got messed up with moment-timezone and moment-timezone-with-data and was causing the issue. Its been resolved now, but I do have another question. 
Styling of decades appears to be not right, How do we style it to look better? I tried looking into it but couldn't get to work.

![picker-decades](https://user-images.githubusercontent.com/46539324/64883635-d7913180-d62d-11e9-9cc2-482f9f78a535.png)

**Comment by William-H-M** [comment]
That seems to be Bootstrap 4 right? Check if your CSS is not doing something weird

**Comment by VedaRamaiah** [comment]
I am using Tailwind instead of Bootstrap in my project , Do you remember what needs to be changed in order to achieve it?

**Comment by William-H-M** [comment]
You will have to adapt all the styles of this project for it, as this only supports Bootstrap 3
