### ISSUE TITLE
DD/MM/YYYY format is  not working when we use minDate and MaxDate

### ISSUE THREAD

**Issue by JalandharP** [Eonasdan/bootstrap-datetimepicker#1600]
Hello,
First let me thank you for this great project. I'm currently facing the following problem, i am setting date format is DD/MM/YYY with minDate and maxDate specified. I am facing problem like, its always taking MM/DD/YYYY format instead of DD/MM/YYYY. 
I have created jsfiddle. Please refer the following URL.
URL: http://jsfiddle.net/Jalandharp/mw61971w/1/
Please can you help me how to get dates with DD/MM/YYYY format if we are specifying minDate and maxDate.

**Comment by jsvini** [comment]
When I use the format DD/MM/YYYY it doesn't accept default value
