### ISSUE TITLE
en/disabledTimeIntervals

### ISSUE THREAD

**Issue by arturojain** [Eonasdan/bootstrap-datetimepicker#1602]
As of #644 we can disable time intervals using `disabledTimeIntervals`, as in any other _option_ making `enabledTimeIntervals` available would also be useful; e.g. times between **May 10 at 1:00PM** and **May 11 at 2:00PM** should only be enabled.

Or is there a built-in way to do this?

**Comment by bermann** [comment]
I also would like this

**Comment by blackrainb0w** [comment]
I would love too !

**Comment by jramiresbrito** [comment]
Please! I need it.
How you guys are currently dealing with this?
