### ISSUE TITLE
Date's time is always 00:00 unless it previously had a value

### ISSUE THREAD

**Issue by alyons9** [Eonasdan/bootstrap-datetimepicker#1604]
When I press the calendar icon to show the datetimepicker and the input was currently an empty value the time is always 00:00...Looking through the code I believe it is because the private method getMoment always returns the date without the time when the argument value is null or undefined. 
To see the issue the command used in the method is: 

moment().startOf('d') 

This moment will always returns the start of the day which is the date with the time as 00:00. This also breaks the currDate granularity functionality because the time will always be 00:00 regardless if you choose hour or minute as the granularity option.

**Comment by gingray** [comment]
have the same issue as @alyons9 but solve it using this coffee code
```coffeescript
  dt_picker_start.datetimepicker
    format : 'DD/MM/YYYY HH:mm'
    defaultDate: moment().utc()

```
