### ISSUE TITLE
Side by side picker with am/pm and seconds displayed layout issue

### ISSUE THREAD

**Issue by gwynjudd** [Eonasdan/bootstrap-datetimepicker#1611]
See this fiddle for replication:

http://jsfiddle.net/fq3Lczc8/

The AM/PM overflows to the right:

![image](https://cloud.githubusercontent.com/assets/314188/15232099/14edec36-18f3-11e6-9270-5986729d7475.png)

Seems pretty simple to fix, if I'm right I'll attach a PR shortly

**Comment by nkovacs** [comment]
This only works in dropdown mode, not inline mode.
