### ISSUE TITLE
date() vs setValue() type

### ISSUE THREAD

**Issue by kriswebdev** [Eonasdan/bootstrap-datetimepicker#1616]
In development branch:

Since v4, `setValue()` is used and only accepts `moment`.

However, `date()` (that uses `setValue()`) accepts a bunch of inputs:

```
            if (newDate !== null && typeof newDate !== 'string' && !moment.isMoment(newDate) && !(newDate instanceof Date)) {
                throw new TypeError('date() parameter must be one of [null, string, moment or Date]');
            }
```

Using a Javascript Date results in no precondition error in `date()`  but is silently ignored by `setValue()` (a `dp.error` is thrown, but no console log).

A decision has to be made: Either Javascript Dates should be accepted, or a precondition error should be thrown by `date()`.

Note that not accepting Javascript Dates breaks compatibility.

**Comment by rockResolve** [comment]
Same issue in development. This is triggered by the "4.17.42 " commit on 15 Sep 2015, which standardised moment.
The change makes parseInputDate call getMoment which creates moment with parseFormats. The presence of the format parameter makes moment treat it as a string (before checking for a date type).

**Comment by rockResolve** [comment]
In addition to date(), both defaultDate() & viewDate() are documented (and have validation) as accepting a Date parameter, but do not.
