### ISSUE TITLE
When I choose a datetime,can datetimepicker automatically close？

### ISSUE THREAD

**Issue by HouserWang** [Eonasdan/bootstrap-datetimepicker#1619]
When I choose a datetime,can datetimepicker automatically close？
What should I do?

**Comment by Eonasdan** [comment]
no it can't.

**Comment by ShavidzeT** [comment]
@Eonasdan are you kidding us? there is no option to close picker after selecting data?

**Comment by Eonasdan** [comment]
As it has been mentioned on many many issues before... YOU can listen for the change event and close it yourself.
