### ISSUE TITLE
How to set MinDate at runtime

### ISSUE THREAD

**Issue by MhAllan** [Eonasdan/bootstrap-datetimepicker#1622]
How can I update options like MinDate dynamically? if not possible please suggest me good datetimepicker that is responsive and have typescript interface.

**Comment by neerajkumarnj** [comment]
I also would like to know that, please resolve this.

**Comment by deyvid5** [comment]
Well, you can easily override method dp.update, dp.show oraz dp.change.
dp.show occurs when u click on the icon which is opening the whole plugin. The other ones occurs, after closing it.

Read docs. It's all there.

U can set minDate options, by doing sth like that.

` $('#datetimepicker').on("dp.change", function (e) {
                $(this).data("DateTimePicker").minDate(e.date);
     });`

**Comment by MhAlan** [comment]
thanks
