### ISSUE TITLE
Cant select tomorrow if minDate is tomorrow

### ISSUE THREAD

**Issue by codev0** [Eonasdan/bootstrap-datetimepicker#1627]
Hi.

In my case I need to select only tomorrow or next dates.

```
var tomorrow = moment().add(1, 'days');

$('#datetimepicker').datetimepicker({
    minDate: tomorrow,
    ignoreReadonly: true,
    format: 'DD/MM/YYYY',
    allowInputToggle: true,
    defaultDate: tomorrow,
    useCurrent: false
});
```

But I cant choose tomorrow date.
http://jsfiddle.net/jjufgejc/1/

**Comment by soifou** [comment]
Yep it seems like a bug, however you can get this behaviour if you change minDate at today like this:
```
var tomorrow = moment().add(1, 'days');

$('#datetimepicker').datetimepicker({
        minDate: moment(),
        ignoreReadonly: true,
        format: 'DD/MM/YYYY',
        allowInputToggle: true,
        defaultDate: tomorrow,
        useCurrent: false
});
```

**Comment by emmgfx** [comment]
Check this answer: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1567#issuecomment-213200598

**Comment by William-H-M** [comment]
If anybody just happen to get this just do
 `moment().startOf('day')`
and the if you want add x days
