### ISSUE TITLE
ViewMode Issue

### ISSUE THREAD

**Issue by johnny2649** [Eonasdan/bootstrap-datetimepicker#1633]
When the minDate was set to last year's today and the maxDate was set to next year's today, e.g. Rnage: 30/5/2015 - 30/5/2017, the decade view mode cannot select any range

**Comment by lesilent** [comment]
I've managed to work around the issue by disabling the decade selection using the following css:

```
.bootstrap-datetimepicker-widget .datepicker-years thead .picker-switch {
     cursor: default;
     pointer-events: none;
}

```
