### ISSUE TITLE
minDate honored, but the "not available" cursor does not display

### ISSUE THREAD

**Issue by blackf0rk** [Eonasdan/bootstrap-datetimepicker#1638]
# The Issue

```
$('#datetimepicker1').datetimepicker({
    viewMode: 'days',
    minDate: moment(),
    maxDate: moment().add(7, 'days'),
    useCurrent: false,
    format: 'MM/DD/YYYY'
});
```

This produces a calendar in which today's date appears to be select-able (i.e. the cursor is the default cursor and not the "not available" cursor), but when selecting today's date, the picker closes and no date is used.

This happens because `useCurrent` is set to `false` and the 'format' is set to one in which the time is not displayed. However, the current time is still being set, observed and acted upon.

Technically, the rest of the today is greater than `moment()` but since the time isn't displayed or able to be changed, then the time shouldn't be included in the check for `minDate`.
# Work-around

The Datetimepicker appears to know when or when not to show the time picker based on the format, so this issue has the possibility of being resolved?

In the meantime, this fiddle demonstrates the issue and the work-around I have implemented: http://jsfiddle.net/bLtsnrk7/2/

Specifically, we create a new `moment()` and `.format()` it to set the time to `00:00:00` today. Then we pass that into a new `moment()`. Finally we `.add()` 1 day to make the correct `minDate` tomorrow at `00:00:00`.

```
$('#datetimepicker3').datetimepicker({
    viewMode: 'days',
    minDate: moment(moment().format('MM/D/YY')).add(1,'days'),
    maxDate: moment().add(7, 'days'),
    useCurrent: false,
    format: 'MM/DD/YYYY'
});
```

I should note that I am adding 1 day here because I specifically, in my particular project, do not want today to be chosen.

**Comment by emmgfx** [comment]
Check this answer: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1567#issuecomment-213200598

**Comment by William-H-M** [comment]
#1627
