### ISSUE TITLE
Time widget reset hour on focus

### ISSUE THREAD

**Issue by dutchiexl** [Eonasdan/bootstrap-datetimepicker#1642]
Using the setup posted below, whenever I focus the input field, the hour is set to 6 PM. If I change the time and click on the input again, the hour is also reset

```
    $('.time-field input').datetimepicker({
        format: 'HH:mm',
        defaultDate: moment().hours(08).minutes(30),
    });
```

**Comment by jreidal** [comment]
I'm seeing the exact same problem. Only mine resets to 3 AM.

` 
$(timeBegin).datetimepicker({
    format: 'LT',
    defaultDate: moment().hour(9)
});
`

**Comment by jreidal** [comment]
Oh, it seems that I fixed it by specifying the timezone, such as `moment().tz('America/Los_Angeles').hour(9)`.

**Comment by patricktoerner** [comment]
Anyone find the solution to this? Mine resets to 3am on click

**Comment by patricktoerner** [comment]
Adding the option `timeZone: null,` get rid of the issue.
