### ISSUE TITLE
Characters inside square brackets in 'format' option should be ignored

### ISSUE THREAD

**Issue by aprevost** [Eonasdan/bootstrap-datetimepicker#1645]
Btw, love your package... just found this one little bug/missing feature in it just now. :-)

Given that your package uses the value of the 'format' option to determine whether or not to display the time picker (or the date picker), and is supposed to use the moment.js package format string rules for this, as per: http://eonasdan.github.io/bootstrap-datetimepicker/Options/#format

And given that there's no other way of explicitly specifying that you want the time picker and/or date picker to be displayed or not to be displayed...

It seems to me, this package's logic for deciding whether or not to display the time picker based on the format string should take in to account the fact that according to the moment.js formatting documentation, any character inside square brackets should be considered be escaped. (See the "Escaping characters" section under: http://momentjs.com/docs/#/displaying/format/)

Unfortunately, that doesn't appear to be the case currently. When I pass the datetimepicker a format value of 'ddd, MMM D [@ 12:45pm]', the datetimepicker is displaying the time picker. I'm guessing probably because of the character 'm' appearing in 'pm'. 

Since you use Moment.js under the hood for the actual formatting, and it properly escapes the characters inside square brackets, the value is being displayed as I want it to be everywhere. However... I do NOT want the time picker to be displayed, and it is.

Why is this useful? Because I want my users to be able to pick the date on which my application should execute a specific task, but the exact time that task is executed every day is constant, and cannot be changed. It is important that my users know and be very aware of the exact time the task will be executed on the day they select, which is why I want the date picker to include the time everywhere it displays the selected date. But they cannot change that time, so I do not want the time picker to show up.

**Comment by egucciar** [comment]
Is there a fix for this?
