### ISSUE TITLE
Submit to grab both Linked Picker dates and update mongo collections.

### ISSUE THREAD

**Issue by scheung38** [Eonasdan/bootstrap-datetimepicker#1649]
How to add submit button, that when clicked, grabs the Linked Picker example and insert into my MeteorJS Collection with db.collection.insert({ .... })

thanks

**Comment by Eonasdan** [comment]
I'd suggest reading [reading the docs](http://eonasdan.github.io/bootstrap-datetimepicker/) or asking on StackOverflow
