### ISSUE TITLE
Angular binding

### ISSUE THREAD

**Issue by nkamenar** [Eonasdan/bootstrap-datetimepicker#1651]
Could anyone give me a hand with binding the angular directive to my data? I have a json array where [...,{DueDate: "2012-09-28T00:00:00.000Z"},...]. When I try to bind ng-model="currentItem.DueDate" the field is empty when I open the form. Is there a certain datatype or format I need to be using here?

**Comment by jnm2** [comment]
I'd recommend using this particular angular module: https://github.com/atais/angular-eonasdan-datetimepicker
