### ISSUE TITLE
Time picker display issue when formatting with seconds

### ISSUE THREAD

**Issue by kyrozetera** [Eonasdan/bootstrap-datetimepicker#1655]
When using a format like `HH:mm:ss A`, it becomes a bit too long for the time picker and overflows the widget.

Example: http://jsfiddle.net/2rxr0L95/

**Comment by rip747** [comment]
You can use this to override

.bootstrap-datetimepicker-widget.dropdown-menu {
  min-width:19em;
  width:auto !important;
}

**Comment by kyrozetera** [comment]
Interesting, that works in the fiddle, but not in my environment. I must have some styles that are interfering with the sizing of some of the elements.
