### ISSUE TITLE
Not working with JQuery 3

### ISSUE THREAD

**Issue by ismeleo** [Eonasdan/bootstrap-datetimepicker#1657]
Not working with JQuery 3

**Comment by freemer** [comment]
The size() function seems to have been removed in JQuery 3.0.0, so the datetimepicker fails upon instantiation

**Comment by ismeleo** [comment]
Seems only changing the "size()" to "length" still not enough, there is no calendar popup after clicking the small calendar icon.

It seems the "widget.show()" at around line 1213 not adding "display:block" to the "widget" so I have to change it to "widget.css('display', 'block')" to workaround it.

`if (component && component.hasClass('btn')) {`
`component.toggleClass('active');`
`}`
`//widget.show();`
**`widget.css('display', 'block'); // at line around 1214`**
`place();`

**Comment by kikonen** [comment]
patch seemed to work for me
