### ISSUE TITLE
Not able to Hide datepicker.

### ISSUE THREAD

**Issue by manish12jes** [Eonasdan/bootstrap-datetimepicker#1663]
I want to use timepicker only.but even after using {format":"LT"} not able to hide date form datetimepicker.
I  am using below code
$(".datetimepickerop").datetimepicker({format: 'LT',pick12HourFormat: true });

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.
