### ISSUE TITLE
Time reseting to 00:00 with " HH:mm a" format

### ISSUE THREAD

**Issue by Zajkra** [Eonasdan/bootstrap-datetimepicker#1665]
using asp.net mvc : this is _timePicker.cshtml view

@model Fumi.Web.Models.UserControls.DateTimePickerModel
@using Fumi.Web.Helpers
    <div class='input-group date'>
        <input type='text' class="form-control" id="@Model.ID" name="@Model.ID" value="@Model.Value" />
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
    </div>

<script type="text/javascript">
    $('#@Model.ID').parent().datetimepicker({ format: "HH:mm a" })
           
</script>

if i do this : 

datetimepicker({ format: "HH:mm a" }) , it shows wrong time

if i do this:
datetimepicker({ format: " HH:mm a" })  (added an space) , it shows correct time.

but when clicking to change the time , it resets the field to 00:00

Any idea of why could this be happening? why also that space could affect the result?

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.
