### ISSUE TITLE
DateTimePicker Hour Round Up Issue with Stepping

### ISSUE THREAD

**Issue by lizardpie** [Eonasdan/bootstrap-datetimepicker#1666]
When using the "stepping" property on the DateTimePicker and initializing the control to a time that approaches the top of the hour, the minutes are rounded to "00" but the hour does not increment.

For example, with stepping set to 15, the control rounds minutes to 00, 15, 30 or 45.  If the control is initialized with "06/17/2016 08:53" one would expect that it would round up to "06/17/2016 09:00", but it instead is set to "06/17/2016 08:00".

Please refer to the following JSFiddle: http://jsfiddle.net/lizardpie/snfo41jq/4/

**Comment by tomosap** [comment]
I've also noticed this, is there a resolution for it yet?

**Comment by lizardpie** [comment]
This has not been fixed yet.  I customized my local version in the meantime.  The change must be made to the **setValue** function. I made the following mods:

             
```
                if (options.stepping !== 1) {
                    var roundedMins = Math.round(targetMoment.minutes() / options.stepping) * options.stepping;
                    targetMoment.minutes((roundedMins) % 60).seconds(0);
                    //targetMoment.minutes((Math.round(targetMoment.minutes() / options.stepping) * options.stepping) % 60).seconds(0);

                    // Are we rounding up to the next hour?
                    if (roundedMins >= 60) {
                        targetMoment.add(1, "hours");
                    }
                }
```
