### ISSUE TITLE
Date Time Picker not working in IE 11.

### ISSUE THREAD

**Issue by sabique** [Eonasdan/bootstrap-datetimepicker#1669]
Date time picker is not working in Internet Explorer 11. However it is working fine in Mozilla and Chrome. I'm using jQuery v 1.12.4 and implemented my script in a ASPX web form.

**Comment by lopezdp** [comment]
How did you implement your script? Did you embed an element in a function using back ticks? Please let me know. I have a similar issue and I am trying to resolve it.

**Comment by William-H-M** [comment]
Hi, @lopezdp what error are you getting becasue I just tested it out on IE11 and currently no problem, this on a W10 (no, no the internal mode of EDGE)

and it's working for me in this [fiddle](https://jsfiddle.net/William_/20oywuno/)

![imagen](https://user-images.githubusercontent.com/24443241/28687861-8ab57d66-72d5-11e7-9617-bd746423987e.png)

**Comment by lopezdp** [comment]
I have it working now. Apparently IE v.11 has no support for ES6 and I was using back ticks to embed HTML in my JavaScript... 

I went back and removed the back ticks, added double quotes, concatenated every line and added forward slashes to the quotes that define my css classes (\")...

It's beautiful. Thanks!

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.

**Comment by donv** [comment]
Old issue, but for me this was solved by including the `Object.assign` polyfill:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill
