### ISSUE TITLE
editable input

### ISSUE THREAD

**Issue by jamir0** [Eonasdan/bootstrap-datetimepicker#1676]
Hello,
is it possible somehow to configure picket to allow manually edit input field (if calendar is not visible, for example)? 

if no, will be great to have the such functionality in v5:
- allow manually edit input
- allow to define mask for field by format or somehow(if "dd.mm.YYYY" should be "__ .__  .____",  "dd/mm/YYYY" -> "__ / __ / ____". Underscore or space - it doesn't matter)
- fix navigation by arrows (left, right) in input field, now it start to present date in UTC format and ignore format option in config. (tested on format "YYYY" with related view mode. and navigation by left/right switches date to default format.)

Thanks in advance.

ps. really cool component, thank you.

**Comment by razorcd** [comment]
This would be very very useful in V5.

It kind of works now if you do:
- select the input
- press down
- press enter
- select input again
- you can manually edit the datetime text
