### ISSUE TITLE
Not working on jquery 3

### ISSUE THREAD

**Issue by scgm11** [Eonasdan/bootstrap-datetimepicker#1684]
jquery.js:2 jQuery.Deferred exception: input.size is not a function TypeError: input.size is not a function
    at dateTimePicker (https://192.168.99.247/sv/uContact/assets/js/vendor/bootstrap/bootstrap-datetimepicker.js:1604:23)
    at HTMLDivElement.<anonymous> (https://192.168.99.247/sv/uContact/assets/js/vendor/bootstrap/bootstrap-datetimepicker.js:1657:46)
    at Function.each (https://192.168.99.247/sv/uContact/assets/js/vendor/jquery/jquery.js:2:2813)
    at r.each (https://192.168.99.247/sv/uContact/assets/js/vendor/jquery/jquery.js:2:1003)
    at r.$.fn.datetimepicker (https://192.168.99.247/sv/uContact/assets/js/vendor/bootstrap/bootstrap-datetimepicker.js:1652:21)
    at HTMLDocument.<anonymous> (<anonymous>:24:31)
    at j (https://192.168.99.247/sv/uContact/assets/js/vendor/jquery/jquery.js:2:29588)
    at k (https://192.168.99.247/sv/uContact/assets/js/vendor/jquery/jquery.js:2:29902) undefined

**Comment by dleffler** [comment]
Work-around is to also load jquery-migrate-3.0.0.js

**Comment by scgm11** [comment]
still not working

**Comment by Synchro** [comment]
Broken with the same error with jQuery 3.1 and jquery-migrate-1.4.1 as well: (there is no such thing as `jquery-migrate-3.0.0.js`; 1.4.1 is current). It really doesn't like that `size` call:

	migrateWarn (jquery-migrate-1.4.1.js:47)
	size (jquery-migrate-1.4.1.js:377)
	dateTimePicker (g=cj&1464952597:709:165)
	(anonymous function) (g=cj&1464952597:716:241)
	each (jquery-3.1.0.min.js:2:2820)
	each (jquery-3.1.0.min.js:2:1008)
	datetimepicker (g=cj&1464952597:716)
	(anonymous function) (373515:1719)
	j (jquery-3.1.0.min.js:2:29574)
	(anonymous function) (jquery-3.1.0.min.js:2:29884)

**Comment by Synchro** [comment]
Changing the two uses of `.size()` to `.length` prevents the migrate errors, but doesn't make it work. With those fixed it does nothing, no errors or warnings are logged.

**Comment by dleffler** [comment]
FYI, jquery-migrate-3.0.0.js is the correct file restores deprecated features and behaviors/troubleshooting for jquery-3.x.0.js. jquery-migrate-1.4.1.js is the version restores deprecated features and behaviors for jquery v2.x/1/x for much older jquery versions. jquery-migrate v3.0.0 and v1.4.1 are incompatible with each other.
https://code.jquery.com/jquery-3.1.0.min.js
https://code.jquery.com/jquery-migrate-3.0.0.min.js

**Comment by Synchro** [comment]
Apologies, you are correct.

**Comment by scgm11** [comment]
PR #1664 resolve issues the important here apart of the size to length is change  widget.show() to  widget.css('display', 'block');

**Comment by Synchro** [comment]
Thanks @scgm11 - I can confirm that that change makes it all work for me in jQuery 3.1.

**Comment by sofoklis** [comment]
@scgm11 Thanks that does the trick!

**Comment by HannesOberreiter** [comment]
@scgm11  thanks!

**Comment by quansun** [comment]
@dleffler Thanks. The 'adding jquery-migrate-3.0.0.min.js' workaround worked for my project. 

The error I got was: '.... e.size is not a function...'

Here are what I did:

Tried to use the 'widget.css('display', 'block');' trick, didn't work.
Added jquery-migrate-3.0.0.min.js, then worked

Thanks

**Comment by KayTokyo** [comment]
I added jquery migrate and it fixed the size issue in console but when i try click the calendar button, nothing gets displaed.

**Comment by steveyj79** [comment]
yep it's still an issue there is a fix applied here https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1664 but it's failing on the unit test so it hasn't been merged

**Comment by elanclarkson** [comment]
@scgm11 
> PR #1664 resolve issues the important here apart of the size to length is change widget.show() to widget.css('display', 'block');

I believe this issue has been reported here #1765 along with a CSS hack.

**Comment by soulcreate** [comment]
some truble

**Comment by nickel715** [comment]
I think this is fixed in 0202134 
Version 4.17.42 is working for me with jquery 3.1.0
