### ISSUE TITLE
The mindate constraint does not work in decade viewmode

### ISSUE THREAD

**Issue by shanknet** [Eonasdan/bootstrap-datetimepicker#1691]
having a mindate set in e.g 2016 will leave the 2012-2023 disabled.

![2016-07-13_09262](https://cloud.githubusercontent.com/assets/20420084/16795249/908fe7ea-48dc-11e6-8f4b-da15ee3148bd.png)

**Comment by shanknet** [comment]
might be related to #1170

**Comment by avbrowne-web** [comment]
I've created this as a hacky fix using jquery for now.

`

        $('input').on('dp.show', function () {
            $(this).siblings('.bootstrap-datetimepicker-widget')
                   .find('.datepicker-decades span.decade.disabled').each (function () {
                       var range = $(this).text().split(' - ');
                       if (manufactureYear >= range[0] && manufactureYear <= range[1]) {
                           $(this).removeClass('disabled');
                       }
            });
        });

`

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.
