### ISSUE TITLE
How to change date without firing 'dp.change' event?

### ISSUE THREAD

**Issue by winters-song** [Eonasdan/bootstrap-datetimepicker#1700]
I'm using datetimepicker as a mini datepicker on the side of a calendar like Google calendar. 
When I change the date of datetimepicker, the date of the calendar should change. So I use 'dp.change' to make it - Easy work.
 But how can I update datetimepicker when I change the date of the calendar? If I use 'date()', it will change the selected date and fire 'dp.change', which makes it infinite loop.
Can I change month of datetimepicker without changing selected date? (just like I click the next button)

**Comment by osamasheikh28c** [comment]
Any fix you found yet, I'm having the same issue.
Let me know,

Thanks
