### ISSUE TITLE
The option `defaultDate` is not working if `inline=false`

### ISSUE THREAD

**Issue by nhtua** [Eonasdan/bootstrap-datetimepicker#1703]
I want to display a date from DB, so I set defaultDate = "2016-07-20 08:00:00". It's a standard time string. But the picker didn't show date. I looked out the `defaultDate` method and didn't understand the `line: 1764`:
`
             if ((options.defaultDate && options.inline) || input.val().trim() === '') {
`
If I config 'inline:true' then the picker will display default date. But I don't like the inline picker. For temporarily used, I remove `&& options.inline` from the line 1764. Please double-check this line. Why do you have to check inline option just to set input's value?

**Comment by mlms13** [comment]
With `inline` pickers, the `input` var isn't actually an input element (in my case, it's a `div`), so `input.val().trim()` was throwing an error. I assume that's why they added the `options.inline` check, but it looks like it went too far in the other direction.

**Comment by andreich1980** [comment]
@nhtua @mlms13 
Seems the project is dead. Can you recomend any other good date-time-picker?
