### ISSUE TITLE
Input value overwritten by initialization

### ISSUE THREAD

**Issue by NVV-WebManager** [Eonasdan/bootstrap-datetimepicker#1705]
Is it expected behavior that if a value attribute is provided for the input field, it will be ignored and overwritten as null upon the datetimepicker initialization?  I see documentation that allows me to set a defaultDate option during initialization, but I want to be able to provide a date (string format) to the input value instead.  I can't imagine that I'm the only one who expected/wanted that to work, so I am thinking it must be a bug of some sort.

**Comment by jonathan-nye** [comment]
@NVV-WebManager, it will do that if your value doesn't match the expected date format of the datetimepicker.  Try passing the format option into the datetimepicker initializer with the same format as your field's value (i.e. if your value is `10/04/2016` then the format should be `format: 'MM/DD/YYYY'`).  It uses moment.js' date formats (http://momentjs.com/docs/#/displaying/format/).

**Comment by NVV-WebManager** [comment]
Thanks for the suggestion, but I had already read that that could be the cause, and formatting the dates doesn't address the problem.  I have my php output value set to format as ''m/d/Y g:i A' and the datepicker is set to format 'MM/DD/YYYY h:mm A' - that should be exactly the same.  But my value is still getting overwritten as blank once the datepicker is initialized.  Any other ideas?

**Comment by Woolear** [comment]
Hi. I have the same issue in .NET MVC. it's very strange and unexpected behaviour. Date format, used in code, can be different from display format.
