### ISSUE TITLE
Knockout binding did not use format for selected date

### ISSUE THREAD

**Issue by DenisTsapelnikov** [Eonasdan/bootstrap-datetimepicker#1707]
using your custom data bind for knockout js framework i use following data bind:
data-bind="dateTimePicker: EndDate, value: EndDate, dateTimePickerOptions: {format: 'L'}'
When the value loads it's shown correct. But when you select a new data from the picker it will be displayed using default format.

**Comment by koenvanderlinden** [comment]
try this:
`<input type='text' class="form-control" data-date-format="DD-MM-YYYY" data-bind="dateTimePicker: EndDate" />`

All data-* attributes will be used as options fot the DateTimePicker.
