### ISSUE TITLE
AngularJS

### ISSUE THREAD

**Issue by arjamizo** [Eonasdan/bootstrap-datetimepicker#1708]
Hello

can somebody help in in getting `ng-model` working with `bootstrap-datetimepicker`? 

https://codepen.io/xadi/pen/oLybjk

**Comment by werevolff** [comment]
It is not clear how signals work. Developers must either update the documentation, or use a more explicit mechanism for receiving events.

**Comment by werevolff** [comment]
`angular.element('.date-form-group').on('dp.change', function () {
        $log.warn('EVENT CATCHED');
    });`

Here is the answer.

**Comment by arjamizo** [comment]
@werevolff really? do you really think this is the full answer?

**Comment by werevolff** [comment]
Just look on this [directive](https://github.com/diosney/angular-bootstrap-datetimepicker-directive). If you don't want to use it, you must to catch dp.change event into your controller and update your model inside the event handler.

**Comment by arjamizo** [comment]
@werevolff so I am actually looking for a @Eonasdan/bootstrap-datetimepicker patch which will allow me using `ng-model`, I do not want to add any additional code for "manual binding", I could be also using `jQuery` and/or `XMLHttpRequest` for that

**Comment by jnm2** [comment]
I'd recommend using this particular angular module: https://github.com/atais/angular-eonasdan-datetimepicker
