### ISSUE TITLE
using keepInvalid for time picker

### ISSUE THREAD

**Issue by sharifahmed** [Eonasdan/bootstrap-datetimepicker#1711]
Setting the option **keepInvalid** to true will not force the date of the datepicker to the previous date.

However, if I set **keepInvalid** to true for the time picker, it does not work.

Are there any alternative ways I can handle this?

I am using version 4.17.37

**Comment by ColinChen2** [comment]
The time valid in moment.js caused this problem. 
KeepInvalid works. Just add {useStrict: true}.
