### ISSUE TITLE
Not compatible with latest Bootstrap v4

### ISSUE THREAD

**Issue by adamreed90** [Eonasdan/bootstrap-datetimepicker#1713]
With release v4.0.0-alpha.3, this no longer functions, however it was functioning up to this release with v4.

**Comment by ethanclevenger91** [comment]
For me, this was related to missing sass variables on compilation. I added the following before importing it to resolve this:

```

$border-radius-base:$border-radius;
$screen-sm-min:map-get($grid-breakpoints, sm);
$screen-md-min:map-get($grid-breakpoints, md);
$screen-lg-min:map-get($grid-breakpoints, lg);
```

**Comment by William-H-M** [comment]
Hi, you can help contrubuting to https://github.com/tempusdominus/bootstrap-4
