### ISSUE TITLE
setDate method triggers changeDate

### ISSUE THREAD

**Issue by rknetwork** [Eonasdan/bootstrap-datetimepicker#1716]
Whenever I setDate within the changeDate handler, it goes into loop and crashes the browser.
setDate SHOULDN'T trigger changeDate, this is wrong.

Same issue: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/267

```
$('input').on('changeDate', function() {
	$('input').datepicker('setDate', '08/10/2016'); // please don't tell me this is wrong, i can throw some real world examples..
	$('body').append('<br>fire!<br>');
})
```

**Comment by liamhughes** [comment]
Please consider reopening this. I have found various issues logged and closed around this, and it is currently causing me some bother working around it.
