### ISSUE TITLE
if locale doesn't exist, fallback to default locale

### ISSUE THREAD

**Issue by fartymonk** [Eonasdan/bootstrap-datetimepicker#1718]
Hi, is there a way to set fallback language when a locale is not found?

I'm using moment-locale and I tried to set the locale to 'zh' (which I know doesn't exist in moment), and got this stopping error:

`bootstrap-datetimepicker.min.js:8 Uncaught TypeError: locale() locale zh-ch is not loaded from moment locales!`

due to this check (bootstrap-datetimepicker.js line 1775)

`if (!moment.localeData(locale)) {
                throw new TypeError('locale() locale ' + locale + ' is not loaded from moment locales!');
            }`

I was expecting datetimepicker to fallback to default language (probably 'en', or moment default language) if this happens instead of throwing a stopping error. And I didn't see an option to set a fallback locale in the documentation.

**Comment by razzed** [comment]
I am having this issue as well. As a workaround, you can check yourself before using that locale, or inline like so:

    $('#datething').datetimepicker({
         "locale": moment.localeData("zh") ? "zh" : "en"
    });

Preferably, we could supply a list of locales and the first found one would be used, e.g.

    $('#datething').datetimepicker({
         "locale": [ "ar-ma", "ar", "en" ]
    });

Thanks for an awesome plugin @Eonasdan!

**Comment by fartymonk** [comment]
Thanks for the advice, razzed. That's what I do in the meantime.

Your suggestion about the list of locale is nice! Especially in cases where the language has a lot of dialects/variant, so we can fallback to base of the language first instead of default language.

I hope it'll be implemented in future releases.
