### ISSUE TITLE
ISO 8601 Format doesn't differentiate between AM/PM

### ISSUE THREAD

**Issue by nicholaai** [Eonasdan/bootstrap-datetimepicker#1720]
If you use the following format:

`$('#filler').datetimepicker({format: 'YYYY-MM-DDThh:mm:ss.sZ'});`

to get an ISO 8601 date, you're still presented with the AM/PM option. While you're able to select the option, there is no change to the actual time that is calculated. The time always stays AM.

You can use format: 

`YYYY-MM-DDTHH:mm:ssZ`

instead but this requires manual AM/PM time calculation. 

Either the first format should be fixed to adjust accordingly for AM/PM or the AM/PM option should be removed. If I'm incorrect in the format then let me know, perhaps there should be an error message. Thanks.

**Comment by johnpancoast** [comment]
I'm having a similar issue and it seems to apply to any format where `am/pm` is shown. This lib will properly determine if it needs to show the meridiem, but it seems it's not doing anything.
