### ISSUE TITLE
I want dateicker only when icon is clicked but not when input is clicked

### ISSUE THREAD

**Issue by vijay7029** [Eonasdan/bootstrap-datetimepicker#1721]
Here is my code

<script>
    $(function () {

        $('.datepicker-me').datepicker({
            allowInputToggle: false
        });
    });
</script>

<div class="input-group date datepicker-me" >

    <div class="input-group-addon" >
        <input type="text" class="form-control">
        <span class="glyphicon glyphicon-calendar" ></span>
    </div>

</div>

**Comment by vijay7029** [comment]
![onlyiconclicked](https://cloud.githubusercontent.com/assets/8259350/17458615/9670568e-5c34-11e6-81b6-28eb79a8d019.png)

**Comment by William-H-M** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/#minimum-setup
