### ISSUE TITLE
When using with browserify doesn't work with jquery >= 2.2.0

### ISSUE THREAD

**Issue by sunrize531** [Eonasdan/bootstrap-datetimepicker#1722]
Works as expected actually, cause you have jquery version number defined as ">=1.8.3 <2.2.0" in package.json. So, if project's jquery, which is also used for bootstrap for example, doesn't match - npm would install its own jquery for datepicker. And datepicker would add itself into its specific jquery.fn, instead of global one. I'd suggest just remove top version limit, it should work fine. ;)

**Comment by styphon** [comment]
I have fixed this and made a pull request - https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1752
