### ISSUE TITLE
Do not support Timezone?

### ISSUE THREAD

**Issue by justqyx** [Eonasdan/bootstrap-datetimepicker#1725]
After a test, I draw a conclusion
1. It parse the time string(+0800) into UTC
2. It will use the timezone(+0800) of my computer when I select a time 

And I could not find an option which can specify the `Timezone`, is this a bug, or have I missing sth?

The versions are
- momentjs `2.11.1`
- bootstrap-datetimepicker `4.14.30`

**Comment by thw0rted** [comment]
There is a `timeZone` option but it is ignored if you are not also using the `moment-timezone` package.  My (npm-managed) `eonasdan-bootstrap-datetimepicker@4.17.47` wants `moment-timezone ^0.4.0` but for some reason I had to manually install it.  Once I did, I was able to specify a `timeZone` in the options hash.

This is not documented. ( #2118 )

**Comment by AlexanderPilhar** [comment]
Use `moment.tz.setDefault('TimeZoneName');` to set the default timezone you want to use (e.g. `moment.tz.setDefault('UTC');` to use UTC as default). You will need the `moment-timezone` package as mentioned by @thw0rted .

You can then convert the timezone to whatever timezone you want:
```
var guess = moment.tz.guess();
var datetime = $('#datetimepicker').data("DateTimePicker").date();datetimepicker
datetime = datetime.tz(guess);
$('#datetimepicker').data("DateTimePicker").date(datetime);
```

**Comment by William-H-M** [comment]
Hi, as @thw0rted this option is not documented but can actually be use I made a fiddle a while ago, and should bw working http://jsfiddle.net/tyw9dnhb/1/
