### ISSUE TITLE
Doesn't work in Safari Mobile

### ISSUE THREAD

**Issue by ismaelrubio** [Eonasdan/bootstrap-datetimepicker#1727]
So the issue is that when I use my iphone 6 (Safari) and try to choose a date in the calendar it will just close the calendar and don't enter the date I selected. The navigation between months/years doesn't work either. Please help, is this a known issue or I'm i doing something wrong?

**Comment by shivavelingker** [comment]
@ismaelrubio Did you ever resolve this? I'm in a similar situation. Using the demo on safari mobile works fine but not when I embed it onto my website. I'm not using the CSS classes from the demos, so I'm not sure if that's potentially the issue.

**Comment by ismaelrubio** [comment]
So the reason it wasn't working on my site was because I was also using the fastclick JavaScript library in my website and that was breaking the date time picker.



Sent from my iPhone
On Jul 1, 2017, at 2:05 PM, Shiva Velingker <notifications@github.com<mailto:notifications@github.com>> wrote:


@ismaelrubio<https://github.com/ismaelrubio> Did you ever resolve this? I'm in a similar situation. Using the demo on safari mobile works fine but not when I embed it onto my website. I'm not using the CSS classes from the demos, so I'm not sure if that's potentially the issue.

**Comment by rmovsoftcorpcom** [comment]
@ismaelrubio @shivavelingker did anyone found solution for it without removing fastclick. 
it does work with fastclick for [v4.0.0](https://github.com/Eonasdan/bootstrap-datetimepicker/releases/tag/v4.0.0) but not after any upgrade above then this.

**Comment by William-H-M** [comment]
@Hi, for anyone still looking at this you can make it work with this PR #2066 you need to either add touch start to that part of the code or you can do what this code tells https://github.com/Eonasdan/bootstrap-datetimepicker/issues/720#issuecomment-127386295

This are the line you need to modify:
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/5a991bfff0b7a721c73d482d06bcbaf9f1e3fc98/src/js/bootstrap-datetimepicker.js#L937

https://github.com/Eonasdan/bootstrap-datetimepicker/blob/5a991bfff0b7a721c73d482d06bcbaf9f1e3fc98/src/js/bootstrap-datetimepicker.js#L1248
