### ISSUE TITLE
Wrong date if format is specified

### ISSUE THREAD

**Issue by VarunPeddina** [Eonasdan/bootstrap-datetimepicker#1729]
When timezone is set and if we specify format, wrong date is being displayed

[http://jsfiddle.net/0Ltv25o8/3221/](http://jsfiddle.net/0Ltv25o8/3221/)

**Comment by cutterbl** [comment]
+1
I had issue with this, even using extraFormats to specify the different incoming value. I found a few things in the 4.17.42 code, while pegging this down.

First was the 'else if' starting on line 150. The if statement on line 159 takes care of applying the timezone to the moment object anyway, making that statement on 150 redundant.

I also found that my incoming value was a .NET ISO 8601 date string, in the following format:
2016-08-10T12:00:00Z

Not sure why .NET doesn't include milliseconds, but it doesn't. (not important) Regardless, I found that if this was the 'date' input (a string), with the parseFormats and useStrict passed to 'tz()', then it would just throw up, especially when using ISO format. Dropping the 'else if' on line 150 improved things.

The final piece of the puzzle was in the setValue() method. There's a line in the 'if isValid()' block around line 873 where there's a line commented out '//viewDate = date.clone();' Uncommenting this line fixed issues I had around the time updating anytime I opened the dtp.

**Comment by cutterbl** [comment]
Adding to this, I also found that if I was passing in a js Date object, with formats specified, that it also gave me an issue. If I added another 'else if' to the getMoment() method

} else if (d instance of Date) {
     returnMoment = moment(d);

this would resolve those issues as well

**Comment by missfxhr** [comment]
had similar issue
