### ISSUE TITLE
NuGet package has two critical bugs with unpublished fixes

### ISSUE THREAD

**Issue by jnm2** [Eonasdan/bootstrap-datetimepicker#1738]
The latest NuGet package [4.15.35](https://www.nuget.org/packages/Bootstrap.v3.Datetimepicker.CSS/4.15.35) is unusable because of these two issues which have been fixed but not published to NuGet:

 * The popup will not appear because `display: none` is never overridden. Fixed in https://github.com/Eonasdan/bootstrap-datetimepicker/commit/ea46c76c6765d2edeef34ddbfbadb5ba6693cb5b.
 * The script totally breaks due to the [jQuery `.size()` issue](https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1726).  Fixed in https://github.com/Eonasdan/bootstrap-datetimepicker/commit/0202134958a7d08b79658fbc4aa4e15b3f407515.

This is assuming you are using current versions of all dependencies exactly as per [https://eonasdan.github.io/bootstrap-datetimepicker/Installing/](https://eonasdan.github.io/bootstrap-datetimepicker/Installing/).

Please provide a working package on NuGet. Thanks!

cc @Eonasdan

**Comment by simonpfeifhofer** [comment]
@Eonasdan: Could you please publish the current main on NuGet?

**Comment by Jecoms** [comment]
Co-signed. Ran into this while trying to add the css version.

**Comment by mvpkenlin** [comment]
What version number will be fixed on these 2 issues in Nuget?

**Comment by ThePaceMaker** [comment]
What version number includes these two fixes? Nuget is still releasing 4.15.35.1 which has the size() defect bundled.

**Comment by Eonasdan** [comment]
https://www.nuget.org/packages/Bootstrap.v3.Datetimepicker/ done
