### ISSUE TITLE
Set default time to 00:00 without setting the field value.

### ISSUE THREAD

**Issue by kolorafa** [Eonasdan/bootstrap-datetimepicker#1741]
How to show "placeholder" and still have default time set to 00:000? Now it defaults to current time.

---

I have an issue, i wan't user to be able to specify hour if needed but normally want to default to midnight (00:00).

Also i wan't to have a placeholder "Select date" until the user selects the date.

The only way to set 00:00 as default is to:

> defaultDate:moment(new Date()).hours(0).minutes(0).seconds(0).milliseconds(0);

But the problem is that it changes the value, the date fields is populated without user interact, so my placeholder doesn't show.

Also

> useCurrent: 'day';

Using useCurrent leaves the field empty, when you click on the field you see the time 00:00, but when you select date it wrongly sets time to current time...

**Comment by vogtdominikgit** [comment]
I added an Issue/Solution which might solve your problem.

**Comment by InstanceOfMichael** [comment]
Been having the same problem.

**Comment by dddlp** [comment]
I know it is an old post but I was facing the same issue.
I tried this to set viewDate option instead of defaultDate.

`viewDate: moment(new Date()).hours(0).minutes(0).seconds(0).milliseconds(0)`
