### ISSUE TITLE
Add :00 for seconds

### ISSUE THREAD

**Issue by PanBagnat** [Eonasdan/bootstrap-datetimepicker#1744]
Hi.

My framework requires in the datetime input also the seconds.
How can I append ':00' to the result?

Thanks.

**Comment by vogtdominikgit** [comment]
http://momentjs.com/docs/#/displaying/format/ => use 'ss'

-> 'data-date-format' => 'DD.MM.YYYY HH:MM:ss'

**Comment by Thorazine** [comment]
Or 'data-date-format' => 'DD.MM.YYYY HH:MM:00' for just zeros.
