### ISSUE TITLE
Close button in DatetimePicker when sideBySide is true

### ISSUE THREAD

**Issue by mahmut-gundogdu** [Eonasdan/bootstrap-datetimepicker#1747]
There is a close button on sideBySide is false. Can i show close button by sidebyside mode?

**Comment by jprberlin** [comment]
You can enforce the toolbar to be showed in sideBySide Mode by setting toolbarPlacement to "top" or "bottom". 
This might be a bug as it should also be shown on default value.

**Comment by William-H-M** [comment]
Hi, I’ll be closing issues that have been answered by the community.
