### ISSUE TITLE
Setting viewDate does not change UI

### ISSUE THREAD

**Issue by callum-resdiary** [Eonasdan/bootstrap-datetimepicker#1750]
A view date can be set and the variable will update but this does not reflect in the UI until another event happens. For example if I set the viewDate to be one year in the future nothing will happen until I click next month causing it to jump appear to just a year and a month into the future.

**Comment by codez** [comment]
A call to `fillDate();` after the viewDate is set in the `viewDate` function works for me.

Just after this line:
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L2312

**Comment by Delagen** [comment]
dp.change event is called, show widget 1 time no updates at UI, second all ok. This must be fixed

**Comment by evilB** [comment]
Created a jsfiddle http://jsfiddle.net/mo287kpo/
