### ISSUE TITLE
jQuery 3.1.0  = "jQuery.Deferred exception: Cannot read property 'date' of undefined TypeError"

### ISSUE THREAD

**Issue by DocTolly** [Eonasdan/bootstrap-datetimepicker#1751]
Hi All,

My project using datetime picker was working fine with jQuery 2.1.1 - When I change it to using jQuery 3.1.0 I get the following error in my console log:

```
jQuery.Deferred exception: Cannot read property 'date' of undefined TypeError: Cannot read property 'date' of undefined
    at HTMLDivElement.<anonymous> (<anonymous>:12:70)
    at HTMLDivElement.dispatch (http://code.jquery.com/jquery-3.1.0.min.js:3:9922)
    at HTMLDivElement.q.handle (http://code.jquery.com/jquery-3.1.0.min.js:3:7949)
    at Object.trigger (http://code.jquery.com/jquery-3.1.0.min.js:4:5465)
    at HTMLDivElement.<anonymous> (http://code.jquery.com/jquery-3.1.0.min.js:4:5975)
    at Function.each (http://code.jquery.com/jquery-3.1.0.min.js:2:2815)
    at r.each (http://code.jquery.com/jquery-3.1.0.min.js:2:1003)
    at r.trigger (http://code.jquery.com/jquery-3.1.0.min.js:4:5951)
    at J (http://****/js/bootstrap-datetimepicker-4.17.12/build/js/bootstrap-datetimepicker.min.js:51:546)
    at aa (http://*****/js/bootstrap-datetimepicker-4.17.12/build/js/bootstrap-datetimepicker.min.js:56:216) undefined
jquery-3.1.0.min.js:2 Uncaught TypeError: Cannot read property 'date' of undefined
```

These are the files I am including and in this order
CSS:

> /js/bootstrap-3.3.7-dist/css/bootstrap.min.css
> /js/bootstrap-datetimepicker-4.17.12/build/css/bootstrap-datetimepicker.min.css

JS:

> //code.jquery.com/jquery-3.1.0.min.js
> /js/moment-with-locales.js
> /js/bootstrap-3.3.7-dist/js/bootstrap.min.js
> /js/bootstrap-datetimepicker-4.17.12/build/js/bootstrap-datetimepicker.min.js

As I said, if I substitute jQuery for v 2.1.1 it works fine. With jQuery 3.1.0 i get the errors above.

If it makes any difference, this is my code to call it

```
                $(function () {
                    $('#datetimepicker12').datetimepicker({
                        inline: true,
                        sideBySide: true,
                        format: 'ddd Do MMM Y HH:mm'
                    });
                });

                $('#datetimepicker12').on('dp.change', function (e) {
                    var current_date = $('#datetimepicker12').data('DateTimePicker').date();
                    $('#dynamic_date').val(current_date);
                });
```

Anyone able to assist?
Thank you! :-)

**Comment by atais** [comment]
+1

**Comment by vladds** [comment]
Same situation. 

InLine, sideBySide, can acces dp.change, but not .data('DateTimePicker').date(). 
In my case I call from angular controller. 

Also I can not find the magic setValue() function from Dev guide.

If I change directly the val, it doesnt update the view, even if I call with change.
`$('#datetimepicker').val(moment).change();`

It's a bug or I am doing something wrong ?

**Comment by vladds** [comment]
DocTolly, Why don't you use e.date / e.date._d ?  

See dp.change documentation.
http://eonasdan.github.io/bootstrap-datetimepicker/Events/#dpchange

**Comment by yhnbgfd** [comment]
+1，
i use picker with bootstrap3.3.7 and vuejs2.x, 
when vuejs component onloaded,`var start = $('#startTime').data("DateTimePicker").date();` throw `Cannot read property 'date' of undefined`.
but when i click a button who Execute`var start = $('#startTime').data("DateTimePicker").date();`,it work good.

**Comment by ramppt** [comment]
Hi, can you tell me where setTimeout is written for above
