### ISSUE TITLE
The editor should trap key events only if it did something with it

### ISSUE THREAD

**Issue by cervengoc** [Eonasdan/bootstrap-datetimepicker#1756]
The events handled by the editor are always trapped (default prevented and stopped propagation), no matter what it did with them. The correct behavior here would be to trap these events only if the editor made use of them.

Example:

Pressing the ESC key on the text editor should:
1. Close the dropdown **if** it is open, and preventDefault/stopPropagation.
2. Bypass the event without preventDefault/stopPropagation if the dropdown **isn't open**, letting other components to handle it.

In my use-case I'm trying to use dynamically created date pickers inside a table, and I need these pickers to close whenever use presses ESC on them.

**Comment by MAWAVANSMOOKEY** [comment]
Leave a comment.GOOD

**Comment by cervengoc** [comment]
@Eonasdan could you please share your thoughts on this? I think this is a general usability bug. When I have time I can put together a PR to fix these, but before that I'd like to hear your thoughts.

**Comment by Eonasdan** [comment]
looks like https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1915 was trying to solve this but changes here https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1915/files#diff-ea7d52a29508ec17b9f2d3dda885833dR1329 are strange
