### ISSUE TITLE
Bootstrap variables.less not found after install via bower

### ISSUE THREAD

**Issue by meijdenmedia** [Eonasdan/bootstrap-datetimepicker#1757]
Hi,

After installing bootstrap-datetimepicker via bower I get following error:

`/usr/local/bin/lessc --no-color bootstrap-datetimepicker-build.less
FileError: 'bootstrap/less/variables.less' wasn't found. Tried - /Volumes/Development/*/Sites/eventcenter.com/public/shared/bower_components/eonasdan-bootstrap-datetimepicker/src/less/bootstrap/less/variables.less,/Volumes/Development/*/Sites/eventcenter.com/public/shared/bower_components/eonasdan-bootstrap-datetimepicker/src/less/bootstrap/less/variables.less,bootstrap/less/variables.less in /Volumes/Development/*/Sites/eventcenter.com/public/shared/bower_components/eonasdan-bootstrap-datetimepicker/src/less/bootstrap-datetimepicker-build.less on line 2, column 1:
1 // Import bootstrap variables including default color palette and fonts
2 @import "bootstrap/less/variables.less";
3 
Process finished with exit code 1`

Am I doing something wrong?

**Comment by Thorazine** [comment]
You need to install bootstrap too. Their less variables file needs to be included. And as normal, you should pull the .less to your build file same as the bootstrap files and let your compiler build all the building with the variables. Cause this package has no default color scheme, it relies on the bootstrap theme. Same for Sass (but install bootstrap-sass)
