### ISSUE TITLE
Arrow keys doesn't work 

### ISSUE THREAD

**Issue by ChriGess** [Eonasdan/bootstrap-datetimepicker#1761]
If you want to move the cursor with the arrow keys to change the date in the date field, it doesn't work. My expectation is that I can use the arrow keys as in other input fields.

**Comment by lucax88x** [comment]
+1

**Comment by henningn** [comment]
+1

**Comment by rockResolve** [comment]
To change the default setting where arrow keys are used to change the date, change the keyBinds.
Refer https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1470.

However I would like to be able to do this quickly when the picker is always shown. In that case the keyBinds should only work when the picker is focused, not when when the input field is.

**Comment by William-H-M** [comment]
Closing in favor of 1014
