### ISSUE TITLE
TypeError: locale() locale it is not loaded from moment locales!

### ISSUE THREAD

**Issue by hackpiro** [Eonasdan/bootstrap-datetimepicker#1764]
I'm using meteor with this version Meteor 1.4.1.1 and this package
tsega:bootstrap3-datetimepicker 4.17.37_1
momentjs:moment 2.14.4

the console ever return this

`tsega/meteor-bootstrap3-datetimepicker TypeError: locale() locale it is not loaded from moment locales!`

this is my code

```
Template.nuovoCantiere.onRendered( () => {
   $( '.datetimepicker' ).datetimepicker({
   timeZone: 'Europe/Rome',
   format: 'D/MM/YYYY',
   locale: 'it'
   });
});

```

I read that moment packages is "Flagged Package This package has been flagged as not working by the community. Use at your own risk." so i tried use npm:

```
var moment = require('moment');
require('moment/locale/it');

Template.nuovoCantiere.onRendered( () => {
$( '.datetimepicker' ).datetimepicker({
timeZone: 'Europe/Rome',
format: 'D/MM/YYYY',
locale: 'it'
});
});

```

**Comment by nacimgoura** [comment]
I have the same problem, still no issues ?

**Comment by William-H-M** [comment]
Hi, @nacimgoura this has been solved on [this Issue](https://github.com/tsega/meteor-bootstrap3-datetimepicker/issues/60)

So I'll quote this just in case:

> to solve the issue
> 
> $ meteor add rzymek:moment
> $ meteor add rzymek:moment-locale-it
> 
> Restart your app and that's it. There's no need to reference a node-module (i.e var moment = require('moment');) and stuff.
> 
> thanks to [R.Pil](https://stackoverflow.com/questions/39275274/meteor-tsega-meteor-bootstrap3-datetimepicker-typeerror-locale-locale-it/39496574#39496574) that solved the issue so

It'll be great if @hackpiro  could close this, as been solved a while ago.
