### ISSUE TITLE
Knockout example doesn't work with 4.17.42

### ISSUE THREAD

**Issue by hpinkos** [Eonasdan/bootstrap-datetimepicker#1770]
[This sample code](http://eonasdan.github.io/bootstrap-datetimepicker/Installing/#knockout) makes the date picker behave really strangely.  For any month, when you click day 1 to 12 it sets that as the month and 20 as the day

JS Fiddle demo: https://jsfiddle.net/w4dt40pw/

It works fine with 4.17.37

**Comment by aptajosh** [comment]
https://jsfiddle.net/aptajosh/2xc34wd9/
