### ISSUE TITLE
Widget pops up behind form controls

### ISSUE THREAD

**Issue by MaximeDawn** [Eonasdan/bootstrap-datetimepicker#1774]
I have a dynamic form in which I can click a button to add a new row. Each row is composed by 2 date time picker text boxes. My issue is when I add a second row, it passes in front of the widget, resulting that only the bottom most picker is acting properly. I already tried fixing that with a z-index at 9999 but it won't. Any suggestions ? ( and sorry for my bad english :x )

![bug](https://cloud.githubusercontent.com/assets/20993007/18302926/c04fa8ec-74da-11e6-91cf-4527dbd5f1be.png)

**Comment by Nicks182** [comment]
Had a similar issue. See here:
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1762

**Comment by MaximeDawn** [comment]
Yes, but i can't make it inline, which is I guess the solution you choose, and i can't figure out how to make this widgetParent option to work like it should :/ Thanks anyway
