### ISSUE TITLE
toolbar not showing when sideBySide is true

### ISSUE THREAD

**Issue by etsmes** [Eonasdan/bootstrap-datetimepicker#1775]
Hi,

I would like to configure showClear and showClose to true as well as sideBySide true. But toolbar is not showing when sideBySide is true.

Many thanks,

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.

**Comment by etsmes** [comment]
Hi,

I don't know why but in the fiddle it works. But not in my own server. 
I solved it specifying toolbarPlacement.

Kind regards,
