### ISSUE TITLE
Invalid css

### ISSUE THREAD

**Issue by krislm** [Eonasdan/bootstrap-datetimepicker#1776]
Still getting the Invalid css warning since PR [#1749](https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1749).

`
Running "sass:dist" (sass) task
`
`
Invalid CSS after "...id transparent;": expected "}", was "               ..."
Line 271  Column 48  bower_components/eonasdan-bootstrap-datetimepicker/src/sass/_bootstrap-datetimepicker.scss
`

Version: 4.17.42
_bootstrap-datetimepicker.scss:
![screen shot 2016-09-08 at 15 05 10](https://cloud.githubusercontent.com/assets/4058715/18350332/bab25dd4-75d5-11e6-898b-205a378a56a9.png)

Perhaps the file wasn't added to the commit prior to publishing to bower, since the same .less file says version 4.17.42 and the .scss file says version : 4.7.14

**Comment by ffaubry** [comment]
+1

**Comment by TifPun** [comment]
+1

**Comment by reneszabo** [comment]
:( that + symbol ..

**Comment by wietsewarendorff** [comment]
+1

**Comment by nmpribeiro** [comment]
Is eonasdan-bootstrap-datetimepicker@4.17.42 already fixed? Because that's the one being installed by my npm and I see a + on 272.
What's the version of the fixed one? dev?

**Comment by krislm** [comment]
@nmpribeiro  Just tried latest version (bower) and problem remains. As stated the version is 4.17.42 however the _bootstrap-datetimepicker.scss file reads version 4.7.14.

**Comment by nmpribeiro** [comment]
@krislm we could fork the master and use it until the rep dev fixes it. right now I'm manually removing the cross. hope next update will take this into consideration. 12 days for such a small annoyance :)

**Comment by krislm** [comment]
@nmpribeiro You don't have to. Since the problem **is** fixed (just not published) you can just require the master branch in your bower.json like so:
`"eonasdan-bootstrap-datetimepicker": "git://github.com/Eonasdan/bootstrap-datetimepicker.git#master"`

**Comment by nmpribeiro** [comment]
@krislm first time I'm installing js libs with gulp and npm... it has resolved the issue. thanks.
