### ISSUE TITLE
data-date-min-date attribute applies to all datepickers 

### ISSUE THREAD

**Issue by Phibbs14** [Eonasdan/bootstrap-datetimepicker#1778]
If a previous datepicker specifies data-date-min-date, the next datepickers will also have the same restriction.

http://jsfiddle.net/aoqx7bj4/2/

Calling datetimepicker on each individual datepicker gets around the issue.

**Comment by btecu** [comment]
This is fixed in the last version https://jsfiddle.net/7j6poL09/
