### ISSUE TITLE
Format gets removed

### ISSUE THREAD

**Issue by btecu** [Eonasdan/bootstrap-datetimepicker#1783]
After selecting a date, the format gets removed.
If you click on the calendar again, you'll be prompted to select a day instead of (month / year).

http://jsfiddle.net/ez13bju0/

**Comment by diegosurita** [comment]
+1

**Comment by lukaszdechovan** [comment]
+1

**Comment by William-H-M** [comment]
Hi, this was solved on latest version.
https://jsfiddle.net/William_/ja6v6x2x/
