### ISSUE TITLE
Cannot read property ... of undefined

### ISSUE THREAD

**Issue by Sajgoniarz** [Eonasdan/bootstrap-datetimepicker#1784]
$('input[name="time_start"]').datetimepicker({
		format: 'HH:mm',
	});

	$('input[name="time_end"]').datetimepicker({
		format: 'HH:mm',
		useCurrent: false
	});

	$('input[name="time_start"]').on("dp.change", function (e) {
		$('input[name="time_end"]').data("DateTimePicker").minDate(e.date);
	});
	$('input[name="time_end"]').on("dp.change", function (e) {
		$('input[name="time_start"]').data("DateTimePicker").maxDate(e.date);
	});

.data is an empty object. Tried with ID's, but result was the same.

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.
