### ISSUE TITLE
Doesn't display initial date

### ISSUE THREAD

**Issue by dleffler** [Eonasdan/bootstrap-datetimepicker#1786]
In the latest release v4.17.42, at least when displayed inline, the calendar initially displays the CURRENT month instead of the SET month, though the date/time is correctly set when you manually move to that month. This worked as expected in the previous version 4.17.37

**Comment by cfood** [comment]
This happens for me too.

**Comment by MaikeAlame** [comment]
Here too. Go back version so

**Comment by drvid** [comment]
I'm getting a completely different date rendered than my initial value, this seems like a pretty severe bug.

I've created a codepen to illustrate:
https://codepen.io/drvid/pen/zJKgPP
