### ISSUE TITLE
datetimepicker pop-up not getting closed after selecting date

### ISSUE THREAD

**Issue by sushantlal** [Eonasdan/bootstrap-datetimepicker#1788]
after selecting date, calendar reamined open, want to hide or closed, once you select date

downloaded from---  https://eonasdan.github.io/bootstrap-datetimepicker/
code is here--
<input type="text" id='gtdDate' ng-model="ExDate" placeholder="Select date" readonly>
<script>
$(document).ready(function () {
    var currentDate = new Date();
    jQuery('#gtdDate').datetimepicker({
        format: 'DD-MMM-YYYY HH:mm',
        useCurrent: false,
       // autoclose: true,
        keepOpen: false,
    })
}); 
</script>

**Comment by Eonasdan** [comment]
this has been mentioned over and over in the issues. use the search box
