### ISSUE TITLE
Using minDate makes the hours and minutes picker disabled and greyed out

### ISSUE THREAD

**Issue by cfood** [Eonasdan/bootstrap-datetimepicker#1789]
When minDate is in use, the hours and minutes in the time picker panel is disabled and greyed out, even when trying to select a time from a day after the minDate value. None of the numbers are clickable. Sometimes selecting a date first will activate the hours/minutes, other times it doesn't. This apparent bug doesn't happen when using maxDate. Only on minDate.

**Comment by MitchTalmadge** [comment]
Same problem 👍

**Comment by MitchTalmadge** [comment]
Found out the problem doesn't exist in 4.17.37 (https://rawgit.com/Eonasdan/bootstrap-datetimepicker/4.17.37/build/js/bootstrap-datetimepicker.min.js)

So it is a recent bug.

**Comment by cfood** [comment]
This happens when the minDate value is set after today's date. 

Reverting back to 4.17.37 solved the bug, but it introduced an older bug (hours decreasing by 1 hr each time I clicked on the input field).

**Comment by cfood** [comment]
I figured out a workaround for this:

```
$(input).on('dp.show', function() {
    if ($(this).val()) {
        $('td.hour.disabled').removeClass('disabled');
        $('td.minute.disabled').removeClass('disabled');
    }
});

$(input).on('dp.change', function() {
        $('td.hour.disabled').removeClass('disabled');
        $('td.minute.disabled').removeClass('disabled');
});
```

**Comment by MitchTalmadge** [comment]
Would that allow you to select times that shouldn't be selected on the minDate?

**Comment by cfood** [comment]
I think that would be the case, although I haven't tested it with specific minDate hours and minutes yet. The above workaround works for my task so far since the minDate time is always 00:00:00.

**Comment by yads** [comment]
FWIW, I believe this is the offending line that introduced the bug:
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/fd3e25f03010d868aaa07b5c34675e12dbf290f3/src/js/bootstrap-datetimepicker.js#L869

The problem is that the functions that are ran as part of an `update()` call all use a stale viewDate in order to figure out whether items need to be disabled. However, it only affects the Hours/Minutes of the picker.

**Comment by MitchTalmadge** [comment]
Still a problem... :/

**Comment by xawiers** [comment]
Anyone want to solve it?

**Comment by William-H-M** [comment]
@xawiers currently this is not a problem anymore on version 4.17.47, I've tested it with the current date, with a day plus date, using useCurrent option on false and true, and still no problem. For now this fiddle show no problem for me. https://jsfiddle.net/William_/ajaxnz23/2/

If for you is a problem please provide which steps you're doing, thanks.

**Comment by xawiers** [comment]
Thanks a lot. Now it works as expected.
