### ISSUE TITLE
Cannot navigate between months using keyboard.

### ISSUE THREAD

**Issue by shreya07** [Eonasdan/bootstrap-datetimepicker#1794]
The calendar does not change to the next month when keyboard navigates to a date from previous/next month.

This used to work before, so it could be related to this pull request: #1780

**Comment by shreya07** [comment]
@johnnyRose @Eonasdan Does this sound related?

**Comment by johnnyRose** [comment]
@shreya07 off the top of my head I would say no, but I haven't looked into it. Do you have a fiddle?
