### ISSUE TITLE
TypeError: locale() locale fr-FR is not loaded from moment locales!

### ISSUE THREAD

**Issue by abumalick** [Eonasdan/bootstrap-datetimepicker#1797]
Hello,
I installed your library in my project using bower.
I got this error when using french version of my website : 
`TypeError: locale() locale fr-FR is not loaded from moment locales!`
It seems that when bower loads moment (as a dependency of your package) it loads `moment.js` and not  the `moment-with-locales.min.js` needed by your library
I had to add an override for moment package in my bower.json : 
```json
"overrides": {
    "moment": {
      "main": [
        "./min/moment-with-locales.min.js"
      ]
    }
  }
```
I don't know if you can fix that on your site.
I use   "eonasdan-bootstrap-datetimepicker": "^4.17.42"
and I don't have moment in my bower.json.

**Comment by Eonasdan** [comment]
the locales are only needed if you intent to use a locale so you'll have to grab what you require
