### ISSUE TITLE
Issue with datetimepicker when clicking on Year.

### ISSUE THREAD

**Issue by jinnarapuanil** [Eonasdan/bootstrap-datetimepicker#1799]
![datetimepicker_issue](https://cloud.githubusercontent.com/assets/4577902/18777522/3c890a16-818d-11e6-8586-cf08abcde8e0.jpg)

**Comment by monkiki** [comment]
I've the same problem. Any fix or workaround?

Thanks!

**Comment by monkiki** [comment]
Solved. The problem was I had this in my custom css file:
`td { white-space: nowrap; }`
