### ISSUE TITLE
Possible CSS issue, the layout does not match one on the tutorial

### ISSUE THREAD

**Issue by Six-wars** [Eonasdan/bootstrap-datetimepicker#1803]
I've followed the setup procedure for manually using bootstrap datepicker 3 and it has worked but the layout looks worse than the one on the tutorial, the calendar css looks not to have work and it looks to be pixelated. It's not possible to upload an image so I've added one to my public stream so any developer can have a preview and advice https://plus.google.com/+SamuelMuiruri/posts/EwFXg4cqhxz

**Comment by Eonasdan** [comment]
you have missing css or it's being overridden

**Comment by Six-wars** [comment]
I looked at the code I hadn't included the datetimepicket css
