### ISSUE TITLE
Date Value Messed Up

### ISSUE THREAD

**Issue by missfxhr** [Eonasdan/bootstrap-datetimepicker#1806]
![screen shot 2016-09-27 at 2 55 19 pm](https://cloud.githubusercontent.com/assets/10817350/18893356/6f9a4dd8-84c2-11e6-96ca-140708f686e3.png)

Does anyone have any idea on that? If src code is needed to debug, i would post then.

**Comment by missfxhr** [comment]
Just found that year number was not the only number that went wrong, actually the whole date value is messed up. It was correct after I opened the widget. Later when I switch between different dates, for some date, the date value went wrong like this. I debugged the DOM element and see the value attribute of the hidden input tag for this date is "05/20/0016 2:55 PM" event though I selected some date in September 2016.

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.
