### ISSUE TITLE
Manual install guid contains no download link

### ISSUE THREAD

**Issue by nickel715** [Eonasdan/bootstrap-datetimepicker#1807]
I like to install bootstrap-datetimepicker manually but I can't find a download link in the installation guide:
http://eonasdan.github.io/bootstrap-datetimepicker/Installing/#manual

**Comment by Eonasdan** [comment]
get the files from the build folder https://github.com/Eonasdan/bootstrap-datetimepicker/tree/master/build

**Comment by nickel715** [comment]
Thanks, what's about providing this link in the installation guide?
