### ISSUE TITLE
Timepicker Show Hours Only

### ISSUE THREAD

**Issue by gamalielwkr** [Eonasdan/bootstrap-datetimepicker#1808]
Hello, I have a question about how to show hours option like this
![screen shot 2016-09-30 at 1 57 49 pm](https://cloud.githubusercontent.com/assets/10864077/18983285/0f292c3e-8716-11e6-8e66-09af08a9452a.png)
when first time the timepicker show up.

That means skip this step
![screen shot 2016-09-30 at 1 57 24 pm](https://cloud.githubusercontent.com/assets/10864077/18983290/1920e196-8716-11e6-8924-941099efe5ea.png)

Thanks in advance.

**Comment by Lukas1990** [comment]
This is also for me needed.
