### ISSUE TITLE
showTodayButton on view 3 (month view) in different month does not go now month

### ISSUE THREAD

**Issue by gabn88** [Eonasdan/bootstrap-datetimepicker#1810]
According to the description: Clicking the "Today" button will set the calendar view and set the date to now.

In practise:
Clicking the "Today" button in the same month as the current month will move the pointer to today. But if you are in view 3 (month view) and are already moved to a different month, the view will not go back to the current month.

**Comment by sdreger** [comment]
'Today' button doesn't switch view to the current month in versions: 4.17.37, 4.17.42, 4.17.43.
Last working version: 4.15.35.

**Comment by sdespont** [comment]
Here is a fiddle of the problem for version 4.17.43 : https://jsfiddle.net/0Ltv25o8/4229/

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.
