### ISSUE TITLE
Function date() do not work with Date type input

### ISSUE THREAD

**Issue by JayDi85** [Eonasdan/bootstrap-datetimepicker#1811]
Hello.

I'm using v4.17.42, firefox, datepicker format = 'DD.MM.YYYY'.

If I try to set datepicker value by date() function with `Date` type -- it's failed and nothing happen:
`$('#dateStart').find('.input-group.date').data('DateTimePicker').date(moment().toDate());`

But if I try to set `moment()` type data -- it's work correct:
`$('#dateStart').find('.input-group.date').data('DateTimePicker').date(moment());`

**Comment by martijnvanderwoud** [comment]
I have the same issue on v4.17.43 (with JQuery 3.1.1-1)

**Comment by afzalgujrat** [comment]
hi

**Comment by rknetwork** [comment]
Same issue here

**Comment by afzalgujrat** [comment]
@rknetwork I found a solution somewhere 
you'll need to include Moment Js also
$("#BidCloseDateTime").data("DateTimePicker").date(moment(yourDate));

I hope it'll help :)

**Comment by rknetwork** [comment]
Mine was a different issue, moment object was invalid. =))
