### ISSUE TITLE
_bootstrap-datetimepicker.scss has error in line 272

### ISSUE THREAD

**Issue by morales2k** [Eonasdan/bootstrap-datetimepicker#1815]
There is a plus `+` sign in there where it shouldn't be cracking up sass compilation.  If I use the bower dependency manager, push-to-deploy is a nightmare because all my deploys fail due to that error.

**Comment by karolyi** [comment]
the issue is, the release 4.17.42 doesn't contain commit c3e46cc301d851cf347366e361c5a0ba50b1de4a.

a fix (new release) would be *really* nice, so I wouldn't have to refer the master branch in bower.
