### ISSUE TITLE
Picker Date Incorrect on Initial View

### ISSUE THREAD

**Issue by kevinmlong** [Eonasdan/bootstrap-datetimepicker#1819]
I'm having an issue with the wrong day being highlighted in the picker when it is initially displayed. 

I'm initializing the field like so:

``` javascript
$('#timeFrameStart').datetimepicker({
            format: 'YYYY-MM-DD HH:mm',
            defaultDate: moment.utc().seconds(0),
            ignoreReadonly: true,
            sideBySide: true
        });
```

This is the initial view:

<img width="572" alt="screen shot 2016-10-06 at 4 22 01 pm" src="https://cloud.githubusercontent.com/assets/6371696/19169198/4cf61f5c-8be1-11e6-879e-4f1331f70504.png">

If I close and re-open the picker:

<img width="565" alt="screen shot 2016-10-06 at 4 24 41 pm" src="https://cloud.githubusercontent.com/assets/6371696/19169228/6d7e9600-8be1-11e6-9adb-82d0963c1ad0.png">

**Comment by kevinmlong** [comment]
I just tested and it seems to have to do with how the moment returned by `moment().utc()` is handled. If I initialize with `moment().seconds(0).add(4,'hours')`, it works as expected.

**Comment by maxigs** [comment]
I have found a similar issue.

When i first open the Datepicker it always has the current date picked (no matter if useCurrent option set or not), when i close and re-open it the correct date is selected.

I'm still not sure why this is, but i suppose something in the chain of events of initialization does not work as it should :(

**Comment by maxigs** [comment]
Downgraded to 4.17.37 now and it works again, not sure yet if i have any other problems due to the downgrade

**Comment by William-H-M** [comment]
Closing on favor of #1959
