### ISSUE TITLE
`dp.change` event not trigged when the date is deleted

### ISSUE THREAD

**Issue by allenwq** [Eonasdan/bootstrap-datetimepicker#1823]
When the user empties the date, `dp.change` is not triggered. 

Because of this, we cannot get the latest status of the date when it's deleted.

**Comment by venkat18** [comment]
Hi @allenwq .. were you able to solve this issue. I have encountered the same issue.
 I am using Datetimepicker for Bootstrap 3 * version : 4.15.35

**Comment by allenwq** [comment]
@venkat18 I was trying to write a custom listener to the input and manually do it...
