### ISSUE TITLE
replace glyphicon to font awesome for support bootstrap4

### ISSUE THREAD

**Issue by simplydesigner** [Eonasdan/bootstrap-datetimepicker#1825]
icons: {
            time: 'fa fa-clock-o',
            date: 'fa fa-calendar',
            up: 'fa fa-chevron-up',
            down: 'fa fa-chevron-down',
            previous: 'fa fa-chevron-left',
            next: 'fa fa-chevron-right',
            today: 'glyphicon glyphicon-screenshot',
            clear: 'fa fa-trash',
            close: 'fa fa-times'
        },

**Comment by koltzc** [comment]
I am using this with Bootstrap 4 and the next/previous don't appear. I have this in my Javascript functions and everything else appears but the next/previous.

icons: {
		time: 'fa fa-clock-o',
		date: 'fa fa-calendar',
		up: 'fa fa-plus',
		down: 'fa fa-minus',
		next: 'fa fa-chevron-left',
		previous: 'fa fa-chevron-right'
		},

**Comment by koltzc** [comment]
Never mind, site was cached and works proper outside of me reversing the next/previous icons :)

**Comment by we125182** [comment]
@koltzc i use this with bootstrap4-alpha6 , but there was nothing but icon to show. what's wrong? could you tell me how to use this correctly?
something like 
![2017-08-08_142848](https://user-images.githubusercontent.com/17947588/29059067-54c0ddf2-7c46-11e7-9ab3-09ab95fb8020.png)
