### ISSUE TITLE
TypeError: option autoclose is not recognized!

### ISSUE THREAD

**Issue by xSQL** [Eonasdan/bootstrap-datetimepicker#1828]
I get this error. Also  TypeError: option language is not recognized! (Use v4.17.42 and bootstrap 3)

**Comment by SirAiedail** [comment]
Those errors are correct behavior, the options don't exist.
Use `keepOpen` instead of `autoclose` and `locale` instead of `language`.
See [the docs](http://eonasdan.github.io/bootstrap-datetimepicker/Options/) for more information.
