### ISSUE TITLE
Is there any proper way to use 12 hour time with AM PM

### ISSUE THREAD

**Issue by anirugu** [Eonasdan/bootstrap-datetimepicker#1830]
Someone please let me know how I can implement the time in 12 hour  like 13:56 will be 1:56 PM.

Any idea ?

I need to show AM PM in UI.  I already use date in one textbox. In another textbox I need to show the AM PM Like the top#1 example on this page
https://eonasdan.github.io/bootstrap-datetimepicker/

Thanks in advanced.

**Comment by Eonasdan** [comment]
The picker uses the `format` option to decide what components to show. Set `format` to `LT` or another valid momentjs format string

Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.

**Comment by anirugu** [comment]
@Eonasdan  Thanks men for help, I got it working :)

**Comment by anirugu** [comment]
@Eonasdan It's look like working but I want to write CSS. How I can modify it ?, Everytime it's focusout it's stop showing and div is removed from DOM.
