### ISSUE TITLE
latest version - prepopulated date doesn't show up in the calender until the 2nd time the popup shows

### ISSUE THREAD

**Issue by CCHSRobochargers** [Eonasdan/bootstrap-datetimepicker#1831]
Spent 2 hours figuring this one out: when we use MVC date fields, which populate the input value attribute to something similar to: "1/21/2014 3:37:42 PM -04:00" (not sure if that's why, just including for info), when using version 4.17.42, or some other versions after 4.17.37, even with no options, clicking on the date button or the input field brings up the month view viewing this month with no blue date selected. Clicking outside the dialog to close it and clicking the input box to open it again a second time then shows the pre-populated month with the correct date selected.

This also appears to be the case with the latest build as well. I am willing to provide any additional information needed if it helps to fix this.

Thanks!

**Comment by mikeerickson** [comment]
I am experiencing a similar issue.  The first time I set the date value, all appears correctly (not quite sure the exact format I should be sending though).

However, if I set the date value from another method, etc. (I am using with Angular) the date value is not updated the model associated with popup.

**Comment by CyborgMaster** [comment]
Is this possibly the same issue as #1836?

**Comment by kgiil** [comment]
I found the reason for this, at least the following fixed it for me:
Line 869 in bootstrap-datetimejs.js (v. 4.17.43 ) has this line commented out:
//viewDate = date.clone(); // TODO this doesn't work right on first use

Uncommenting the line fixed the issue for me.

**Comment by lucianjp** [comment]
If you want to patch without altering the code you can instanciate the date before the picker and set both date and viewDate as :
```
var date = moment($('#datetimepicker>input')[0].value);
$('#datetimepicker1').datetimepicker({
  date: date,
  viewDate: date
});
```

**Comment by mrndig** [comment]
I can confirm this is still an issue in 4.17.43. 

First time you open the datepicker, you see the current month/date and not the month/date in the input. If you open it again, it will display the correct month.

As @lucianjp pointed out, the only solution at the moment is forcing **viewDate** option to the date you want to see when you first open the datepicker.

**Comment by gameboyzone** [comment]
It's quite interesting that the Bootstrap-DateTimepicker plugin works so well but has this defect in the current library v4.17.42. It turns out as per documentation there exists the date() function to set the date but also viewDate() function to set the date selected when you view the date modal. That is exactly what the defect is - date() function does not set the viewDate()!

I tried the solution suggested by @kgiil but that gives me the following error in console -
Uncaught TypeError: Cannot set property 'newWindow' of null

Also the solution suggested by @lucianjp did not work for me unfortunately. So I tried doing both in separately and that works -

`
$("#txtApptDate").data("DateTimePicker").date(dateObj.format("MM-DD-YYYY"));
$("#txtApptDate").data("DateTimePicker").viewDate(dateObj.format("MM-DD-YYYY"));
`

**Comment by eusonlito** [comment]
Same problem here (version 4.17.43), a gif example:

![peek 2016-12-18 01-57](https://cloud.githubusercontent.com/assets/644551/21290734/faf47be0-c4c5-11e6-9c76-0e731f44cbf6.gif)

Current code:

```js
$('.date-picker').datetimepicker({
    format: 'DD/MM/YYYY',
    locale: 'es',
    ignoreReadonly: true,
    useCurrent: true
});
```

**Comment by William-H-M** [comment]
Hi, seems like the latest version, 4.17.47, doesn't have this error.

**Comment by chippy-0908** [comment]
again shows the pop up for date after get the select the date what to do in quasar

**Comment by chippy-0908** [comment]
![Screenshot at 2019-11-28 18-07-01](https://user-images.githubusercontent.com/58297441/69806990-30726e00-120a-11ea-9995-9f6e4c6b3284.png)

**Comment by chippy-0908** [comment]
![Screenshot from 2019-11-28 18-11-42](https://user-images.githubusercontent.com/58297441/69807210-bb536880-120a-11ea-9251-32346a2c38dc.png)
