### ISSUE TITLE
datetimepicker minDate issue

### ISSUE THREAD

**Issue by zlaja1983** [Eonasdan/bootstrap-datetimepicker#1832]
Hello,
I am setting minDate and maxDate on datetimepicker.

minDate is showing as selectable but when i click it it does not update the input control.
Selecting maxDate works fine.

Here is the fiddle: 
https://jsfiddle.net/zlaja1983/t23z4hLd/

**Comment by emmanuelballery** [comment]
```js
var minDate = moment().subtract(7, 'days').millisecond(0).second(0).minute(0).hour(0);
```

Time flies ... :)

**Comment by zlaja1983** [comment]
Thank you, that works.

**Comment by JaniceLian** [comment]
if i set options like following:
options({
          format: "YYYY",
          viewMode: "years",
          maxDate: new Date("2017"),
          minDate: new Date("2014")
  })

minDate "2014" is showing selectable, but when i click it it does not update the control
