### ISSUE TITLE
date and time picker

### ISSUE THREAD

**Issue by observingly** [Eonasdan/bootstrap-datetimepicker#1833]
Do you have an option for the picker to display only the date and not include the time?

**Comment by btecu** [comment]
Yes, you just have to use [format](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#format). Read the documentation. 😄

**Comment by observingly** [comment]
thank you, haven't seen that one. :)

**Comment by btecu** [comment]
Close this, since it's not an issue.
