### ISSUE TITLE
Disable minute and seconds

### ISSUE THREAD

**Issue by iamdriz** [Eonasdan/bootstrap-datetimepicker#1834]
Is it possible to disable the minute and seconds when using the time picker?

I only want to allow the user to pick change the hour so I always get values like: `13:00:00` and `14:00:00`, etc.

**Comment by TrevorPearson** [comment]
using the option "stepping: 60" would probably work. 
Or change your format option "format: MM/dd/YYYY hh". Not sure if hour format is correct

**Comment by iamdriz** [comment]
Well I still want to see the minutes and seconds on the picker. But I want them to be read only at 00

**Comment by Eonasdan** [comment]
The picker uses the `format` option to decide what components to show. Set `format` to `LT` or another valid momentjs format string
