### ISSUE TITLE
Set date option and open picker does not show correct date

### ISSUE THREAD

**Issue by MicheleMannino** [Eonasdan/bootstrap-datetimepicker#1836]
It seems to be date moment-with-locales version 2.15.1 does not with datetimepicker version 4.17.42.

moment-with-locales: 2.15.1
datetimepicker: 4.17.42

https://jsfiddle.net/0Ltv25o8/3809/

`$('#datetimepicker1').datetimepicker({
    date: '2015-11-09T15:40+0200'
});`

**Comment by TrevorPearson** [comment]
What value are you expecting? your fiddle sets the date to "11/09/2015 7:40 AM" for me.

**Comment by MicheleMannino** [comment]
It seems to be that the first time the datetimepicker is opened, it does not show the selected date (11/09/2015), but the calendar shows the current month.

**Comment by CyborgMaster** [comment]
I'm also having the calendar show the current month.  If I set it to `2015-10-19`, when I open the picker it shows October 2016.  If I browse back to October 2015 I can see that the correct date is selected, it just opens with the wrong month showing.

**Comment by CyborgMaster** [comment]
This seems to have been introduced in version 4.17.42.  It doesn't appear to be a problem in version 4.17.37, so reverting to that version was a temporary work around for me.

**Comment by MicheleMannino** [comment]
I confirm that using 4.17.37 works without any problem.

**Comment by jayanthrajpramuk** [comment]
4.17.43 has the same issue. But i can confirm that it works fine in 4.17.37

**Comment by taikitech** [comment]
The same bug in 4.17.43.
4.17.37 - works fine.
