### ISSUE TITLE
Two dates has today

### ISSUE THREAD

**Issue by maikealame** [Eonasdan/bootstrap-datetimepicker#1837]
Hey, I noticed a bug on today. Follow image:
![image](https://cloud.githubusercontent.com/assets/15782847/19438287/e0b322b6-9457-11e6-9d4e-04e18cf7a3dd.png)
The code:

```
$("input.datepicker").datetimepicker({
        format: 'DD/MM/YYYY',
        locale: "pt-br"
})
```

I'm using version 4.17.42 (the newest has another bug with inline option)

**Comment by William-H-M** [comment]
Closing in favour of #2182
