### ISSUE TITLE
TypeError: a.fn.datepicker is undefined

### ISSUE THREAD

**Issue by Kevincifuentes** [Eonasdan/bootstrap-datetimepicker#1839]
Hi everyone!

The datetimepicker works great but i keep getting `TypeError: a.fn.datepicker` is undefined every time the page is reloaded. Do you know why this happens?
I just follow this example http://jsfiddle.net/msh722an/1/
Sorry if the question was asked before, didn't find it.

Thanks in advance!

**Comment by Eonasdan** [comment]
you're not using my picker
