### ISSUE TITLE
viewMode: "years" and format: 'YYYY', lowest year not pickable?

### ISSUE THREAD

**Issue by clutwo** [Eonasdan/bootstrap-datetimepicker#1840]
It seems that when the datepicker is set to "Years", the lowest available Year (minDate) is never pickable, isValid looks like this: 

`
if (options.minDate && targetMoment.isBefore(options.minDate, granularity)) {
                    return false;
                }`

The targetMoment is (i.e. when selecting 2014) Jan 1, 00:00:00 2014, so the minDate object for the year 2014 can never be before that. If I pass 31.12.20013, 2013 is not disabled but again, it can't be picked. But 2014 now can be picked.

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.

and if you set up this option will work too:

```
  format: 'YYYY',
  minDate: moment('2014', 'YYYY')
```
