### ISSUE TITLE
How to use datepicker only and appear the popup by clicking anywhere on the input field?

### ISSUE THREAD

**Issue by itzpradip** [Eonasdan/bootstrap-datetimepicker#1845]
Hi,
I want to use this picker to pick the **date only** user will not be able to select any time and is it possible to make the **calendar box appear by clicking anywhere on input field** not just by clicking on the calendar icon.

thanks in advance.

**Comment by itzpradip** [comment]
I have found to make the calendar box appear by clicking on input field. Now just help me with **date only** part please.

**Comment by mai-reda** [comment]
@itzpradip  
how did u show the date only ?? 
and inform me if u knew how to make the format  dd-mm-yyyy

**Comment by itzpradip** [comment]
Use `format: 'L'` it will make the date format as mm/dd/yyyy or you can use `format: 'LL'` to make the date format as October 22, 2016 (today's date 22/10/2016). I haven't found the way to make the format a dd-mm-yyyy yet.

**Comment by mai-reda** [comment]
how can i make the calendar box appear by clicking on the input field @itzpradip

**Comment by SirAiedail** [comment]
Call `.datetimepicker()` on `$('input')`instead of `$('.input-group')`.
Take a look at [this example in the docs](https://eonasdan.github.io/bootstrap-datetimepicker/#no-icon-input-field-only).

**Comment by itzpradip** [comment]
Yes solution provided by @SirAiedail is perfect solution for your problem @mai-reda .
