### ISSUE TITLE
datepicker not triggering 'input' event

### ISSUE THREAD

**Issue by marcandre** [Eonasdan/bootstrap-datetimepicker#1846]
While not widely known, the `input` event is triggered before all `change` events for inputs and selects (see [the spec here](https://www.w3.org/TR/html5/forms.html#send-select-update-notifications))

`Parsley` relies on the `input` event, so [it is not compatible with datetimepicker](https://github.com/guillaumepotier/Parsley.js/issues/1123)

I'd gladly provide a PR but they don't seem to get merged in.

**Comment by SirRawlins** [comment]
I'm having similar issues with `stretchy.js` which relies on the `input` event to resize the input fields to fit the content.

**Comment by SirRawlins** [comment]
As an aside, I'm currently working around this by binding manually to the `dp.change` event and triggering my stretchy events. Not optimal but works just fine.

```js
$(function () {
    $('.mydatepicker').datetimepicker().on("dp.change", function(e) {
        Stretchy.resize(e.target)
    });
});
```

**Comment by bodinsamuel** [comment]
I can confirm this issue as well.
For now, this works:
`$(event.target).trigger('input');`

**Comment by William-H-M** [comment]
Hi, I’ll be closing issues that have been answered by the community.

**Comment by marcandre** [comment]
@William-H-M the issue itself is not fixed. I'll gladly provide a PR if there's a chance it'll land... but the README isn't clear: is there a new repo and will bug fixes be merged in?

**Comment by William-H-M** [comment]
Hi, @marcandre the thing is that the widget, if not wrong, does a `e.prenventDefault` that is by dessing, what It could be done is to trigger that event again inside the code, but as we have a "personalized" event there souldn't be need of adding it. And yes the new repo maybe would take this in considiretion but currently they don't have that feauture, but of course you could ask for the PR on:

For BS3: https://github.com/tempusdominus/bootstrap-3
For BS4: https://github.com/tempusdominus/bootstrap-4

**Comment by marcandre** [comment]
Actually, looks like `tempusdominus/core` is triggering `'input'` events as it should :-)

**Comment by William-H-M** [comment]
Hi, @marcandre do you mind if you can confirm me something?
In this fiddle https://jsfiddle.net/William_/20oywuno/ and pasting this code does the problem still appears? The one that it doesn't trigger is `change` event for what I said before

```
$('#myDatepicker').datetimepicker();
$('#myDatepicker').on('input', function() {
  alert("Hey there :)")
});
```

**Comment by marcandre** [comment]
@William-H-M Doesn't work from your fiddle. But from the official one of BS4 (https://jsfiddle.net/Eonasdan/agbkdzhv/ ), it does work as it should.
