### ISSUE TITLE
How to get value programmatically on date selected?

### ISSUE THREAD

**Issue by neeilya** [Eonasdan/bootstrap-datetimepicker#1847]
Hello!
I am trying to get updated value after user choses date or closes the popup.

In jquery ui they provide [onSelect option](https://api.jqueryui.com/datepicker/#option-onSelect)
which allows to bind event handler with value argument.

Is there any similar option?
---

P.s. I've read _Events_ section in documentation, but I am not sure if they are
appropriate and how to subscribe for example to dp.change() event.

Could you please provide quick example?
Thanks!

**Comment by cervengoc** [comment]
It should work like this.

```
$('editor').on('dp.change', function(e) {
  var date = !e.date ? null : e.date.toDate();
});
```

Note that `e.date` is falsey or a moment instance, hence you have to call `toDate()` to get the javascript `Date` instance.
