### ISSUE TITLE
Allow multiple min/maxDate ranges

### ISSUE THREAD

**Issue by michaelzangl** [Eonasdan/bootstrap-datetimepicker#1848]
I want to allow multiple min/max date ranges.

Currently, I have the ranges in an array like:
[[min1, max1], [min2, max2], ...]

There are only a few ranges but I want the user to only select dates in any of those ranges. Is there any way to do this using the existing code?

**Comment by cervengoc** [comment]
I guess you can do the validation in the `dp.change` event.

```
var minMaxDates = [...];
var widget: any = $("#editor").data("DateTimePicker");
$("#editor").on("dp.change", function(evt) {
  if (!evt.date) return;
  var dateObj = evt.date.toDate();
  for (var i=0;i<minMaxDates.length;++i) {
    if (dateObj < minMaxDates[i][0] || dateObj > minMaxDates[i][1]) {
      alert("Invalid date");
      widget.date(evt.oldDate);
    }
  }
});
```

Note that this is just a sample code, not tested in any ways.

**Comment by michaelzangl** [comment]
I have a separate validation plugin and the validation is done on server side as well.

**Comment by cervengoc** [comment]
Ok, just wanted to give a tip for editing-time validation. Server-side validation is still required of course, and that's another thing.

**Comment by michaelzangl** [comment]
Worked around this one. Used #1859 to add a custom validator and fix the decade filter for it.
