### ISSUE TITLE
Version 4.17.42 After closed, view mode will go back to days mode

### ISSUE THREAD

**Issue by datwsui** [Eonasdan/bootstrap-datetimepicker#1850]
In line 936, Version 4.17.42, there is `currentViewMode = 0;`
As a result, after closed, view mode will go back to days mode

**Comment by gfaramaz** [comment]
Thanks, I've been searching the source of this bug !

**Comment by mvpkenlin** [comment]
4.17.43 still have the same code. Is it just remove this code and then it will be fixed?

**Comment by datwsui** [comment]
Yes. I'm using 4.17.42. Just comment out `currentViewMode = 0;`

**Comment by mvpkenlin** [comment]
Yes, it works too after I comment it.

**Comment by bobinthomas** [comment]
Yes. I'm using 4.17.43. commenting out currentViewMode = 0; did not work for me

**Comment by hunzaboy** [comment]
.43, still have the same issue.

**Comment by interist32** [comment]
+1 for .43

**Comment by William-H-M** [comment]
Hi, this was solved on latest version.
https://jsfiddle.net/William_/ja6v6x2x/
