### ISSUE TITLE
Disable dates before current/today's date

### ISSUE THREAD

**Issue by rpundlik** [Eonasdan/bootstrap-datetimepicker#1858]
Hi,

I have implemented datetimepicker as follows

`$('#txtStartDate').datetimepicker({ useCurrent: false, locale: _defaultCulture[0], format: 'L' });`
`$('#txtEndDate').datetimepicker({ useCurrent: false, locale: _defaultCulture[0], format: 'L' });`

Can anyone tell how can I disable date before to current/today's date ?

Thanks for the help !

**Comment by Eonasdan** [comment]
try reading the docs: http://eonasdan.github.io/bootstrap-datetimepicker/Options/#mindate
