### ISSUE TITLE
useCurrent changed behaviour between 4.17.37 and 4.17.43

### ISSUE THREAD

**Issue by benr77** [Eonasdan/bootstrap-datetimepicker#1860]
Behaviour between 4.17.37 and 4.17.43 has changed with respect to the _useCurrent_ setting.

Initialise with default options:

```
$('.my-date-field').datetimepicker();
```

With version 4.17.37, if I have the datepicker on a form field with no value, the datepicker leaves the form field blank on page load. Clicking the field opens the datepicker, with the current date selected.

With version 4.17.43, if I have the datepicker on a form field with no value, the datepicker POPULATES the form field on page load with the current date. Please not this is NOT when I click the field to open the date picker - it populates the field on page load. Surely this is not the intended behaviour?

I can fix this with 4.17.43 by setting `useCurrent: false` but this then leads to a secondary issue whereby when I do click on the datepicker it has no default date set.

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.
