### ISSUE TITLE
The newest Version has problem but v4.15.35 which is using on http://eonasdan.github.io/bootstrap-datetimepicker/ don't have the problem

### ISSUE THREAD

**Issue by blankzust** [Eonasdan/bootstrap-datetimepicker#1865]
I downloaded the js in http://eonasdan.github.io/bootstrap-datetimepicker/#min-view-mode, And I find it different with **v4.17.43**

_difference_
There is a difference in the code when hiding the model.
**v4.17.43**
```
hide = function () {
                ......
                input.blur();

                currentViewMode = 0;
                viewDate = date.clone();

                return picker;
            },
```
**Document's**
```
hide = function () {
                ......
                input.blur();

                return picker;
            },
```
I am confused why currentViewMode should be set to 0 when hiding.
The mode will be always chosing day If the currentViewMode'value is 0
![image](https://cloud.githubusercontent.com/assets/8541906/19918360/6f2e6c12-a105-11e6-9e52-6fc043854401.png)
My code is 
```
$(document.getElementById('test')).datetimepicker({
        viewMode: 'years',
        format: 'YYYY'
      });
```
The currentViewMode will be 0 when I click secondly because hide() will make it 0.
```
showMode = function (dir) {
                if (!widget) {
                    return;
                }
                if (dir) {
                    currentViewMode = Math.max(minViewModeNumber, Math.min(3, currentViewMode + dir));
                }
                widget.find('.datepicker > div').hide().filter('.datepicker-' + datePickerModes[currentViewMode].clsName).show();
            },
```

**Comment by blankzust** [comment]
I was confusing my usage about it because the document told me that v4.17.42 is the current stable release. And my problem is not exsted on the http://eonasdan.github.io/bootstrap-datetimepicker/ .I need help

**Comment by blankzust** [comment]
Should I use the old version?Or there is some suggestion to solve the problem?

**Comment by DominoDev** [comment]
there is a work around for this issue discussed in issue [#1894](https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1894)

**Comment by pascal-hofmann** [comment]
Duplicate of #1854.

**Comment by blankzust** [comment]
Good.The problem is fixed
