### ISSUE TITLE
Set max view mode

### ISSUE THREAD

**Issue by natashawylie** [Eonasdan/bootstrap-datetimepicker#1871]
Hi,

It would be great if the max view mode could be set. I do not wish my calendar to go back past years so would like to disable centuries and decades.

The main reason for this is when I go back to centuries there are no clickable options meaning the user has to refresh the browser to get back to days again. I have the calendar set to only enable certain dates which is possibly causing a odd little bug.

I hope this is something that can be added as soon as possible. In the mean time I can try and add it in a pull request if I can.

Cheers,

Natasha

**Comment by RodrigoFlorex** [comment]
Same problem here, if you set a min/max date not exceeding a year and go to the century view mode, you will not be able to go back to other view mode.
![temp](https://cloud.githubusercontent.com/assets/13855786/20060543/744ed938-a4da-11e6-8144-022b42c77d82.png)

**Comment by martintern** [comment]
I would also like to set something like {maxViewMode: 'days'} to disable clicking on `Select Month`, while still allowing to navigate the months through the arrow keys.
