### ISSUE TITLE
How change format to timestamp?

### ISSUE THREAD

**Issue by rjgamer** [Eonasdan/bootstrap-datetimepicker#1877]
Hi,

this is my code:
`$('.datetimepicker2').datetimepicker({
   language: 'de',
   format: 'MMMM Y'
});`

With this code I get a nice formatted date like "Januar 2016" (yes in german). But I need the timestamp of this date after I submitted the form. Is there any solution to get the timestamp on submit and not the localized and formatted date in the input form (this is for the user only)?

Thanks,
rjgamer

**Comment by bukowskiadam** [comment]
Have you solved your issue? I'm looking for something similar.
