### ISSUE TITLE
Bug with locale

### ISSUE THREAD

**Issue by ltduc** [Eonasdan/bootstrap-datetimepicker#1881]
Dear Team,

I use lib v4.17.43
My code is:
dpThoiGianDen.datetimepicker({
        format: "DD/MM/YYYY HH:mm",
        locale: "vi",
        defaultDate: new Date()
})

Run ok, but when try type change Time(<> time current) then I open popup to change Date.
Result Time set time current.

Pre version is ok: http://jsfiddle.net/RR4hw/7/

Please, help me!

**Comment by William-H-M** [comment]
Wrong picker anyways http://tarruda.github.io/bootstrap-datetimepicker/
