### ISSUE TITLE
Key events stops working when ESC pressed

### ISSUE THREAD

**Issue by rlukacik** [Eonasdan/bootstrap-datetimepicker#1883]
When datetimepicker is shown and user press ESC key, the picker is closed but the "keyup" event not raised. So the "keyMap" object still refer that the ESC key is still pressed (not released).
I'm just did a small fix, clear the keyMap object when the key is not the control key inside the "keydown" event.

            keydown = function (e) {
                var handler = null,
                    index,
                    index2,
                    pressedKeys = [],
                    pressedModifiers = {},
                    currentKey = e.which,
                    keyBindKeys,
                    allModifiersPressed,
                    pressed = 'p';

                keyState[currentKey] = pressed;

                for (index in keyState) {
                    if (keyState.hasOwnProperty(index) && keyState[index] === pressed) {
                        pressedKeys.push(index);
                        if (parseInt(index, 10) !== currentKey) {
                            pressedModifiers[index] = true;
                        }
                    }
                }

                for (index in options.keyBinds) {
                    if (options.keyBinds.hasOwnProperty(index) && typeof (options.keyBinds[index]) === 'function') {
                        keyBindKeys = index.split(' ');
                        if (keyBindKeys.length === pressedKeys.length && keyMap[currentKey] === keyBindKeys[keyBindKeys.length - 1]) {
                            allModifiersPressed = true;
                            for (index2 = keyBindKeys.length - 2; index2 >= 0; index2--) {
                                if (!(keyMap[keyBindKeys[index2]] in pressedModifiers)) {
                                    allModifiersPressed = false;
                                    break;
                                }
                            }
                            if (allModifiersPressed) {
                                handler = options.keyBinds[index];
                                break;
                            }
                        }
                    }
                }

                if (currentKey !== 17) {
                    keyState = {};
                }

                if (handler) {
                    handler.call(picker, widget);
                    e.stopPropagation();
                    e.preventDefault();
                }
            },

**Comment by wvary** [comment]
@rlukacik I see this issue and will implement some settings to prevent it.  You should create a PR if this solution works.

**Comment by stgenov** [comment]
Same problem with selecting the value from the picker with enter - after that the keyBinds don't work anymore.
