### ISSUE TITLE
Show time by default

### ISSUE THREAD

**Issue by jLynx** [Eonasdan/bootstrap-datetimepicker#1888]
Is there a way to show the time by default and still be able to access the date?

**Comment by rarumberger** [comment]
I came up with the following workaround (note that I'm using v3 in a legacy project):

```
$(".date").datetimepicker().each(function () {
    $(this).data("DateTimePicker").widget.find(".picker-switch a.btn").click();
});
```

It targets the view switch button and pre-clicks it, setting the time icon (if you're using icons) and setting the view to time before it's shown the first time. It would be nice if this was an option you could just set, but the workaround seems to be working nicely. I'm not sure what changes need to be made for the latest version.
