### ISSUE TITLE
The values of datetime picker is not showing in input box when it is initialized, after using clear() method.

### ISSUE THREAD

**Issue by SanthoshArya** [Eonasdan/bootstrap-datetimepicker#1889]
When second time focus event happens on input field after usage of clear() the datetime picker is visible but the value is not getting displayed in input field.

`<input type='text' id='datetime'>`

on focus event the datetime picker is initialized.

```
'focus #datetime': function() {
                             $('#datetime').datetimepicker({
                             format: "YYYY-MM-DD HH:mm",
                             minDate: new Date(),
                             keyBinds: "up"
                           });

```
Below code is to clear datetime picker values .

```
f($('#datetime').val().length > 0) {
        $('#datetime').data("DateTimePicker").clear();
    }
```

**Comment by William-H-M** [comment]
Hi, you must destroy the picker after cleaning, because the you're reataching datepicker agin over the same element so add
f($('#datetime').val().length > 0) {
        $('#datetime').data("DateTimePicker").clear();
        $('#datetime').data("DateTimePicker").destroy();
    }
