### ISSUE TITLE
End date should not be less than Start date

### ISSUE THREAD

**Issue by ketavc** [Eonasdan/bootstrap-datetimepicker#1890]
I'm using datetimepicker for two times in one form.  First for Start time and Second for End time.
I want second date should not less than first date.

Here is my code : 

`
$("#campaign_start_time").datetimepicker({
            format: 'yyyy-mm-dd hh:ii',
            autoclose: true,
            //startDate: new Date.UTC(),
            minuteStep: 5
        }); 
        $("#campaign_stop_time").datetimepicker({
            format: 'yyyy-mm-dd hh:ii',
            autoclose: true,
            //startDate: new Date.UTC(),
            minuteStep: 5
        });
`

**Comment by 888moe888** [comment]
I did this with a JS function onBlur() at the starttime-picker.

Just set the minDate of the stoptime-picker to the time the starttime has when you unselect it.
Like this:

$('#datetimepicker').data("DateTimePicker").minDate("date from starttime-picker");

**Comment by William-H-M** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers
