### ISSUE TITLE
Trigger dp.change on init

### ISSUE THREAD

**Issue by DaniloPolani** [Eonasdan/bootstrap-datetimepicker#1901]
Hello, 
I'm using the inline mode and I need the event "Dp.change" (with the date) on init. 
There's a way to do this? 

At this time, I call my function with the selection of the date of the datepicker, but maybe there will be timing issues.

Thank you 
Danilo

**Comment by ecuci** [comment]
Hi @DaniloPolani ;
I needed the same thing. Here is my solution with a sample:

```

var minDateValue = moment().add(30, 'minute'),
      maxDateValue = moment().add(1, 'year'),
      defaultDateValue = minDateValue;
        
$('#datetimepicker12').datetimepicker({
          locale: 'tr',
          inline: true,
          sideBySide: true,
          minDate: minDateValue,
          maxDate: maxDateValue
});

$('#datetimepicker12').on('dp.update', function(event) {
        // what i did in dp.change but instead of event.date I used event.viewDate
       console.log( event.viewDate.format('DD/MM/YYYY HH:mm') );
});

$('#datetimepicker12').data("DateTimePicker").viewDate(defaultDateValue);

```

I used **viewDate(...)** because I've found out that it fires **dp.update**
but dp.update 's event doesn't have **date** so I needed to use **event.viewDate** instead. 

Hope it helps.

Best regards,
Ece
