### ISSUE TITLE
Can't see dates only time (jQuery 3 only)

### ISSUE THREAD

**Issue by St1fle** [Eonasdan/bootstrap-datetimepicker#1902]
As I started transitioning to jQuery 3 I noticed that the date pickers stopped working. 

When I click on a datepicker I see this:
![Bad display](http://i.imgur.com/bOWO9BI.png)

If I click on the time icon, I can swap to time, it transitions correctly, and I see the time fine (except I think the icon is supposed to be at the bottom?):
![Time is fine](http://i.imgur.com/2xWWYC6.png)

If I click back everything is still short like it was on the first picture. If I swap to jQuery 2.2.4 it works just fine so I have no idea what to do about this situation. I thought it could be related to this #1657 but I tried applying these changes and it did nothing.

Help please!

**Comment by poulpo** [comment]
Hi,
As mentioned in #1765 you can temporarily add
`div.datepicker > div { display: block; }`
until the issue is fixed.

**Comment by St1fle** [comment]
Hi @poulpo !

Thank you so much, this piece of code has seemed to fix the issue for the time being!
