### ISSUE TITLE
When using a linked datetimepickers, selecting date changes the time to current time

### ISSUE THREAD

**Issue by malhayek2014** [Eonasdan/bootstrap-datetimepicker#1906]
I have two datetime pickers. When the page is loaded I set the first one to the start of the dat "ie. Today 12:00 AM" and the second one to the end of the day "ie. Today 11:59 PM"

When I change the date on the second picker, the time also changes to current time. I don't expect the time to change because I set `useCurrent: false`

Here is a fiddler with the issue. http://jsfiddle.net/0Ltv25o8/4120/

**Comment by outshyn** [comment]
Duplicate here: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1884
