### ISSUE TITLE
Calendar dropdown picker is invalid under localized "zh"

### ISSUE THREAD

**Issue by hexd-moshi** [Eonasdan/bootstrap-datetimepicker#1907]
Calendar dropdown picker is invalid under localized "zh", but it is Ok under localized "zh_CN"

![image](https://cloud.githubusercontent.com/assets/22312976/20737626/d95eecf8-b6e8-11e6-901c-5bd31e00efe0.png)

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.

**Comment by hexd-moshi** [comment]
Thanks for your quick response.
Here is the jsfiddle for your reference, thanks

$('#datetimepicker1').datetimepicker({locale:"zh"});

**Comment by Eonasdan** [comment]
That's not a fiddle. That's pasted code.

If you'd look at the dev console in your browser you would see the error telling you what's wrong:
![image](https://cloud.githubusercontent.com/assets/1006516/20797087/5f83169c-b7a7-11e6-83f0-953b69146d88.png)

`zh` is not a valid locale from moment
