### ISSUE TITLE
Add an option to disable days from previous/next month

### ISSUE THREAD

**Issue by KnpA** [Eonasdan/bootstrap-datetimepicker#1909]
I don't want users to see days from previous/next month, it's confusing
I found a solution on stackoverflow and modified it a bit:
```
.bootstrap-datetimepicker-widget table tr td.new { display: none; }
.bootstrap-datetimepicker-widget table tr td.old { visibility: hidden; } 
```
It works but it's not really an "acceptable" solution because it still create previous/next month days.

And with the calendarWeeks option, it's bad:
![calendarweek](https://cloud.githubusercontent.com/assets/6367927/20756055/976670ae-b711-11e6-983b-0c8ef7405cc8.png)

Is there a better solution ?

**Comment by William-H-M** [comment]
Hi, I’ll be closing issues that have been answered by the community.
