### ISSUE TITLE
event dp.change not fired

### ISSUE THREAD

**Issue by franckysolo** [Eonasdan/bootstrap-datetimepicker#1912]
hello,
thanks for this plugin
I'm using the picker in a vuejs project
the dp.change event is not fired with jquery 3.1.1
i test with 2.2.4 jquery , it's ok the event is fired
is there a trick to make it working with jquery 3?
This code work with 2.2.4 version but not with the 3.1.1
```js
....
 mounted () {
    let vm = this
    let options = { locale: 'fr', sideBySide: true, format: 'DD/MM/YYYY HH:mm:ss' }
    $('#dateStart').datetimepicker(options).on('dp.change', function (e) {
      window.alert('event is fired')
      vm.$nextTick(() => {
        let ds = $('#dateStart').val()
        vm.$set(vm.$data, 'dateStart', ds)
      })
    })
  }
...
```

**Comment by Eonasdan** [comment]
Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.

**Comment by franckysolo** [comment]
hello,
i have already test with two differents projects  i put it on git
the [first](https://github.com/franckysolo/vue-eonasdan-datetimepicker-01) example working with jquery2..4
the [second](https://github.com/franckysolo/vue-eonasdan-datetimepicker-02) with issue with jquery3.1.1
in this one, i can't get it worked with validator the event dp.change not triggered

**Comment by Jorisslagter** [comment]
Sadly I am having the same issue; but I cannot get my finger around the problem.

**Comment by Jorisslagter** [comment]
Ok I found out what the problem is. For some reason your component uses his own jQuery to fire the events to. In case of my project, I've got my own jQuery installed trough npm; that's the reason why in my code $ isn't able to listen to the events that is send to the other jQuery instance in you component. 

I fixed this for now by passing through my own jQuery instance as a second parameter 

```javascript

$.fn.datetimepicker = function (options, jquery) {
        return this.each(function () {
            if(jquery) {
                $ = jquery;
            }
            var $this = $(this);
            if (!$this.data('DateTimePicker')) {
                // create a private copy of the defaults object
                options = $.extend(true, {}, $.fn.datetimepicker.defaults, options);
                $this.data('DateTimePicker', dateTimePicker($this, options));
            }
        });
    };

    window.$.fn.datetimepicker = $.fn.datetimepicker;
```
