### ISSUE TITLE
from version 4.17.42 min view mode case not working correctly

### ISSUE THREAD

**Issue by akrom123** [Eonasdan/bootstrap-datetimepicker#1914]
you may compare minViewMode case
on version 4.17.37 https://codepen.io/anon/pen/WozpoY
and on version 4.17.42 https://codepen.io/anon/pen/KNoWqL

**Comment by DominoDev** [comment]
this looks like a duplicate of #[1894](https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1894)

**Comment by pascal-hofmann** [comment]
Which itself is a duplicate of #1854.
