### ISSUE TITLE
input value is always set to maxDate

### ISSUE THREAD

**Issue by lafeber** [Eonasdan/bootstrap-datetimepicker#1922]
The input value is set to maxDate, even when the value is before the maxDate.

Code:

    <div class="input-group date datetimepicker">
      <span class="input-group-addon">
        <span class="fa fa-calendar"></span>
      </span>
      <input class="form-control string date_picker optional" value="2016-10-10" data-date-options="{'locale':'en','format':'YYYY-MM-DD','dayViewHeaderFormat':'MMMM YYYY','minDate':'2016-10-09','maxDate':'2016-10-19'}" placeholder="jjjj-mm-dd" type="text" name="startdate" id="startdate">
    </div>

call: `$('.datetimepicker').datetimepicker();`

The value was set to "2016-10-19", while it should have been "2016-10-10"
I've hacked around this with the following code:

`  $('input.date_picker').each(function(el) {
    $(this).val($(this).attr('value'));
  });
`

But I hope this can be fixed. (datetimepicker version 4.17.42)

**Comment by aalho** [comment]
Noticed the same behaviour.

I do believe that this has something to do with having your current date beign greater than the maxDate value.

For example:
current date is march 6, 2017.
maxDate -option is set to december 31, 2016.
Value set to the input is december 22, 2016.

When the page is loaded and datetimepicker is initialized, the UI shows a value of december 31, 2016. When inspecting the element value is correct: december 22, 2016.

As a work-around do the following: Set the useCurrent -option to false, So there must be a bug where current date is greater than maxDate AND useCurrent is set to true.
