### ISSUE TITLE
Click calendar icon twice to show selected date

### ISSUE THREAD

**Issue by jamison187** [Eonasdan/bootstrap-datetimepicker#1931]
I have an issue where I have to click the calendar icon twice in order for the datetimepicker to recognize the date provided from my model. In other words, my model provides the input field with '08/18/2016' but the first time I click on the calendar icon to select a date from the datetimepicker, December 2016 is displayed instead of August 2016. When I click outside of the datetimepicker (to close it) and then click the calendar icon to open it again, August 2016 is selected as expected. It works every time after. I cannot figure out how to fix it. I have tried this but it does not work:
var dt = new Date($('#dtinput').val());
 $('#datetimepicker').datetimepicker({
        allowInputToggle: true,
        ignoreReadonly: true,
        format: 'L',
        showTodayButton: true
    }).on('dp.show', function () {
         $(this).data("DateTimePicker").date(moment(dt).format('L'));
    });

**Comment by StevenDevooght** [comment]
We have the same issue. I created a [fiddle](http://jsfiddle.net/jv8n283d/) to reproduce it.

**Comment by jamison187** [comment]
Any updates or anyone looking into this?

**Comment by William-H-M** [comment]
For those still having this issue the problem was solved on version [4.17.45](https://github.com/Eonasdan/bootstrap-datetimepicker/releases/tag/v4.17.45) just update library and it's done tested with same [Fiddle ](http://jsfiddle.net/jv8n283d/) different [version ](http://jsfiddle.net/0ujbt71p/)

**Comment by jamison187** [comment]
Thank you! Works great now!
