### ISSUE TITLE
Set a different date format for the value displayed and submitted :

### ISSUE THREAD

**Issue by fas3r** [Eonasdan/bootstrap-datetimepicker#1932]
Hello, 

Is it possible to set a different date format for the value displayed and submitted. 

After the date is picked up from the datepicker, I would like to show the date with the format: "dddd, MMMM Do YYYY" .

But when the form is submitted I would like to have the date with the format : "MM/DD/YYYY".

Can I do it directly with datetimepicker ? Or I need to parse the input before submitting my form and change the format of the date ?

Thanks.

**Comment by wonderer007** [comment]
I am also looking for same solution

**Comment by William-H-M** [comment]
You will need to parse the input before send it, do it with moment.format()
and for the way the fomat is show on input just set the option:

   format: 'dddd, MMMM Do YYYY

**Comment by fas3r** [comment]
hello,

OK, I did that. 

Thanks and happy new year !
