### ISSUE TITLE
viewDate not updated when setValue called

### ISSUE THREAD

**Issue by hitok** [Eonasdan/bootstrap-datetimepicker#1933]
line 871: //viewDate = date.clone(); // TODO this doesn't work right on first use

**Comment by bevinhex** [comment]
It is not about that,
adding `update()` after notifyEvent({type:'dp.change',date:false,oldDate:oldDate}); fixed the problem, please someone merge it
![image](https://cloud.githubusercontent.com/assets/9736688/24003090/cf80a96a-0a62-11e7-8479-6aee04725428.png)
