### ISSUE TITLE
Regression: Selecting day outside of current month no longer changes month

### ISSUE THREAD

**Issue by ngandhy** [Eonasdan/bootstrap-datetimepicker#1936]
Hi all,
  Between versions 4.15.35 and 4.17.43 the widget stopped changing months to reflect the the date selected. 

Repro:
1) Load up calendar
2) Click on a day from the previous or next month (should be slightly grayed out)
3) Notice the date selects, but the month does that change at the top to reflect the new date.

Expected:
Month would change to reflect the new selected date (as it previously worked). This *does* work on http://eonasdan.github.io/bootstrap-datetimepicker/ as it has an older js file imported (4.15.35).

Thanks for your help and your awesome widget!

**Comment by ngandhy** [comment]
@William-H-M - was this solved

**Comment by William-H-M** [comment]
Hi, @ngandhy it does for me on latest version could you check, thanks.
https://jsfiddle.net/William_/20oywuno/

**Comment by ngandhy** [comment]
Works for me! Thanks!
