### ISSUE TITLE
datetimepicker generating strange static month number

### ISSUE THREAD

**Issue by iyunusov** [Eonasdan/bootstrap-datetimepicker#1938]
When I choose date, calendar picking day and year fine but generating some strange number like '54' for month, where month value shouldn't be greater than 12, even after choosing different month previously generated number is not changing.

I've made a [fiddle](https://jsfiddle.net/uxoysa0y/) in which the issue is the same as mentioned above.

**Comment by niborg** [comment]
You were probably getting the "54" on the 54th minute of the hour. You need to use [moment.js formats](http://momentjs.com/docs/#/displaying/format/). See also [this](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#format).

[Updated fiddle.](https://jsfiddle.net/0u3bky52/)

**Comment by iyunusov** [comment]
@niborg Thanks for update, it seems I was supposed to use `dd/MM/yyyy` instead of `dd/mm/yyyy`.

**Comment by niborg** [comment]
no problem @iyunusov -- want to close this issue then?
