### ISSUE TITLE
dp.change event not firing

### ISSUE THREAD

**Issue by fake-fur** [Eonasdan/bootstrap-datetimepicker#1940]
hi 

i copied the code from your docs but the change events are not being fired - any reason you can think of that might cause this?

thanks
:)

**Comment by joseshiru** [comment]
Hi, same is happening here.

Any possible idea?

Thanks

**Comment by fake-fur** [comment]
i've tried everything i can think of but no luck - not sure if it's an incompatibility with new jquery or moment or a bug in the datetime picker itself

hoping for some progress toward a fix soon or i have to dump this and use something else

**Comment by Gnative** [comment]
I'm getting this as well.. it seems to be that on line 483 that the date and old date are the same and its not firing the event.

` if (e.type === 'dp.change' && ((e.date && e.date.isSame(e.oldDate)) || (!e.date && !e.oldDate))) `

it seems that 'unset' online 861 is always false so its making the oldDate always equal to the new date. 

`var oldDate = unset ? null : date;`

dp.change will never be fired.

I'm investigating more.

**Comment by fake-fur** [comment]
so the event comes from the datetimepicker *within* the element?
*slaps head*
thanks i will try this

**Comment by Nerian** [comment]
@fake-fur I added the HTML code to the example, in case you want to compare.

It shouldn't be relevant but, in my case I am using `input-group-btn` instead of `input-group-addon` – I edited the datepicker js file to support this.

**Comment by fake-fur** [comment]
thanks will try later when home from office :)

**Comment by warrickbayman** [comment]
Trying to attach to an input. I cannot get this to work.

```javascript
$('input[name="start-date"],input[name="end-date"]').datetimepicker({
    format: 'DD MMMM YYYY'
}).on('dp.change', function(e) {
    console.log('changed');
});
```

**Comment by Gnative** [comment]
I found if I used the most recent release 4.17.46 it is working. 
Also try attaching to the input with an ID.

**Comment by warrickbayman** [comment]
@Gnative Thanks. Am on the latest version, and tried with IDs, but still no luck.

**Comment by joseshiru** [comment]
Hi, actually seems like this issue was happening in the latest version.

My code was working fine with the older version but it just stopped working after updating the plugin.

I workaround that I found in order to trigger the change event was setting a new date (could be the same as the initial one) by using the function `.date()`

Note: you should call it after the datepicker is initialized.

It's not an elegant solution but so far I didn't found any other way.

**Comment by lasseal** [comment]
Using jQuery v2 instead of v3 "fixes" this for me.

**Comment by arcontact** [comment]
This **not** work:
```
$('.date').on("dp.change", function(e){
	//doesnt work
});
```
This work:
```
$('.parent_div').on("dp.change", '.date', function(e){
	//works
});
```

**Comment by lasseal** [comment]
Does #1942 (included in v4.17.47) fix this?

**Comment by jhenriquez** [comment]
@lasseal This is happening to me as well, I'm on 4.17.47 but my JQuery is is an oldy, 1.12. Maybe upgrading to JQuery v2? Did you have any luck solving this?

**Comment by lasseal** [comment]
```
"eonasdan-bootstrap-datetimepicker": "^4.17.47",
"jquery": "^3.1.1"
```

Works like a charm together.

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.

**Comment by Goodmedalist** [comment]
In my case the dp.change event was not firing because the dp.error event fires instead. When the dp.error event fires, the dp.change event does not fire at all.

**Comment by kamleshwebtech** [comment]
I am using bootstrap datetime picker. After doing lots of research, below code works for me:

    $('.data_date_of_birth').on('changeDate', function(event) {
      alert($(this).val());
    });
