### ISSUE TITLE
Add jQuery 3 in package.json

### ISSUE THREAD

**Issue by ssipos90** [Eonasdan/bootstrap-datetimepicker#1942]
Please add jquery `|| ^3.0` as a dependency in packages.json.

**Comment by asyndesis** [comment]
`npm ERR! peer invalid: jquery@^1.8.3 || ^2.0, required by eonasdan-bootstrap-datetimepicker@4.17.45`

👍

**Comment by happycat6323** [comment]
Please ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by lasseal** [comment]
`npm shrinkwrap` doesn't work without due to: `npm ERR! peer invalid: jquery@^1.8.3 || ^2.0, required by eonasdan-bootstrap-datetimepicker@4.17.45`.  Please do add jQuery `|| ^3.0` as a dependency in packages.json.

**Comment by numanWD** [comment]
+1

**Comment by macolo** [comment]
*ping*

**Comment by ankurk91** [comment]
@Eonasdan 
It seems like jQuery 3 is already in [package.json](https://github.com/Eonasdan/bootstrap-datetimepicker/commit/6b1f49adefa6dd42b27152a807a2eb5a21cb2ead) but it was not published on [npm](https://www.npmjs.com/package/eonasdan-bootstrap-datetimepicker),
```
npm install eonasdan-bootstrap-datetimepicker@4.17.46
```
Gives this warning message 
```
+-- eonasdan-bootstrap-datetimepicker@4.17.46 
`-- UNMET PEER DEPENDENCY jquery@3.1.1

npm WARN eonasdan-bootstrap-datetimepicker@4.17.46 requires a peer of jquery@^1.8.3 || ^2.0 but none was installed.
```
When i look into my project ```node_modules/eonasdan-bootstrap-datetimepicker/package.json``` i found this -
```json
"dependencies": {
    "bootstrap": "^3.3",
    "jquery": "^1.8.3 || ^2.0",
    "moment": "^2.10",
    "moment-timezone": "^0.4.0"
  },
```
I don't know your how release on npm works. But only you (owner of this repo) can fix it.

**Comment by asyndesis** [comment]
We ended up cloning the repo and changing it in our branch until it's fixed.  Doesn't seem to be any errors using jQuery 3.0.

**Comment by Eonasdan** [comment]
there

**Comment by lasseal** [comment]
Great! Thank you so much for closing this issue and keeping the package alive.
