### ISSUE TITLE
Update Packagist

### ISSUE THREAD

**Issue by oznorts** [Eonasdan/bootstrap-datetimepicker#1949]
Packagist still shows 4.17.42 as the current version, which is incorrect.  Please update ASAP.

**Comment by hackel** [comment]
Packagist is for PHP packages.  This shouldn't even be included there.  Use Bower or Yarn (NPM).

**Comment by oznorts** [comment]
If that's true @hackel, then the composer.json file should be removed.

**Comment by Eonasdan** [comment]
"Once you entered your public repository URL in there, your package will be automatically crawled periodically. You just have to make sure you keep the composer.json file up to date."
