### ISSUE TITLE
Clear only Time

### ISSUE THREAD

**Issue by renebrain** [Eonasdan/bootstrap-datetimepicker#1956]
Is it possible to clear only the time or make the time picker optional in the datetimepicker plugin?

Is there also any possibilty to listen on the clear of the calender? (Okay, the dp.change is triggered on it aswell, that's fine. i am still interested in the first question though ^^)

**Comment by William-H-M** [comment]
Mmmm if you mean with "make the time picker optional" you can actually do it with the format option
format: 'YYYY-MM-DD' ; 
you just have to use it without the hours that will do that the plugin doesn't show the time picker and you can do the same for just use the time picker with:

format: 'HH:mm'

and of the clear just time I think you can do it with setting time hours with moment to 00:00
