### ISSUE TITLE
exist autoclose option after of selected date?

### ISSUE THREAD

**Issue by oscarruz** [Eonasdan/bootstrap-datetimepicker#1961]
Hello,

I've not found the option to autoclose the form after of selected date? Do it exist?

Thanks in advance :)

**Comment by William-H-M** [comment]
Hey, yes it does exist the option is
It's setted by default but just if you're selecting dates if in your format you have hours then it won't auto close, so for do it just set the format without hours like i.e
 format: 'YYYY-MM-DD' ; In that way the picker will close automatically
 format: 'YYYY-MM-DD hh:mm a', ; In this way the picker won't close automatically
