### ISSUE TITLE
bower error in packages

### ISSUE THREAD

**Issue by publicocean0** [Eonasdan/bootstrap-datetimepicker#1974]
bower                                                  ENOTFOUND Package v4.7.45 not found

**Comment by publicocean0** [comment]
did you tag correctly git source?

**Comment by susiko** [comment]
I have the same problem, but if you install with:"bower install eonasdan-bootstrap-datetimepicker#latest --save", the package is ok and work. I see that the version of package has a caret before: "eonasdan-bootstrap-datetimepicker": "^4.17.45", instead of "4.17.45".  I dont'know why....
