### ISSUE TITLE
Overwrite one date in daysOfWeekDisabled array.

### ISSUE THREAD

**Issue by alidzen** [Eonasdan/bootstrap-datetimepicker#1975]
Hi, 
I'm using datepicker for booking tables in restaurant. Here is example: http://jsfiddle.net/u8pc8bo7/1/

How can I enable exception day, when normally restaurant closed and I need to open it for the exact day? For example: we have restaurants that are normally closed on Tuesday, but on Tuesday Feb 14th they will be opened and need to accept reservations.

**Comment by un-matthewdavis** [comment]
@alidzen Did you find a solution to this issue? I've got the same problem.

**Comment by alidzen** [comment]
@un-matthewdavis Yes, i'm using disabledDates options for this. And i changed isValid function  
`if (options.disabledDates && granularity === 'd' && isInDisabledDates(targetMoment)) {
                    return false;
                }` to return true;
It's a hack, but in my case work well.
