### ISSUE TITLE
setting a maxDate value as a option overwrites the value when the field is bound to a .net mvc Model

### ISSUE THREAD

**Issue by mawarnes** [Eonasdan/bootstrap-datetimepicker#1980]
In the .net MVC view there is a datetimepicker bound to a field in the Model as follow

```
<div class='input-group date' id='datetimepicker1'>
                    @Html.TextBoxFor(m => m.DOB, new { @class = "form-control",@type="text" })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
</div>
```

If the maxDate is set in the constructor, as follows, it overwrites the value bound from the model

```
    $(function () {
        $('#datetimepicker1').datetimepicker({
            maxDate: moment().subtract(18, 'years'),
            minDate: moment().subtract(65, 'years'),
            format: 'DD/MM/YYYY',
            viewMode: 'years'
        });
    });
```

however if it is set after the constructor using maxDate and minDate functions(as follows) it works as expected

```
    $(function () {
        $('#datetimepicker1').datetimepicker({
            //maxDate: moment().subtract(18, 'years'),
            //minDate: moment().subtract(65, 'years'),
            format: 'DD/MM/YYYY',
            viewMode: 'years'
        });

        $('#datetimepicker1').data("DateTimePicker").maxDate(moment().subtract(18, 'years'));
        $('#datetimepicker1').data("DateTimePicker").minDate(moment().subtract(65, 'years'));
   });
```

I have tried to pick through the source to locate the cause, but my javascript skills are obviously not up to the challenge....yet, sorry!!, will keep looking though. Could it be some kind of timing issue to do with the way the model is bound to the control by .net MVC?

**Comment by William-H-M** [comment]
On the contructor set `useCurrent: true`, this will avoid that the current value on the textbox being overwrited this had happend to me with WebForms and that and setting the option after constructor, that's not that bad tbh, is the only way I've solved 

[Here's](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#usecurrent) a document of the useCurrent option
