### ISSUE TITLE
How to set up the datepicker read-only

### ISSUE THREAD

**Issue by chabai** [Eonasdan/bootstrap-datetimepicker#1988]

**Comment by William-H-M** [comment]
So....what you mean? any description of what are you trying...?
In the doc there's something called [IgnoreReadOnly](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#ignorereadonly)
and here a JSfiddle http://jsfiddle.net/Eonasdan/0y0bofoa/

Close this as is a "How to.." and not a valid question
