### ISSUE TITLE
left right arrow keys don't work if custom formats chosen

### ISSUE THREAD

**Issue by pavarnos** [Eonasdan/bootstrap-datetimepicker#1989]
To reproduce. Go to
http://eonasdan.github.io/bootstrap-datetimepicker/
in the Custom Formats demo box enter the text `10:30`
press the left arrow key. The cursor does not move one character left as expected.

I think the issue may be in the keydown function: it searches for a handler function for each key type. If found, it stops propagation. Perhaps a fix would be to return truthy if handled, falsy if not then change

```
if (handler) {
    handler.call(picker, widget);
    e.stopPropagation();
    e.preventDefault();
}
```
to
```
if (handler && handler.call(picker, widget)) {
    e.stopPropagation();
    e.preventDefault();
}
```

**Comment by ariacom** [comment]
this fix seems to work, thanks.
