### ISSUE TITLE
Problem with bootstrap 4.0 alpha 6

### ISSUE THREAD

**Issue by LaySoft** [Eonasdan/bootstrap-datetimepicker#1996]
With bootstrap 4.0 alpha 6, if i set format to 'YYYY-MM-DD HH:mm', only the time part appears, date part not. In bootstrap 4.0 alpha 5, everything ok.

**Comment by 1nivas** [comment]
Why it is broke only in alpha 6, is there any quick fix anyone found to make it work

**Comment by Er-Kalpesh** [comment]
any temporary workaround for this ?

**Comment by TommyDool** [comment]
alpha 6 has replaced collapse in with collapse show.


Quick and dirty, but the following changes should work:

getTemplate:

                if (hasDate()) {
                    content.append($('<li>').addClass((options.collapse && hasTime() ? 'collapse in' : '')).append(dateView));

Change to:

                if (hasDate()) {
                    content.append($('<li>').addClass((options.collapse && hasTime() ? 'collapse show' : '')).append(dateView));
                }

togglePicker:

                        expanded = $parent.find('.in'),
                        closed = $parent.find('.collapse:not(.in)'),
.....

                        } else { // otherwise just toggle in class on the two views
                            expanded.removeClass('in');
                            closed.addClass('in');

Change to:

                        expanded = $parent.find('.show'),
                        closed = $parent.find('.collapse:not(.show)'),

.....

                        } else { // otherwise just toggle in class on the two views
                            expanded.removeClass('show');
                            closed.addClass('show');

**Comment by LaySoft** [comment]
Thank you, it works!

**Comment by sr9yar** [comment]
Thank you, @TommyDool

**Comment by midhunadarvin** [comment]
Is this fix merged to master ?

**Comment by William-H-M** [comment]
@midhunadarvin Hi quoting what @Eonasdan said on #1377 

> instead of forking this repo and trying to keep it update for bootstrap 4, you could help and contribute to https://github.com/tempusdominus/bootstrap-4

So no, this isn't gonna be merge to main is this is not the repor for BS4 it's mainly for BS3

**Comment by tnqsoft** [comment]
@TommyDool: Thanks you very much. Save my time.

**Comment by William-H-M** [comment]
@Eonasdan should this be close/lock as
1) Looks like solved
2) This widget is not developed for BS4, you have https://github.com/tempusdominus/bootstrap-4 for that
3) BS4 it's currently still on alpha so many things will change, probably, as happened between alpha 4 and alpha 6
