### ISSUE TITLE
defaultDate not highlighting date in picker

### ISSUE THREAD

**Issue by warrenAR** [Eonasdan/bootstrap-datetimepicker#2000]
When  I use defaultDate (with the following code):
```
$('.datetimepicker').datetimepicker({
            format: 'DD-MMM-YYYY hh:mm a'
        }).on('dp.show', function() {
            $(this).data('DateTimePicker').defaultDate(moment("17-Jan-2017 12:00 pm", "DD-MMM-YYYY hh:mm a"));
    });
```
The field gets the supplied date and time, but the day in the calendar view is not highlighted. It is, however, after clicking the minute selector buttons which I can see at the same time because I'm using the inline option.

I would think that the date supplied should be highlighted so that the user can see what is selected?

**Comment by William-H-M** [comment]
Hi the things is that the 'dp.show' is just fired when you click on the actioner like on a button what you need is as soon as initialized the picker set you up the date so just set it with the events like this: 
`  $('#datetimepicker12').data("DateTimePicker").defaultDate(moment("17-Jan-2017 12:00 pm", "DD-MMM-YYYY hh:mm a"))`

Here a working [JSFiddle ](http://jsfiddle.net/539mx1ja/)

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
