### ISSUE TITLE
Background height issue

### ISSUE THREAD

**Issue by firebird631** [Eonasdan/bootstrap-datetimepicker#2007]
When displayed on the bottom of the input, the height of the background is shorted :

![issue](https://cloud.githubusercontent.com/assets/7570462/22684830/4c65bb62-ed1e-11e6-855f-f5bcc73da495.png)

There is no issue when it is displayed on top. I display the input in a bootstrap input-group and the input-group in table row.

**Comment by gustaflindqvist** [comment]
@firebird631 Hard to know your problem without any code at all?

**Comment by firebird631** [comment]
Ok, I've found the problem. It is because datetimepicker uses a class named bottom and I use the same class name in my application. May it will interesting to uses prefix for class name.
