### ISSUE TITLE
Datetimepicker showing NaN after Mouse drag when using timepicker

### ISSUE THREAD

**Issue by sairam1274** [Eonasdan/bootstrap-datetimepicker#2009]
In my application I have used on timepicker to help of bootstrap datetimepicker, But I have faced some issue like when I am trying to drag timepicker value, my timepicker default select to **NaN:NaN** , Guys can You help me, what is the issue behind this and I have used the below Url for datetimepicker.
http://www.eyecon.ro/bootstrap-datepicker

**Comment by a1iraxa** [comment]
**When you call new Date() you have to pass a valid date**

This is working for me.
```
$(this).daterangepicker({
    minDate: new Date('DD/MM/YYYY'),  // this must be valid format
    timePicker: true,
    timePicker24Hour: true,
    timePickerIncrement: 30,
    locale: {
            format: 'DD/MM/YYYY H:mm' // this one too
    },
});
```

**Comment by William-H-M** [comment]
This is not the correct plugin o non of the question nor the answer
