### ISSUE TITLE
Cannot select any dates

### ISSUE THREAD

**Issue by SteveBarnettTF** [Eonasdan/bootstrap-datetimepicker#2011]
We're using the date time picker in an Angular 2 app. The control is initialised to allow a date range which may be 1-20 years in the past up to todays date:

`

    $(this.datePicker.nativeElement).datetimepicker(
        {
            format: "dddd MMM Do YYYY",
                maxDate: new Date(),
                minDate: this.model.InceptionDate,
                defaultDate: this.selectedDate
         }
     );
`
That all works fine, until the user zoons the control out to maximum zoom by clicking on the title of the control (at the moment, this shows a date range of 2000-2107). Once zoomed out, you cannot select any date in the dropdown to zoom back in - they all have the 'stop' icon on them. 

You can close the picker by clicking somewhere else on the page, but next time you open it, the zoon is still at it's fullest and cannot be shrunk down. The only solution is to completely reload the page.

I was looking at handling the dp.change event, but that doesn't fire so can't help me. Is there some way to handle this elegantly? Can I restrict how far out people can zoom?

It's important to say, this problem only happens if you set the max and min dates. If these aren't set, then you always end up with something you can click on.

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.
