### ISSUE TITLE
Set Custom time

### ISSUE THREAD

**Issue by ghost** [Eonasdan/bootstrap-datetimepicker#2014]
Hi there,
 I was searching for custom time set option in this plugin but i didn't find any option. I need to show the default time '03:00' but in plugin i was just getting default time according  to time and zone but i need to show '03:00' always. [Here](https://almidan.sa.com/owner/courts/create) is a site link you can see if you scroll down in court management block there is a Rates section with Rates title in that section i am using time picker in From and To input filed so i need to set there a custom time '03:00'.

Thank you,

**Comment by fanblater** [comment]
Hello, 
do you find an issue about your problem ? because i have the same ...
Thanks
