### ISSUE TITLE
viewMode: years problem

### ISSUE THREAD

**Issue by anterokarttunen** [Eonasdan/bootstrap-datetimepicker#2017]
1 when using viewMode: 'years' and format: 'YYYY'
2 plugin displays years correctly for selection.
3 After you have selected one, it sets the field value to selected year. (correct behaviour)
4 When you want to change to another year, now it opens the picker in days level (problem)

It should show the year picker not days picker?

`
<input type="text" id="yearPicker"/>
$('#yearPicker').datetimepicker({
		viewMode: 'years',
		format: 'YYYY'
	});
`

**Comment by crnogaj** [comment]
I had this problem with `viewMode: 'months'` also and it was due to jQuery version
I used version 3 (3.1.1) and when I changed to 2 (2.2.4) it worked fine.

**Comment by William-H-M** [comment]
Dup of
 #1854
 #1894
 #1959
quick fix at #1897 
And if not wrong this got fixed on last version and on the version 4.17.46 in master branch

**Comment by anterokarttunen** [comment]
Thanks, sorry for the dupe. Please close ☺

Br, Antero
