### ISSUE TITLE
Duplicate Date on March

### ISSUE THREAD

**Issue by DeyaZ88** [Eonasdan/bootstrap-datetimepicker#2023]
Hi There, 

There is a bug when the month is March on firefox browser.
There is a Duplicated Date on the calendar, Please check the image below.

![duplicate_date](https://cloud.githubusercontent.com/assets/536752/23453481/380bad34-fe71-11e6-9245-7e01a48ff98e.jpg)

Please note that the bug is only on firefox , the calendar on chrome is working just fine.

Best Regards,

**Comment by William-H-M** [comment]
I'm using firefox 51.0.1 and I'm do not see the bug
![captura de pantalla 1](https://cloud.githubusercontent.com/assets/24443241/23459906/6d00bfe6-fe50-11e6-968d-88de8ec5d912.png)

Maybe more info about what version or what were you doing when the big appeared

**Comment by DeyaZ88** [comment]
Im using firefox 51.0.1 32-bit also , I have windows 7 , 
and I've tried it on firefox on Ubuntu on another laptop too, which I've faced the same problem

**Comment by DeyaZ88** [comment]
I believe the issue related to timezone, I'm in Jordan and the timezone is +02:00

**Comment by DeyaZ88** [comment]
Since its a javascript , and the browser read the timezone from OS .. I've change the timezone to +00:00
and the issue is not appeared.
but still it needs to be fixed in all timezones.
