### ISSUE TITLE
Calendar button

### ISSUE THREAD

**Issue by oslyak** [Eonasdan/bootstrap-datetimepicker#2024]
In all examples http://eonasdan.github.io/bootstrap-datetimepicker/
Calendar opens only when clicking on **span class="input-group-addon**, not on input itself.
When I use it, calendar opens when clicking on input itself.

The question is how to make calendar opens only when clicking on calendar button, like in examples?

**Comment by William-H-M** [comment]
Hi, here is a live example of what you're asking http://jsfiddle.net/Eonasdan/0Ltv25o8/

**Comment by oslyak** [comment]
Thank you!

May be should add this example to the examples page?
