### ISSUE TITLE
Android keyboard / forced scroll usability issue

### ISSUE THREAD

**Issue by llanverygranger** [Eonasdan/bootstrap-datetimepicker#2025]
## Overview
When using this on Android, there's a usability issue relating to a scroll, forced by he Android keyboard appearing:

### To Reproduce
1) Ensure Android onscreen keyboard is hidden
2) Click the calendar icon, and choose a date
3) The textfield will be updated live with the chosen date... this brings up the Android keyboard, which then forces the date picker off the screen (only the bottom half now showing). This means I have to scroll to get the datepicker again.

### Alternative User Interface?
Don't update the textfield live. Wait until the user clicks off the datepicker, or give an option to have a button on the datepicker, that says 'OK' or something like that. The idea is to ensure the datepicker is not in view when the textfield is populated. Unless there's a way to stop the Android keyboard appearing, when the textfield is populated  or updated, which I doubt.

**Comment by William-H-M** [comment]
A pretty simple way Is use the text field as ReadOnly, that will avoid android to show up the keyboard, after all, in must of the cases, is not a good idea let the user set dates to their will

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
