### ISSUE TITLE
Can I custom the style of enable and disable dates?

### ISSUE THREAD

**Issue by philwu** [Eonasdan/bootstrap-datetimepicker#2027]
The current styles of enable, disable and other month dates are not obvious as expected.
Is there anyway I can style it myself? I didn't find anything about this from document.
If there is not a such option yet, is it possible to add it on?

Thank you very much.

**Comment by hanoncs** [comment]
Easy.

```
<style>
        .bootstrap-datetimepicker-widget table td.disabled, .bootstrap-datetimepicker-widget table td.disabled:hover {
            background: rgba(255, 0, 0, 0.13) !important;
            color: black;
            cursor: not-allowed;
        }
</style>
```
