### ISSUE TITLE
Calendar is getting cut from the bottom

### ISSUE THREAD

**Issue by vijan87** [Eonasdan/bootstrap-datetimepicker#2036]
In case of there is no space available in the bottom calendar is not going to available space area i.e. top of input box; rather is coming down only n its getting cut/all dates are not visible

**Comment by marcagba** [comment]
Your issue is related to this one: #790 
I personally used the workaround indicated here [here](https://github.com/Eonasdan/bootstrap-datetimepicker/issues/790#issuecomment-234652413)

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
