### ISSUE TITLE
Custom close button/ add a custom button into datetimepicker form

### ISSUE THREAD

**Issue by longlyduc** [Eonasdan/bootstrap-datetimepicker#2038]
I am fairly new to Github so please forgive me - should I be in violation of the etiquette with my question. This isn't really an issue but more of a problem I am having. I try to custom close button, i want remove "x" icon and change it into text like "OK", but i cant find how to do that. Please tell me is it possible to do that, and if it possiable,  it would be great if somebody could tell me how to do that.
Thank you very much and keep up the good work!

**Comment by William-H-M** [comment]
Hi, there are two ways.
1) If you have an icon with an 'OK' sign It can be do it quite easy it's just change the class 
2) Do [this workaround](http://jsfiddle.net/y3cy36ng/1/) that is when the widget is how

Both option are based on this [documentation](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#icons)

**Comment by longlyduc** [comment]
thank you for support, your solution work perfect. And i have 1 more question, can i custom hovering color of button in form? And how to do that?

**Comment by William-H-M** [comment]
Hi, if you mean to change the hovering color of the 'OK' button, is quite simple just add this rule to your css
`.OK:hover { background: whatever color !important}` the important is necessary to overwrite the css of the widget

if it's for all the buttons 
this rule 
```
.bootstrap-datetimepicker-widget table td span:hover {
	background: #eeeeee;
}
```
change the background and add !important on your own css that way you don't need to change anything of the css of the widget

**Comment by longlyduc** [comment]
thank you so much :)
