### ISSUE TITLE
I need to set min date and max date to datepicker input via jquery, but it is not taking the data-date-start-date value, 

### ISSUE THREAD

**Issue by AhammedShaheer** [Eonasdan/bootstrap-datetimepicker#2039]
`$('elementID').data('data-date-start-date','10/03/2017')` not working
`$('elementID').data('data-date-startDate','10/03/2017')` also not working

**Comment by eprislac** [comment]
Try this:
```
$('elementID').data('DateTimePicker').minDate('10/03/2017')
```

**Comment by William-H-M** [comment]
Well this seem more to be for a datepicker and not DateTimePicker
http://bootstrap-datepicker.readthedocs.io/en/latest/options.html
