### ISSUE TITLE
defaultViewDate Option for setting calendar view without setting input value

### ISSUE THREAD

**Issue by NeoElit** [Eonasdan/bootstrap-datetimepicker#2040]
Is there any way to set the calendar view to some date without setting input value.

- My use case to let user choose a set of dates within a period of time. I want picker to open up that month/date without actually setting the input field (since optional)

- Event: dp.change won't get triggered for same date on selection if i set defaultDate

- Event: dp.hide will choose date unintentionally if clicked outside too.

Any workaround for this?
I've seen this issue: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/688 but couldn't get any helpful solution

**Comment by William-H-M** [comment]
Hi, I can help about the first point, the other I don't actually know much about it
So for the first to happen just set default date and `useCurrent: false` and that should work here a [fiddle ](http://jsfiddle.net/10tab7cu/) trying it if doesn't work for your case tell me.

**Comment by NeoElit** [comment]
Yeah, correct. Combination of ```viewDate``` & ```useCurrent``` options will do the trick.
Thanks @William-H-M
