### ISSUE TITLE
widget falls behind elements

### ISSUE THREAD

**Issue by ahmed-sherien** [Eonasdan/bootstrap-datetimepicker#2041]
I can't get the widget to show on top of the elements although I set `z-index` to the max value

**Comment by William-H-M** [comment]
Hi,
Can you give us an example of it, like a jsfiddle or a test page you have?

**Comment by vinodkumar1080** [comment]
I think it's falling behind element because overflow:hidden style applied to it .

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
