### ISSUE TITLE
Option to remove day names of the week

### ISSUE THREAD

**Issue by caneta** [Eonasdan/bootstrap-datetimepicker#2043]
Hi.
I cannot find an option to disable names of week days (Monday, Tuesday, ...) from the calendar header.
Does such a feature exist, or may I set display to none for the second row of calendar thead?

Thank you

**Comment by William-H-M** [comment]
That's right there's no such option, but you can do it setting display none to second row, as you've said before

**Comment by caneta** [comment]
Ok, thank you!

**Comment by William-H-M** [comment]
@Eonasdan could this possibly be a future option, called maybe 'DisplayDayHeader' or something like that?, can be done through css, though

**Comment by caneta** [comment]
Yes, it would be really handy to have an option!

**Comment by William-H-M** [comment]
Hi, I’ll be closing issues that have been answered by the community.

**Comment by egorsmkv** [comment]
Any update on the topic?
