### ISSUE TITLE
how to display timezone abbriviation ?

### ISSUE THREAD

**Issue by artknight** [Eonasdan/bootstrap-datetimepicker#2044]
Hi,
I was wondering if there was a way to display the timezone. I was using this moment format `MM/DD/YYYY hh:mm A z`. 

PS: I know that moment deprecated the use of `z` without the moment-timezones, so essentially we would have to do `moment().tz(timezone).format('MM/DD/YYYY hh:mm A z')` and that would display the timezone abbreviation.

Thanks!

**Comment by thw0rted** [comment]
Until this gets official support, you can always set `format: "MM/DD/YYYY hh:mm [" + theActualTimeZone + "]"` in your options object.  That's what I'm doing now.
