### ISSUE TITLE
Key Bindings Issue

### ISSUE THREAD

**Issue by anshake** [Eonasdan/bootstrap-datetimepicker#2048]
Hi,

I came across a problem with key bindings in datetime picker.
To reproduce,  open http://eonasdan.github.io/bootstrap-datetimepicker/#no-icon-input-field-only.
Then click inside a datepicker. A popup shows up. I can now use left-right-up-down keys to select date and then hit Enter to confirm the choice. So far is perfect. Now, click the field again.
Problem --> Note that now you can not use your keyboard.

General question. Is it somehow possible to set date/time using only keyboard? (I noticed that in a couple of other examples it often does not work. For example, left-right keys won`t work in case popup is hidden.

Thanks in advance,

Anton

**Comment by William-H-M** [comment]
Hi, for this bug please refer to #1690, if not wrong there's a fix there
You can close this as is a duplicate

**Comment by anshake** [comment]
Hi,

Yes, this is what I've got in my case as well.
(namely this https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1690#issuecomment-284269985)

So I can indeed close this one as duplicate
