### ISSUE TITLE
minDate is showing selectable, but it does not update the input control after click it

### ISSUE THREAD

**Issue by JaniceLian** [Eonasdan/bootstrap-datetimepicker#2051]
Hello, 
if i set options like following:

```js
options({
format: "YYYY",
viewMode: "years",
maxDate: new Date("2017"),
minDate: new Date("2014")
})
```

minDate "2014" is showing selectable, but when i click it it does not update the input control

**Comment by eseguro** [comment]
I have the same problem :(

**Comment by JerryWang24** [comment]
me toooooo

**Comment by William-H-M** [comment]
Hi, for thoose that still have problems just do it like this:

```
$('#myDatepicker').datetimepicker({
  format: "YYYY",
  viewMode: "years",
  maxDate:  moment('2017', 'YYYY'),
  minDate: moment('2014', 'YYYY'),
  useCurrent: false
});
```
This will solve the problem.

Hope someone can close this is a quite older issue and is solved
