### ISSUE TITLE
bootstrap-datetimepicker  is not working in mvc5

### ISSUE THREAD

**Issue by sakthivel37** [Eonasdan/bootstrap-datetimepicker#2052]
bootstrap-datetimepicker is not working   and it is throwing datetimepicker() is not found while loading the page in mvc5

**Comment by William-H-M** [comment]
Mmmm did you include it on the bundle config an reference it? that's the only why it shouldn't show

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
