### ISSUE TITLE
Millisecond format

### ISSUE THREAD

**Issue by Xeyos88** [Eonasdan/bootstrap-datetimepicker#2053]
How do I add the display of millisecond?

`format: "MM/DD/YYYY hh:mm:ss.milliseconds"`

**Comment by William-H-M** [comment]
You could show it, but you won't be able to select it, beacause max choose option is till seconds so to show it just do as de [docs says](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#format) 
it'll be something like 
`format: "MM/DD/YYYY hh:mm:ss:SSS"`
http://momentjs.com/docs/#/displaying/format/ where the miliseconds

**Comment by Xeyos88** [comment]
:SSS
print ever 000

**Comment by William-H-M** [comment]
weird it's working for me here: http://jsfiddle.net/539mx1ja/5/
