### ISSUE TITLE
DST, missing is the 2 hour

### ISSUE THREAD

**Issue by GonZOO82** [Eonasdan/bootstrap-datetimepicker#2055]
<img width="883" alt="screen shot 2017-03-26 at 17 05 10" src="https://cloud.githubusercontent.com/assets/9081072/24332431/c07a4642-1246-11e7-870d-af3095bb28cc.png">

**Comment by William-H-M** [comment]
Working for me 

![](https://i.gyazo.com/c0554349b61b7bea200d5acb57577e30.png)
