### ISSUE TITLE
daysOfWeekDisabled changes initial value to following week.

### ISSUE THREAD

**Issue by swilla** [Eonasdan/bootstrap-datetimepicker#2056]
<img width="713" alt="screen shot 2017-03-27 at 9 49 10 am" src="https://cloud.githubusercontent.com/assets/304159/24359546/ae0f8d5a-12d2-11e7-8a64-43c2e65814b3.png">

```
$('#monitor_date').datetimepicker({
        format: "YYYY-MM-DD",
        daysOfWeekDisabled: [
          0,1,2,3,4,6
        ]
    });
```

Value: 2017-03-24 
Changes to: 2017-03-31

https://jsfiddle.net/4kxf0hta/1/

**Comment by William-H-M** [comment]
Hi,
Set `useCurrent: false` and with that you will solve the problem
