### ISSUE TITLE
Close widget only with select date

### ISSUE THREAD

**Issue by chiborg** [Eonasdan/bootstrap-datetimepicker#2059]
I have a problem with this code:

$('.date').datetimepicker({
	format: 'YYYY-MM-DD HH:mm:ss'
});
$('.date').on("dp.change", function(e){
	$(this).data("DateTimePicker").hide();
});

This will close the widget, when the date and time change. Just I want, the widget close when I select a day, and not close, when I change the time. The widget always close, when I change the time with arrow icons.

**Comment by William-H-M** [comment]
Hi, you could have reached this with setting 
`format: 'YYYY-MM-DD'`
that way It would just choose date picker and would close automatically

**Comment by chiborg** [comment]
OK, but I have to input the time too...
