### ISSUE TITLE
can't use minDate and stepping 15 at the same time!!

### ISSUE THREAD

**Issue by mohdmurtuzakhan** [Eonasdan/bootstrap-datetimepicker#2062]
Why I can't use these two options at the same time (stepping and minDate)?

$('#datetimepicker1').datetimepicker({
    sideBySide: true,
    **stepping: 15,
    minDate: new Date()**
});

**Comment by mohdmurtuzakhan** [comment]
The possible work around would be : 
$('#datetimepicker1').datetimepicker({
            **minDate: moment().add(52, 'minutes'),**
            sideBySide: true,
            stepping: 15
        });

**Comment by William-H-M** [comment]
Hi, is not that it doesn't work, it's by the logic taken if it's 7:19 on your browser and you set it up as min date you won't be allowed to choose until you change the hour to 7:30
