### ISSUE TITLE
I want to show only date and month on datetimepicker. Don't want to show year on datepicker as well.

### ISSUE THREAD

**Issue by pratikthakare777** [Eonasdan/bootstrap-datetimepicker#2063]
I want to show only date and month that contain leap year value (i.e. 29) for Feb. Is it possible in current datetimepicker ?
![datepiker](https://cloud.githubusercontent.com/assets/6868325/24602142/29623bbe-1879-11e7-8cc1-11501b610f0d.png)

**Comment by fffuture** [comment]
use `format` parameter in constructor.
f.e. 

```
{
  format: 'DD/MM'
}

```

**Comment by pratikthakare777** [comment]
Hey @fffuture Thanks for responding but setting format will provide next/prev year with it when i click on  next/prev button. I want only 1 year calendar that contain leap year value also.

**Comment by fffuture** [comment]
@pratikthakare777 
probably, it not possible to prevent switching between years, but you can set `maxDate` and `minDate`.
also check `change` event and switch to previous year. it's first idea than comes to mind...
