### ISSUE TITLE
Errors with Microsoft Edge

### ISSUE THREAD

**Issue by thorakmedichi** [Eonasdan/bootstrap-datetimepicker#2065]
I am getting an error in Microsoft Edge (38.14393.0.0) stating datetimepicker property or method is not supported. 

So far this script is working fine with my desktop Safari, Firefox, Chrome and IE 11. As well as working well on several mobile platforms. Edge seems to be the only issue.

![capture](https://cloud.githubusercontent.com/assets/5092843/24638332/6cb08204-189c-11e7-9e8a-26de53ad49ec.PNG)

**Comment by thorakmedichi** [comment]
I should note that I am implementing it like so
`$('#workStart').datetimepicker({ format: 'LT' });`

**Comment by gabn88** [comment]
Was the datetimepicker javascript blocked? For me it works on Edge (Edge 38.14393.1066.0 on Windows 10).

**Comment by thorakmedichi** [comment]
@gabn88 Javascript is on. Looks like you have the same version Edge as me and using Windows 10 so clearly something is up. Thanks for that heads up.
