### ISSUE TITLE
viewMode cannot work

### ISSUE THREAD

**Issue by zhang110912** [Eonasdan/bootstrap-datetimepicker#2067]
i use viewMode:months and format:'YYYY-MM'，but when i click a month ,then open it again ,it shows the days viewmode,is that something wrong? expect your response.

**Comment by William-H-M** [comment]
Hi, this is a duplicate of:
#1854 
#1894 
#1959 
#2061 <--just 6 Issues ago.....
and there's a quick fix at #1897 

For this case if not wrong was fixed on lastest release

**Comment by William-H-M** [comment]
This was fixed on 4.17.47, so I'll close this for now
