### ISSUE TITLE
Format - Day and Month are switched

### ISSUE THREAD

**Issue by h3ko** [Eonasdan/bootstrap-datetimepicker#2068]
Hello,

I've encountered a problem when a DateTime input field is filled from the view model (ASP.NET Core).

`<input asp-for="@Model.MyDate" type="text" />`

MyDate is DateTimeOffset.UtcNow;

The settings for the DateTimePicker are default.

```
function setDatePicker(selector) {
    selector.datetimepicker({ });
}
```

Result: 04/06/2017 12:25 PM (OK)

When I add a format (DD.MM.YYYY)

```
function setDatePicker(selector) {
    selector.datetimepicker({
        format: 'DD.MM.YYYY'
})
```

The result is 04.06.2017 and not 06.04.2017 which would be correct.

Am I missing something? 

I've found simmilar issue https://github.com/Eonasdan/bootstrap-datetimepicker/issues/61

Kind Regards,
Martin

**Comment by William-H-M** [comment]
Hi,
I'm not totally sure what are you actually trying
DateTimeOffset.UtcNow show as with a format of ` 04/06/2017 12:25 PM` what is DD/MM/YYYY HH:mm a

and then you format it again as `format: 'DD.MM.YYYY'` which actually is 04.06.2017
if you want it like `06.04.2017` what is  MM/DD/YYYY
then the format should be
`format: 'MM.DD.YYYY'` and not ``format: 'DD.MM.YYYY'``

Good Luck!

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
