### ISSUE TITLE
sideBySide doesn't work when using standalone CSS

### ISSUE THREAD

**Issue by rknetwork** [Eonasdan/bootstrap-datetimepicker#2072]
Looks like `sideBySide` only works when original `bootstrap.min.css` is loaded.
Unfortunately, I can't use bootstrap's default CSS file, it overrides my styles and causes some CSS conflicts.

I use standalone css file provided, but sideBySide is not working.
```
<link href='styles/bootstrap-datetimepicker-standalone.css' rel='stylesheet' type='text/css'>
<link href='styles/bootstrap-datetimepicker.min.css' rel='stylesheet' type='text/css'>

```

What classes do I need to grab from original bootstrap's css to get `sideBySide` working?

**Comment by ribasal1** [comment]
Try changing the .table-condensed class and the  .bootstrap-datetimepicker-widget.dropdown-menu width only for this page. 
Something like this should work:
`.table-condensed > thead > tr > th,
    .table-condensed > tbody > tr > th,
    .table-condensed > tfoot > tr > th,
    .table-condensed > thead > tr > td,
    .table-condensed > tbody > tr > td,
    .table-condensed > tfoot > tr > td {
      padding: 5px;
    }

    .bootstrap-datetimepicker-widget.dropdown-menu {
      margin: 2px 0;
      padding: 4px;
      width: 39em;
    }`

**Comment by ramppt** [comment]
How to set the date for inline bootstrap datetimepicker.
I used jQuery ('#datetimepicker1').data('DateTimePicker').date('1/10/2017 12:34:24').
Is there any other way to set date and time since it throws error uncaught typeerror: cannot read property 'date' of undefined..  Please provide solution for this..
