### ISSUE TITLE
how to activate in 24 hour formate instead of 12 hour AM PM

### ISSUE THREAD

**Issue by vkkcnit** [Eonasdan/bootstrap-datetimepicker#2075]
how to activate in 24 hour formate instead of 12 hour AM PM, please do 
![dt](https://cloud.githubusercontent.com/assets/26711383/25129690/b42b47ec-245c-11e7-912d-b839a92a889f.png)
needfull

**Comment by William-H-M** [comment]
Hi, 
refer to http://eonasdan.github.io/bootstrap-datetimepicker/Options/#format in there the get you to moment documents
just set format : 'YYYY-MM-DD HH:mm' for more info go [here](http://momentjs.com/docs/#/displaying/format/)

BTW as this is a usage question you could just go and ask on [stackoverflow](http://stackoverflow.com/questions/tagged/bootstrap-datetimepicker)

**Comment by AlexBlt** [comment]
Hi,


You need to change the "locale" parameter.

See here for more info : https://eonasdan.github.io/bootstrap-datetimepicker/Options/#locale
