### ISSUE TITLE
Inconsistent documentation and functionality

### ISSUE THREAD

**Issue by rknetwork** [Eonasdan/bootstrap-datetimepicker#2076]
- Documentation refers to some non-existent `setDate` method/function?
- `min/maxDate` function has a myth feature listed in documentation:
> Note: If the minDate parameter is after the currently selected moment the currently selected moment changes to minDate parameter
- Some features like `sideByside` are not working with `standalone.css`
- Impossible to update date dynamically without triggering `dp.change`
- Access to functions using sick approaches like `data()` with impossible return to the original jquery object!
- Author doesn't respond in timely manner, compare to any other projects.

**Comment by ZalemCitizen** [comment]
- Documentation says : "Note: To limit the picker to selecting, for instance the year and month, use format: MM/YYYY" : this seems not functional

**Comment by binhphanduc** [comment]
I think this library was very good. It just need to improve the documentation. :+1: 
> Documentation refers to some non-existent setDate method/function?
