### ISSUE TITLE
how do I show only current month days only

### ISSUE THREAD

**Issue by sravansurepally** [Eonasdan/bootstrap-datetimepicker#2077]
![oneteam](https://cloud.githubusercontent.com/assets/14120986/25216924/77449e98-25c2-11e7-9742-a9a5f0887382.png)

**Comment by supratims** [comment]
Have you tried

`        $( "#datepicker" ).datepicker({
            showOtherMonths: false,
            selectOtherMonths: false
        });
`

**Comment by William-H-M** [comment]
If someone still looking for this refer to #1909

```
.bootstrap-datetimepicker-widget table tr td.new { display: none; }
.bootstrap-datetimepicker-widget table tr td.old { visibility: hidden; } 
```

**Comment by barilee** [comment]
I recently hit this problem as well so I figured I should share my solution:

 1. Create these functions in a custom (DatePicker) namespace.

`    DatePicker = {
        hideOldDays: function(){ // hide days for previous month
            var x = $('.datepicker .datepicker-days tr td.old');
            if(x.length > 0){
                x.css('visibility', 'hidden');
                if(x.length === 7){
                    x.parent().hide();
                }
            }
        },
        hideNewDays: function(){ // hide days for next month
            var x = $('.datepicker .datepicker-days tr td.new');
            if(x.length > 0){
                x.parent().hide();
            }
        },
        hideOtherMonthDays: function(){ // hide days not for current month
            DatePicker.hideOldDays();
            DatePicker.hideNewDays();
        }
    };`

 2. Add this event for datePicker

`    $('.datepicker').datepicker().on('show', function(e) {
        DatePicker.hideOtherMonthDays();
    });`

**Comment by hamutaro89** [comment]
.datepicker table tr td.new, .datepicker table tr td.old {
    height: 0;
    line-height: 0;
    visibility: hidden;
}

**Comment by jadamec** [comment]
@hamutaro89 great solution, thanks for that!
