### ISSUE TITLE
Double Time

### ISSUE THREAD

**Issue by aquilatrindade** [Eonasdan/bootstrap-datetimepicker#2081]
Hi guys, can i use two times in the datetimepicker ?
For example: Day - Start Time - End Time

Please help!

**Comment by William-H-M** [comment]
Hi, I don't think it's possible but you ca set two datepickers like [this](http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers)

**Comment by aquilatrindade** [comment]
William-H-M Hey dude tnx alot for the quick answer
