### ISSUE TITLE
The dropdown-menu not showing in Jquery confirm window

### ISSUE THREAD

**Issue by derrickxiang** [Eonasdan/bootstrap-datetimepicker#2082]
Hi, I encountered an issue when using bootstrap-datetimepicker plugin, basically in a modal page, when user click a button, it will popup a dialog window (it's another jquery plugin from [here](http://craftpip.github.io/jquery-confirm/) ), and there is a datetime picker inside the dialog window, the issue is, under IE (version 11), when click the calendar icon, there is no dropdown calendar shown, but if change to view in Chrome, it's working.
Wondering if it's related to the z-index as I see the jquery dialog set a very big number for  z-index, but I tried add z-index under style of bootstrap-datetimepicker-widget.dropdown-menu, seems no help, anyone can advice?

**Comment by mtizziani** [comment]
I think i have the same problem. Using Jquery-Confirm 3.2.3 and bootstrap-datetimepicker. if i have a small window with a popup (jquery-confirm dialog) and have a date picker inside that modal it popups to top. but it is cutted on the top and 3 lines are completely missing. 

I have allready searched to change the z-index and set it to 1000 for the confirm dialogs but dont find the point to set it for the datetimepicker .

you can see a screenshot of my issue here:  
[http://prntscr.com/mdmhx3](http://prntscr.com/mdmhx3)
