### ISSUE TITLE
Hours view

### ISSUE THREAD

**Issue by Lukas1990** [Eonasdan/bootstrap-datetimepicker#2084]
Hello, 
is it possible to display hours like this by default (as in attachment)?
Can you help me with this? :-)
![hours](https://cloud.githubusercontent.com/assets/22254913/25557703/f59e4cb6-2d16-11e7-92ed-a49ef1d67e0d.JPG)

**Comment by arthurkirkosa** [comment]
Were you able to make it work?

**Comment by Lukas1990** [comment]
No

**Comment by William-H-M** [comment]
Hi, currently there's a PR review for merge #1892
