### ISSUE TITLE
Add pick month and year from select control

### ISSUE THREAD

**Issue by dagoss** [Eonasdan/bootstrap-datetimepicker#2085]
While this control works very well for capturing a date that is close to the present, our users have issues figuring out how to specify dates far in the past, like birth dates. The user has to click the 7-8 times to specify the date.

I'm hoping there could be an additional option like `singleScreen` where if true, the month and year would be displayed in the toolbar as select boxes, similar to the [JQueryUI datepicker](https://jqueryui.com/datepicker/#dropdown-month-year)

**Comment by anant-lelesys** [comment]
I also suggest this.

**Comment by William-H-M** [comment]
Hi, for this you can always set the [viewMode ](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#viewmode)to either 'years' or 'decades' that way your user would know they have to picker one of those far dates in the past, and will decrease greatly the clicks they have to do.

With by example setting on 'decades' and looking for my birthday it was just a few click, only 5, against 5 of Jquery UI, and not counting that I did have to open the select box every time that I want to get to the 90's that would have been 9 clicks almost the double, other problem would be that's is not that much of intuitive with a select box and that have to make a limit of the years appeaing, like what it's done with JQuery UI

Note: not sure if close this, as been "solved" by setting viewMode, or leave it open for disccusion.
New features are being taking on mind tough.

> [...] I'll be closing PR that do not contribute emergency fixes [...]
