### ISSUE TITLE
Move away from jQuery

### ISSUE THREAD

**Issue by DincaRoberto** [Eonasdan/bootstrap-datetimepicker#2086]
Is there a plan to remove jQuery as a dependency and rely fully on Angular?

**Comment by jsbUSMC** [comment]
Why rely on Angular? If anything, removing jQuery would be best if replaced by vanilla JS.

**Comment by DincaRoberto** [comment]
Vanilla would work also... As long as we get rid of the jQuery dependency 


Enviado de Samsung Mobile

-------- Original message --------

**Comment by madzman23** [comment]
Why @DincaRoberto?

**Comment by DincaRoberto** [comment]
Because is a small component, depending on a huge library (jQuery)... For
instance, one might want to use this component in a project where jQuery is
not included.

**Comment by pkmccaffrey** [comment]
Per the docs, Bootstrap requires jQuery for all of its plugins.   As far as these plugins, It looks like this widget uses Transitions and Collapse.

I'm sure it would be possible to re-implement this widget without relying on jQuery or the base Bootstrap plugins.  However, this seems like an exceptionally unlikely use case.

**Comment by atonse** [comment]
Bootstrap 4 ditches jQuery. They've reimplemented bootstrap.js using vanilla Javascript. So this is a pretty reasonable thing to discuss at this point.

**Comment by William-H-M** [comment]
Hi, if that's the case on BS4 then this should be moved to https://github.com/tempusdominus/bootstrap-4
AS:
1) All PR's that are not seen as emergency fixed will be ignored
2) This library depends heavily on jQuery and it seems like there're no plans to move to a non dependencies' library like VanillaJS

Will be waiting for respone or else this issue will be closed on 8 from now.
