### ISSUE TITLE
Jquery later append how to trigger？

### ISSUE THREAD

**Issue by fuerpeng** [Eonasdan/bootstrap-datetimepicker#2094]
![image](https://cloud.githubusercontent.com/assets/24818415/25935975/355c4336-3658-11e7-84ac-f3cd429ff688.png)

**Comment by William-H-M** [comment]
Hi, I'm not totally sure if you're on the same library, as I do not recognize does option for this project, at least it's one of the older versions, can you verify on the JS file if it's from this project or an older version?

**Comment by fuerpeng** [comment]
This should be the old version, Thank you I now come to learn the latest version
