### ISSUE TITLE
Normal text and Disabled text colors are interchanged

### ISSUE THREAD

**Issue by premu21** [Eonasdan/bootstrap-datetimepicker#2095]
![error](https://cloud.githubusercontent.com/assets/23609876/26024102/5005b884-37e8-11e7-9c58-7e8d90057822.png)

**Comment by premu21** [comment]
Gotcha, there was a css class stating color of td,th to white

**Comment by William-H-M** [comment]
Hi, is this solved? If it's, and it's what it looks like, please close this issue.
