### ISSUE TITLE
How can disable date with hour

### ISSUE THREAD

**Issue by Lukas1990** [Eonasdan/bootstrap-datetimepicker#2097]
How can I disable date with specific hour?
I tried add disabledDates: ["05/29/2017 21:00"] to the script but this disable all day and not only time in this date.
Thanks.

**Comment by ajcastro** [comment]
Maybe there should be an option of `disabledTime` and `enabledTime`, which accepts string or array of times

**Comment by RizzCandy** [comment]
Just use `format: 'LL'`

**Comment by ajcastro** [comment]
He wants that the time 21:00 should be the disabled, not the whole day.

**Comment by RizzCandy** [comment]
Then, according to [moment](http://momentjs.com/docs/#/displaying/) displaying, it should be `format: 'kk mm'`

**Comment by Lukas1990** [comment]
My friend helped me with this issue. :-)
He used his knowledge from here:
https://stackoverflow.com/questions/35166506/bootstrap-datetime-picker-disable-hours

**Comment by KG20** [comment]
But isn't that to block period of time. how can it be done, if i want to disable only a particular time, (as stepping will already take care of the time interval for my case)??

**Comment by William-H-M** [comment]
Hi, this seems like solved so I'll be closing this

**Comment by ankitsakhareliya** [comment]
It works for me:
 hoursDisabled: '0,1,2,3,4,5,6,7,18,19,20,21,22,23'
