### ISSUE TITLE
Is there any way to show only time picker ?

### ISSUE THREAD

**Issue by ashu07** [Eonasdan/bootstrap-datetimepicker#2098]

**Comment by William-H-M** [comment]
Hi, as on the [documents ](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#format)say 
you can do that with the format just set up
`format: hh:mm` for 12 hours format or `HH:mm` for 24h

as this is an usage question close this issue as soon as you see this message thanks.

**Comment by ashu07** [comment]
got that and thanks 👍
