### ISSUE TITLE
Data binding issues

### ISSUE THREAD

**Issue by wewedgeworth** [Eonasdan/bootstrap-datetimepicker#2099]
I am using version 4.15.35 of the bootstrap-datetimepicker in an AngularJS Boostrap application. 

The only bootstrap-datetimepicker option I am using is `format = 'MM/DD/YYYY'`. I am binding data to the input using data-ng-model.

Issue #1: 
I select a date through the calendar picker, then input some invalid characters through the input box as follows:
![image](https://cloud.githubusercontent.com/assets/13909502/26167855/b12b3860-3afd-11e7-9167-6101eec95643.png)

When I click away to blur the input, the boostrap-datetimepicker removes these invalid characters from the value in the input:
![image](https://cloud.githubusercontent.com/assets/13909502/26167898/d6b97cd6-3afd-11e7-87f6-a2a7ea00afe0.png)

However, in the Javascript the value "01/aaa13/2017" is still present in the bound property.

Issue #2:
I select a date through the calendar picker. Then I click away to blur the input. Then I click back and select another date through the picker. In the Javascript, the bound property still holds the first selected value, and this does not change with any subsequent date selections through the calendar picker.

If anyone has any insite as to how I should proceed, I would really appreciate it. Additionally, if any further information/code would be helpful please let me know.

**Comment by William-H-M** [comment]
Hi, these problem has been happend before, it's recomend to do 2 thing

1) Use the angular wrapper given by the [guide ](http://eonasdan.github.io/bootstrap-datetimepicker/Installing/#angular-wrapper)on the docs

2) Use another angular wrapper that most of people use: This one by [Atais](https://github.com/atais/angular-eonasdan-datetimepicker)

This related to #314 and maybe to #1993 

BTW: You should not use # for setting points as is reserved for call related issue, as I did before, instead just list them with "-" or a simple list.

**Comment by wewedgeworth** [comment]
Thank you for the reply! I was able to get it working using the solution in #314.

**Comment by William-H-M** [comment]
Hi, Great that it worked!, as I've never used angular maybe I wouldn't able to give you any other help, but now is solved, any other question related to the plugin just ask :)

Now as this is solved please close this issue, maybe that way others can find it faster.
