### ISSUE TITLE
INIT with Format YYYY-MM-DD, HH:mm:ss , then reformat with YYYY-MM-DD , the hour view not disappear

### ISSUE THREAD

**Issue by ice0526** [Eonasdan/bootstrap-datetimepicker#2100]

**Comment by William-H-M** [comment]
Hi, do you have any example like a [fiddle ](https://jsfiddle.net/)or a shared code?
2. Did you try to first destroy the picker and then re-attach the picker?

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.

**Comment by yinsang** [comment]
Do you solve this problem?
I have the same problem with you had met.
`$(function () {
						        $('.user-date-picker').datetimepicker({
						        	format:'yyyy-mm-dd'
						        }); 
						    });`

**Comment by rdkmaster** [comment]
@ice0526 and i worked together.

NO, this issue has not been fixed yet.

**Comment by ice0526** [comment]
not fixed yet

**Comment by William-H-M** [comment]
Hi, I'll reopen this but can you guys provide a fiddle showing what are you doing, with the proper steps to reproduce it? here a base for the fiddle https://jsfiddle.net/William_/20oywuno/

**Comment by ice0526** [comment]
https://jsfiddle.net/n9aofvht/    add a fiddle.  when click the button , change the format to YYYY-MM-DD , but the hour view not disappear

**Comment by William-H-M** [comment]
Hi, ok I see, so the thing is not refreshing "the view", do you guys mind if I change a little bit something?
It seems something more like a workaround but somehow It still the same, the only difference is that will have a function doing "everything" here the live https://jsfiddle.net/William_/20oywuno/5/

What I did is to make a function that Init the picker with a desired format (you can alway see if the option is undefined and set a format if you want), see if has been called before, if yes destroy picker and set new format, that should work.

Pasting code here in case jsfiddle get downs:

```
InitPicker("YYYY-MM-DD HH:mm:ss");
$("#changeFormat").click(function(event) {
  InitPicker("YYYY-MM-DD");
});


function InitPicker(format) {
  var initiated = $('#myDatepicker').data("DateTimePicker");
  if (initiated !== undefined) {
    $('#myDatepicker').data("DateTimePicker").destroy();
  }

  $('#myDatepicker').datetimepicker({
    format: format,
    inline: true
  });
  alert($('#myDatepicker').data("DateTimePicker").format());
}
```
Should this be okay for you guys?

**Comment by rdkmaster** [comment]
@ice0526 can you please try @William-H-M 's code and tell me is that working for this issue?

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
