### ISSUE TITLE
Bootstrap Datepicker inside table not showing completly

### ISSUE THREAD

**Issue by hugoromo** [Eonasdan/bootstrap-datetimepicker#2103]
WWhat fix to use? I already tried all that I could find about this issue, but no luck
http://jsfiddle.net/0Ltv25o8/5069/

**Comment by evanre** [comment]
Hi, it's because you are using `.table-responsive` wrapper. Css property `overflow: scroll` hides calendar.

**Comment by ajcastro** [comment]
Did you try putting z-index? So that it will above other elements.
