### ISSUE TITLE
Getting epoch timestamp sent over GET method form

### ISSUE THREAD

**Issue by lcoulon** [Eonasdan/bootstrap-datetimepicker#2104]
Hello,

I'm trying to send the user datetime selection over GET form method, i tried the following example but i can't pass the epoch timestamp when the user clicks on the submit button.

http://jsfiddle.net/lcoulon/qva09wtb/3/
I also found the 'real' html page related to my example won't load properly but jsfiddle's does, i don't know why :
http://s529471052.onlinehome.fr/datetimeform/gpio/test-eonasdan-form.htm

console says 

> Uncaught TypeError: input.size is not a function
>     at dateTimePicker (bootstrap-datetimepicker.js:1842)
>     at HTMLDivElement.<anonymous> (bootstrap-datetimepicker.js:1897)
>     at Function.each (jquery-3.1.1.slim.min.js:2)
>     at r.fn.init.each (jquery-3.1.1.slim.min.js:2)
>     at r.fn.init.$.fn.datetimepicker (bootstrap-datetimepicker.js:1892)
>     at test-eonasdan-form.htm:101

Would you please show me how i could get it the epoch timestamp sent as parameter when form is submitted ?

**Comment by William-H-M** [comment]
Hi, as I'm not sure what language you do use, so I'm going to stick it out with the one that I usually use, ASP NET MVC with an AJAX for submit buttons.

1) What you could do is that as every time there's a change on the date, set it up on a variable so when there's a click on submit button you assign that variable on the AJAX data call, or at least is how I'll do it with something for general use like AJAX

2) About your error on the page, it looks like you're using 2 different versions of JQuery 2.1.3 and 3.1.1 maybe that's crashing something? As not totally sure if there's no problem between the version of the datetimepicker and JQuery 3

3) One more little quick thing, try to update to the latest version of the plugin on your example appear to be 4.7.14, currently it's on the 4.17.37

**Comment by lcoulon** [comment]
I use HTML Bootstrap v4, alpha 6.

I finally get datetime displayed, however in 'inline' mode , the dates windows and time are not properly aligned in my example below :

http://s529471052.onlinehome.fr/datetimeform/gpio/test-eonasdan-dtp-form_1.htm

Is there a way to add a link in epoch format in order to get it sent out when the user submits the form ?
If so can you show me how to do this please ?
