### ISSUE TITLE
not show hours and minutes

### ISSUE THREAD

**Issue by AlbertoMrFz** [Eonasdan/bootstrap-datetimepicker#2105]
It's possible only show dates and not show hours and minutes??

**Comment by William-H-M** [comment]
Hi, #2098 just a few issues ago reference to the same, in the docs it tell too how to do this [http://eonasdan.github.io/bootstrap-datetimepicker/Options/#format](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#format).

As this an usage question close this as soon as you see this, thanks

**Comment by AlbertoMrFz** [comment]
thanks
