### ISSUE TITLE
disble all dates except i pass with parameter in json

### ISSUE THREAD

**Issue by AlbertoMrFz** [Eonasdan/bootstrap-datetimepicker#2107]
I try to do this, disable all dates and enable the dates that i pass with parameters

This code not work
```
$.ajax({
       method: "GET",
        url: "url",
 })
.done(function(msg) {
       console.log(JSON.parse(msg));//moment("5/25/2017"),moment("5/26/2017"),moment("5/27/2017")
       $('#input_from').datetimepicker({
                 locale: 'es',
                 format: 'DD-MM-YYYY',
                 enabledDates: [
                         JSON.parse(msg)
                 ]
        });
});
```

But this code work:
```
$.ajax({
       method: "GET",
        url: "url",
 })
.done(function(msg) {
       console.log(JSON.parse(msg));//moment("5/25/2017"),moment("5/26/2017"),moment("5/27/2017")
       $('#input_from').datetimepicker({
                 locale: 'es',
                 format: 'DD-MM-YYYY',
                 enabledDates: [
                         moment("5/25/2017"),moment("5/26/2017"),moment("5/27/2017")
                 ]
        });
});
```

Its possible to do that i want??

Thanks

**Comment by William-H-M** [comment]
Hi, for this you should iterate through the data, [I did it this way](https://jsfiddle.net/William_/sapLtgsm/2/) it should work for you even with json

the basic idea is this

```
var vector = [moment("5/25/2017", "M/DD/YYYY"), moment("5/26/2017", "M/DD/YYYY"), moment("5/27/2017", "M/DD/YYYY")];

  enabledDates: $.each(vector, function(i, value) {
    return value;
  })
```

**Comment by AlbertoMrFz** [comment]
Hello,
Thanks for the reply.
But this code does not work for my case, what I need is to use the values ​​that the ajax request returns, I do not define them, I want them to be dynamic

**Comment by William-H-M** [comment]
Hi, vector it'll be Ajax data, not sure how are you gone retrieve it (I mean like if just date ["5/25/2017"] or if you will return it with the moment("5/25/2017", "M/DD/YYYY") )

So when onSucces Ajax request the result should contain that data, then it'll be parse, and then you could do the iterator, of course you can avoid the "vector part" and do it directly with json.parse being the data that you will iterate.

I just did it with static data as a given example of what you would get from the Ajax.

SIDE NOTE: I do use the [string + format](http://momentjs.com/docs/#/parsing/string-format/) as should be the easier way to avoid errors from the browser and the moment console warning
