### ISSUE TITLE
Form validation not working

### ISSUE THREAD

**Issue by nowsathshereef21** [Eonasdan/bootstrap-datetimepicker#2109]
Hi,
I am using Bootstrap Datetime picker for my project. the date field always return false even if I give correct date.
Here is my code
**HTML:**
```
<div class="input-group date" id="startdate">
  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
  <input type="text" class="form-control" value="" name="startDate" data-fv-notempty="true">
</div>

```

**JS:**
```
$('#startdate')
  .datetimepicker({
    format: 'DD/MM/YYYY'
  })
  .on('changeDate', function(e) {
    // Revalidate the date field
    $('#officeApplicationForm').formValidation('revalidateField', 'startdate');
  });

```

**Comment by Frank735** [comment]
Looks like you are binding the wrong change event. It should be:
`.on('dp.change', function(e){});`

Maybe there is something wrong with your validation? You can check the selected date with:
`console.log($('input[name="startDate"]').val());`
If the above logs the correct date, you should fix your validation.

**Comment by William-H-M** [comment]
Hi, I’ll be closing issues that have been answered by the community.

**Comment by nayakranjeet** [comment]
good
