### ISSUE TITLE
Calendar not showing today, until yesterday it was working fine

### ISSUE THREAD

**Issue by Giovanni-Enrico** [Eonasdan/bootstrap-datetimepicker#2110]
Is some of the js repository not working? Yesterday I was using the calendar just fine, now it wont work anymore. These are my .js imports.
`	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
	<script
		src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<script
		src="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/a549aa8780dbda16f6cff545aeabc3d71073911e/src/js/bootstrap-datetimepicker.js"></script>

	<script src="DadosTabela.js"></script>

	<script src="//code.jquery.com/jquery-1.12.4.js"></script>

	<script
		src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

`

**Comment by Giovanni-Enrico** [comment]
Nevermind, I realized I was importing 2 jquery versions.

**Comment by William-H-M** [comment]
Hi, everything seems fine for me from this side could you try to change the rawgit one for the [cdnjs](https://cdnjs.com/libraries/bootstrap-datetimepicker)?
