### ISSUE TITLE
Confused to what version should I use

### ISSUE THREAD

**Issue by nam-co** [Eonasdan/bootstrap-datetimepicker#2114]
Hi, Im confused in what version should I use, Im using bootstrap 4, I see this repo has a version 5, but theres another https://github.com/tempusdominus/bootstrap-4, can you please recommend witch is more maintain and better for scss etc..

thanks, appreciate the tip

**Comment by William-H-M** [comment]
Hi, I should recommend use the current version and not the V5 as this is just in alpha, about how to use it with bootstrap 4, on #1377 there're a few ways to handle everything related to it, and the last comment is related to sass

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
