### ISSUE TITLE
MinDate Format

### ISSUE THREAD

**Issue by AlexandreLogist** [Eonasdan/bootstrap-datetimepicker#2115]
Hello,

I cant seem to find the **format that minDate** takes?
It's for year month and day and i want to give it by a string

**already tried:**
DD/MM/YYYY 
DD-MM-YYYY  
DDMMYYYY
and switched in all orders...

When I just enter 2017 mindate starts from 22 januari 2017

Thanks in advance

**Comment by Frank735** [comment]
The easiest (and probably preferred) way is to use Moment for this. So for example:
`moment("02-06-2017","DD-MM-YYY")`

Where the first variable is your desired date, and the second is the format of said date.

**Comment by AlexandreLogist** [comment]
@Frank735 , a string "02-06-2017" should work no ?

**Comment by Frank735** [comment]
If you want to to be today, setting moment() should be good enough. It works for maxDate in my code. You do have the latest version right?

Looking at the source code, maybe you should try setting the minDate to string: 'now' or 'moment:
`            if (typeof minDate === 'string') {
                if (minDate === 'now' || minDate === 'moment') {
                    minDate = getMoment();
                }
            }`

**Comment by AlexandreLogist** [comment]
It was an issue with different css & js versions... That gave me a conflict.
Thanks for the help!

Alex

**Comment by Frank735** [comment]
Glad to know it has been resolved. Happy coding!
