### ISSUE TITLE
`timeZone` option is not documented

### ISSUE THREAD

**Issue by thw0rted** [Eonasdan/bootstrap-datetimepicker#2118]
There are several issues that reference passing a `timeZone` option, which appears to work, but this option does not appear anywhere in [the docs](http://eonasdan.github.io/bootstrap-datetimepicker/Options/).

**Comment by adrichey** [comment]
Also curious about this. Is this going to continue to be supported?

**Comment by rodrigoyoshida** [comment]
I was searching for hours about this. Read the whole documentation and could not find any option to set the timezone. They should document this option or at least say it's deprecated if it's the case. My whole application runs in UTC mode and I really needed this option.

**Comment by AlexanderPilhar** [comment]
Very true! I just was in need for this option for the second time since half a year and almost forgot about it. Still it took me hours just to find out about this one again ... Is this meant to be some easter-egg-thing!?

**Comment by kwiniarski97** [comment]
It is documented now. Could use some example. For people who found this issue from google. There's an example: 

Include moment-timezone in your app.
In your configuration set timeZone to one of the [moment-timezone zones ](https://momentjs.com/timezone/) i.e. `timeZone: 'Europe/Warsaw'`


http://eonasdan.github.io/bootstrap-datetimepicker/Options/#timezone
