### ISSUE TITLE
Change the Color of "togglePeriod" button

### ISSUE THREAD

**Issue by AshishTechIT** [Eonasdan/bootstrap-datetimepicker#2120]
Hello,
I'm trying to perform some CSS changes to change the background color of Period button (AM/PM) avaialble in Datetimepicker.
But any change in the CSS files has no impact on the button color.

The following CSS modifications doesn't impact the button color:-
`<style>
    .bootstrap-datetimepicker-widget table tr td.active,
    .bootstrap-datetimepicker-widget table tr td.active:hover,
    .bootstrap-datetimepicker-widget table td.active,
    .bootstrap-datetimepicker-widget table td.active:hover,
    .bootstrap-datetimepicker-widget table td.day:hover,
    .bootstrap-datetimepicker-widget table td.hour:hover,
    .bootstrap-datetimepicker-widget table td.minute:hover,
    .bootstrap-datetimepicker-widget table td.second:hover,
    .bootstrap-datetimepicker-widget table td span:hover {
        background: #ff6a00;
    }

    .bootstrap-datetimepicker-widget table thead tr:first-child th:hover {
        background: #ff6a00;
    }

    .bootstrap-datetimepicker-widget table td.today:before,
    .bootstrap-datetimepicker-widget table td.active,
    .bootstrap-datetimepicker-widget table td.active:hover,
    .bootstrap-datetimepicker-widget table td span.active {
        background: #ff6a00;
    }

    .bootstrap-datetimepicker-widget table td span:hover {
        background: #ff6a00;
    }`
Is there any ways we can change the background color on active and hover action for this button?

**Comment by William-H-M** [comment]
Hi, this is because the AM/PM button has the clas btn btn-primary of bootstrap that's how put the color itself, so for this you gotta overide btn btn-primary button style

**Comment by AshishTechIT** [comment]
Thanks. I managed to change the color and remove the border by adding the following css:-

` .btn[data-action="togglePeriod"], .btn-primary[data-action="togglePeriod"] {
        background: #fe6601;
        border:none;
    }
`
