### ISSUE TITLE
How to change the format dynamically?

### ISSUE THREAD

**Issue by HuangZhenyang** [Eonasdan/bootstrap-datetimepicker#2122]
Hi! I want to ask that what I should do to change the format.
For example, if I choose "day", format is `"yyyy-mm-dd hh:ii"`; If I choose "month", format is `"yyyy-mm-dd"`. **I meet the challenge that the format always the one that I set the first time.** 
And I've tried some solutions, but none worked. 
Thank u very much!

**Comment by William-H-M** [comment]
Hi refer to #2100
