### ISSUE TITLE
Clicking the same date twice, doesnt fire up the dp.change event

### ISSUE THREAD

**Issue by m33ts4k0z** [Eonasdan/bootstrap-datetimepicker#2124]
Hello,

I was looking for a way to update the time even if the input field is not empty. Since I couldnt find a built in way to do it I wrote some code that handles it. This is working correctly. My code waits for the dp.change event and then I append the selected date with the current time through my code. I noticed that when the user clicks on the same date more than once, the old time that was existing in the field when the page loaded, takes the place of the new, updated one. That means that the dp.change is not fired once again although the time has changed.

Its a minor issue so I just thought to report it.

Thanks

**Comment by William-H-M** [comment]
Know that this a old issue, but I wasn't able to reproduce it, does still happens with the later version? or in [this fiddle](https://jsfiddle.net/20oywuno/)?

**Comment by vishalinfyom** [comment]
yes happen into your fiddle too, add this line and select same date twice, alert() should be popup twice, but it is not.
```
$('#myDatepicker').on('dp.change', function(){
alert();
});```
