### ISSUE TITLE
Is it possible for bootstrap-datetimepicker to show which week the current day is?

### ISSUE THREAD

**Issue by HuangZhenyang** [Eonasdan/bootstrap-datetimepicker#2125]
Hi! I want to know if bootstrap-datetimepicker can show which week the current day belongs to. If it can, could u please tell me how to do ? 

thank u

**Comment by William-H-M** [comment]
Hi, Mmmm something like [this?](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#calendarweeks)


![imagen](https://user-images.githubusercontent.com/24443241/27133279-3c9f12e2-50d7-11e7-9456-843a368465a7.png)

If yes, set up:
`calendarWeeks: true`

As this is an usage question please close the issue as soon you see this message, thanks.

**Comment by HuangZhenyang** [comment]
Yes, that's it! 
Thank u very much.
