### ISSUE TITLE
date time format not working...

### ISSUE THREAD

**Issue by fake-fur** [Eonasdan/bootstrap-datetimepicker#2128]
hi guys

```
$('#sdate').datetimepicker({
	locale: 'NL',
	format: 'DD-MM-YYYY HH:mm'
});
```

this is not working ... i see the date time in the text input area after selecting a date, but i cannot make the time picker icon show up at the bottom of the calendar

any ideas?
thanks

**Comment by William-H-M** [comment]
Hi, it's working for me right now: [Fiddle](https://jsfiddle.net/William_/ajaxnz23/)

Note: I do not set the locale as I do not have the file

**Comment by fake-fur** [comment]
*bangs head against desk*
yes it does work when you comment out the CSS you had previously added to specifically hide it
*mutters and wanders away*

thanks so much for shining the light
:)
