### ISSUE TITLE
Cannot Select 00:00 as Time using Hour

### ISSUE THREAD

**Issue by trevrobwhite** [Eonasdan/bootstrap-datetimepicker#2131]
Hi,
I found a small issue in the datetimepicker, if you set the minDate to be midnight on a certain day, it is not possible to roll this back using the hour clicker.

For example, I have the defaultDate and minDate set to today 00:00.
Say now the user clicks the hour up to make this 01:00 it is not possible to use the hour down button to change it back to 00:00, instead the user has to press the minute down arrow to make 00:59 then continue pressing a further 59 times to get back to 00:00.

To allow this to work then the minDate has to be set to 22 hour of the previous day, however this means the user can select a date from yesterday.

![image](https://user-images.githubusercontent.com/8374586/27231361-4c420f18-52aa-11e7-9a02-96b4e36f351b.png)

Works but can select a date from yesterday:
```javascript
  var dateNow = new Date();
     var yesterday = new Date(new Date().getTime() - 24 * 60 * 60 * 1000);
    $('#datetime').datetimepicker({
        format: "DD-MMM-YYYY HH:mm",
        defaultDate:moment(dateNow).hours(0).minutes(0).seconds(0).milliseconds(0),
        minDate: moment(yesterday).hours(22).minutes(59).seconds(0).milliseconds(0),
        sideBySide: true
    });
```

Would be best if this worked:
```javascript
  var dateNow = new Date();
    $('#datetime').datetimepicker({
        format: "DD-MMM-YYYY HH:mm",
        defaultDate:moment(dateNow).hours(0).minutes(0).seconds(0).milliseconds(0),
        minDate: moment(dateNow).hours(0).minutes(0).seconds(0).milliseconds(0),
        sideBySide: true
    });
```

**Comment by William-H-M** [comment]
Hi, two things:
1) I wasn't able to reproduce the problem (at least not on the latest version).
2) You can simplify all this:
`moment(dateNow).hours(0).minutes(0).seconds(0).milliseconds(0)`
to this:
`moment(dateNow).startOf('day')`

Easier to read and understand for others [including yourself] on the future
