### ISSUE TITLE
SideBySide produce bad result on big screen

### ISSUE THREAD

**Issue by fabifabi** [Eonasdan/bootstrap-datetimepicker#2132]
$('.datetimepicker').datetimepicker({
            locale: 'fr',
            useCurrent: true,
            sideBySide: true,
            showTodayButton: true
        });

SideBySide make hour  display ON  the Calendar, product a bad effect,on chrome&ff.
And today button don't appear :(

**Comment by William-H-M** [comment]
Hi, can you give a more specific resolution for "on big screen", that way others can try it? thanks

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
