### ISSUE TITLE
Stop Days in Datetimepicker

### ISSUE THREAD

**Issue by xdezines** [Eonasdan/bootstrap-datetimepicker#2133]
/*! version : 4.17.43

We are trying to stop particular days in date picker but it's not working.
`jQuery(function($) {	
	$('#reachus-date').datetimepicker({ pickTime: false, daysOfWeekDisabled:[0,1] });	
});
`
i am not sure what we are doing wrong but all days are staying enabled. We want to disable Sunday & Monday of all months in our calendar.

Please help.

Regards,
Chirag

**Comment by William-H-M** [comment]
Hi, you have a console error, 

> TypeError: option pickTime is not recognized!

`pickTime: false` does not exist in this plugin.

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
