### ISSUE TITLE
Is it possible to preventDefault on dp.change ?

### ISSUE THREAD

**Issue by d-aven** [Eonasdan/bootstrap-datetimepicker#2135]
Is it possible to preventDefault on dp.change ?

**Comment by noveweb** [comment]
+1

**Comment by d-aven** [comment]
There are all events fire only notifications. You cannot change data indside your handlers.
In my case, I used stupid way using global variables as flag.

**Comment by William-H-M** [comment]
Hi, somehow this would apply for eonasdan dp.change event too.
https://stackoverflow.com/questions/24251955/preventdefault-not-working-for-change-event

this should be close as is not a error on the code but on the design itself of JavaScript

**Comment by noveweb** [comment]
I understand now. But, how can i prevent that dp.change fires twice? I'm using the version 4.17.47.

Thanks in advance!

**Comment by d-aven** [comment]
Use global variable.
`var isFirstTime = false;`
Inside your event
```
if (isFirstTime !== true) {
   isFirstTime = true;
}
```

**Comment by William-H-M** [comment]
Hi, I’ll be closing issues that have been answered by the community.
