### ISSUE TITLE
Picker not working when including ionic v1.3 js

### ISSUE THREAD

**Issue by singhniranjan** [Eonasdan/bootstrap-datetimepicker#2138]
Picker would not launch when ionic v1.3.3 js is included in the html page. When binding to input directly, the popup would launch, however date selection will work on IE only, will not work in FireFox and Chrome.

Please see this jsfiddle to reproduce the issue:
[https://jsfiddle.net/xq2svuc5/](https://jsfiddle.net/xq2svuc5/)

Any pointer to pinpoint and fix the issue would be highly appreciated.

Thanks.

**Comment by luis-ordering** [comment]
Hello, for the input datepicker, you can try with:

> var datefrom = $('#datefrom').datetimepicker({
>     format: 'L',
> });
> 
> datefrom.on('dp.show', function () {
>     $(".bootstrap-datetimepicker-widget").attr('data-tap-disabled', 'true');
> });

There will let you click and select the day and other functions.
This worked for me, greetings.

**Comment by singhniranjan** [comment]
Thanks @luis-ordering .
