### ISSUE TITLE
Bug: How to make disabled year section?

### ISSUE THREAD

**Issue by PramodSaw** [Eonasdan/bootstrap-datetimepicker#2142]
I tried to disable yearsViewHeader but it's not working, Please tell me that how to make disable  year header.

![datetimepicker](https://user-images.githubusercontent.com/14846186/27736293-3d2cc988-5dc1-11e7-8c96-634cfc85f36b.jpg)

**Comment by William-H-M** [comment]
Hi, be itself this is not a bug as there's not intended by the pluing

you can disable with a css class just do this:

```
.bootstrap-datetimepicker-widget thead .picker-switch {
     cursor: default;
     pointer-events: none;
}
```

**Comment by PramodSaw** [comment]
Thanks! it's working
