### ISSUE TITLE
Custom format problem

### ISSUE THREAD

**Issue by felipyamorim** [Eonasdan/bootstrap-datetimepicker#2145]
In current version i have this issue with custom format. I choose the month, and when i came back the picker ignore the format and open the days.

https://jsfiddle.net/c5gu85pL/

**Comment by William-H-M** [comment]
Hi, you have an older version on your fiddle you have 4.17.45 but on 4.17.47 this was fixed, here a [fiddle with 4.17.47 ](https://jsfiddle.net/William_/ja6v6x2x/)

**Comment by felipyamorim** [comment]
Thank you, I will try.

Closing for now.
