### ISSUE TITLE
Disable decreasing time after a specific time when mode="time"

### ISSUE THREAD

**Issue by sumit1726** [Eonasdan/bootstrap-datetimepicker#2146]
Hi,

I'm using react-bootstrap-datetimepicker <DateTimeField mode="time"/> for start time and end time only. I want to not allow the end time be before than start time. And would like not to allow user to decrease time in end-time so that start-time will always be before than end-time. Please help me out in this issue.

**Comment by William-H-M** [comment]
Hi, do you mean something like related pickers? like if one start picker it's 1 PM then on the end picker he, the user, only can chose 1.15 PM or 1.01 PM? 
If yes, this can actually be done and is show on the [docs page](http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers) using jquery here's a [fiddle](https://jsfiddle.net/William_/20oywuno/) showing it.

**Comment by sumit1726** [comment]
![image](https://user-images.githubusercontent.com/8969007/28004827-b880c04e-6564-11e7-9160-1933d29a9bcb.png)

**Comment by sumit1726** [comment]
In the above image, I just want to disable/hide the down icons to decrement hours and min. this way, the user won;t be able to input the time before the start time. I tried setting the icons of down to null to replace it, but it's not working.
