### ISSUE TITLE
Bootstrap datetimepicker is not working for culture zh-HK (Chinese-Hongkong)

### ISSUE THREAD

**Issue by KushalMaz** [Eonasdan/bootstrap-datetimepicker#2149]
I am working in a multilingual application and Bootstrap DateTime Picker (version : 4.17.37) is being used there. When I am using culturecode : (zh-HK), it is throwing an error called "locale is not loaded from moment locales" and the datetime picker is not working.
It would be helpful if anyone could suggest me any workaround.
Note: When I used culturecode : (zh-CN), it worked properly but I need to implement in (zh-HK).

Thanks
Kushal

**Comment by William-H-M** [comment]
Hi, one question are you loading moment.js or moment-with-locale.js? Becasue if you don't load the local this is not going to work for your case, I made a fiddle check it out and see if you get any output.

https://jsfiddle.net/William_/20oywuno/1/

**Comment by KushalMaz** [comment]
Hi William,
I have used "bootstrap-datetimepicker.min.js". Here is the path from I downloaded it.
" https://github.com/Eonasdan/bootstrap-datetimepicker "
It is working properly for "zh-CN" and "zh-TW" but it is not working for "zh-HK".
zh-CN - Chinese (China)
zh-TW - Chinese (Taiwan)
zh-HK - Chinese (Hong Kong)

It would be helpful if there is any workaround to make "zh-HK" workable in the existing  "bootstrap-datetimepicker.min.js"  as I won't be able to add new .JS file because that might hamper other language in the existing application.

Thanks
Kushal

**Comment by William-H-M** [comment]
Hi, what I mean was if you have added the moment.js library that is necessary to show the locales, if you add this new JS will NOT affect the other locale as datetimpicker use the scripts of moment.js to show the message and locales but if you want a work around it'll be to only add the need it locale that's zh-hk you can download it from here: https://github.com/moment/moment/blob/develop/locale/zh-hk.js

You can see the exception on the docs here http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#locale

So I would recommend using the moment-with-locales.js

**Comment by KushalMaz** [comment]
Hi William,
I have used moment-with-locales.js but still it is not working.
Then I used the workaround suggested by you that is to use this one "https://github.com/moment/moment/blob/develop/locale/zh-hk.js" and now it is working :-)

Thanks Man for your help.



Thanks
Kushal

**Comment by William-H-M** [comment]
Hi @KushalMaz  Great now as this is working can you please close this issue?
If any other problem appear just tell, have a nice day :)

**Comment by KushalMaz** [comment]
Sure.

Thanks
Kushal
