### ISSUE TITLE
Unable to set endDate on change of one datetimepicker

### ISSUE THREAD

**Issue by parth23** [Eonasdan/bootstrap-datetimepicker#2150]
This repo is no longer actively monitor or supported. All future work is being done to https://github.com/tempusdominus/bootstrap-3

**Comment by William-H-M** [comment]
Hi, Can you show code of what're doing?

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there hasn't been any feedback in more of 8 days, feel free to re open it if there's any doubt
