### ISSUE TITLE
Can i use viewMode : week ? 

### ISSUE THREAD

**Issue by zeing** [Eonasdan/bootstrap-datetimepicker#2152]
Can i viewMode is week like  this picture 

![image](https://user-images.githubusercontent.com/20161393/28924370-bc2143ce-788b-11e7-8fbc-4e7611fb7bf6.png)

thank you

**Comment by William-H-M** [comment]
Hi, No this is not possible for this plugin you only have:
`Default: 'days'`
`Accepts: 'decades','years','months','days'`

http://eonasdan.github.io/bootstrap-datetimepicker/Options/#viewmode

This issue can be close as is more an usage question than an error, have a nice day :)

**Comment by zeing** [comment]
thank you :)
