### ISSUE TITLE
DateTimePicker disabledDates assign String Array

### ISSUE THREAD

**Issue by AshishTechIT** [Eonasdan/bootstrap-datetimepicker#2153]
Hello All,

I'm using bootstrap datetimepicker with my ASP.net MVC5 application.
I'm trying to fetch the dates from DB, create an Array of disabled dates and then pass that array in jquery:-

C#
public String[] disabledDates { get; set; } // This model property gets set from database.

e.g. disabledDates = ["2017-08-29","2017-11-22"];

`<script type="text/javascript">
    $(function () {
var disabledDatesAr = '@Model.disabledDates';
$('#scheduleDate').datetimepicker({
useCurrent: false,
minDate: new Date(),
format: 'DD-MM-YYYY hh:mm A',
showTodayButton: true,
sideBySide: true,
showClose: true,
 showClear: true,
 toolbarPlacement: 'top',
disabledDates: disabledDatesAr
});
});
</script>`

But the above code doesn't work and DateTimePicker popup getting disabled.
Can anyone please guide me on how to assign this array value to disabled dates?
Thanks in advance.

**Comment by William-H-M** [comment]
Hi, I think you should populate the array of JS from the one of your MVC first bacause maybe of the way you're currently doing it is not working, so let's comfirng 2 things first:

1) does appear a console error?
2) if you do a console.log to disabledDatesAr what appears?

but for now populate the JS array of this old way and try it:

```
<script type="text/javascript">
    var myArray = [];
    @foreach (var d in Model.data)
    {
        @:myArray.push("@d");
    }
    alert(myArray);
</script>
```

**Comment by AshishTechIT** [comment]
Hello William-H-M,

Thanks for your response. I've resolved it using the suggestion provided in following link:-
[https://stackoverflow.com/questions/45502237/unable-to-assign-string-array-to-bootstrap-datetimepicker-disableddates](url)
