### ISSUE TITLE
keep old date when using datetimepicker for just picking time

### ISSUE THREAD

**Issue by vonboth** [Eonasdan/bootstrap-datetimepicker#2154]
I'm using the picker just for time picking (format: 'HH:mm')

The problem is: when I change the time the date is changed too and set to today but I want it to stay at the old date.

Example:
Orig. date is: 2017-08-01 11:00:00

I want to change from 11:00 to 12:00
But the date is also updated to the current day which results in 2017-08-07 12:00:00

How can I prevent datetimepicker to update the date?

**Comment by William-H-M** [comment]
Hi, can you provide a fiddle showing your case you can use whatever you prefer [JSFiddle ](https://jsfiddle.net/William_/20oywuno/)or a [JSbin](http://jsbin.com/?html,output)

**Comment by vonboth** [comment]
Thanks for the answer, the problem seems to be somewhere else.
I use the picker in combination with knockout and found the problem there
Sorry!
