### ISSUE TITLE
How to Enable only one particular date of every month with Bootstrap DatetimePicker

### ISSUE THREAD

**Issue by dhawaljos** [Eonasdan/bootstrap-datetimepicker#2155]
Hi All,

I am using Bootstrap DatetimePicker. I want to enable 20th of every month and all other dates must be disabled for user to select. Also, user should be able to change the month and year. I tried to do something like : 
var DATE = new Date();
     var dte = DATE.getDate();
     var Fdt = new Date();
     Fdt.setDate(20);
     var current = moment(Fdt); 
     this.$('#startdate').siblings(".datetimepicker").data("DateTimePicker").minDate(current).maxDate(current).enabledDates([current]); 

With the above code the 20th get enabled and rest of the dates in current month gets disabled, but i am not able to select next month.

**Comment by William-H-M** [comment]
Hi, what about using `enabledDates` it'll accept and array so just capture the year when this change on the picker and the months are basically always the same or even you can do that with the months using an event change you capture the month and the year

**Comment by dhawaljos** [comment]
Thanks William for the prompt response. if you have seen the code in the original thread of the issue i have already used enabledDates which works fine and sets the default date for current month as 20 in enabled mode, however i am not able to select next months date. Thats my issue, it would be great if you could help me on this.

**Comment by William-H-M** [comment]
Hi, you should for that avoid using `minDate `and `maxDate `
If you set thoose then you will unable to select anything more than the current date, just remove it and do an array for all the 12 months and always load the year depending on what year is selected for datepicker

**Comment by dhawaljos** [comment]
Hi William in my case how can i use dp.update there is no example mentioned in the link, can you please help to give an example for that.

**Comment by William-H-M** [comment]
Hi, you can use [this event](https://jsfiddle.net/William_/5mL0et6b/) and as on the doc say, if  YYYY it's bacause changed the year so then you do the enabledDates with that then you use the [moment get](http://momentjs.com/docs/#/get-set/), for by example years, you something like:

`e.viewDate.year(); //this will get the year on which you will be`

Note: e.viewDate this is a moment object so the all the methods of moment.js work on it

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
