### ISSUE TITLE
Unable to pick value for default locale

### ISSUE THREAD

**Issue by AshishTechIT** [Eonasdan/bootstrap-datetimepicker#2157]
Hello All,

I've created an ASP.net MVC application using bootstrap datetimepicker, moment.js and moment-with-locale.js. I want to make the datetimepicker display according to the local browser language.  Example, if the browser language is "fr-Fr", then set  "locale:'fr-Fr'" in datetimpicker. And if the corresponding browser language is not available, set it to default value "en".  
As per the moment documentation, it says that browser language "en-US" is considered as "en" by default. 

My scenario is to edit the datetime using datetimepicker. For any other language like Spanish("es") or French ("fr-FR), this code works with my bootstrap datetimePicker displaying DateTime value according to "locale", but if the browser culture is "en-US", it won't pick the value of DateTime and display blank box with predefined setting to current machine date and time.
I've created following fiddle to describe my issue:
http://jsfiddle.net/ashu_mdu/m45d5aqL/

Can anyone please guide me on how to resolve it? Thanks in advance.

**Comment by William-H-M** [comment]
Hi, @AshishTechIT I know it's been a while but I didn't want to comment till I get an easy answer and seems like I found it!

NOTE: It did work for me on my browser language "es-CO", I didn't test it out on other language so you should try it out.

Add this to you js:

`var userLang = navigator.language || navigator.userLanguage;`

This will give you things like es-CO, Fr, etc..

Please test it put, and if it's works close, thanks.
