### ISSUE TITLE
Not able to find the immediateupdate attribute 

### ISSUE THREAD

**Issue by Sidharthan1988** [Eonasdan/bootstrap-datetimepicker#2158]
Not able to find the immediate update attribute ,i need the datepicker to fire the event only after the datepicker is closed

**Comment by William-H-M** [comment]
Hi, do you mean like you want to know when the picker has been closed?
if yes then use [dp.hide](http://eonasdan.github.io/bootstrap-datetimepicker/Events/#dphide)
If not please give an example of what you want to do.

**Comment by Sidharthan1988** [comment]
I have a scenario where I pull report based on date and time filter ..
before selecting time the dp.change event is fired ,I want the event to
fire only after I select date time and close the picker ..please suggest
what changes I have to make

**Comment by William-H-M** [comment]
Hi, the only thing you have to do is capture the event for when the picker close, so do this with JQuery:

```
$('#myDatepicker').on('dp.hide', function(e) {
  console.log(e);
});
```
Where e is a clone of moments object you can see what it has on the console, that should be all just apply whatever you want inside the event.

with this done the issue should be close, thanks if any other doubt just say

**Comment by Sidharthan1988** [comment]
Will implement that and let You know if I still face issues... thanks for
the response

**Comment by Sidharthan1988** [comment]
Hi Will ,I was able to make the event trigger and call the required functions on the dp.hide.The fact is that i need the datepicker to be closed first and trigger the other functions in that event ..

 $('#datetimepicker2').datetimepicker().on('dp.hide', function (e) {
        console.log(e);

        Messages();
});

The messages() function gets called before the Bootstrap datepicket closes.Please suggest what i have to update to get the desired behaviour.

**Comment by William-H-M** [comment]
Hi, the event and it's function activate as soon as the picker has been hidden what you can do is use a setTimeOut function and set an amount of time that you see usable for your case see an example here: https://jsfiddle.net/William_/f0oge86c/

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
