### ISSUE TITLE
date and time range option required

### ISSUE THREAD

**Issue by vishalsingh119** [Eonasdan/bootstrap-datetimepicker#2163]
Kindly go through this image first-
https://ibb.co/gLDjp5

In one input we want to allow user to select two different dates(date range), and same functionality we want for hour(range), in one input user can select two time.

**Comment by William-H-M** [comment]
Hi, currently this is not possible for this picker you can maybe use [DateRangePicker](http://www.daterangepicker.com/#examples)
I'll be closing this for now, If you have any more doubts just ask :)
