### ISSUE TITLE
Highlight dates

### ISSUE THREAD

**Issue by lumenier1** [Eonasdan/bootstrap-datetimepicker#2164]
Are you f kidding me?
enabledDates and disabledDates only?? Apparently the dev is disabled xD
Where is activeDates option with tooltip/href data preset? This plugin is useless w/o highlighting multiple dates!
What was dev thinking about?

**Comment by William-H-M** [comment]
> Don't Like It? Code it Yourself!
https://blog.codinghorror.com/dont-like-it-code-it-yourself/

1) Wow what childish way to ask for something, are you sure you're old enough to even use Facebook?

2) Now apart from the above, why don't you code it by yourself? If you're saying it should be available, then go on and make useful Pull Request!

As this is not an issue nor a question about something, this will be close

**Comment by lumenier1** [comment]
Of course I will code it by myself cuz the dev is smart enough not to include this "musthave" option for any datepicker by default. When you buy a car, do you take it along with the wheels?

**Comment by William-H-M** [comment]
Good, happy coding :)

**Comment by lumenier1** [comment]
Ty
