### ISSUE TITLE
Allow only certain days

### ISSUE THREAD

**Issue by sarfraznawaz2005** [Eonasdan/bootstrap-datetimepicker#2167]
So I have two date pickers, start date and end date. Want I am trying to achieve is end date should only allow those dates that weekdays that was selected in start date. 

For example, if in start date, user selected a date that starts on Monday then end date calendar would only allow selecting days from Monday column and if user selected Tuesday then end date calendar would only allow selecting days from Tuesday column.

To do that, I could not find built-in way (may be I am missing something or may be moment.js can be used) so I did like this:

```
$('#Start').datetimepicker({
  format:"L",
  useCurrent: true,
  minDate:moment()
}).on('dp.show', function() {
  var weeksDisabled = [0, 1, 2, 3, 4, 5, 6];
  
  $('div.datepicker').on('click', 'td', function (e) {
    var index = $(this).index();    
    weeksDisabled.splice(weeksDisabled.indexOf(index), 1);
    //alert(weeksDisabled);
    
    $('#End').datetimepicker({      
      format:"L",
      useCurrent: false,
      daysOfWeekDisabled:weeksDisabled
    });    
        
  });  
});
```
As can be seen I am binding click event on clicked date `$('div.datepicker').on('click', 'td', function (e){} ` to get column/weekday of first calendar and then in second calendar only allow selecting days from same weekday. 

[This is working fine.](http://jsbin.com/sewuzujoka/1/edit?js,output)

However when I choose some other date from start date, end date still shows old column/dayweek selectable.

How can I make it so users can select dates only from **same day** in second calendar that they selected in first calendar?

Thanks for the help

**Comment by William-H-M** [comment]
Hi, the thing is that you're wrongly using the events, you don't call again the same Instantiation of the picker over the same again, what you have to do is call it once and after that just set the function as documented on
[Functions ](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/)
So what you'll do is something like this 

```
$('#Start').datetimepicker({
  format: "L",
  useCurrent: false,
//if you don't set it like this then after you choose another date
//won't allow you to pick again today date
  minDate: moment().startOf('day')
}).on('dp.show', function() {
  var weeksDisabled = [0, 1, 2, 3, 4, 5, 6]; 
  $('div.datepicker').on('click', 'td', function(e) {
    var index = $(this).index();
    weeksDisabled.splice(weeksDisabled.indexOf(index), 1);  
    $('#End').data("DateTimePicker").daysOfWeekDisabled(weeksDisabled);
  });
});
//you just call it once and no more!
$('#End').datetimepicker({
  format: "L",
  useCurrent: false,
});

$('#Start').on('dp.change', function(e) {
//This here is to set minDate as the date you choose, 
//because I mean you don't end this in the past, or yes?
  $('#End').data("DateTimePicker").minDate(e.date);
});
```

I left some anotations on the code of things you should add too

**Comment by sarfraznawaz2005** [comment]
@William-H-M thanks for the help, this does work.

Just one question: How do I make sure they can only select dates greater than today ? And for the end date the date they chose in start should be disabled too?

Thanks

**Comment by sarfraznawaz2005** [comment]
Okay I used this in start date:

```minDate: moment(moment().format('L')).add(1,'days'),```

and I can select dates greater than today. Hopefully it is right.

You can close this if you think above line won't create any issue :)

**Comment by sarfraznawaz2005** [comment]
Okay I did following to acheive what I asked in my last comment:

```
$startDate.datetimepicker({     
      //minDate: moment().startOf('day')
      minDate: moment(moment().format('L')).add(1,'days')
})
```

and

```
$startDate.on('dp.change', function (e) {
    $endDate.data("DateTimePicker").minDate(moment(e.date.format('L')).add(1,'days'));
 });
```

Hopefully I have done it right and you don't see issue in this ? If so, you can close this. Thanks :)

**Comment by William-H-M** [comment]
Hi, yea no problem but instead of
`moment(moment().format('L')).add(1,'days')`
use `moment().format('L').add(1,'days')` because what you're doing above is redundant
same for the 
```
$startDate.on('dp.change', function (e) {
    $endDate.data("DateTimePicker").minDate(e.date.format('L').add(1,'days'));
 });
```
as 'e' is a moment object

**Comment by sarfraznawaz2005** [comment]
Thanks @William-H-M
