### ISSUE TITLE
Not working in Chrome browser. Bootstrap Datetimepicker

### ISSUE THREAD

**Issue by Venkateshwarsri** [Eonasdan/bootstrap-datetimepicker#2169]
@Eonasdan @William-H-M  
https://jsfiddle.net/Venkatesh_srikanth/e2mwv05v/11/

Bootstrap Datetimepicker not working in chrome browser only. if we navigate to other tab or inspect the web page it works.

**Comment by Eonasdan** [comment]
well this is a bs **3** library and your using bs 4 alpha 6 so try https://github.com/tempusdominus/bootstrap-4
