### ISSUE TITLE
Setting maxDate changes the default date

### ISSUE THREAD

**Issue by monkiki** [Eonasdan/bootstrap-datetimepicker#2171]
It's quite annoying, but it seems impossible to set a maxDate without changing the default value. For example, if the default value is "01/02/2017" and maxDate is "05/06/2017" then the component shows "05/06/2017"

**Comment by William-H-M** [comment]
Hi, set useCurrent:false, and done, confirm and close please

**Comment by monkiki** [comment]
It worked, thanks!

**Comment by WhistlerHusky** [comment]
That's why!

Now it works, thanks.
