### ISSUE TITLE
daysOfWeekDisabled broke load default value from input

### ISSUE THREAD

**Issue by knedle** [Eonasdan/bootstrap-datetimepicker#2173]
example:

http://jsfiddle.net/knedle/0Ltv25o8/5563/

**Comment by King-ZeuS** [comment]
No, its not :)...
Updated fiddle
[http://jsfiddle.net/0Ltv25o8/5565/](url)

**Comment by King-ZeuS** [comment]
[http://jsfiddle.net/0Ltv25o8/5566/](url)

**Comment by King-ZeuS** [comment]
`$('#datetimepicker2').datetimepicker({
    locale: 'cs',
    useCurrent:false,
    daysOfWeekDisabled: [0, 6]
});`

**Comment by William-H-M** [comment]
Hi, 2 things:
1) Please add a description we can't just see a tittle an example and try to guess what's going on.
2) You're using an older version, do this happen with the latest version?

And as @King-ZeuS has given a valid answer I'll be closing this.

NOTE: I edited @King-ZeuS's answer to be formatted as code.
