### ISSUE TITLE
Start ajaxrequest if datetimepicker gets closed

### ISSUE THREAD

**Issue by One3Three7** [Eonasdan/bootstrap-datetimepicker#2174]
Hi,
I created an Dashboard for visualizing sensordata. Next to some other Userinputs the dashboard includes two Datetimepicker which presenting start- and enddate of a timeinterval. If the user makes inputs, an ajax request should transfer the userdata to the server. Previously I used this code to query the datetimepickers.

`	$("#datetimestart, #datetimeend").on("dp.change", function (e) {
		ajaxRequest();
	});`

If the user makes one change the ajax requests fires, which is very inefficient. It would be better if ajax fires, if the datepicker gets closed by the user. What I'm looking for is something like this:

`	$("#datetimestart, #datetimeend").on("dp.close", function (e) {
		ajaxRequest();
	});`

**Comment by William-H-M** [comment]
Hi, something like http://eonasdan.github.io/bootstrap-datetimepicker/Events/#dphide it's what you're looking for:

`$("#datetimestart, #datetimeend").on("dp.hide", function (e) { ajaxRequest(); });`

As this is a HOW TO question I'll be closing this, good luck :)
