### ISSUE TITLE
How to can I set 9:00 AM to 4: 00 PM only?

### ISSUE THREAD

**Issue by raprapbautista10** [Eonasdan/bootstrap-datetimepicker#2180]
I already use enabled hours 9 to 16 it's working but, until 3:59 only. I need to display 4:00. is there any way with my problem?

**Comment by William-H-M** [comment]
Sorry but I'm unable to reproduce this at least you show some code I see no problem

**Comment by raprapbautista10** [comment]
Hi William,

Thanks Inalready fix this issue.
