### ISSUE TITLE
Use a callback function for format

### ISSUE THREAD

**Issue by nealyip** [Eonasdan/bootstrap-datetimepicker#2183]
Is there any way to use a callback instead of a string for format so that I can produce a week picker like

https://medium.com/@thien.an.vo.nguyen/a-quick-week-picker-with-bootstrap-96c07e8b2447

Currently it's likely that only string is acceptable.

> format
> Default: false
> See momentjs' docs for valid formats. Format also dictates what components are shown, e.g. MM/dd/YYYY will not display the time picker.
>

**Comment by cargellio** [comment]
I had to change format and solved it this way:

	$('#event_type_id').change( function(e) {
		var opt = $('#event_type_id option:selected').text();
		changeFormat( $('input[name="start_at"]'), ( opt == 'Ziek' ? 'DD-MM-YYYY' : 'DD-MM-YYYY HH:mm' ) )
		changeFormat( $('input[name="end_at"]'), ( opt == 'Ziek' ? 'DD-MM-YYYY' : 'DD-MM-YYYY HH:mm' ) )
	});
	
	var changeFormat = function(el, format) {
		var initiated = $(el).data('DateTimePicker');
			if (initiated !== undefined) {
				$(el).data('DateTimePicker').destroy();
			}

			$(el).datetimepicker({
			format: format,
		});
	};

hope it helps
