### ISSUE TITLE
bootstrap datetimepicker loses keyboard navigation when selecting a date

### ISSUE THREAD

**Issue by Merji** [Eonasdan/bootstrap-datetimepicker#2184]
When i focus on the input datetimepicker first time after page load the widget displays correctly and i can navigate inside it using keyboard keys perfectly, but once i choose a date using keyboard enter key and get back to the same input, the widget displays correctly but i can't use keyboard keys to navigate inside it anymore,

Is there a way to handle this??
Thank you.

**Comment by William-H-M** [comment]
Hi, for this please refer to #1690, and to be more prices this comment https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1690#issuecomment-284269985

Closing as a duplicate.
