### ISSUE TITLE
Clock and select icon is not available in Bootstrap datetimepicker in Internet Explorer 11

### ISSUE THREAD

**Issue by KushalMaz** [Eonasdan/bootstrap-datetimepicker#2188]
I am working in MVC application and Bootstrap DateTime Picker (version : 4.17.37) is being used there.
In some systems, the datetime picker is not working properly in IE11. Time clock and select icon is invisible. I have attached two screenshots. 
'Proper' screenshot is from the system where it works fine.
'Wrong' screenshot took from the system where the issue exists. I have cleared the cache from browser multiple times, but it did not work. Version of the browser is also cheked. Strangely the system where it is working and the system where it is not working has the same version of the browser.
It would be helpful if anyone could suggest me to get rid of this issue.

![proper](https://user-images.githubusercontent.com/30590341/31230898-04052aae-aa03-11e7-8dbf-f9fa94f0c6bb.jpg)
![wrong](https://user-images.githubusercontent.com/30590341/31230897-03f457b0-aa03-11e7-9025-aa4bca1aedc8.jpg)

Thanks
Kushal

**Comment by William-H-M** [comment]
Hi, this seems more a problem of Glypicons than the widget, and it seem is there some configuration on IE11 that cause this:

https://stackoverflow.com/questions/25281286/bootstrap-3-2-0-glyphicons-are-not-displaying-in-internet-explorer

https://stackoverflow.com/questions/39056541/font-awesome-bootstrap-glyphicons-not-displaying

https://stackoverflow.com/questions/42075631/bootstrap-glyphicons-not-displaying-in-windows-10-in-ie11

This is something the widget cannot control, so I'll be closing this, good luck.
