### ISSUE TITLE
How to hide the calendar dropdown picker

### ISSUE THREAD

**Issue by Luca4k4** [Eonasdan/bootstrap-datetimepicker#2190]
Hi, 
there's an option to hide the calendar picker? I can't find it! 
I want only to use the check over field without showing the calendar.

Regards, Luca

**Comment by William-H-M** [comment]
Sorry but I do not understand which dropdown picker? this plugin do not use any dropdown, list, select, etc.

If you're not using the calandar, then for what to include the picker?

> I want only to use the check over field without showing the calendar.

I don't really understan maybe an image example?

**Comment by Luca4k4** [comment]
I would like to disable the calendar picker, letting just the input field. There isn't an option as "hideCalendar" to set to true or something similar?


(Sorry for my english!)
Luca

**Comment by William-H-M** [comment]
Hi, sorry but for what just an input? and not the calendar, the calendar is what it make this plugin works! 
Or do you mean something like not showing the calendar icon in the input? something like this:

![imagen](https://user-images.githubusercontent.com/24443241/31408244-764ec2d2-adcd-11e7-85eb-06b00a328cb1.png)

If yes just follow this link:  http://eonasdan.github.io/bootstrap-datetimepicker/#no-icon-input-field-only
and if not, then sorry but I think you're in the wrong place or I really don't understand what are you looking for.

**Comment by Luca4k4** [comment]
Sorry, I'm explaining a bit bad. I have this situation:

```
<div class="form-group">
       <label>Birth Date</label>
       <input type='text' class="col-xs-12 form-control" placeholder="gg/mm/aaaa" 
                   id='datePicker' name="dateBirth"  required/>
</div>
......
......
$('#datePicker').datetimepicker({
     viewMode: 'years',
     format: 'DD/MM/YYYY',
     minDate: '01/01/1900',
     maxDate: 'moment',
});
```

With this result: [https://ibb.co/ivFEDw](url)

So, when i click on the field, calendar is showed (inside the red circle in my image). I want this calendar is not showed, never. In other words, i want to use the plugin only to check if the format of date (hand-written) inside the field is valid.
I see the documentation, but i can't find an options to do it!

**Comment by William-H-M** [comment]
Hi, for yo to do that it not necessary to use this plugin the only that you need is [`moment.js`](http://momentjs.com/)

just doing something like this will suffice your needs:
`console.log(moment('14-14-2012', 'DD-MM-YYYY',true).isValid());`

Just follow this guide: http://momentjs.com/docs/#/parsing/string-format/ almost at the end of that part you can see the `isValid()` function.

> I want this calendar is not showed, never.
> I see the documentation, but i can't find an options to do it!

That's because is not possible to do it at least not with an option form this plugin.

For more question about this please use [StackOverflow](https://stackoverflow.com/questions/tagged/momentjs)

**Comment by wilyjaromj** [comment]
I know this is an old conversation, but I was looking for the same thing and I did this and it works great!

$('date-selector').focus(function () {
        $('.bootstrap-datetimepicker-widget').css('display', 'none');
});
