### ISSUE TITLE
Dual selected dates

### ISSUE THREAD

**Issue by Albejr** [Eonasdan/bootstrap-datetimepicker#2194]
See the attached gif.
Related in lasted version "Firefox", "Edge", and "Opera". 

![dualdate](https://user-images.githubusercontent.com/24717256/31625613-69517d56-b285-11e7-9a89-e10a8813af90.gif)

**Comment by William-H-M** [comment]
Hi, let me guess are you in a country with currently DST? If yes, that's the reason and explanation given on #2182, this is not exactly a duplicate but kinda.

NOTE: This does not happen to me because I'm not on a DST Zone

**Comment by Albejr** [comment]
Exactly. Thank's.
