### ISSUE TITLE
TypeError: offset is undefined

### ISSUE THREAD

**Issue by El-Mahbub** [Eonasdan/bootstrap-datetimepicker#2196]
I got an error = TypeError: offset is undefined, how i can solve this ?
And i was searching a line codes of error.
Here is line : 
// Top and bottom logic
                if (vertical === 'auto') {
                    if (offset.top + widget.height() * 1.5 >= $(window).height() + $(window).scrollTop() &&
                        widget.height() + element.outerHeight() < offset.top) {
                        vertical = 'top';
                    } else {
                        vertical = 'bottom';
                    }
                

I was trying to solve that error with this codes : 
typeof offset === 'undefined' ? offset = (component || element).offsetParent() : offset = offset;
typeof position === 'undefined' ? position = (component || element) : position = position;
But css codes that will not work
Thank

**Comment by andrewtite** [comment]
I'm having this same issue and can't find a solution.
Added everything exactly as specified and I'm getting the following error when I click the datetime textfield:
TypeError: offset is undefined

PLEASE HELP. OBI-WAN KANOBI, YOU'RE MY ONLY HOPE! :(

**Comment by inkawarrior** [comment]
@andrewtite in case you still need it
change
`offset = (component || element).offset(),`
to
`offset = (component.offset() || element.offset()),`

in the place function (line 405) in bootstrap-datetimepicker.js

**Comment by UpwardProcess** [comment]
I ran into a similar problem after upgrading to Bootstrap 4 and using input groups with a markup like this:

`<div class="form-group"><label for="datetime">Label</label>
    <div class="input-group date" id="datetime-datetimepicker">
        <input id="datetime" class="form-control" name="datetime" type="text">
        <div class="input-group-append">
            <span class="input-group-text"><i class="fa fa-calendar"></i></span>
        </div>
    </div>
</div>`

I was running `.datetimepicker()` on `#datetime-datetimepicker`. Changing it to the input element itself (`#datetime`) fixed the problem for me.
