### ISSUE TITLE
The control is not displayed when we add an alert() into dp.change event

### ISSUE THREAD

**Issue by alexsantosquispe** [Eonasdan/bootstrap-datetimepicker#2197]
The behavior only happens the first time when we select a new date and the alert is shown and the widget isn't.
Here an example of the code:

```
$(".date").datetimepicker({
        format:'YYYY-MM-DD',
        useCurrent: true,
        icons: {
          time: "fa fa-clock-o",
          date: "fa fa-calendar",
          up: "fa fa-arrow-up",
          down: "fa fa-arrow-down"
        }
		}).on('dp.change', function (event) {
        alert("value was changed");
    }).find('input:first').....
```

The issue was replicated on v4.14.30 and v4.17.47
on v3.1.3 it's working correctly.

**Comment by ramppt** [comment]
Hi, please help me regarding this

When I tried to set the date and time value for inline bootstrap datetimepicker using  jQuery ("#datetimepicker1").data('DateTimePicker').date(11/04/2017 11:23:45);
I got error in console uncaught. Type error:  can't read property date of undefined..


Please help me regarding this. It's urgent.. 
Is there any other way to set date and time in datetimepicker..

**Comment by ramppt** [comment]
Hi, please help me regarding this

When I tried to set the date and time value for inline bootstrap datetimepicker using  jQuery ("#datetimepicker1").data('DateTimePicker').date(11/04/2017 11:23:45);
I got error in console uncaught. Type error:  can't read property date of undefined..


Please help me regarding this. It's urgent.. 
Is there any other way to set date and time in datetimepicker..

**Comment by ramppt** [comment]
Please help me regarding this. I am struck with this issue

**Comment by William-H-M** [comment]
@ramppt  as I said before you need to use JQuery obove you're not using it:
`("#datetimepicker1").data('DateTimePicker').date(11/04/2017 11:23:45)`
you need to put 
`$("#datetimepicker1").data('DateTimePicker').date('11/04/2017 11:23:45')`

If you continue to spamming other issues I'll have to block you of the repo.
If you need more help ask at https://stackoverflow.com/

**Comment by ramppt** [comment]
Hi William, 
I have done in the same way. But still throws the same error. Any other way to set the value.

**Comment by William-H-M** [comment]
@ramppt Create an issue and make a [Minimal, Complete, and Verifiable example ](https://stackoverflow.com/help/mcve)

**Comment by ramppt** [comment]
Ok William. Thank you. I will post the example.
Meanwhile can you tell me how to set date and time for bootstrap datetimepicker other than that method..
Thanks once again

**Comment by nakhla** [comment]
only the first change is working
