### ISSUE TITLE
Datetimepicker month/year selection ignores sidebyside=false

### ISSUE THREAD

**Issue by Ekjon** [Eonasdan/bootstrap-datetimepicker#2198]
I am using Bootstrap version 3.3.6 and eonasdan-bootstrap-datetimepicker version 4.17.42.

 I have this datetimepicker configured as:

```
$(".dateTimePickerElement").datetimepicker({
  toolbarPlacement: "top",
  showTodayButton: true,
  sideBySide: false,
  showClear: true,
  showClose: true,
  useCurrent: true,
  keepOpen: true,
  locale: "en",
  format: "YYYY-MM-DD h:mm A",
  debug: true
});
```

When the year month is clicked to make a selection of months or years, it ignores sideBySide: false and shows up wide on the screen on other elements like this:

![imagen](https://user-images.githubusercontent.com/24443241/31972261-5f269260-b8e5-11e7-94c5-01d224baa310.png)

However, when date or time picker is open, it works fine.
Help will be appreciated from Eonasdan team or anyone else.
Thanks.

**Comment by Ekjon** [comment]
@Eonasdan , @eonasdan-bot - any inputs on this? 
Thanks.

**Comment by William-H-M** [comment]
I remember have seen this before on the issues page and was related to custom styles with a `.td .row` that's the only why there should be a problem. Remove your custom css code and see if it's fixed

**Comment by Ekjon** [comment]
We are not using any tds, and as mentioned - it works perfectly with the date or time pickers. 
But breaks only when Year/Month is clicked to display Year/Month options.

**Comment by William-H-M** [comment]
Sorry but you probably must have some style (or something else, some dynamic JavaScript/JQuery inserting some style) crashing something as using a fiddle with the same versions that you reported I have no issues with the Year/Month view and even if set `sideBySide: true,` the style won't look like that.

![imagen](https://user-images.githubusercontent.com/24443241/32064888-c5186dc6-ba40-11e7-97f3-63ad147a5625.png)

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.

**Comment by AndreaRylander** [comment]
I have the same problem, the thing is I need my custom css and I need to import my custom css last so the date-picker css doesnt affect other elements on my site, so is there another workaround?

**Comment by helenaraya** [comment]
@Ekjon did you end up solving the issue. Please advise me on what I should do

I am having exactly the same problem as yours.

**Comment by helenaraya** [comment]
@AndreaRylander  did you end up solving this problem because I am having the same issue.

**Comment by chriseyes** [comment]
Hello all, I may have a solution for this. I just find out for my project were was the problem.
I had a parent (td) with a "white-space:nowrap", like I had my datepicker inside a td with this value.
Then if you really need it like me, I add white-space:normal to the principal class of the datepicker.
I hope it might help
