### ISSUE TITLE
Date Picker cutting from right side

### ISSUE THREAD

**Issue by chauhanbhargav** [Eonasdan/bootstrap-datetimepicker#2199]
![image](https://user-images.githubusercontent.com/27570488/32089602-8c8caab2-bb08-11e7-829a-e9b65d629183.jpg)

**Comment by William-H-M** [comment]
Hi, you should check your custom css, this seem to be a conflict with your template

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
