### ISSUE TITLE
Setting defaultDate on DateTimePicker, with use of functions from dtp on event firing

### ISSUE THREAD

**Issue by joseeduardorebelo** [Eonasdan/bootstrap-datetimepicker#2205]
I'm using Bootstrap Datetimepicker to have a calendar on my page and select days and hours.

I'm setting up this way:

```
var $dtp = $("#datetimepicker1");
$(function () {
      $dtp.datetimepicker({
                format: 'DD-MM-YYYY HH:00',
                locale: 'pt',
                defaultDate: d,
                minDate: dMin,
                maxDate: dMax
            });
        });
```
And I have trigger "dp.change":

```
$dtp.on("dp.change", function(e) { 
    d = $dtp.data("DateTimePicker").date().toDate();
});
```
`dMin`, `dMax` and `d` are Date Objects:

```
var d = new Date(); //actual Date
var dMin = new Date(2012, 0, 1, 0);
var dMax = new Date(); dMax.setDate(dMax.getDate()+2); dMax.setHours(0); //more 2 days
```
Well, I need to setUp `defaultDate`, because sometimes `d` are changed and it's not the current date, but another date between `dMin` and `dMax`.

The problem is that, no matter if `d` is current or not, with `defaultDate` on the initializing setup of datetimepicker, the calendar doesn't work.

Inspecting the error, on console, I conclude that `$dtp.data("DateTimePicker") `is undefined, when first `"dp.change"` occurs, but only when I have defaultDate on initializing setup.

I'm having some problems on solving this.

Thanks.

**Comment by William-H-M** [comment]
Hi, could you provide a [fiddle ](https://jsfiddle.net/William_/20oywuno/)of the error?
Note: is better if you set up those dates using [moment.js](http://momentjs.com/) It'll be easier to read and after all you **have to** include it with this library.

preferably follow the [mcve](https://stackoverflow.com/help/mcve) pattern
