### ISSUE TITLE
Side By Side

### ISSUE THREAD

**Issue by msiqueira9** [Eonasdan/bootstrap-datetimepicker#2207]
Hi all,
I know there is an option to display the time on the side of the calendar, but people here wants to display it one on top of the other, is that even possible?
Have the calendar on top and the time component underneath it?

**Comment by William-H-M** [comment]
Hi, you can do it but this depends a lot of the Bootstrap grid system, so... you can do it but it's not gonna be pretty...
What you want is this:
![imagen](https://user-images.githubusercontent.com/24443241/33320252-98bf792a-d40f-11e7-8263-c4c9a1fd635b.png)

That style up there is definied by 2 two divs:

`<div class="datepicker col-md-6">` and `<div class="timepicker col-md-6">`
As you can see they are with the BS Grid system so if your width is > 992px they will take the media rules, what you could try to do is change that to a `col-lg-6` or something like that and will end like this:

![imagen](https://user-images.githubusercontent.com/24443241/33320473-6007771c-d410-11e7-88af-beb7a78f77c6.png)

Is pretty? For me, yeah sure, I actually don't care and my clients neither...

Now where can I change that?! Well the fast forward option is using Jquery something like when the widget show:

```
$("#myDatepicker").on('dp.show', function(e) {
  $("div.datepicker.col-md-6").removeClass('col-md-6').addClass('col-lg-6');
  $("div.timepicker.col-md-6").removeClass('col-md-6').addClass('col-lg-6');
});
```
Is this a dirty trick, yeap pretty much. It does work? Yes, so just ignore it :) (That's what you're gonna tell to your fellow developers...)

The other one is looking into the code and change it for yourself, but not sure where those lines are... so.... Good luck :D

Hope it works for you!

**Comment by msiqueira9** [comment]
Hi William,
Thank you for your reply, I was reading a bit further the documentation and apparently there in a function that does that, I havent tried because people here gave up on the idea but the specs says
collapse(collapse)
Takes a boolean. If set to false the picker will display similar to sideBySide except vertical.

**Comment by William-H-M** [comment]
Hey I didn't remember that one! thanks.
