### ISSUE TITLE
when I select one date, then del some words to '12' by keyboard, It became 12/01/0000 12:00 AM

### ISSUE THREAD

**Issue by martinko2009** [Eonasdan/bootstrap-datetimepicker#2208]
This repo is no longer actively monitor or supported. All future work is being done to https://github.com/tempusdominus/bootstrap-3

when I select one date, then I get the date like 12/07/0000 12:00 AM,  after that, I delete some words to '12' by keyboard, It became 12/01/0000 12:00 AM.

you can get the problem by [https://eonasdan.github.io/bootstrap-datetimepicker/](url)

Sometimes I want to input the date manually by keyboard. When I input some date to half, the component begins to transform the string to date. I hope that  the component doesn't transform the date, and return this string when user input  some dates which format  is not fit to the format.

**Comment by William-H-M** [comment]
>when I select one date, then I get the date like 12/07/0000 12:00 AM
>I delete some words to '12' by keyboard, It became 12/01/0000 12:00 AM.

You're probably using an older version, nothing of the above happens to me.

>I hope that the component doesn't transform the date, and return this string when user input some dates which format is not fit to the format.

http://eonasdan.github.io/bootstrap-datetimepicker/Options/#keepinvalid

Still if you use format with hour you WILL (**_IF_** the original format) need to somehow put an hour even if using `keepInvalid`
