### ISSUE TITLE
How to Set Element Container?

### ISSUE THREAD

**Issue by mehmetalidumlu** [Eonasdan/bootstrap-datetimepicker#2210]
Hi,
Is this plugin support set container? If it supports this when how can i set element container?
```
$(selector).datetimepicker({
    container:'body'
});
```
Thanks...

**Comment by William-H-M** [comment]
Hi, sorry for late response, but yes somehow you can but it's need to be relative positionated.

[widgetParent](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#widgetparent)

> On picker show, places the widget at the identifier (string) or jQuery object if the element has css position: 'relative'

**Comment by elementum** [comment]
it does not work even though body has position:relative set.
