### ISSUE TITLE
Wrong inittializaion if used minDate

### ISSUE THREAD

**Issue by d-aven** [Eonasdan/bootstrap-datetimepicker#2212]
Please see demo:
https://jsfiddle.net/bh5easnm/2/
In this demo you can see 
1) input with 
`data-date-format="M/D/YY"`
2) input with 
```
data-date-format="M/D/YY"
data-date-min-date="2017-12-22"
data-date-max-date="2018-01-25T07:31:05+0000"
```
3) input with 
```
data-date-format="M/D/YY"
data-date-min-date="2017-12-22T00:00:00+0000"
data-date-max-date="2018-01-25T07:31:05+0000"

```
All inputs have `value="12/26/17"`.

Despite the value is the same for all inputs there are different dates after inittialization.
Another issue is in the third input - if you click on the 23-30 of December and then you will not be able to choose 22

**Comment by kelishrestha** [comment]
Having the same issue as well. 

**The value for datetime picker defaults to end date whenever max date is set.** 

Setting minimum and maximum date defaults to minimum or maximum date rather than input value. This is not selecting actual date. Need to fix this ASAP since I am working with timezones and datetime values.

**Comment by William-H-M** [comment]
Hi, it's been a while huh.

Well the way to workaround without causing a big problem is actually simple set `useCurrent: false`

And.....that's it solve.

But wait who is the culpirt and when do we start the witch hunt!

The culpirt:

https://github.com/Eonasdan/bootstrap-datetimepicker/blob/5a991bfff0b7a721c73d482d06bcbaf9f1e3fc98/src/js/bootstrap-datetimepicker.js#L1713

When setting `maxDate` It'll check if `date` (that's today's date) is after the `maxDate` and in this specific case it was; then our friend `useCurrent` will be false and won't get inside the condition and boom magic!

When do we start the witch hunt: No, thanks

Another way to fixed, if fixed will be pushed?: Not that I know and no, the proyect is on code freeze.
