### ISSUE TITLE
$(...).data(...).getDate is not a function

### ISSUE THREAD

**Issue by benjieperez** [Eonasdan/bootstrap-datetimepicker#2214]
Here's my fiddle and it says its not a function
i just followed what it is in the documentation
http://jsfiddle.net/0Ltv25o8/6061/

**Comment by William-H-M** [comment]
I don't think you have read enough of the documentation `getDate` doesn't exist, but [`date` ](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#date)does

Second you're calling the function immediately at the next line of the call of the picker and `date`  will return null and [`.format()`](http://momentjs.com/docs/#/displaying/format/) needs a valid date, moment not null

**Comment by benjieperez** [comment]
how to get date in the datetimepicker?

**Comment by William-H-M** [comment]
I have literrally linked you to the documents, just replace `getDate` with `date`
