### ISSUE TITLE
How to prevent disabled dates selection with keyboard direction keys 

### ISSUE THREAD

**Issue by busrauman** [Eonasdan/bootstrap-datetimepicker#2215]
I have an array to disable dates on calendar but when i change the date with keyboard direction keys, i can pick the date but this is disable date. How to prevent this ?

**Comment by William-H-M** [comment]
Hi, well this quite a bug but I can give you a workaround, just on the change date if the element is disabled the move it to the next [_or the date before, your decision_] date.

```
const disabledDates = [
  moment("01/21/2018"),
  moment("01/22/2018"),
  moment("01/23/2018"),
  moment("01/24/2018"),
]


$(document).on('dp.change', '#myDatepicker', function(e) {
  if (itShouldBeDisabled(e.date)) {
    console.log("changing");
    $('#myDatepicker').data("DateTimePicker").date(e.date.add(1, 'day'));
  }
});

function itShouldBeDisabled(element) {
  for (let i = 0; i < disabledDates.length; i++) {
    if (moment(element).isSame(disabledDates[i], 'day')) {
      return true;
    }
  }
  return false;
}
```

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.

**Comment by edgrod01** [comment]
hi, excellent but how can i do for disabledweekdays example saturday or sunday :(

**Comment by busrauman** [comment]
if you wanna disable reqular day of week you can use dayOfWeekDisabled  parameter this can take an array between 0 and 6 these numbers refers days in an week .
``
$("#inputId").datetimepicker({
            format:'mm/dd/yyyy hh:ii',
            autoclose: true,            
            weekStart: 1,
            todayHighlight: true,
            firstDay : 1,
            startDate: new Date(),
            todayBtn: true,
            daysOfWeekDisabled: [0, 6]
            });
Also you can use unregular dates to disable dates for example you have an array include dates 
like disabledDates in below you use datesDisabled parameter in datetimepicker
``
var disabledDates = ['01/21/2018' , '15/21/2018', '02/21/2019']
$("#inputId").datetimepicker({
            format:'mm/dd/yyyy hh:ii',
            autoclose: true,            
            weekStart: 1,
            todayHighlight: true,
            firstDay : 1,
            startDate: new Date(),
            todayBtn: true,
            datesDisabled: disabledDates
           });

**Comment by edgrod01** [comment]
hi!
Thanks for your answer, but my question was wrong... im using dayOfWeekDisabled and datesDisabled for the 2 cases when i need it. example 

`$disabledDates=data;
			$('#fecha').data("DateTimePicker").destroy();
			
			$('#fecha').datetimepicker({
				format: "YYYY-MM-DD",
				icons:{
					previous: "fa fa-arrow-circle-left",
					next: "fa fa-arrow-circle-right"
				},
				disabledDates: data,
				widgetPositioning: {
					horizontal: 'right',
					vertical: 'bottom'
				},
				maxDate: $disabledDates[$disabledDates.length-1],  
				minDate: $disabledDates[0], 
				daysOfWeekDisabled: [0, 6], 
			});`
now, when i use the keyboard arrows for displace en the calendar, this allows select daysOfWeekDisabled and  it should not

Thanks

**Comment by William-H-M** [comment]
Well is basically the same logic just change the array `disabledDates ` for an array of `daysOfWeekDisabled`
and the method of `itShouldBeDisabled` change it like this

```
function itShouldBeDisabled(element) {
  for (let i = 0; i < daysOfWeekDisabled.length; i++) {
    if (moment(element).day() == daysOfWeekDisabled[i]) {
      return true;
    }
  }
  return false;
}
```

**Comment by edgrod01** [comment]
thanks,

**Comment by Wonderfulintl-tel-input1** [comment]
> thanks,





https://lnkr.fun/3111159
