### ISSUE TITLE
INC/DEC Hour function down after define enableHours

### ISSUE THREAD

**Issue by Supertramplee** [Eonasdan/bootstrap-datetimepicker#2216]
such as, i set 
`{
enableHours=[7,19], 
stepping:60,
defaultDate:timenow.getFullYear()+'-'+(timenow.getMonth()+1)+'-'+timenow.getDate()+' '+(timenow.getHours()-12)+':00', 
}`
then ,   INC/DEC hour button didn't work ....

temperately,i add var stepH under option settings.and made some change on js. 
i didn't know if it's really a bug or it's just my setting error..

FYI

`var c = function(c, d) {`
...
`ea = {`
...
`incrementHours: function() {
                var a = e.clone().add(d.stepH, "h");
                R(a, "h") && aa(a)
            },
`
`
decrementHours: function() {
                var a = e.clone().subtract(d.stepH, "h");
                R(a, "h") && aa(a)
            },
`
...
`
l.stepH = function(a) {
            return 0 === arguments.length ? d.stepH: (a = parseInt(a, 10), (isNaN(a) || a < 1) && (a = 1), d.stepH = a, l)
        },
    }
}`

`a.fn.datetimepicker.defaults = {`
...
`stepH:1,`
...
`keyBinds:{`
    ....
            `"control up": function(a) {
                if (a) {
                    var b = this.date() || this.getMoment();
                    a.find(".datepicker").is(":visible") ? this.date(b.clone().subtract(1, "y")) : this.date(b.clone().add(this.stepH(), "h"))
                }
            },
            "control down": function(a) {
                if (a) {
                    var b = this.date() || this.getMoment();
                    a.find(".datepicker").is(":visible") ? this.date(b.clone().add(1, "y")) : this.date(b.clone().subtract(this.stepH(), "h"))
                }
            },`
    ...
    `}`
`}`

**Comment by William-H-M** [comment]
Your code is way too hard to read, l[earn to highlight your code](https://help.github.com/articles/creating-and-highlighting-code-blocks/) and create a [MCVE as of StackOverflow](https://stackoverflow.com/help/mcve)

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
