### ISSUE TITLE
Not able to use time picker when minDate and maxDate are set on the same day but hours differs

### ISSUE THREAD

**Issue by jonperron** [Eonasdan/bootstrap-datetimepicker#2219]
Hello everyone,

I got an odd behaviour when using bootstrap-datetimepicker v. 4.17.47.
Here is my config:
```
format: 'YYYY-MM-DD HH:mm',
showTodayButton: true,
useCurrent: false,
showClear: true,
minDate: moment('{{ ts_beg }}'),
maxDate: moment('{{ ts_end }}')
```
When setting `minDate `and `maxDate `to the same day but with different hours, let's say `2018-2-1 00:00` and `2018-2-1 02:00`, I am unable to choose both date and time:
![peek 2018-02-05 09-33](https://user-images.githubusercontent.com/18113590/35794888-aaf3dbf8-0a57-11e8-9fa8-94ed7d0e1440.gif)
Does anyone has a workaround to solve this issue ?

**Comment by William-H-M** [comment]
There's a simple workaround for this and it is using [functions of min/max Date](eonasdan.github.io/bootstrap-datetimepicker/Functions/#minmaxdate) here an example:

`$('#myDatepicker').data("DateTimePicker").maxDate(MaxDate);`

This should fix the problem

**Comment by jonperron** [comment]
I saw your answer @William-H-M on SO and that's just perfect ! Many thanks for the hint, I'm sure it will be pretty useful for a lot of people.
