### ISSUE TITLE
Can i only use monthpicker?

### ISSUE THREAD

**Issue by colordove** [Eonasdan/bootstrap-datetimepicker#2220]
when I set `format: 'MM'` and `viewMode: 'months'`, I also can select years. is there any way to hide yearspicker?

![image](https://user-images.githubusercontent.com/11832969/35910420-7cde105e-0c31-11e8-8e78-19efa1582067.png)

**Comment by William-H-M** [comment]
Hide it with css, this a how-to question so closed
```
.datepicker-months thead {
  display: none;
}
```
