### ISSUE TITLE
datetimepicker mindate when current date selected the time gets disabled

### ISSUE THREAD

**Issue by milind777** [Eonasdan/bootstrap-datetimepicker#2221]
when i put mindate : new Date() inside bootstrap datetimepicker . It disables the back dates as expected 
but when i click on clock symbol it throws a error in console " Uncaught TypeError: Cannot read property '$trigger' of undefined" and it disables the time . 

Code:

html:
`<div class='input-group date' id='datetimepicker1'>
<input id="startDate" path="startDate" type="text"
placeholder="Start Date" class="form-control"
required="required" readonly="true" />
																<span class="input-group-addon"><span
																	class="glyphicon glyphicon-calendar"></span> </span>
															</div>
															
															
															<div class='input-group date' id='datetimepicker2'>
																<input id="endDate" path="endDate" type="text"
																	placeholder="End Date" class="form-control"
																	required="required" readonly="true" />
																<span class="input-group-addon"><span
																	class="glyphicon glyphicon-calendar"></span> </span>
															</div>`
js:

`$("#datetimepicker1").on("dp.change",` function(e) {

		validDateTimepicks();
	}).datetimepicker({
		 minDate: new Date(),
		  useCurrent: false,
		  format: 'YYYY-MM-DD HH:mm:ss'
	});

	$("#datetimepicker2").on("dp.change", function(e) {

		validDateTimepicks();
	}).datetimepicker({
		 minDate:new Date().setHours(0,0,0,0),
		  useCurrent: false,
		  format: 'YYYY-MM-DD HH:mm:ss'
	});

	function validDateTimepicks() {
		if (($('#startDate').val() != '' && $('#startDate').val() != null)
				&& ($('#endDate').val() != '' && $('#endDate').val() != null)) {
			var fromDate = $('#startDate').val();
			var toDate = $('#endDate').val();
			var eDate = new Date(fromDate);
			var sDate = new Date(toDate);
			if (sDate < eDate) {
				alert("endate cannot be smaller than startDate");
				$('#startDate').val("");
				$('#endDate').val("");
			}
		}
	}
`

**Comment by William-H-M** [comment]
Your code is way too hard to read, format it
