### ISSUE TITLE
You keep closing topics on date submit and display.. why ?

### ISSUE THREAD

**Issue by Sen-Sai** [Eonasdan/bootstrap-datetimepicker#2227]
Logic states you want to have the user choose a date in there preferred way save it in a way the server can handle.
Why all the fuzz with hooking in the submit etc when you should just make it an option setting.
If you do not want to, then just say "I don't want to". Then people can look elsewhere for a datepicker that does support it.

**Comment by William-H-M** [comment]
Hi, if you mean about issue 2222 it was a How-to and not an issue and wasn't closed but after a given solution. Others didn't give a feedback nor were an issue but more a how-to that should be asked at [StackOverflow](https://stackoverflow.com/questions/tagged/eonasdan-datetimepicker).

This is not an issue so this will be closed as invalid
