### ISSUE TITLE
bootstrap datepicker popup scroll on mouse scroll

### ISSUE THREAD

**Issue by patil-ganesh** [Eonasdan/bootstrap-datetimepicker#2228]
bootstrap datepicker popup scroll on mouse scroll issue
![screenshot from 2018-02-16 11-58-43](https://user-images.githubusercontent.com/31791156/36296528-a879ea42-1313-11e8-9ba6-6857a475f1cb.png)

**Comment by patil-ganesh** [comment]
bootstrap datepicker popup scroll on mouse scroll issue
![screenshot from 2018-02-16 11-58-43](https://user-images.githubusercontent.com/31791156/36296528-a879ea42-1313-11e8-9ba6-6857a475f1cb.png)

**Comment by William-H-M** [comment]
Hi, I'll need more info than a simple message and a not so clear image

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
