### ISSUE TITLE
datetime picker not working within a webgrid

### ISSUE THREAD

**Issue by vermapraveen** [Eonasdan/bootstrap-datetimepicker#2229]
Hi,

I am using bootstrap datetimepicker 4 in edit mode in MVC webgrid.
when the grid is rendered i see that the calender opens only for the first row. it doesnt show up for any other rows. 
i dont see any errors in console too.
can you please refer me to a place there is an example to this.
i am a first time user of this datepicker. 
Please help.

**Comment by William-H-M** [comment]
Hi, this is a how-to question and will be too broad to ask it here I recommend you to ask it on [StackOverflow](https://stackoverflow.com/questions/tagged/eonasdan-datetimepicker)
