### ISSUE TITLE
"togglePeriod" Button Disabled - Why?

### ISSUE THREAD

**Issue by lucanos** [Eonasdan/bootstrap-datetimepicker#2233]
![image](https://user-images.githubusercontent.com/126774/37439591-e56ffc22-284c-11e8-8606-c5dd2fa3bfe5.png)

Not sure why the AM/PM Toggle Button is not shown.

JSON of the Options I have running:

    {
      "timeZone":"",
      "format":false,
      "dayViewHeaderFormat":"MMMM YYYY",
      "extraFormats":false,
      "stepping":15,
      "minDate":false,
      "maxDate":false,
      "useCurrent":true,
      "collapse":true,
      "locale":"en",
      "defaultDate":false,
      "disabledDates":false,
      "enabledDates":false,
      "icons":{
        "time":"glyphicon glyphicon-time",
        "date":"glyphicon glyphicon-calendar",
        "up":"glyphicon glyphicon-chevron-up",
        "down":"glyphicon glyphicon-chevron-down",
        "previous":"glyphicon glyphicon-chevron-left",
        "next":"glyphicon glyphicon-chevron-right",
        "today":"glyphicon glyphicon-screenshot",
        "clear":"glyphicon glyphicon-trash",
        "close":"glyphicon glyphicon-remove"
      },
      "tooltips":{
        "today":"Go to today",
        "clear":"Clear selection",
        "close":"Close the picker",
        "selectMonth":"Select Month",
        "prevMonth":"Previous Month",
        "nextMonth":"Next Month",
        "selectYear":"Select Year",
        "prevYear":"Previous Year",
        "nextYear":"Next Year",
        "selectDecade":"Select Decade",
        "prevDecade":"Previous Decade",
        "nextDecade":"Next Decade",
        "prevCentury":"Previous Century",
        "nextCentury":"Next Century",
        "pickHour":"Pick Hour",
        "incrementHour":"Increment Hour",
        "decrementHour":"Decrement Hour",
        "pickMinute":"Pick Minute",
        "incrementMinute":"Increment Minute",
        "decrementMinute":"Decrement Minute",
        "pickSecond":"Pick Second",
        "incrementSecond":"Increment Second",
        "decrementSecond":"Decrement Second",
        "togglePeriod":"Toggle Period",
        "selectTime":"Select Time"
      },
      "useStrict":false,
      "sideBySide":true,
      "daysOfWeekDisabled":false,
      "calendarWeeks":false,
      "viewMode":"days",
      "toolbarPlacement":"default",
      "showTodayButton":false,
      "showClear":false,
      "showClose":false,
      "widgetPositioning":{
        "horizontal":"auto",
        "vertical":"auto"
      },
      "widgetParent":null,
      "ignoreReadonly":false,
      "keepOpen":false,
      "focusOnShow":true,
      "inline":false,
      "keepInvalid":false,
      "datepickerInput":".datepickerinput",
      "keyBinds":{},
      "debug":true,
      "allowInputToggle":false,
      "disabledTimeIntervals":false,
      "disabledHours":false,
      "enabledHours":{
        "8":true,
        "9":true,
        "10":true,
        "11":true,
        "12":true,
        "13":true,
        "14":true,
        "15":true,
        "16":true,
        "17":true,
        "18":true,
        "19":true,
        "20":true,
        "21":true,
        "22":true
      },
      "viewDate":false
    }

It is not just hidden by a CSS glitch - the HTML element has the "disabled" class on it for some reason, which I cannot understand.

    <button class="btn btn-primary disabled" data-action="togglePeriod" tabindex="-1" title="Toggle Period">PM</button>

Versions:

- Bootstrap DateTimePicker v4.17.47
- jQuery v3.3.1
- Moment v2.21.0

**Comment by William-H-M** [comment]
Hi, it must be a problem with a rule of your CSS because I tried it on my side and didn't happened, https://jsfiddle.net/20oywuno/91/

By the way thoose option you can always remove most of them, they are by default and are not need it for most of the examples:
`tooltips`, `icons `for example

**Comment by lucanos** [comment]
Legacy CSS - it will get you everytime.
Appreciate the advice, and direction.

**Comment by gotoAndBliss** [comment]
@lucanos How did you treat that legacy CSS issue? I'm using the latest version `4.17.50` .. yet experiencing the same thing.
