### ISSUE TITLE
Regression bug since 4.17.x.x in month selection

### ISSUE THREAD

**Issue by DiogoBarros90** [Eonasdan/bootstrap-datetimepicker#2234]
If i initiate an instance with the following options, the month selection doesn't work:

$('.monthpicker').datetimepicker({
    format: 'MM/YYYY',
    viewMode: 'months'
 });

It worked in 4.15.35

**Comment by William-H-M** [comment]
It works for me with your same options, are you sure you're including everything?
Try on this fiddle https://jsfiddle.net/William_/20oywuno/

**Comment by DiogoBarros90** [comment]
I picked the library from here: https://www.nuget.org/packages/Bootstrap.v3.Datetimepicker/
Now, i've just tested the release from this github repo and it works (with the same initializations, as i'm only switching files).

**Comment by William-H-M** [comment]
That's because of this https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1128#issuecomment-218210715
