### ISSUE TITLE
How to set default date in Hindi format Like "१६ मार्च २०१९ दोपहर १:५० बजे" used locale: 'hi'

### ISSUE THREAD

**Issue by kchauhaneworkplaceappscom** [Eonasdan/bootstrap-datetimepicker#2235]
This repo is no longer actively monitor or supported. All future work is being done to https://github.com/tempusdominus/bootstrap-3

**Comment by William-H-M** [comment]
> Issues that are submitted without a description (title only) will be closed with no further explanation.
