### ISSUE TITLE
Repo Moved????

### ISSUE THREAD

**Issue by TBSliver** [Eonasdan/bootstrap-datetimepicker#2238]
As found in THIS ISSUE SUBMISSION:

```
This repo is no longer actively monitor or supported. All future work is being done to https://github.com/tempusdominus/bootstrap-3
```

Can this PLEASE be put in the actual README? As there is no mention of this anywhere in this particular GitHub project that it is deprecated and has been superseded.

**Comment by pedrofurtado** [comment]
@Eonasdan
