### ISSUE TITLE
Use isoWeek week instead of week

### ISSUE THREAD

**Issue by leiripmeester** [Eonasdan/bootstrap-datetimepicker#2241]
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/5a991bfff0b7a721c73d482d06bcbaf9f1e3fc98/src/js/bootstrap-datetimepicker.js#L721

**Comment by J0nKn1ght** [comment]
I'd second this.  It's exactly the fix that we've had to do to our local copy:

```javascript
row.append('<td class="cw">' + currentDate.isoWeek() + '</td>');
```
