### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by gordal18** [Eonasdan/bootstrap-datetimepicker#2248]
Hello
I tried to use it in my project.
Very simple, just to integrate in meteor project.
But when I click the icon, I can see only popup.
I hope to solve this ASAP

Please ping me when you are available.
Best Regards,
Kakha

**Comment by esgi-dendyanri** [comment]
Hi,

i'm not the developer of this plugin, but i just want to help, have you follow this http://jsfiddle.net/msrdw98u/2/ ?

you can also make a simple prototype in jsfiddle.net and send it here, someone could help you better
