### ISSUE TITLE
REQUIREMENTS FOR USING DATETIMEPICKER

### ISSUE THREAD

**Issue by programmerchibi** [Eonasdan/bootstrap-datetimepicker#2249]
The documentation is just saying to use this and that **script and css** but it doesn't specify what version exactly. Can anyone help?

It doesn't show the form at the current version I am using.

Jquery 2.2.3
Bootstrap 3.3.6 
bootstrap-datetimepicker 4.17.*

**Comment by patarapolw** [comment]
Me too, it doesn't show the form at the current version I am using.

In addition, I tried to install via Bower, but Bootstrap folder doesn't come...

Anyway, I'll revert to https://github.com/smalot/bootstrap-datetimepicker for now. It seems to be OK with Bootstrap 4.

Another question... I am not sure if it is even possible to install Bootstrap 3 alongside Bootstrap 4... Or Bootstrap 4 only?

**Comment by William-H-M** [comment]
This a specifically BS3  version and it does work with jQuery 2.2.3+ that includes jQuery 3.3.1
You can get files from [CDNJS](https://cdnjs.com/libraries/eonasdan-bootstrap-datetimepicker)

> Another question... I am not sure if it is even possible to install Bootstrap 3 alongside Bootstrap 4... Or Bootstrap 4 only?

Most people would say that you shouldn't do it, you don't want things breaking here and there.

For a version of BS4 of this project rewrite from scratch look at https://tempusdominus.github.io/bootstrap-4/
