### ISSUE TITLE
 why impossible press button datetimepicker  twice

### ISSUE THREAD

**Issue by y2kim** [Eonasdan/bootstrap-datetimepicker#2252]
i'm try again change value press button but  
log show 
Uncaught TypeError: b.isDate is not a function
    at y (bootstrap-datetimepicker.min.js:1)
    at da (bootstrap-datetimepicker.min.js:1)
    at ga (bootstrap-datetimepicker.min.js:1)
    at HTMLSpanElement.ha (bootstrap-datetimepicker.min.js:1)
    at HTMLSpanElement.dispatch (jquery.min.js:3)
    at HTMLSpanElement.r.handle (jquery.min.js:3)

this error

**Comment by thetomester13** [comment]
I'm seeing this as well, were you able to get past this?

**Comment by y2kim** [comment]
Nope :(   I change another lib datetimepicker          
https://github.com/T00rk/bootstrap-material-datetimepicker      <-   this is my different lib  it little less functional that this but functionaly it well

**Comment by thetomester13** [comment]
Ok, I switched to [bootstrap-datepicker](https://github.com/uxsolutions/bootstrap-datepicker) - thanks!

**Comment by aquiles12345** [comment]
I fixed it, using version 2.9.0 of moment.js
As stated in moment docs method isDate is added on version 2.9.0

<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
