### ISSUE TITLE
$(..).datetimepicker is not a function

### ISSUE THREAD

**Issue by hsherlocked** [Eonasdan/bootstrap-datetimepicker#2255]
recently,i use ur product in my angular2 project,but there is a error in the console called '$(..).datetimepicker is not a function'.
I defined the function:
pick(){
        $('#startTime').datetimepicker({
            format: "YYYY-MM-DD",
        });
        $('#endTime').datetimepicker({
            format: "YYYY-MM-DD",
        });
    }
and I used this function pick() in ngOnInit().
I need ur help,thx!

**Comment by Augustpi** [comment]
bootstrap-datetimepicker.css
moment.js
bootstrap-datetimepicker.min.js

Please include css and js files to try again

```
    $(function () {
          $('#startTime').datetimepicker();
     });
```

**Comment by zhouyu1993** [comment]
`$(..).datetimepicker is not a function`

**Comment by elamje** [comment]
I believe this is still an issue even when the js/css is included.
