### ISSUE TITLE
When minDate is today ( new Date() ), can only chose today by click today button.

### ISSUE THREAD

**Issue by AlexVincent525** [Eonasdan/bootstrap-datetimepicker#2257]
Hi there.
When I was using 'minDate' option and set to 'new Date()', I can't choose today (such as July 28th.) by normal click in the container, value doesn't change. But click "Today" button will be fine.

Code below:
HTML:
`<div class="input-group date">`
&nbsp;&nbsp;&nbsp;&nbsp;`<div class="input-group-addon">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<i class="fa fa-calendar" aria-hidden="true"></i>`
&nbsp;&nbsp;&nbsp;&nbsp;`</div>`
&nbsp;&nbsp;&nbsp;&nbsp;`<input type="text" id="datetimepicker" class="form-control" title="选择日期">`
`</div>`

JS:
`$datetimepicker.datetimepicker({ /* Event: Initialze DateTimePicker */`
&nbsp;&nbsp;&nbsp;&nbsp;`calendarWeeks: true,`
&nbsp;&nbsp;&nbsp;&nbsp;`format: "YYYY-MM-DD",`
&nbsp;&nbsp;&nbsp;&nbsp;`minDate: new Date(),`
&nbsp;&nbsp;&nbsp;&nbsp;`showTodayButton: true`
`});`

Result:
![image](https://user-images.githubusercontent.com/15884415/43355073-e6352cb2-9288-11e8-82e6-2afb09ea1346.png)
You can't change value to "2018-07-28" by clicking "28", but today button will help. ("28" can't be selected while it hasn't been disabled.)

**Comment by William-H-M** [comment]
Hi the why  you can't choose that today's date is because `newDate()` will include the hour but I see you're not using hours on your picker, so the "best" way to solve this, and the way _**I**_ do it is:

Just use momentJs and his great methods, more specifically, [`startOf()`](https://momentjs.com/docs/#/manipulating/start-of/)

So, in a short you just use this snippet:

```
$('#myDatepicker').datetimepicker({
  format: 'DD-MM-YYYY',
  minDate: moment().startOf('day'),
});
```

**Comment by AlexVincent525** [comment]
Hi william !
Thanks for your methods and I use moment no longer than 1 day, now I found its greatness.
But I think the inconsistance between today button and day button can be noticed, it actually show different methods in deal with minDate.

**Comment by William-H-M** [comment]
Hi, the reason behind this, _if not wrong_, is beacause today's button use a validation of day so if he will just pick the day and doesn't matter _per se_ the hour*

There's some exception like when setting `minDate`

**Comment by utopictown** [comment]
> Hi the why you can't choose that today's date is because `newDate()` will include the hour but I see you're not using hours on your picker, so the "best" way to solve this, and the way _**I**_ do it is:
> 
> Just use momentJs and his great methods, more specifically, [`startOf()`](https://momentjs.com/docs/#/manipulating/start-of/)
> 
> So, in a short you just use this snippet:
> 
> ```
> $('#myDatepicker').datetimepicker({
>   format: 'DD-MM-YYYY',
>   minDate: moment().startOf('day'),
> });
> ```

thank you this worked
