### ISSUE TITLE
angularjs bootstrap eonasdan datepicker default date

### ISSUE THREAD

**Issue by kvkv** [Eonasdan/bootstrap-datetimepicker#2261]
I am using eonasdan angular bootstrap datepicker. How to set the default date in option. 

I am giving like below. Format is working fine but default date is not working. Can you please suggest how to implement default date.

$scope.datePickerOptions = {
    format: "DD/MM/YYYY",
	defaultDate:'23-04-2015'
   
};

<input type='text' class="form-control"  ng-model="modelName" datetimepicker options="datePickerOptions"/>

**Comment by William-H-M** [comment]
You should set that date as a moment object:
`defaultDate: moment('23-04-2015', "DD/MM/YYYY")`

This is a How-To question an as suh will be closed, anymore how-to related question pleas ask them on 
[StackOverflow](https://stackoverflow.com/questions/tagged/eonasdan-datetimepicker)
