### ISSUE TITLE
disabledDates not working correct

### ISSUE THREAD

**Issue by mlfactory** [Eonasdan/bootstrap-datetimepicker#2263]
Hello Guys,

i have a php array from 01-01-2018 to 31-12-2018.

In this array stored the disabled dates.

In a other array i have the dates that should enabled.

The output is right also the Dates was saved in the second array are unset in the first array.

Now i pass the first array to datetimepicker

`			disabledDates: [
						<?php 
						//print_r($datespan);
						foreach($datespan as $k => $datesp) {
						?>
						 '<?php echo str_replace("-", "/", $datesp); ?>',
						<?php
						}
						?>					
                    ]`

Output is correct but in the calender its not correct.

In every month are this days disabled:  1day in month - 12 day in month.
All other still enabled but thats not correct then only this dates should enabled:

30-08-2018 
07-09-2018  
01-09-2018 
26-08-2018  
27-08-2018  
29-08-2018 

Anyone a idea?

**Comment by William-H-M** [comment]
I think you're overthinking this, why?

Simple, if you have enableDates and disableDates, shouldn't be enough with enableDates?

Why I said this, because as per the [documentation they override each other](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#endisableddates)

> disabledDates: Also calling this function removes the configuration of options.enabledDates if such exist.

>enabledDates: Also calling this function removes the configuration of options.disabledDates if such exist.

So pretty much what I'm trying to say is pick one!

Note: use moment in those dates

**Comment by mlfactory** [comment]
Hey,

many thanks, your are my hero 👍  
All working now.

Super fast response , i like !

Have a nice day, Michael

**Comment by mlfactory** [comment]
Hey,

sorry another question ....

Is there a was to enable only specify hours for each enabled day?

I found disabledHours and enabledHours but in my chase its no working :(

`disabledHours: [],
  enabledHours: []`

and i found disabledTimeIntervals but this only for the current day or?

Many many thanks for your help, I appreciate that.

**Comment by mlfactory** [comment]
Hello Guys,

Nobody a Tipp for me ? :/

Thanks

**Comment by Ghost990** [comment]
> Hey,
> 
> sorry another question ....
> 
> Is there a was to enable only specify hours for each enabled day?
> 
> I found disabledHours and enabledHours but in my chase its no working :(
> 
> `disabledHours: [], enabledHours: []`
> 
> and i found disabledTimeIntervals but this only for the current day or?
> 
> Many many thanks for your help, I appreciate that.

You can use the allowTimes: [] array where you can specify the selectable times, e.g.: allowTimes: ['13-09-2018'].

Hope this helps :)

**Comment by mlfactory** [comment]
option allowTimes is not recognized!

:(
