### ISSUE TITLE
minDate disabled afte setting date with data("DateTimePicker").date(date);

### ISSUE THREAD

**Issue by DanielShinken** [Eonasdan/bootstrap-datetimepicker#2264]
I'm having some troubles trying to set date after clicking a button, I'm updating datetimepicker like this:

`$('#fecha_hora').data("DateTimePicker").date(fecha);`

where fecha is a date string in forma 'DD-MM-YYYY HH:mm' 
this updates my datetimepicker but the date set as minDate then became disabled, it appears as a selectable date (different from disabled dates) but I'm not allow to select the minDate back again.

Is this some kind of issue? I'm I doing something wrong? 

this is the complete code inside button click

$("#modal_fecha").on("shown.bs.modal", function () { 
      $('#fecha_hora').datetimepicker({
        format:'DD-MM-YYYY HH:mm',
        defaultDate:new Date(),
        minDate:new Date(),
        locale:'es',
        inline:true,
        sideBySide: true
      });
      var fecha = $('#date_hidden').val();
      if(fecha != 'false'){
        $('#fecha_hora').data("DateTimePicker").date(fecha);
        $('#fecha_hora').datetimepicker({minDate:new Date()});
      } 
    });

**Comment by snickom** [comment]
I have the same issue - v4.17.47.
```
$("#timepicker").datetimepicker({ ... }).on("dp.show", function (e) {
$("#timepicker").minDate(moment(minimalTime).format("YYYY-MM-DD HH:mm:ss"))
    .maxDate(moment(maximalTime).format("YYYY-MM-DD HH:mm:ss"));
});
```

**Comment by jiaoyixuan** [comment]
I have same trouble. It works in Chrome but not in IE10+.

**Comment by bspanyik** [comment]
I have the same issue with simply minDate set to `moment()`. 

The first time the datepicker appears, I can select today. Then I select another date. Then I try to select today again, it doesn't work: looks to be selectable, but disabled. 

Possibly related to #1302?

**Comment by William-H-M** [comment]
There's a workaround for this and is using [`moment.startOf()`](https://momentjs.com/docs/#/manipulating/start-of/) 

Why this happens? Because when you ask for `moment()` It'll come with a date and hours which make some conflicts at the time to select today's date, a quick snippet of what I do is:
```
$(element).datetimepicker({
    format: 'format',
    useCurrent: false,
    maxDate: moment().endOf('day'),
    minDate: moment().startOf('day'),
});
```
That way it won't break the date to select when is in a format without hours

Related to #1627
