### ISSUE TITLE
Linked Picker defaultDate Function Error

### ISSUE THREAD

**Issue by mehmetalidumlu** [Eonasdan/bootstrap-datetimepicker#2269]
Hi all,
I use linked picker with defaultDate param. But first picker throw this error:"defaultDate() Could not parse date parameter: NaN"

I cant find error or solution. 

**defaultStartDate:"30/10/2018"
defaultEndDate:"02/11/2018"**

```
$('#start-date').datetimepicker({
	useCurrent: false,
	locale: moment.locale('tr'),
	format: 'DD/MM/YYYY',
	defaultDate: defaultStartDate
});
$('#end-date').datetimepicker({
	useCurrent: false,
	locale: moment.locale('tr'),
	format: 'DD/MM/YYYY',
	defaultDate: defaultEndDate,
	showTodayButton:true
});
$("#start-date").on("dp.change", function (e) {
	$('#end-date').data("DateTimePicker").minDate(e.date);
});
$("#end-date").on("dp.change", function (e) {
	$('#start-date').data("DateTimePicker").maxDate(e.date);
});
```

Can anybody help me?
Thanks.

**Comment by William-H-M** [comment]
Hi, use [moment with format](https://momentjs.com/docs/#/parsing/string-format/) `moment(defaultStartDate, 'DD/MM/YYYY')`
