### ISSUE TITLE
 How do I configure the z-index of the popover that encloses the calendar or time selector of this component?

### ISSUE THREAD

**Issue by martinmurciego** [Eonasdan/bootstrap-datetimepicker#2274]
**How do I configure the z-index of the popover that encloses the calendar or time selector of this component?**

I am including this component in cells of a datatables.net table and I do not understand which class I am referring to to apply the z-index property so that the popover of the calendar or time selector is shown above the table. Some functional example that I find useful because I look at this issue and I can not find anything that works for me.

I would appreciate if you tell me how to fix this visual bug or unwanted behavior.
datetimepicker version : 4.17.47

I would inspect it but not focus and keep inspecting the element with the devtool.

![datatable y datetimepicker](https://user-images.githubusercontent.com/7759127/48666423-71d12900-eaa0-11e8-88f2-e77ced5bb30d.jpg)

**Comment by earlseay** [comment]
Put it in the display inline mode somewhere else in the page, then you can inspect it. That's how I had to get to it.

**Comment by martinmurciego** [comment]
Thanks, the problem is that I'm not looking to reference the calendar but the popover that uses the one that encloses the calendar,  this popover does not work in the inline mode.

**Comment by martinmurciego** [comment]
The problem is that inline mode [https://eonasdan.github.io/bootstrap-datetimepicker/#inline
](url) does not show the popover that encloses the calendar-widget but I found how to apparently inspect DOM elements that appear on focus:
[https://stackoverflow.com/questions/28963272/how-can-i-inspect-html-element-that-disappears-from-dom-on-lost-focus](url)

**Comment by earlseay** [comment]
Oh yeah i forgot in chrome you can use the inspector to focus elements

**Comment by martinmurciego** [comment]
While I found this code by inspecting Chrome DevTool but applying z-index style: 99999 to this div or input, it does not make the calendar look out of the table. Maybe it takes some CSS to handle property overflow or position. I have to investigate.
`<div class="bootstrap-datetimepicker-widget dropdown-menu usetwentyfour top" style="top: auto; bottom: 34px; left: 0px; right: auto;">
    <ul class="list-unstyled">
        <li>
            <div class="datepicker">
                <div class="datepicker-days" style="display: block;">
                    <table class="table-condensed">
                        <thead>
                            <tr>
                                <th class="prev" data-action="previous"><span class="glyphicon glyphicon-chevron-left" title="Mes anterior"></span></th>
                                <th class="picker-switch" data-action="pickerSwitch" colspan="5" title="Seleccionar mes">noviembre 2018</th>
                                <th class="next" data-action="next"><span class="glyphicon glyphicon-chevron-right" title="Mes siguiente"></span></th>
                            </tr>
                            <tr>
                                <th class="dow">lu</th>
                                <th class="dow">ma</th>
                                <th class="dow">mi</th>
                                <th class="dow">ju</th>
                                <th class="dow">vi</th>
                                <th class="dow">sá</th>
                                <th class="dow">do</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td data-action="selectDay" data-day="29/10/2018" class="day old">29</td>
                                <td data-action="selectDay" data-day="30/10/2018" class="day old">30</td>
                                <td data-action="selectDay" data-day="31/10/2018" class="day old">31</td>
                                <td data-action="selectDay" data-day="01/11/2018" class="day">1</td>
                                <td data-action="selectDay" data-day="02/11/2018" class="day">2</td>
                                <td data-action="selectDay" data-day="03/11/2018" class="day weekend">3</td>
                                <td data-action="selectDay" data-day="04/11/2018" class="day weekend">4</td>
                            </tr>
                            <tr>
                                <td data-action="selectDay" data-day="05/11/2018" class="day">5</td>
                                <td data-action="selectDay" data-day="06/11/2018" class="day">6</td>
                                <td data-action="selectDay" data-day="07/11/2018" class="day">7</td>
                                <td data-action="selectDay" data-day="08/11/2018" class="day">8</td>
                                <td data-action="selectDay" data-day="09/11/2018" class="day">9</td>
                                <td data-action="selectDay" data-day="10/11/2018" class="day weekend">10</td>
                                <td data-action="selectDay" data-day="11/11/2018" class="day weekend">11</td>
                            </tr>
                            <tr>
                                <td data-action="selectDay" data-day="12/11/2018" class="day">12</td>
                                <td data-action="selectDay" data-day="13/11/2018" class="day">13</td>
                                <td data-action="selectDay" data-day="14/11/2018" class="day">14</td>
                                <td data-action="selectDay" data-day="15/11/2018" class="day">15</td>
                                <td data-action="selectDay" data-day="16/11/2018" class="day">16</td>
                                <td data-action="selectDay" data-day="17/11/2018" class="day weekend">17</td>
                                <td data-action="selectDay" data-day="18/11/2018" class="day today weekend">18</td>
                            </tr>
                            <tr>
                                <td data-action="selectDay" data-day="19/11/2018" class="day">19</td>
                                <td data-action="selectDay" data-day="20/11/2018" class="day">20</td>
                                <td data-action="selectDay" data-day="21/11/2018" class="day">21</td>
                                <td data-action="selectDay" data-day="22/11/2018" class="day">22</td>
                                <td data-action="selectDay" data-day="23/11/2018" class="day">23</td>
                                <td data-action="selectDay" data-day="24/11/2018" class="day weekend">24</td>
                                <td data-action="selectDay" data-day="25/11/2018" class="day weekend">25</td>
                            </tr>
                            <tr>
                                <td data-action="selectDay" data-day="26/11/2018" class="day">26</td>
                                <td data-action="selectDay" data-day="27/11/2018" class="day">27</td>
                                <td data-action="selectDay" data-day="28/11/2018" class="day">28</td>
                                <td data-action="selectDay" data-day="29/11/2018" class="day">29</td>
                                <td data-action="selectDay" data-day="30/11/2018" class="day">30</td>
                                <td data-action="selectDay" data-day="01/12/2018" class="day new weekend">1</td>
                                <td data-action="selectDay" data-day="02/12/2018" class="day new weekend">2</td>
                            </tr>
                            <tr>
                                <td data-action="selectDay" data-day="03/12/2018" class="day new">3</td>
                                <td data-action="selectDay" data-day="04/12/2018" class="day new">4</td>
                                <td data-action="selectDay" data-day="05/12/2018" class="day new">5</td>
                                <td data-action="selectDay" data-day="06/12/2018" class="day new">6</td>
                                <td data-action="selectDay" data-day="07/12/2018" class="day new">7</td>
                                <td data-action="selectDay" data-day="08/12/2018" class="day new weekend">8</td>
                                <td data-action="selectDay" data-day="09/12/2018" class="day new weekend">9</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="datepicker-months" style="display: none;">
                    <table class="table-condensed">
                        <thead>
                            <tr>
                                <th class="prev" data-action="previous"><span class="glyphicon glyphicon-chevron-left" title="Anno anterior"></span></th>
                                <th class="picker-switch" data-action="pickerSwitch" colspan="5" title="Seleccionar anno">2018</th>
                                <th class="next" data-action="next"><span class="glyphicon glyphicon-chevron-right" title="Anno siguiente"></span></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="7"><span data-action="selectMonth" class="month">ene.</span><span data-action="selectMonth" class="month">feb.</span><span data-action="selectMonth" class="month">mar.</span><span data-action="selectMonth" class="month">abr.</span><span data-action="selectMonth" class="month">may.</span><span data-action="selectMonth" class="month">jun.</span><span data-action="selectMonth" class="month">jul.</span><span data-action="selectMonth" class="month">ago.</span><span data-action="selectMonth" class="month">sep.</span><span data-action="selectMonth" class="month">oct.</span><span data-action="selectMonth" class="month">nov.</span><span data-action="selectMonth" class="month">dic.</span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="datepicker-years" style="display: none;">
                    <table class="table-condensed">
                        <thead>
                            <tr>
                                <th class="prev" data-action="previous"><span class="glyphicon glyphicon-chevron-left" title="Decada previa"></span></th>
                                <th class="picker-switch" data-action="pickerSwitch" colspan="5" title="Seleccionar decada">2013-2024</th>
                                <th class="next" data-action="next"><span class="glyphicon glyphicon-chevron-right" title="Decada siguiente"></span></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="7"><span data-action="selectYear" class="year">2013</span><span data-action="selectYear" class="year">2014</span><span data-action="selectYear" class="year">2015</span><span data-action="selectYear" class="year">2016</span><span data-action="selectYear" class="year">2017</span><span data-action="selectYear" class="year">2018</span><span data-action="selectYear" class="year">2019</span><span data-action="selectYear" class="year">2020</span><span data-action="selectYear" class="year">2021</span><span data-action="selectYear" class="year">2022</span><span data-action="selectYear" class="year">2023</span><span data-action="selectYear" class="year">2024</span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="datepicker-decades" style="display: none;">
                    <table class="table-condensed">
                        <thead>
                            <tr>
                                <th class="prev" data-action="previous"><span class="glyphicon glyphicon-chevron-left" title="Centuria previa"></span></th>
                                <th class="picker-switch" data-action="pickerSwitch" colspan="5">2000-2107</th>
                                <th class="next" data-action="next"><span class="glyphicon glyphicon-chevron-right" title="Siguiente centuria"></span></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="7"><span data-action="selectDecade" class="decade" data-selection="2005">2000 - 2011</span><span data-action="selectDecade" class="decade active" data-selection="2017">2012 - 2023</span><span data-action="selectDecade" class="decade" data-selection="2029">2024 - 2035</span><span data-action="selectDecade" class="decade" data-selection="2041">2036 - 2047</span><span data-action="selectDecade" class="decade" data-selection="2053">2048 - 2059</span><span data-action="selectDecade" class="decade" data-selection="2065">2060 - 2071</span><span data-action="selectDecade" class="decade" data-selection="2077">2072 - 2083</span><span data-action="selectDecade" class="decade" data-selection="2089">2084 - 2095</span><span data-action="selectDecade" class="decade" data-selection="2101">2096 - 2107</span><span></span><span></span><span></span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </li>
        <li class="picker-switch accordion-toggle">
            <table class="table-condensed">
                <tbody>
                    <tr>
                        <td><a data-action="today" title="Seleccionar fecha actual"><span class="glyphicon glyphicon-screenshot"></span></a></td>
                        <td><a data-action="clear" title="Limpiar seleccion"><span class="glyphicon glyphicon-trash"></span></a></td>
                        <td><a data-action="close" title="Cerrar"><span class="glyphicon glyphicon-remove"></span></a></td>
                    </tr>
                </tbody>
            </table>
        </li>
    </ul>
</div>`

**Comment by William-H-M** [comment]
Hi, Ehhhh for this reference to #1346 there's some talk about why happens, and at the end there's a dirty work around.

Not sure if apply to your case too, but you can always try to adapt to it.

Oh btw when need to debug the calendar it will always hide, so there exist the [`debug`](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#debug) option.

If it doesn't help you, or if you found another workaround, leave it here ;)

**Comment by earlseay** [comment]
I had to force the WidgetParent property to reposition the thing based on the outer container. I opened a bug in the new repo to see if they'll fix it. Mine was about overflow though not z-index

**Comment by martinmurciego** [comment]
I was doing an exhaustive search because it is a project that I want to finish and I would like to not change this component in so many parts that I use it as in the case of DataTables. But it seems to be a problem with the Datatables.

**Without DataTables:**
[https://jsfiddle.net/6abxn644/168/](url)
[https://jsfiddle.net/znLmpgz7/](url)
[https://jsfiddle.net/znLmpgz7/1/](url)

**With DataTables:** 
http://jsfiddle.net/28675z97/74/
http://jsfiddle.net/28675z97/
https://jsfiddle.net/annoyingmouse/pdxkzyz6/3/

**Comment by Gloix** [comment]
It may be worth taking a look into how GwtDateTimePicker positions itself. I have a container with a fixed height that does not have enough space for the calendar to be shown completely, while GwtDateTimePicker shows fine. I found out that it positions itself just outside the fixed height container or maybe it has some other way to find out where it positions itself.
