### ISSUE TITLE
How remove all button tooltips?

### ISSUE THREAD

**Issue by hidayetsoltanzade** [Eonasdan/bootstrap-datetimepicker#2275]
How can i remove tooltips for all buttons? I set tooltips options to empty object, but nothing changed.

**Comment by elli-pirelli** [comment]
getToolbar = function () {


 if (!options.sideBySide && hasDate() && hasTime()) {
                    row.push($('<td>').append($('<a>').attr({'data-action':'togglePicker', 'title':'Select Time'}).append($('<span>').addClass(options.icons.time))));
                }


-->

 if (!options.sideBySide && hasDate() && hasTime()) {
                    row.push($('<td>').append($('<a>').attr({'data-action':'togglePicker', 'title':''}).append($('<span>').addClass(options.icons.time))));
                }

I would just erase it without deleting the brackets.
