### ISSUE TITLE
Can't close calendar dialog by anyways

### ISSUE THREAD

**Issue by tuanvayn** [Eonasdan/bootstrap-datetimepicker#2284]
I'm using your source. And it work perfectly in the <body> tag. but i want to  use in bootstrap modal. And I can open the calendar dialog but can't close even focus out or esc key. and it is not responsive. When I minimize the window it stil stand at the old position. But it work fine in the body tag or anothers tag except modal. Hope you help

**Comment by darkikari** [comment]
Hi,

If you can't close, you can add the onDpChange function and theses line to your javascript. See the example here : 

```
	$('#yourDTP').datetimepicker({
		viewMode: 'days',
	}).on('dp.change', onDpChange);

	function onDpChange(event) {
		var elements = document.getElementsByClassName('bootstrap-datetimepicker-widget dropdown-menu picker-open');
		elements[0].style.display = "none"; // This will hide when your picker-open class is active and show the dialog
		elements[0].classList.remove('picker-open'); // this will remove the picker-open class. If you don't remove, you should click 2 time to the button to re-open your dialog
	}
``` 

Enjoy
