### ISSUE TITLE
can't open Date Only, is not working

### ISSUE THREAD

**Issue by mickvega** [Eonasdan/bootstrap-datetimepicker#2287]
in the examples given in  https://eonasdan.github.io/bootstrap-datetimepicker/ it's a example called date only which is not showing or doing anything

**Comment by fperniavp** [comment]
Why is this closed if it's still happening?

**Comment by William-H-M** [comment]
We are in code freeze, and the issue doesn't seem to be critical or doesn't affect the code base of the project.

New project can be found at: https://github.com/tempusdominus
