### ISSUE TITLE
Maintain Repositery

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [Eonasdan/bootstrap-datetimepicker#2294]
Hi,

This is the recent update from the main source. I noticed you are not maintaining this repository. If you don't have time to maintain then give me I will handle this.

PS: I am interested in making free things for the public and managing.

**Comment by William-H-M** [comment]
Hi, currently this project is in code freeze, meaning that no new features are going to be implemented and only PR that are emergency fixes are accepted.

If you want to contribute you can do it on the new projects [TempusDominus ](https://github.com/tempusdominus/)
