### ISSUE TITLE
DatePicker to dispay only date with format MM/DD/YYYY changes 09/01/2019 to become 01/09/2019

### ISSUE THREAD

**Issue by bituinb** [Eonasdan/bootstrap-datetimepicker#2300]
```
$("#mydate).datetimepicker(
 timeZone: ""Australia/Adelaide", 
 format: 'MM/DD/YYYY',
 showTodayButton: true,
 showClear: true,
 showClose: true
)
```

If $("#mydate) has value of 09/01/2019 which is Sept 1, 2019, if you click on the input box it will change the value to 01/09/2019 and the calendar picker highlights January 1, 2019 instead of Sep 1, 2019.   

If I change the configuration to :

```
$("#mydate).datetimepicker(
 timeZone: ""Australia/Adelaide", 
 format: 'MM/DD/YYYY hh:mm A ',
 showTodayButton: true,
 showClear: true,
 showClose: true
)
```
The datepicker doesn't change the date to January1, 2019.

I only want it to display date without the time part.

**Comment by William-H-M** [comment]
Couldn't reproduce using this fiddle as base (it has the moment-timezone included) https://jsfiddle.net/William_/20oywuno/298/

Are you sure you're not changing the values?

BTW: You have an error on the line of timeZone
