### ISSUE TITLE
minDate do not work correctly when minDate = 2019-12-01 and without value

### ISSUE THREAD

**Issue by locxtit** [Eonasdan/bootstrap-datetimepicker#2301]
Sample:
$('#dp').datetimepicker(
    {
      minDate: moment('2019-12-01','YYYY-MM-DD')
    }
  );

**Comment by William-H-M** [comment]
Hi, I think I'll need a little more of code than that, please use this as a base and try to reproduce it:
https://jsfiddle.net/William_/20oywuno
