### ISSUE TITLE
startDate-BUG,  I cannot select 2019 

### ISSUE THREAD

**Issue by chunjingqiu** [Eonasdan/bootstrap-datetimepicker#2308]
This repo is no longer actively monitor or supported. All future work is being done to https://github.com/tempusdominus/bootstrap-3
![image](https://user-images.githubusercontent.com/14174491/71649483-246a5680-2d4a-11ea-9819-6b8b0babb163.png)
![image](https://user-images.githubusercontent.com/14174491/71649496-41068e80-2d4a-11ea-9ad3-2ceecd19dcf9.png)

**Comment by William-H-M** [comment]
Hi, you seem to have the wrong picker, or at least not a current version of this tool, you're probably using [UX Solutions](https://github.com/uxsolutions/bootstrap-datepicker) one
