### ISSUE TITLE
.date() and .viewDate() return old date

### ISSUE THREAD

**Issue by morawcik** [Eonasdan/bootstrap-datetimepicker#2310]
I open page with initial date in input. Use .date() return this date. Open picker, select other date, close picker by click outside - input show new date but .date and .viewDate() return old date.
To get new date I need open picker second time and close again (without clicking on any date) by click outside.

Why this first select date not update date for .date() ?

EDIT:
Even with keepOpen: false I have to open and close picker again

**Comment by littleylv** [comment]
I think you got the wrong property. try ``e.date.format``.

For example. I set the default value `2020-06-10`, after choose `2020-06-14`:

```html
<input type="text" class="form-control" value="2020-06-10">
```

```javascript
    dp.on('dp.change', function(e) {
      console.log(e.date._i);  // output 2020-06-10
      console.log(e.date.format('YYYY-MM-DD'));  // output 2020-06-14
      console.log(e.oldDate._i);  // output 2020-06-10
      console.log(e.oldDate.format('YYYY-MM-DD'));  // output 2020-06-10
    });
```
