### ISSUE TITLE
Partial rendering of datetimepicker. Only time is there. No dates available

### ISSUE THREAD

**Issue by rangrasjay** [Eonasdan/bootstrap-datetimepicker#2315]
![datetimepicker](https://user-images.githubusercontent.com/35130479/83870042-2d24e580-a74b-11ea-84f1-5b45134aa1de.png)

After updating jquery to 3.5.1 and bootstrap to 3.3.7, I am not able to see dates in calendar

**Comment by valinaga** [comment]
+1

**Comment by valinaga** [comment]
found a quick hack.
in `bootstrap-datetime.js`, around line 368, replace with this (`show` class added to dateView's `li`)
```
                if (hasDate()) {
                    content.append($('<li>').addClass((options.collapse && hasTime() ? 'collapse in show' : '')).append(dateView));
                }
```
and around line 1113 replace with this:
```
                        if (expanded.collapse) { // if collapse plugin is available through bootstrap.js then use it
                            expanded.collapse('hide');
                            closed.collapse('show');
                        }
                        expanded.removeClass('in');
                        closed.addClass('in');
```
apparently the collapse plugin available through bootstrap.js is not working so I forced for plugin to keep using add/removeClass.
Hope this help!
