### ISSUE TITLE
Does not fully support usage without input element

### ISSUE THREAD

**Issue by daveshapiro** [Eonasdan/bootstrap-datetimepicker#381]
In my scenario I do not have (or want) an input button.  We have a three elements: left arrow to decrement date by one, an anchor which displays the selected date and brings up the date picker when clicked, and a right arrow which increments the date by one.

The issue I'm experiencing is that I cannot set defaultDate due to the below code:
if (picker.options.defaultDate !== "" && getPickerInput().val() == "")
                picker.setValue(picker.options.defaultDate);

Since there's no input, getPickerInput returns no elements and so val() is undefined (not "").

Modifying to the following works:
var currentVal = getPickerInput().val() || "";
if (picker.options.defaultDate !== "" && currentVal == "")
       		picker.setValue(picker.options.defaultDate);

**Comment by Eonasdan** [comment]
@daveshapiro does this work for you: http://jsfiddle.net/Eonasdan/k0ghcjsa/

**Comment by daveshapiro** [comment]
Nope.  We don’t need or want an input control regardless of it being hidden.

**Comment by Eonasdan** [comment]
@daveshapiro check out the dev branch with this code

```
<h6>datetimepicker3</h6>
<div class="form-group">
	<label for="datetimepicker3">datetimepicker3</label>
	<div class="row">
		<div class="col-md-8">
			<div id="datetimepicker3"></div>
		</div>
	</div>
</div>

$('#datetimepicker3').datetimepicker({
	inline: true,
	sideBySide: true
});
```

**Comment by daveshapiro** [comment]
Unfortunately this still does not satisfy our needs.  We are not looking for an inline calendar (there are other plugins which do that easily enough.  We want to be able to use this the same way everyone else does, but without the requirement of an input control.

http://plnkr.co/edit/GOReONhi2oP7KgdcZ2ut?p=preview

In this plunkr demo, you can see I have a button (could be a div, could be a span, could be whatever).  The expectation is that clicking this will cause the calendar to pop open.  We would then have event handlers to capture the date change event in order to trigger an AJAX request data for the selected day.

**Comment by gwynjudd** [comment]
I was able to get this working by using the development build (with some modifications):

1. modified development build to allow the datetime widget to not require an input control (https://github.com/Eonasdan/bootstrap-datetimepicker/issues/381#issuecomment-51800434, https://github.com/Eonasdan/bootstrap-datetimepicker/issues/381#issue-36400669)
2. use the "inline" style on the picker
3. use a normal bootstrap dropdown menu:

    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Date<span class="caret"></span>
      </button>
      <div class="dropdown-menu">
        ... inline date picker goes here
      </div>
    </div>

**Comment by daveshapiro** [comment]
Sorry, but this is still not closed; I did mention that the inline form of the calendar is not desired, nor is extraneous HTML markup.

Per my first two posts, it is quite possible (or was at the time) to modify the plugin to attach to **any** element without the need for an input element or any additional mark up.

If this is something you cannot or do not want to support, please simply say so... I'm not sure why I'm getting suggestions for workarounds 8 months after initially posting the feature request.

**Comment by naczu** [comment]
just change input type as submit (=

**Comment by MatthewBooth** [comment]
This is still an issue. The demo code from the homepage gives this error. Bit of an oversight really when the demonstration code is totally broken and unusable.
