### ISSUE TITLE
Pop-up is partially outside the viewport on small devices

### ISSUE THREAD

**Issue by billccn** [Eonasdan/bootstrap-datetimepicker#431]
When the viewport is narrow and the button is somewhere in the middle of the screen, the pop-up will always be aligned with the button and gets cut off instead of using the available screen real-estate.

When the widget gets cut off, it also don't enable scroll bars on the viewport, so you literally cannot choose certain dates.

This is especially bad with the side-by-side mode.

**Comment by Eonasdan** [comment]
if you still experience this with the current version, please post a fiddle or demo site
