### ISSUE TITLE
Change events, soft/hard model link behaviour and soft/hard bounce functionality for version4

### ISSUE THREAD

**Issue by nikoskalogridis** [Eonasdan/bootstrap-datetimepicker#472]
Since we are in the process of defining the behaviour and API for version 4 of the component I think its a good time to decide on the behaviour of the component when a ```setDate``` is called with a moment that is invalid according to the validations configured through (min/maxDate, enabledDates, disabledDates, daysOfWeekDisabled). Note also that this problem could also come from a call to setting those validations rendering the currently selected moment to be invalid.

I think that a configuration boolean/string parameter ie. ```options.softBounce``` could be used to define the behaviour of the component on such occations. 

If for example softBounce is set to ```false``` then a ```dp.error``` should be emmited and the currently selected moment should be cleared (both in the components model value and on the input element the component is attached) emmiting a ```dp.change``` event. 

Otherwise setting softBounce to ```'back'``` or ```'forward'``` string would allow for the currently set date to roll back or forward to the next available valid state. In which case a ```dp.change``` will be emitted as well.

We also need to decide if we neet to emmit any special events in case the 'softBounce' happens

Let me hear your thoughts

**Comment by tsjoberg** [comment]
One comment - I know Backbone for example has an option for `silent: true` if you dont want a corresponding event to fire after for example a set or change. Would it be possible to implement something similar here? Use case would be a .date() and not fire dp.change event if your setting date systematically vs user input. This could be somewhat of a global option for any event emitted by a function.

**Comment by dtruel** [comment]
I tried to make an angular directive for this, and this is causing me a major headache.  All you have to do is add an extra property to the object called 'triggeredInternally' and it would save a lot of headache on my part!

By the way, thanks for a great plugin. This is the best datetime picker I've come across and that's why I'm trying to make it work with Angular
