### ISSUE TITLE
Add option to disable mobile device native keyboard

### ISSUE THREAD

**Issue by Michelangelo9** [Eonasdan/bootstrap-datetimepicker#494]
Is there an option to disable mobile device native keyboard support for the input fields?
Currently, when viewing on mobile, the native keyboard pops-up and forces the user to close the keyboard before interacting with the datepicker. Not a user-friendly experience.
http://jsfiddle.net/kmbo576p/16/

I've found a solution that could be leveraged from the below plugin.
https://github.com/eternicode/bootstrap-datepicker/pull/842/files

**Comment by Eonasdan** [comment]
The dev branch has some new features that will help with this. `showClose: true` will show an icon that will call the `hide()` function. `ignoreReadonly: true` will allow you to set an input to be `readonly` or `disabled` but still let the icon work.

**Comment by Eonasdan** [comment]
Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

**Comment by dougwo** [comment]
This doesn't work... I added readonly and also added ignoreReadonly:true and still cannot click on the icon.

**Comment by vsatishkumar91** [comment]
I downloaded  the  minified version of the datepicker, how could i change the code?

**Comment by holdech** [comment]
Is the fix to stop display of the mobile keyboard ( ignoreReadonly: true) in production yet?
