### ISSUE TITLE
Is there any way to set minDate/maxDate to now?

### ISSUE THREAD

**Issue by deitch** [Eonasdan/bootstrap-datetimepicker#549]
For example

````html5
<input data-date-minDate="now"/>
````

Sure, I could add it using the current format, but then I have to render it correctly each time, accounting for the format, which may change. So much easier to just say `minDate="now"`

**Comment by Eonasdan** [comment]
the dev branch now support using the string `now` and `moment` in the `min/maxDate` functions

**Comment by deitch** [comment]
Great! I will keep an eye on it.

**Comment by MohammadDayeh** [comment]
data-date-min-date="now" and data-date-min-date="moment" worked for me
