### ISSUE TITLE
dp.change event not fired when the input value is empty

### ISSUE THREAD

**Issue by nicolasgarnil** [Eonasdan/bootstrap-datetimepicker#587]
The `dp.change` event is not fired when the input is empty.

This is because line `828` to `839`:

```javascript
if (newDate.isValid() && !isInDisableDates(newDate) && isInEnableDates(newDate)) { // returns false if `input.val() ==''` 
  update();
  picker.setValue(newDate);
  notifyChange(oldDate, e.type);
  set();
}
else {
  picker.viewDate = oldDate;
  picker.unset = true;
  notifyChange(oldDate, e.type);
  notifyError(newDate);
}
```

If the input value is empty then the moment object returns false when asked if valid so the picker viewDate remains the same. This causes the `notifyChange` to be called but it returns in line `361`:

```javascript
if (moment(picker.date).isSame(moment(oldDate)) && !errored) {
  return;
}
```

It returns because the value is never updated. 

I understand this logic is fine when the user enters invalid dates, but an empty string should not be consider neither a valid or invalid date.

I need the value to be updated because I am writing an AngularJS directive and the model is not being updated when I clear the input's value:

```javascript
return function (scope, element, attrs, controller) {
          element.datetimepicker({
            pickTime: attrs.pickTime == 'true',
            format: attrs.format,
            useCurrent: false
          });

          element.on('dp.change',function (e) { // not called when the user clears the input as the value is not updated.
            scope.$apply(function (scope) {
              modelAccessor.assign(scope, e.date);
            });
          });

          scope.$watch(modelAccessor, function (val) {
            var newDate = moment(val);
            element.data('DateTimePicker').setValue(newDate);
          });
        };
```

Any workaround?

Thanks in advanced.

**Comment by nicolasgarnil** [comment]
Sorry I forgot to test it, will do it this week.

**Comment by purple-sunrise** [comment]
Try v4. Event 'dp.change' doesn't fire on empty value.

**Comment by raysunqi** [comment]
I think this still happens on version : 4.7.14
