### ISSUE TITLE
change timezone

### ISSUE THREAD

**Issue by derfbn** [Eonasdan/bootstrap-datetimepicker#594]
Hi,
is it possible to change the timezone of the Datetimepicker?
If i push a moment() with different timezone, its shown correct.
But when I open the pickerand change month or date, Datetimepicker automatically selects 
browser timezone again.

**Comment by jedvardsson** [comment]
It would be nice if you could also pick time zone in the UI.

**Comment by ssathishkumar540** [comment]
Without selecting date if I click outside of the calendar, It is taking the current date and Time. I need after selecting date in a calendar only,  I want to display the selected date in a textbox. Please help me anyone how can I do this in bootstrap datetimepicker version v3. It has displaying like this,

![datet](https://cloud.githubusercontent.com/assets/10419324/6551352/2256f046-c65d-11e4-8aa9-95a7c21487d8.JPG)

It is displying current date and time in screen. I dont want like this. After selecting date only the selected date will display in texbox. Example if I select "28/04/1990" means the seleced date will display on screen. How can I do this?

**Comment by ssathishkumar540** [comment]
In my screen add, delete and save button is there. If I click + button, new row will add. In that new row If I insert any date, I want to display the date as selected date and time as "00:00". I have attach the image like what I want,
![exampl](https://cloud.githubusercontent.com/assets/10419324/6551418/3d3d30b8-c65e-11e4-9d8a-209ce5c3de8e.JPG)

Here, I am setting time "00:00" as manually. What I want If I select any date in calendar,  the time will  automatically take "00:00". This is for only newly added row. How can I do this? Please help me anyone.

**Comment by Eonasdan** [comment]
@ssathishkumar540 please don't hijack issues with unrelated problems. It's best to open your own issue.

if you want the picker to just select the date then use the format option `format: 'L'` or `MM/dd/YYYY`

**Comment by ssathishkumar540** [comment]
datetimepicker defaultly taking current date and time. After selecting a date in a calendar only I want to display the selected date in textbox. Please help me how can I do this?

**Comment by Eonasdan** [comment]
I'm locking this issue.
