### ISSUE TITLE
Option for data-date-view-mode HTML attribute being ignored

### ISSUE THREAD

**Issue by benr77** [Eonasdan/bootstrap-datetimepicker#613]
If I set in the Javascript options viewMode: 'years' then this works correctly as expected.

However, if I use the alternative method of setting options with the HTML attribute 'data-date-OPTION' this does not work.

The following JSFiddle demonstrates this, with the first datepicker having the option set in the JS and the second in the HTML.

http://jsfiddle.net/j91u95gj/

**Comment by Eonasdan** [comment]
please check v4, and use `data-date-view-mode="years"

**Comment by benr77** [comment]
Upgraded to v4 and used ```data-date-view-mode="years"``` as you suggest and it works perfectly.

Thanks for all the work on this plugin especially the v4 rewrite! BTW your docs are rather broken at the moment https://eonasdan.github.io/bootstrap-datetimepicker/ has no CSS

**Comment by Eonasdan** [comment]
Docs are fixed. Sorry about that, rawgit issues
