### ISSUE TITLE
Installation via bower forces bootstrap install

### ISSUE THREAD

**Issue by CaptSaltyJack** [Eonasdan/bootstrap-datetimepicker#634]
When I install this package via `bower install bootstrap3-datetimepicker -S`, grunt wires into my code the following:

    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script> 

This is causing a big problem since I already have bootstrap-sass-official installed. Could you maybe tell me how I can get the line above to stop injecting into my code every time grunt runs?

**Comment by Eonasdan** [comment]
@CaptSaltyJack I just updated the library to v4. When I did I removed Bootstrap dependencies for all package managers (accepts the nuget packages). If you would, check that this is to your liking.
