### ISSUE TITLE
Disabling Time Intervals

### ISSUE THREAD

**Issue by Isaac-Kleinman** [Eonasdan/bootstrap-datetimepicker#644]
I'm aware that dates can be blocked using the `disabledDates` option, but I'd like to have certain time intervals disabled; e.g. any time between **3 PM** and **6 PM** on **11/12/2014** should be disabled. 

Is there a built-in way for me to do this?

**Comment by Markovsky** [comment]
I tried to give it a go and do the code needed to do that but it seems that i'm missing something because my array of hours doesnt seems to be passed so i'd really like the see the feature implemented or some help to do so.

**Comment by Eonasdan** [comment]
I'm actually working on this now. I have something working already (might not be the best in performance at the moment)

**Comment by Markovsky** [comment]
Great! Do you have an ETA?

**Comment by Eonasdan** [comment]
@Markovsky I think what you and @Isaac-Kleinman want is different.

The original feature request is to disable a time interval on a give date. I think what you're hoping for is that 8 and 13 are enabled (or disabled) for all dates. Right?

**Comment by Markovsky** [comment]
Exactly. It would be useful in the case of a leave management system where certain type of leavecan only start at specific hours

**Comment by Eonasdan** [comment]
Please check the development branch.
