### ISSUE TITLE
Set default date for a birth date

### ISSUE THREAD

**Issue by greg0ire** [Eonasdan/bootstrap-datetimepicker#665]
In a form that has an **optional** birth date field I would like to have the datepicker to be set on a date more than 20 years ago, so that the majority of the users, that usually are older than that don't need to click too much to get to the decade they were born in. The input field should stay blank until a date is clicked in the calendar.
I don't think this is possible at the moment, is it?

**Comment by Eonasdan** [comment]
Please check the dev branch. `viewMode: 'decades'` is now available.

**Comment by greg0ire** [comment]
Thank you for working on that! It looks a bit funny though, it is not really decades but "elevenades" (or [hendecades](https://en.wikipedia.org/wiki/11_%28number%29) ? ) :


![decades](https://cloud.githubusercontent.com/assets/657779/6886832/9623f50c-d64b-11e4-9e61-91b0826e6e2d.png)

Here is how <del>I configured it</del> it is configured :

```javascript
            jQuery(function ($) {
                $('#dp_s5518387ac544a_birthDate').datetimepicker({
                        "viewMode":"decades",
                        "defaultDate":"",
                        "disabledDates":[],
                        "enabledDates":[],
                        "icons":{
                        "time":"glyphicon glyphicon-time",
                        "date":"glyphicon glyphicon-calendar",
                        "up":"glyphicon glyphicon-chevron-up",
                        "down":"glyphicon glyphicon-chevron-down"
                        },
                        "useStrict":false,
                        "sideBySide":false,
                        "daysOfWeekDisabled":[],
                        "minDate":"1900-01-01",
                        "maxDate":"2015-03-29",
                        "useCurrent":false
                        });
            });
```

**Comment by Eonasdan** [comment]
I know it looks funny. I didn't know what else to do with it. Currently, the year picker show 12 years so to get it it to line up with the years I had to make it by 12. I'm open for improving it, but it works `:)`

**Comment by greg0ire** [comment]
Apart from that it works great indeed. Why not show 10 years in the year picker then ?

**Comment by Eonasdan** [comment]
take a look at another dp: http://demos.telerik.com/kendo-ui/datepicker/index

their text shows 10 years but when you click on it, you get 12

**Comment by greg0ire** [comment]
Oh yeah, with two disabled, contextual years before and after. That's clever.

**Comment by Eonasdan** [comment]
I think it's supposed to be "previous", "next" over disabled, but it's hard to tell.

**Comment by Eonasdan** [comment]
maybe in v5 we could change the year picker or something.

I'm assuming this can be closed.

**Comment by greg0ire** [comment]
Yes it can.
