### ISSUE TITLE
v4: can't set an min/maxDate with the onHide event

### ISSUE THREAD

**Issue by Jantastic** [Eonasdan/bootstrap-datetimepicker#677]
I want to set the minDate and maxDate for two Datetimepickers.
It works fine if you use the onChange event, but if you use the onHide event, it crashes because the event param is undefined.

Error Message:
bootstrap-datetimepicker.js:1296 Uncaught TypeError: minDate() Could not parse date parameter: undefined

http://jsfiddle.net/jantastic/j4brdsnn/

Jan

**Comment by Eonasdan** [comment]
Please check the latest, it should be fixed
