### ISSUE TITLE
Next / previous year stepper

### ISSUE THREAD

**Issue by patrickt010** [Eonasdan/bootstrap-datetimepicker#682]
I am wondering if it is possible to step one year further or earlier, just like you currently can step to the next or previous month. Datepickers from other makers show a double next-button and a double prev-button:

 <<    <     January 2014    >    >>

Is this currently possible?

**Comment by gwikle** [comment]
This actually is possible with the current implementation.  Click on the Month text at the top of the popup.  It changes to the year.  Then you can use the forward and backward buttons to skip through years.  If you click again on the year you get a faster way to jump to another year.

**Comment by patrickt010** [comment]
Yep, was able to uncover this after going through the implementation and it works perfectly, but was not very discoverable as an end user.
