### ISSUE TITLE
Choose defaultDate without setting Value

### ISSUE THREAD

**Issue by conorot** [Eonasdan/bootstrap-datetimepicker#688]
It would be great if there was an option to set the default date that the calender opens up on so that it doesn't start today, without changing the HTML value with the current defaultDate option.

My use case - setting a date of birth. I know that no users are allowed to be less than 13 so I can set the maxDate to 13 years ago, then to change where my pop-up starts, I set the defaultDate to 13 years ago, however this sets the HTML value to the date 13 years ago and thus overrides my "placeholder" text which reads "Date of birth"

**Comment by karolyi** [comment]
there's a workaround for this 'bug', if anyone interested:

you can set the datetimepicker with it's set() function, and then set the bound element back to its original value. thus, you'll have the picker opening up with the wished datetime.

if you modify the enabled/disabled dates, redo this procedure.

**Comment by Eonasdan** [comment]
if I add a check for a placeholder value on the input field does that solve all of your issues?

**Comment by karolyi** [comment]
you mean `data-placeholder=""`? I think yes.

**Comment by Eonasdan** [comment]
I mean if you did `<input type="text" class="form-control" placeholder="put a date here"/>`

**Comment by iancmuir** [comment]
The issue for me is that if I require this field then if a user simply clicks on the datetimepicker button by mistake then I don't want it to populate the input unless they actually pick a date.  Meaning they actually haven't chosen a date. That way I can leave the input readonly or disabled.

**Comment by Eonasdan** [comment]
what would be the point of setting the defaultDate at that point?

You can use `useCurrent:false` to not auto populate the input

**Comment by iancmuir** [comment]
I believe this was version 3 and I was looking for functionality similar to conorot where it would default the selection to that date but not populate the input unless it chosen.  I'm really after a way so that when the user clicks the calendar it doesn't just through a date in there until a date is picked. But might have a way of picking the default day the calendar opens up on.

**Comment by Eonasdan** [comment]
perhaps an new feature of `defaultViewDate` or something similar would be better. To me, your goal changes the functionality of `defaultDate`

**Comment by iancmuir** [comment]
That would make sense but I'm really after a better way to force the user to use the datetimepicker button and not set a date until one is chosen.  That way I can keep the input as readonly and not have to worry about a user clicking a button and populating the input when they didn't want to.  Perhaps I should have made a separate issue.

**Comment by Eonasdan** [comment]
the `placeholder` check is go into dev in a little bit.

You can make a separate issue. The `defaultViewDate` option would change the picker's view to whatever was passed in without actually setting the date

**Comment by Eonasdan** [comment]
Please check the dev branch. Should be a fix in there for you. Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

@iancmuir your feature request will go into the next release. I don't want to make any more feature changes so that dev can settle for a bit.

**Comment by ssathishkumar540** [comment]
How to make datetimepicker textbox as readonly. I just want to enter date while selecting in calendar only. I dont want the manual entry. How to do this?

**Comment by Eonasdan** [comment]
@ssathishkumar540 please see the [ignorereadonly](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#ignorereadonly) function.
