### ISSUE TITLE
How can I show the date picker on input and icon click 

### ISSUE THREAD

**Issue by almogdesign** [Eonasdan/bootstrap-datetimepicker#704]
Right now it works just by clicking the icon but I would also like it to show when a user clicks the input flied

**Comment by kingjerod** [comment]
In case anybody else stumbles on this question, this is how I solved it with jQuery:
```javascript
    $('.open-datetimepicker').click(function(event){
        event.preventDefault();
        $('#datetimepicker').click();
    });
```

Your HTML might look similar to this:
```html
<div class="input-group">
    <input type="text" id="datetimepicker" class="form-control" name="date">
    <label class="input-group-addon btn" for="date">
       <span class="fa fa-calendar open-datetimepicker"></span>
    </label>
</div>
```

**Comment by brubie** [comment]
This works for us in both Chrome and Safari. Thanks!

**Comment by Eonasdan** [comment]
You can easily do this:

```
<div class="form-group">
    <div class="input-group date" id="datetimepicker1">
        <input type="text" class="form-control" /><span class="input-group-addon"><span class="glyphicon-calendar glyphicon"></span></span>
         </div>
</div>

$('#datetimepicker1 input').click(function(event){
   $('#datetimepicker1 ').data("DateTimePicker").show();
});
```

Also a new feature in the dev branch, you can press the down arrow key while focused on the input box to show the picker

**Comment by sean-madhavan** [comment]
perhaps binding focus is better than click?

**Comment by mkotov13** [comment]
Thanks @brubie!!! that works

**Comment by Eonasdan** [comment]
the current version allows `allowInputToggle` which will open the picker from either the icon or the textbox

**Comment by vietnguyen09** [comment]
Thanks @brubie that is safe me a headache

**Comment by DanielFurmanov** [comment]
as @Eonasdan sayed just use:


```
	$('#datepicker).datetimepicker({                    		
                  	allowInputToggle: true
          });
```
and it works like a charm

**Comment by sylvinho81** [comment]
Thanks @brubie .

**Comment by santosh-k1** [comment]
I have used  one main wrapper in below solution to use where we can open the date picker on text box as well as glyphicon-calendar ...
'<div class="input-group date" id="ReportDate">' +
                  '<div id="txtdatefrom">' +
                  '<input accesskey="r" readonly="true" class="form-control datepicker" placeholder="Select Date" ng-required="true" ng-model="SelectedReportDate" type="text" id="txtReportDate" name="txtReportDate" required="required" data-ng-animate="2">' +
                  '</div>' +
                  '<span class="input-group-addon text-pointer">' +
                  '<span class="glyphicon glyphicon-calendar"></span>' +
                  '</span>' +
                  '</div>' +

$('#ReportDate').datepicker(
                  {
                      format: 'dd/mm/yyyy',
                      autoclose: true,
                      forceParse: false,
                      Default: true,
                      pickDate: true,
                      todayHighlight: true,
                  
                  });

**Comment by rroxysam** [comment]
@kingjerod. Thanks.
Only instead of click, i have used focus.

```
$('.open-datetimepicker').click(function(event){
    event.preventDefault();
    $('#datetimepicker').focus();
})
```;

**Comment by decentplusd** [comment]
Thanks @brubie

**Comment by eddieyugo** [comment]
Thanks @rroxysam you're a life saver :+1:

**Comment by tarmotalu** [comment]
Use **data-provide** attribute for _input-group_ div.

```html
 <div class="input-group date" data-provide="datepicker">
  <input type="text">
  <span class="input-group-addon">
    <span class="glyphicon glyphicon-calendar"></span>
  </span>
</div>
```

**Comment by vaniachoi** [comment]
what if i have an icon, and when i pick the date, the value of a span change? not input?
