### ISSUE TITLE
getDate shows time for date picker with out time enabled 

### ISSUE THREAD

**Issue by almogdesign** [Eonasdan/bootstrap-datetimepicker#705]
I have a date picker without the time but when I run the getDate function I get the time as 00.00.00 

```javascript
$('#datepicker').datetimepicker({language:  TAPi18n.getLanguage(), pickTime: false});

 organicFieldStatusTo: $('#datepicker').data("DateTimePicker").getDate(),
```

Tue Dec 23 2014 00:00:00 GMT+0200 (IST)

**Comment by Eonasdan** [comment]
please use v4, I believe this issue has been solved there
