### ISSUE TITLE
Intended errors are never thrown when using global variables

### ISSUE THREAD

**Issue by dani-h** [Eonasdan/bootstrap-datetimepicker#716]
```javascript
        // Neither AMD or CommonJS used. Use global variables.
        if (!jQuery) {
            throw new Error('bootstrap-datetimepicker requires jQuery to be loaded first');
        }
        if (!moment) {
            throw new Error('bootstrap-datetimepicker requires moment.js to be loaded first');
        }
```

The errors will never be thrown. Instead it will cause a ReferenceError since jQuery and/or moment are evaluated but never defined. I'm guessing you are throwing errors to be informative on which lib is missing, but that code can never be reached. try/catch?

**Comment by Eonasdan** [comment]
@Thinkscape this section was your doing. I don't use AMD or other dependency checkers. @nikoskalogridis do you have any thoughts?

**Comment by Eonasdan** [comment]
@dani-h I think I've got a fix for this in the dev branch. Check it out

**Comment by dani-h** [comment]
@Eonasdan I notice this until now, can you link me the commit that fixed it ?

**Comment by Eonasdan** [comment]
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/a4e7201a9293a60e3627ecee1b31cf0c1e971491/src/js/bootstrap-datetimepicker.js

https://github.com/Eonasdan/bootstrap-datetimepicker/commit/a4e7201a9293a60e3627ecee1b31cf0c1e971491
