### ISSUE TITLE
Defaulting the time?

### ISSUE THREAD

**Issue by winzig** [Eonasdan/bootstrap-datetimepicker#721]
I see the closed issue here: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/679

But it's not clear to me from the response, either in version 3.x or 4.x, how does one default the time if just using a picker without a date? Right now it's defaulting to NOW, but we'd like to specify the default time.

**Comment by Eonasdan** [comment]
if you use a format string for time `HH:mm` or any valid moment string, v4 will use that string to determine what components to show. Check `useCurrent` and `defaultDate` options if you don't want it to be `now` or `moment()`.

**Comment by mahesh-ziffi** [comment]
Still I'm also facing the same issue. Any valid solution please ?
