### ISSUE TITLE
Delay in opening datetimepicker popup on clicking the calender widget.

### ISSUE THREAD

**Issue by sanjit12345** [Eonasdan/bootstrap-datetimepicker#722]
Hi Team,
 I am using the datetimepicker bootstrap for displaying date and time. But when the number of datetimepicker is increased its opening very slow. 

Below is the snapshot -

![pickerissue](https://cloud.githubusercontent.com/assets/9696354/5627303/677debc4-95bc-11e4-9d13-5a4c7beae3dd.png)

As i am increasing the number of datetimepicker  its getting delayed in opening. So can you please provide me solution for this issue.
Thanks in advance

Regards
Atul kumar

**Comment by Eonasdan** [comment]
please try v4. It's been greatly improved over v3

**Comment by berwite** [comment]
where i can dl the v4?

**Comment by Eonasdan** [comment]
https://github.com/Eonasdan/bootstrap-datetimepicker/tree/v4beta
