### ISSUE TITLE
Setting the picker value to null

### ISSUE THREAD

**Issue by ThiagoMVF** [Eonasdan/bootstrap-datetimepicker#723]
Is there any way I can set a picker value to null after it had a value set?
I've seen it can be done once the page is loaded, with options set to not use current as default and never touching the picker but I needed a way to get it back to null if the user wants to erase the input contents or something like that.

My use case is that the datetimepicker is used to define the date of an event but sometimes things need to be shifted around and some events need to be removed from specific dates so that others can be added, problem lies in the fact that right now users can't simply set these removed events to "No date defined" because I couldn't find a way to bring the picker value back to null and once the form is submitted the date is restored to it's previous value.

**Comment by Eonasdan** [comment]
check v4 and you should be able to call `.date("")` or `.date(null)`

**Comment by ThiagoMVF** [comment]
Thank you! I'll take a look into v4
