### ISSUE TITLE
Init date in show method

### ISSUE THREAD

**Issue by guilhermeaiolfi** [Eonasdan/bootstrap-datetimepicker#726]
Hi,

First of all: great lib. Congrats. 

So, I was trying to use it in a new project I'm working on that uses ractive.js (but the problem should show up in ember.js, angular, etc as well). The initialization process starts before the databinding process sets the value in the input tag. So it(bootstrap-datetimepicker) thinks there's no date set in the input and use the current date. 

To workaround this problem I suggest bring this code:
```javascript

                    if (input.val().trim().length !== 0) {
                        setValue(parseInputDate(input.val().trim()));
                    } else if (options.defaultDate) {
                        setValue(options.defaultDate);
                    }
```

to the ```show``` method. So it will consider the value in the input by the time it is going to show the modal window.

Edit: I'm using v4beta

**Comment by Eonasdan** [comment]
I had a fix in place for you but the jasmine test failed. I'll have to look into it more, sorry.

**Comment by Eonasdan** [comment]
@guilhermeaiolfi check out the dev branch and let me know if that worked for you

**Comment by guilhermeaiolfi** [comment]
Hi,

sorry the delay. I was on vacation. So, I tested the 4.0.0 release and the development branch. None worked for me.

Looking at https://github.com/Eonasdan/bootstrap-datetimepicker/commit/a4e7201a9293a60e3627ecee1b31cf0c1e971491 I don't see what change would fix what I described.

**Comment by guilhermeaiolfi** [comment]
In the ```show``` function, if I create a else for this condition: https://github.com/Eonasdan/bootstrap-datetimepicker/blob/d072d926998f6277b555d74d35b78e8b81cb8762/src/js/bootstrap-datetimepicker.js#L991

like so:

```javascript
  if (options.useCurrent && unset && (input.is('input') && input.val().trim().length === 0)) {
    ...
  } else {
   setValue(parseInputDate(input.val().trim()));
  }
```

It works. I don't see how to solve the problem I'm describing without the above line somewhere in the show function. Since it is what will set the lazy value as date.

**Comment by guilhermeaiolfi** [comment]
@Eonasdan could you reopen this issue?

**Comment by Eonasdan** [comment]
can you setup a fiddle or a demo page for this please?

**Comment by guilhermeaiolfi** [comment]
Sure, I should have done that from the start: https://jsfiddle.net/UG7Eq/13/

**Comment by Eonasdan** [comment]
the fiddle you posted seems to work just fine for me. What I am looking for? Sorry `:)`

**Comment by guilhermeaiolfi** [comment]
The date set in the model (then propagate to the input element) is not the
date shown in the widget when opened.
Em 02/04/2015 17:31, "Eonasdan" <notifications@github.com> escreveu:

**Comment by guilhermeaiolfi** [comment]
Were you able to see the problem in the fiddle?
