### ISSUE TITLE
Default .getDate();

### ISSUE THREAD

**Issue by tojw** [Eonasdan/bootstrap-datetimepicker#727]
First off - thanks for the great plugin!

Maybe I misread the docs, but is it a design decision to set the default .getDate() to the current datetime even thought no date (& time) is selected using the date (& time) picker? as demonstrated in this jfiddle: http://jsfiddle.net/p06cLq3t/6/

It seems only once you call $('#datetimepicker1').data("DateTimePicker").setDate(); on initial load will it set the value to null.

Thank you in advance for any feedback

**Comment by Eonasdan** [comment]
please use v4. I checked your fiddle with v4 and it doesn't do this.

https://github.com/Eonasdan/bootstrap-datetimepicker/tree/v4beta

**Comment by tojw** [comment]
Thanks for the prompt feedback.
