### ISSUE TITLE
Wrong calculated date picker position

### ISSUE THREAD

**Issue by aliemre** [Eonasdan/bootstrap-datetimepicker#731]
In multiple use with single instance of the picker, some position issue may arise. In the example below, after re-arrange the size of window, picker is not initiated at correct position.

http://jmp.sh/jIUYbuT

```html
<div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date datetimepicker' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
```

```js
$(function () {
                $('.datetimepicker').datetimepicker();
            });
```

**Comment by Eonasdan** [comment]
which version are you using? 3 or 4?

**Comment by aliemre** [comment]
Version 3.

**Comment by Eonasdan** [comment]
please try v4 and let me know if you still have the issue

**Comment by aliemre** [comment]
Sorry, but the last release is v3.1.3 on GitHub and the demo website using also v3.1.3. Where can I download v4?

**Comment by Eonasdan** [comment]
https://github.com/Eonasdan/bootstrap-datetimepicker/tree/v4beta

**Comment by aliemre** [comment]
It seems to be fixed v4. Thanks for your support.
