### ISSUE TITLE
Mouse drag on time picker causes 'invalid date' and 'NaN' error

### ISSUE THREAD

**Issue by leoxlmn** [Eonasdan/bootstrap-datetimepicker#732]
To reproduce the problem:
1) Bring up the Time picker window, which shows hour:minute am/pm with ^ and v buttons.
2) Click either the hour or the minute to bring up the next window, which shows either 00 to 12 (for hour) or 00 to 55 (for minute).
3) Mouse over the number 00 and press and hold the mouse button and move/drag to the next line and mouse over either 05 (for hour) or 20 (for minute) and release the mouse button.
4) You will see both the hour and minute will be showing 'NaN' and the date time value will be showing 'invalid date'

Date picker windows doesn't have this problem though.

I am using the 3.1.3 version

**Comment by Eonasdan** [comment]
First, please use v4.

Second, what would you like this to do instead? This is an extreme fringe case. Does this happen often?

Finally, thank you for including the version number! :+1:

**Comment by leoxlmn** [comment]
First, I didn't know there is version 4. And, I still don't know where to the get the v4. Is it released yet? I don't want to use an alpha or beta version though.

Second, I would like this to do nothing, just like the Date picker, other than showing errors. No, it doesn't happen often. But, I still think it's a bug. Actually, most bugs don't happen often, but they still need to be fixed. Regarding the Time picker, sometime you click on a number but change your mind and want to cancel the selection. What I always do to cancel a click in other apps is, to hold the mouse button down and move out of the clicked button. It just didn't work in the Time picker.

Hopefully, this can be fixed. Or, the v4 can be released soon.

Thanks.

**Comment by Eonasdan** [comment]
v4 is here: https://github.com/Eonasdan/bootstrap-datetimepicker/tree/v4beta

It's going to be released soon. I haven't had the time to finish the docs and demo pages so I haven't made it the master branch yet.

Try your issue with v4 and let me know
