### ISSUE TITLE
Option to use the default moment.js locale

### ISSUE THREAD

**Issue by benbro** [Eonasdan/bootstrap-datetimepicker#733]
The picker already uses moment.js so it will be useful if the default moment.js locale will be used instead of having to define it with the language attribute for each picker.
```javascript
moment.locale('fr');
```

**Comment by Eonasdan** [comment]
check the v4 branch, I believe it already does this

**Comment by benbro** [comment]
v3.1.3
When setting locale with moment.locale('fr'), datetimepicker uses that locale only when adding language: '' to the options. 

I couldn't make the v4 branch work. It uses new options.
