### ISSUE TITLE
Feature request: timezoneId and outMode

### ISSUE THREAD

**Issue by comerc** [Eonasdan/bootstrap-datetimepicker#734]
For Meteor wrapper we are released two new property:
* [x] timezoneId ([get](https://github.com/comerc/meteor-autoform-bs-datetimepicker/blob/v4beta/autoform-bs-datetimepicker.js#L47-L54)-[set](https://github.com/comerc/meteor-autoform-bs-datetimepicker/blob/v4beta/autoform-bs-datetimepicker.js#L23-L31))
* [x] outMode ([get](https://github.com/comerc/meteor-autoform-bs-datetimepicker/blob/v4beta/autoform-bs-datetimepicker.js#L55-L61)-[set](https://github.com/comerc/meteor-autoform-bs-datetimepicker/blob/v4beta/autoform-bs-datetimepicker.js#L32-L38))

But I believe that they will be useful to all.

**Comment by Eonasdan** [comment]
could you give some more detail on what you did and what these are supposed to do?
