### ISSUE TITLE
Nullable datetimepicker?

### ISSUE THREAD

**Issue by emzero** [Eonasdan/bootstrap-datetimepicker#735]
I'm using two linked pickers like in your demo to pick a date range. But also I need to provide null values because I need to support all the following scenarios:

1) Not chosing anything: This should return null for both getDate()
2) Select only one of the pickers: The other one should return null
3) Selecting both: Of course, both getDate() should return the corresponding date

Problem is right now, just after the page is loaded if I call getDate() on both of them I get the current datetime. I want to get null/undefined or something not-date if I haven't even touched the pickers.

**Comment by Eonasdan** [comment]
check v4. This issue should be resolved https://github.com/Eonasdan/bootstrap-datetimepicker/tree/v4beta

**Comment by emzero** [comment]
Ok, thanks.

But how to use the Public API?

In your JsFiddle I'm adding the following line:
alert($('#datetimepicker1').date());

And I get "undefined is not a function"

**Comment by Eonasdan** [comment]
that hasn't changed. You'll still have to do `$('#datetimepicker3').data("DateTimePicker").date()` to get the date

**Comment by emzero** [comment]
Ok, I see. 

Problem is the v4beta doesn't seem to allow linked pickers (for selecting a period).
This is not working on v4beta: http://jsfiddle.net/emzero/t5oqb7o6

**Comment by Eonasdan** [comment]
change your script to:

```
$('#datetimepicker1').datetimepicker();
$('#datetimepicker2').datetimepicker();

$("#datetimepicker1").on("change.dp", function (e) {
    $('#datetimepicker2').data("DateTimePicker").minDate(e.date);
});
$("#datetimepicker2").on("change.dp", function (e) {
    $('#datetimepicker1').data("DateTimePicker").maxDate(e.date);
});
```

v4 docs are about finished and will be up soon
