### ISSUE TITLE
offset.top values are wrong in some cases

### ISSUE THREAD

**Issue by tayhimself** [Eonasdan/bootstrap-datetimepicker#736]
In datetimepicker.js on line 309:
 `offset.bottom = $window.height() - offset.top + picker.element.outerHeight() + 3;`
should instead be 
`offset.bottom =  $window.scrollTop() + $window.height() - offset.top + picker.element.outerHeight() + 3;`
For large values of offset.top, offset.bottom ends up being negative and this causes the widget to be displayed off screen making it seem that the widget isn't working.

**Comment by Eonasdan** [comment]
If you're using v3 please give v4 a try. The placement has been redone

**Comment by GoZOo** [comment]
I have same issue.

To reproduce, your date field has to be at the bottom of the browser (but you can still scroll bottom). Datepicker can't display under date field so should be placed at top.

As @tayhimself said, replace following resolve this issue :

    if (placePosition === 'top') {
        offset.bottom = $window.height() - offset.top + picker.element.outerHeight() + 3;
        picker.widget.addClass('top').removeClass('bottom');
    }

by 

    if (placePosition === 'top') {
        offset.bottom = $window.scrollTop() + $window.height() - offset.top + picker.element.outerHeight() + 3;
        picker.widget.addClass('top').removeClass('bottom');
    }

**Comment by GoZOo** [comment]
Solution by @tayhimself doesn't work as fine as expected. I still have troubles. I make a pull request with another solution : https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1203
