### ISSUE TITLE
datetimepicker don't hide.

### ISSUE THREAD

**Issue by Bladezal** [Eonasdan/bootstrap-datetimepicker#737]
Hello, I'm using your datetimepicker with bootstrap v3 and CodeIgniter, but as soon as my page is loaded, the calendar is displayed and don't hide when you select a date.
Could you please clarify to me what's going on?
![datetimepicker](https://cloud.githubusercontent.com/assets/7606979/5744838/da017f34-9c02-11e4-8c8a-675ce30f9159.jpg)
I've also tried with V4.

**Comment by Eonasdan** [comment]
Are you also using jqueryui? 

Please provide a jsfiddle of your issue. There are base fiddles that will get you started in the contribute docs

**Comment by Bladezal** [comment]
Yes, I'm using jqueryui.
could you be more specific? what's a jsfiddle? I'm relatively new with all this stuff.

**Comment by Eonasdan** [comment]
This datepicker is for Bootstrap and is not compatible with jquery ui. You'll have to fix whatever jquery ui is overwriting to get this picker to work. Jquery ui has its own datepicker plugin.

jsfiddle.net allows you to share your code with others. This fiddle: http://jsfiddle.net/Eonasdan/f3x2mvr1/ shows the minimal setup for this picker.

The issue you are having is a conflict with jquery ui and bootstrap styling.
