### ISSUE TITLE
minDate for time

### ISSUE THREAD

**Issue by ZeusZoe** [Eonasdan/bootstrap-datetimepicker#739]
Hi

Ex.
        $("#datacorsaapp").datetimepicker({
            language: localize,
            pickTime: false,
            minDate: moment(),
            daysOfWeekDisabled: [0, 6]
        });

        $("#oracorsaapp").datetimepicker({
            language: localize,
            pickDate: false,
            //minDate: moment(),
            minuteStepping: 1
        });
If I set minDate in "oracorsaapp" to moment(), it fix the time to moment() and no change, while work fine for date.
Thanks

**Comment by Eonasdan** [comment]
Try v4 and post a jsfiddle of your code

**Comment by ZeusZoe** [comment]
Hi, can you pass me the link.
Thanks

**Comment by Eonasdan** [comment]
v4 is here: https://github.com/Eonasdan/bootstrap-datetimepicker/tree/v4beta

**Comment by ZeusZoe** [comment]
For me it is working fine, for now. It is better. Which is the new options list.
Thanks
