### ISSUE TITLE
v4: format LLLL not showing timepicker

### ISSUE THREAD

**Issue by bjoe2k4** [Eonasdan/bootstrap-datetimepicker#740]
I am failing to get the timepicker to appear for formats LLLL or llll. It only works by using the full format 'dddd D MMMM YYYY LT'.

http://jsfiddle.net/0Ltv25o8/34/

**Comment by Eonasdan** [comment]
It looks like it's working for me

![image](https://cloud.githubusercontent.com/assets/1006516/5761250/3a9dcaf0-9ca8-11e4-86ce-13ba9958bb00.png)

**Comment by bjoe2k4** [comment]
I don't get the timepicker for the second one.

http://jsfiddle.net/0Ltv25o8/35/
![untitled](https://cloud.githubusercontent.com/assets/1668390/5761524/3fa7ec54-9cdc-11e4-9b4a-6f2efedeb476.png)

**Comment by Eonasdan** [comment]
ah quite right. I'll get it fixed

**Comment by Eonasdan** [comment]
mmm this might be a momentjs issue. It does the same thing for `LLL`. I've opened a [new issue](https://github.com/moment/moment/issues/2163)

**Comment by bjoe2k4** [comment]
i not very confident they will fix this soon or even at all. In the meantime i would suggest to do the longdateFormat() simply twice.

http://jsfiddle.net/5Ld0ycLr/5/

**Comment by Eonasdan** [comment]
yup. If moment doesn't fix it, I'll just add a second `longdate`

**Comment by e2** [comment]
:+1:

**Comment by kAworu** [comment]
Hi,

I would be very please by a fix / wordaround for LLLL :+1:

**Comment by Eonasdan** [comment]
@nikoskalogridis do you have any better idea's then what @bjoe2k4 has posted?

**Comment by Eonasdan** [comment]
@bjoe2k4 added your fix to the dev branch until Moment address it (assuming they ever do)

**Comment by bjoe2k4** [comment]
Great, thanks!

**Comment by Eonasdan** [comment]
just to update this:

Moment acknowledged that this is an issue. It has been marked as a bug, but that's all

**Comment by kAworu** [comment]
@Eonasdan thanks for the follow up :+1:

**Comment by Eonasdan** [comment]
A fix in the momentjs library was merged to their dev branch! https://github.com/moment/moment/pull/2419

v5 of the picker should be able to take out the double parse
