### ISSUE TITLE
Scroll through years

### ISSUE THREAD

**Issue by tpegley** [Eonasdan/bootstrap-datetimepicker#741]
I only see chevrons to scroll back and forth through months in the popup. Is it possible to scroll through years too? For example if I want to set the birth date of a 60 year old person I don't want to scroll back 720 times.

**Comment by Eonasdan** [comment]
Set `viewMode: 'years'`.

You can also click on the **Month Year** to get to the month picker, click again to get the year picker

![image](https://cloud.githubusercontent.com/assets/1006516/5762355/87b72a46-9caf-11e4-8a5c-c3aae2001ad8.png)
