### ISSUE TITLE
v4: .maxDate() returns TypeError: options.maxDate.clone is not a function

### ISSUE THREAD

**Issue by bjoe2k4** [Eonasdan/bootstrap-datetimepicker#742]
when the functions picker.minDate and picker.maxDate are called without argument, a check for existance is missing:

minDate, maxDate line 1256, 1283:
```return options.minDate.clone();```

This should be done like here:

defaultDate, line 1310
```return options.defaultDate ? options.defaultDate.clone() : options.defaultDate;```

sorry for no jsfiddle, but this is quite obvious.

**Comment by Eonasdan** [comment]
I'll get it fixed. Thanks

**Comment by Eonasdan** [comment]
Please check the latest, it should be fixed

**Comment by bjoe2k4** [comment]
It's fixed, thx!
