### ISSUE TITLE
v4 - Localization with moment

### ISSUE THREAD

**Issue by ZeusZoe** [Eonasdan/bootstrap-datetimepicker#745]
Hi,
localization with moment non working for me:
        $("#dt1").datetimepicker({
            locale:moment.locale("it"),
            minDate: moment(),
            format: "DD/MM/YYYY",
            daysOfWeekDisabled: [0,6]
        });
Thanks

**Comment by Eonasdan** [comment]
it should be `locale: 'it'`.

As per the contrib doc, please provide a js fiddle of your problem

**Comment by ZeusZoe** [comment]
not work.
http://jsfiddle.net/h2aen016/2/

**Comment by Eonasdan** [comment]
read what I said:

it should be `locale: 'it'`

```
$("#dt1").datetimepicker({
        locale: 'it',
        minDate: moment(),
        format: "DD/MM/YYYY HH:mm",
        daysOfWeekDisabled: [0, 6]
    });
```

Be sure to include `moment-with-locales.js` or `it.js`

**Comment by ZeusZoe** [comment]
Read and tried, but not work.
Thanks

**Comment by Eonasdan** [comment]
yup it does: http://jsfiddle.net/Eonasdan/h2aen016/3/

**Comment by ZeusZoe** [comment]
moment.js was in conflict.
Thank you

**Comment by xiongxoy** [comment]
I18N is broken now: http://jsfiddle.net/Eonasdan/h2aen016/3/

**Comment by Eonasdan** [comment]
@xiongxoy no, you fiddle is broken.There are errors in the console

**Comment by xiongxoy** [comment]
You are right. I forgot to include moment-with-locales in my project. I18N works now.

But the fiddle is not mine, you posted that fiddle. I don't know why the fiddle is broken
