### ISSUE TITLE
v4: picker position off target element

### ISSUE THREAD

**Issue by bjoe2k4** [Eonasdan/bootstrap-datetimepicker#749]
With v4 the picker positioning is somewhat different to v3 and has some odd quirks, positioning the picker far off the target input element.

http://jsfiddle.net/0Ltv25o8/36/

Offtopic: is the development for v4 taking place somewhere else other than github? Or is it simply collecting bugreports and PRs and fixing them all at a time? It's been quite a while since the last commit to development branch :) I'm asking because i'm using v4 already on some private site successfully, however i have to work around some easy to fix bugs.

**Comment by Eonasdan** [comment]
I'll look into the positioning thing.

Off topic: I've been trying to get the docs and examples up to date with v4. I finally put v3 on feature freeze so I didn't have to try and maintain both at the same time. I have a full time job that doesn't always let me work on this. I've just about got the docs ready, I'm really hoping to make v4 as the master soon.

**Comment by nikoskalogridis** [comment]
@bjoe2k4, are you refering to the first input field on your jsfiddle or the second one? You should follow bootstrap rules for placing elements inside rows and cols in order for widget positioning to behave properly. Have a look on that [jsfiddle](http://jsfiddle.net/0Ltv25o8/79/) and let me know if that handles your issue.

**Comment by Eonasdan** [comment]
if you have further issue, please comment and I'll reopen this
