### ISSUE TITLE
v4: Is inline mode implemented?

### ISSUE THREAD

**Issue by jdbelo** [Eonasdan/bootstrap-datetimepicker#752]
I was working with picker inline in previous version (v.3.1.3).

Is this mode implemented in new version?

**Comment by Eonasdan** [comment]
You can do inline like this: http://jsfiddle.net/Eonasdan/6dnzs2pv/

**Comment by jdbelo** [comment]
In previous version the picker was embedded. This still possible? There was no border too.

**Comment by Eonasdan** [comment]
Try the dev branch and use this code:

```
<h6>datetimepicker3</h6>
<div class="form-group">
	<label for="datetimepicker3">datetimepicker3</label>
	<div class="row">
		<div class="col-md-8">
			<div id="datetimepicker3"></div>
		</div>
	</div>
</div>

$('#datetimepicker3').datetimepicker({
	inline: true,
	sideBySide: true
});
```

cheers!

**Comment by bodrick** [comment]
So I just tried this out and it works great, however the initial selection of the date doesn't seem to highlight it, the date is selected and the event triggered has the correct date, but the date isn't highlighted as selected.  Clicking the date again or another date then highlights just fine thereafter.

**Comment by OBOLLL** [comment]
I tried dev branch and I can't get it work - http://jsfiddle.net/0Ltv25o8/315/
There is an error - "Cannot read property 'dateOptions' of undefined"

**Comment by Eonasdan** [comment]
@bodrick Please check the dev branch.

Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

**Comment by mwinandy** [comment]
Hello,

It works but MM/YYYY format is not supported.

https://jsfiddle.net/Annhydrium/1gxa51js/1/

Thanks.

**Comment by Eonasdan** [comment]
@mwinandy by "not supported" I assume you mean that it hides after selecting a month?

If so, please check the patch I just put in.

**Comment by mwinandy** [comment]
Yes, because, even with keepOpen set as true, the picker disapear.

I will test in few hours.

Thanks! ;)

2015-03-04 15:43 GMT+01:00 Eonasdan <notifications@github.com>:

**Comment by mwinandy** [comment]
i've tested, and it works. Thanks for that quickly fix.
