### ISSUE TITLE
Issue with min/max dates and undefined values

### ISSUE THREAD

**Issue by danielbsig** [Eonasdan/bootstrap-datetimepicker#753]
Hi, 

first of all: thanks a lot for a great component! I'm using it in Angular, works much better than the ui-datepicker from angular-ui.

There is one issue I believe belongs to this component (i.e. instead of the Angular directive wrapper I'm using), since it can be reproduced in the examples. I have two datepickers (lets call them Start and End). The user picks a start date somewhere in the future (current day + 1 is enough), which should set the minDate for the End picker to that date. However, if the user now opens the End picker, the value in the picker gets set to the current date. If the user simply cancels the picker, that value is still displayed in the input field. 

It would probably be a nice addition to check if the current date violates the minDate, and if so, use the minDate instead.

A similar check would probably have to be added for the maxDate value as well.

**Comment by Eonasdan** [comment]
Have you checked the latest (v4)? min/max date has been changed to be aware of `useCurrent` and not set the date to `now` if it violates existing date rules.

http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers

**Comment by danielbsig** [comment]
Yes it seems to be fixed now. I noticed that when I refreshed the demo page after submitting the issue, that there was a lot that had been changed. Thank you very much!

**Comment by Eonasdan** [comment]
Yup. We've fixed a lot and made a ton of improvements. Let me know if you feel the docs are missing anything
