### ISSUE TITLE
v4 - Spin button in time-mode

### ISSUE THREAD

**Issue by ZeusZoe** [Eonasdan/bootstrap-datetimepicker#754]
Hi, for only time mode, why not  use spin button?
Thanks

**Comment by Eonasdan** [comment]
I'm not sure what you mean.

**Comment by ZeusZoe** [comment]
If now it's 16 o'clock and I must to set the 23, I must to press the button 7 times, while with spin-button I must hold pressed the button.
Thanks

**Comment by Eonasdan** [comment]
ah I see. You can also click on the hour (16) to be given a choice of hours.

I'll look into this some more to see if it's something we want to implement.

**Comment by ZeusZoe** [comment]
Ok.
Thanks
