### ISSUE TITLE
Datetimepicker in a wizard form 

### ISSUE THREAD

**Issue by berwite** [Eonasdan/bootstrap-datetimepicker#756]
I'm trying to implement datetimepicker with twitter-bootstrap-wizard. I'm using VinceG/twitter-bootstrap-wizard. The calendar is not showing after i click the icon but the input fields showing the current time and date.

![image](https://cloud.githubusercontent.com/assets/8809661/5803222/72a5adf4-a037-11e4-9f76-a0497b37b55f.png)

**Comment by Eonasdan** [comment]
please provide an example page or a jsfiddle

**Comment by berwite** [comment]
my bootstrap-wizard codes base on this  http://www.creative-tim.com/live/bootstrap-wizard i don't know if the problem was generated because of the z index of the datetimepicker or or from the   widgetParent. i dont know how to append the calendar in the bootstrap-wizard form. thanks

**Comment by berwite** [comment]
After a series of test i find the solution. the gsdk.css has a conflict on the datetimepicker.css on the dropdown class. 
thnx. ILOVE this plugin ^_^

**Comment by Eonasdan** [comment]
I'd love some details on where you're using the plugin. Thanks for the love :)
