### ISSUE TITLE
enabledDates() doesn't seem to work

### ISSUE THREAD

**Issue by karolyi** [Eonasdan/bootstrap-datetimepicker#760]
Hi,

I'm currently using V4 with German localization and enabledDates(). It seems that neither setting the enabled dates at init time with options, nor setting it manually via calling its enabledDates() function seem to work.

the datetimepicker accepts the parameters, it even gives them back, but the dates other than I allow, aren't disabled.

Could you please look into this?

Cheers,

**Comment by carlosalan** [comment]
+1

**Comment by nikoskalogridis** [comment]
have a look at development branch and let us know if that fixes the problem. thanks

**Comment by zlajson** [comment]
@nikoskalogridis Works now. Thanks.

**Comment by karolyi** [comment]
If this works, can you please bump the version?

**Comment by karolyi** [comment]
Revert that, using enabledDates() still does not work.

**Comment by karolyi** [comment]
Using enabledDates at init time also does not work. I still get the set values with the getter functionality, but still every date is enabled in the selector.

**Comment by karolyi** [comment]
My bad, sorry, I was still using the minified version. Works, please bump the version and do a release.

Cheers

**Comment by Kylia669** [comment]
use dev version, but get logical issue, when enable dates from previous month, i coudn`t navigate to prev or next month. I can just select from existing dates for current month.
Can you fix this issue ?
info : v.4.0.0 branch - development
