### ISSUE TITLE
v4: error on year only mode

### ISSUE THREAD

**Issue by tedliang** [Eonasdan/bootstrap-datetimepicker#761]
When format is 'YYYY', error 'Uncaught TypeError: undefined is not a function' will be thrown after selecting any year in v4.0.0.
http://jsfiddle.net/m641r23m/1/

**Comment by tedliang** [comment]
The same problem as #768

**Comment by btecu** [comment]
The bug is also reproducible on the demo page.
http://eonasdan.github.io/bootstrap-datetimepicker/#min-view-mode

**Comment by nikoskalogridis** [comment]
Can you give development branch a try and let us know if that fixes the issue? Thanks

**Comment by tedliang** [comment]
Yes, looks good. Thanks for the quick fixing. ATB.
http://jsfiddle.net/0Ltv25o8/86/
