### ISSUE TITLE
A datetimepicker in a table will replace all table cells with a date value (suggested fix included)

### ISSUE THREAD

**Issue by 1bugreporter** [Eonasdan/bootstrap-datetimepicker#762]
Version 3.1.3

Steps to reproduce:

* Create a HTML table with a few rows of fake data.
* Add a datetimepicker in one of the table cells

Expected result:
* The datetimepicker renders a picker in one cell

Actual result:
* All table cells are replaced with a string value representing the datetimepicker's default value.

Suggested fix: Replace '.parents("table")' with '.closest("table")' in this block:

    yearCont = picker.widget.find('.datepicker-years').find(
        'th:eq(1)').text(year + '-' + (year + 9)).parents('table').find('td');

**Comment by Eonasdan** [comment]
Please try V4 and post a jsfiddle with your issue

**Comment by notionslate** [comment]
I ran into this as well.  Probably won't upgrade to v4 due to trajectory of project.
