### ISSUE TITLE
Disable previous times datetimepicker

### ISSUE THREAD

**Issue by angelapr** [Eonasdan/bootstrap-datetimepicker#763]
How can I disable previous time of a selected date? 
I need a datetimepicker that disables all dates and time before the current moment.
I'm using momentjs and have this:
$.fn.datetimepicker.defaults = {
....
minDate = moment(),
....}
This disables all previous dates till current dates but the time can't be selected
Also I tried this:
$.fn.datetimepicker.defaults = {
....
minDate = moment(1, 'h'),
....}
This disables all previous dates till current dates but it allows me to select a previous time

**Comment by Eonasdan** [comment]
Please post a jsfiddle of your example

**Comment by angelapr** [comment]
Could you tell me how, cause I put the bootstrap-datetimepicker.js in javascript field, bootstrap-datetimepicker.css in css field and the input in the html field. I guess I have to add some external resources, but I don't know how.

Thanks in advance!!!

**Comment by Eonasdan** [comment]
This jsfiddle: http://jsfiddle.net/Eonasdan/0Ltv25o8/ is a good base.

By the way, it's listed on the main page and it's in the contributing docs

**Comment by angelapr** [comment]
As you can see, http://jsfiddle.net/0Ltv25o8/66/  all dates are disabled, but if you select the current day, the time can be earlier than the current moment, and I just need that the prevoius time is disabled too.

Thanks!

**Comment by Eonasdan** [comment]
try changing your code to `minDate: moment().add(1, 'h')`

**Comment by angelapr** [comment]
In that case the time can't be changed, nor later or earlier

**Comment by Eonasdan** [comment]
huh? What do you mean..?

**Comment by angelapr** [comment]
I mean I can't select any tiime. Time is blocked :(

**Comment by angelapr** [comment]
I mean I can't select any tiime. Time is blocked :(
It just shows me the current time, but can't select any other.

**Comment by Eonasdan** [comment]
works for me:

![image](https://cloud.githubusercontent.com/assets/1006516/5857826/8cb474be-a21c-11e4-9433-32fdd47027e5.png)

**Comment by angelapr** [comment]
Yes, I know it's works, but not for me :(

**Comment by Eonasdan** [comment]
well it works for me in jsfiddle. You'll need to check your console/firebug or do more to help me reproduce what you're reporting, otherwise I can't fix it.

**Comment by angelapr** [comment]
I realized I have a previous version. I followed the steps here: https://github.com/zpaulovics/datetimepicker-rails and the generated code is different than yours
