### ISSUE TITLE
demos don't work

### ISSUE THREAD

**Issue by brettskiii** [Eonasdan/bootstrap-datetimepicker#765]
Refused to execute script from 'http://rawgit.com/Eonasdan/bootstrap-datetimepicker/master/src/js/bootstrap-datetimepicker.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
eonasdan.github.io/:153 Uncaught TypeError: undefined is not a function

**Comment by Eonasdan** [comment]
`cdn.rawgit` is outdated and now `rawgit.com` is blocking our script file for high usage. I'm working on getting that fixed.

**Comment by Eonasdan** [comment]
Docs are fixed
