### ISSUE TITLE
getWidget() support

### ISSUE THREAD

**Issue by aberenyi** [Eonasdan/bootstrap-datetimepicker#766]
Hi,

It would be awesome if one could grab the widget only (i.e. do not show automatically) and display it in anywhere on the page (e.g. popover) - it looks like with v4 it could be done only in slightly hacky way.

Cheers

**Comment by Eonasdan** [comment]
You can do inline like this: http://jsfiddle.net/Eonasdan/6dnzs2pv/ is that what you're looking for?

**Comment by aberenyi** [comment]
Hey - sorry for the late response. Please have a look at this [fiddle](http://jsfiddle.net/aberenyi/fv2ykch2/), basically this is what I'd like to achieve using v4.

**Comment by aberenyi** [comment]
Any update on this?

**Comment by Igor10k** [comment]
I also wonder why `widget` is not exposed anymore. I used it to handle cases when popup was cut off on the left.
