### ISSUE TITLE
time icon pull to left in french

### ISSUE THREAD

**Issue by caBBAlainB** [Eonasdan/bootstrap-datetimepicker#771]
Hi,
I didn't chek for other locales but in french, the time icon is pulled to left and the month/year title seems to not be centered !?!
![2015-01-22 09_36_56-sites](https://cloud.githubusercontent.com/assets/9322571/5852653/909821ae-a21a-11e4-870d-dcfec2db46f1.png)

More generally, I think there are many problem in layouts for french locale, at least.
![2015-01-22 09_55_45-sites](https://cloud.githubusercontent.com/assets/9322571/5852832/114fa770-a21d-11e4-83c4-ffc216d6d0d3.png)

EDIT: In fact this behavior concerns my installation, despite I exactly use the external resources you have in your jsfiddle !?!

**Comment by Eonasdan** [comment]
Looks fine in jsfiddle:

![image](https://cloud.githubusercontent.com/assets/1006516/5858077/583ca9d4-a21e-11e4-8c9f-f3ad66124a79.png

Seems like you didn't include some CSS or you have some CSS that is overriding the picker style.

**Comment by caBBAlainB** [comment]
Yes, yes, I saw it looks fine in jsFiddle it's the reason why I added 'Edit' to precise it's certainly related to my context.
So, as I still didn't find the problem, if someone encountered the problem....
Thanks
