### ISSUE TITLE
can't disable time picker at v4

### ISSUE THREAD

**Issue by 4eRTyaka** [Eonasdan/bootstrap-datetimepicker#774]
Hi,

first of all, sorry for my english and thank you for this wonderful component, it's realy cool!!

About new version: i couldn't disable time picking as in previous version (3.1.3). I tried to use option "pickTime" with value "false", but it didn't work.

How can i disable time picker at v4?

Thanks in advance

**Comment by Eonasdan** [comment]
in v4 we use the `format` string to determine what components show. If you just want the date use a format string without any time components, e.g. `format: 'MM/dd/YYYY'`. Look at the momentjs docs: http://momentjs.com/docs/#/parsing/format/ for valid settings

**Comment by 4eRTyaka** [comment]
It's works for me, thank you for quick answer and your time

**Comment by sanchezbroz** [comment]
Ohhhh just what I needed.
Thank you so much..

**Comment by khurz10** [comment]
awesome support you got here :) i'm loving your plugin, BTW :+1:

**Comment by josephskeller** [comment]
If I use this new method, I need to determine the date format for the language the client is using. Whereas before, the date format would automatically match the users local. Any possibility of bringing the old pickTime feature back?

**Comment by Eonasdan** [comment]
@josephskeller just use one of the momentjs token formats, such as `L` or `LT` http://momentjs.com/docs/#localized-formats

**Comment by josephskeller** [comment]
Wonderful! Thank you so much for pointing out this solution to me.
