### ISSUE TITLE
how to get date in datetimepicker???

### ISSUE THREAD

**Issue by learner010** [Eonasdan/bootstrap-datetimepicker#775]
I have read the documentation and yet I have no idea how to get or set date for the component. Few examples would be appreciated.

I have tried following ways but non works.
```javascript
$('#datetime').date(); //get date
$('#datetime').currentDate(adate_variable); //set default date 
```

**Comment by nikoskalogridis** [comment]
Try

$('#datetimepicker1').data('DateTimePicker').date()

**Comment by learner010** [comment]
thanxs, it works. It would be useful if included in the documentation. I had to dig down the source codes in the demo to figure out.
