### ISSUE TITLE
NuGet Wrong Dependency

### ISSUE THREAD

**Issue by ReAdPT** [Eonasdan/bootstrap-datetimepicker#776]
Hello,

in NuGet package Bootstrap.v3.Datetimepicker.CSS 4.0.1, one dependency is wrong, instead of bootstrap (≥ 3.0.0) like Bootstrap 3 Datetimepicker CSS 3.1.3, is Twitter.Bootstrap.Less (≥ 3.0.0).

Keep excelent work.

**Comment by Eonasdan** [comment]
fixed. sorry
