### ISSUE TITLE
minDate and maxDate error

### ISSUE THREAD

**Issue by davidrojo** [Eonasdan/bootstrap-datetimepicker#777]
When having two connected datepickers as the example in documentation, if you set a date more than 1 month away from the other datepicker current month you will be unable to change the month with right conrol  due to its control is disabled.

![image](https://cloud.githubusercontent.com/assets/1050749/5899899/b7f91942-a562-11e4-9e37-09bb2e36000e.png)

**Comment by nikoskalogridis** [comment]
merged to development branch
