### ISSUE TITLE
version 4 to npm?

### ISSUE THREAD

**Issue by buggyvelarde** [Eonasdan/bootstrap-datetimepicker#779]
I see the latest version in npm is 3.1.3 and was wondering if version 4 will be available on npm. 
Thank you.

**Comment by aranw** [comment]
Any chance of getting NPM updated to the latest version? Am having issues installing the latest version and using it with browserify

**Comment by sherwinyu** [comment]
Yes, this would be great. In the meantime, a workaround is to use github style urls in the package.json:

```
dependencies: {
  "bootstrap-datetimepicker": "eonasdan/bootstrap-datetimepicker#1b2fe6ef0062"
}
```

(or another commit hash).

**Comment by mathieumg** [comment]
:+1:

**Comment by Eonasdan** [comment]
npm should be updated now
