### ISSUE TITLE
How to style a range between min and max dates?

### ISSUE THREAD

**Issue by seleckis** [Eonasdan/bootstrap-datetimepicker#780]
I can set minDate and maxDate of linked datepickers. But I would like to style cells with dates between min and max dates.
```html
<tr>
    <td data-action="selectDay" class="day">9</td>
    <td data-action="selectDay" class="day">10</td>
    <td data-action="selectDay" class="day active">11</td>
    <td data-action="selectDay" class="day">12</td>
    <td data-action="selectDay" class="day">13</td>
    <td data-action="selectDay" class="day weekend">14</td>
    <td data-action="selectDay" class="day weekend">15</td>
</tr>
```
some additional class needed after/before `.active`

**Comment by bjoe2k4** [comment]
All disabled dates have class "disabled". You can style all non-disabled dates using a proper CSS selector:
```
div.datepicker tbody td:not(.disabled) {
     background:#f0f
}
```

Example: http://jsfiddle.net/0Ltv25o8/100/

**Comment by Eonasdan** [comment]
@bjoe2k4 I think your fiddle js should be:

```
$('#datetimepicker1').datetimepicker();
$('#datetimepicker2').datetimepicker();

$('#datetimepicker1').data("DateTimePicker").minDate("01/15/2015 2:47 PM")
$('#datetimepicker2').data("DateTimePicker").maxDate("01/20/2015 2:47 PM")
```

Thank you for posting this. This what my initial thought as well.

**Comment by bjoe2k4** [comment]
No, this was intentional, i wanted to have both set on the same picker, so that i have a range in one picker ;-) 

Offtopic: is there a way to prevent the picker to close, when analyzing it using firebug or clicking somewhere else?

**Comment by seleckis** [comment]
It looks horrible! ))
No, I mean, there should be ability to style range after you finished to choose dates.
