### ISSUE TITLE
Setting value after datetimepicker is load not working properly

### ISSUE THREAD

**Issue by alexandrevicenzi** [Eonasdan/bootstrap-datetimepicker#782]
If I use jQuery to set input value after datetimepicker is loaded I have this bug:

When input get focus datetimepicker shows the current time, not the value of input.

I think it should detect input changes and trigger some event.

**Working:**

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="bootstrap-datetimepicker.min.css">
</head>
<body>
    <div class="container" style="margin-top: 20px">
        <div style="position: relative">
            <input class="form-control" type="text" id="time"/>
        </div>
    </div>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
    <script type="text/javascript" src="bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript">
        $("#time").val("18:56:00");
        $("#time").datetimepicker({
            showClear: true,
            format: 'HH:mm',
        });
    </script>
</body>
</html>
```

**Not working:**

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="bootstrap-datetimepicker.min.css">
</head>
<body>
    <div class="container" style="margin-top: 20px">
        <div style="position: relative">
            <input class="form-control" type="text" id="time"/>
        </div>
    </div>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
    <script type="text/javascript" src="bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript">
        $("#time").datetimepicker({
            showClear: true,
            format: 'HH:mm',
        });
        $("#time").val("18:56:00");
    </script>
</body>
</html>
```

Another good thing, is to apply format when input change. But this is not so relevant.

**Comment by bjoe2k4** [comment]
This will not work, because all datetimepicker data is stored in a data attribute.

Use `$('#time').data("DateTimePicker").date("18:56:00")`

For convenience you can also cache this attribute for later use:
```
$time = $('#time').data("DateTimePicker");
$time.date("18:56:00")
```

**Comment by Eonasdan** [comment]
@alexandrevicenzi I just tried your example and it works fine. Please provide a jsfiddle of what's not working.

**Comment by alexandrevicenzi** [comment]
@Eonasdan, the second one does not work. You can see [here](http://jsfiddle.net/rrg4o5y7/). I think @bjoe2k4 answer is right. But could not datetimepicker detect change events and update?

**Comment by Eonasdan** [comment]
your fiddle is invalid and doesn't work. You have console errors. You can fork this fiddle: http://jsfiddle.net/Eonasdan/0Ltv25o8/ to get started

**Comment by alexandrevicenzi** [comment]
Take a look [here](http://jsfiddle.net/p2zarpw1/1/). It show 18:56, but when I focus shows the current time.

**Comment by bjoe2k4** [comment]
Actually, it's implemented already, the TimeDatePicker adjusts itself on every `change` event, your only problem is that jQuery's `.val(...)` doesn't trigger the `change` event. Only real user action can trigger the `change` event, see also http://api.jquery.com/change/ (yellow note somewhere in the middle).

If you want to set your date via `.val(...)` then you have to trigger the change event manually, see http://jsfiddle.net/p2zarpw1/2/

**Comment by alexandrevicenzi** [comment]
Thanks @bjoe2k4

**Comment by nikoskalogridis** [comment]
Shall we close this?

**Comment by bkdotcom** [comment]
triggering a change on a date range field doesn't seem to update the datepicker
