### ISSUE TITLE
Timepicker inline

### ISSUE THREAD

**Issue by Exerlol** [Eonasdan/bootstrap-datetimepicker#783]
Hello there, first of all thx for a lovely plugin, i was wondering is it possible to make inline timepicker? I mean timepicker without input or button... I want to show widget only...Is that possible ? Something like this, only with timepicker:

**Comment by Exerlol** [comment]
![datetimeinline](https://cloud.githubusercontent.com/assets/10726640/5920450/ee6b830e-a63c-11e4-87c0-3164c80e9a34.JPG)

**Comment by Eonasdan** [comment]
how about this: http://jsfiddle.net/Eonasdan/9sr7wzat/

**Comment by Exerlol** [comment]
I love you man! : ) Thank you!

**Comment by jfschwarz** [comment]
I would be interested in this, too. However, the jsfiddle link gives me a 404. Could you update the link?

**Comment by Exerlol** [comment]
HTML : 
<input type="hidden" class="form-control" id="datetimepicker1" />
<div id="showpicker"></div>
JS: 
$('#datetimepicker1').datetimepicker({
            widgetParent: $("#showpicker"),
            format: 'DD.MM.YYYY HH:mm'
});
$('#datetimepicker1').data("DateTimePicker").show();

Here you go m8, enjoy!

**Comment by Eonasdan** [comment]
a true `inline` option is coming to a datepicker near you. It should be in the dev branch some time this week

**Comment by Exerlol** [comment]
Oh, gr8 to hear... Anywayz, this work around is good enough for my case :)
