### ISSUE TITLE
Why not merge in bootstrap3-datetimepicker-rails ?

### ISSUE THREAD

**Issue by e2** [Eonasdan/bootstrap-datetimepicker#784]
To me it just doesn't make sense to have 2 GH projects with the same bundled assets.

Otherwise, with every release there will be update requests like this: https://github.com/TrevorS/bootstrap3-datetimepicker-rails/issues/23

**Comment by TrevorS** [comment]
Sorry for the delay, the gem has been updated with 84e78ecf17588f0f1e381cb758e30b2cdd0adc48.

**Comment by e2** [comment]
Thanks. I"ll close this.
