### ISSUE TITLE
useCurrent: false won't default timepicker to 00:00:00

### ISSUE THREAD

**Issue by adamellsworth** [Eonasdan/bootstrap-datetimepicker#792]
version: 4.0.0

    <input type="text" placeholder="Offset Format - HH:MM:SS">

    $('input').datetimepicker({
        useCurrent: false,    // default to 00:00:00
        format: 'HH:mm:ss'  // 24:59:59
    });

**Comment by nikoskalogridis** [comment]
How about also using `defaultDate` option set to `00:00:00`?

**Comment by adamellsworth** [comment]
Failed on string `00:00:00` with error:

    defaultDate() Could not parse date parameter: 00:00:00

---

Worked with `Date` instance:

    var d = new Date();
    d.setHours(0,0,0);

    $('input').datetimepicker({
        useCurrent: false,
        format: 'HH:mm:ss',
        defaultDate: d
    });

**Comment by Eonasdan** [comment]
Please check the dev branch and let me know if you still have this issue.

**Comment by Eonasdan** [comment]
Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

**Comment by adamellsworth** [comment]
Sorry for the belated response.

I've bumped up to development branch `4.7.14` and tried the same thing and now it's returning `12:00:00` as the default date with the following params:

    $('.selector').datetimepicker({
        useCurrent: false,
        format: 'HH:mm:ss',
    });
