### ISSUE TITLE
Go to timepicker after picking date

### ISSUE THREAD

**Issue by storeman** [Eonasdan/bootstrap-datetimepicker#797]
Would it be a nice feature to go to the time picker if a date is selected? Especially if viewMode 'year' is used, this would be very pretty and intuitive I think.

**Comment by Exerlol** [comment]
+ for this one... Would be gr8 if we could jump to time picker after picking date...

**Comment by Eonasdan** [comment]
this is not user friendly to me. If you pick the wrong date this would force you to go back to the picker.

Still, I'll call for a vote. Please +1 if you would like to see this add, or -1 to leave it out.

**Comment by Exerlol** [comment]
I agree that its not friendliest feature ever, but i would love to see it as optional feature. Thanks for reply.

**Comment by storeman** [comment]
My argument is, when you want a full datetime input from a user, it should show this option. The time-picker is somewhat hidden by an icon, i can imagine a user wouldn't see this. Maybe it should be an option parameter.

**Comment by Eonasdan** [comment]
@storeman you can also use `sideBySide`  which puts the date and time in view at the same time
