### ISSUE TITLE
Picker closes after picking date with inline picker

### ISSUE THREAD

**Issue by siegerhansma** [Eonasdan/bootstrap-datetimepicker#798]
Jsfiddle: http://jsfiddle.net/L6gako18/1/

This is only when using format and widgetParent together. Remove the format and the picker remains when picking a date.

**Comment by Exerlol** [comment]
Hey m8, use i used this format : format: 'DD.MM.YYYY HH:mm'   and its working fine

**Comment by Eonasdan** [comment]
@siegerhansma see this: http://jsfiddle.net/Eonasdan/L6gako18/2/

I just added the `keepOpen: true`.

Please let me know if you still have an issue with this
