### ISSUE TITLE
Update datetimepicker on change underlying input field

### ISSUE THREAD

**Issue by bobvandevijver** [Eonasdan/bootstrap-datetimepicker#799]
I can not this anywhere in the doc or source, but it it possible to update the datetimewidget with the value which is in the input field, without doing that manually?

What I am looking for is something like an `update()` or `refresh()` function, which I can run on all datetimepickers simultaneously. Something like in [bootstrap-select](http://silviomoreto.github.io/bootstrap-select/#refresh). 

Does anyone have an idea, or is it non-existing functionality? In that case, I would like to request  it.

**Comment by Eonasdan** [comment]
you want to update the date on several pickers at the same time? am I understanding that correctly?

**Comment by bobvandevijver** [comment]
Yes, you do. Imagine the case in which I update a start and end time dynamically through javascript: now it would be possible to explicitly set those values also for the datetimepicker, but an general update for which reloads the inputs would be nicer. 

Maybe even an option to listen to underlying input changes and automatically updating the widget would be nice. It already directly syncs one way, so why not the other way around?

**Comment by Eonasdan** [comment]
You can already do some or all of that.

Use the [`.date(newDate)`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#date)

Do a foreach over a css class and call the function on them
