### ISSUE TITLE
datetimepicker is not compatible with moment-timezone with default timezone set

### ISSUE THREAD

**Issue by tmotyl** [Eonasdan/bootstrap-datetimepicker#803]
Since version 2.9.0 of moment js and moment-timezone 0.3.0
you can set the default timezone for the newly created moment objects
```
moment.tz.setDefault('Australia/Darwin');
````
see 
https://github.com/moment/moment-timezone/issues/15
http://momentjs.com/timezone/docs/#/using-timezones/default-timezone/

However if you set the default timezone, then the datetimepicker is changing the time, when you change the date.
How to reproduce:
1. set default timezone
2. open datapicker
3. select some date and time
4. change the date
you will notice that after changing the date, time was also changed

**Comment by sromano** [comment]
+1

**Comment by tmotyl** [comment]
The reasoning for this request is following:
Inside our system (TYPO3 CMS) user can configure his timezone (and date format).
This setting is then used all over the product to present date and time fields.
We would also like to display timezone information inside input field 
using format "HH:mm DD-MM-YYYY [(UTC]Z[)]"
which gives e.g. 11:52 31-01-2015 (UTC+01:00)

On the database side, we store the dates as UTC timestamp, so the timezone offset and date format is  applied before displaying the date to the user.
And before sending the data back to the server we need to convert it back to the UTC timestamp.

Some technical details:
We have this implemented in the way that for every datapicker we have 2 inputs:
- one which is visible and renders a datapicker with a human readable date & time e.g."11:52 31-01-2015 (UTC+01:00)"
- second one which is hidden and contains a utc unix timestamp

So on every change of date in the datapicker we update the hidden input value (converting user TZ date to UTC timestamp).

We use the value from the hidden input for further processing on the server side.

**Comment by legrego** [comment]
+1

**Comment by JuliusOnGitHub** [comment]
+1

**Comment by maddoger** [comment]
+1

**Comment by Ngorror** [comment]
+1

**Comment by aratak** [comment]
+1

**Comment by alessiostalla** [comment]
+1

**Comment by AshCoolman** [comment]
+1

**Comment by wolfgangkirchler** [comment]
+1

**Comment by Eonasdan** [comment]
This is **planned**. I get, really I do. `:)`

**Comment by Eonasdan** [comment]
this got added to the version 4 recently by a PR. You're welcome :)
