### ISSUE TITLE
make datepickerinput class configurable

### ISSUE THREAD

**Issue by tmotyl** [Eonasdan/bootstrap-datetimepicker#804]
right now the class for the input field "datepickerinput" is hardcoded in the getPickerInput function.
It would be nice if this class could be configured.

**Comment by Eonasdan** [comment]
personally, I don't really see why this needs to be configurable. Since it's a class it can easily and unobtrusively be added to your code.

**Comment by tmotyl** [comment]
Thanks for your comment.
We're evaluating the use of the datapicker in the TYPO3 CMS (the opensource enterprise CMS which runs sites like Unesco, Lufthansa...). 
It's not easy to change the markup in the existing product. First of all we need to change markup all over the core. Then it would also require that all custom modules update their templates for the new TYPO3 version. 
In other words I would like to make the class configurable, to make the datapicker change backward compatible (non-breaking) for the TYPO3 CMS core.

**Comment by Eonasdan** [comment]
hmmm ok. I can see your point.

**Comment by Eonasdan** [comment]
Please check the dev branch. Should be a fix in there for you. Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

**Comment by tmotyl** [comment]
thank you! I will test it later this week.
