### ISSUE TITLE
Left and right arrows should not be disabled in this particular scenario

### ISSUE THREAD

**Issue by zlajson** [Eonasdan/bootstrap-datetimepicker#807]
Here's the fiddle:

http://jsfiddle.net/0Ltv25o8/188/

Thanks for this great library. Keep up the good work.

**Comment by Eonasdan** [comment]
left arrow is not disabled for me:

![image](https://cloud.githubusercontent.com/assets/1006516/6001893/624c66d4-aabc-11e4-947e-60302a987490.png)

**Comment by zlajson** [comment]
Seems like it is working now - when the system clock is greater than February 1st, 2015.

I have managed to reproduce this issue by following these steps:

1. Host the fiddle on local web server
2. Change the local web server system clock back to February 1st, 2015 (the date when I experienced and posted the issue).

**Comment by Eonasdan** [comment]
closing in favor of #820
