### ISSUE TITLE
Calendar and time picker at the same time

### ISSUE THREAD

**Issue by Garito** [Eonasdan/bootstrap-datetimepicker#809]
Hi!
I'm trying the new v4 inline calendar and I'm wondering if it is possible to put the calendar in a mode were the date picker and the time picker are shown at the same time (side by side)

Is it possible? How?

Thanks a lot!

**Comment by Eonasdan** [comment]
if you read the docs you'll find [`sideBySide`](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#sidebyside) which will give you what you want

**Comment by Garito** [comment]
Thanks a lot!
