### ISSUE TITLE
Checking if its date or time change event occurred

### ISSUE THREAD

**Issue by Exerlol** [Eonasdan/bootstrap-datetimepicker#810]
Is there a way to check which change event occurred? Was it date or time changed... Thanks in advance.

**Comment by Eonasdan** [comment]
No, not at this point. There's nothing that indicates if it was the date or the time. You can, however, compare the previous date and the new date

**Comment by Exerlol** [comment]
Oh, ok... thanks for the quick reply... comparing old and new date can do the trick for me... One more thing, if you could check issue (https://github.com/Eonasdan/bootstrap-datetimepicker/issues/797) i would really appreciate It. Thanks
