### ISSUE TITLE
Experiencing Error 'option pickDate is not recognized!' only on external domain w/ Chrome 40.0

### ISSUE THREAD

**Issue by JaisonBrooks** [Eonasdan/bootstrap-datetimepicker#811]
Im experiencing the following error `option pickDate is not recognized!` when my code is deployed to my domain. While running locally on a PHP server it does fine and i experience no error. However when i deploy my code to my AWS PHP hosted server and am running `Google Chrome` i am presented with the following error as soon as the input is rendered on the page. This issue doesnt seem to happen on Firefox or Safari.

Any ideas? or work arounds? or am i simply missing something here?

### Current Setup
* Beta v4 of the datetimepicker
* JQuery (google hosted v. 2.1.3)
* HTML 5 doctype
* PHP v5.5
* Google Chrome 40.0.2214.94 (64-bit)

Chrome Stacktrace (if helpful)
 ```javascript
/**
Uncaught TypeError: option pickDate is not recognized!
bootstrap-datetimepicker.min.js:1 (anonymous function)
jquery.min.js:2 
n.extend.eachbootstrap-datetimepicker.min.js:1 
j.optionsbootstrap-datetimepicker.min.js:1 
cbootstrap-datetimepicker.min.js:1 (anonymous function)
jquery.min.js:2 
n.extend.eachjquery.min.js:2 
n.fn.n.eachbootstrap-datetimepicker.min.js:1 
a.fn.datetimepickerindex.js:30 (anonymous function) **/
```

## Code
```javascript
$(function () {
        $('#time_in').datetimepicker();
        $('#time_out').datetimepicker();
        $("#time_in").on("dp.change",function (e) {
            $('#time_out').data("DateTimePicker").minDate(e.date);
        });
        $("#time_out").on("dp.change",function (e) {
            $('#time_in').data("DateTimePicker").maxDate(e.date);
        });
    });
```

```html
<form method="post">
...
    <input type='text' class="form-control text-center" id='time_in' name="time_in" value="<?php echo $time_in; ?>" required />
    <input type="text" class="form-control text-center" name="time_out" id="time_out" value="<?php echo $time_out;?>" required/>
...
</form>

```

**Comment by Eonasdan** [comment]
`pickDate` is an option we removed from v4 in favor of using the `format` string to determine what components to show.

Can you setup a jsfiddle with a minimal example of your code/issue?

**Comment by JaisonBrooks** [comment]
Here is the jsfiddel => http://jsfiddle.net/jaisonbrooks/Lgo9n256/

And i pulled the current external resource from the predefined jsfiddle to ensure it was the latest v4 and im receiving an error at this part in the script.

```javascript
throw new TypeError('option ' + key + ' is not recognized!');
```

**Comment by Eonasdan** [comment]
please let us know if you're still having this issue.
