### ISSUE TITLE
Date Picker Layout not uniform across months

### ISSUE THREAD

**Issue by bodrick** [Eonasdan/bootstrap-datetimepicker#812]
If you look at the jsfiddle : http://jsfiddle.net/Eonasdan/0Ltv25o8/, you'll see that if you look at February it fits perfectly into 4 weeks, but then May fits into 6 weeks.  In the old version it seemed to show 6 weeks no matter what.  Is there a chance this can be added back in, or set as an option?

**Comment by Eonasdan** [comment]
@bodrick please check the dev branch. I just put in a patch that show make the picker show 42 days at all time

**Comment by bodrick** [comment]
@Eonasdan Not sure if this is related, but I tried the dev branch and it appears to be working pretty well, however I did run into an issue regarding enabledDates, it seems in prior versions enabledDates would disable the month forward and back if there were no enabledDates in the future or past of the current month, but now it seems that regardless you can go forward or back.  The dates themselves are enabled or disabled just fine, its just the month forward and back buttons that seem to have the problem.

**Comment by Eonasdan** [comment]
@bodrick that is probably due to a bug where the buttons would disable when they shouldn't that I fixed.

**Comment by bodrick** [comment]
@Eonasdan So is it a bug, or it was a bug and has been fixed, if a bug do you want me to open a new issue for it?

**Comment by Eonasdan** [comment]
there was a bug where the arrows and other controls where disabled when it shouldn't have been, which I fixed.

The fix, might be the reason you see a different issue

**Comment by bodrick** [comment]
Fair enough, I actually realized in my testing that indeed the arrows were disabled when they shouldn't have been.  Anyway I figured out a solution to my other problem and all appears to be working well.
