### ISSUE TITLE
TypeError when using MinViewMode

### ISSUE THREAD

**Issue by rauldinho** [Eonasdan/bootstrap-datetimepicker#813]
Hi, when I try to use MinViewMode so the user can only select Year and Month, I get this error on the browser console: TypeError: o.find is not a function. 
![error-datepicker](https://cloud.githubusercontent.com/assets/984519/6029715/a90de684-abc4-11e4-8632-72bff878ba06.png)

**Comment by nikoskalogridis** [comment]
Give development branch a try. Try with the unminified version. That should be fixed there

**Comment by rauldinho** [comment]
In development branch is fixed.
