### ISSUE TITLE
Setting minDate does not change currently selected date before minDate

### ISSUE THREAD

**Issue by theduke** [Eonasdan/bootstrap-datetimepicker#816]
The docs specify: 

```
Note: If the minDate parameter is after the currently selected moment the currently selected moment changes to minDate parameter
```

This is not the case with the current release (tag 4.0.0).
If a picker has , for example, the date 20th of march selected, and I set the minDate to 25 of march, the picker does not change to 25th.

**Comment by Eonasdan** [comment]
can you post a fiddle please

**Comment by Eonasdan** [comment]
Please check the development branch.
