### ISSUE TITLE
Create a mirror field

### ISSUE THREAD

**Issue by nevits8as** [Eonasdan/bootstrap-datetimepicker#819]
U can created a mirror link that change a time i selected before? for example if i select in format MM/DD/YYYY the mirror link capture this value and change to DD/MM/YY, and the time too if i select un 24h in this mirror change in to 12h. This is becouse for the user enter the value in any way he want, but the mirror flied has the format i need to send via SQL

**Comment by Eonasdan** [comment]
Just use the [`date`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#date) function to get the date from the picker and call `format("DD/MM/YY")` or whatever [format](http://momentjs.com/docs/#/parsing/format/) you need it in.

All date's in the picker are Moment objects and you can format it as you need it.
