### ISSUE TITLE
Enabled / Disabled Dates

### ISSUE THREAD

**Issue by nodrog** [Eonasdan/bootstrap-datetimepicker#820]
Hi

I think i must be doing something wrong, but i cannot get enabledDates to work at all, and disabledDates is just not working write.

I have made a fiddle: http://jsfiddle.net/Lg7uk2db

As you can see it is using disabledDates (i would rather use enabledDates), if you look at 2015, the is not available March, but i am not disabling for example: 2015-03-03, 2015-03-04 or 2015-03-05.

Can anyone help. i love this picker it is by far the best. i have upgraded 4 because it has support for the picker being open to start with.

Many thanks

**Comment by nikoskalogridis** [comment]
Try the unminified version on the development branch. It is fixed there and will be release soon.

**Comment by nodrog** [comment]
that was super quick thanks.

if you mean this one...

https://raw.githubusercontent.com/Eonasdan/bootstrap-datetimepicker/development/build/js/bootstrap-datetimepicker.min.js

it does not help.

what seems to help is not having such a large list of dates disabledDates, would this make any sense?

http://jsfiddle.net/Lg7uk2db/2/

**Comment by nikoskalogridis** [comment]
try the unminified file /src/js/bootstrap-datetimepicker.js

Normally large lists should not be a problem.

**Comment by nodrog** [comment]
unfortunately it did not help.

It has something todo with the months and years being given a disabled class when they should not be.

If i change the class in the inspector it is selected the right days in the disabled months.

i am looking at the code now 

thanks

**Comment by stuf** [comment]
Made a workaround for this, came across this functionality when working on a datepicker implementation. The next month would be entirely disabled, even though it only contains a minority of disabled dates.

What I changed was how the internal isValid() method works, by changing the disabledDates conditional:
```javascript
if (options.disabledDates && isInDisabledDates(targetMoment) && granularity !== 'M') {
    return false;
}
```

This is a bit of an ugly fix, but probably going to try to have a closer look at this after I get this project over with.

**Comment by zlajson** [comment]
I have also experienced the same behavior.

I do also believe that this issue is related to #807

**Comment by nodrog** [comment]
We have only fixed up disabledDates but this works:

https://gist.github.com/nodrog/7a47db2a8056d1d51640

basically we pass granularity to isInDisabledDates, and then have an index for disabledMonths and disabledYears.

Hope this helps

**Comment by Eonasdan** [comment]
Please check the dev branch. Should be a fix in there for you. Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

**Comment by mathiassen1990** [comment]
Is enabledDates fixed or is it still only disabledDates?

**Comment by Eonasdan** [comment]
@mathiassen1990 I believe both should be fixed but there is currently an issue #874 with `minDate`

**Comment by rafaelfaria** [comment]
Hi all, sorry to post on an old topic, but just want to check if this has been really resolved.

I have the latest and I'm trying something like:

```
$("#datepicker").data("DateTimePicker").disabledDates([
	'2015-09-21'
]);
``` 

but no luck. It would enable previous disabled dates, but it wouldnt disable the new one.

**Comment by rafaelfaria** [comment]
Basically, after debugging a little bit, when adding the disabledDates in the initialization: 
```
	$('#datepicker').datetimepicker({
			locale: 'pt-br',
			format: 'DD-MM-YYYY',
			useCurrent: false,
			disabledDates: [
				'2015-09-27'
			]
		})
```

This will works.

I debugged the disabledDates function on your script and when outputting

```
console.log(indexGivenDates(dates));
```

i get 

```
Object {2015-09-27: true}
```

now when i run

```
$("#datepicker").data("DateTimePicker").disabledDates([
				'2015-09-21'
			])

i get

Object {2021-09-20: true}

```
