### ISSUE TITLE
Unable to Tab Forward when using the TimePicker only

### ISSUE THREAD

**Issue by jasonds** [Eonasdan/bootstrap-datetimepicker#822]
Please have a look at this JSFiddle:
http://jsfiddle.net/jdsears/wekedwjv/1/

Version : 4.0.0

When using the timepicker, I am unable to tab to subsequent input fields after the timepicker.
Here is the JavaScript to setup the timepicker:
var timepickerOptions = {
  format: "HH:mm"
};
$('#timepicker').datetimepicker(timepickerOptions);

From the JSFiddle, I set up a timepicker and a datepicker:
- If I start in input "Other Input 1" in the timepicker row and begin tabbing forward, I am unable to proceed after the timepicker.
- If I start in input "Other Input 1" in the datepicker row, I am able to tab forward to the end.

**Comment by jasonds** [comment]
I looked through the code and I believe I know why this was happening.
In the function getTimePickerMainTemplate, when the anchor elements are added for incrementing and decrementing hours/minutes/seconds, they are considered tab stops.
So when you tab from a timepicker input to the next input, the next tab stop is the increment anchor for hours (assuming hours is enabled). Then the widget is hidden.

The fix is to apply the following to each of the six anchors (increment and decrement for hours, minutes and seconds) in the getTimePickerMainTemplate function:
.attr('tabindex', '-1')

This certainly fixes the issue. I'm not sure if this is the desired change we'd like to push.
Please let me know your thoughts here.

**Comment by Eonasdan** [comment]
That's probably what it is. You're welcome to put a PR into the Dev branch of you want.

**Comment by Eonasdan** [comment]
I've got a fix in my local code. I hope to have that committed to the dev branch later this week

**Comment by Eonasdan** [comment]
I've add the tabindex fix to the dev branch

**Comment by jasonds** [comment]
Looks great - thanks for committing the fix!

**Comment by Eonasdan** [comment]
Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

**Comment by garethdn** [comment]
I can still repro this issue in the scenario where the AM / PM is introduced into the timepicker `format` attribute. For example, `'h:mm A'`

http://jsfiddle.net/wekedwjv/3/
