### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by rnjailamba** [Eonasdan/bootstrap-datetimepicker#824]
**I was using :**

$(function () {

               
$('#datetimepicker1').datetimepicker();

});

and was getting the above mentioned error.

 
**The error was solved by using:**

var j = jQuery.noConflict();

j(document).ready(function(){

             j('#datetimepicker1').datetimepicker();

})

Is there any reason for this?

**Comment by Eonasdan** [comment]
Please test and/or fork [this jsfiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) with an example of your issue.

You're probably using a conflicting library

**Comment by rnjailamba** [comment]
Havent been able to reproduce the issue,the other libraries are the following:

**My application.js file includes the following:**

//= require jquery

//= require jquery-ui

//= require jquery_ujs

//= require bootstrap

//= require turbolinks

//= require moment

//= require bootstrap-datetimepicker

//= require masonry/jquery.masonry

//= require_tree .

 
**And below are all my script tags:**

&lt;script
src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"&gt;


&lt;script
src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"&gt;&lt;/script&gt;

  &lt;script
type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&libraries=places&language=en-US"&gt;&lt;/script&gt;
