### ISSUE TITLE
Little problem with linked datetimepicker

### ISSUE THREAD

**Issue by caBBAlainB** [Eonasdan/bootstrap-datetimepicker#825]
Hello,
Your example doesn't allow to easily define an event which could start on, for example 2015/02/26 20:00 and ends on 2015/02/26 22:00.
We have to select the 27th, then choose 22:00 and then come back to 27th.
It maybe because of the way you set the minDate() of the second datetimepicker.
Maybe the minDate() should be set to 1 minute later, I don't know.
Is there a way to do it?
Regards,

**Comment by Eonasdan** [comment]
Please test and/or fork [this jsfiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) with an example of your issue

**Comment by rnjailamba** [comment]
I am using the linked date time picker given at http://eonasdan.github.io/bootstrap-datetimepicker/

My problem is similar to that given above.
It is related with picking up the date and time for an intra day event.

For example in the first text area select this date and time :02/26/2015 8:48 AM
Now attempt to select this date and time in the second text area:02/26/2015 9:20 AM which does not happen.

The problem can be simulated on the above link.

**Comment by caBBAlainB** [comment]
Hi,
I'm pleased to see the post of rnjailamba because it's exactly the problem I talked about.
I'm really sorry Eonasdan because I didn't reply to your answer, and I thank you for it, but I was very very busy these last days.

**Comment by Eonasdan** [comment]
please check the dev branch. this issue appears to be resolved there

**Comment by caBBAlainB** [comment]
Yoh thanks eonasdan I take a look at it.

**Comment by caBBAlainB** [comment]
I think it's maybe not really fixed.
I tried https://github.com/Eonasdan/bootstrap-datetimepicker/tree/development is it correct?
Date of bootstrap-datetimepicker.min.js seems to be on feb 21st at 18:21

Because I still cannot define an event with starting hour and ending hour within the same day.

For example if I choose (french locale) 29/03/2015 20:00, I cannot choose 29/03/2015 22:00, I still have to choose 30/03/2015 22:00, then 29/02/2015 22:00.

My code is here http://jsfiddle.net/Eonasdan/0Ltv25o8/
I have the same behavior but does this fiddle use the development code?

**Comment by Eonasdan** [comment]
try the non minified version

**Comment by caBBAlainB** [comment]
Perfect!!!!

**Comment by Eonasdan** [comment]
Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

**Comment by caBBAlainB** [comment]
no problem, thanks a lot.
