### ISSUE TITLE
Linked Pickers: Unable to navigate through month tabs

### ISSUE THREAD

**Issue by m1ndCtrl3r** [Eonasdan/bootstrap-datetimepicker#826]
Hey,

I'm using Linked Pickers as the example shown here:http://eonasdan.github.io/bootstrap-datetimepicker/.
I've noticed that when you set an initial date (datetimepicker6) to a future month the nav arrows on the ending date picker (datetimepicker7), which by default opens in the current month, are disabled and it's impossible to select any date at all.

I found a way around this: after setting the initial date, when opening the ending date picker the date is set to the date on the first datepicker. This way it redirects to the month that it's possible to set the ending date.

Here is the code I used:
$("#datetimepicker7").on("dp.show",function () {
if ($("#datetimepicker7").data("DateTimePicker").date() == null){
$("#datetimepicker7").data("DateTimePicker").date($("#datetimepicker6").data("DateTimePicker").date()); } });

I guess this would be a default functionality to prevent this type of bug ;)

![bugz](https://cloud.githubusercontent.com/assets/10886264/6085001/02a755fc-ae2e-11e4-9e24-5f68d49dc078.png)

**Comment by Eonasdan** [comment]
please check the dev branch. I believe this issue has already been fixed. Please let me know if it's not
