### ISSUE TITLE
Uncaught TypeError: undefined is not a function  bootstrap-datetimepicker.js:508 after selecting date in months view

### ISSUE THREAD

**Issue by reckface** [Eonasdan/bootstrap-datetimepicker#827]
I've only started using the viewMode: 'months' (or MM/YYYY format) and I noticed the following error in the console view for Chrome the following every time I choose a month (this also occurs on the read the docs sample):

Uncaught TypeError: undefined is not a function  bootstrap-datetimepicker.js:508
at fillDate
actions.selectMonth
doAction
jQuery.event.dispatch
jQuery.event.add.elemData.handle
It appears to be caused by the widget being false after the picker is collapsed
if(!widget) return; // I've added this to fix it for now
var daysView = widget.find('.datepicker-days'),
                    daysViewHeader = daysView.find('th'),
                    currentDate,
                    html = [],
                    row,
                    clsName;
For now I've added a condition that checks for the widget before calling find on it, but as it's a nuget package, I expect the next update will wipe out my change, and I don't know what implications this change would have on other uses.

**Comment by nikoskalogridis** [comment]
this has been corrected on development branch and will surface to master branch once a new release is made
