### ISSUE TITLE
Expected behaviour of disabledDates and daysOfWeekDisabled

### ISSUE THREAD

**Issue by gwynjudd** [Eonasdan/bootstrap-datetimepicker#829]
I'm not really sure what the expected behaviour is supposed to be here. Please see this fiddle:

http://jsfiddle.net/fafoLkkz/

In the second picker I have used disabledDates to disable the current date, as well as daysOfWeekDisabled to disable sunday.

However, you can type in a date that is on a sunday, but you cannot type in a date that is today's date. This seems inconsistent to me, but I'm not sure what the expected behaviour is meant to be.

![image](https://cloud.githubusercontent.com/assets/314188/6100004/c3f71d70-b06b-11e4-94c3-25dd6c2af402.png)

**Comment by Eonasdan** [comment]
please check the dev branch and let me know if you still have this issue

**Comment by gwynjudd** [comment]
Yes that seems to have fix the issue

**Comment by Eonasdan** [comment]
Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.
