### ISSUE TITLE
How do you use the functions?

### ISSUE THREAD

**Issue by ryanmortier** [Eonasdan/bootstrap-datetimepicker#830]
Using this code:

    var date = $('#date').datetimepicker();
    date.destroy();

I get: `Uncaught TypeError: undefined is not a function`

**Comment by aspyatkin** [comment]
Actually, you should be using functions as in other jQuery plugins:
``` javascript
$('#date').datetimepicker('destroy');
```

**Comment by ryanmortier** [comment]
Great, that worked. Thank you very much.
