### ISSUE TITLE
Is it possible to only pick date

### ISSUE THREAD

**Issue by sjvisschers** [Eonasdan/bootstrap-datetimepicker#832]
It's more a question then a issue. 
Is it possible to only pick a date with this module?

**Comment by djtechonline** [comment]
I would also like to be able to pick only the date so I can use it to select a "date of birth" field, for example.  An option like "pickTime: false" would be great.  Then, the datetimepicker should only return the date format, without the time.  Is there a way to do this now?

**Comment by Eonasdan** [comment]
v4  use the [`function`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#format) setting to determine what components to show. See the [format example](http://eonasdan.github.io/bootstrap-datetimepicker/#custom-formats)

To show only the date use `format: 'MM/dd/YYYY` or `format: 'L'`

**Comment by djtechonline** [comment]
Yes!  format: 'L' works great.  However, if using the other format: use uppercase DD, not lowercase dd.  Lowercase will return an abbreviated day of the week such as th for Thursday.  Thank you!

**Comment by Eonasdan** [comment]
as mentioned in the docs... `format` takes a valid [momentjs format string](http://momentjs.com/docs/#/displaying/format/)

**Comment by davitk** [comment]
Thank's it works for me
