### ISSUE TITLE
Min View Mode causes 'Uncaught TypeError: undefined is not a function' exception when selecting month

### ISSUE THREAD

**Issue by nseba** [Eonasdan/bootstrap-datetimepicker#833]
When you set the following options:
`viewMode: 'years',
format: 'MM/YYYY'`
and then select the year, then month an `Uncaught TypeError: undefined is not a function` is thrown in the browser. 

This can be even reproduced with the sample on the website: http://eonasdan.github.io/bootstrap-datetimepicker/#min-view-mode (select 2015, then Jan).

Digging inside the code it seems that the `fillDate` method should have a check for `widget === false` and return if that's the case.

**Comment by simplicitylab** [comment]
Also had this problem adding a widget check solved the problem 

https://gist.github.com/simplicitylab/0af888a62b51f749c9d9

**Comment by vicmancb** [comment]
I would like to use bootstrap-datetimepicker in my project, but I cant implement it with this bug. I'll wait the solution of this

**Comment by Eonasdan** [comment]
please check dev branch. this issue has already been brought up and I believe @nikoskalogridis has already fixed it.
