### ISSUE TITLE
get user selected date

### ISSUE THREAD

**Issue by billyysim** [Eonasdan/bootstrap-datetimepicker#834]
hi. im kinda new in php and javascript coding.

so this is more of a question than an issue,

after user select date and is shown in the input area.
how do i get that value when i submit the form?

i hope my english is clear enough.

thanks

**Comment by Eonasdan** [comment]
you just get the date from the input field like you would any other input field when the form is posted.

if you're trying to get the date via javascript, I suggest [reading the docs](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#date).

**Comment by v1p** [comment]
To be honest, this needs to be documented properly I believe. It's not clear from the docs page that `.date()` is a function/property of what & how it can be accessed. I had to use `$el.data("DateTimePicker").date()` in order to get it.

**Comment by mmuelle4** [comment]
Totally agree with @v1p -- although it is documented on the main page, there is absolutely zero mention of the fact that one has to use the data attribute to access any of the functions on the actual functions page. Providing example usage of each function on the function page with the proper $('#elem').data('DateTimePicker').functionName(...) syntax would've made the quest to get this working way easier.

**Comment by Eonasdan** [comment]
![image](https://cloud.githubusercontent.com/assets/1006516/6695398/4784b3e8-ccb7-11e4-87c8-cb30fd654fe0.png)

**Comment by mmuelle4** [comment]
To be clear @Eonasdan, my comment acknowledged that the alert you posted is available on the main page, but not on the actual Functions page. It should exist on both pages (rather than forcing one to hunt around on multiple pages just to figure out how to use a function).

**Comment by v1p** [comment]
Yeah even I never bothered to goto mainpage & went directly to functions page, as that was the area of concern for me. 
I might have skipped the callout note on the mainpage, as it has no business there IMO, that the mainpage is primarily a showcase of what the plugin can do.

This is an amazing plugin as far as datetime picker goes. Quite easy to use once you know the way around, and I was able to customize it a bit to work with Foundation 5, well at least the basics of it.
