### ISSUE TITLE
Change the date only icon by setting the hidden field.

### ISSUE THREAD

**Issue by pedrosalpr** [Eonasdan/bootstrap-datetimepicker#835]
In version 3, I could change the date to the hidden field and so call the function and changed the page. In the new version 4, I can not change the date, do not open the calendar.

My code is in https://jsfiddle.net/pedrosalpr/prsodvv6/1/  that worked in version 3. How can I change the code to work to work in version 4?

I've tried several times, but all failed.

**Comment by Eonasdan** [comment]
your fiddle throws console errors. Can you reproduce your issue with v3 or v4 that doesn't get console errors?

**Comment by pedrosalpr** [comment]
I updated the fiddle, creating several fiddles with different libs:

moment (2.9.0) and datetimepicker (3.1.3) - (Runs)
http://jsfiddle.net/pedrosalpr/prsodvv6/2/

moment (2.10.3) and datetimepicker (3.1.3) - (Runs)
http://jsfiddle.net/pedrosalpr/prsodvv6/3/

moment (2.10.3) and datetimepicker (04.07.14) - (Error - It does not show the calendar)
http://jsfiddle.net/pedrosalpr/prsodvv6/4/
