### ISSUE TITLE
v4 is not working on IE8

### ISSUE THREAD

**Issue by raysunqi** [Eonasdan/bootstrap-datetimepicker#836]
options.daysOfWeekDisabled = daysOfWeekDisabled.reduce(function (previousValue, currentValue) 

the function reduce is not supported until IE9

can you please fix it?

**Comment by Eonasdan** [comment]
You can add the [Polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#Polyfill) to your project
