### ISSUE TITLE
V4 No longer works in dropdown

### ISSUE THREAD

**Issue by mapkyca** [Eonasdan/bootstrap-datetimepicker#837]
V3 supported the ability to have the date selector in a dropdown. This functionality no longer seems to work in V4

(see http://jsfiddle.net/0Ltv25o8/282/)

On my code, if I go back to the dropdown after the initial select, the datepicker displays on dialog load (can't replicate in JS fiddle), so initially I thought it might be the initialisation was triggering an onChange(), since the control now defaults to Today.

However, setting ```useCurrent: false``` prevents the picker from working at all. This may be a separate issue.

**Comment by Eonasdan** [comment]
This may not work for you but, you can use inline mode

```
<ul class="dropdown-menu qualitiesdate">
                            <li><a href="javascript:void(0)" value="today">Today</a></li>
                            <li><a href="javascript:void(0)" value="tomorrow">Tomorrow</a></li>
                            <li>
                                <div id="datetimepicker7">
                                </div>
                            </li>
                        </ul>

$('#datetimepicker7').datetimepicker({
                inline: true
            });
```
