### ISSUE TITLE
V4:  Knockout Binding Handler

### ISSUE THREAD

**Issue by svtguy88** [Eonasdan/bootstrap-datetimepicker#838]
What are the thoughts on adding a Knockout binding handler to the project/docs?  I noticed there is an Angular directive linked int he docs, but nothing for KO.

I recently updated to v4, and re-worked my binding to function correctly again.  Anyway, here's what I'm using, in case it may help others.  The defaults are set up for what I need, but that's easy enough to change.

#### Markup

    <input type="text" data-bind="datTimePicker: { format: 'MM/DD/YYYY' }, value: DateTime />

#### Binding Handler
```javascript
ko.bindingHandlers.dateTimePicker = {
    init: function (element, valueAccessor, allBindings, viewModel, bindingContext) {

        var options = ko.unwrap(valueAccessor());
        var valueObservable = allBindings.get('value');

        var defaults = {
            //defaultDate: valueObservable(), //can't set default here because parsing fails for time strings (ex:  "09:15 AM" throws error)
            format: 'MM/DD/YYYY hh:mm A',
            icons: {
                down: 'fa fa-chevron-down',
                up: 'fa fa-chevron-up'
            },
            minDate: '01/01/1986',
            stepping: 15,
            sideBySide: false,
            widgetPositioning: {
                horizontal: 'auto',
                vertical: 'auto'
            }
        };

        var config = ko.utils.extend(defaults, options); //override defaults with passed in options
        var $pickerElement = $(element).datetimepicker(config);

        $pickerElement.data("DateTimePicker").date(valueObservable()); //force initial value to be whatever is in the observable

        $pickerElement.bind('dp.change', function (eventObj) {
            var picker = $(element).data("DateTimePicker");
            if (picker) {
                var date = picker.date();
                var formattedDate = date ? date.format(picker.format()) : "";
                if (formattedDate != valueObservable()) {
                    valueObservable(formattedDate);
                }
            }
        });

        ko.utils.domNodeDisposal.addDisposeCallback(element, function () {
            var picker = $(element).data("DateTimePicker");
            if (picker) {
                picker.destroy();
            }
        });

    },
    update: function (element, valueAccessor, allBindings, viewModel, bindingContext) {

        var picker = $(element).data("DateTimePicker");
        if (picker) {
            var valueObservable = allBindings.get('value');
            var date = picker.date();
            var formattedDate = date ? date.format(picker.format()) : "";
            if (formattedDate != valueObservable()) {
                picker.date(valueObservable());
            }
        }

    }
};
````

**Comment by Incognito-Nemo** [comment]
I'm totally agree with this post : an official Knockout Binding Handler is necessary !

I use <input type="text" data-bind="datTimePicker: { format: 'DD/MM/YYYY' }, value: DateTime />

I have a problem with your solution : i'm french so the date is in format DD/MM/YYYY. When I use your code, I have the month and the day inverted. How can I solve it ?

**Comment by svtguy88** [comment]
> I use input type="text" data-bind="dateTimePicker: { format: 'DD/MM/YYYY' }, value: DateTime

I've only tested it using the few format that I need, but I would think that passing in the correct format for you ("DD/MM/YYYY") would have fixed your problem.  As far as I know, this plugin accepts any of the moment.js format strings.

If I have some time later today, I'll play with it and see if I can get your format working correctly.

**Comment by svtguy88** [comment]
@Incognito-Nemo  - can you describe your problem more?  I just tried using "DD/MM/YYYY" as follows, and it appears to work correctly:

    <input type="text" data-bind="dateTimePicker: { format: 'DD/MM/YYYY' }, value: DateObservable, valueUpdate: 'input'" />

**Comment by Incognito-Nemo** [comment]
I have many problems…

I use input type="text" data-bind="dateTimePicker: { format: 'DD/MM/YYYY' }, value: DateTimeObservable, valueUpdate: 'input'"

First, on init, the format is not applyed : I have displayed Thu Feb 22 1973 01:00:00 GMT+0100 and not 22/02/1973.

Second, when I try to put 23/02/1973 in the datetimepicker, the result is Sat Nov 02 1974 00:00:00 GMT+0100 and not 23/02/1973.

Any idea ?

And thanks a lot for your precious help !

**Comment by anthonny2890** [comment]
<input data-bind = "datetimepicker:FechaInicioContrato, datetimepickerOptions: { minDate: new Date(), locale:'PUTMYLOCALE' } , event: {change: flagContratoClienteAsEdited}"  /> i am working with moment_with_locales.js and then 
ko.bindingHandlers.datetimepicker = {
    init: function (element, valueAccessor, allBindingsAccessor) {
        //initialize datepicker with some optional options
        var options = allBindingsAccessor().datetimepickerOptions || {};
         $(element).datetimepicker(options);

        //when a user changes the date, update the view model
        ko.utils.registerEventHandler(element, "dp.change", function (event) {
            var value = valueAccessor();
            if (ko.isObservable(value)) {
                value(event.date);
            }
        });
        
        ko.utils.domNodeDisposal.addDisposeCallback(element, function () {
            var picker = $(element).data("DateTimePicker");
            if (picker) {
                picker.destroy();
            }
        });
    },
    update: function (element, valueAccessor) {
        
        var picker = $(element).data("DateTimePicker");
        //when the view model is updated, update the widget
        if (picker) {
            var koDate = ko.utils.unwrapObservable(valueAccessor());
//in case return from server datetime i am get in this form for example /Date(93989393)/ then fomat this
            koDate = (typeof (koDate) !== 'object') ? new Date(parseFloat(koDate.replace(/[^0-9]/g, ''))) : koDate;
            picker.date(koDate);
           
        }
    }
};

**Comment by Incognito-Nemo** [comment]
Thanks a lot for your help. It works for me except that the returned value is a Moment and not a Date type.

I modify your code in the registerEventHandler function : 

    ko.bindingHandlers.dateTimePicker = {
        init: function (element, valueAccessor, allBindingsAccessor) {
            //initialize datepicker with some optional options
            var options = allBindingsAccessor().dateTimePickerOptions || {};
            $(element).datetimepicker(options);

            //when a user changes the date, update the view model
            ko.utils.registerEventHandler(element, "dp.change", function (event) {
                var value = valueAccessor();
                if (ko.isObservable(value)) {
                    if (event.date != null && !(event.date instanceof Date)) {
                        value(event.date.toDate());
                    } else {
                        value(event.date);
                    }
                }
            });

            ko.utils.domNodeDisposal.addDisposeCallback(element, function () {
                var picker = $(element).data("DateTimePicker");
                if (picker) {
                    picker.destroy();
                }
            });
        },
        update: function (element, valueAccessor, allBindings, viewModel, bindingContext) {

            var picker = $(element).data("DateTimePicker");
            //when the view model is updated, update the widget
            if (picker) {
                var koDate = ko.utils.unwrapObservable(valueAccessor());

                //in case return from server datetime i am get in this form for example /Date(93989393)/ then fomat this
                koDate = (typeof (koDate) !== 'object') ? new Date(parseFloat(koDate.replace(/[^0-9]/g, ''))) : koDate;

                picker.date(koDate);
            }
        }
    };

Are you agree with this suggestion ? It seems to work for me…

**Comment by anthonny2890** [comment]
okay , take care :-) :+1:

**Comment by Eonasdan** [comment]
so... do you guys still want something on the wiki or the installation guide and which code block?

**Comment by Incognito-Nemo** [comment]
It seems to be like Angular in Installation guide, on the model of the Angular wrapper directive.

**Comment by Eonasdan** [comment]
adding this to the docs in the installation section with the next push

**Comment by svtguy88** [comment]
Which code block are you going with for the installation section?  I'm not totally sure any of them are generalized enough for people to just copy/pasta from project to project...

I think there is a happy medium somewhere between my code block and the one that @Incognito-Nemo and @anthonny2890 came up with:

* For example, to keep with what seems to be "standard" KO binding handler convention, I'd like to see the "value" binding hold the date observable, and then have the  "dateTimePIcker" binding's valueAccessor be an object containing specific options for the picker.

* The code in the update callback that handles invalid server date formats, I feel, shouldn't be there.  The date should be passed down from the server in a format that is recognizable.  The date format you show there looks like an issue that I ran into recently.  If you're on .NET, the issue is that the date gets mangled during serialization - you should override the formatting on the server (this [page](http://www.hanselman.com/blog/OnTheNightmareThatIsJSONDatesPlusJSONNETAndASPNETWebAPI.aspx) contains some good info - if this is your issue, also beware of the [IE9 millisecond bug](http://stackoverflow.com/questions/11789114/internet-explorer-json-net-javascript-date-and-milliseconds-issue)).

**Comment by Eagle3386** [comment]
Hey everyone,

I'm struggling with the awesome datetimepicker in conjunction with KnockoutJS 3.3.0 and TypeScript 1.4.
Using the example code from http://eonasdan.github.io/bootstrap-datetimepicker/Installing/#knockout I get:
```PowerShell
Property 'dateTimePicker' does not exist on type 'KnockoutBindingHandlers'
```

So I've added a Knockout interface for that, because the current TypeScript definition for Bootstrap V3 DateTimePicker was written for version 3.0.0 and not the recent 4.14.30 one (BTW: @Eonasdan the changelog at http://eonasdan.github.io/bootstrap-datetimepicker/Changelog/ has a typo stating version 4.14.40 as the latest):
```TypeScript
/// <reference path="knockout.d.ts" />

interface KnockoutBindingHandlers {
  dateTimePicker: KnockoutBindingHandler;
}
```

Then I faced and fixed the next error:
```PowerShell
Property 'date' does not exist on type 'Datetimepicker'.
```
By modifying **bootstrap.v3.datetimepicker.d.ts** with this:
```TypeScript
line 32 (**interface DatetimepickerOptions**): format?: any;
lines 58-62 (**interface Datetimepicker**):
date(): any;
date(date: any): void;
format(): any;
format(format: any): void;
```
I got it through compiling. However, it seems that I've missed something, because having
``` TypeScript
ko.utils.registerEventHandler(element, "dp.change", function(event) {
  var value = valueAccessor();
  console.log(value);
```
doesn't log anything.

What am I missing (or doing wrong)?

**Comment by ark4n631** [comment]
@pkmccaffrey Thanks a lot, this was very useful information, you may want to do a github repo for your handler and mantain it.

Regards

**Comment by pkmccaffrey** [comment]
Thanks for the feedback.  I've been meaning to set up a repo for a few of the random binding handlers I've got floating around.  Hopefully I find some time to get these things organized soon.

**Comment by ark4n631** [comment]
@pkmccaffrey Just let me know when you do so i can help and give feed back ;)

Also leave a star into the repo, was really helpful.

Regards and thanks again

**Comment by pkmccaffrey** [comment]
Is there still interest in me putting the code for the KO binding up in a repo?  I've recently found myself making some changes to the code to allow for localizing date/times based on the browser's time zone, which may or may not be helpful for others.

**Comment by Eagle3386** [comment]
Of course! The more, the better! 👍
