### ISSUE TITLE
Link to documentation for Version 3

### ISSUE THREAD

**Issue by lucatros** [Eonasdan/bootstrap-datetimepicker#839]
Can you add a link to the documentation for Version 3?
Thanks!

**Comment by Eonasdan** [comment]
v3 is here: http://eonasdan.github.io/bootstrap-datetimepicker/version3/

**Comment by lucatros** [comment]
awesome. Thanks!

**Comment by Eonasdan** [comment]
You're welcome. I updated the readme in the branch to show the docs.
