### ISSUE TITLE
Display picker inline

### ISSUE THREAD

**Issue by loopmode** [Eonasdan/bootstrap-datetimepicker#84]
Hi,

It would be very useful to be able to display the picker directly, without the need of a input and a click into it. For example, this could be the default behaviour when the plugin is applied to a div-element instead of an input-element.

**Comment by Eonasdan** [comment]
how does this work for you? http://jsfiddle.net/Eonasdan/k0ghcjsa/

**Comment by Eonasdan** [comment]
closing for #752

**Comment by Eonasdan** [comment]
Try the dev branch and use this code:

```
<h6>datetimepicker3</h6>
<div class="form-group">
	<label for="datetimepicker3">datetimepicker3</label>
	<div class="row">
		<div class="col-md-8">
			<div id="datetimepicker3"></div>
		</div>
	</div>
</div>

$('#datetimepicker3').datetimepicker({
	inline: true,
	sideBySide: true
});
```

cheers!

**Comment by Eonasdan** [comment]
Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.
