### ISSUE TITLE
Display timepicker above datepicker

### ISSUE THREAD

**Issue by diogoalexandrefranco** [Eonasdan/bootstrap-datetimepicker#840]
Maybe this isn't an issue and i just haven't figured it out:

Is it possible to, when using 'sideBySide: false,' have the picker display the time picker first, with the calendar for the date picker below it?

Thanks for this!

**Comment by Eonasdan** [comment]
the date will always display first, if it's enabled. you can also use `collapse: false` which will display them vertically.

**Comment by diogoalexandrefranco** [comment]
Thanks, and is there any way to toggle it via javascript, so that, even if the date is above the time, one could force the transition to the timepicker on loading?

**Comment by Eonasdan** [comment]
I guess you could try something like `.find('.picker-switch a[data-action="togglePicker"]').click()` on the show event?

**Comment by diogoalexandrefranco** [comment]
That worked beautifully, thanks!
