### ISSUE TITLE
Mindate to disable selection but still allow display of older dates.

### ISSUE THREAD

**Issue by Shobs** [Eonasdan/bootstrap-datetimepicker#842]
Hello, 

I am currently using minDate to limit selection of past dates.  My issue is that the input field is blank when it is populated from the db with a past date.

I'd like for minDate to limit the selection but not the display of past dates, is there any ways to achieve that?

Thanks!

**Comment by Zanguu** [comment]
Have you tried setting defaultDate to your minDate ?

**Comment by Shobs** [comment]
Hi thanks for the reply, I can't use defaultDate as it would override (I assume) the date populated from the database, which I want to display, but sometimes happens to be outside the minDate range.

For example: 
-minDate is set to moment() / "now"
-User sets date to today and saves it.
-User comes back tomorrow and wants to see / modify date, minDate prevents date from being shown since it's outside it's range

Hope my issue is clear enough.

**Comment by Eonasdan** [comment]
`keepInvalid` has been added as an option to the dev branch. This should allow you to set the input to an older date. Please check it out and let me know

**Comment by Eonasdan** [comment]
Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

**Comment by linhkurt** [comment]
Set <code>keepInvalid:true</code> definitely does the job. Thank you!
