### ISSUE TITLE
V4: Can't set default value

### ISSUE THREAD

**Issue by Stajor** [Eonasdan/bootstrap-datetimepicker#843]
In gem file
```
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.0.0'
```
In js
```
        $('#user_birthday').datetimepicker({
            defaultDate: "11/10/1984",
            viewMode: 'years',
            format: 'DD/MM/YYYY'
        });
```

Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.

Please update documentation for right defaultDate

**Comment by Eonasdan** [comment]
the docs on [`date`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#date) and [`defaultDate`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#defaultdate) states that the function will take "string, Date, moment, boolean:false". Therefore, the docs are correct. If you don't want the error, construct the date with a moment or js Date object
