### ISSUE TITLE
.date() doesn't work when a maxDate is defined

### ISSUE THREAD

**Issue by Sladix** [Eonasdan/bootstrap-datetimepicker#844]
See http://jsfiddle.net/0Ltv25o8/309/ for example

**Comment by Eonasdan** [comment]
Your code doesn't work because you're trying to set the date to a date **past** the `maxData`.

your `feeling-date` throws a `dp.error` event when you click on the button

**Comment by Sladix** [comment]
Daaaaaaamn ! Maaaaan ! I'm a fool lol Mind Blown

**Comment by Eonasdan** [comment]
lol no worries. it happens.
