### ISSUE TITLE
Setting date() to a empty string returns the same value

### ISSUE THREAD

**Issue by tit1** [Eonasdan/bootstrap-datetimepicker#845]
Perhaps im missing something in the documentation, if so please let me know. Im trying to clear a selected date from a previous selection by doing:

`$("#catDialog #timeDue").data("DateTimePicker").date('');`

According to the javascript console no error is throw but the time remains the same.
my date-time picker is being initiated like so:
`
    $("#catDialog #timeDue").datetimepicker({
     format: 'LT',
     stepping: 15,
    });
`

**Comment by Eonasdan** [comment]
try passing in `null` instead.
