### ISSUE TITLE
V4: data-date-defaultDate Not working

### ISSUE THREAD

**Issue by Isaac-Kleinman** [Eonasdan/bootstrap-datetimepicker#846]
Assigning a value to the `defaultDate` option using the `data-date` attribute like this:

`data-date-defaultDate="2/17/2015"` is not working.

I have to resort to doing it via JavaScript as follows:

`datetimepicker( { defaultDate : "02/17/2015" })`

**Comment by Isaac-Kleinman** [comment]
I see now that `minDate` and `maxDate` aren't either working for me.

**Comment by Zanguu** [comment]
Got the same issue, you have to change the camelCase to dash separated words.
- defaultDate => data-date-default-date
- minDate => data-date-min-date
- etc

**Comment by Isaac-Kleinman** [comment]
Ah. Thanks for pointing that out.

I also noticed that the `data-date-*` attributes now have to be on the surrounding `<div class="input-group date" data-date-*...>' rather than in the nested `input` tag as was the case in V3.

**Comment by MohammadDayeh** [comment]
using data-date-min-date instead of data-date-minDate worked for me
