### ISSUE TITLE
No documentation exists for retrieving the JS date object via .data('DateTimePicker')

### ISSUE THREAD

**Issue by marc-lebourdais** [Eonasdan/bootstrap-datetimepicker#847]
It took looking through the test code to figure out how to extract the underlying object from a datepicker widget before finally realizing all you had to do was:

    $('#myDatePicker').data('DateTimePicker')

I'm fairly new to jQuery, so maybe this is common-enough knowledge that it doesn't require documentation? I'd still think that for novice users that it should be explicitly specified.

**Comment by Eonasdan** [comment]
while not explicitly in the documentation that read "hey do this". It is in all the examples

**Comment by marc-lebourdais** [comment]
Examples where? I haven't found them I guess.

**Comment by Eonasdan** [comment]
it's the link on the front page: http://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by marc-lebourdais** [comment]
The only example that has it is:
http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers

That's hardly obvious or "in all the examples."

**Comment by marc-lebourdais** [comment]
I see you added this in big font at the top of the docs. I appreciate it!
