### ISSUE TITLE
Automatically focusing on input makes date selection awkward on mobile

### ISSUE THREAD

**Issue by grassick** [Eonasdan/bootstrap-datetimepicker#848]
v3 did not automatically focus on the input, meaning that if the calendar icon was clicked, the user would see just the popup widget.

v4 now focuses in `show`:
```
                if (!input.is(':focus')) {
                    input.focus();
                }
```

That means that ~ half of the screen is covered by the mobile keyboard, obscuring the widget and making it very difficult to use on mobile.

**Comment by tschiela** [comment]
+1. Very annoying on mobiles. Maybe there should be an option like autoFocus (true|false)

**Comment by asofta** [comment]
+1

**Comment by mohsinraza** [comment]
check my comment might be helpful for you.
https://github.com/Eonasdan/bootstrap-datetimepicker/pull/793#issuecomment-75078483

**Comment by ahmader** [comment]
+1

**Comment by robwatkin** [comment]
I have locally patched tschiela's fix (see above) into the current master branch. It works except with linked pickers - http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers On android the first picker doesn't hide when the second is selected.

**Comment by bookreev** [comment]
+1

**Comment by Eonasdan** [comment]
#884 was pulled into the dev branch to address this issue.
