### ISSUE TITLE
TypeError: option pickTime is not recognized!

### ISSUE THREAD

**Issue by almogdesign** [Eonasdan/bootstrap-datetimepicker#850]
I'm getting the following error after upgrading to V4 but I'm not seeing this change in the changelog or how this is now set 

TypeError: option pickTime is not recognized!

My code 
$('#datepicker').datetimepicker({pickTime: false, useCurrent: false, defaultDate:this.data.block.organicFieldStatusTo, locale:  TAPi18n.getLanguage()});

**Comment by Zanguu** [comment]
Not in the changelog but pickDate and pickTime where removed. This is managed by the 'format' option.
The format function parse the format string and check if you have a date componant and/or a time component to toggle this.

I use 'dd/MM/YYYY' to get only de datepart and 'HH:mm' to get only the time part.

**Comment by almogdesign** [comment]
ook thanks

**Comment by devamitbera** [comment]
HI have face same issue. If i add  any  option it show error  **_Uncaught TypeError: option onRender is not recognized!_**.

I have tried with  $('#datetimepickerSCFrom').datetimepicker({
       format: 'DD-MM-YYYY',
       onRender: function(date) {
		return date.valueOf() < now.valueOf() ? 'disabled' : '';
		}
     
    });

Also tried with startDate and get the issue.Also tried with  change date format dd/MM/YYYY
Using jquery   jQuery-2.1.4.min.js.

**Comment by Eonasdan** [comment]
there's no option `onRender`
