### ISSUE TITLE
Datetime Picker not showing

### ISSUE THREAD

**Issue by danfsd** [Eonasdan/bootstrap-datetimepicker#852]
Hello,
I was able to successfully use the Datetime Picker on pure HTML, but I'm not able to integrate this component to my Yii2 application (PHP) with the AppUI Backend template (by PixelCave).

When I try to click on the button, the date is placed on the input text but no popover appears. What could possibly be causing this problem?

All javascript files are being imported at the head section and in this order:
1st jQuery 2.1.3
2nd Moment.JS (with locales) 2.9
3rd Bootstrap 3
4th Bootstrap-Datetimepicker V4
![js](https://cloud.githubusercontent.com/assets/4552181/6255738/8a94b058-b799-11e4-8970-bc13886ea77e.PNG)

I'm also importing Bootstrap-Datetimepicker's CSS.
![css](https://cloud.githubusercontent.com/assets/4552181/6255730/8371d2a6-b799-11e4-971a-e774d9626938.PNG)

Add to this situation the fact that nothing is being logged at the console, so no importion errors are happening.
Can this problem be generated by CSS conflicts with the AppUI template?

It's difficult for me to create a jsFiddle because the problem only occurs inside the framework itself.

Thanks in advance!

**Comment by Eonasdan** [comment]
Can you setup a demo page somewhere and give me a link?

Have you checked your console log to make sure you aren't getting an error?
