### ISSUE TITLE
Widget is locked if minDate() is greater that selected date

### ISSUE THREAD

**Issue by rimano** [Eonasdan/bootstrap-datetimepicker#853]
Hi I have notices in version 4.0 that if you set minDate greater than date which is already selected that month navigation gets locked.
Navigation thought months using  back and forward < > arrows that are located on the top of the widget is disabled.
Example with this issue is shown here:
http://jsfiddle.net/0Ltv25o8/331/

Regards

**Comment by Eonasdan** [comment]
please check the dev branch, I believe it's been fixed there

**Comment by rimano** [comment]
Yes, it is fixed there. Thanks
