### ISSUE TITLE
EnabledDates not work

### ISSUE THREAD

**Issue by megeduar** [Eonasdan/bootstrap-datetimepicker#854]
Hello
Little time to work with this control seems very iteresante ago, but my problem is when I only want to show days available that has a program where you insert the dates available under the enabledDates owned nothing happens, you should let me active only those dates and other disabled if they could help me with this problem.

**Comment by Eonasdan** [comment]
Please submit a jsfiddle of your issue. You can fork [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) to get started.

**Comment by megeduar** [comment]
$('#circuit-date').datetimepicker({
        enabledDates: [outputdates]
    });
this is an example of the code I use, the outputdates variable is an array of available dates.
What I want to achieve ess only available dates are activated.

**Comment by Eonasdan** [comment]
please check the dev branch and let me know if you still have this issue

**Comment by gungp720** [comment]
$('#dob').datetimepicker({
        format: 'YYYY-MM-DD',
        enabledDates : ["02/23/2015","02/28/2015","03/02/2015"]
    });
hello, please check this, using dev brach, i can't choose next month enabled dates (march 2015). I can only choose current month enabled dates (february 2015). Thank you.

**Comment by gwynjudd** [comment]
Maybe try this fiddle which shows some interesting behaviour:

http://jsfiddle.net/fafoLkkz/

I noticed that on "datepicker2", you if you go to January 2015, then the button to go to february is disabled - I think it is because 1 Feb would be disabled, it being a sunday. You also can't select February from the months view, or go back to February from March.

![image](https://cloud.githubusercontent.com/assets/314188/6320210/38dcfd18-bb3d-11e4-8d20-99b7ccd3bc64.png)

![image](https://cloud.githubusercontent.com/assets/314188/6320216/56e13888-bb3d-11e4-84fb-e4038117d549.png)

![image](https://cloud.githubusercontent.com/assets/314188/6320221/6c37da16-bb3d-11e4-8da7-27a89c366e73.png)

**Comment by mathiassen1990** [comment]
Hi i have same experience, when i choose some dates to be enabled. I expected the rest of the dates to be disabled. But that does not seem to happen.

Se my fiddle for example: http://jsfiddle.net/sqagg9jp/

**Comment by megeduar** [comment]
Hi, the only solution I had was to do the reverse process, generate a set date and I excluded that sets the dates I want who are enabled, then that result is what I set the disabledDates property that works well for me. Do not know if this solution suits you, so expect future versions.

**Comment by mathiassen1990** [comment]
How would you make that line of code?
Can't figure out how to disable all dates except thoose i want to allow.
Can you show on fiddle?

**Comment by Eonasdan** [comment]
please check the dev branch. Except for the bug that @gungp720 mentioned the enabled dates is working there.

**Comment by mathiassen1990** [comment]
Don't seem to work, i updated the bootstrap-datetimepicker.min.js to the one from the dev branch.
But it still don't disable all other dates than thoose i choose to enable.

**Comment by mahipatsinh007** [comment]
I have a same Issue like I passes a date String in 
            $(".datetimepicker").datetimepicker({
                format: 'MM/DD/YYYY',

                disabledDates: [moment(disabledSpecificDays)],

 })


where disabledSpecificDays is Date string like ",10/01/2013,10/03/2013,10/05/2013,10/07/2013,10/09/2013,10/08/2013,10/11/2013,"  but It is not working

**Comment by mahipatsinh007** [comment]
I have a same Issue like I passes a date String in 
            $(".datetimepicker").datetimepicker({
                format: 'MM/DD/YYYY',

                disabledDates: [moment(disabledSpecificDays)],

 })


where disabledSpecificDays is Date string like ",10/01/2013,10/03/2013,10/05/2013,10/07/2013,10/09/2013,10/08/2013,10/11/2013,"  but It is not working

**Comment by Eonasdan** [comment]
`en/disabledDates` expects an array of `string`, `Data`, or `moment`. It should be `disabledDates: ['date1','date2']` etc

**Comment by mathiassen1990** [comment]
it gets a date, as i wrote in my earlier post: http://jsfiddle.net/sqagg9jp/

**Comment by Eonasdan** [comment]
@mathiassen1990 my last comment was directed at @mahipatsinh007

**Comment by mathiassen1990** [comment]
Okay, fair enough :) But then he still got the same problem as me.
Cause i have the array of dates, and it still dont work. Even though i have the dev version.

**Comment by nikoskalogridis** [comment]
@mathiassen1990 

http://jsfiddle.net/sqagg9jp/1/

isn't this working as you expect?

**Comment by mathiassen1990** [comment]
It is, what version is that? didn't work earlier..

**Comment by nikoskalogridis** [comment]
it is the version (not the minified one) on the development branch. On your jsfiddle you where using the master branch version

**Comment by mathiassen1990** [comment]
Cool Thanks! i will give it a try, ill be back if it still don't work :)
