### ISSUE TITLE
Day duplicate in October

### ISSUE THREAD

**Issue by fbeas** [Eonasdan/bootstrap-datetimepicker#855]
datepicker shows a duplicate day for October
![dupliqueday](https://cloud.githubusercontent.com/assets/11092980/6289704/b8d4d232-b900-11e4-9be5-2e7cf716cfe4.png)

**Comment by bjoe2k4** [comment]
Not on my side, can you create a jsfiddle?

**Comment by Eonasdan** [comment]
Please check the development branch. I think I fixed this by moving the fillDate to startOf day
