### ISSUE TITLE
DateTimePicker with "MM/YYYY" format, disappears after picking a month

### ISSUE THREAD

**Issue by Exerlol** [Eonasdan/bootstrap-datetimepicker#856]
Ok, so I had to change format of datetimepicker on lets say button click, my default format was "dd MM yyyy", so on a button click i wanted to change it to "MM/YYYY", managed to do so with : 

$('#datetimepicker').data("DateTimePicker").format('MM/YYYY').hide().show(); - without hide / show datetimepicker remained unchanged.

So, with this code format changes , but when i click on any month datetimepicker disappears. Even if i use keepOpen: true.

You can check it out http://jsfiddle.net/batngmea/12/

So my 1st would be : I dont like this hide, show workaround... Is there another way to do this (refresh datetimepicker) or smthing?

And second question would be : How to keep picker open after picking a month :P

Thanks in advance

**Comment by Exerlol** [comment]
So, any1 got idea how to make inline month picker? Because that's what i basically need.

**Comment by Eonasdan** [comment]
you can use `inline:true` in the dev branch. Updated docs and a push to master is coming soon

**Comment by Exerlol** [comment]
Yep,  im using it,  but  when i select month with format:  MM/YYYY picker disappears...even if i use keepOpen option.. i just need to show year / month picker without days... so i can choose year / month only... hope you get what i mean.. thx for ur effort btw...

**Comment by Exerlol** [comment]
I made a fiddle with new inline option, but as you see, as soon as you pick something widget disappears... How can i keep it open? 
Fiddle : https://jsfiddle.net/8xmucouf/1/

**Comment by Eonasdan** [comment]
@Exerlol this should be fixed by the way

**Comment by Exerlol** [comment]
Hey mate, yep it works as expected now... Thank you very much!
