### ISSUE TITLE
ViewMode after reopen

### ISSUE THREAD

**Issue by pr1moz** [Eonasdan/bootstrap-datetimepicker#857]
Hi,
I'm using viewMode: 'years' option for the date of birth input and the first time the user opens the datepicker it works fine, but the second time the view starts with days. I think that if the viewMode was set it should be used every time the datepicker is opened.

Thanks for a great datepicker :)

**Comment by Eonasdan** [comment]
There is nothing in the code at the moment that will do this automatically for you. However, you can listen for the change event and use the ['viewMode'](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#viewmode) function to reset it to years

**Comment by mvpkenlin** [comment]
If you look at line 963, you will see this
`currentViewMode = 0;`

Just comment it and it will not reset the viewMode

**Comment by luisgustavolf** [comment]
Problem persist in the last version (4.17.45)... I've applied the same fix and every things is work good, so far...
