### ISSUE TITLE
JS error when using keyboard navigation and useCurrent: false

### ISSUE THREAD

**Issue by jfschwarz** [Eonasdan/bootstrap-datetimepicker#859]
On the development branch, there is a JavaScript error when using keyboard navigation in the calendar popup with `useCurrent: false`:

```
TypeError: null is not an object (evaluating 'this.date().clone')
``` 

See the following fiddle for a demonstration of the bug:

http://jsfiddle.net/0Ltv25o8/361/

(Open the datepicker popover and hit the arrow down key.)

**Comment by Eonasdan** [comment]
good catch! thanks!

**Comment by Eonasdan** [comment]
Please check the dev branch. Should be a fix in there for you. Assuming no other major issue with the dev branch come up this week, dev will be prompted to master March 7th.
