### ISSUE TITLE
class label requires "addon" to be first

### ISSUE THREAD

**Issue by end-user** [Eonasdan/bootstrap-datetimepicker#860]
`bootstrap-datetimepicker.js:1614` is checking that the class attribute begins with "input-group-".  This prevents the use of other classes that might be mixed in, e.g. "btn btn-default input-group-addon".  It might be better to use `element.find('[class*="input-group-"]')`

**Comment by webcmsdesigns** [comment]
you shouldn't be mixing .btn classes with .input-group-addon. "you'll need to use .input-group-btn to wrap the buttons"
http://getbootstrap.com/components/#input-groups-buttons

**Comment by Eonasdan** [comment]
is there any reason to use the button group instead of the input group?

Please post your suggestion to the #841 v5 planning issue
