### ISSUE TITLE
update the wiki

### ISSUE THREAD

**Issue by ctrl-f5** [Eonasdan/bootstrap-datetimepicker#863]
please add clear information in the wiki and homepage about how this plugin works, ie: that it does not update the value of the input the picker is on...

this was pretty essential for me and I lost quite some time figuring this out.

also, setting defaultDate option did not work in any way, shape or form.

**Comment by Eonasdan** [comment]
you mean like the link to the full documentation at the top? http://eonasdan.github.io/bootstrap-datetimepicker/

As per the Contrib docs, please provide a jsfiddle of your issue

**Comment by ctrl-f5** [comment]
yeah im too frustrated to be bothered

**Comment by Eonasdan** [comment]
well I can't help you if you don't bother to tell me what's wrong. Hope the docs help
