### ISSUE TITLE
pickTime and pickDate are no longer options

### ISSUE THREAD

**Issue by SiddharthMantri** [Eonasdan/bootstrap-datetimepicker#864]
It seems like `pickTime` and `pickDate` can no longer be recognized as options for a `datetimepicker`. 

If this was done intentionally, what's the alternative? It would help a lot if mentioned in the changelogs.

**Comment by Eonasdan** [comment]
`pickTime` and `pickDate` were removed in favor of the `format` string.

The `format` option takes an valid MomentJs format.

If you just want the date: `format: 'MM/dd/YYYY`. Likewise, `format: 'HH:mm`. The moment shortcuts also work `L,LT,LTS`

**Comment by dmr** [comment]
The example you mentioned format: 'MM/dd/YYYY' is assuming american way of setting a date. How do I specify a format that can be localized?

**Comment by Eonasdan** [comment]
@dmr see the documentation about the format: http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#format

all valid moment format strings are accepted
