### ISSUE TITLE
localize date format

### ISSUE THREAD

**Issue by martingg88** [Eonasdan/bootstrap-datetimepicker#865]
can it localize the date format based on selected locale?

for example en-gb

2 January 2015

for example en-us
january 2 2015

**Comment by Eonasdan** [comment]
yes. just include the local file from momentjs and pass in `locale: en-gb`

http://eonasdan.github.io/bootstrap-datetimepicker/#using-locales

**Comment by martingg88** [comment]
yes..it work..but it seems have a bug there. 

The following must give me the 'ms-my' language in output. But, it show me another language (etc: chinese) for the output.
 $('.date').datetimepicker({
        format: 'LL',
        ignoreReadonly: true,
        showClear: true,
        locale: 'ms-my'
    });

**Comment by Eonasdan** [comment]
This is working as expected.

Please see the momentjs docs on formatting: http://momentjs.com/docs/#/displaying/

The [`ms-my`](https://github.com/moment/moment/blob/develop/locale/ms-my.js) locale uses  `D MMMM YYYY` as the `LL` format.

if you still have an issue please post a jsfiddle
