### ISSUE TITLE
Getting/setting value with locales

### ISSUE THREAD

**Issue by bartzon** [Eonasdan/bootstrap-datetimepicker#866]
I'm struggling to have the datetimepicker display a timestamp from the database.

What I want is the following:

- display the date and time in the textfield in the Dutch locale,
- have the datetimepicker use the Dutch locale.

Obviously the timestamps are in UTC in the database, but I cannot for the life of me find the right combination to render the times in the form, and have the datetimepicker do it's magic correctly.

Rails renders the following in my form:
```
<input value="2015-02-26 16:00:00 UTC" />
```

My datetimepicker init call is:
```
  $('.datetimepicker').datetimepicker({
    locale: 'nl',
    calendarWeeks: true,
    showTodayButton: true,
  })
```

Given the example above, the datetimepicker display **20-02-0026 16:00** in the field, which is obviously incorrect. The docs do not give any pointers on how to set and parse specific values.

Any ideas?

**Comment by Eonasdan** [comment]
are you including the proper locale file?

**Comment by bartzon** [comment]
Yup:

```
//= require moment
//= require moment/nl
//= require bootstrap-datetimepicker
```

**Comment by Eonasdan** [comment]
hmm.. the option `extraFormats` **should** allow you to use the format you get from the DB and parse it into the `format` option.

A quick work around would be to do this

`$('#datetimepicker1').data("DateTimePicker").date(moment('2015-02-26 16:00:00 UTC'));`

**Comment by bartzon** [comment]
Not quite:

```
<div class="form-group">
  <div class='input-group date' id='datetimepicker1'>
    <input type='text' class="form-control" />
    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
    </span>
  </div>
</div>
```

and

```
  $('#datetimepicker1').date("DateTimePicker").date(moment('2015-02-26 16:00:00 UTC'));
```

gives error:

```
TypeError: undefined is not a function (evaluating '$('#datetimepicker1').date("DateTimePicker")')
```

**Comment by Eonasdan** [comment]
that line should go after your init.

can you setup a jsfiddle or a demo page?

**Comment by bartzon** [comment]
Yeah, I still have the .datetimepicker() call in my javascript files.

I'll whip up a fiddle.

**Comment by bartzon** [comment]
http://jsfiddle.net/zcegtLr1/3/

**Comment by Eonasdan** [comment]
` $('#datetimepicker1').date("DateTimePicker").date(moment('2015-02-26 16:00:00 UTC'));`

should be

` $('#datetimepicker1').data("DateTimePicker").date(moment('2015-02-26 16:00:00 UTC'));`

:)

**Comment by bartzon** [comment]
I've updated the fiddle, still get:
```
[Error] TypeError: undefined is not an object (evaluating '$('#datetimepicker1').data("DateTimePicker").date')
	(anonymous function) (_display, line 40)
	fire (jquery-2.1.0.js, line 3047)
	add (jquery-2.1.0.js, line 3093)
	ready (jquery-2.1.0.js, line 3326)
	init (jquery-2.1.0.js, line 2768)
	jQuery (jquery-2.1.0.js, line 78)
	(anonymous function) (_display, line 33)
	dispatch (jquery-2.1.0.js, line 4371)
	handle (jquery-2.1.0.js, line 4057)
```

**Comment by webcmsdesigns** [comment]
I fiddled around a bit with some options for this, just note none of them will produce a date that can be blindly inserted in the db. I didn't see an obvious way to pass UTC in the date string in the moment docs. Moment does have options for working directly with UTC dates, which I have barely experimented with, but touched on in the fiddle. 

I have had the best luck with converting the date stored in the db to the proper locale format (via PHP), prior to populating the form and loading the datetimepicker. Of course you then need to convert it back to store it in the db. To make validating and converting it back easier I split the date and time selection into 2 input fields and force the 24hr format on all users; an example of which I also fiddled with...

http://jsfiddle.net/spasticdonkey/7he0s2mf/1/

**Comment by bartzon** [comment]
Thanks @webcmsdesigns, that gave me enough info to get it working. For the record:

```
  $('.datetimepicker').datetimepicker({
    locale: 'nl',
    format: 'YYYY-MM-DD HH:mm:ss',
  })
```

and

```
<%- t0 = f.object.online_at.present? ? I18n.l(f.object.online_at, format: '%Y-%m-%d %H:%M:%S') : nil -%>
<%= f.text_field :online_at,  value: t0, class: 'datetimepicker', append: i('calendar') %>
```

@Eonasdan, it might be an idea to add something similar to this to the documentation.

**Comment by Eonasdan** [comment]
@bartzon how about this: `extraFormats: ['YYYY-MM-DD HH:mm:ss [UTC]']`? You'll have to convert the date back to UTC before you stick it in your db though

**Comment by Eonasdan** [comment]
`format` now supports the inclusion of the brackets `[]`
