### ISSUE TITLE
Behaviour of enabledDates and next/back buttons

### ISSUE THREAD

**Issue by gwynjudd** [Eonasdan/bootstrap-datetimepicker#867]
I'm seeing a problem when you have enabledDates set which includes some dates in another month - the month view disables the next/back buttons so you cannot go to that month to choose the date.

See this fiddle for an example (note it is using the dev branch of datetimepicker, but I think the same behaviour occurs in release):

http://jsfiddle.net/u6q8d7ua/

It has one date enabled in january, and one date in february. On the month view, the "next/back" buttons are disabled. On the year and also decade view, all of the buttons are disabled (except on the year view, the next/back buttons are enabled).

![image](https://cloud.githubusercontent.com/assets/314188/6399044/e31ad38a-be54-11e4-870b-8d8e2c59ae4d.png)

![image](https://cloud.githubusercontent.com/assets/314188/6399051/ef74f138-be54-11e4-99ba-4c87afa7d9c7.png)

**Comment by gwynjudd** [comment]
There is also a similar behaviour with daysOfWeekDisabled:

http://jsfiddle.net/wb4zjv01/

On this picker, if you go back to January, the back button is disabled

**Comment by Eonasdan** [comment]
Please check the dev branch. Should be a fix in there for you. Assuming no other major issue with the dev branch come up this week, dev will be prompted to master March 7th.

**Comment by gwynjudd** [comment]
It doesn't seem to be quite right - for instance, in this fiddle (it is using the dev branch):

http://jsfiddle.net/u6q8d7ua/

When you open the date picker, the next/back buttons are disabled in March, even though you should be able to go back to select a date in February.

Also, if you bring up the year view, all of the months are disabled.

![image](https://cloud.githubusercontent.com/assets/314188/6432577/3b32260a-c0bb-11e4-9a78-90bb7230e18f.png)

**Comment by Eonasdan** [comment]
@gwynjudd unfortunately, rawgit.com doesn't update to the latest. Have you tried this locally or pointing a fiddle to the github tree?

**Comment by gwynjudd** [comment]
Ah yes, I hadn't noticed it didn't update. I updated the fiddle to use 'rawgit.com' instead of 'cdn.rawgit.com' - this uses the latest update from github:

http://jsfiddle.net/u6q8d7ua/1/

The logic for enabledDates doesn't seem to be correct in this version - the dates that are in enabledDates are disabled, and all other dates are enabled. I think there is a simple true/false error in the logic for isValid, note that the enabledDates and disabledDates cases are exactly the same:

                if (options.disabledDates && isInDisabledDates(targetMoment) && granularity !== 'M') {
                    return false;
                }
                if (options.enabledDates && isInEnabledDates(targetMoment) && granularity !== 'M') {
                    return false;
                }

The daysOfWeekDisabled behaviour seems to be ok in this version however.

**Comment by Eonasdan** [comment]
yup, you're right. I had introduced this bug today. Oops! fixed though

**Comment by gwynjudd** [comment]
LGTM
