### ISSUE TITLE
Provide the same look-and-feel of Bootstrap popover?

### ISSUE THREAD

**Issue by chuanconggao** [Eonasdan/bootstrap-datetimepicker#868]
Strongly hope the this great date-time picker can provide the same matching look-and-feel of the official Bootstrap popover. I am using both date-time picker and popover for some inputs in the page, and the styles just do not match. 

Currently I am modifying the CSS by myself, but can not get a perfect result, especially the arrow position and size. 

Maybe the date-time picker can be wrapped in a popover, instead of a customized widget.

**Comment by Eonasdan** [comment]
Please add this as a comment to the #841 v5 planning issue. Thanks
