### ISSUE TITLE
Keep timepicker open

### ISSUE THREAD

**Issue by razor-rich** [Eonasdan/bootstrap-datetimepicker#869]
is there a way to disabled the click off event so the timepicker doesn't close when i inspect my code using dev tools?

**Comment by Eonasdan** [comment]
if you're using the dev branch, I just added a `debug` option. setting this to `true` will prevent the `hide()` from being called on a `blur` event

**Comment by razor-rich** [comment]
Sorry my knowledge of jQuery isn't the best. Like this?
                            <script type="text/javascript">
                            $(function () {
                                $('#start_time').datetimepicker({
                                    format: 'LT',
                                    debig: true
                                });                              
                            });
                            </script>

**Comment by Eonasdan** [comment]
yup!

**Comment by razor-rich** [comment]
Doesn't seem to work
https://jsfiddle.net/5fu1w85L/

**Comment by Eonasdan** [comment]
the fiddle has console error's and you're loading the datepicker from the master branch. You'll need to download the files from the dev branch

**Comment by razor-rich** [comment]
is there not just a simple function which keeps the timepicker open so i can inspect it and add some styling?

wheres the dev branch - out of interest?

**Comment by Eonasdan** [comment]
The dev branch is here: https://github.com/Eonasdan/bootstrap-datetimepicker/tree/development

As I said, this feature hasn't made it into the master yet. Adding `debug: true` will keep the picker open.

**Comment by razor-rich** [comment]
Excellent - sorry for my stupidity.

**Comment by dustapplications** [comment]
hopefully option to keep open just like debug:true will also be added.
