### ISSUE TITLE
Disable following year

### ISSUE THREAD

**Issue by dincio** [Eonasdan/bootstrap-datetimepicker#871]
Is there a way to disable the following year? i mean i want to restrict that user cant select a year more than the current year. because i will use the date picker to restrict under 18 years old

**Comment by Eonasdan** [comment]
this is easy to do with [`min/maxDate`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#minmaxdate)

```
minDate: moment().subtract(18, 'y'),
maxDate: moment().add(1,'y')
```

**Comment by dincio** [comment]
the minDate: moment().subtract(18, 'y'), is not working, i can still select the year that is not supposed to be chosen as i will be requiring to register and select only those 18 years old and above
