### ISSUE TITLE
how set value?

### ISSUE THREAD

**Issue by anthonny2890** [Eonasdan/bootstrap-datetimepicker#873]
$('#Date').datetimepicker('setValue',new Date()); because don't work :( help

**Comment by Eonasdan** [comment]
`$('#Date').data("DateTimePicker").date(newDate)`

**Comment by anthonny2890** [comment]
thanks! and this is integration with knockout works!
ko.bindingHandlers.datetimepicker = {
    init: function (element, valueAccessor, allBindingsAccessor) {
        //initialize datetimepicker with some optional options
        var options = allBindingsAccessor().datetimepickerOptions || {};
         $(element).datetimepicker(options);

        //when a user changes the date, update the view model
        ko.utils.registerEventHandler(element, "dp.change", function (event) {
            var value = valueAccessor();
            if (ko.isObservable(value)) {
                value(event.date);
            }
        });
        
        ko.utils.domNodeDisposal.addDisposeCallback(element, function () {
            var picker = $(element).data("DateTimePicker");
            if (picker) {
                picker.destroy();
            }
        });
    },
    update: function (element, valueAccessor) {
        
        var picker = $(element).data("DateTimePicker");
        //when the view model is updated, update the datetimepicker
        if (picker) {         
            picker.date(ko.utils.unwrapObservable(valueAccessor()));            
        }
    }
};
:+1:

**Comment by Argun** [comment]
thanks
