### ISSUE TITLE
minDate being applied to every month

### ISSUE THREAD

**Issue by webcmsdesigns** [Eonasdan/bootstrap-datetimepicker#874]
Running into an issue on the dev branch, where use of minDate: moment() is resulting in the minimum day being applied to every month. This being Feb 28th you can only select the 28th and after in each month. 
![datetimepicker-issue](https://cloud.githubusercontent.com/assets/3319686/6429071/9b9bdff8-bf81-11e4-952d-8cca7ca4a4d5.png)

this does not occur in the master branch.
http://jsfiddle.net/spasticdonkey/3w5wqvnb/3/

Since tomorrow is the 1st it may be harder to spot the issue after today ;)

**Comment by Eonasdan** [comment]
just put in a fix for this. please check the dev branch and let me know if you're still having the issue

**Comment by webcmsdesigns** [comment]
Fixed the minDate issue, but we seem to have lost the localized formatting "L", at least in looking at the fiddle link above. Tried both "fr" and "de" and both ended up as MM/DD/YYYY. Off to work but I'll look at it more in a few hours.

**Comment by Eonasdan** [comment]
that should be fixed now too

**Comment by webcmsdesigns** [comment]
nicely done. minDate and maxDate are working without issue, in the half dozen locales I'm working with. Even unusual formats such as Hungarian "YYYY.MM.DD." ;)
