### ISSUE TITLE
pickTime:false is it working?

### ISSUE THREAD

**Issue by peopledrivemecrazy** [Eonasdan/bootstrap-datetimepicker#875]
$(function () {
            $('#date').datetimepicker();
            format: 'YYYY-MM-DD'
            pickTime:false
                 
        });

This code is supposed to pick only dates and not time along with it? Correct me if I am wrong.

**Comment by peopledrivemecrazy** [comment]
Moreover, I want to make them into two separate fields one for choosing the date and other for time only, not both together my head is about to blowup.

**Comment by webcmsdesigns** [comment]
pickTime is an option for a different datetimepicker. Removing that should get you going, if you are using this script that is... :)
For the time picker you'll want format: 'HH:mm' or one of the other moment time formats, to limit picker to time selection. http://momentjs.com/docs/#/displaying/format/

**Comment by peopledrivemecrazy** [comment]
<img src="http://puu.sh/ghB8k/89a784387a.png">
I still don't get the desired result, it automatically puts time after the date.
The code right now is <pre>        $(function () {
            $('#date').datetimepicker();
            format: 'l'
            $('#time').datetimepicker({
                format: 'LT'
            });
        });</pre>

**Comment by webcmsdesigns** [comment]
looks like a syntax error. this is a different fiddle but see the picker5 and picker6 example
http://jsfiddle.net/spasticdonkey/7he0s2mf/1/

**Comment by peopledrivemecrazy** [comment]
Thank you so much, This fixed my issues how silly of me.
