### ISSUE TITLE
Incorrect events documentation

### ISSUE THREAD

**Issue by JiaJian** [Eonasdan/bootstrap-datetimepicker#876]
The docs page stated `change.dp`, `show.dp`, etc as events. I think you meant `dp.change`, `dp.show` and `dp.hide`. The page is [here](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/)!

**Comment by Eonasdan** [comment]
Thanks. I'm aware of this. I expect to push the dev to master this coming Saturday and will fix the docs. We had hope to have the namespaces fixed, but `change.dp` causes issues so we had to revert it (again)

**Comment by JiaJian** [comment]
I see. Thanks for the clarification! :smile:
