### ISSUE TITLE
Linked datepicker

### ISSUE THREAD

**Issue by qwertynus** [Eonasdan/bootstrap-datetimepicker#878]
Hi,
thanks for you work. It's great!
I have one question: how can i update the second datepicker with the minDate of the first datepicker?

The code is:
```javascript
$("#txt-datefrom").on("dp.change", function (e) {
    $('#txt-dateto').data("DateTimePicker").minDate(e.date);
    $('#txt-dateto').data("DateTimePicker").defaultDate(e.date);
    $('#txt-dateto').val(e.date.format("DD/MM/YYYY"));
});
$("#txt-dateto").on("dp.change", function (e) {
    $('#txt-datefrom').data("DateTimePicker").maxDate(e.date);
});
```
![image](https://cloud.githubusercontent.com/assets/4681579/6437650/c92ad42e-c0c1-11e4-91dd-94a925436bd3.png)
If i choose `20/04/2015` in the first one, how can i change the displayed month in the second datepicker?

Thank you very much.

**Comment by Eonasdan** [comment]
instead of

```
$('#txt-dateto').data("DateTimePicker").defaultDate(e.date);
$('#txt-dateto').val(e.date.format("DD/MM/YYYY"));
```

use
`$('#txt-dateto').data("DateTimePicker").date(e.date);`

**Comment by qwertynus** [comment]
Thank you very much! It's OK!
