### ISSUE TITLE
Select Multiple Dates

### ISSUE THREAD

**Issue by WhayP** [Eonasdan/bootstrap-datetimepicker#879]
Is there a provision for selecting multiple dates and storing it as an array ?

Basic need is for the user to be able to select multiple dates using the date picker.

**Comment by WhayP** [comment]
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/755 I guess from a similar issue, This can't be achieved. :-1:

**Comment by Eonasdan** [comment]
nope sorry this isn't a feature. If you find an existing date picker that does this, you can post a request for a new feature in the #841 v5 planning issue
