### ISSUE TITLE
[v4] 24-hours handling fails with German locale from moment.js v2.8

### ISSUE THREAD

**Issue by althaus** [Eonasdan/bootstrap-datetimepicker#883]
Hey,

I just updated our system to use the latest v4 and the 24 hour detection fails when sticking to moment.js v2.8.* (we had [2.8.3](https://github.com/moment/moment/blob/2.8.3/locale/de.js) as defined in the `bower.json`. The reason is that the German locale defines the time as `HH:mm [Uhr]`. As your code simply checks for `h` to trigger AM/PM it fails in this situation.

I guess a clean fix would be to strip every literal matching `[.*]` from the format before guessing the  value for `use24hours` in [line 1053](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/v4.0.0/src/js/bootstrap-datetimepicker.js#L1053) or bring back the config option. I'll fix it by updating moment.js to [2.9](https://github.com/moment/moment/blob/2.9.0/locale/de.js) where the German locale is now just defined as `HH:mm` and therefore not raising an issue. So raising the dependency would be a workaround. I don't know how common those literals are in general.

Fiddle for reproduction: http://jsfiddle.net/xjpbw5r1/1/

Cheers
Matthias

**Comment by Eonasdan** [comment]
I've changed all the dependencies to moment 2.9

**Comment by althaus** [comment]
:+1:
