### ISSUE TITLE
Disabled day of week not respected for current date

### ISSUE THREAD

**Issue by edclement** [Eonasdan/bootstrap-datetimepicker#885]
if you set `disabledDaysOfWeek = [3];` (which disables Wednesday) and if you click the "Today Button", the date selected (today/now) is considered valid even though it falls on a Wednesday.

**Comment by webcmsdesigns** [comment]
I can confirm this behavior on the development branch. The today button will honor the minDate and maxDate settings, but not daysOfWeekDisabled
http://jsfiddle.net/spasticdonkey/do6mzhse/1/

**Comment by Eonasdan** [comment]
Please check the development branch.
