### ISSUE TITLE
Dynamically changing End Date to selected Start Date

### ISSUE THREAD

**Issue by kevinrogerteng** [Eonasdan/bootstrap-datetimepicker#886]
Hey,

Sorry for the dumb question, but is there a way to dynamically update the End Date when Start Date has been selected? Right now, when I select a start date 3 months from now, opening the End Date widget is no clickable (since end date can't be before start date) or I would have to scroll all the way the page where user has selected Start Date.

Thanks!

**Comment by Eonasdan** [comment]
You could set the date of the 2nd picker in the change event. Presently, there is not a method for setting the "view date" of the picker. 

There is a feature request #872 that will likely produce a new feature to allow you to set the view date without actually changing the date.

**Comment by webcmsdesigns** [comment]
This is a fiddle for another issue but may help.
http://jsfiddle.net/spasticdonkey/3w5wqvnb/3/

I have a start and expiration picker but I've set useCurrent: false on both of them, which may differ from your approach (and be of some help)

**Comment by kevinrogerteng** [comment]
Thanks, both comments are very useful. I've also realized that it was the maxDate and minDate that was causing issues for me. Something I didn't notice before popping a question in here. 

Thanks again.

**Comment by Glideh** [comment]
Thanks @webcmsdesigns `useCurrent: false` was what I needed.
Without, it was setting the constraint on both inputs from the first opening.

```javascript
function updatePickers() {
    var start_date = $(START_DATE).data('DateTimePicker');
    var end_date = $(END_DATE).data('DateTimePicker');
    if (end_date.date()) {
        start_date.maxDate(end_date.date());
    }
    if (start_date.date()) {
        end_date.minDate(start_date.date());
    }
}

var dp_options = {
    format: 'DD/MM/YYYY HH:mm',
    useCurrent: false
}

$(START_DATE + ',' +  END_DATE)
    .datetimepicker(dp_options)
    .on('dp.change', updateDuration)
;
updateDuration();

```
