### ISSUE TITLE
Automatic hide on selection

### ISSUE THREAD

**Issue by laurentlemaire** [Eonasdan/bootstrap-datetimepicker#887]
Hi,

How can I hide the datepicker as soon as a date has been selected?

Thanks,

**Comment by webcmsdesigns** [comment]
The picker should close automatically if using a format that does not include time.
format: "MM/DD/YYYY" or format: "L" amongst others
http://momentjs.com/docs/#/displaying/format/

**Comment by Eonasdan** [comment]
listen for the change event `dp.change` then call the `hide()` function
