### ISSUE TITLE
"Today" doesn't work

### ISSUE THREAD

**Issue by rjamesnw** [Eonasdan/bootstrap-datetimepicker#889]
I created a data attribute "data-date-today-btn="true" and "Today" shows in the footer of the datepicker popup (as expected).  I then changed it to "false", and it no longer shows (also as expected).  The issue is when "Today" is showing in the footer, it's only text (can't click it).  Any ideas?

This is what gets rendered:
````
    <tfoot><tr><th class="today" style="display: table-cell;" colspan="7">Today</th></tr><tr><th class="clear" style="display: none;" colspan="7">Clear</th></tr></tfoot>
````

**Comment by Eonasdan** [comment]
this `data-date-show-today-button="true"` should be on the input.

**Comment by rjamesnw** [comment]
It was on the input, and nothing showed.  I'll try to create a sample project to show it.
