### ISSUE TITLE
v4 Dependency on Bootstrap less source

### ISSUE THREAD

**Issue by warrendodsworth** [Eonasdan/bootstrap-datetimepicker#892]
I'd like to ask why the dependency on boostrap less source in Bootstrap.v3.Datetimepicker.CSS.

I used nuget to download the package - Bootstrap.v3.Datetimepicker.CSS - update and was forced to download the LESS source and Bootstrap fonts, when I already have a Boostrap CSS and fonts in the project.

The Twitter.Boostrap.Less dependency in nuget forces everyone to download Less files when its expected to check for a dependency on Bootstrap CSS.

The other version Bootstrap.v3.Datetimepicker I'm guessing is meant to be dependent on the Twitter.Boostrap.Less package.

Thanks :)

**Comment by penihel** [comment]
I Have same Problem. One of the earlier versions had the same problem and it was fixed. Now the problem back again

**Comment by penihel** [comment]
Here #776

**Comment by Eonasdan** [comment]
yes yes... the build for the css package had the wrong dependency. it's fixed
