### ISSUE TITLE
Is there a way to set minTime maxTime?

### ISSUE THREAD

**Issue by geocine** [Eonasdan/bootstrap-datetimepicker#894]
I am currently using the time picker for start time and end time. Is there a way to set minTime and maxTime within the day? like 8:00 to 23:00 :heavy_check_mark: , 20:00 to 23:00 :heavy_check_mark:, not 15:00 to 8:00 :x:

**Comment by Eonasdan** [comment]
```
$('#datetimepicker1').datetimepicker({
    minDate: moment({h:8}),
    maxDate: moment({h:23})
});
```

**Comment by artamonovdev** [comment]
Add the attribute for this option.
