### ISSUE TITLE
setting default time using defaultDate

### ISSUE THREAD

**Issue by geocine** [Eonasdan/bootstrap-datetimepicker#895]
I have start time and end time fields. I couldn't set the default time for the end time field using defaultDate

Here is a jsfiddle https://jsfiddle.net/cyden0gs/1/

**Comment by Eonasdan** [comment]
`defaultDate` only sets the date when the picker is initialized.

There's a feature request #872 to allow you to set the `viewDate` but I haven't had time to work on it. Please keep an eye on that issue (even add a +1 so you'll get a notification).
