### ISSUE TITLE
On select day event?

### ISSUE THREAD

**Issue by andre2** [Eonasdan/bootstrap-datetimepicker#897]
How i can create event on select day, and change my button value display alert with current selected day.

<img src="http://i.imgur.com/riF2t2A.png?2">
After click "7" i want see alert with 07.03.2015

This is my html:

	<input type="button" id="change_date">

and js:

	$('#change_date').datetimepicker({
		format: "DD.MM.YYYY"
	});

how i can do this? ;)
nice plugin!

**Comment by Eonasdan** [comment]
you can listen for the `change.dp` event.

see the example here: http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers

**Comment by QsmaPL** [comment]
@Eonasdan Thanks! Work good :)

**Comment by rus0000** [comment]
Great datepicker!
This should be definitely in docs like this:
  $("#datetimepicker").on("dp.change", function (e) {
    console.log(e.date.format('YYYYMMDD'));
  });
