### ISSUE TITLE
Bower main and wiredep

### ISSUE THREAD

**Issue by oswaldoacauan** [Eonasdan/bootstrap-datetimepicker#899]
Why both javascript (minified and uncompressed) are listed as main files?

This can be a problem for people who are using wiredep for auto-inject dependencies, causing it to inject the script two times.

**Comment by Eonasdan** [comment]
why? Because I can't please everyone and other people were complaining about what got included.

I don't know anything about bower

**Comment by oswaldoacauan** [comment]
I suggest you keep as bower main files only one copy of each file (uncompressed ones). Something like:

```json
"main": [
    "build/css/bootstrap-datetimepicker.css",
    "build/js/bootstrap-datetimepicker.js",
    "src/less/_bootstrap-datetimepicker.less",
    "src/less/bootstrap-datetimepicker-build.less"
  ]
```

**Comment by legshooter** [comment]
:+1:

**Comment by Eonasdan** [comment]
Despite that I will likely get an influx of issues about how the packages don't contain everything, the next release will remove (again) the source files.

At some point, I'm just going to lock those files and like people deal with it...

**Comment by oswaldoacauan** [comment]
Using what i suggest will make #920 happy too, since what he is asking is to have a precompiled LESS files. I dont have any problem with that and actually i agree with it.

My only concern is having multiple javascript files (minified and uncompressed) listed as main.

**Comment by clabnet** [comment]
I agree oswaldoacauan suggest.
