### ISSUE TITLE
v4 update inline example

### ISSUE THREAD

**Issue by asebold** [Eonasdan/bootstrap-datetimepicker#901]
The current example of the inline option doesn't work. It appears the html markup is for a previous example (id is set to 'datepicker11' and the script calls '#datepicker12'). Please update with the correct html markup for this example.

**Comment by asebold** [comment]
Even though you fixed the id, I don't think the example includes the right markup. I tried the example in fiddle and it didn't work.

**Comment by Eonasdan** [comment]
please post the fiddle then

**Comment by asebold** [comment]
https://jsfiddle.net/1k22ga29/1/

**Comment by Eonasdan** [comment]
your fiddle doesn't include any of the required scripts, I don't know why you expected it to work.

http://jsfiddle.net/Eonasdan/q39LozLd/
