### ISSUE TITLE
Popup not visible (z-index issue?)

### ISSUE THREAD

**Issue by jmichaelterenin** [Eonasdan/bootstrap-datetimepicker#902]
If I provide a link, will that be sufficient? There's a lot of stuff going on in the vicinity of the date field, including a slider and sections of the form being moved and/or made visible. 

And the debug option seems to be no longer in the latest version, so I can't keep the "hidden" calendar from closing.

And I don't have any problem integrating jquery datetimepicker quickly and without problem, so I will probably use that.

**Comment by Eonasdan** [comment]
`debug:true` still keeps the picker open. A link or a fiddle or something...

**Comment by jmichaelterenin** [comment]
Not the version I got from bower, I promise! Even looked for a mention of it in the js. Anyways, I do have a pretty tight development schedule and I already had logic in place using the jquery datetimepicker, so I regretfully won't have time to recreate it on fiddle, my apologies.
