### ISSUE TITLE
Keyboard pops up on mobile

### ISSUE THREAD

**Issue by robwatkin** [Eonasdan/bootstrap-datetimepicker#903]
Mobile (android) keyboards popup and render the widget unusable or at least very confusing. I have tried the solution suggested in issue 848 but I wont work if there are two pickers on a page. Would it be possible to use the html5 datetime widgets instead as an option?

**Comment by Eonasdan** [comment]
there's a new option in the dev branch `focusOnShow` if set to false, it will not set the focus to the textbox
