### ISSUE TITLE
The defaultDate not working 

### ISSUE THREAD

**Issue by segi** [Eonasdan/bootstrap-datetimepicker#904]
I create a datetime popup with the next configuration, but the default date is not working properly because it doesn't set the month. Everything fine expect the month which is January every time.
``` javascript 
{
 sideBySide: true,
 format: 'DD MMM YYYY HH:mm',
 defaultDate: '11 20 2012 10:00',
 stepping: '15'
};
```
![2015-03-12_1832](https://cloud.githubusercontent.com/assets/1001383/6623963/9358fb0a-c8e6-11e4-8ab6-fecd0aa976ce.png)

**Comment by segi** [comment]
Ok, I found what cause the issue, there is a connection between the datepopup date format and defaultDate format. 
Everything is fine, when I print out the month with number, but it doesn't work If I try to print out with text. Here is my config:

```javascript
var startDate = moment();
startDate.format('D MMM YYYY HH:mm');
startDate.locale('en');
var calendarOptions = {
  sideBySide: true,
  format: 'D MMM YYYY HH:mm',
  defaultDate: startDate,
  stepping: '15',
  locale: 'en'
};
```

 The result as same as the previous comment. So the month is January

**Comment by Eonasdan** [comment]
I this from you screen cap that it doing this for you, however I don't have this issue with the latest code. Please post a jsfiddle of your issue

**Comment by segi** [comment]
Sorry, yes the code is working it was my fault. I defined the "new language" which cause the problem because the language was different for defaultDate and calendar.
So I close the issue.
