### ISSUE TITLE
Any way to limit time?

### ISSUE THREAD

**Issue by simPod** [Eonasdan/bootstrap-datetimepicker#905]
Hello, is there any way I can limit time? I found only minDate and maxDate for date limitations but nothing for timepicker. Thanks

**Comment by Eonasdan** [comment]
You can easily do this like so:

```
$('#datetimepicker1').datetimepicker({
    format: 'LT',
    minDate:moment({h:8}),
    maxDate:moment({h:18})
});
```

**Comment by simPod** [comment]
oh thanks.

I'm facinf this problem though:

```$('#datetimepicker1').datetimepicker({
    format: 'LT',
    stepper: 30,
    minDate:moment({h:8}),
    maxDate:moment({h:18})
});```

When 17:30 is selected, I can't get to 18. Is there anyway or is it a bug?

**Comment by Eonasdan** [comment]
```
    format: 'LT',
    stepping: 30,
    minDate:moment({h:8}),
    maxDate:moment({h:18, m:1})
```

**Comment by simPod** [comment]
Thanks! that works. I wish it would work when 17:30 is set that when I click to increment by one hour, 18:00 would be set. I suppose it's not implemented. I'd love to help to develop this but my JS skills are poor

**Comment by Eonasdan** [comment]
That would be counter-intuitive. Your users would not expect that to happen when they clicked that button.

Glad you got it working though
