### ISSUE TITLE
useCurrent:false is not working correctly

### ISSUE THREAD

**Issue by ArsenMkrt** [Eonasdan/bootstrap-datetimepicker#906]
with the useCurrent: false option, control does not select date in calendar on the first click.

Please refer to this jsfiddler  http://jsfiddle.net/o7jp9ob4/

How to reproduce
1. Open calendar
2. Select any date on calendar

Result
  Input shows selected date, but date stays un-selected on the calendar

Expected Result
   Date is selected on calendar

**Comment by Eonasdan** [comment]
Please check the development branch.

**Comment by ArsenMkrt** [comment]
Thanks a lot for all your work, will check...
