### ISSUE TITLE
How to limit date range and time range and the same time

### ISSUE THREAD

**Issue by simPod** [Eonasdan/bootstrap-datetimepicker#907]
Any way how to solve this? I found my question on stackoverflow asked by somebody else too http://stackoverflow.com/questions/28940527/how-to-limit-min-max-time-in-bootstrap-datetimepicker

Lets say I limit datetime picker for 8 to 18h from next Monday to next Sunday but I can select 22h on Wednesday because it's in range. Is it possible?

The only way I found was to separate it as a date and time picker, not datetimepicker. Thanks a lot

**Comment by Eonasdan** [comment]
Please check the dev branch
