### ISSUE TITLE
Document Events at http://eonasdan.github.io/bootstrap-datetimepicker

### ISSUE THREAD

**Issue by diosney** [Eonasdan/bootstrap-datetimepicker#908]
As title says, it will be very useful to have plain documentation of related events that the component may trigger.

I' m refering to those of the component, not the input related ones.

Diving into the code I found out those, which are built by means of the `notifyEvent` method.

```js
dp.change
dp.error
dp.hide
dp.show

**Comment by prionkor** [comment]
+1 Events need to be documented. I tried some of those before never worked for me. Probably I was doing something wrong.

**Comment by simPod** [comment]
+1 I agree too, had a hard time to find `dp.change`

**Comment by MageCoder** [comment]
How can i catch the datetimepicker changed event?
I tryed it this way:

element.datetimepicker(
                    {
                        locale: scope.locale
                    }
                ).on('change',function(){
                        alert('changed...');
                    }
                );

But it doesn't work.

**Comment by simPod** [comment]
Catch `dp.change`

**Comment by MageCoder** [comment]
THX

**Comment by josser** [comment]
This is probably not correct place to ask, but is there any way to handle 'month change' event?
I mean when user click 'next/prev' or get to next month by pressing arrows on keyboard.

**Comment by Eonasdan** [comment]
@josser please open a separate issue.

**Comment by Eonasdan** [comment]
oddly enough, I already had an events page on the docs, there just wasn't a link to it.
