### ISSUE TITLE
Adding official RTL option

### ISSUE THREAD

**Issue by legshooter** [Eonasdan/bootstrap-datetimepicker#910]
Hey,

It seems to me like that all that's missing for full RTL support is switching `.glyphicon-chevron-left` inside of `th.prev` with `.glyphicon-chevron-right` and vice versa.

Could be controlled by a `rtl: true` option.

This is very important for me, any chance for an implementation?

**Comment by Eonasdan** [comment]
couldn't you just change the icon option?

```
        icons: {
            next: 'glyphicon glyphicon-chevron-left',
            previous: 'glyphicon glyphicon-chevron-right',
        }
```

**Comment by legshooter** [comment]
You're right, missed that one.

We're still better off with an official RTL option, since building an application that fully supports RTL requires controling every plugin the app uses seperately, and instead of hacking and tweaking each plugin we use, a LTR/RTL option (which is very common in other plugins) is much easier to control and way more elegant.

Also, sepecifically for this plugin, it only makes sense. Since as I said, as far as I can tell the only thing missing from officially adding the "RTL support" title to this plugin, is this tiny tweak. In the future, if other tweaks are needed, they can all be added under the hood, for the RTL option.

Thanks a lot.
