### ISSUE TITLE
Version 3.1.3 manual

### ISSUE THREAD

**Issue by jacktric** [Eonasdan/bootstrap-datetimepicker#911]
Hello,

on a website I need to use the version 3.1.3 of datetimepicker.
I can't switch to new 4 version so where can I find the manual and documentation for version 3.1.3?

Thanks.

**Comment by Eonasdan** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/version3/

**Comment by jacktric** [comment]
Thanks a lot ... I didn't find the way :-)
