### ISSUE TITLE
useCurrent:false does not affects viewMode:'months','years'

### ISSUE THREAD

**Issue by mrigi** [Eonasdan/bootstrap-datetimepicker#912]
With useCurrent set to false it is expected to have nothing pre-selected/highlighted in any mode.
But this is not the case in 4.7.14.

jsfiddle: http://jsfiddle.net/0Ltv25o8/511/

**Comment by Eonasdan** [comment]
Please check the development branch.

**Comment by mrigi** [comment]
Seems done in dev. Thanks.
