### ISSUE TITLE
Detection of 24h format is invalid in some locales

### ISSUE THREAD

**Issue by olance** [Eonasdan/bootstrap-datetimepicker#914]
In France, we write time like this: 21h45, for 9:45 PM.
Hence I need the time picker to use 24h format and to display time with the Moment.js format `H[h]mm`.

The condition to automatically choose whether to use 24h format prevents me from doing so:

```js
    use24Hours = (actualFormat.toLowerCase().indexOf('a') < 1 && actualFormat.indexOf('h') < 1); 
```

Indeed, I do have a "h" in my format string although it does not mean anything as far as the actual time formatting is concerned!

**Comment by yboudjennah** [comment]
Hi olance : I'm french too, and I wrote this : 

                       $('#datetimepickerfin').datetimepicker({
                            format: "DD/MM/YYYY HH:mm"
                        });

Which gives me something like 18/03/2015 10:17... And, well, this one is globally used in France (as the 'h' is mostly used for handwriting) ;)

**Comment by olance** [comment]
Unfortunately that's not a compromise I was ready to go for, mainly because it's not my own project ^^

I just shamelessly patched the file and used ` use24Hours = true`. Too bad there's no way to force the option when the automatic behavior is not suitable.

**Comment by olance** [comment]
(actually I guess this issue could/should be addressed so let's not close it just yet!)

**Comment by Eonasdan** [comment]
Please check the development branch. `format` now allows `[h]` (or `[*]`).

**Comment by olance** [comment]
Thanks @Eonasdan sorry for the delay! ^^
