### ISSUE TITLE
Bootstrap columns are hardcoded to 12

### ISSUE THREAD

**Issue by sidonaldson** [Eonasdan/bootstrap-datetimepicker#915]
If you compile a custom bootstrap and change:
```
@grid-columns: 24;
```

The sideBySide layout breaks as: (~line 310)

```
$('<div>').addClass('row').append(dateView.addClass('col-sm-6')).append(timeView.addClass('col-sm-6'));
```

I would suggest adding an optional property to define the bootstrap column variable.

**Comment by sidonaldson** [comment]
for anyone wanting a CSS only fix you can use

```
.timepicker-sbs{
    .col-sm-6{
        width:50% !important;
    }
}
```

**Comment by Eonasdan** [comment]
I'll let people hack the css if they change the default behavior of bootstrap.

Thanks for the workaround
