### ISSUE TITLE
ASP .NET : locale not working

### ISSUE THREAD

**Issue by yboudjennah** [Eonasdan/bootstrap-datetimepicker#918]
Hello,

I'm using your Bootstrap 3 DateTimePicker with : 
 - ASP .NET (C#)
 - jQuery 2.1.3

My code is :

                <script type="text/javascript">
                    $(function () {
                        $('#datetimepickerfin').datetimepicker({
                            format: "DD/MM/YYYY HH:mm"
                        });
                        /*locale: 'fr'*/
                    });
                </script>

This one works well, but when I try

                <script type="text/javascript">
                    $(function () {
                        $('#datetimepickerfin').datetimepicker({
                            locale: 'fr'
                        });
                    });
                </script>

The calendar shows up but still in English.

Here are my includes in the Site.Master : 

                <asp:ScriptReference Name="MsAjaxBundle" />
                <asp:ScriptReference Name="jquery" />
                <asp:ScriptReference Name="bootstrap" />
                <asp:ScriptReference Name="respond" />
                <asp:ScriptReference Name="WebForms.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebForms.js" />
                <asp:ScriptReference Name="WebUIValidation.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebUIValidation.js" />
                <asp:ScriptReference Name="MenuStandards.js" Assembly="System.Web" Path="~/Scripts/WebForms/MenuStandards.js" />
                <asp:ScriptReference Name="GridView.js" Assembly="System.Web" Path="~/Scripts/WebForms/GridView.js" />
                <asp:ScriptReference Name="DetailsView.js" Assembly="System.Web" Path="~/Scripts/WebForms/DetailsView.js" />
                <asp:ScriptReference Name="TreeView.js" Assembly="System.Web" Path="~/Scripts/WebForms/TreeView.js" />
                <asp:ScriptReference Name="WebParts.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebParts.js" />
                <asp:ScriptReference Name="Focus.js" Assembly="System.Web" Path="~/Scripts/WebForms/Focus.js" />
                <asp:ScriptReference Name="WebFormsBundle" />
                <%--Scripts de site--%>
                <asp:ScriptReference Path="~/Scripts/moment.min.js" />
                <asp:ScriptReference Path="~/Scripts/bootstrap-datetimepicker.min.js" />
                <asp:ScriptReference Path="~/Scripts/bootstrap-datetimepicker.min.css" />
                <asp:ScriptReference Path="~/Scripts/modernizer-2.6.2.js" />
                <asp:ScriptReference Path="~/Scripts/moment-with-locales.min.js" />
                <asp:ScriptReference Path="~/Scripts/jquery-2.1.3.min.js" />

Plus, I'm not getting the same style as the one on the demo page, here is what I have : 

![calendrier1](https://cloud.githubusercontent.com/assets/11535296/6705644/3cc11870-cd57-11e4-8550-4e1aedfb5a60.png)

Is there any problem related to the files I include ? I have no idea why the options are not taken in consideration... (defaultDate doesn't work, sideBySide neither...)

Thanks by advance.

Yann B.

EDIT : I think this has nothing to see with anything else than my includes, since it works in a jsfiddle...

**Comment by Eonasdan** [comment]
you're including moment twice and jquery after all the other scripts, if I'm reading that correctly.

please look at your console to make sure there are no errors.

**Comment by yboudjennah** [comment]
I tried not including moment.min.js for just leaving moment-with-locales.min.js ans the datetimepicker just didn't appear.

And jquery is included at the very beginning of my ScriptManager... So in fact I removed my last jQuery declaration, which didn't change anything.

My console gives me three errors : 
 1. Syntax error, expected expression, got '.' - bootstrap-datetimepicker.min.css (at the first definition of .bootstrap-datetimepicker-widget)
 2. (Warning) getPreventDefault() is obsolete, use "defaultPrevented" instead
 3. No element found (5 times, with the same reference to "send:1:1", I don't even know what it is)

And no error in Visual Studio...

**Comment by yboudjennah** [comment]
Just to give some precisions : 
 - I have no idea what's the matter with getPreventdefault or defaultPrevented

But the fact is including moment-with-locales.min.js juste after moment.min.js made the display in French work (bootstrap-datetimepicker.min.css in very last)

I'm gonna try the default date and tell after how it's going. However, I'm not getting the selected date in a blue like it is on the demo page.

**Comment by Eonasdan** [comment]
you don't need both `moment-with-locales.min.js` and `moment.min.js`.

You probably are not include the css properly.

You need to get a base page working with the picker and add the rest of scripts/libraries to the page. The issues you are having are probably not the pickers issues.

**Comment by yboudjennah** [comment]
I know, the only issue I'm still getting now is the style one.

I have this now : 

                <%--Pour plus d'informations sur les scripts de regroupement dans ScriptManager, consultez http://go.microsoft.com/fwlink/?LinkID=301884 --%>
                <%--Scripts Framework--%>
                <asp:ScriptReference Name="MsAjaxBundle" />
                <asp:ScriptReference Name="jquery" />
                <asp:ScriptReference Name="bootstrap" />
                <asp:ScriptReference Name="respond" />
                <asp:ScriptReference Name="WebForms.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebForms.js" />
                <asp:ScriptReference Name="WebUIValidation.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebUIValidation.js" />
                <asp:ScriptReference Name="MenuStandards.js" Assembly="System.Web" Path="~/Scripts/WebForms/MenuStandards.js" />
                <asp:ScriptReference Name="GridView.js" Assembly="System.Web" Path="~/Scripts/WebForms/GridView.js" />
                <asp:ScriptReference Name="DetailsView.js" Assembly="System.Web" Path="~/Scripts/WebForms/DetailsView.js" />
                <asp:ScriptReference Name="TreeView.js" Assembly="System.Web" Path="~/Scripts/WebForms/TreeView.js" />
                <asp:ScriptReference Name="WebParts.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebParts.js" />
                <asp:ScriptReference Name="Focus.js" Assembly="System.Web" Path="~/Scripts/WebForms/Focus.js" />
                <asp:ScriptReference Name="WebFormsBundle" />
                <%--Scripts de site--%>
                <asp:ScriptReference Path="~/Scripts/modernizr-2.6.2.js" />
                <asp:ScriptReference Path="~/Scripts/moment-with-locales.min.js" />
                <asp:ScriptReference Path="~/Content/bootstrap-datetimepicker.min.css" />
                <asp:ScriptReference Path="~/Scripts/bootstrap-datetimepicker.min.js" />

I find it cleaner now indeed. My DateTimePicker looks like this now : 

![calendrier2fr](https://cloud.githubusercontent.com/assets/11535296/6712731/7efe816e-cd8e-11e4-8ee1-8da13074d257.PNG)

Did I miss the inclusion of a CSS file ? Since the jQuery seems to be working well.

**Comment by yboudjennah** [comment]
I'd just like to point the error I get in Console, with Chrome as well as with Firefox. The console reports a syntax error in file bootstrap-theme.min.css and bootstrap-datetimepicker.min.css.

It says : Uncaught SyntaxError: Unexpected token .

That's quite weird...

**Comment by yboudjennah** [comment]
I'd just like to point the error I get in Console, with Chrome as well as with Firefox. The console reports a syntax error in file bootstrap-theme.min.css and bootstrap-datetimepicker.min.css.

It says : Uncaught SyntaxError: Unexpected token .

That's quite weird...

EDIT : NEVERMIIIIIIIND
I just had to include my bootstrap-datetimepicker.min.css like this : 

    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap-datetimepicker.min.css" />

As otherwise it had been interpreted as a JS script file.

**Comment by andyxning** [comment]
@yboudjennah i have made the same mistake. :-(
