### ISSUE TITLE
No build provided on npm installation

### ISSUE THREAD

**Issue by ezecafre89** [Eonasdan/bootstrap-datetimepicker#920]
Hi guys, first of all, great job!

I'm trying to use the DatetimePicker with browserify. I found that you guys already published the package on npm. But when I do the install, I only get the src code.

Is this a bug on the distribution or is that the way you guys want to provide it?

Hopefully is a bug that you can fix, because I don't think build it on my project is something i can do in this case.

Thanks!

**Comment by Eonasdan** [comment]
it seems you npm/bower users can't decide what you want included in the package: #899.

Mostly, it's complaints about what it does or doesn't do.

I don't use bower or npm so I don't know anything about it.

**Comment by ezecafre89** [comment]
I agree that distribution is not something easy, and you can't please everyone.
But maybe, you can see what other libraries expose and do the same.

If you think about it, is not that crazy what i'm suggesting.
You are using Less as a preprocessor, i'm not (i'm using Sass actually).
In the way the Datepicker is being provided right now, i need to add a new dependency, and build your project on my build process. 
That's great... only if i want to modify your src.

Don't worry if you can't fix this. It was only a question/suggestion. 
Regards

**Comment by Eonasdan** [comment]
Despite that I will likely get an influx of issues about how the packages don't contain everything, the next release will remove (again) the source files.

At some point, I'm just going to lock those files and like people deal with it...
