### ISSUE TITLE
defaultDate for a div datetimepicker doesn't work

### ISSUE THREAD

**Issue by pakb** [Eonasdan/bootstrap-datetimepicker#921]
As there is no input with a div as a datetimepicker, the if test at line 1494 (in bootstrap-datetimepicker.js) isn't working properly. Here is a jsfiddle with this case (open up the console to see the err) : https://jsfiddle.net/xgkeq5y0/

You could change this line by something like that
```
if (options.defaultDate && (input.length === 0 || (input.val().trim() === '' && input.attr('placeholder') === undefined))) {
```
which will bypass further test on the input if there isn't one.
Sorry not to have done a pull request right away, I'm new to GitHub and wasn't able to push my changes on the dev branch...

**Comment by Eonasdan** [comment]
your fiddle doesn't load moment correctly.

If you paste your code into this fiddle: http://jsfiddle.net/Eonasdan/0Ltv25o8/ you'll see that it works

**Comment by pakb** [comment]
Sorry but it doesn't. Would it be a browser problem? I'm using Safari 8.0.4.
Here is a jsfiddle with the correct imports : http://jsfiddle.net/fu1evxb6/
If I run it, I still see today's date as the selected one in the date picker.
