### ISSUE TITLE
Help!  Change notifications?

### ISSUE THREAD

**Issue by jelion** [Eonasdan/bootstrap-datetimepicker#924]
I suspect this is "user error" but I can't find a public forum and I see a bunch of datetimepickers so I want to make sure I seek help from the right group of people.  I apologize in advance - if there is a better site for posting this sort of thing please refer me to it.

In short, I can't figure out what event to listen to in order to respond to input field change events.  I have a very nice date picker on my form where I can either type in the edit field directly or choose a date from the popup picker, and the form field gets updated.  But I can't seem to get any of my change event functions (which for now simply call ALERT) to fire.  I have tried doing $(#).change, $(#).on("event"), where # is both the input and the div, and event was change, dp.change, change.dp, changeDate, and changeDateTime.

I have HTML that is dynamically generated that ends up looking like this:
&lt;div class="form-group"&gt;
  &lt;div data-date-format="YYYY/M/D h:mm:ss" 
       data-date="1970/1/2 7:44:54"
       id="dp.timeobservedlong"
       class="input-group date form_datetime"&gt;
    &lt;input id="timeobservedlong" class="form-control" size="16" value="1970/1/2 7:44:54" type="text"&gt;
    &lt;/input&gt;
    &lt;span class="input-group-addon"&gt;
      &lt;span class="glyphicon glyphicon-calendar"&gt;
      &lt;/span&gt;
    &lt;/span&gt;
  &lt;/div&gt;
&lt;/div&gt;

Did I construct properly?  What event should I listen for?  Is the event listening function something I need to add to my constructor (which BTW is on the inner "div" (dp.timeobservedlong) with the following arguments {
format: "YYYY/M/D h:mm:ss",
defaultDate: "1970/1/2 7:44:54",
showTodayButton: true,
sideBySide: true
}

Thank you very much.

**Comment by Eonasdan** [comment]
look at the [linked pickers example in the docs](http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers) to see how to use the change event

**Comment by thebitguru** [comment]
I had a question related to this.  I noticed that [toggle function documentation](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#toggle) says `change.dp` instead of `dp.change` that the examples show.  Is that a mistake in the documentation?

**Comment by jelion** [comment]
Thank you for your reply.

The dp.change event - in fact, the linked pickers example - is not working for me in Firefox; though it could just as easily be user error as software problem.  Looks like the dp.change event is what I was after.

If I can come up with a better repro I'll write up a problem as a new issue.  Thanks for your help.  (leaving open to address the doc issue).
JKE
