### ISSUE TITLE
Not working on Safari Browser (MacOSX)

### ISSUE THREAD

**Issue by rodfersou** [Eonasdan/bootstrap-datetimepicker#926]

**Comment by Eonasdan** [comment]
...ok what I am supposed to do with that?

No description, no issue.

**Comment by rodfersou** [comment]
@Eonasdan man, you are pretty good in keep people away from your projects

No problem I don't need it anymore

**Comment by Eonasdan** [comment]
@rodfersou you have 24 repositories on github. what would you do if I open this issue on one of your repos?
