### ISSUE TITLE
Rogue CSS class ".sr-only" breaks LESS compatability?

### ISSUE THREAD

**Issue by InstanceOfMichael** [Eonasdan/bootstrap-datetimepicker#930]
In File:

https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/less/bootstrap-datetimepicker-build.less

```
// Import bootstrap variables including default color palette and fonts
@import "../../node_modules/bootstrap/less/variables.less";

// Import datepicker component
@import "_bootstrap-datetimepicker.less";


.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0,0,0,0);
  border: 0;
}
```

How important is the ``.sr-only``? I need to include this less file without including the default bootstrap variables. Shouldn't the ``sr-only`` be inside of the file ``@import "_bootstrap-datetimepicker.less";`` or have it's own file?

**Comment by Eonasdan** [comment]
`sr-only` is a bootstrap mixin/class. It was added our build file to make some LESS compilers work if it couldn't find the mixin from bootstrap.

**Comment by InstanceOfMichael** [comment]
Oh OK, I guess that should be commented in? I didn't think to check the blame button, maybe it's my fault lol.

**Comment by Eonasdan** [comment]
see also: #567

**Comment by Eonasdan** [comment]
I added a comment to the less file
