### ISSUE TITLE
defaultDate not working when inline and calendar pointing to a div as in example

### ISSUE THREAD

**Issue by zairnamlas** [Eonasdan/bootstrap-datetimepicker#932]
I tried defaultDate in inline mode on an input control it works fine but not on div. Then I tried to using input control but as the focus is out from the control the calendar hides (no more inline in that way).

**Comment by zairnamlas** [comment]
As I noticed that I have to wait for a fix, so I tried myself and fixed it.
Following is the fix

Replacing line 1492 in bootstrap-datetimepicker.js in function picker.defaultDate from
if (options.defaultDate && input.val().trim() === '' && input.attr('placeholder') === undefined) {

to 

if (options.defaultDate && (options.inline || (input.val().trim() === '' && input.attr('placeholder') === undefined))) {

Maybe this will help someone.

**Comment by Eonasdan** [comment]
I pulled in a PR last night that might have fixed this. Please check the dev branch

**Comment by Discartyptics** [comment]
I can confirm @zairnamlas 's fix works
