### ISSUE TITLE
Set input as readonly

### ISSUE THREAD

**Issue by mindware** [Eonasdan/bootstrap-datetimepicker#933]
Setting the input as readonly appears to completely disable the calendar. I would like to force the user to use the date-picker but be able to see the date in the readonly field as it is updated. Any tips?

Here's the jsfiddle:
http://jsfiddle.net/m2710d4n/

**Comment by Eonasdan** [comment]
A recently added option of [`ignoreReadonly`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#ignoreReadonly) was added to let you use the picker even with the disabled attribute

http://jsfiddle.net/Eonasdan/0y0bofoa/

**Comment by mindware** [comment]
Thank you. Works as expected.
