### ISSUE TITLE
stepping for minutes does not work sometimes

### ISSUE THREAD

**Issue by papagei9** [Eonasdan/bootstrap-datetimepicker#934]
I noticed, that sometimes, the stepping causes the datepicker to not completely initialize in connection with "minDate: moment().valueOf()"

I think it's because of the flooring/ceiling of the current minutes.

http://jsfiddle.net/u9msz57s/

**Comment by Eonasdan** [comment]
why are you trying to set the `minDate` to `valueOf` anyway?

**Comment by papagei9** [comment]
because I want to disable all past dates, but also would like to have a stepping of 5 minutes for easier usability.

**Comment by Eonasdan** [comment]
you don't need to use `valueOf()` just use `minDate:moment()`

**Comment by ashwinikr26** [comment]
I have disabled all past dates with time stepping of 5 minutes. I got some issue like, time will set to 12 PM 
date will not be selected and after that will not set back to current date/time.

If calendar is opened for few minutes and then I am getting this issue
