### ISSUE TITLE
Can't use both defaultDate and enabledDates

### ISSUE THREAD

**Issue by gabyshev** [Eonasdan/bootstrap-datetimepicker#935]
jsfiddle: http://jsfiddle.net/vupap2fv/
I want to restrict datetimepicker in only 1 day, and choose it as default.

error:

    Uncaught TypeError: defaultDate() date passed is invalid according to component setup validations

**Comment by yboudjennah** [comment]
Try using minDate and maxDate together maybe ?

**Comment by Eonasdan** [comment]
I'm not sure why the `defaultDate` won't work like that.

In the mean time, just use `minDate`, `maxDate`

**Comment by n0xic** [comment]
I have the same issue, although I have a few enabledDates passed, and I want to select one of them with the default date. I can't use minDate + maxDate in that case as it restricts my other enabled dates.

I get the same error as stated above obviously.

If you have some other workarounds for that situation, please let me know in the meantime!

<code>Uncaught TypeError: defaultDate() date passed is invalid according to component setup validations</code>

**Comment by gabyshev** [comment]
sorry, I used ```minDate``` and ```maxDate``` as a workaround

**Comment by talexand** [comment]
Does this work even without enabledDates? I am running into the same error passing in a Date object in an Ember app I am working on.

**Comment by Eonasdan** [comment]
please check the dev branch

**Comment by gabyshev** [comment]
@Eonasdan ok. Will check this evening

**Comment by gabyshev** [comment]
@Eonasdan http://codepen.io/anon/pen/PPzppw
In my case it's working correctly.

**Comment by CodingMinds** [comment]
Any news on this issue ? Or the date of the release of 4.17.42 ?
