### ISSUE TITLE
Modal form selected datetime value

### ISSUE THREAD

**Issue by Gino888** [Eonasdan/bootstrap-datetimepicker#936]
Hello, 

If i load the datetime picker in a bootstap 3 modal, the first time the date are selected in the date box. 

Then when i select a new date the old highlighted dates are still selected. 

 
Does anyone have any idea?

**Comment by Gino888** [comment]
sorry forgot the pictures: 
1st: 
![image](https://cloud.githubusercontent.com/assets/11613575/6780900/2aa0c608-d1bd-11e4-8e2d-aff8179c6311.png)

2nd: 
![image](https://cloud.githubusercontent.com/assets/11613575/6780909/41231ae8-d1bd-11e4-9021-033e17f3de01.png)

**Comment by Eonasdan** [comment]
hi @Gino888 can you setup a jsfiddle with your issue? You can use this as a primer  http://jsfiddle.net/Eonasdan/0Ltv25o8/

**Comment by Gino888** [comment]
ok i have done that
so press the button and you will see the correct date highlighted. Then
select a different date, close the modal, then reopen it. the previous date
is still selected.

**Comment by Gino888** [comment]
and let try that again with the new link:
http://jsfiddle.net/zcf90693/

**Comment by Eonasdan** [comment]
You're initializing the value and the datepicker inside of your openmodal function

http://jsfiddle.net/Eonasdan/zcf90693/1/

**Comment by Gino888** [comment]
Yep.
i have to. I left out most of the code. I do a ajax call to get data from
the server when i click on an event, then with knockoutJS i bind the date
time value to the to the control.

this date changes based on what date time value i selected. I'm opening
date time value from the calendar (http://fullcalendar.io/)

does this make sense?

**Comment by Eonasdan** [comment]
I'm not sure what you're expecting to happen then. In your code, you're setting the value and initializing the picker every time the modal gets opened.

if you're trying to get the date **after** the modal is closed and **before** it's reopened, you can do this:

`$('#groupSessionStartDateTime').data("DateTimePicker").date()`

You can also set the date that way `$('#groupSessionStartDateTime').data("DateTimePicker").date(DATEFROMFULLCAL)`
