### ISSUE TITLE
Event for view update

### ISSUE THREAD

**Issue by josser** [Eonasdan/bootstrap-datetimepicker#937]
Hi! 
It would be good to have ability track view updates by binding on some event like 'dp.view_updated' or just 'dp.update' which triggered every times user clicks next/prev or change view by keyboard events. 

IRL example: 

I have a datepicker where user can choose date of event, but actual list of dates available for picking is stored on server. I can't fetch them all, but I can fetch them for specific month. 
So If I'll have ability to bind on view change, I can fetch events every time user click next/prev for currently displayed month and than update enabledDates option. 

Thanks and sorry for my bad english

**Comment by josser** [comment]
I think this can be done by adding something like this to fillDate function:

```javascript
notifyEvent({
    type: 'dp.update',
    date: viewDate
});
```

But i'm not sure this is correct way

**Comment by Eonasdan** [comment]
Please check the development branch.
