### ISSUE TITLE
Trying to get current user locale

### ISSUE THREAD

**Issue by yboudjennah** [Eonasdan/bootstrap-datetimepicker#938]
Hello

I'm trying to adapt my calendar to the current user locale. I tried : 

    var userlocale = <%= GetCurrentCulture %>;
    $('#datetimepickerfin').datetimepicker({
        locale: userlocale,
        showTodayButton: true,
        defaultDate: moment({ h: 23, m: 59 })/*Heure par defaut : le jour même à 23:59*/
    });

But the calendar just doesn't show up.

I tried
 locale: navigator.language || navigator.browserlanguage

But I got the installation language of the browser, which doesn't help me as I have a multilingual web page and the datetimepicker still displayed in french although I have set the prefered language to german.

Anyone had the same thing ?

Yann.

**Comment by Eonasdan** [comment]
what does `var userlocale = <%= GetCurrentCulture %>;` actually render in the browser as?

the `local` must match one of Momentjs' local files
