### ISSUE TITLE
Disable picker for browser that support input type date

### ISSUE THREAD

**Issue by hpatoio** [Eonasdan/bootstrap-datetimepicker#939]
I want to disable the the picker if the browser supports `date` input type.

I know I can conditionally load it using `Modernizr` for the detection. But I'm wondering if there is a built in feature/option.

**Comment by Eonasdan** [comment]
no there's no built in feature other then maybe the `destroy()` function. This datepicker does **way** more then the browser dp so I don't see why this should be a feature.
