### ISSUE TITLE
Unable to Tab Forward when timepicker format includes AM / PM

### ISSUE THREAD

**Issue by garethdn** [Eonasdan/bootstrap-datetimepicker#940]
There was no reply to my comment on https://github.com/Eonasdan/bootstrap-datetimepicker/issues/822 so I'm creating a new issue.

Bug https://github.com/Eonasdan/bootstrap-datetimepicker/issues/822 can still be reproduced in the scenario where AM / PM is introduced into the timepicker format attribute. For example, 'h:mm A'

http://jsfiddle.net/wekedwjv/4/

**Comment by Eonasdan** [comment]
Please check the development branch.
