### ISSUE TITLE
Catch change event

### ISSUE THREAD

**Issue by GiankOtarola** [Eonasdan/bootstrap-datetimepicker#942]
Why I can't catch the change event if i use the datetime picker in a tab? If I use it in a simple div without a tab I can catch the event without problems. (Version 3.0)

Edit: the problem is on 
$('#datetimepicker').on('dp.change', 'td', function() {
        console.log("hello");
});
I can set the new date, but the event change doesn't fire, console doesn't print 'hello'.
Any solution?

**Comment by JohnHanks** [comment]
Can we have instructions for this for both V3 and V4?  If I can just implement in V3 I will, if I have to update to figure it out I will do so.  Examples would be great since the documentation is lacking somewhat.

**Comment by Eonasdan** [comment]
@GiankOtarola 

this should probably just be:

```
$('#datetimepicker').on('dp.change', function() {
console.log("hello");
});
```

if that doesn't work please provide a jsfiddle or a demo page

**Comment by Eonasdan** [comment]
@JohnHanks the docs are lacking? Seriously?

v3 docs: http://eonasdan.github.io/bootstrap-datetimepicker/version3/

Current: http://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by GiankOtarola** [comment]
@Eonasdan 
I tried like you said, but didn't work. Here are my demos.
With Tabs
http://plnkr.co/edit/AdyRI0G0S4PSylhcMaEx?p=preview

Without Tabs
http://plnkr.co/edit/Luf3Nc5iElCopE8UvnAG?p=preview

If the event is detected, it shows an alert.

**Comment by Eonasdan** [comment]
the link you sent me doesn't have the code to listen to the change event. looking at your previous revision, you have invalid code

this works just fine
```
 $(function () {
    $('#datetimepicker1').datetimepicker();
    $('#datetimepicker1').on('dp.change', function() {
        alert("change");
     });
});
```

**Comment by GiankOtarola** [comment]
It has, but  the codes to listen the change event are in the angular controller in script.js files. If you see, without tabs, works fine, but with tabs, doesn't work.

**Comment by Eonasdan** [comment]
other then `altert("change");` being wrong. I don't know what else to tell you. I don't know anything about angular. I'd suggest making sure everything else is spelled and referenced correctly. Sorry

**Comment by GiankOtarola** [comment]
I'ts ok. I did other solution, detecting the event when the input change.
Thanks @Eonasdan helping.

**Comment by iltera** [comment]
My issue was not using dp.change and insisting on using just "change" as an event listener. Using "dp.change" fixed my issues. Thank you @Eonasdan !
