### ISSUE TITLE
options specified in a field affect following ones?

### ISSUE THREAD

**Issue by kakipo** [Eonasdan/bootstrap-datetimepicker#943]
I have multiple datepicker fields, and one of them is specified  `viewMode` as `years` via `data-date-view-mode` attribute. 

```
<input type="text" class="form-control js-picker" />
<input type="text" class="form-control js-picker" data-date-view-mode='years' />
<input type="text" class="form-control js-picker" />
```

I thought the last one's `viewMode` would be `days` as default, but actually it was `years`.

Is this intended or just a bug?

Here's a fiddle.
[datetime picker base master - JSFiddle](http://jsfiddle.net/kakipo/0Ltv25o8/635/)
- bootstrap-datetimepicker: 4.7.14
- jquery: 2.1.0
- bootstrap: 3.2.0

You can workaround by applying `datetimepicker()` for each fields, but it may cause performance issues.

```
// workaround
$('.js-picker').each(function(){
   $(this).datetimepicker();
});
```

**Comment by Eonasdan** [comment]
the issue seems the that `data-date-*` is getting cross contaminated. I'm still looking into it, but your work around should be find for now

**Comment by mrdinghy** [comment]
if you use the fiddle and name each it resets to the defualt on the third input
<code>
$('.js-picker1').datetimepicker();
$('.js-picker2').datetimepicker();
$('.js-picker3').datetimepicker();
</code>
