### ISSUE TITLE
Updating daysOfWeekDisabled via options does not work

### ISSUE THREAD

**Issue by Pyppe** [Eonasdan/bootstrap-datetimepicker#944]
Updating `daysOfWeekDisabled` using the `options`-function does not work. See http://jsfiddle.net/Pyppe/hccLcc5m/1/ illustrating the issue.

**Comment by Eonasdan** [comment]
the fix will be to make `daysOfWeekDisabled` accept a bool of `false` to void the option

**Comment by Eonasdan** [comment]
Please check the development branch. Pass `false` to reset
