### ISSUE TITLE
Is it possible for this datetimepicker to work with Django?

### ISSUE THREAD

**Issue by awechsler** [Eonasdan/bootstrap-datetimepicker#945]
Hello, I'm in the middle of a project where we are trying to create a portal that includes an inline formset with the need of a date time picker. Since we are using crispy forms, it seems logical to find a date time picker built around bootstrap. I was wondering if anyone has been able to get this working with Django and if so could provide some tips, assistance? I probably should also mention that in addition to Django/Bootstrap the inline formset is using JQuery in order to dynamically copy specific fields.

Thanks
Alex

**Comment by Eonasdan** [comment]
There's a couple of django related things out there for this picker. I don't know if any of them are updated for the current version (4) or not.

I'm not very familiar with django so I don't know what the requirements are to make it work.

**Comment by awechsler** [comment]
I found this version but have been unable to get it working (django-bootstrap3-datetimepicker). If you know if any others I would appreciate the info... 
Thanks
Alex

**Comment by Eonasdan** [comment]
the last update to [this one](https://pypi.python.org/pypi/django-bootstrap3-datetimepicker-timepicker/) was for v3 of the picker. Perhaps you could fork that and update it? It might work with v4 of the picker if you update the options.

As I said, I don't know much about django so I'm afraid I can't help you to much. If you find one that's been updated for v4, please let me know
