### ISSUE TITLE
Being able to keep picker from ever hiding

### ISSUE THREAD

**Issue by Arwym** [Eonasdan/bootstrap-datetimepicker#948]
Right now, I have been unsuccessful at preventing the dp.hide event from happening. I am assuming that dp.hide occurs AFTER the picker has been hidden. Is  there any way to keep the picker ALWAYS open? Even after it loses focus? What I mean is, if it's not clear, I want the same behavior that we get when debug is set to true.

Thank you in advance.

**Comment by Eonasdan** [comment]
`keepOpen` will prevent it from hiding in all cases except for a blur. What's the reason for wanting to keep it open?

**Comment by Arwym** [comment]
Hello,

Thanks for replying. It is a client request. They want the picker to be visible at all times, even on blur.

**Comment by Eonasdan** [comment]
You could use `debug:true` and manually call the `hide()` function.

I think I'll change the functionality of `keepOpen` to do this in v5. I can't change it now as it would be a breaking change. It should be quite easy to make a modification on your end to support this in the meantime.

Change [Line 1122](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L1122) from `option.debug` to `option.keepOpen` (or if you want to keep debug `(option.debug || option.keepOpen)`

**Comment by Arwym** [comment]
Thank you very much. Changing this line produced exactly what I needed. :)
