### ISSUE TITLE
How to show a datetimepicker?

### ISSUE THREAD

**Issue by vandung2k6** [Eonasdan/bootstrap-datetimepicker#949]
Hi Guys,

I use 2 field input: <from> link <to>

I want show datetimepicker  of <to> after <from>  was hidden.

My code:
// <from>:#datetimepicker_from
// <to>: #datetimepicker_to

$("#datetimepicker_from").on("dp.hide",function (e) {
           //How to show datetimepiker of <to>
 });

How to?

Thanks so much!

**Comment by Eonasdan** [comment]
check the linked picker example in the docs http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers

**Comment by vandung2k6** [comment]
Great, thanks so much!
