### ISSUE TITLE
Quarter -Year date format

### ISSUE THREAD

**Issue by RaghavendhraK** [Eonasdan/bootstrap-datetimepicker#950]
It will be nice if we have the date picker to choose the dates with quarter-year format support.

Thanks,
Raghu

**Comment by Eonasdan** [comment]
I'm not sure I understand what you're asking

**Comment by RaghavendhraK** [comment]
That means we can have the quarters to select within the year. Like Q1-2013, Q2-2013, Q3-2013,....etc...

Like selecting the month and date in a year, we need to be able to select the quarterly year...

I hope you can get me now.

Thanks,
Raghu

**Comment by Eonasdan** [comment]
You could use the datpicker in years mode and have a second dropdown for Q1-Q4. 

Moment supports the concept of quarter so we might be able to do this. This probably won't make it into the next release 4.13.28 though.

**Comment by stevdom** [comment]
Is there any chance of adding this feature (quarter viewMode) in v5 (#841)?

**Comment by deltrotter** [comment]
Would love to see it as well.

Has anyone found a datepicker with quarters for Bootstrap?

Cheers

Del

**Comment by itsmejainh** [comment]
Would be great to have feature of selecting quarter and year from date-picker. 
Is this functionality still in plan ? 

thanks.

**Comment by BooleanType** [comment]
Agree with previous commentators. Could be great to be able to select quarters of year and weeks of month.
