### ISSUE TITLE
Missing 3AM from the timepicker

### ISSUE THREAD

**Issue by iforlife** [Eonasdan/bootstrap-datetimepicker#951]
Here is my setup:
$('#timeStart').datetimepicker({
        format: 'h A'
    });

![image](https://cloud.githubusercontent.com/assets/11709259/6887187/25af1440-d660-11e4-8a59-cf23a807238e.png)
![image](https://cloud.githubusercontent.com/assets/11709259/6887202/4eb01790-d660-11e4-969c-529a5ade2c3e.png)

**Comment by iforlife** [comment]
Go here: http://jsfiddle.net/Eonasdan/0Ltv25o8/
Open the first picker. 
Go to time picker. 
Switch to AM.
Click on the hours.

**Comment by Eonasdan** [comment]
it's there for me. I need more details, please. Browser, OS, time zone, locale

**Comment by iforlife** [comment]
Chrome - latest, Win8, (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius, locale - bg

**Comment by Eonasdan** [comment]
can you inspect element where the 3 is supposed to be and see what it does.

You'll need to turn `debug:true` on so that it doesn't close on you

**Comment by iforlife** [comment]
the td is not present at all. on each row there are 4 td, on the first one there are only 3

**Comment by Eonasdan** [comment]
have you tried the dev branch?
