### ISSUE TITLE
Seconds are missing?

### ISSUE THREAD

**Issue by vabatta** [Eonasdan/bootstrap-datetimepicker#952]
Hi all,

I was looking for a datetimepicker for bootstrap and I came here, but I don't see any information about seconds. Are they missing? Is possible to have them in the date picker?

Thanks and bye

P.s.: I read the old https://github.com/Eonasdan/bootstrap-datetimepicker/issues/65 but wasn't helpful...

**Comment by Eonasdan** [comment]
v4 use the `format` string to determine what components to show. See [momentjs' doc](http://momentjs.com/docs/#/displaying/format/) for valid tokens
