### ISSUE TITLE
Cannot select first enabled date when -> minDate: "now"

### ISSUE THREAD

**Issue by iforlife** [Eonasdan/bootstrap-datetimepicker#953]
Here is my setup:
$('#DueDate').datetimepicker({
        locale: 'bg',
        format: 'D MMM YYYY, ddd',
        ignoreReadonly: true,
        widgetPositioning: {
            horizontal: 'auto',
            vertical: 'auto'
        },
        minDate: "now", or new Date(), Date.now(), moment()
        showTodayButton: true,
        showClear: true,
        showClose: true,
        useCurrent: false,
        focusOnShow: false,
        debug: false
    });

minDate: new Date().setHours(0,0,0,0) -> WORKS

**Comment by Eonasdan** [comment]
This seems to work for me. Please provide a jsfiddle of your issue. You can use [this fiddle](http://jsfiddle.net/Eonasdan/0Ltv25o8/) as a base.
