### ISSUE TITLE
Should open with the set value or default value

### ISSUE THREAD

**Issue by akila1996** [Eonasdan/bootstrap-datetimepicker#954]
Whenever datepicker opens it should open with the currently set value or default date bt it is not doing it.

**Comment by Eonasdan** [comment]
please provide a jsfiddle of your issue

**Comment by akila1996** [comment]
http://jsbin.com/yoveru/39/edit
eg .If I have selected a date in april 25 and clicked the next button the calender will show may month.
If I just skipped it ,whenever the calender popup's i want it to open with the date selected (april 25 )or with the default date. but it is opening with the month may.

**Comment by Eonasdan** [comment]
you mean that when you select a date, change the view (to the month of May), close the picker, and reopen it that you want the view to go back to the selected date?

**Comment by akila1996** [comment]
yes.u r right

**Comment by Eonasdan** [comment]
because this may not always be the desired issue, I have created #959 as a RFC so that others can voice their opinion. Please keep track of this request there.
