### ISSUE TITLE
disabledTimeIntervals not working

### ISSUE THREAD

**Issue by darklomba** [Eonasdan/bootstrap-datetimepicker#956]
Whenever I try to use disabledTimeIntervals i get a "Uncaught TypeError: option disabledTimeIntervals is not recognized!" error. I'm using the example of the documentation, but it seems that the function is not inside the .js

disabledTimeIntervals: [[moment({ h: 0 }), moment({ h: 8 })], [moment({ h: 18 }), moment({ h: 24 })]]

**Comment by darklomba** [comment]
Sorry I forgot to provide the jsfiddle

http://jsfiddle.net/869w50wj/

Thanks!

**Comment by Eonasdan** [comment]
this is a new feature that in the dev branch at the moment.

I guess I need to make sure the docs indicate the version that applies to.

Once the dev branch has a chance to settle and I make sure I didn't introduce new blocking bugs, it will be pushed to main (probably another week or so).

**Comment by darklomba** [comment]
Thanks a lot. I got confused with the bootstrap-datetimepicker documentation.

**Comment by Eonasdan** [comment]
I've updated the docs (and hope to continue the habit) to mark which version number has a feature.
