### ISSUE TITLE
enabledDates option breaks viewMode: 'years' and viewMode: 'months'

### ISSUE THREAD

**Issue by mrigi** [Eonasdan/bootstrap-datetimepicker#957]
Two issues:

**1. viewMode: 'months'**

Arrows left/right are disabled even when years to the left and to the right have enabledDates values. I think there is no need to block these arrows at all regardless of enabledDates presence.

**2. viewMode: 'years'**

All years are disabled. Can't click anything.

jsfiddle:
http://jsfiddle.net/0Ltv25o8/648/

**Comment by Eonasdan** [comment]
mmm does this also happen on the dev branch?

**Comment by mrigi** [comment]
Yes, same issues on 4.13.28

**Comment by peda** [comment]
I have come around the same issue and narrowed it down a little bit:
updateYears() does call isValid() with a targetMoment - the day and month of the targetMoment are todays day and month. If it happens that todays day and month is in the enabledDates list everything is working fine. 
If this isn't the case all years are disabled. What isValid should do for the granularity === 'y' is the following: if there is at least one date of the given year in the enabledDates list it should consider it as valid and return true.

**Comment by Eonasdan** [comment]
the issue with making a change here is that if I set the `en/disabledDate` to only check if the granularity is on the day picker is that users will be able to select months/years that do not have any valid date in them.

I was going to try and check if the date was in between the start/end of the month/year but that's not going to work (at least not my first attempt)
