### ISSUE TITLE
datetimepicker and datatable plugin conflict

### ISSUE THREAD

**Issue by osuwariboy** [Eonasdan/bootstrap-datetimepicker#958]
I'm not sure if this is a problem with the datetimepicker or with jquery's DataTable plugin, but here goes (I've also posted it on the datatable forum, just to be sure). The thing is that I've been trying to put this plugin inside a DataTable's cell and the styles end up being a bit messed up. Here's a link to a fiddle demonstrating this issue:

http://jsfiddle.net/28675z97/

As you can see, the calendar part ends up being too wide for the allowed space.

**Comment by osuwariboy** [comment]
After a lot of digging, I was able to locate the problem inside this specific style:

table.dataTable  thead > tr > th {
	padding-left: 8px;
	padding-right: 30px;
}

Defined as it is, this style will drill down its padding to the datetimepicker's table... however, since this style is defined by the Datatable plugin, I'm closing this issue. To anyone wondering how I fixed it, here's what I did:

table.dataTable > thead > tr > th {
	padding-left: 8px;
	padding-right: 30px;
}

**Comment by rossinkiwi** [comment]
Thanks for finding this!  I fixed it by adding the following to my css:

    // Fix interference between jquery datatables and bootstrap datetimepicker
    table.dataTable.table-condensed .bootstrap-datetimepicker-widget thead > tr > th {
        padding-right: 0;
     }
    table.dataTable.table .bootstrap-datetimepicker-widget thead > tr > th {
      padding-right: 0;
    }

**Comment by chandragie** [comment]
Thank you for this, I know it had been solved quite long ago, but I found this today in my project and this is so helpful! Thanks.
I added this.

```
table.dataTable.table-condensed .bootstrap-datetimepicker-widget thead > tr > th {
    padding-right: 0;
    padding-left: 0;
 }
table.dataTable.table .bootstrap-datetimepicker-widget thead > tr > th {
  padding-right: 0;
  padding-left: 0;
}
```
