### ISSUE TITLE
Should the VewDate get reset back to the selected date on hide?

### ISSUE THREAD

**Issue by Eonasdan** [Eonasdan/bootstrap-datetimepicker#959]
When the picker widget gets hidden show the `viewDate` get reset back to the currently selected date?

As it stands now, if you navigate to the month or year view or use the `< >` arrows and close the picker, and reopen it, the `viewDate` will remain at the previous location.

![image](https://cloud.githubusercontent.com/assets/1006516/6943399/c5466fe2-d85b-11e4-90a6-7beddf291fdc.png)

To vote please use `+1` or `-1`

**Comment by tsjoberg** [comment]
+1 view date should be reset back to the original selected date

**Comment by akila1996** [comment]
+1

**Comment by jeremyVignelles** [comment]
+1, this is not top priority for be, but it could be nice to reset to the selected value.

**Comment by Eonasdan** [comment]
this is the development branch
