### ISSUE TITLE
maxDate ignores formatted future dates

### ISSUE THREAD

**Issue by PureMansWeb** [Eonasdan/bootstrap-datetimepicker#960]
When using a combination of the options 'maxDate' and 'keepInvalid' are used, the client side error handling is triggered when entering a date in the format 01012016, however if we enter a date in the format 01/01/2016, no client side error handling is triggered.

Html:

                                <div class="has-feedback form-group">
                                    <label class="col-sm-6" for="date_first_out">Date de 1ère mise en circulation <span class="biggest" style="color:red">*</span></label>
                                    <div class="col-sm-5">
                                        <div class="input-group date" id="date_first_out_picker">
                                            <input type="text" name="date_first_out" id="date_first_out" value="{$date_mec}" class="form-control" placeholder="jj/mm/aaaa">
                                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                        </div>
                                    </div>
                                </div>

JS:

        $('#date_first_out_picker').datetimepicker({
            locale: 'fr',
            format: 'DD/MM/YYYY',
            // Force today to end of day
            maxDate: moment().hour(23).minute(59).second(59),
            keepInvalid: true,
        });

**Comment by Eonasdan** [comment]
You're not providing a date in the format you said you were going to.

please provide a jsfiddle of this code

Pro Tip: you can use `moment().endOf('day')`

**Comment by PureMansWeb** [comment]
Thankyou for you rapid response and for your Pro Tip.

We have since discovered that the problems lies with our jquery validation methods and not with the Bootstrap DateTimePicker.
