### ISSUE TITLE
AM et PM

### ISSUE THREAD

**Issue by SimonBHB** [Eonasdan/bootstrap-datetimepicker#967]
Bonjours, j'utilise les date avec le format 24h:
$('#datetimepicker').datetimepicker({
	locale: 'fr',
	format: 'YYYY-MM-DD hh:mm:ss',
});

J'aimerais savoir si on peut désactiver l'affichage de PM et AM qui me sert à rien ? 
Merci

**Comment by n0xic** [comment]
Salut,

Essaye ceci à la place:

<code>
$('#datetimepicker1').datetimepicker({
    locale: 'fr',
    format: 'YYYY-MM-DD HH:mm:ss'
});
</code>

Le format 24h se fait avec les HH majuscules.

[JSFiddle] http://jsfiddle.net/0Ltv25o8/704/

**Comment by Eonasdan** [comment]
Se il vous plaît voir la chaîne de format sur le site de [momentjs](http://momentjs.com/docs/#/displaying/format/)

**Comment by SimonBHB** [comment]
Merci n0xic. Je pensais pas que c'était aussi simple, car je n'avais pas fait attention que l'heure était sous 12h vu que j'ai fait mes tests le matin^^

**Comment by houyewei** [comment]
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/962
same issue for chinese. i have submit the pull request

**Comment by houyewei** [comment]
My pull request but no feedback. https://github.com/Eonasdan/bootstrap-datetimepicker/pull/963
