### ISSUE TITLE
Linked Pickers issue with passing null dates

### ISSUE THREAD

**Issue by webcmsdesigns** [Eonasdan/bootstrap-datetimepicker#968]
If you are using linked pickers and enter a date, and then use the clear button, an error is thrown with minDate and/or  maxDate:

minDate() Could not parse date parameter: null
maxDate() Could not parse date parameter: null

This issue seems to persist in both the master and dev branches. Although the linked picker example in the docs does not use the clear button, you can reproduce the error by manually clearing the input after selecting a date (and selecting/tabbing to the next input)

http://jsfiddle.net/spasticdonkey/jwarn708/

**Comment by CallMeBruce** [comment]
@webcmsdesigns I too ran in to this problem, my workaround:
```javascript
$(function () {
	$('.datecontrol').datetimepicker();
	$("#dateSessionStart").on("dp.change", function (e) {
		if (e.date != null) { // <-- test for null to avoid TypeError
			$('#dateSessionEnd').data("DateTimePicker").minDate(e.date);
		}
	});
	$("#dateSessionEnd").on("dp.change", function (e) {
		if (e.date != null) { // <-- test for null to avoid TypeError
			$('#dateSessionStart').data("DateTimePicker").maxDate(e.date);
		}
	});
});
```

**Comment by Eonasdan** [comment]
I just pulled in PR #1080 which will change the `null` to `false`. Please check the dev branch

**Comment by Eonasdan** [comment]
the dev branch was pushed to the master, please check the latest
