### ISSUE TITLE
No way to disable the input but still be able to use the picker.

### ISSUE THREAD

**Issue by donnyv** [Eonasdan/bootstrap-datetimepicker#969]
Is there anyway to disable the input box but still be able to use the picker? I don't want users to be able to type anything in.

**Comment by Eonasdan** [comment]
use the [`ignoreReadonly`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#ignorereadonly) flag

**Comment by donnyv** [comment]
Ooooooooh...the only thing I would change is that when the "ignoreReadonly" is true that the picker icon is not grayed out.

**Comment by tsjoberg** [comment]
You would also have to set readonly attribute on the input field as well. The datepicker wont do that for you.
