### ISSUE TITLE
Set MaxDate

### ISSUE THREAD

**Issue by dalamar17** [Eonasdan/bootstrap-datetimepicker#970]
I have figured out everything except how to set the maxDate - what is the format for say 30 days ahead max? I can't figure out the documentation - not a programmer.

**Comment by Eonasdan** [comment]
`maxDate` takes a `moment` object so do `maxDate: moment().add(30 'd')`

**Comment by dalamar17** [comment]
that gave me a syntax error (and I did put a comma after the previous statement. How do I change the color to a basic white BTW? Is there a quick fix?

**Comment by Eonasdan** [comment]
please post a jsfiddle of your issue. there's a fiddle in the start page you can fork.

>basic white

what do you mean?

You can change whatever CSS you need

**Comment by dalamar17** [comment]
$(function () {
            $('#datetimepicker1').datetimepicker({
                viewMode: 'days',
                format: 'DD/MM/YYYY',
				minDate: new Date(),
				maxDate: moment().add(30 'd')    -   this line generates a syntax error in dreamweaver
            });
        });

**Comment by Eonasdan** [comment]
oops should have `maxDate: moment().add(30, 'd')`

**Comment by dalamar17** [comment]
ok cool - that worked. The last thing was the color - my default calendar has a black background but in your examples, its white. Do I need to dig into the CSS or is there some other setting I have missed?

**Comment by Eonasdan** [comment]
just change the css or less files to suite your needs
