### ISSUE TITLE
showTodayButton with maxDate today date doesn't work

### ISSUE THREAD

**Issue by Lodecesa** [Eonasdan/bootstrap-datetimepicker#971]
I have used ```moment()``` for ```maxDate``` but ```showTodayButton``` doesn't work
https://jsfiddle.net/Lodecesa/6nps786f/5/

You can try to use ```moment("today_string_format")``` in this code
https://jsfiddle.net/Lodecesa/6nps786f/6/
but the ```showTodayButton``` still doesn't work

**Comment by pcragone** [comment]
Take a look at my issue: I think it's the same problem
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/995

**Comment by Lodecesa** [comment]
It's possible.

Thanks.

**Comment by Silentspy** [comment]
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/995#issuecomment-108388511

**Comment by Eonasdan** [comment]
closing in favor of #995
