### ISSUE TITLE
Would like an option to set the number of visible weeks per month.

### ISSUE THREAD

**Issue by dsmeltz** [Eonasdan/bootstrap-datetimepicker#978]
An option to always show the same number of weeks when viewing a month.  Most months display 5 weeks, but February could be 4 weeks and some other months can be 6 weeks.  So when viewing Feb 2015, you would also have the last week of Jan 2015 and the first week of Mar 2015 showing.  
![fullfeb](https://cloud.githubusercontent.com/assets/1830600/7051817/dfef4a6a-ddf8-11e4-955a-9e356b9bec38.PNG)

When clicking through the months, and the number of displayed weeks changes, you have to keep moving the mouse, if the month view opens above the text box.

Obviously this is not a bug, just a nice to have.

**Comment by Eonasdan** [comment]
the dev branch has a fix to always show 42 days. please check the dev branch
