### ISSUE TITLE
v4 Does not work in IE8

### ISSUE THREAD

**Issue by JohnMcAvinue** [Eonasdan/bootstrap-datetimepicker#979]
I've just loaded our form which is using version 4.7 within IE8 and I'm getting an "Object doesn't support that method" JavaScript error.

I searched the issues and see some fixes for older versions. Is there any way to get this plugin working in IE8?

Thanks
John

**Comment by Eonasdan** [comment]
IE 8 is not supported. I've seen people post shivs, polyfills and fixes for it, but I don't have anything to test IE8 nor the time to hack the picker to make it work.

Where does that error occur?

Sorry. If you come up with anything I'm happy to add it to the docs.

**Comment by JohnMcAvinue** [comment]
Yeah that's fair enough - it should be obsolete but my clients demand that it be supported because 50% of their users are in government agencies and bodies who only have IE8. 

I'm not sure what line it's happening on as I'm using the minified version. I'll checked later and get back to you

**Comment by JohnMcAvinue** [comment]
Ok, good news from a reproduction point of view - you can reproduce it in IE11 running in IE8 mode in the develop console.

The error is "Object doesn't support property or method 'reduce'" in jQuery which is thrown on control initialisation:

var dateTimePickerOptions = {
    format: 'DD/MM/YYYY HH:mm',
    sideBySide: true,
    showClose: true,
};
$('.datetimepicker').datetimepicker(dateTimePickerOptions);

**Comment by Eonasdan** [comment]
ah. In that case, you can use this [Polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#Polyfill)

this is a what #836 was about

**Comment by francdore** [comment]
I get this error in IE8. Any idea how to fix it?

See screenshot here: https://francdore.tinytake.com/sf/NTI4Mzc3XzI3NjM3Mjg

PS. You can test using VirtualBox and then install a version of Windows using this: https://davidwalsh.name/free-ie-vms

**Comment by Eonasdan** [comment]
IE8 is not supported. There are several issues in the issue tracker about how to get IE8 to work or using polyfill or featurefills.

Other wise ask questions on StackOverflow
