### ISSUE TITLE
Glyphicon calendar is not open in correct position

### ISSUE THREAD

**Issue by ssathishkumar540** [Eonasdan/bootstrap-datetimepicker#981]
I am using Eonasdan bootstrap datetimepicker in paramquery grid. In starting I am facing one problem, If I open datetimepicker, the calendar is hiding inside the grid. When I give the css condition

.dropdown-menu {
    position: fixed;
}

it is working. The calendar is visible clearly but it is not open in a correct place. After given position:fixed If I click  picker icon, the calendar is open in right-top  of the grid or right-bottom of the grid. It is not open in an exact place. 

![isssss](https://cloud.githubusercontent.com/assets/10419324/7083378/a0baa556-df7e-11e4-9fef-3324fe3dc51e.png)

The issue is showed in the image. Please help me how can I resolve this issue?

**Comment by ssathishkumar540** [comment]
Please see the below fiddle, Please help me here how can I do?

http://jsfiddle.net/rtzxsa3e/14/

In this fiddle glyphicon calendar is not open in a correct position. It is always open in left corner.

**Comment by Eonasdan** [comment]
there was a PR to the dev branch recently that might help you. Please check the dev branch and let me know if that makes a difference

**Comment by ssathishkumar540** [comment]
I am using Bootstrap 3 datetimepicker inside the paramquery grid. Normally it is working fine. But inside grid its not working. Please see the fiddle. The calendar is hiding inside the grid. Sometimes I can't able to pick time. In this fiddle please open the 5th or 6th row calendar. Then you will see the issue. Here how can I do this? Please help me.

**Comment by Eonasdan** [comment]
there was a PR to the dev branch recently that might help you. Please [**check the dev branch**](https://github.com/Eonasdan/bootstrap-datetimepicker/tree/development) and let me know if that makes a difference.

**Comment by ssathishkumar540** [comment]
Yeah I tried this. Calendar is open. But it is not visible fully. I can't pick date. It is like this.
![12](https://cloud.githubusercontent.com/assets/10419324/7116899/b9b38d20-e212-11e4-9601-2215b4dbe0de.png)

**Comment by ssathishkumar540** [comment]
And one more issue I am facing. Without clicking anywhere while scrolling down, the calendar is closed. This problem also inside the grid only. If it is outside the grid or toolbar means it is working fine.
