### ISSUE TITLE
disabledTimeIntervals still not working

### ISSUE THREAD

**Issue by TawreCZ** [Eonasdan/bootstrap-datetimepicker#982]
Hi, at first I mention that I have development version. That is resolved in issue #956 

When I try it, It doesn't work in that way I can still choose disabled hours.

So I updated fiddle from mentioned issue to the development version. http://jsfiddle.net/869w50wj/4/

I there something what I miss or it is just a bug?

**Comment by vdomah** [comment]
Also tried to use dev branch with disabledTimeIntervals. Error about this option disappeared but hours are still all available to pick.

**Comment by suganthanraj** [comment]
I have use disabledTimeIntervals options. still i got error in console as options disabledTimeIntervals is not recognized!. This options still is in use or it is depreciated. Can anybody guide me how to make it as work?
