### ISSUE TITLE
Cant set custom change events on input element

### ISSUE THREAD

**Issue by cookiecavekeeper** [Eonasdan/bootstrap-datetimepicker#983]
I have an application in place that tracks changes to a form with the `change` or `focusout` events on all input elements.
But upon including this Datetetimepicker all custom `$(':input').on('change'` events were broken.

Now I know that there is a `dp.change` event, but I cant possibly add that as an additional event to all my listeners.

I tracked this down the [following lines:](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L1115)
```js
e.stopImmediatePropagation();
return false;
```
When I comment them out everything works as expected!

[JSFiddle](http://jsfiddle.net/hha0oLoj/1/)

**Comment by Godrules500** [comment]
I second this issue. It's causing parts of my program to now fail.

**Comment by jrochelle** [comment]
I am handling this situation in my application by doing the following:

$('.datetime-picker')
            .datetimepicker()
            .on('dp.hide',function (e) { 
                $(e.target).trigger('change');
        });

So when the user has made a final selection of a date, when the calendar ui component is hidden, the onchange event will fire as usual.

**Comment by alltonp** [comment]
+1

Thank you jrochelle for the work around, but it would be preferable for the events to propogate (even if it is just a config option)

**Comment by anotherstarburst** [comment]
The fix by @jrochelle doesn't seem to work for me... I've tried with the j
