### ISSUE TITLE
How to disable dates before today

### ISSUE THREAD

**Issue by niranjans** [Eonasdan/bootstrap-datetimepicker#986]
Is it possible to provide some kind of range in the `disabledDates` option. For example, if we want to disable all dates in the past. I tried to look for info regarding this in the docs or the issues but couldn't find any.

**Comment by Eonasdan** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#minmaxdate

**Comment by niranjans** [comment]
Ahh yes, sorry I missed that. I appreciate your help and thanks for the package.

**Comment by dotnetqueries** [comment]
we can easily disable past days by using the minDate function..

`$('#datetimepicker').datetimepicker({ minDate: new Date() });`

you can find the example in the below link
http://www.dotnetqueries.com/Article/105/bootstrap-datetimepicker-disable-past-dates
