### ISSUE TITLE
How to disable time

### ISSUE THREAD

**Issue by orca123** [Eonasdan/bootstrap-datetimepicker#988]
i use this script not work...pls help

$(function () {
                $('#datepicker1').datetimepicker();
				format: 'DD.MM.YYYY'
            });

**Comment by Eonasdan** [comment]
works just fine for me, please provide more details. OS, browser and a jsfiddle of your issue

**Comment by linuxthink** [comment]
Try putting the format as the parameter of datetimepicker() function, such as
`$('#datetimepicker1').datetimepicker({ format: 'DD.MM.YYYY' });`

**Comment by Eonasdan** [comment]
oh! nice catch @linuxthink
