### ISSUE TITLE
Cant view value in the edit form 

### ISSUE THREAD

**Issue by Frank004** [Eonasdan/bootstrap-datetimepicker#990]
Hi im using this in my rails 4 app
If I use the datepicker on the form in the edit part the value of the date field is empty and the datepicker is not selected with the value date form the database.
If need any more info let me know. thanx

```
<div class="form-group">
      <label for="datetime">Fecha</label>
      <div class="input-group date" id="datetimepicker2">
        <input class="form-control" value="2014-02-14 13:47:00" type="text" name="training[date]" id="training_date">
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
    </div>
```

![screen shot 2015-04-13 at 2 35 11 pm](https://cloud.githubusercontent.com/assets/7242689/7122561/5c774f34-e1ea-11e4-8eff-93c20b20ec26.jpg)

**Comment by Eonasdan** [comment]
where's the javascript for the picker?

**Comment by Frank004** [comment]
on my application.js
```
$(function () {
    $('#datetimepicker2').datetimepicker({
        locale: 'es',
        format: 'DD/MM/YYYY h:mm a',
    });
});
```

**Comment by Eonasdan** [comment]
your format string is not the sames as the textbox values'. Use `extraFormats`, change the dp's format or change the textbox value format

**Comment by Frank004** [comment]
![screen shot 2015-04-13 at 2 44 25 pm](https://cloud.githubusercontent.com/assets/7242689/7122792/a14344c8-e1eb-11e4-8b05-5ec1fc986c4b.jpg)


you can see that the date is not selected in the datepicker or the text_field

**Comment by Frank004** [comment]
ok ill check that out and let you know

**Comment by Frank004** [comment]
Thank it works I dnt see that. :+1:

**Comment by Eonasdan** [comment]
np glad you got it working

**Comment by Frank004** [comment]
Just another issues that I encontre is that if I have this value: 2015/04/22 09:59 am  on the view i get 2015/04/22 09:59 am  but if I go and edit it I get 2015/04/22 12:59 am

**Comment by khacluan** [comment]
:+1:

**Comment by sanjusoftware** [comment]
@Frank004 can u help me understand what you ended up making your settings looks like, which made it work for you. I am still not able to display my date on the edit form. 

Following is how I see the HTML with a date being displayed in my edit form:

```
<input class="form-control date-time" type="text" value="2015-09-14 05:44:00 UTC" name="talk[starts_at]" id="talk_starts_at">
```
and following is my application.js

$('.date-time').datetimepicker();

In my controller I have following to store the date submitted from the form:

```
def talk_params
      valid = params.require(:talk).permit(:topic, :details, :starts_at, :duration, :event_id, :tag_list)

      date_format = '%m/%d/%Y %I:%M %p'
      offset = DateTime.now.strftime('%z')
      valid[:starts_at] = valid[:starts_at] != '' ? DateTime.strptime(valid[:starts_at], date_format).change(:offset => offset).to_s : valid[:starts_at]
      valid
end
```
please help me also resolve this. 
Many thanks

**Comment by Frank004** [comment]
@sanjusoftware  Hi sorry for the late replay I endup doing this:

     <%= f.text_field :start_date, class: 'form-control', :value => (@varible.start_date.blank? ? '' : @varible.start_date.strftime('%d/%m/%Y'))  %>

so if I have a value in the column it will display in the field.

**Comment by pablougas** [comment]
Thanks Frank, that worked!
