### ISSUE TITLE
showClear don't working

### ISSUE THREAD

**Issue by JDittmerCOM** [Eonasdan/bootstrap-datetimepicker#992]
If my JS file showClear to true is set, no corresponding icon is displayed.

**Comment by Eonasdan** [comment]
works for me. Please provide a jsfiddle of your issue

**Comment by JDittmerCOM** [comment]
Now it works for me also, Funnily enough.
Earlier it looked at me (now also), only it did not work before. But okey. Thanks for the quick feedback.

// DATETIMEPICKER [start]
$(function () {
    $('#posts_createapi_datetimepicker').datetimepicker({
    	format: 'DD.MM.YYYY HH:mm',
    	showClear: true
    });
});
// DATETIMEPICKER [end]
