### ISSUE TITLE
random timestamp and incomplete date

### ISSUE THREAD

**Issue by EkaCreativeSolutions** [Eonasdan/bootstrap-datetimepicker#994]
HI,
I inizialize datetimepicker =>
$('#time').datetimepicker({
	locale:'it',
	format:'LL',
});
when stamp a log of dp.change, get random timestamp, and date._d is correct, but when i get value from FORM input, this value is incomplete. Value get from Input is "13 aprile 2015" for example.
How i can get correct format date, for manipulating server side?

Sorry for my english.
Thanks

**Comment by EkaCreativeSolutions** [comment]
After other test, i can get only a view format date.
i can get coplete date if get value manually with $(selector).data('DateTimePicker').date();
But not with jquery.serialize on form.
I suppose moment.js format date object containing in input value. Is true?
How can i get correct date, with jquery.serialize?

**Comment by Eonasdan** [comment]
if you call `.format()` on the date it will give a string

**Comment by EkaCreativeSolutions** [comment]
yes. but where use .format() ?
I set date in my custom function with $(selector).data('DateTimePicker').date(moment(datastring));
and in .on('dp.change'){
var value=$(e.target).data('DateTimePicker').date();
$(e.target).attr('value',value);
}
but it not work. date result always in format view plugin "13 aprile 2015" format:'LL' when i get value with jquery.serialize
