### ISSUE TITLE
Problems with maxDate

### ISSUE THREAD

**Issue by pcragone** [Eonasdan/bootstrap-datetimepicker#995]
Couldn't really come up with a more descriptive title.

So here's the scenario:

maxDate is set to tomorrow (it's currently April 13, 2015, at 2201 here in New York, so it's set to moment("4/14/2015").format()).  If you manually enter "04/14/2015" in the date field, you can then use the datepicker to select a different date, then go back in and you can select "04/14/2015".  All fine and dandy.

However, if you manually enter "04/14/2015" in the date field, then go in and click the "today" button, you can no longer select "04/14/2015" as a date, despite it being selectable (that is, not grayed out like 4/15, 4/16, etc. are).

Thoughts?

Currently debugging.

**Comment by pcragone** [comment]
Quite simple really.  The "maxDate" is not *really* a "maxDATE".  It's a maxDATETIME.  So If you set the max date as tomorrow - "04/14/2015" - you're really setting it to "04/14/2015 00:00:00".  And since the default time for a chosen date is right now, and right now is often after 00:00:00 in the morning, the isAfter check will always fail.  That is, selecting "04/14/2015" on the date picker is stating that your chosen date/time is actually, (if I do it right now) "04/14/2015 22:21:30", which is obviously after "04/14/2015 00:00:00", and so it is not considered a valid date.

Perhaps the isAfter check should ignore the time when comparing in the isValid method?

**Comment by Silentspy** [comment]
my solution to this problem was just setting maxDate to:

moment().startOf('day').add(1, 'days').subtract(1, 'seconds')

**Comment by Eonasdan** [comment]
please check the dev branch
