### ISSUE TITLE
If useCurrent is false, selected date highlight doesn't appear on first click

### ISSUE THREAD

**Issue by gardient** [Eonasdan/bootstrap-datetimepicker#997]
As the title says if you use `useCurrent: false` option on initialise the first click will select the date, but the highlight does not appear.

i made a fiddle with it if interested [fiddle](http://jsfiddle.net/gradient/oor9n4hL/)

**Comment by gardient** [comment]
Found the problem.
`unset` is changed after you call the `update` function in `setValue`.

just move it up one line and it works

**Comment by Dhrubaneel** [comment]
I have gone through the same problem but didn't understand the solution provided by you. I have made a solution for myself. It works.
<a href='http://jsfiddle.net/Dhrubaneel/a1rvtLw6/''>fiddle</a>

**Comment by gardient** [comment]
my solution is the one you would call modifying the plugin source [bootstrap-datetimepicker.js:Line726](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L726)
you move `unset = false;` before `update();`

the problem is that if date is 'unset' (even if you use `.date(null)` you can reproduce this) the `unset` variable is changed after you update the UI. So when the UI is being updated it still thinks that the date is unset (even tough it isn't).

**Comment by Dhrubaneel** [comment]
Ya got it. Its working like magic. Only thing is every time I download the updated file I need to make this modification, though only a small change. My solution was little lengthy.

**Comment by gardient** [comment]
well yeah, unless Eonasdan includes the fix into the next version

**Comment by ngandhy** [comment]
thx for the fix! 

I didn't see a pull request for the fix you have. Maybe that will get it in the next version.

**Comment by KarelCemus** [comment]
I confirm this resolved in **4.14.30**. Thanks for the fix.

**Comment by RameshBukka** [comment]
I am using datetimepicker library bootstrap for my application i was unable to highlight particular dates there is no option for that can any one help me for that its emergency....?
