### ISSUE TITLE
showClear and HTML Input text value

### ISSUE THREAD

**Issue by JDittmerCOM** [Eonasdan/bootstrap-datetimepicker#998]
When I click on the trash icon on my calendar, it is then also any way the he that HTML input empty text value?
Because in my case, the date always remains when you save an article.

And sorry for my bad english.

**Comment by JDittmerCOM** [comment]
Is there a way to remove the contents of the input at all in your plugin?
Because even through much around to try it would not work for me. Please, I need a quick response from you.

**Comment by Eonasdan** [comment]
just clear the text box with jquery

**Comment by JDittmerCOM** [comment]
I tried that several times. This works but only with an extra button.
I want this but that value by clicking on the trash can is emptied. Now I have the problems.

**Comment by JDittmerCOM** [comment]
And if I empty the TextBox with the button, the field is indeed empty, but in the live source, this is still always available.
http://fs2.directupload.net/images/150416/cc9h2o5y.png

**Comment by Eonasdan** [comment]
when I click the clear button it clears the text box just fine: http://jsfiddle.net/2keukdww/

**Comment by JDittmerCOM** [comment]
Okey, but with you there is box without a value. I must I use a value field.
And the value field is currently my absolute problem.

**Comment by Eonasdan** [comment]
nope. still works: http://jsfiddle.net/2keukdww/1/

**Comment by JDittmerCOM** [comment]
not really ..
![screenshot_2](https://cloud.githubusercontent.com/assets/11929467/7170461/9b8f5b0e-e3ce-11e4-8a7d-6f4578397d8b.png)

**Comment by Eonasdan** [comment]
http://jsfiddle.net/2keukdww/2/ clicking the button after clicking the clear button results in a empty alert.

**Comment by Eonasdan** [comment]
just get the date from the picker. it will return null `.data('DateTimePicker').date()`

**Comment by JDittmerCOM** [comment]
The message says that perhaps no more results exist, but I'm working with me mainly with PHP. And form I do save my HTML with PHP in my database and not using jQuery or similar.
And when retrieving the specific post he gets ID, also the date from (everything with PHP). But as soon as I delete the date with your plugin, a result in the live source is still...

**Comment by JDittmerCOM** [comment]
so, I found a solution though by chance. I would like to but like then always have by clicking on the trash, delete the value result.
Is there a way to insert this into your DateTimePicker JS file maybe?
![screenshot_3](https://cloud.githubusercontent.com/assets/11929467/7170640/4aecc7ac-e3d0-11e4-9add-19bbc1a51f9b.png)

**Comment by Eonasdan** [comment]
it's not an issue with my plugin: http://jsfiddle.net/7b2pwvL2/

if you click the button, it sets the input val to `''`, if you inspect the input with chrome, the value still shows

**Comment by JDittmerCOM** [comment]
Why can it not also so work?
The Trash button is <a data-action="clear">...</a> or not?
http://jsfiddle.net/2keukdww/3/

**Comment by JDittmerCOM** [comment]
why you closed the issue? ..
